### ISSUE TITLE
Running node Sample on BeagleBone Black (Debian)

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#100]
In the section that reads:

_Open a shell (Linux) or Node.js command prompt (Windows) and navigate to the folder you placed the sample files in. Then run the sample application using the following commands:_

_npm install_
_node ._

I ran this on both an Ubuntu system and a BeagleBone Black running Debian. On Ubuntu I didn't encounter any problems. However on the BeagleBone Black I was presented with:

_root@beaglebone:~/azure-iot-sdks/node/device/samples# npm install_
_npm ERR! Linux 3.8.13-bone79_
_npm ERR! argv "node" "/usr/bin/npm" "install"_
_npm ERR! node v0.12.7_
_npm ERR! npm  v3.3.8_

_npm ERR! No compatible version found: azure-iot-device@^1.0.0-preview.4_
_npm ERR! Valid install targets:_
_npm ERR! ["1.0.0-preview.3","0.0.1","0.0.1-preview.3"]_
_npm ERR!_
_npm ERR!_
_npm ERR! If you need help, you may report this error at:_
_npm ERR!     <https://github.com/npm/npm/issues>_

_npm ERR! Please include the following file with any support request:_
_npm ERR!     /root/azure-iot-sdks/node/device/samples/npm-debug.log_

Modifying the package.json file to read _"azure-iot-device": "^1.0.0-preview.3"_ circumvents this issue.

uname -a output:
_Linux beaglebone 3.8.13-bone79 #1 SMP Tue Oct 13 20:44:55 UTC 2015 armv7l GNU/Linux_

Sample successfully runs.

A little further research shows that my version of package.json on Ubuntu is already set to 1.0.0-preview.3. Since I only downloaded this one day prior to testing on the BeagleBone this might be the result of a recent change.

**Comment by dcristoloveanu** [comment]
There was a mishap in releasing our latest npm packages on our last release.
We have since then fixed this and uploaded the new npm packages.
Can you try this again and if it works, close the issue?

Thanks,
/Dan

**Comment by tameraw** [comment]
npm packages were released. Closing this issue, but please reopen if still having problems with this.
