### ISSUE TITLE
[Browser, MQTT] Connection forcibly shuts down / rejected

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-iot-sdks#1001]
I'm writing a lightweight wrapper / node.js module directly around `mqttjs/MQTT.js` for both node and browser. In both environments I'm able to successfully connect to the wss endpoint using the same code snippet as shown below, including using the same opts values. However the connection is being rejected when running in a browser environment. 

```javascript
  this.client = mqtt.connect('wss://' + this.opts.host + ':443/$iothub/websocket', {
    cmd: 'connect',
    protocolId: 'MQTT',
    protocolVersion: 4,
    clean: false,
    clientId: this.opts.deviceId,
    rejectUnauthorized: true,
    username: this.opts.host + '/' + this.opts.deviceId + '/DeviceClientType=' + versionString,
    password: this.opts.sas, 
    reconnectPeriod: this.opts.reconnectPeriod || 1000
  });

  this.client.connect();
```
I'm not receiving any errors on the client side, iothub-explorer is not logging any connection attempts.

**Comment by olivierbloch** [comment]
Hi
The Azure IoT Hub service doesn't support cross origin requests at this point. You can't establish the connection from a browser client.
We have this feature in the backlog but have mot prioritized it yet.

**Comment by 1N50MN14** [comment]
Appreciate for the quick response. Is it safe for me to assume this is something that is definitely on your roadmap? If so, then I will deploy a broker cluster as a temporarily solution until cors is supported.

**Comment by 1N50MN14** [comment]
@olivierbloch Any progress on this one?  AWS IoT supported this since January 2016 and my use case is to combine this with Azure Functions through IoT Hub triggers, which makes perfect sense...
