### ISSUE TITLE
[Java] Incorrect packages in JCenter/Bintray leading to inconsistent behavior

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdks#1002]
Some IDEs, e.g. Scala developers using SBT, are commonly setup to look for packages also in **JCenter/Bintray**, other than **Maven Central**. In this case some developers will experience odd SDK behavior, because the versions published are not consistent. 

For instance, it took several hours to debug an issue that was affecting only Scala (missing classes loaded by `SSlEngineFacadeFactory`), to finally discover that Scala was pulling **iothub-java-service-client 1.0.10** from Bintray and using **Proton-J 0.12.2**, while instead Java was pulling from Maven Central and using **Proton-J 0.15.0**.

Please either remove the wrong packages or make sure they are always in sync. For instance you could publish only snapshots to Bintray, with a "-DEV" suffix (e.g. `iothub-java-service-client-1.0.10-DEV`).

* https://oss.sonatype.org/content/repositories/releases/com/microsoft/azure/iothub-java-client/iothub-java-service-client/1.0.10/iothub-java-service-client-1.0.10.pom

```xml
    <dependency>
      <groupId>org.apache.qpid</groupId>
      <artifactId>proton-j</artifactId>
      <version>0.15.0</version>
      <type>jar</type>
    </dependency>
```

* http://jcenter.bintray.com/com/microsoft/azure/iothub-java-client/iothub-java-service-client/1.0.10/:iothub-java-service-client-1.0.10.pom

```xml
    <dependency>
      <groupId>com.microsoft.azure.iot</groupId>
      <artifactId>proton-j-azure-iot</artifactId>
      <version>0.12.2</version>
      <type>jar</type>
    </dependency>
```

**Comment by tameraw** [comment]
@dluc - We'll look into removing the packages from JCenter & Bintray

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-java#17
