### ISSUE TITLE
Calling convention not explicitly declared in headers

### ISSUE THREAD

**Issue by paulmon** [Azure/azure-iot-sdks#1005]
The calling convention of the nuget libraries is __cdecl but it's not explicitly declared in the headers.  This means if the compiler option /Gd is not specified for msvc projects that there will by unresolved symbol errors because of the differing calling conventions.

**Comment by anporumb** [comment]
Hello @paulmon,

Our nugets (binaries)are produced with __cdecl convention. Our headers do not have the convention explicitly stated. We do not have nugets build with __stdcall convention.

Trying to use the nugets in a project with __stdcall convention will fail at link time.

There are several ways to advance this topic:
1) in the short term, I could recommend writing a workaround. This workaround is a passthrough layer that simply changes calling convention.
2) in the long term produce nugets that have both calling conventions in them. I would very much appreciate any constribution in this area, even as "advice" (how to pack two calling conventions in the same nuget).

Best Regards,
Andrei Porumb

**Comment by paulmon** [comment]
Yes. That's the problem.  The headers do not work in a build environment where __cdecl is not the default calling convention.  If you explicitly declare the library methods as __cdecl you don't need 2 libraries or 2 sets of headers.

**Comment by anporumb** [comment]
Got it! I will label this with "Enhancement". 

Thank you!

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-c#16
