### ISSUE TITLE
ErrorCode:DeviceNotOnline when invoking device method from DeviceExplorer to a MQTT device client

### ISSUE THREAD

**Issue by michael-chi** [Azure/azure-iot-sdks#1007]
I am testing Device Method with a C# client using M2Mqtt library. following this doucment:https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support
my client subscribes to the topic "$iothub/methods/POST/#".

When invoking device method from Device Explorer, I got error message ErrorCode:DeviceNotOnline even when my client is able to send events to IoT Hub. The error came out immediately after I click "Call Method" button (does not honor Timeout setting in Device EXplorer)

my client code:
            var deviceId = ConfigurationManager.AppSettings["deviceId"];
            var iotHubName = ConfigurationManager.AppSettings["iotHubName"];
            var iotHubUrl = $"{iotHubName}.azure-devices.net";

            var clientId = deviceId;
            var userName = $"{iotHubName}.azure-devices.net/{deviceId}";
            var password = ConfigurationManager.AppSettings["deviceSAS"];
            var publishPath = $"devices/{deviceId}/messages/events/";
            var subscribePath = $"devices/{deviceId}/messages/devicebound/#";
            
            var client = new MqttClient(iotHubUrl, 8883, true, null,null,MqttSslProtocols.TLSv1_0);
           
            var result = client.Connect(clientId, userName, password);
            var directMethodPath = "$iothub/methods/POST/#";
            client.MqttMsgPublishReceived += Client_MqttMsgPublishReceived;
            
            
            client.Subscribe(new string[] { directMethodPath }, new byte[] { MqttMsgBase.QOS_LEVEL_AT_MOST_ONCE });

**Comment by kreuzhofer** [comment]
+1

**Comment by don-noonan** [comment]
+1

**Comment by jasmineymlo** [comment]
Hi michael-chi,

I think you will need to append the api-version to the userName when the device connect.  Something similar to below:

username = this.iotHubHostName + "/" + this.deviceId +"/api-version=" + ClientApiVersionHelper.ApiVersionString;

where ClientApiVersionHelper.ApiVersionString = "2016-11-14"

Regards,
Jasmine

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-csharp#33
