### ISSUE TITLE
Running node Sample

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#101]
Typo in following line:
_Use the DeviceExplorer utility to observe the messages IoT Hub receives from the **simplesample_amqp** application._

I believe the bold lettering above should read **simple_sample_http**. There is not an amqp node device sample.

**Comment by dominicbetts** [comment]
@markrad thanks for pointing this out. A PR will be submitted shortly to fix this issue.

**Comment by tameraw** [comment]
Issue resolved. Please advise/reopen if you're still having issues. Thanks.
