### ISSUE TITLE
[C#][UWP] Can't get UWPSample to receive message 

### ISSUE THREAD

**Issue by Schwimo** [Azure/azure-iot-sdks#1012]
Hello,

I tried it with every C# sample but it is not possible to receive any messages.
My understanding: I thaught i receive the messages which are sent from the example?
I have the free IoT Hub running and entered the device connection string which was generated from the device explorer. I can also see the messages from the device explorer and I am able to receive messages sent from device explorer, but how is it possible to receive messages sent from the UWPSample?

Kind regards

**Comment by tameraw** [comment]
@Schwimo - 
- Run the UWP sample app in debug mode
- Send a message from DeviceExplorer to the UWP app
- Check the "Debug" output window. You should be able to see the message that you sent from DeviceExplorer.

**Comment by arturl** [comment]
@Schwimo, this scenario should work. A small C# repro would help us figure out what's wrong.

**Comment by Schwimo** [comment]
Sorry guys, at the time of writing I had a misunderstanding with IoT Hub. I thought it can work as a MqttBroker and I wanted to send device -> device Messages. The sample works! This can be closed / removed.
