### ISSUE TITLE
Microsoft.Azure.Devices.Client nuget packet v1.1.1: File not found exception due to a missing reference

### ISSUE THREAD

**Issue by jcsantamaria** [Azure/azure-iot-sdks#1014]
I am getting an FileNotFoundException due to a missing reference in Microsoft.Azure.Devices.Client.winmd.

The complete exception message is the following:

```
System.IO.FileNotFoundException was unhandled
Message: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Microsoft.Azure.Devices.Client.winmd
Additional information: Could not load file or assembly 'Microsoft.Azure.Devices.Shared.WinRT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

```

It occurs during a call to: eg.  await _deviceClient.SendEventBatchAsync(messages);

This exception does not occur if I reference the Microsoft.Azure.Devices.Client nuget packet v1.0.21 or v1.0.22.

It appears similar to issue #1009 but here the referenced assembly seems to be properly signed.

**Comment by olivierbloch** [comment]
Hi @jcsantamaria 
This defitnively seems related to issue #1009 .
@BertKleewein is working on a resolution and will update this issue when done.
Thanks

**Comment by BertKleewein** [comment]
@jcsantamaria, you're correct.  Similar to 1009 but not exactly the same.  For this issue, you can work around this by manually add a nuget reference to Microsoft.Azure.Devices.Shared, v1.0.2

**Comment by BertKleewein** [comment]
This is fixed in Microsoft.Azure.Devices v 1.1.3 (if you're using the service SDK) and Microsoft.Azure.Devices.Client v  1.1.2 (if you're using the device SDK).  I'm going to close this issue for now, please re-activate (or open a new issue) if you still have problems.
