### ISSUE TITLE
Create Java sample from scratch - document is very unclear

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#102]
I was trying to follow along in creating a Java client from scratch, but the page was unclear enough that I wasn't able to follow along.  The confusion starts at this point:
Create application

It starts showing snippets of code, but doesn't mention where they should be placed.  Should I have created a new project in Visual Studio, or just be using notepad?
Once I've added these lines and modified them to include my own connection strings will this code run as is?  It doesn't look like it would.  Whole sections of this sample seem to be missing.

Finally, if all the code was now in a .java file, no instructions are mentioned about a command line that should be used to build the file and turn it into a .jar file.

**Comment by dominicbetts** [comment]
@jtanner-msft I've completely re-written this doc. Submitting a PR so the new version shoud be there soon.

**Comment by tameraw** [comment]
Issue resolved. Please advise/reopen if you're still having issues. Thanks.
