### ISSUE TITLE
Node SDK sendEventBatch fails with "sendEventBatch is not a function" when using mqtt

### ISSUE THREAD

**Issue by briancr-ms** [Azure/azure-iot-sdks#1020]
Calling Client.sendEventBatch using the node.js SDK (version 1.1.1) when the mqtt client is used fails with the following error:

TypeError: thisClient._transport.sendEventBatch is not a function

Expected:
- The call to work successfully

**Comment by pierreca** [comment]
@briancr-ms 
Batching has only been implemented in HTTP for now. 

To make the error clearer, I've added code that throws a more explicit `NotImplementedError`
https://github.com/Azure/azure-iot-sdk-node/commit/6c95bbb0543f73d6cb7d850f327d5a6784933e74

Thanks!
