### ISSUE TITLE
Issue #969 is not completely fixed: Twin is not imported in client.d.ts file

### ISSUE THREAD

**Issue by sharathbaddam** [Azure/azure-iot-sdks#1021]
../iot/node_modules/azure-iot-device/lib/client.d.ts(23,36): error
 TS2304: Cannot find name 'Twin'.
[13:40:56] TypeScript: 1 semantic error

Please add import statement in client.d.ts file

**Comment by anhashia** [comment]
Investigating. Link to #969

**Comment by anthonyvercolano** [comment]
Agree.  This should be fixed in the next release (in about 2 weeks).

**Comment by anhashia** [comment]
https://github.com/Azure/azure-iot-sdk-node/commit/1a1b2e68

**Comment by pierreca** [comment]
Fixed in the develop branch of new Node SDK repository: https://github.com/azure/azure-iot-sdk-node

Please consider switching to it when opening issues related to the Node SDK (we are still monitoring them here too)

Thanks!

**Comment by sharathbaddam** [comment]
Sure, thank you!
