### ISSUE TITLE
No azure-iot-sdk for objective c

### ISSUE THREAD

**Issue by naimskaria** [Azure/azure-iot-sdks#1023]
I am developing iOS app using objective c but i won't find any sdk natively for objective c. one sdk is for xamrin for c#. can any one help me to integrate this in objective c.

**Comment by naimskaria** [comment]
also please check ticket https://github.com/Azure/azure-iot-sdks/issues/771

**Comment by olivierbloch** [comment]
Hello.
There is work in progress happening in the C SDK repo: https://github.com/Azure/azure-iot-sdk-c/pull/5
I will close this issue and invite you to track this in the C SDK repository
Thanks
