### ISSUE TITLE
Having timeouts sending data with DeviceClient

### ISSUE THREAD

**Issue by goncalo-oliveira** [Azure/azure-iot-sdks#1026]
I'm having a few timeout issues trying to send data out to an IoT hub with the DeviceClient and I can't quite figure this out, so hopefully any of you might be able to help.

I've tried changing OperationTimeoutInMilliseconds, RetryPolicy, but still ended up with timeouts. Also tried  passing through AmqpTransportSettings into the instance creation method, with same results.

One thing that might be worth mentioning, is that this is being done in a proxy service, where devices communicate with the proxy and proxy communicates with the hub. There are multiple devices communicating with the proxy and the proxy is creating a DeviceClient per device, naturally.

Can anyone shine some light into this?

Cheers

**Comment by rajeevmv** [comment]
Can you provide more details?

1. Name of IoTHub and time window when this happened.
2. Client type/version used (C#, Java, Node etc).
3. Protocol used (Amqp over TCP? Amqp over WebSocket?).
4. Type of device credentials used by the proxy: were they device-scoped or hub-scoped?
5. How many devices were you trying to connect? was there a certain amount that worked and did it start to fail at some point? Can you describe the setup in more detail?
6. Does it fail when you are opening a connection or when sending telemetry data?

**Comment by tameraw** [comment]
Closing issue after checking with @goncalo-oliveira.
