### ISSUE TITLE
On Ubuntu 14.03 - Document should be re-ordered for setting up Java environment

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#103]
Currently the document has a note if you're running a version of Ubuntu prior to 14.10, but it's unclear from the instructions that you should re-run BOTH of the above commands to install Java again after the 'optional' command for the earlier versions:

If you are running a version of Ubuntu below 14.10, you will need to run the below command to add the respository containing openjdk-8-jdk to Ubuntu's list of software sources before attempting to use apt-get to install openjdk-8-jdk:
sudo add-apt-repository ppa:openjdk-r/ppa

I had tried just running 
sudo apt-get install openjdk-8-jdk

But needed to run:
sudo apt-get update
sudo apt-get install openjdk-8-jdk

before it worked.

Maybe you should put that note above the two commands so it's more apparent that it's needed earlier on.

**Comment by dominicbetts** [comment]
@jtanner-msft thanks for the suggestion. I've submitted a PR to make this change.

**Comment by tameraw** [comment]
Issue resolved. Please advise/reopen if you're still having issues. Thanks.
