### ISSUE TITLE
[java] send-receive-sample does not work with amqps

### ISSUE THREAD

**Issue by gemehendrix** [Azure/azure-iot-sdks#1032]
I've been trying to incorporate the azure iot device client java library into a piece of software I'm writing. It appears HTTPS is working ok but AMQPS and MQTT are not. I have tried the tokens I'm using with a simple C# program and it works fine.

I then tried using the sample applications provided to see if this was something I was doing. It appears the sample applications exhibit the same problem.

I tried running the 'sample-receive-sample' with AMQPS and get the follow errors in my output...

    Starting...
    Beginning setup.
    Successfully read input parameters.
    Using communication protocol AMQPS.
    Successfully created an IoT Hub client.
    Successfully set message callback.
    Opened connection to IoT Hub.
    Beginning to receive messages...
    Sending the following event messages:
    Updated token expiry time to 2400
    Event Message 0
    Press any key to exit...
    Lost connection to the server. Reconnection attempt 1...
    Lost connection to the server. Reconnection attempt 2...
    IoT Hub responded to message 0 with status MESSAGE_EXPIRED
    Lost connection to the server. Reconnection attempt 3...
    Lost connection to the server. Reconnection attempt 4...
    Lost connection to the server. Reconnection attempt 5...
    Lost connection to the server. Reconnection attempt 6...
    Lost connection to the server. Reconnection attempt 7...
    Lost connection to the server. Reconnection attempt 8...
    Lost connection to the server. Reconnection attempt 9...
    Lost connection to the server. Reconnection attempt 10...

Note the reconnection attempts. This is the same message I get in my own application. MQTT is different. I just don't get any responses. As I mentioned before, it's ok with HTTPS.

I have ruled out token and firewall issues by creating a separate C# program with the same parameters.

Please note, I am using a connection string in the following format...

    HostName=<hostName>;DeviceId=<deviceId>;SharedAccessSignature=<SharedAccessSignature>

Update: this works if I use a SASToken created from the device key. This problem only occurs when I use a SAS token created from the server key.

**Comment by prmathur-microsoft** [comment]
Can you please explain what does it mean by creating SAS Token from server key ? 
Azure IOT SDK for java currently only supports the following : 
1. Use device key in the connection string
2. Use SAS token in the connection string
Both of the above can be created using device explorer.
Please let me know more details about how you are creating SAS tokens to help me help you better.

**Comment by olivierbloch** [comment]
Hi @gemehendrix 
If by "Creating SAS Token from server key" you mean using one of the IoT Hub policies shared access keys (such as iothubowner), then you should NOT use this key to provision the device client. You should only use device id/key pair or SASToken generated from these to connect a device client.
This doesn't answer why you are seeing this difference in behavior when switching protocols, but can you please confirm that you are NOT seeing the issue when using a SASToken generated with a DeviceID/Key pair?

**Comment by anhashia** [comment]
Investigating !

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-java#13

**Comment by anhashia** [comment]
Hi @gemehendrix 
If you use Azure IoT SDK ( including Send and Receiver Sample), it should abstract all the SAS token generation details, You will just specify connection string in following format in send receive sample provided in the SDK.

``
HostName=<iothub_host_name>;DeviceId=<device_id>;SharedAccessKey=<device_key>
``

For AMQP connection (SASL PLAIN), you would need username and password.
This is covered in **detail** under
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security

Foer SASL PLAIN, username will change based on scope of the token as mentioned in the above  **documentation**.
*{policyName}@sas.root.{iothubName} will be used for IoT hub-level tokens.
*{deviceId}@sas.{iothubname} if using device-scoped tokens.

For connecting to specific device, you would normally use device specific token which is just scoped for that device. In this case username  and password will be as shown below  (**example**)
**username**:MyDevice1@sas.MyTestHub
**password**: SharedAccessSignature sig={**}&se=1484788914&sr=MyTestHub.azure-devices.net/devices/MyDevice1

Now are you are trying to use token with HUB level scope, you will have to set username and password accordingly.

**Comment by SalmanZubair** [comment]
I am facing the same issue. Using azure-iot-sdk for cloud to device command receiving sample app.
I am always getting this issue in the command receiving code:
Lost connection to the server. Reconnection attempt 1...
Lost connection to the server. Reconnection attempt 2...
Lost connection to the server. Reconnection attempt 3...
Lost connection to the server. Reconnection attempt 4...
Lost connection to the server. Reconnection attempt 5...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 7...
Lost connection to the server. Reconnection attempt 8...  

While using the sample java code provided on azure website: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-java-java-c2d
I provided connection string in the below format: 
"HostName="********.azure-devices.net;SharedAccessKey=device-key;DeviceId=****";
and protocol is AMQPS.

Note: D2C is working perfectly fine.

Can anyone help me with the issue.
 

Thanks.

**Comment by anhashia** [comment]
Hi @SalmanZubair 

For sending **C2D** message using Java Service client SDK you should use Azure IoT **HUB** level connection string. It should be of the format (example for reference)

``
HostName=MyTestHub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=***
``
Please test with HUB level connection string.

If you specify device level connection string using the SDK service client sample you should get a validation **error**

``
Exception in thread "main" java.lang.IllegalArgumentException: SharedAccessKeyName cannot be null or empty
``

Service client sample is covered under
https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-samples/service-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/service/sdk/ServiceClientSample.java

Validation check  for connection string in service client is covered under
https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/sdk/IotHubConnectionStringBuilder.java#L158

**Comment by SalmanZubair** [comment]
Hi @anhashia

Thanks for guiding me to the solution. The code is working fine for sending the command to device.
The major problem which I am facing is with the code receiving the command which is using Message call back.

This is the code which I am using for command recevier:

public class ReceiveCommand {

	private static final String connectionString = "Connection String ;" + DeviceId=*****";

	private static final IotHubClientProtocol protocol = IotHubClientProtocol.AMQPS;

	private static class MessageCallback implements
			com.microsoft.azure.iothub.MessageCallback {

		public IotHubMessageResult execute(Message msg, Object context) {
			System.out.println("Received message from hub: "
					+ new String(msg.getBytes(),
							Message.DEFAULT_IOTHUB_MESSAGE_CHARSET));

			return IotHubMessageResult.COMPLETE;
		}
	}

	public static void main(String[] args) throws IOException,
			URISyntaxException, Exception {

		DeviceClient client = new DeviceClient(connectionString, protocol);
		System.out.println(client.toString());
		MessageCallback callback = new MessageCallback();
		client.setMessageCallback(callback, null);
		client.open();
	}

}
I tried connection string using both device level and iothubowner.

But every time I am getting error:
Lost connection to the server. Reconnection attempt 1...
Lost connection to the server. Reconnection attempt 2...
Lost connection to the server. Reconnection attempt 3...


Thanks
Salman

**Comment by anhashia** [comment]
Hi @SalmanZubair 
You can use following **sample** as a reference
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceive.java

It also has Receive side. Below is the output by running this sample.
C2D message "Hello" was sent by Device Explorer tool for test purpose to the device.
Connection string is a **device connection string** that you can get using Device Explorer tool.

The argument for the sample would be something line this (as an example)
``
HostName=MyTestHub.azure-devices.net;DeviceId=MyDevice;SharedAccessKey=*** 1 amqps
``

```
Press any key to exit...
IoT Hub responded to message 1 with status OK_EMPTY
IoT Hub responded to message 0 with status OK_EMPTY
Received message 0 with content: Hello
Responding to message 0 with COMPLETE
```

**Comment by SalmanZubair** [comment]
Hi @anhashia 

I tried the above mention code but still getting same error:

Press any key to exit...
IoT Hub responded to message 0 with status MESSAGE_EXPIRED
IoT Hub responded to message 1 with status MESSAGE_EXPIRED
Lost connection to the server. Reconnection attempt 1...
Lost connection to the server. Reconnection attempt 2...
Lost connection to the server. Reconnection attempt 3...
Lost connection to the server. Reconnection attempt 4...
Lost connection to the server. Reconnection attempt 5...
Lost connection to the server. Reconnection attempt 6...

**Comment by gemehendrix** [comment]
I can confirm this was an issue with our SAS token. This has been resolved and we can connect via AMQPS without any issues.

**Comment by anhashia** [comment]
Hi @gemehendrix 
Thanks for the confirmation !

**Comment by anhashia** [comment]
Hi @SalmanZubair 

As per your latest log, looks like you are also not even able to send D2C cloud message successfully using the SDK send receive sample . I though you had D2C working. You are then subsequently losing connection to Azure IoT Hub leading to retry (reconnection attempt).

Anyway, can you please try following  (basically test with **HTTPS**) with **SendReceive** Java **sample**
``
HostName=MyTestHub.azure-devices.net;DeviceId=MyDevice;SharedAccessKey=*** 2 https
``

and see if you get the similar log or different log.

Also, if you are using older SDK by any chance, make sure you are testing with **latest available** SDK.
Latest available  IoT device client is **1.0.17**
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.microsoft.azure.sdk.iot%22

**Comment by SalmanZubair** [comment]
Hi @anhashia

Thanks a ton for ur help. I m able to receive command send using Device Explorer as shown in my log:

**Using communication protocol AMQPS.
Successfully created an IoT Hub client.
Successfully set message callback.
Opened connection to IoT Hub.
Beginning to receive messages...
Sending the following event messages: 
Updated token expiry time to 2400
Event Message 0
Event Message 1
Press any key to exit...
IoT Hub responded to message 0 with status OK_EMPTY
IoT Hub responded to message 1 with status OK_EMPTY
Received message 0 with content: 1/27/2017 4:17:32 PM - check
Responding to message 0 with COMPLETE**

But I have one question when I am sending the message to device using **ServiceClientSample** I am not able to receive that message using Send Receive code. 

Can you help me understand what wrong m doing here...??

**Comment by anhashia** [comment]
Hi @SalmanZubair 
Your should be able to send C2D using ServiceClient sample. Make sure you test with latest available SDK in case you are using older version. What is the  error that you are getting ?

Below are the log snippets for your reference

**C2D** using ServiceClientSample.java
```
------------------------------------------------------------------------
Building Service Client Sample 1.0.12
------------------------------------------------------------------------
********* Starting ServiceClient sample...
Creating ServiceClient...
```

**D2C** using SendReceive.java
```
IoT Hub responded to message 0 with status OK_EMPTY
IoT Hub responded to message 1 with status OK_EMPTY
Received message 0 with content: Cloud to device message ...
Responding to message 0 with COMPLETE
```

**Comment by SalmanZubair** [comment]
Hi @anhashia

I am not getting any error. 

Logs for C2D:

********* Starting ServiceClient sample...
Creating ServiceClient...
********* Successfully created an ServiceClient.
********* Successfully opened FeedbackReceiver...
********* Sending message to device...
********* Waiting for feedback...
********* Feedback received, feedback time: 2017-01-30T06:50:04.636929100Z
********* Successfully closed FeedbackReceiver.
********* Successfully closed ServiceClient.
********* Shutting down ServiceClient sample...


But this message is not received by SendReceive.java code.
I am using the latest version of SDK downloaded from below url.

**https://github.com/Azure/azure-iot-sdk-java**


Note:  ConnectionString for Service client code is in the format:
**HostName=*****.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=*******.**

I even tried the format for ServiceClient:
**HostName=*****.azure-devices.net;SharedAccessKey="devicekey".**


For SendReceive the format is: 
**HostName=*****.azure-devices.net;SharedAccessKey="devicekey".**

**Comment by SalmanZubair** [comment]
Hi @anhashia

It's working now thanks a ton for ur help and guidance.

Now I will be exploring Direct Method for the same.

If you have any info regarding this kindly share it with me.

Thanks
Salman

**Comment by anhashia** [comment]
Hi @SalmanZubair 
Thanks for the update !  Direct Method feature in work in progress for Java SDK.

**Comment by tameraw** [comment]
@SalmanZubair & @anhashia - Device Methods for Java is current a work-in-progress feature.
For the latest status, please find our project below highlighting the top prio feature for Java and their order of priority:
https://github.com/Azure/azure-iot-sdk-java/projects/1
