### ISSUE TITLE
IoT-Hub Explorer URL is not working

### ISSUE THREAD

**Issue by venkatapidikiti** [Azure/azure-iot-sdks#1033]
Hello,
The following link is not working and redirects to Page not found.
See Install iothub-explorer for more information.
Thanks

 

- SDK used when observing the issue: 
- Type of device: 
- OS (with version) on which the code is running 

Code sample exhibiting the issue: 

Console log of the issue:

**Comment by pierreca** [comment]
Hi @venkatapidikiti, it looks like you missed pasting the link you're talking about in your message ("the following link"?)

Please update the issue, there's not much for us to work with to understand your problem here

**Comment by tameraw** [comment]
@venkatapidikiti - Closing. Please feel free to file new issue and paste link to the document that contains the broken URL.. 
For issues related to iothub-explorer, please file in its repo at:
https://github.com/Azure/iothub-explorer
