### ISSUE TITLE
ReceiveMessageCallback works with sendeventasync only

### ISSUE THREAD

**Issue by sarangkalbande** [Azure/azure-iot-sdks#1034]
Hi All,
I am facing one issue with SDK,
My requirement is sendingTo and receiveFrom IOTHub should work independently.
But when I verify with sample code unless i send some message to IOT hub receive call back is not invoking.

how can we achieve this behavior using IOT hub client library calls?

**Comment by pierreca** [comment]
Which SDK are you talking about and have you considered opening the issue directly on that SDK github repository? 

- C:      https://github.com/azure/azure-iot-sdk-c/issues/new
- .NET:   https://github.com/azure/azure-iot-sdk-csharp/issues/new
- Node:   https://github.com/azure/azure-iot-sdk-node/issues/new
- Java:   https://github.com/azure/azure-iot-sdk-java/issues/new
- Python: https://github.com/azure/azure-iot-sdk-python/issues/new

**Comment by sarangkalbande** [comment]
This issue was for C SDK and I had posted in  C SDK repository also 
now my issue is resolved now.
