### ISSUE TITLE
Unable to Statically Link VC runtime (/MT, /MTd) in IoT Client Samples

### ISSUE THREAD

**Issue by don-noonan** [Azure/azure-iot-sdks#1036]
We need to be able to statically link the VC runtime for Win32 builds, however when attempting to do so we get ~50 unresolved external symbol errors like the following:

`Error	LNK2019	unresolved external symbol __imp____stdio_common_vsscanf referenced in function __vsscanf_l	iothub_client_sample_amqp_websockets	C:\AzureIoT\azure-iot-sdk-c\cmake\iotsdk_win32\iothub_client\samples\iothub_client_sample_amqp_websockets\iothub_client_amqp_ws_transport.lib(parson.obj)	1`

You can reproduce the errors by simply changing the Runtime Library setting in VS 2015 Configuration Properties > C/C++ > Code Generation > Runtime Libary.
For example, grab the sample iothub_client_sample_amqp_websockets and while in debug mode change the option to statically link the VC runtime by selecting Multi-threaded Debug (/MTd).

Sample Used:
iothub_client_sample_amqp_websockets

Development Environment:
Windows 10 Pro
Visual Studio Enterprise 2015 Update 3

Thanks for your help.

Don

**Comment by anporumb** [comment]
Hello @don-noonan,

I would assume there is a mismatch between your compiled libraries and your applications. They both need to match.

Did you recompile the libraries too, to have /MTd?

Best Regards,
Andrei Porumb

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-c#22
