### ISSUE TITLE
iothub-explorer instructions are not correct

### ISSUE THREAD

**Issue by remintz-acn** [Azure/azure-iot-sdks#1037]
on page https://github.com/Azure/azure-iot-sdks/blob/master/doc/manage_iot_hub.md

the instructions for creating a device using iothub-explorer are not correct.

**Comment by pierreca** [comment]
Looks like @neeraj-khanna fixed it with 7e492c6c228f24c337492d3144ccbbb0f89f01ff. 
I ran through the instructions and they seem correct now, feel free to reopen and add details if it's still not working for you.
