### ISSUE TITLE
Linux doesn't have .sln files

### ISSUE THREAD

**Issue by anporumb** [Azure/azure-iot-sdks#105]
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md#linux
mentions that Linux might get a .sln file. Linux has makefiles :)

"[...]and generates in that folder a Visual Studio solution called azure_iot_sdks.sln"

**Comment by dominicbetts** [comment]
@anporumb thanks for pointing this out. I'll submit a PR to correct this.

**Comment by tameraw** [comment]
Issue resolved. Please advise/reopen if you're still having issues. Thanks.
