### ISSUE TITLE
REST API is missing api for Cloud to Device message

### ISSUE THREAD

**Issue by henrikstromberg** [Azure/azure-iot-sdks#1051]
- SDK used when observing the issue: 
- Type of device: 
- OS (with version) on which the code is running 

Code sample exhibiting the issue: 

Console log of the issue:

**Comment by olivierbloch** [comment]
Hi @henrikstromberg 
The Cloud to Device operation is done over AMQP for bandwidth, performance and availability reasons. Our Service SDK abstract the complexity of using the AMQP interface and you can find more info in our [docs](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d)  as well on how to use them.

**Comment by tameraw** [comment]
@henrikstromberg - As this is not SDK related, can you please submit note in user voice at:
https://feedback.azure.com/forums/321918-azure-iot
Others will benefit from your request and can "up" vote it. Thanks.
