### ISSUE TITLE
Maximum payload size for Cloud to Device using Direct Method for all the available edition of IOTHUB

### ISSUE THREAD

**Issue by SalmanZubair** [Azure/azure-iot-sdks#1052]
Hi,

I am exploring Cloud to Device Communication using Direct Method (MQTT) on Azure IOTHUB. I have got a message whose size is around 800KB. Right now I am using free edition of Azure IOTHUB which is giving error:
**Failed to invoke method 'writeLine': 'payload' size should be less than 8192 bytes.**

I tried looking for the answer but was not able to find any.
Now I want some info which can explain what could be the maximum payload for different version of Azure IOTHUB.

And can someone suggest what could be the best possible way for achieving this.

Can we achieve this using Service Bus queue and topics..??

Thanks 
Salman Zubair

**Comment by olivierbloch** [comment]
Hi @SalmanZubair 
The max size for a Direct Method's payload is 8KB. The info is honestly not well documented and can be found on [this page](https://azure.microsoft.com/en-us/pricing/details/iot-hub/), scrolling down and expanding the "How are direct methods charged?" link. We have docs updates on the way that should allow to find this type of info more easily.
The maximum payload size is always 8KB independently of the SKU, but the billing differs as you will find in the link above.
We have discussions about bumping up this limit, but certainly not as much as 800KB. I am curious to know what scenario you are trying to implement that requires passing that much data in a Method call: that could help us find the right limit and eventually the right option to utilize for you.
