### ISSUE TITLE
Please update the link to azure-iot-sdk-node repo to fix AMQP over Websocket for server SDK

### ISSUE THREAD

**Issue by Sneezry** [Azure/azure-iot-sdks#1055]
- SDK used when observing the issue: Node, 1.1.1
- Type of device: PC
- OS (with version) on which the code is running: Windows 10

Code sample exhibiting the issue: 

var Client = require('azure-iothub').Client;
var Protocol = require('azure-iothub').AmqpWs;
var Message = require('azure-iot-common').Message;
var connectionString = 'xxx';
var targetDevice = 'xxx';
var client = Client.fromConnectionString(connectionString, Protocol);

Console log of the issue: 

SDK uses amqps instead.

----------

This issue is caused by azure-iot-sdks repo, but not azure-iot-sdk-node. This repo links to azure-iot-sdk-node an old version (v1.1.1, the latest is 1.1.7), which has bug in AMQP over Websocket for service side SDK.

Please update the link to azure-iot-sdk-node repo.

**Comment by olivierbloch** [comment]
The current repository azure-iot-sdks is being deprecated (I will update the readme to make it clearer) and the submodules links are obsolete.
Please clone the various languages repositories (azure-iot-sdk-node, azure-iot-sdk-c, ...) separately.
Thank you

**Comment by Sneezry** [comment]
OK, thanks for your information.
