### ISSUE TITLE
downloaded ZIP IoT SDKs is empty

### ISSUE THREAD

**Issue by chafiaa** [Azure/azure-iot-sdks#1056]
- SDK used when observing the issue: 
- Type of device: 
- OS (with version) on which the code is running 

Code sample exhibiting the issue: 

Console log of the issue:

**Comment by olivierbloch** [comment]
Hi @chafiaa 
The current repository is being deprecated (I will update the readme to make it clearer) and you should work directly with the various SDKs repositories: azure-iot-sdk-c, azure-iot-sdk-node, azure-iot-sdk-java, azure-iot-sdk-python, azure-iot-sdk-csharp
