### ISSUE TITLE
Preparing C development environment on Linux - Minor suggestion for scripts

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#106]
Can you please update the setup Linux environment documentation from:

1.Clone this repository (azure-iot-sdks) to the Ubuntu machine you are using.

2.Open a shell and navigate to the folder c/build_all/linux in your local copy of the repository.

3.Run the  setup.sh  script to install the prerequisite packages and the dependent libraries.

4.Run the  build.sh  script.

To:
1.Clone this repository (azure-iot-sdks) to the Ubuntu machine you are using.

2.Open a shell and navigate to the folder c/build_all/linux in your local copy of the repository.

3.Run the  ./setup.sh  script to install the prerequisite packages and the dependent libraries.

4.Run the  ./build.sh  script.

Not having worked in Linux for a while it was kind of annoying that I was in the directory but could not get setup.sh to execute.  It was only after I asked a colleague that I was able to get it to run via ./setup.sh

**Comment by dominicbetts** [comment]
@jtanner-msft good suggestion. I'll submit a PR with the change.

**Comment by tameraw** [comment]
Issue resolved. Please advise/reopen if you're still having issues. Thanks.

**Comment by kuldeepmarker** [comment]
I am currently using IoT sdk agent in c for a project. I have a few questions about the sdk.

 In my project I need to send sensor data to IoT hub.But in the sdk I have found no API using which my sensor data can be collected and the same data is send to the IoT hub through the IoT hub client.All the samples show hard coded values send to the IoT hub.
So can any one suggest me the way I can use sdk agent to collect data from sensor and send to iot hub.
