### ISSUE TITLE
Cmake 3.0 or higher required on Ubuntu Linux 14.04

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#107]
When trying to execute the script:
./build.sh

I received an error stating that my version of Cmake was not high enough.  Version 3.0 was required, but I was running 2.8.12.2 which was included with my install.

The documentation for setting up the Linux build environment might want to mention that they might need to install an updated version of Cmake.

**Comment by dcristoloveanu** [comment]
Will update the documentation for this issue.

**Comment by dominicbetts** [comment]
@jtanner-msft I added a note to this effect in the doc. I'll submit a PR shortly.

**Comment by robertoyg** [comment]
I don't think this is just a documentation issue as the Raspberry Pi 2 doesn't have cmake 3.0 and using the supported packages updates I can only get it to go up to 2.8.9 so this requirement of cmake 3.0 essentially leaves the RPi out of being supported for the C SDK.

**Comment by robotdad** [comment]
I was able to get it to get cmake 3 running on the Pi as follows:
    wget https://cmake.org/files/v3.3/cmake-3.3.2.tar.gz
    tar zxvf cmake-3.3.2.tar.gz
    cd cmake-3.3.2
    ./bootstrap
    make
    make install

The build took over an hour. It would be awesome if apt could catch up.

**Comment by dominicbetts** [comment]
It all seems to working fine on the Raspberry Pi now. Using the latest Raspbian image, the \azure-iot-sdks/c/build_all/Linux/setup.sh script runs successfully and installs cmake 3.0.2 on my Pi.

**Comment by tameraw** [comment]
Closing per @dominicbetts update. If there are any more issues seen, please reopen. Thanks.

**Comment by rcshubhadeep** [comment]
If anybody is still interested. This seems to work - http://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04
