### ISSUE TITLE
Path to simplesample_amqp appears wrong

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#112]
Step 6 in the documentation says:

6.Run the ~/cmake/serializer/samples/simplesample_amqp/linux/simplesample_amqp sample application.

On my own install of Ubuntu following those directions it appeared that the sample was actually built to this path:

~/cmake/serializer/samples/simplesample_amqp/simplesample_amqp

**Comment by tameraw** [comment]
Closing issue as referenced by #112. If unresolved still, please reopen.
