### ISSUE TITLE
Make a Python SDK

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#115]
We have used python in the past for quick development on the Raspberry Pi. We had used Event Hubs and Topics, utilising the service bus library.

It would be great to have a Python SDK we could use for the IoT Hub. Many thanks in advance

**Comment by aribeironovaes** [comment]
Hi @damienpontifex! 

Thanks for the feedback! 
I will follow up here. Can you enter your feedback here? https://feedback.azure.com/forums/321918-azure-iot
This is the forum where we get feedback for future features. 

Thanks a lot, 

Angelo Ribeiro.

**Comment by rcarmo** [comment]
I'd like to have this re-opened in the context of a service SDK, since there is currently no documentation or APIs for registering devices on IoT Hub using Python alone.
