### ISSUE TITLE
Please provide a way to just build samples

### ISSUE THREAD

**Issue by robotdad** [Azure/azure-iot-sdks#117]
With the move to cmake the build script builds the samples, and everything else. Please provide a way to build just the samples. 

I would also like to see a sample that uses a cmake file that is self contained. The cmake files are nested such that I'm not able to determine how to create one that will build outside of the repo. The only way I've found to build my own app is by adding it to the samples directory and modifying the cmake files to include it, then run the build all script. 

I'm using the linux samples, I presume this applies to other platforms as well.

**Comment by tameraw** [comment]
Thanks for the feedback. We're working on a solution for that.

**Comment by jebrando** [comment]
A task has been added for this and will be address in the next release.

**Comment by tameraw** [comment]
@robotdad - We should provide an update to this ask by end of this month. Regards.

**Comment by taunusflieger** [comment]
Any update on this? Not been able to build an individual samples is extremely time consuming

**Comment by tameraw** [comment]
Apologies this has been postponed as it keeps dropping lower in our priority list. We'd be happy to accept contribution for this.

**Comment by jebrando** [comment]
We've created the cmake that builds the samples only using the apt-get packages.  See the following instructions and let us know if you have any issues:

https://github.com/Azure/azure-iot-sdks/blob/develop/c/doc/ubuntu_apt-get_sample_setup.md
