### ISSUE TITLE
Git update process...

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#118]
As not everyone is familiar with Git and performing an update on a master branch.  (Myself included), You might want to at least describe the process that someone who has cloned the master branch should use to update it on a periodic basis as the bi-monthly updates to the master branch are released.

After some review of the git docs I believe the instructions are:
In an x86 native tools command prompt that has git in the path:
cd <folder you cloned project to> (by default it might be 'azure-iot-sdks')
git remote update

If the above is wrong please correct my understanding.  Either way seems like something reasonable to include in the general FAQ section.

**Comment by olivierbloch** [comment]
Hi @jtanner-msft , if you want to keep your local changes and merge with the upstream repository, you can follow the instructions here: https://help.github.com/articles/syncing-a-fork/
If you just want to get the latest version scratching your local changes, you can simply discard your changes a "git checkout --" should suffice.

**Comment by sethmanheim** [comment]
It's a good practice to do your Git work in smaller, atomic units. "git pull upstream master:myworkingbranch" creates a local working branch based on master. Once you add your changes, commit, and push back to origin, then create a PR, when the PR is merged you can delete this branch. Create a new local working branch for your next set of changes.

If your local working branch is still active and you want to update it with changes from master, just do a "git pull upstream master" from the command line while you have your local working branch checked out.

Hope that helps.

**Comment by tameraw** [comment]
@jtanner-msft Closing issue but feel free to reopen or file new one if you still feel feel your issue has not been addressed. Thanks.
