### ISSUE TITLE
Java MVN command line - hard to select

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#119]
Given that it has a scroll bar since it's on a single line it's a little difficult to select this command line:
mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=iot-device -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false

I had to copy parts of it into a notepad and then grab the next section to get it somewhere that I could select all at once.
If you can spread it across two lines, or provide a button to copy the entire contents that would probably make things easier.

Also it would be nice if you state where (if anywhere) they should be directory wise prior to creating this new project.
I'm guessing it's azure-iot-sdks\java\device but if it doesn't matter or should be somewhere else please specify.

**Comment by dominicbetts** [comment]
Thanks @jtanner-msft, I made some changes based on your suggestions that will be checked in shortly.
FYI, you can run the mvn command anywhere that you like on your dev box to create a project, it doesn't need to be in the repository folder structure.

**Comment by tameraw** [comment]
Issue addressed. Thanks.
