### ISSUE TITLE
New Java sample from Scratch issue

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#120]
Overall kudos for a much improved Java from Scratch sample that seems to overall build and work quite nicely.
The only issue I've noticed was when sending a message from Device Explorer to the device.
Each time I sent a message it receives it, but the odd thing was it kept printing out the text of whatever the first message had been.
For example it would say:
Received message with content: Hello!
Which was correct the first time. But if I then sent "Boo!"
I still saw this message get printed out:
Received message with content: Hello!

But it did print something each time I sent a message, just always the text from the first message.  
Maybe this is a bug in:
com.microsoft.azure.iothub.MessageCallback?

**Comment by andrew-buckley** [comment]
Hi @jtanner-msft, which sdk version were you using?

**Comment by andrew-buckley** [comment]
Hi @jtanner-msft, wanted to check if this is still occurring on your end. I haven't been able to repro this.

**Comment by tameraw** [comment]
Closing issue based on last comment. If this repros, please feel free to file new issue. Thanks.
