### ISSUE TITLE
Set Java logging level

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#121]
I tried to follow the instructions for setting a java logging level, but didn't see much change even when I had tried to set the level to 'ALL'.

How should the config.properties file look?
.level=ALL
<or>
.level={ALL}
<or>
.level = {ALL}

also in it wasn't clear how I should set this property:
java.util.logging.config.file

I tried the following:
set java.util.logging.config.file=C:\bin\azure-iot-sdks\java\device\iot-device

Does it need to point to the actual config.properties file, or just the folder it's located?

**Comment by andrew-buckley** [comment]
Hi @jtanner-msft, I'll be looking into this issue and will report back.

**Comment by tameraw** [comment]
@jtanner-msft - Closing as this one should be fixed already. Please open new issue if still having problems. Thanks.
