### ISSUE TITLE
Doc error in connecting devices to Suite doc

### ISSUE THREAD

**Issue by msjaosborn** [Azure/azure-iot-sdks#124]
https://azure.microsoft.com/en-us/documentation/articles/iot-suite-connecting-devices/
 
Running your device on Windows
1.               Set up your environment: if you have never used our device SDK before, learn how to set up your environment on Windows here.
2.               Start a new instance of Visual Studio 2015. Open the remote_monitoring.sln solution in the c\serializer\build\windows folder in your local copy of the repository.
 
Should be c\serializer\samples\remote_monitoring\windows

**Comment by tameraw** [comment]
Thanks James. Will fix it.

**Comment by dominicbetts** [comment]
Fixed in https://github.com/Azure/azure-content-pr/pull/17181

**Comment by tameraw** [comment]
Issue addressed. Thanks.
