### ISSUE TITLE
Errors in build batch files when using zip download

### ISSUE THREAD

**Issue by VMinute** [Azure/azure-iot-sdks#128]
When the code is downloaded as a zip file the files use Unix EOL (line feed) and not DOS EOL (carriage return and line feed). There is an issue in the command prompt interpreter that leads to subroutine labels not being recognized in Unix-formatted batch files. This leads to errors that are not easy to fix since they complain about not finding a label that is there.
There is no easy way to fix this (also because it happens randomly, not with every var), but can affect people that download the zip or the code keeping it in the Unix format. It may be useful to add a warning message or describe the issue in the docs.

**Comment by tameraw** [comment]
We'll add a description in the docs noting the issue you observed. Thanks.

**Comment by dominicbetts** [comment]
Added a comment to the FAQ about this issue.

**Comment by tameraw** [comment]
Hi VMinute - Issue addressed in documentation. Please reopen if still having issue. Thanks.
