### ISSUE TITLE
serializer_e2etests tests not executing on Ubuntu Linux

### ISSUE THREAD

**Issue by brean** [Azure/azure-iot-sdks#129]
Hi,

I followed the installation documentation at https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md#linux 
using Ubuntu 15.10 and some of the tests are not running:

```
47: Error: Time:Tue Nov 10 19:10:19 2015 File:/home/ubuntu/coding/azure-iot-sdks/c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_Create Line:286 underlying transport failed
47:  === Executing test suite serializer_e2etests ===
47: Executing test IoTClient_Http_MacroSend_E2ETests ...
47:   Assert failed: non-NULL expected. 
47: !!! FAILED !!!
47: Executing test IoTClient_Http_MacroRecv_E2ETests ...
47:   Assert failed: non-NULL expected. 
47: !!! FAILED !!!
47: Executing test IoTClient_AMQP_MacroSend_E2ETests ...
47:   Assert failed: non-NULL expected. 
47: !!! FAILED !!!
47: Executing test IoTClient_AMQP_AmqpMacroRecv_E2ETests ...
47:   Assert failed: non-NULL expected. 
47: !!! FAILED !!!
47: 4 tests ran, 4 failed, 0 succeeded.
```

**Comment by ewertons** [comment]
Hi brean, 
Azure IoT SDK currently supports the operating systems defined in https://github.com/Azure/azure-iot-sdks/blob/master/doc/tested_configurations.md
Please deploy Ubuntu 14.04 LTS and try running the tests.

In addition to that, please also make sure you have set your environment up with the ENV VARs consumed by the End-to-End tests:
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_end_to_end_tests.md
