### ISSUE TITLE
Linux Ubuntu build.sh not building examples

### ISSUE THREAD

**Issue by brean** [Azure/azure-iot-sdks#130]
Hi, 

I followed the example documentation at [simplesample_amqp/linux/readme.txt](https://github.com/Azure/azure-iot-sdks/blob/master/c/serializer/samples/simplesample_amqp/linux/readme.txt)
but when I run build.sh at the end it does not build the examples

I had to change the connection string in [simplesample_amqp.c](https://github.com/Azure/azure-iot-sdks/blob/master/c/serializer/samples/simplesample_amqp/simplesample_amqp.c) not [main.c](https://github.com/Azure/azure-iot-sdks/blob/master/c/serializer/samples/simplesample_amqp/linux/main.c) as the [readme.txt](https://github.com/Azure/azure-iot-sdks/blob/master/c/serializer/samples/simplesample_amqp/linux/readme.txt) says and I set run_e2e_tests=OFF in my build.sh, see https://github.com/Azure/azure-iot-sdks/issues/129

What do I need to build to example?

**Comment by brean** [comment]
I found the compiled example at
~/cmake/serializer/samples/simplesample_amqp
so it is just the readme.txt that points to the wrong file

**Comment by ewertons** [comment]
Hi brean, indeed I just verified that the readme is incorrect.
It should indicate that the IoT credentials should be written on simplesample_amqp.c
I added that to our current backlog.

**Comment by ewertons** [comment]
The fix is now merged into develop branch.
Thanks.
