### ISSUE TITLE
Raspberry Pi 2 Raspbian Setup - Documentation Issue

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#131]
I had an issue with this section:
*Build and install the Apache Proton library:*

*sudo ./c/build_all/linux/build_proton.sh --install /usr*

I created the root account as documented but this step only appears to work if one is actually __logged in__ to the root account. Perhaps that should have been obvious to me but it does not mention that one should actually log into that account. If one tries to build it from the pi account the messages:

*Install the project...*
*-- Install configuration: "RelWithDebInfo"*
*-- Up-to-date: /usr/share/proton-0.9/LICENSE*
*CMake Error at cmake_install.cmake:36 (file):*
  *file INSTALL cannot set permissions on "/usr/share/proton-0.9/LICENSE"*

*Makefile:66: recipe for target 'install' failed*
*make: *** [install] Error 1*

are generated.
When logged into the root account it apparently works as expected.

**Comment by ewertons** [comment]
Hi markrad, thanks for the feedback. 
We will investigate and report back with the root cause/solution.

**Comment by anporumb** [comment]
I seem to remember running into the same problem.
Did you add sudo to your sudoers group? [as strange as that might sound].

Best Regards,
Andrei Porumb

**Comment by dominicbetts** [comment]
The latest version of setup.sh installs both qpid proton and paho libraries so these extra steps are no longer necessary. I'll update the docs accordingly.

**Comment by tameraw** [comment]
Hi Markrad - Doc has been updated. Please let us know if you're still having issues.
