### ISSUE TITLE
Why is the JDK in the list of dependencies for the C SDK?

### ISSUE THREAD

**Issue by robotdad** [Azure/azure-iot-sdks#132]
If I'm not using java I generally prefer not to use it. The C SDK build_all script includes openjdk-7-jre in it's list of dependencies. Why?

**Comment by robotdad** [comment]
OK, I see it is for proton. But why do I have to build the jar for proton when I'm not going to use it?

**Comment by tameraw** [comment]
It is indeed because of proton. We are looking at a fix to not build it for c SDK and remove the openjdk-7 dependency.

**Comment by dcristoloveanu** [comment]
This has been fixed now in the develop branch. It will be available in the next release.
