### ISSUE TITLE
Full life cycle for provisioning devices

### ISSUE THREAD

**Issue by Humancell** [Azure/azure-iot-sdks#139]
Hello,

We build a wide range of custom and off-the-shelf IoT solutions and are currently pushing data into EventHubs.  I'm researching what my team needs to do to integrate via the IoT SDKs.  Our devices range from fully embedded devices (C apps, running on dedicated hardware) to embedded Linux solutions.

In reading about the provisioning, I'm seeing some of the same issues that we have hit with EventHubs.  I've read the page here:  https://github.com/Azure/azure-iot-sdks/blob/master/tools/iothub-explorer/doc/provision_device.md

What we are trying to understand is how a end-user is supposed to do this all in an automated way for the long-term full life-cycle of the device.  I can not find any documentation which really explains this in a way that will work in enterprise and commercial projects that we are working on.

Our customers will buy a device from us to connect to their Azure account.  So there must be mechanisms in place to allow the device to be configured for Internet Connectivity (which we provide) and then obtain a provisioning string via some automated method.  Then, since I see that the strings have a TLL, there must be some way for the device or management system to automate the updating of these periodically.

We're currently provisioning and managing hundreds of devices, and approaching thousands.

Have you documented how your architecture is meant to work in scenario like this?

How did you intend for all of this to automated and managed without any human intervention?

Thanks!

**Comment by olivierbloch** [comment]
Hi
Thanks for chiming in!
We definitively understand the need for mechanisms to help our customers scale when they deploy their solutions. We are actually working on features that will address these scenarios and expect to be able to share these very soon.
At this point one has to provision the device OOB as demonstrated in the samples.
Thanks
Olivier

**Comment by Humancell** [comment]
Thank you for the reply ... one other questions:  Does the TTL always have to be set?  What is the longest TTL that can be used?

**Comment by Humancell** [comment]
Bump!  I'm curious if you can answer my questions from November 23rd?

The explanation for provisioning implies that it still requires manual execution of command-line tools.

1. Does the TTL always have to be set?

2. What is the longest TTL that can be used?

Thanks!

**Comment by fsautomata** [comment]
Hi,

The TTL does not have to always be set, when not set it is assumed the default value in the IoT Hub configuration (defaultTtlAsIso8601).

As reported in the Cloud-to-device configuration options (https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide/#c2dconfiguration) the maximum TTL is up to 2 days.

**Comment by Humancell** [comment]
Hello,

I think we are talking about two entirely different TTL values.  The one that I was asking about is the one that is specified during the creation of the Shared Access Signature for submitting date from "device to cloud" ... not the lifetime of messages in the hub/queue for "cloud to device".

If you look here:  https://github.com/Azure/azure-iot-sdks/blob/master/tools/DeviceExplorer/doc/how_to_use_device_explorer.md

Scroll down and you'll see where you have to create the signature string and specify a TTL for the signature to be valid.

I have also had to set a Shared Access Signature TTL on my use of various other Azure service in generating these request signatures.  Once this TTL expires, your device is no longer able to submit any data to the IoT Hub or Event Hub.

The TTL that you are looking at appears to be completely different and indicates the lifetime of a message in the queue for "cloud to device" messages.

**Comment by fsautomata** [comment]
Hi,

Sorry about the misunderstanding.
Expiry Time should be set, and it currently has no max.
It is advisable not to use long lasting SAS tokens from authorization rules as they present a security hole.

It seems you might be looking into creating a "bootstrapping" service (as described in https://azure.microsoft.com/en-us/documentation/articles/iot-hub-device-management/#device-provisioning-and-discovery). This is common pattern where you have a service that creates a new identity/key for devices at the time of onboarding. The idea is that the "first internet connection" of a device would use this service to set up a deviceId/key for subsequent connections with IoT Hub.

During bootstrapping the bootstrap server can decide to use any security validation technique is appropriate for the specific scenario (e.g. 2 factor authentication with a phone, connection with a CRM, simple validation that no other device with the same MAC address is registered, association with a human's account (outlook, gmail, ...)).

Elio

**Comment by tameraw** [comment]
@Humancell - Please let us know if you have any other questions or issues. Thanks.

**Comment by kevin0402** [comment]
Hi,

Above link is no longer available.
Please share the new link regarding devices provisioning mechanism.
Thanks.
