### ISSUE TITLE
Error messages for acknowledgement errors

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#141]
I haven't been able to find descriptors for error messages to debug an error with msg acknowledgement.

The specific one on `client.complete` that I'm receiving is DeviceMessageLockLost but when sending a command on the server I am setting `Ack = DeliveryAcknowledgement.Full` on the message.

Is there something else to debug to find where the error is occurring?

**Comment by rajeevmv** [comment]
The DeviceMessageLockLost exception is thrown if the the DeviceClient does not complete/reject/abandon a message that it has received within a short time period (typically 1 min). It can also be thrown if the device tries to complete/reject/abandon a message that it has already abandoned.

**Comment by tameraw** [comment]
We will take on updating the MSDN description for this Exception and all others (that aren't up to date).

**Comment by tameraw** [comment]
Doc has been updated for this:
https://msdn.microsoft.com/en-us/library/microsoft.azure.devices.client.exceptions.aspx
Thanks!
