### ISSUE TITLE
Message properties lost receiving via HTTP

### ISSUE THREAD

**Issue by ppatierno** [Azure/azure-iot-sdks#142]
Hello,
I read the following post on MSDN (pay attention to the last question and not the first one) :

https://social.msdn.microsoft.com/Forums/en-US/bd2902e6-01e4-495a-ab83-d6f4eb48da6e/deviceclient-for-iothub-communication-in-uwp

If I understood well, if you send a message using HTTP, the message properties are set as HTTP headers with a prefix, key and value.
I can't see the reverse path on receiving. I can't find the code where the received HTTP header are used to fill the message properties.

This is what the author of the blog post said : no message properties receiving via HTTP.

Paolo.

**Comment by NNM11** [comment]
+1 on this issue

**Comment by rajeevmv** [comment]
This bug has been fixed on the service. The client side fix is in the "develop" branch and will be rolled into a NuGet package by the end of the month.
