### ISSUE TITLE
Intel Edison, Yocto Linux

### ISSUE THREAD

**Issue by vaswork** [Azure/azure-iot-sdks#147]
[excuse my eng]

As for me, it is impossible to use azure-iot-sdks on Intel Edison board (Yocto Linux 2.1). Formally, the blocking issue is that for building sdk cmake 3.0 required:

root@edison:~/azure-iot-sdks/c/build_all/linux# ./build.sh
~/cmake ~/azure-iot-sdks/c/build_all/linux
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  CMake 3.0 or higher is required.  You are running version 2.8.12.2

-- Configuring incomplete, errors occurred!

I have not found how to update cmake on Intel Edison. There is instruction for ubuntu only (https://github.com/Azure/azure-iot-sdks/blob/8e6b95854d6281764ce9eddb820617b0be9a074e/c/doc/devbox_setup.md).

But may be I am wrong somewhere. Lets try to do it step-by-step:

My configuration:

Intel Edison + Groove/Xadow Kit. 
Firmware updated using Phone Flash Tool Lite. 
The OS Image http://downloadmirror.intel.com/25384/eng/edison-iotdk-image-280915.zip, named as "Release 2.1 Yocto* complete image" here https://software.intel.com/en-us/iot/hardware/edison/downloads ),  
WiFi connected, root has a password.

<PuTTY>

Poky (Yocto Project Reference Distro) 1.7.2 edison ttyMFD2

edison login: root
Password:

root@edison:~# configure_edison --version
159.devkit

So, accordingly the list of tested configurations (https://github.com/Azure/azure-iot-sdks/blob/75107fa7b0e614a83dfcd81aff4727541d81fa28/doc/tested_configurations.md) I can use Intel Edison board with Yocto Linux 2.1 with my C/C++ project (Eclipse). I have used the "Run sample on Intel Edison" (https://github.com/Azure/azure-iot-sdks/blob/2f43c239f3d58fdab9c45e1bb2c57965fc17f9c7/c/doc/run_sample_on_intel_edison.md) I have got this:
0) 
root@edison:~# opkg install git
Package git (2.0.1-r0) installed in root is up to date.

1) 
root@edison:~# git clone github.com/Azure/azure-iot-sdks.git
fatal: repository 'github.com/Azure/azure-iot-sdks.git' does not exist

Try to use https:

root@edison:~# git clone https://github.com/Azure/azure-iot-sdks.git
Cloning into 'azure-iot-sdks'...
remote: Counting objects: 10111, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 10111 (delta 6), reused 0 (delta 0), pack-reused 10057
Receiving objects: 100% (10111/10111), 19.69 MiB | 18.00 KiB/s, done.
Resolving deltas: 100% (6079/6079), done.
Checking connectivity... done.
Checking out files: 100% (1623/1623), done.

2) 
root@edison:~/azure-iot-sdks/c/build_all/linux# opkg install util-linux-libuuid-dev
Package util-linux-dev (2.24.2-r1) installed in root is up to date.

3)

root@edison:~/azure-iot-sdks/c/build_all/linux# ./build_proton.sh
Source: /home/root/qpid-proton
Install: /home/root
Azure IoT SDK has a dependency on apache qpid-proton-c
https://github.com/apache/qpid-proton/blob/master/LICENSE
Do you want to install the component (y/n)?Y
preparing qpid proton-c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138    0   138    0     0     89      0 --:--:--  0:00:01 --:--:--    93
  0     0    0 1663k    0     0   115k      0 --:--:--  0:00:14 --:--:--  160k
Archive:  proton.zip
   creating: qpid-proton-0.9-IoTClient/
  inflating: qpid-proton-0.9-IoTClient/.gitignore
  inflating: qpid-proton-0.9-IoTClient/.mailmap
  inflating: qpid-proton-0.9-IoTClient/CMakeLists.txt
  inflating: qpid-proton-0.9-IoTClient/DEVELOPERS

[tens pages of logs here ... ]

[ 65%] Building C object proton-c/CMakeFiles/qpid-proton.dir/src/platform.c.o
[ 66%] Building C object proton-c/CMakeFiles/qpid-proton.dir/src/ssl/openssl.c.o
Linking C shared library libqpid-proton.so
[ 66%] Built target qpid-proton
Scanning dependencies of target proton-dump
[ 68%] Building C object proton-c/CMakeFiles/proton-dump.dir/src/proton-dump.c.o
Linking C executable proton-dump
[ 68%] Built target proton-dump
[ 69%] Swig source
Scanning dependencies of target _cproton
[ 71%] Building C object proton-c/bindings/python/CMakeFiles/_cproton.dir/cprotonPYTHON_wrap.c.o
Linking C shared module _cproton.so
CMakeFiles/_cproton.dir/cprotonPYTHON_wrap.c.o: In function `_wrap_pn_messenger_set_client_sasl_mechanism':
/home/root/qpid-proton/build/proton-c/bindings/python/cprotonPYTHON_wrap.c:19630: undefined reference to `pn_messenger_set_client_sasl_mechanism'
collect2: error: ld returned 1 exit status
proton-c/bindings/python/CMakeFiles/_cproton.dir/build.make:129: recipe for target 'proton-c/bindings/python/_cproton.so' failed
make[2]: *** [proton-c/bindings/python/_cproton.so] Error 1
CMakeFiles/Makefile2:1094: recipe for target 'proton-c/bindings/python/CMakeFiles/_cproton.dir/all' failed
make[1]: *** [proton-c/bindings/python/CMakeFiles/_cproton.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2

4)
And as I already told:

root@edison:~/azure-iot-sdks/c/build_all/linux# ./build.sh
~/cmake ~/azure-iot-sdks/c/build_all/linux
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  CMake 3.0 or higher is required.  You are running version 2.8.12.2

-- Configuring incomplete, errors occurred!

--- 
If you need more info from me or some another assistance - feel free.

Slava.

**Comment by darobs** [comment]
I just recently installed CMake 3 on an Intel Edison running Yocto.

The easiest way is to download the self extracting .sh from cmake.org, run it, and then make sure the directory you installed CMake 3 is in your path.

For example (using the current link to the Cmake release):
```
wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-i386.sh
chmod u+x cmake-3.4.0-Linux-i386.sh
./cmake-3.4.0-Linux-i386.sh --help
Usage: ./cmake-3.4.0-Linux-i386.sh [options]
Options: [defaults in brackets after descriptions]
  --help            print this message
  --prefix=dir      directory in which to install
  --include-subdir  include the cmake-3.4.0-Linux-i386 subdirectory
  --exclude-subdir  exclude the cmake-3.4.0-Linux-i386 subdirectory

```

**Comment by aribeironovaes** [comment]
Hi Slava,

After you fix the Cmake Problem you will need to do the following. (hint,
for the CMAKE problem make sure you add the folder you created on your PATH
by exporting it OR use the command --prefix=/usr (This will replace your
current cmake for the latest one).

-Run build_proton.sh from the build folder; (It will fail with the problem
you mentioned with Python Binding);
-Go to file: <Folder where qpitproton is, usually your root home
folder>\qpid-proton\*proton-c/bindings/CMakeLists.txt  and edit this file
removing "python" from "BINDINGS"*
*-Edit the Build Proton script and remove or comment **#sync_proton line,
otherwise it will sync again the overwrite your change;*
*-Run build_pronto.sh again.*
*-Just to be safe, go to folder ~/qpid-proton/build and run "make" and
"make install" and make sure proton is getting installed correctly.*
-Run our Build.sh with the parameter --no-mqtt

Olivier/Tamer, we shall add documentation for that or update our scripts to
fix these problems.

Hope this helps,

Angelo Ribeiro.

On Fri, Nov 20, 2015 at 8:10 AM, darobs <notifications@github.com> wrote:

> I just recently installed CMake 3 on an Intel Edison running Yocto.
>
> The easiest way is to download the self extracting .sh from cmake.org,
> run it, and then make sure the directory you installed CMake 3 is in your
> path.
>
> For example (using the current link to the Cmake release):
>
> wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-i386.sh
> chmod u+x cmake-3.4.0-Linux-i386.sh
> ./cmake-3.4.0-Linux-i386.sh --help
> Usage: ./cmake-3.4.0-Linux-i386.sh [options]
> Options: [defaults in brackets after descriptions]
>   --help            print this message
>   --prefix=dir      directory in which to install
>   --include-subdir  include the cmake-3.4.0-Linux-i386 subdirectory
>   --exclude-subdir  exclude the cmake-3.4.0-Linux-i386 subdirectory
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-iot-sdks/issues/147#issuecomment-158445943>
> .
>



-- 
---
Angelo Ribeiro
Msc - Federal University of Pernambuco
Team in Training Alumni Triple Crowned! :)

**Comment by dominicbetts** [comment]
Added entry to FAQ describing this issue and solution.

@tameraw please close this issue once the PR is accepted.

**Comment by tameraw** [comment]
PR has been merged.
