### ISSUE TITLE
C# SDK returning "The specified SAS token is expired"

### ISSUE THREAD

**Issue by mortenf** [Azure/azure-iot-sdks#152]
I have had an IoT Hub running for some time, with one client using the Node.js SDK working (almost) without problems.

However, the C# client (simple, based on the sample, using 1.0.0-preview6), running on a Raspberry Pi 2 with Windows 10 IoT Core, doesn't work, immediately (a few seconds, at first attempt) returning a Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException with "The specified SAS token is expired".

I have tried the same connection string with the Node.js client: Works fine.
I have tried generating a new connection string (deleting and recreating the device) using Device Explorer: Same error.
I have tried first regenerating the IoT Hub main (iothubowner) key, then generating a new connection string: Same error.
I have tried creating a new IoT Hub and recreating the sample UWP App: Same error.

Which token is expired and why (all of the above done within half an hour)?

**Comment by rajeevmv** [comment]
The SharedAccessSignature token string has a field with expiry time called "se". Take that value and convert it into human readable time using a converter (like the one @ www.epochconverter.com). This will tell you when that token is supposed to expire. This type of issue usually happens when there is a significant clock skew between the client and the service.

**Comment by mortenf** [comment]
Ah. Thanks a bunch - time was totally off. Didn't realize that could be the case.
This is of course not really the fault of the SDK, but since there is no easy way to keep time synced on RPi IoT Core - or discover that wrong time is the issue - perhaps a check for this situation (check time after receiving this error) could be added? I'd be happy to try creating a pull request, if interested.
