### ISSUE TITLE
CBS token problem on Linux ARM

### ISSUE THREAD

**Issue by FlorianLudwig** [Azure/azure-iot-sdks#157]
Running on Linux ARM 32 bit (little endian) I receive:
```
iothubtransportamqp.c Func:processCBSReply Line:1222 The CBS put token operation failed: 401

iothubtransportamqp.c Func:processCBSReply Line:1235 The CBS put token operation failed due to: The specified SAS token is expired
```

Using the same code (and connection string!) on a Linux Intel 64 bit box it works just fine. Hence I am certain the SAS token is not the problem.

Test code is  `./serializer/samples/simplesample_amqp/simplesample_amqp` with only the connection string changed.

Any ideas how to debug this?

Thanks

**Comment by rajeevmv** [comment]
This is probably because there is a significant clock skew between the client and the service.

**Comment by FlorianLudwig** [comment]
@rajeevmv you are indeed right. Thank you very much for the hint!

User error, closing.
