### ISSUE TITLE
Device sdk fx/System.Net.Http.Formatting could not be resolved

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#158]
This is to do with the server SDK, but I don't believe there is a repository for that code?

When including the IoT SDK package Microsoft.Azure.Devices which has dependencies on Microsoft.AspNet.WebApi.Client (≥ 5.2.3)
Microsoft.AspNet.WebApi.Core (≥ 5.2.3)

Building from VS2015 and in VSO and using ASP.NET 5 1.0.0-rc1-final I get the error:

"error NU1001: The dependency fx/System.Net.Http.Formatting could not be resolved."

Could this be something to do with including WebAPI packages as above in aspnet 5 project? Or another problem...?
If so, could the packages be updated to support a more friendly package for asp.net 5 or also .NET core?

**Comment by damienpontifex** [comment]
Manually linking against System.Net.Http seems to have fixed it. My apologies

**Comment by damienpontifex** [comment]
Reopening as we have come across this issue again on a new developers machine. We are now using 1.0.4 of the devices SDK.

Any insights from the devices team?

**Comment by arturl** [comment]
NuGet package Microsoft.AspNet.WebApi.Client needs to be added as a dependency (this is already happening in the Connected Service for Azure IoT Hub)

**Comment by damienpontifex** [comment]
@arturl We already have that as a dependency, so doesn't seem to be a resolution. I also received another response at https://github.com/aspnet/Home/issues/1132#issuecomment-207218861 that seems promising and have sent an email via NuGet.org to see if that can be done to resolve the issue.

**Comment by damienpontifex** [comment]
Resolved with Microsoft.Azure.Devices 1.0.5
