### ISSUE TITLE
AMQP feedback

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#170]
I've been using the NodeJS library for the iot sdk and had been using the HTTP transport which had a `sendFeedback` function to acknowledge receival of the message.

This doesn't seem to exist in the AMQP transport. Is this handled automatically for AMQP or is it yet to be implemented for AMQP?

**Comment by pierreca** [comment]
Hi Damien

the pattern is a little different with AMQP. You can now call complete/abandon/reject directly on the receiver object obtained calling getReceiver(). These methods take the message you want to settle as a parameter. Long term, all protocols will follow the same pattern. The code in simple_sample_amqp.js should show that.

**Comment by pierreca** [comment]
@damienpontifex I'm closing this hoping the previous comment answered your question. Don't hesitate to reopen if it wasn't the case :)

**Comment by damienpontifex** [comment]
Yes, was just looking at it and happy to close.

Thanks for the help
