### ISSUE TITLE
Iot SDK for C - cannot execute binary file

### ISSUE THREAD

**Issue by Shachar1** [Azure/azure-iot-sdks#172]
Hey, I've followed the instructions of - RasberryPi 2 with Raspbian OS and tried to run the simplesample_amqp using bash and I'm getting "Cannot execute binary file".

I'm using - Raspbian GNU/Linux 7 (wheezy), with RaspberryPi 1. 
also, I don't know if it's related but I'm getting that some tests failed in the build process.

The following tests FAILED:
     25 - iothubclient_amqp_e2etests (Failed)
     27 - iothubclient_http_e2etests (Failed)
     49 - serializer_e2etests (Failed)

Thanks.

**Comment by v-pravek** [comment]
Hi,

Could you please provide the link to instructions you are following. Please also make sure that you have gcc version 4.9 or later installed on your device and try building again. 

On E2E failure, could you please follow instructions at https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_end_to_end_tests.md to make sure that all your environment variables are set correctly. These failures can happen if required environment variables are not set or if the value to these variables is not correctly.

Thanks

**Comment by tameraw** [comment]
@Shachar1 - Is this still an issue for you or has it been resolved? thanks.

**Comment by tameraw** [comment]
@Shachar1 - Please reopen if you're still having issues. Thanks.
