### ISSUE TITLE
nuget instructions for proton are unclear

### ISSUE THREAD

**Issue by BertKleewein** [Azure/azure-iot-sdks#176]
When setting up the proton nuget file, the instructions at https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md says:

"In Visual Studio 2015 right click on your solution and select "Manage NuGet Package for Solutions".

I'm not exactly sure _which_ solution I'm supposed to click on.  Since we haven't used cmake at this point in the instructions, I may not even have the appropriate .sln files yet.  Is there a chicken-and-egg problem here?

**Comment by tameraw** [comment]
Pull request has been merged. Thanks.
