### ISSUE TITLE
CC3200 Setup - Document Issues

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#177]
Installation of NS package are not very specific. Should just tell the user to unzip it into the c:\ti directory
Line:  *ti.targets.arm.elf.M4  ?= C:/ti/cgt_arm_5.2.5*
The directory path is actually *C:/ti/ti-cgt-arm_5.2.5*

**Comment by dcristoloveanu** [comment]
This has been updated directly in master to have the default ti-cgt-arm_5.2.5.
