### ISSUE TITLE
build.cmd parameter change not documented

### ISSUE THREAD

**Issue by BertKleewein** [Azure/azure-iot-sdks#179]
in https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md:
it tells you to run: build.cmd --skip-e2e-tests
it looks like the behavior of build.cmd has changed to skip the tests by default, so these instructions need to change

**Comment by dominicbetts** [comment]
@BertKleewein Thanks for pointing this out. I've submitted a PR to fix this.
@tameraw you can close this issue now.
