### ISSUE TITLE
Support UTF8 byte array in sending message from Device Explorer

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Azure/azure-iot-sdks#187]
While DeviceClient can send and receive UTF8 byte array and Device Explorer can also monitor receive UTF8 string, Device Explorer sends ASCII byte array.
Are there any restrictions of sending UTF8 byte array? I don't know the detail, but I can send and receive UTF8 byte array with Windows 10 UWP on Raspberry Pi 2.

- sending ASCII
https://github.com/Azure/azure-iot-sdks/blob/2015-11-30/tools/DeviceExplorer/DeviceExplorer/MainForm.cs#L548

- monitoring UTF8
https://github.com/Azure/azure-iot-sdks/blob/2015-11-30/tools/DeviceExplorer/DeviceExplorer/MainForm.cs#L395,L424

**Comment by tameraw** [comment]
@tanaka-takayoshi - Thanks for submitting this issue and apologies it's taken that long to respond back.
Currently not all our clients support UTF8 yet, so in DeviceExplorer we send ASCII as you mentioned.
We have captured tasks in our backlog for support of UTF8 (or UTF16) in all of our different client SDKs.

**Comment by tameraw** [comment]
@tanaka-takayoshi - Please feel free to reopen if you feel your question has not been answered. Thanks.
