### ISSUE TITLE
Question: Best way to provision devices with connection string

### ISSUE THREAD

**Issue by nhwilly** [Azure/azure-iot-sdks#190]
I know this has to be pretty simple, but what's considered best practice for getting the device connection string into the device?  

Actually trying to think through the flow as if the user has a device in their hands and has to set it up.

**Comment by bergotronic** [comment]
+1 Curious to see some tips / guidance on this once - perhaps a post?

**Comment by olivierbloch** [comment]
That definitively is a legitimate question.
As of now the samples instruct to type the connection string in the sample code which is not a good practice for an actual deployment as it doesn't scale.
There are different approaches and practices to provision devices with a connection string that would include proper security and authentication mechanism. We are indeed working on device management features for IoT Hub that will address this scenario.
Juan recently published an article about device management that mentions the use of a bootstrap service to provision devices with an IoT Hub connection string: https://azure.microsoft.com/en-us/documentation/articles/iot-hub-device-management/#device-provisioning-and-discovery
That should be a good start.

**Comment by tameraw** [comment]
@nhwilly - Thanks for your inquiry. Please let us know if you have any more questions.

**Comment by nhwilly** [comment]
Out of town for a few weeks.  Thanks for following up.

Bill

Sent from my Windows Phone
________________________________
