### ISSUE TITLE
Java DeviceClient taking a long time to close

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdks#193]
Calling close() on a DeviceClient instance in a Java application takes 20 minutes to complete if the protocol is set to AMQPS. If the protocol is HTTPS the method completes almost instantaneously.

IotHubClientProtocol protocol = IotHubClientProtocol.AMQPS;
DeviceClient client = new DeviceClient(connString, protocol);
client.open();
System.out.println("Press ENTER to exit.");
System.in.read();
System.out.println("Closing Client...");
client.close(); // Takes 20 minutes
System.out.println("Client closed");

**Comment by andrew-buckley** [comment]
Hi @dominicbetts, thanks for reporting this. We've filed a bug and will have a look.

**Comment by tameraw** [comment]
@dominicbetts - We captured this in our backlog and should be able to provide a solution to this soon as several people have reported the same issue.

**Comment by tameraw** [comment]
This should be resolved by now. @dominicbetts please feel free to reopen if you're still having issues. Thanks!
