### ISSUE TITLE
Program received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by rajvael** [Azure/azure-iot-sdks#195]
I found below error while continuously sending more messages and my internet connection was lost in between. I am not sure why this is happening if the internet/wifi connection goes offline and coming online. 

#0  0x00000000 in ?? ()
#1  0xb6d9bdcc in pn_class_decref (clazz=0x84f48, object=0x668c0) at /home/qpid-proton/proton-c/src/object/object.c:93
#2  0xb6da8c28 in pn_event_finalize (event=0xf7da0) at /home/qpid-proton/proton-c/src/events/event.c:190
#3  pn_event_finalize_cast (object=0xf7da0) at /home/qpid-proton/proton-c/src/events/event.c:235
#4  0xb6d9bdf4 in pn_class_decref (clazz=0xb6dc74e8 <clazz>, object=0xf7da0) at /home/qpid-proton/proton-c/src/object/object.c:97
#5  0xb6d9c024 in pn_decref (object=<optimized out>) at /home/qpid-proton/proton-c/src/object/object.c:252
#6  0xb6da8d9c in pn_collector_pop (collector=<optimized out>) at /home/qpid-proton/proton-c/src/events/event.c:167
#7  0xb6db5cc8 in pn_messenger_process_events (messenger=messenger@entry=0x6f840) at /home/qpid-proton/proton-c/src/messenger/messenger.c:1285
#8  0xb6db5d3c in pn_messenger_selectable (messenger=messenger@entry=0x6f840) at /home/qpid-proton/proton-c/src/messenger/messenger.c:730
#9  0xb6db5de4 in pni_wait (messenger=messenger@entry=0x6f840, timeout=timeout@entry=0) at /home/qpid-proton/proton-c/src/messenger/messenger.c:1360
#10 0xb6db62f4 in pn_messenger_tsync (messenger=0x6f840, predicate=0xb6db2bf4 <pn_messenger_stopped>, timeout=<optimized out>) at /home/qpid-proton/proton-c/src/messenger/messenger.c:1412
#11 0xb6db6368 in pn_messenger_sync (messenger=<optimized out>, predicate=<optimized out>) at /home/qpid-proton/proton-c/src/messenger/messenger.c:1428
#12 0xb6df9d9c in stopMessenger (messenger=0x6f840) at /home/Iot/azure-iot-sdks-master/c/iothub_client/src/iothubtransportamqp.c:436
#13 0xb6df9eb8 in herdTheMessengers (state=state@entry=0x587a8, logMessengerStopFailures=logMessengerStopFailures@entry=false) at /home/Iot/azure-iot-sdks-master/c/iothub_client/src/iothubtransportamqp.c:477
#14 0xb6dfcb34 in clientTransportAMQP_DoWork (handle=0x587a8, iotHubClientHandle=<optimized out>) at /home/Iot/azure-iot-sdks-master/c/iothub_client/src/iothubtransportamqp.c:1508

**Comment by olivierbloch** [comment]
We are working on changes that will make this issue go away. Expect a resolution end of this month.

**Comment by tameraw** [comment]
@rajvael - We have released a new update to our SDK and this issue should now be resolved. Note that we no longer are using the Porton library, but using uAMQP instead (library we open sourced for constrained devices). Please let us know if you have any other issues.
