### ISSUE TITLE
CC3200 Simple HTTP Sample Build Error

### ISSUE THREAD

**Issue by bjgross1076** [Azure/azure-iot-sdks#196]
Hello, receiving an error when trying to build the HTTP sample.  

cleaning ..

c:\ti\azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200> C:\ti
\xdctools_3_31_01_33_core\gmake.exe all
making package.mak (because of package.bld) ...
generating interfaces for package main (because package/package.xdc.inc is older
 than package.xdc) ...
configuring main.xem4 from package/cfg/main_pem4.cfg ...
generating custom ti.sysbios library makefile ...
Starting build of library sources ...
making c:/ti/azure-iot-sdks/c/serializer/samples/simplesample_http/tirtos/cc3200
/main/package/cfg/main_pem4.src/sysbios/sysbios.aem4 ...
gmake[1]: Entering directory `c:/ti/azure-iot-sdks/c/serializer/samples/simplesa
mple_http/tirtos/cc3200/main/package/cfg/main_pem4.src/sysbios'
clem4 C:/ti/tirtos_simplelink_2_14_01_20/products/bios_6_42_02_29/packages/ti/sy
sbios/BIOS.c ...
asmem4 C:/ti/tirtos_simplelink_2_14_01_20/products/bios_6_42_02_29/packages/ti/s
ysbios/family/arm/m3/Hwi_asm.sv7M ...
asmem4 C:/ti/tirtos_simplelink_2_14_01_20/products/bios_6_42_02_29/packages/ti/s
ysbios/family/arm/m3/Hwi_asm_switch.sv7M ...
asmem4 C:/ti/tirtos_simplelink_2_14_01_20/products/bios_6_42_02_29/packages/ti/s
ysbios/family/arm/m3/IntrinsicsSupport_asm.sv7M ...
asmem4 C:/ti/tirtos_simplelink_2_14_01_20/products/bios_6_42_02_29/packages/ti/s
ysbios/family/arm/m3/TaskSupport_asm.sv7M ...
arem4 BIOS.obj m3_Hwi_asm.obj m3_Hwi_asm_switch.obj m3_IntrinsicsSupport_asm.obj
 m3_TaskSupport_asm.obj ...
gmake[1]: Leaving directory `c:/ti/azure-iot-sdks/c/serializer/samples/simplesam
ple_http/tirtos/cc3200/main/package/cfg/main_pem4.src/sysbios'
Build of libraries done.
clem4 package/cfg/main_pem4.c ...
"..\..\..\..\inc\agenttypesystem.h", line 602: warning: typedef name has already
 been declared (with same type)
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
n3" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
n4" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
n5" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
n6" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
n2" was declared but never referenced
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
ff3" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
ff4" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
ff5" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
ff6" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
ff2" was declared but never referenced
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_SetAirRe
sistance3" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_SetAirRe
sistance4" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_SetAirRe
sistance5" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_SetAirRe
sistance6" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_SetAirRe
sistance2" was declared but never referenced
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: expression has no effect
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_phantomN
ame2" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_phantomN
ame1" was declared but never referenced
"../../simplesample_http.c", line 107: warning: enumerated type mixed with anoth
er type
"../../simplesample_http.c", line 116: warning: enumerated type mixed with anoth
er type
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_ContosoA
nemometerTurnFanOn1" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
n1" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_ContosoA
nemometerTurnFanOff1" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_TurnFanO
ff1" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_ContosoA
nemometerSetAirResistance1" was declared but never referenced
"../../simplesample_http.c", line 32: warning: variable "eatThese_COMMA_SetAirRe
sistance1" was declared but never referenced
"../../simplesample_http.c", line 32: warning: function "ToAGENT_DATA_TYPE_Conto
soAnemometer" was declared but never referenced
"../../simplesample_http.c", line 74: warning: function "sendMessage" was declar
ed but never referenced
building simplesample_http.out ..
<Linking>
warning: automatic library build: using library
   "C:\ti\ti-cgt-arm_5.2.5\lib\rtsv7M4_T_le_eabi.lib" for the first time, so it
   must be built.  This may take a few minutes.
>> ERROR: mklib: could not find program "gmake", required for building libraries
.  Modify the PATH environment variable to contain a directory containing this p
rogram.
warning: automatic RTS selection:  resolving index library "libc.a" to
   "rtsv7M4_T_le_eabi.lib", but "rtsv7M4_T_le_eabi.lib" was not found

 undefined             first referenced

  symbol                   in file

 ---------             ----------------

 __TI_decompress_none

 __TI_decompress_rle24

 __TI_zero_init

 __aeabi_lmul          C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_ht
tp\tirtos\cc3200\main\package\cfg\main_pem4.src\sysbios\sysbios.aem4<BIOS.obj>
 __aeabi_uidivmod      C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_
29\packages\ti\targets\arm\rtsarm\lib\ti.targets.arm.rtsarm.aem4<System.oem4>
 __aeabi_uldivmod      C:/ti/tirtos_simplelink_2_14_01_20/packages/ti/drivers/li
b/drivers_ccware.aem4<PowerCC3200.oem4>
 _args_main            C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_
29\packages\ti\targets\arm\rtsarm\lib\boot.aem4<boot.oem4>
 _nop                  C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_ht
tp\tirtos\cc3200\main\package\cfg\main_pem4.oem4
 _register_lock        C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_ht
tp\tirtos\cc3200\main\package\cfg\main_pem4.oem4
 _register_unlock      C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_ht
tp\tirtos\cc3200\main\package\cfg\main_pem4.oem4
 abort                 C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_
29\packages\ti\targets\arm\rtsarm\lib\ti.targets.arm.rtsarm.aem4<System.oem4>
 copy_in               C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_
29\packages\ti\targets\arm\rtsarm\lib\auto_init.aem4<auto_init.oem4>
 exit                  C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_
29\packages\ti\targets\arm\rtsarm\lib\ti.targets.arm.rtsarm.aem4<System.oem4>
 main_func_sp          C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_
29\packages\ti\targets\arm\rtsarm\lib\boot.aem4<boot.oem4>
 memcpy                simplesample_http.o

 memset                C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_ht
tp\tirtos\cc3200\main\package\cfg\main_pem4.oem4
 strlen                netwifi.o

error: unresolved symbols remain
error: errors encountered during linking; "simplesample_http.out" not built

>> Compilation failure
gmake: *** [simplesample_http.out] Error 1

c:\ti\azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200>^A

**Comment by dcristoloveanu** [comment]
This happened to me also and I solved this by adding to my path the xdc tools folder, in your case: 
C:\ti\xdctools_3_31_01_33_core
I will add this information to the getting started doc for TI CC3200.

Let me know if this helps.

Thanks,
/Dan

**Comment by olivierbloch** [comment]
Documentation has been updated. we are closing this one.  @bjgross1076 , feel free to re-open if the issue persists for you.
Thanks
