### ISSUE TITLE
Build Azure IoT device SDK for Java from Sources - Build won't run

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#197]
Having followed the instructions, when I attempted to run the code I received the error:
*Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes*
I was able to fix this by adding a filter to the maven shade plugin in java\device\samples\pom.xml as follows:
```xml
<filters>
    <filter>
        <artifact>*:*</artifact>
        <excludes>
            <exclude>META-INF/*.SF</exclude>
            <exclude>META-INF/*.DSA</exclude>
            <exclude>META-INF/*.RSA</exclude>
        </excludes>
    </filter>
</filters>
```

**Comment by olivierbloch** [comment]
We have identified the issue and are working on a fix. Stay tuned.

**Comment by tameraw** [comment]
@markrad - This is has been fixed. Please let us know if you're still having issues.Thanks.
