### ISSUE TITLE
Problem IoTHubClient_CreateFromConnectionString function in C code

### ISSUE THREAD

**Issue by ypkdani** [Azure/azure-iot-sdks#202]
Hello, 

we are trying to use the sdk azure iot library. We have a problem with the function IoTHubClient_CreateFromConnectionString. My code is:

serializer_init(NULL);
IOTHUB_CLIENT_HANDLE iotHubClientHandle = IoTHubClient_CreateFromConnectionString(connectionString, HTTP_Protocol);
ContosoAnemometer* myWeather = CREATE_MODEL_INSTANCE(WeatherStation, ContosoAnemometer);

but the Error: File:../Azure_IOT/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_Create Line:286 underlying transport failed compare. I use a custom board, not an mbed or similar product.

Thanks

**Comment by dcristoloveanu** [comment]
Hi,

I'd be happy to help if I can.
Have you made any modifications to the original azure-iot-sdks code? Based on the fact that you use a custom device I assume yes.
Using the same connection string, is the default Windows or Linux sample working fine?
Which HTTPAPI adapter are you using? Did you write one by yourself or are you using one of the adapters in the SDK?

I'm trying to isolate whether this is an issue with the arguments for the transport (like invalid connection string) or something with the underlying transport code an the HTTPAPI adapter code for the platform that you use.

Thanks,
/Dan

**Comment by ypkdani** [comment]
Hi,

i have taken the c library and clean all the file that are not necessary (sample, doc ..) and imported in eclipse. I use the Freescale Kinetis L with a GSM sim 900 module. In the folder \Azure_IOT\common\adapters i have delete the file not need like said in the tutorial for use the library in other systems and leave blank the functions (that i will implement when i will understand how to do). Trying the code i have that error, i think that in the functions listed in the first post they didn't use the library present in the folder: adapters, or not? This is for understand if are the blank functions that create this error.

Attached my library. Thanks

[Azure_IOT.zip](https://github.com/Azure/azure-iot-sdks/files/73547/Azure_IOT.zip)

**Comment by maxpasquinucci** [comment]
In my case a malloc in the SDK code function create connection tokes from connection string destroy mine string for free up memory

**Comment by dcristoloveanu** [comment]
Hi @ypkdani,
Sorry for the very late reply.
It seems the approach you took to start porting is right.
You might want to snap to the latest release since there were many changes in the internal structure of the project (specifically we have now an azure-c-shared-utility library and we have in-house libraries for AMQP and MQTT).
If you have not resolved your porting issue feel free to post again and we'll do our best to be more responsive.
Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
@maxpasquinucci 
Did you get to reolve your issue in anyway?
If not and your issue still reproes with the latest release we have, could you open a new issue and post the call stack and I'll do my best to help debug it.

Thanks,
/Dan

**Comment by tameraw** [comment]
@maxpasquinucci - Please feel free to reopen if still having issues. Thanks.

**Comment by maxpasquinucci** [comment]
Thanks a lot for replying, I m at the moment on a different project so forgive me for not reply before now.  I see new git repo for sdk support library and changed mine project with new sdk git structure.  I hope I can work soon on this. Mine client have a http class so I can also use rest api. I fond a problem to generate SAS key from device key as you do in sdk from Javascript using base64 encode and sha256,  it doesn't create correct sak and fail authentication.  
After authentication I need to manage messages as you do in sdk.  
Thanks thought 
Inviato da Libero Mail per Android martedì, 23 febbraio 2016, 08:35PM +01:00 da tameraw < notifications@github.com> :
