### ISSUE TITLE
Ardunio Yun sample build error

### ISSUE THREAD

**Issue by burakdm** [Azure/azure-iot-sdks#203]
I'm getting this error when runing build.sh in  ardunio folder. Can you help me?

[ 99%] Linking C executable simplesample_http
../../libserializer.a(agenttypesystem.c.o): In function `AgentDataTypes_ToString':
agenttypesystem.c:(.text+0xf34): undefined reference to `__isnanf'
agenttypesystem.c:(.text+0xf88): undefined reference to `__isinff'
agenttypesystem.c:(.text+0xf98): undefined reference to `__signbitf'
agenttypesystem.c:(.text+0x10dc): undefined reference to `__isnan'
agenttypesystem.c:(.text+0x1134): undefined reference to `__isinf'
agenttypesystem.c:(.text+0x1148): undefined reference to `__signbit'
collect2: ld returned 1 exit status

**Comment by ramonmata** [comment]
Getting the same error with the master branch

**Comment by burakdm** [comment]
Is there any progress about this bug ?
or 
Is there any solution run this sdk to openwrt ?

**Comment by tameraw** [comment]
@burakdm - Please try against the "develop" branch and report here if you're still having issue. Thanks.

**Comment by burakdm** [comment]
@tameraw thanks for answer. But i getting another error develop branch when run build script .
Also i 've got same error at master branch.
Here is log:

- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:27 (add_subdirectory):
  add_subdirectory given source "azure-c-shared-utility/c" which is not an
  existing directory.


-- Configuring incomplete, errors occurred!
See also "/home/bd/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/CMakeFiles/CMakeOutput.log".
make[2]: *** [/home/bd/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/.configured_] Error 1
make[2]: Leaving directory `/home/bd/openwrt/sdk/package/azure-iot-sdks'
make[1]: *** [package/azure-iot-sdks/compile] Error 2
make[1]: Leaving directory `/home/bd/openwrt/sdk'
make: *** [package/azure-iot-sdks/compile] Error 2
bd@bd-VirtualBox:~/azure-iot-sdks-develop/c/build_all/arduino$
.

**Comment by burakdm** [comment]
@tameraw :
Ok i copied manually "azure-c-shared-utility" folder from Azure-iot-sdks to developer branch folder. 
After that i run build script  and  sample package created for open wrt succesfully.

**Comment by tameraw** [comment]
@burakdm - Thanks for confirming that you're able to build successfully. Closing this issue, and please feel free to re-open if you're still having problems.
