### ISSUE TITLE
HTTPAPIEX error on TI cc3200 

### ISSUE THREAD

**Issue by DeepaBellary** [Azure/azure-iot-sdks#209]
Hi Team,

We are working on cc3200 launch pad board with Microsoft azure in windows 7 (32-bit operating system).

We are able to build the simplesample_http project provided along with SDK and flashed it in cc3200 launch pad board. 
After flashing to launch pad board, we are able to connect to IoTHub successfully, but following error is seen while sending the messages. 
 
 Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state

Snapshot
![iotsdk](https://cloud.githubusercontent.com/assets/16488608/12064164/10b77a94-afe2-11e5-87a9-cda9a499d397.jpg)

Please help in resolving this issue.

Thanks,
Deepa

**Comment by tameraw** [comment]
@DeepaBellary - Thanks for submitting your issue. We're looking at this issue and will update you here soon.

**Comment by ashokkhurana** [comment]
Could you please try it again on our latest SDK. Looks like the SDK version you were using when you encountered this issue was old 1.0.0-preview.7 and we are running 1.0.0-preview.9 currently and we were 1.0.0-preview.8 when this issue was reported.

**Comment by DeepaBellary** [comment]
After debugging we figured out that the issue was due to the way we flashed the certificate to board. 
Name of the certificate was not matching the one defined in code. 

Resolved after flashing it as /cert/ms.der

Thanks

**Comment by alexdg18** [comment]
Hi I am having kind of the same error,I have done the servipack update.I wasnt sure about how to flash the certificate so I did it as follows:
-Formatted the cc3200 with 1MB capacity
-Added new file then ,name :/cert/ms.der  ,url:  \azure-iot-sdks\c\certs\ms.der.
-the .bin to the /sys/mcuimg.bin under System Files

I have checked erase, update ,verify check boxes as specified by http://processors.wiki.ti.com/index.php/CC31xx_%26_CC32xx_UniFlash#GUI_Interface

the error:
Info: IoT Hub SDK for C, version 1.0.0-preview.9
IoTHubClient accepted the message for delivery
Error: Time:Wed Aug 23 09:48:40 2028 File:../../adapters/httpapi_tirtos.c Func:H                                                                                                 TTPAPI_CreateConnection Line:67 HTTPCli_initSockAddr failed, ret=-106
Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_E                                                                                                 xecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Thu May 13 16:10:32 2032 File:../../src/iothubtransporthttp.c Func:D                                                                                                 oEvent Line:1212 unable to HTTPAPIEX_ExecuteRequest
Error: Time:Thu May 13 16:10:32 2032 File:../../adapters/httpapi_tirtos.c Func:H                                                                                                 TTPAPI_CreateConnection Line:67 HTTPCli_initSockAddr failed, ret=-106
Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_E                                                                                                 xecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Thu May 13 16:10:32 2032 File:../../src/iothubtransporthttp.c Func:D
