### ISSUE TITLE
 node / device / samples / remote_monitoring.js -> send event error: Error: Unauthorized

### ISSUE THREAD

**Issue by neevedr** [Azure/azure-iot-sdks#210]
After a period of time the node sample remote_monitoring.js gives the error: **Error: Unauthorized**. Looks like some kind of timeout. 

```
Sending device event data:
{"DeviceId":"raspberrypi","Temperature":19.3,"Humidity":58.7}
Sending device event data:
{"DeviceId":"raspberrypi","Temperature":19.3,"Humidity":58.7}
Sending device event data:
{"DeviceId":"raspberrypi","Temperature":19.3,"Humidity":58.7}
Sending device event data:
{"DeviceId":"raspberrypi","Temperature":19.3,"Humidity":58.7}
send event error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
Sending device event data:
{"DeviceId":"raspberrypi","Temperature":19.3,"Humidity":58.7}
receive error: Error: Unauthorized
send event error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
Sending device event data:
{"DeviceId":"raspberrypi","Temperature":19.3,"Humidity":58.8}
receive error: Error: Unauthorized
send event error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
Sending device event data:
{"DeviceId":"raspberrypi","Temperature":19.3,"Humidity":58.8}
receive error: Error: Unauthorized
send event error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
receive error: Error: Unauthorized
```

**Comment by damonbarry** [comment]
When you create a device client from a connection string (which is what this sample is doing), under the hood the SDK generates a shared access signature--a temporary token that times out after an hour. Currently we don't have any logic in the device SDK to automatically refresh the token, or to allow you to specify your own token and refresh it manually.  Those tasks are on our backlog. In the meantime you have to manage the timeout yourself by creating a new client.

In the future, we plan to add the following:
- azure-iot-device.Client.fromSharedAccessSignature(token) (similar to what we already have in the service client, i.e., azure-iothub.Client)
- logic to automatically refresh the token if the user created the client via fromConnectionString()
- something like azure-iot-device.Client#updateSharedAccessSignature(token) so users can manually manage their token without having to create a new client

**Comment by pierreca** [comment]
SAS token auto-renewal and the APIs that @damonbarry suggested have been added in the latest release of the SDK. closing this for now, please re-open if you still observe the issue.
