### ISSUE TITLE
IoTHubExplorer unable to monitor events on user created Consumer group

### ISSUE THREAD

**Issue by rgknp** [Azure/azure-iot-sdks#214]
Assuming that there is a $Default consumer group where events can be consumed.
 
Customer has asked that they want to monitor device message without actually “consuming” it.
They have two team, one responsible for Device client app and other for Service app.
Device client app team would like to test their side without actually impacting Service client.
This can be done if there are more than one consumer groups available.
 
I added a new Consumer Group “telemetrycg” but how do monitor using IoTHubExplorer for the new consumer group. I only see it monitors $Default CG.
 
C:\Users\rahgupt>iothub-explorer HostName=iotdemorg.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=6p7V6MReibYdcONA5pMqXbSTEBEk/wWJGn/8bqbPaxE= monitor-events mydemodevice
 
Monitoring events from device mydemodevice
Listening on endpoint iotdemorg/ConsumerGroups/$Default/Partitions/0 start time: 1452029987343
Listening on endpoint iotdemorg/ConsumerGroups/$Default/Partitions/1 start time: 1452029987343
Listening on endpoint iotdemorg/ConsumerGroups/$Default/Partitions/2 start time: 1452029987343
Listening on endpoint iotdemorg/ConsumerGroups/$Default/Partitions/3 start time: 1452029987343

**Comment by damonbarry** [comment]
Thanks for opening this issue.  We're working to round out the Event Hubs logic (take a look at the [node folder in the develop branch of the azure-event-hubs repo](https://github.com/Azure/azure-event-hubs/tree/develop).  Once we have that, we'll add a --consumer-group option to the iothub-explorer CLI.

**Comment by tameraw** [comment]
@rgknp - Thanks for submitting this request. We believe this is an important feature and have captured it in our product backlog to bring in soon.
