### ISSUE TITLE
C SDK

### ISSUE THREAD

**Issue by pbreed** [Azure/azure-iot-sdks#215]
The C SDK should be called C++ SDK, as it uses a lot of C++ features such as templates and the C++ standard library and is not appropriate for a lightweight IOT device. 

It would also be useful if there was some discussion on the TLS/SSL requirements required to inter operate, not everyone runs Linux and openssl.  Does it require client side certs? What ciphers suites are acceptable all this information is either missing or hard to find when looking at the docs.

**Comment by tameraw** [comment]
@pbreed - Currently our mocking framework is a c++ one which enforces us to have our tests written in C++. Note that the client sdk libs that end up being part of the application running on devices are c code (mostly c99 plus the usage of __COUNTER__). Long term we might switch to purely c based tests.
As for TLS/SSL, we will add more information on that in our porting guide.

**Comment by pablosun** [comment]
The C SDK requires GCC 4.9+ (https://github.com/Azure/azure-iot-sdks/blob/master/doc/iotcertification/iot_certification_linux_c/iot_certification_linux_c.md). 

Is there a specific reason that GCC 4.8 won't be compliant? We are now working on a embedded system with GCC 4.8 as the primary cross-compilation toolchain, and would like to know if GCC 4.8 would work without potential risks.

**Comment by tameraw** [comment]
@pablosun - There should not be a problem using GCC4.8 (for example, for our Arduino Yun instructions, we are using GCC4.6 today).

**Comment by rabbitom** [comment]
I'm cross-compiling c sdk with a toolchain for mips target, and I encounter some troubles compiling c++ files. Is it possilbe to skip all c++ files when compiling?

**Comment by dcristoloveanu** [comment]
There is a cmake option (skip_unittests) which will skip building the unit tests. The following configuration should not build unit tests:

skip_unittests = 1
run_e2e_tests = 0
run_longhaul_tests = 0

Let me know if this helps.

Thanks,
/Dan

**Comment by rabbitom** [comment]
@dcristoloveanu - I used the --skip-e2e-tests and --skip-unittests options(longhaul tests is off by default), but some tests are stil built. So I added a "--no-tests" option to build.sh and made a pull request.

**Comment by tameraw** [comment]
@rabbitom - PR under review. Thanks.

**Comment by tameraw** [comment]
@rabbitom - Please address comments on the PR. Thanks.

**Comment by tameraw** [comment]
Closing. Please reactivate if still having issues.
