### ISSUE TITLE
feedback acks in node (maybe) inconsistent with REST API docs

### ISSUE THREAD

**Issue by epaulson** [Azure/azure-iot-sdks#219]
This might be more of an issue with the MS docs than the SDK code, but there are some minor inconsistencies with URI parameters and headers for handling cloud to device messages.

In the C2D REST API doc, for 'Completing' a C2D device from the device side:
https://msdn.microsoft.com/en-us/library/azure/mt605155.aspx

I'm pretty sure the URI is wrong for complete and is missing either the message ID, or the lock token ID - the docs for the abandon and reject REST calls both include the "message sequence number"  in the URI and the "message lock id" in the headers as an "If-Match" key.

In looking at the Javascript client library for the device, it includes the "lockToken" in both the headers and the URI for complete, abandon, and reject. 
https://github.com/Azure/azure-iot-sdks/blob/master/node/device/lib/http.js

So I certainly think the docs for 'Complete' are missing a part of the URI - but it's unclear to me exactly what they're missing - are the 'lock token', the 'message sequence number" and the "message lock id" all the same thing?

There is a 'message ID' in the code and the code treats messageID and lock token as different things: 

https://github.com/Azure/azure-iot-sdks/blob/master/node/common/lib/http.js 

Sorry if this is the wrong place to open issues on MSDN documentation. (I love that Microsoft is doing most of its articles as Markdown on GH though!)

**Comment by olivierbloch** [comment]
Hi @epaulson 
you are correct, the doc was out of date when you faced the issue and there should have been the etag for the device at the end of the URI.
The doc has since been fixed.
