### ISSUE TITLE
Java Service SDK: newly created devices are disabled by default and can't be enabled

### ISSUE THREAD

**Issue by bossie** [Azure/azure-iot-sdks#225]
It seems that when one creates a new `Device` and adds it to the IoT Hub device registry using the `RegistryManager` it is disabled, simply because its status is set to `DeviceStatus.Disabled` in the `Device` constructor, and a `Device` object is immutable.

Also, even though `RegistryManager` has an `updateDevice()` method, the device cannot be updated because this method accepts a `Device` and again, it is immutable.

I have a workaround for the first problem in the form of an anonymous inner class with an initializer block that is kind of doable:

```java
Device device = new Device(deviceId) {{ status = DeviceStatus.Enabled; }};
registryManager.addDevice(device);
```

Updating an existing device is still a pain, however.

This kind of functionality is so trivial I'm starting to think I'm missing something here. Any thoughts?

**Comment by tameraw** [comment]
@bossie - A fix has been checked-in into our develop branch. Closing the issue and please feel free to reopen if you are still having problems.
Thanks.
