### ISSUE TITLE
Exception Handling - Public Exceptions

### ISSUE THREAD

**Issue by ruttopia** [Azure/azure-iot-sdks#226]
It is currently very difficult to properly handle exceptions in a Universal Windows App due to all the exceptions being internal.  The following lines is present in every Exception derived class:

#if !WINDOWS_UWP // Exporting custom exception types is not allowed in WinRT
public
#endif

Does this actually apply to UWP apps?  I am able to export custom exception types without issue in all my UWP apps.

Making all the derived Exceptions public would make exception handling much easier in UWP apps.

**Comment by tameraw** [comment]
@ruttopia - Thanks for your suggestion. We have captured your request in our backlog and will be addressing it in a future release.

**Comment by arturl** [comment]
Hi @ruttopia,

This is part of the restrictions on WinRT components (see [here](https://msdn.microsoft.com/en-us/library/br230301.aspx#ThrowingExceptions)).

We could introduce HRESULT codes that correspond to specific exception types, but that would require the client code to do error code translation.
