### ISSUE TITLE
services bus vs iothub

### ISSUE THREAD

**Issue by MZDN** [Azure/azure-iot-sdks#227]
I could see in the SDK for c you are supporting azure iothub but not service bus. Are there any reason for this choice? Thanks!

**Comment by matlus** [comment]
I'd second this for the .NET SDK as well. Simple example for using the HTTPS and AMQP protocols for ServiceBus

**Comment by olivierbloch** [comment]
Hello,
Azure IoT Hub is a service that is NOT part of Service Bus like Event Hub is. It uses a different authentication mechanism and exposes its own APIs.
This SDK is for developing against IoT Hub, not against Service Bus services like Event Hub.
Hope this answers the question
Olivier

**Comment by MZDN** [comment]
@olivierbloch many thanks for your reply!
