### ISSUE TITLE
Instructions not complete for beginners like me (Arduino Yun) - Build Failed

### ISSUE THREAD

**Issue by btusca** [Azure/azure-iot-sdks#229]
Hi!
I followed the instructions step by step.
### Requirements: 
**Git** - Check
**Arduino Yun** - Check
**Debian** - I installed it in vmware 10 - Debian 8

### Setup the development environment
**Clone this repository (azure-iot-sdks) to the machine you are using**. - Check, BUT it says to do it under root/sudo but this will cause problems when you wanna try to build it and you will have to copy all the repository to user maker folder. (same with openwrt sdk folder)

**Run the setup.sh script to install the OpenWRT SDK and prerequisites.**
Ok, here is where problems starts again:
1. Following instructions, I had to copy azure-iot-sdks and openwrt folders outside root folder, if not, build doesn't work.
2. I had to install *apt-get install lib32z1*
3. I had to clone *azure-c-shared-utility* in c folder
4. I had to install *apt-get install build-essential*

And build still not working. This is the log:

>root@debian:/home/administrador/azure-iot-sdks/c/build_all/arduino/azure-iot-sdks/c/build_all/arduino# su administrador ./build.sh
Building IoT
Collecting package info: done
WARNING: your configuration is out of sync. Please run make menuconfig, oldconfig or defconfig!
make[1]: Entering directory '/home/administrador/openwrt/sdk'
make[2]: Entering directory '/home/administrador/openwrt/sdk/package/azure-iot-sdks'
mkdir -p /home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1
cp -fpR ./src/c/* /home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/
touch /home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/.prepared_2fc5b556ff6f893d2c1df2810fd3816b
IN_OPENWRT=1 TARGET_CPPFLAGS="-I/home/administrador/openwrt/sdk/staging_dir/target-mips_r2_uClibc-0.9.33.2/usr/include -I/home/administrador/openwrt/sdk/staging_dir/target-mips_r2_uClibc-0.9.33.2/include -I/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/usr/include -I/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/include" TARGET_CFLAGS="-Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -DIN_OPENWRT" TARGET_LDFLAGS="-L/home/administrador/openwrt/sdk/staging_dir/target-mips_r2_uClibc-0.9.33.2/usr/lib -L/home/administrador/openwrt/sdk/staging_dir/target-mips_r2_uClibc-0.9.33.2/lib -L/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/usr/lib -L/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/lib" AR="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-ar" AS="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-gcc -c -Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float" LD="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-ld" NM="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-nm" CC="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-gcc" GCC="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-gcc" CXX="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-g++" RANLIB="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-ranlib" STRIP="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-strip" OBJCOPY="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-objcopy" OBJDUMP="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-objdump" cmake -DCMAKE_FIND_ROOT_PATH="/home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2" /home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/CMakeLists.txt -DIN_OPENWRT=1 -Duse_amqp:bool=OFF -Duse_http:bool=ON -Duse_mqtt:bool=OFF -Dskip_unittests:bool=ON -Duse_floats:bool=OFF -Duse_condition:bool=OFF
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-gcc
-- Check for working C compiler: /home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-g++
-- Check for working CXX compiler: /home/administrador/openwrt/sdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
>
>   use_condition
>
>
>-- Build files have been written to: /home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1
rm -f /home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/.configured_*
touch /home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/.configured_
make -C /home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1
make[3]: Entering directory '/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1'
make[4]: Entering directory '/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1'
make[5]: Entering directory '/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1'
Scanning dependencies of target aziotsharedutil
make[5]: Leaving directory '/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1'
make[5]: Entering directory '/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1'
**[  0%] Building C object azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/src/base64.c.o
mips-openwrt-linux-uclibc-gcc: error: unrecognized option '--std=c11'**
**azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/build.make:54: recipe for target 'azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/src/base64.c.o' failed**
make[5]: *** [azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/src/base64.c.o] Error 1
make[5]: Leaving directory '/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1'
CMakeFiles/Makefile2:80: recipe for target 'azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/all' failed
make[4]: *** [azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/all] Error 2
make[4]: Leaving directory '/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1'
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1'
Makefile:86: recipe for target '/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/.built' failed
make[2]: *** [/home/administrador/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/.built] Error 2
make[2]: Leaving directory '/home/administrador/openwrt/sdk/package/azure-iot-sdks'
package/Makefile:105: recipe for target 'package/azure-iot-sdks/compile' failed
make[1]: *** [package/azure-iot-sdks/compile] Error 2
make[1]: Leaving directory '/home/administrador/openwrt/sdk'
/home/administrador/openwrt/sdk/include/toplevel.mk:151: recipe for target 'package/azure-iot-sdks/compile' failed
make: *** [package/azure-iot-sdks/compile] Error 2

How should I proceed? 

I just followed the instructions and I add some steps. I don't know if I missing some kind of 'another instructions' or if i have to install anything else.  Did you install anything else to build?

Thanks a lot!

I hope I can contribute with you once I get this set up

**Comment by tameraw** [comment]
@btusca - Thanks for submitting your issue. We have just gone through an update of our Yun instructions: 

https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_sample_on_arduino_yun.md

Please follow through the updated instructions and let us know if you're still having any issues.
Thanks.
-Tamer

**Comment by btusca** [comment]
Oh, thanks tameraw!!

I will give it a try this week!

I'll keep you post!

**Comment by tameraw** [comment]
@btusca - Please feel free to reopen if still having issues after trying the latest Yun instructions.
