### ISSUE TITLE
Error in Microsoft.Azure.Devices.Client

### ISSUE THREAD

**Issue by QiMata** [Azure/azure-iot-sdks#230]
I am getting this error whenever I call RecieveAsync or SendEventAsync using DeviceClient.

Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.ServerErrorException' in mscorlib.ni.dll
{"Message":"2ef6bf7a6ed34bc0af9ea3182c837ad6-G:0-TimeStamp:01/18/2016 19:25:41"}:Error in sample: {0}

you can recreate by starting up the UWP demo and trying it.

**Comment by tameraw** [comment]
@QiMata - Hello. I tried the sample located at: https://github.com/Azure/azure-iot-sdks/tree/master/csharp/device/samples/UWPSample
I was able to send events to IoTHub and receive messages from IoTHub with no issues. Can you please provide more info on how you hit this error exactly? Thanks!

**Comment by QiMata** [comment]
Getting it just having launched the UWP in debug on a RP2. Updating the IoT Core image and trying again. Will update with more info if that doesn't work. If it does, will just update you.

**Comment by QiMata** [comment]
Reinstalling the IoT Core image onto the PI fixed it. Not sure what the exact error was but it may be incompatible with older versions? Thank you for taking a look into this for me.

**Comment by tameraw** [comment]
@QiMata - Thanks for your update. Please feel free to reopen if still having issues.
