### ISSUE TITLE
Missing method for creating Client from a SAS token in Node SDK

### ISSUE THREAD

**Issue by liushuping** [Azure/azure-iot-sdks#233]
There is only one method in `client.js` from Node SDK for creating a Client which is `fromConnectionString`.

But there are also cases that device does not own the symmetric key, and it requests SAS token from IoT hub to send messages. So, need extra method to instantiate a client with a SAS token.

**Comment by tameraw** [comment]
@liushuping - Thanks for your feature request. We have captured this in our backlog and will be addressed in a future release.

**Comment by tameraw** [comment]
@liushuping. While we captured this in our backlog, I wanted to point out, if this is an urgent ask and would like to contribute the feature, please follow the instructions in our document: https://github.com/Azure/azure-iot-sdks/blob/master/contribute.md

**Comment by pierreca** [comment]
Added in v1.0.0
