### ISSUE TITLE
C SDK - Ubuntu build fails 3 tests

### ISSUE THREAD

**Issue by QiMata** [Azure/azure-iot-sdks#237]
Tried a few times with a clean Ubuntu 14.04 build on VMWare Workstation 12. After following the guide I get this:

95% tests passed, 3 tests failed out of 57

Total Test time (real) =   7.02 sec

The following tests FAILED:
	 33 - iothubclient_amqp_e2etests (Failed)
	 35 - iothubclient_http_e2etests (Failed)
	 57 - serializer_e2etests (Failed)
Errors while running CTest

**Comment by tameraw** [comment]
@QiMata - For end to end tests one need to setup some environment variables with the proper credentials. Here is the instruction on how to run end-to-end test.
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_end_to_end_tests.md

Please post back if you are still having issues. Note, this is not a prerequisite for running the sample.

**Comment by tameraw** [comment]
@QiMata - Please feel free to reopen if still having issues.
