### ISSUE TITLE
Enable IEventProcessor to receive ACK messages from devices as an alternative to ServiceClient.GetFeedbackReceiver()

### ISSUE THREAD

**Issue by andrzej518** [Azure/azure-iot-sdks#243]
I have an extended app logic for ACK workflow and it's cumbersome to use `ServiceClient.GetFeedbackReceiver()`, especially when there are many processors registered.

It would be very useful to be able to receive message acknowledges through registered IoT Hub `IEventProcessor` object. For instance:

    Task IEventProcessor.ReceiveFeedbackAsync(PartitionContext context, FeedbackBatch feedbacks)

**Comment by tameraw** [comment]
@andrzej518 - Thanks for the suggestion. We will evaluate this new feature request and respond back.

**Comment by gustafsonk** [comment]
I would really like something like this so we can use consumer groups for the feedback messages. It's too easy right now for someone to check the Monitor Feedback Endpoint checkbox in the Device Explorer tool and not realize they're 'stealing' messages from another process that's trying to archive the status of each feedback for later retrieval.

**Comment by tameraw** [comment]
We'll consider adding this in a future release. However, we would happily accept contributions if you decide to submit a pull request for this. Thanks.

**Comment by nberdy** [comment]
This is work that must be done on the service itself, not a client ask, so I'm closing this request to track in the service backlog.
