### ISSUE TITLE
Error when AMQPClient tries to reconnect in Node

### ISSUE THREAD

**Issue by dmoreland** [Azure/azure-iot-sdks#249]
```javascript
TypeError: self._reconnect is not a function
    at AMQPClient._attemptReconnection (C:\Source\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\amqp_client.js:330:15)
    at null._onTimeout (C:\Source\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\amqp_client.js:136:21)
  at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by pierreca** [comment]
interesting. looks like an error in node-amqp10 more than in the SDK, I'll talk to them.
is it something you observed once only? do you have a bit of code or a procedure to repro the issue?

Thanks!

**Comment by noodlefrenzy** [comment]
Exactly what I was going to say. I'll open an issue against node-amqp10.

**Comment by dmoreland** [comment]
It happens after i leave the code sending messages for about an hour

**Comment by pierreca** [comment]
Alright, if it's after an hour it's probably because the SAS token has expired. currently the only way to regenerate it is to create a new client, but we do have that captured in our backlog and shall come up with a solution very soon

**Comment by dmoreland** [comment]
Ok that's fine i will add something too capture the issue in my code

**Comment by noodlefrenzy** [comment]
Regardless, amqp10 shouldn't be spitting dumb errors like that in that case, so I'll try and trap it on my end and see if we can do something more graceful. Thanks for reporting.

**Comment by pierreca** [comment]
We checked in auto-renewal of the SAS token with our 1.0.0 release, so this should be fixed. Please let us know if you still see the issue with the new packages.
