### ISSUE TITLE
Java SDK uses library unavailable in Android by default

### ISSUE THREAD

**Issue by gustafsonk** [Azure/azure-iot-sdks#25]
So I succeeded in getting the Java IoT SDK running on Android and most of the process was pretty smooth. I encountered one issue that I was wondering could be changed to make the process smoother for others that try to run on Android.

The SignatureHelper.java file imports javax.xml.bind.DatatypeConverter, which is not implemented in Android for whatever reason. It's only use in the SignatureHelper class is for converting between a byte[] and a base64 string. I was able to pull in the 6 .java files from javax.xml.bind that were required for it to build and run (DatatypeConverter, DatatypeConvertImpl, DatatypeConverterInterface, JAXBPermission, Messages, WhiteSpaceProcessor).

Could this be changed so that the SDK does its own conversion or something similar? Thanks.

**Comment by dcristoloveanu** [comment]
We could definitely look at writing our own byte[] -> base64 translation, we already do that in the C SDK, so the Java code could only be simpler :-). Also if you need this right away and you end up having a stab at it let us know and we'd love to do a PR.

**Comment by dcristoloveanu** [comment]
Let's discuss the Base64 issues on PR #35.

**Comment by btusca** [comment]
Hi! How did you do to get working azure-iot-sdk on Android Studio??
