### ISSUE TITLE
Cannot quit iothub-explorer tool in Windows

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdks#251]
In Windows, Ctrl-C to quit the following commands doesn't work:

```
node iothub-explorer receive myFirstDevice
node iothub-explorer monitor-events myFirstDevice
```

**Comment by tameraw** [comment]
@dominicbetts - Thanks for reporting the issue. We'll investigate it.

**Comment by olivierbloch** [comment]
This issue seem to be resolved now. Feel free to reopen the issue if you see this behavior again
Thanks
