### ISSUE TITLE
Unable to create device identity in asp.net web application

### ISSUE THREAD

**Issue by arminhaghi** [Azure/azure-iot-sdks#253]
Hi, I'm trying to have a webpage for registering new devices in our IoT Hub instance through a web platform, but the async method never resolves and eventually the web page times out.

Here's a the part of the code:

[HttpPost]
[ValidateAntiForgeryToken]
public ActionResult Create([Bind(Include = "xxxxxxxxxxxxxx")] Hubs hubs)
{

RegistryManager registryManager;
string connectionString = "xxxxxxxxxxxxxxxx;
registryManager = RegistryManager.CreateFromConnectionString(connectionString);

string deviceId = hubs.DeviceID;
System.Threading.Tasks.Task<Device> device;

try
{
        device = registryManager.AddDeviceAsync(new Device(deviceId));
}
catch (DeviceAlreadyExistsException)
{
        //Alert device already exists!
        return RedirectToAction("Index");
}

//This is where it never resolves, I have tried different ways, and all will hame the timeout issue at some point.
hubs.DeviceKey = device.Result.Authentication.SymmetricKey.PrimaryKey;

return View(hubs);
}

**Comment by dmoreland** [comment]
You need to await the result of AddDevice otherwise the code will continue execution before its completed.

**Comment by tameraw** [comment]
@arminhaghi & @dmoreland - Thank you for contributions. Closing this issue as it's been answered.
