### ISSUE TITLE
Java RegistryManager.GetDevices max count parameter is not respected

### ISSUE THREAD

**Issue by jasoneilts** [Azure/azure-iot-sdks#258]
ArrayList<Device> registeredDevices = this.registryManager.getDevices(100);

Returns a list of >600 in my case.

**Comment by tameraw** [comment]
@jasoneilts - Thank you Jason for reporting this. We'll address it.

**Comment by iluican** [comment]
We fixed the client side, but it's not enough. Service will need to be fixed as well, and there is a bug tracking this issue.
