### ISSUE TITLE
Ardunio Yun Certificate link broken

### ISSUE THREAD

**Issue by burakdm** [Azure/azure-iot-sdks#261]
Hi;
The link that you write at Ardunio Yun sample documentation for installing Certificates gives 404 not found  error.

 https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/base/ca-certificates_20151214_ar71xx.ipk

**Comment by tameraw** [comment]
@burakdm - Thanks for reporting your issue. We'll investigate and update you soon.

**Comment by ashokkhurana** [comment]
Hi Burakdm,

Looks like the certificate version has changed and thus the link is broken. Could you please try  https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/base/ca-certificates_20160104_all.ipk link which is the link to updated version of ceretificate. We'll have our documentation updated soon.

Thanks,
Ashok

**Comment by tameraw** [comment]
@burakdm - closing as fixed. Thanks.

**Comment by burakdm** [comment]
thanks for your support.
