### ISSUE TITLE
Building issue after run build.sh (os ubuntu)

### ISSUE THREAD

**Issue by mzaky** [Azure/azure-iot-sdks#262]
~/git/azure-iot-sdks/c/build_all/linux$ ./build.sh
...
[ 60%] Building C object iothub_client/tests/iothubtransportamqp_unittests/CMakeFiles/iothubtransportamqp_unittests_exe.dir/__/__/src/iothubtransportamqp.c.o
/home/user/git/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c: In function ‘processCBSReply’:
/home/user/git/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c:1256:9: warning: implicit declaration of function ‘pn_messenger_release’ [-Wimplicit-function-declaration]
         pn_messenger_release(transportState->messenger, tracker, 0);
         ^
[ 60%] Building C object iothub_client/tests/iothubtransportamqp_unittests/CMakeFiles/iothubtransportamqp_unittests_exe.dir/main.c.o
Linking CXX executable iothubtransportamqp_unittests_exe
CMakeFiles/iothubtransportamqp_unittests_exe.dir/__/__/src/iothubtransportamqp.c.o: In function `processCBSReply':
iothubtransportamqp.c:(.text+0x2eca): undefined reference to `pn_messenger_release'
CMakeFiles/iothubtransportamqp_unittests_exe.dir/__/__/src/iothubtransportamqp.c.o: In function `processMessage':
iothubtransportamqp.c:(.text+0x2fe3): undefined reference to `pn_messenger_release'
iothubtransportamqp.c:(.text+0x30bd): undefined reference to `pn_messenger_release'
iothubtransportamqp.c:(.text+0x3187): undefined reference to `pn_messenger_release'
iothubtransportamqp.c:(.text+0x322f): undefined reference to `pn_messenger_release'
CMakeFiles/iothubtransportamqp_unittests_exe.dir/__/__/src/iothubtransportamqp.c.o:iothubtransportamqp.c:(.text+0x32d7): more undefined references to `pn_messenger_release' follow
collect2: error: ld returned 1 exit status
make[2]: *** [iothub_client/tests/iothubtransportamqp_unittests/iothubtransportamqp_unittests_exe] Error 1
make[1]: *** [iothub_client/tests/iothubtransportamqp_unittests/CMakeFiles/iothubtransportamqp_unittests_exe.dir/all] Error 2
make: *** [all] Error 2

**Comment by ashokkhurana** [comment]
Hi,

Could you please let us know which GITHUB repo you are using and path to the instruction document that you are following. Also what's the Ubuntu version that you are trying on? 

I tried step by step instruction available at https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_sample_on_arduino_yun.md and I don't see any issue when building the libraries on my Ubuntu 14.04 box. If your instruction document was different, could you please try again using the instructions in above link and let us know how it goes.

Thanks,
Ashok

**Comment by ashokkhurana** [comment]
Hi,

We need some more information to troubleshoot it further.

Could you please share the instruction document that you are using? What's the Ubuntu version you are using and which GITHUB repo you are using?

Thanks,
Ashok

**Comment by tameraw** [comment]
@mzaky - Closing for none response. Please feel free to reopen if the issue persists.
