### ISSUE TITLE
Installation of Qpid JMS is failing because of test failure on Windows 10 with Java libraries

### ISSUE THREAD

**Issue by v-pravek** [Azure/azure-iot-sdks#27]
TransportSupportTest.testCreateSslContextIncorrectStoreType test is failing. 
Note: By skipping tests using "mvn clean install -DskipTests" further steps are working as expected. 

![qpidjmsinstallationfailure](https://cloud.githubusercontent.com/assets/13991281/10305720/95954aac-6c3f-11e5-92fb-255c27337ab3.jpg)
reateSslContextIncorrectStoreType

**Comment by andrew-buckley** [comment]
@v-pravek, please double check your java version. If you are not using Java SE 1.7 please install that, update your environment variables, and try to do a "mvn clean install" again.

**Comment by v-pravek** [comment]
I was using Java SE 1.8. Issue is not repro with Java SE 1.7. Closing the issue.
