### ISSUE TITLE
Build failure on Beagle Bone Black?

### ISSUE THREAD

**Issue by kasebe** [Azure/azure-iot-sdks#273]
[build_sh.txt](https://github.com/Azure/azure-iot-sdks/files/115158/build_sh.txt)

I'd like to access from Beagle Bone Black to Azure while referring to below URL.
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_sample_on_beaglebone_black_debian.md

However, "/cmake" directory isn't make.(It seems execute binary for Debian is included.)
My setup and build procedure as shown below.

-----
[[Beagle Bone Black setup]]
Referred to below URL.
http://elinux.org/BeagleBoardDebian
PC linux is Ubuntu 12.04LTS.

1.Get jessie prebuild image.
#wget https://rcn-ee.com/rootfs/2016-01-14/elinux/debian-8.2-console-armhf-2016-01-14.tar.xz

2.Unpack image
#tar xf debian-8.2-console-armhf-2016-01-14.tar.xz
#cd debian-8.2-console-armhf-2016-01-14

3.Install to SD card
#./setup_sdcard.sh --mmc /dev/mmcblk0 --dtb beaglebone

4.Rename from bbb-uEnv.txt to uEnv.txt
#mv /media/rootfs/bbb-uEnv.txt /media/rootfs/uEnv.txt

[[Build simplesample_amqp for Debian/Beagle Bone Black]]
1.Change to root authority
$sudo su

2.Install the prerequisite packages for the device SDK
#apt-get update
#apt-get install -y curl libcurl4-openssl-dev uuid-dev uuid g++ make cmake git unzip openjdk-7-jre

3.Download the Azure IoT device SDK to Beagleboneblack
#cd /home
/home#git clone https://github.com/Azure/azure-iot-sdks.git
/home#ls
azure-iot-sdks  debian

4.Change directory to azure-iot-sdks
/home#cd azure azure-iot-sdks

5.Modified "./c/serializer/samples/simplesample_amqp/simplesample_amqp.c" for device connection string
/azure-iot-sdks#nano ./c/serializer/samples/simplesample_amqp/simplesample_amqp.c

6.Build and install the Apache Proton library
/azure-iot-sdks#./c/build_all/linux/build_proton.sh --install /usr

7.Build a few libraries upon which the samples depend
/azure-iot-sdks#./c/build_all/linux/build_paho.sh

...
In file included from src/MQTTPacket.h:24:0,
                 from src/MQTTPacketOut.h:22,
                 from src/MQTTPacketOut.c:28:
src/SSLSocket.h:27:25: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
                         ^
compilation terminated.
In file included from src/Socket.c:28:0:
src/SocketBuffer.h:28:25: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
                         ^
compilation terminated.
Makefile:199: recipe for target 'build/output/libpaho-mqtt3cs.so.1.0' failed
make: *** [build/output/libpaho-mqtt3cs.so.1.0] Error 1

8.Add OpenSSL library for build error
/azure-iot-sdks#apt-get install libssl-dev

9.Retry build_paho.sh
/azure-iot-sdks#./c/build_all/linux/build_paho.sh

10.Build the sample applications
/azure-iot-sdks#./c/build_all/linux/build.sh

~/cmake /home/azure-iot-sdks
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:27 (add_subdirectory):
  add_subdirectory given source "azure-c-shared-utility/c" which is not an
  existing directory.

-- Configuring incomplete, errors occurred!
See also "/root/cmake/CMakeFiles/CMakeOutput.log".

11.Add azure-c-shared-utility for build error(azure-c-shared-utility directory is empty)
/azure-iot-sdks#cd c
/c#git clone https://github.com/Azure/azure-c-shared-utility.git

12.Rebuild the sample applications
/c#cd ../
/azure-iot-sdks#./c/build_all/linux/build.sh

...
55:   Assert failed: non-NULL expected.
55: !!! FAILED !!!
55: 4 tests ran, 4 failed, 0 succeeded.
55/55 Test #55: serializer_e2etests ...................***Failed    0.17 sec

95% tests passed, 3 tests failed out of 55

Total Test time (real) =  69.49 sec

The following tests FAILED:
         31 - iothubclient_amqp_e2etests (Failed)
         33 - iothubclient_http_e2etests (Failed)
         55 - serializer_e2etests (Failed)
Errors while running CTest

* Above seems build is OK, but 3 tests are NG. Please find the attached file which shows all log.

13.Run the simplesample_amqp sample(?????)
GitHub says execute binary is placed at "~/cmake/serializer/samples/simplesample_amqp/simplesample_amqp".
I couldn't find /cmake directory and simplesample_amqp application in other directories.

-----

Could anyone please provide any ideas?

**Comment by ashokkhurana** [comment]
@kasebe , we are not able to repro the issue you reported. We tried all the steps and the sample app binary is created under ~/cmake/seaializer/samples/simplesample_amqp. Please find the screenshot of where we are seeing the binary on our system.

azure-c-shared-utility.git issue could be resolved by cloning the repo recursively using following command

git clone --recursive https://github.com/azure/azure-iot-sdks.git 

Test case failure happened because they require few environment variables been setup on device. Details for same can be found at https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_end_to_end_tests.md .

**Comment by kasebe** [comment]
Hello, ashokkhurana,

Thank you for your information.

I have tried "git clone --recursive https://github.com/azure/azure-iot-sdks.git" on cleaned BBB again.

The procedure is
1.#git clone --recursive https://github.com/azure/azure-iot-sdks.git
2.#apt-get install libssl-dev
3.#./azure-iot-sdks#./c/build_all/linux/build.sh
(build_proton.sh and build_paho.sh deleted??)

Last result shows

---
test 71
      Start 71: serializer_e2etests

71: Test command: /root/cmake/serializer/tests/serializer_e2etests/serializer_e2etests_exe
71: Test timeout computed to be: 9.99988e+06
71:  === Executing test suite serializer_e2etests ===
71: Executing test IoTClient_Http_MacroSend_E2ETests ...
71: Suceeded.
71: Executing test IoTClient_Http_MacroRecv_E2ETests ...
71: Suceeded.
71: Executing test IoTClient_AMQP_MacroSend_E2ETests ...
71: Suceeded.
71: Executing test IoTClient_AMQP_AmqpMacroRecv_E2ETests ...
71: Suceeded.
71: 4 tests ran, 0 failed, 4 succeeded.
71/71 Test #71: serializer_e2etests ...................   Passed    0.20 sec

100% tests passed, 0 tests failed out of 71

Total Test time (real) =  82.75 sec
/home/debian/azure-iot-sdks/c/build_all/linux

---

It looks like build and test are passed, but /cmake isn't created.
Could you provide your built binary application?
Anyway, I would like to work BBB Azure application.

I'm going to try your another suggestion as configuration of environment variables.

BTW, which Debian version do you use on BBB?
I use Debian version 8.2.

Thanks,
Kasebe

**Comment by kasebe** [comment]
I could find /cmake directory in /root directory.
Thank you!

Kasebe

**Comment by ashokkhurana** [comment]
@kasebe , yes build_proton and build_paho are deleted and not needed after latest release last week. Debian version on my BBB is 7.9. My built binary application is pointing to my own IoT hub and won't be useful if I share with you. I am still not able to repro what you are seeing as cmake folder is creating for me. I am trying to find out what could cause this issue.

Thanks,
Ashok

**Comment by kasebe** [comment]
Ashok,
I understood your binary application can not be used on my BBB. I had been looking for /cmake under /home because /azure-iot-sdks was cloned in /home. However,  /cmake was created in /root. 

Thanks,
Kasebe
