### ISSUE TITLE
Arduino Yun - simplesample_http curl_easy_perform() failed: Error

### ISSUE THREAD

**Issue by jjlee3** [Azure/azure-iot-sdks#277]
I would like to apply Azure IoT certification for MediaTek LinkIt Smart 7688.
The device is based on a MIPSel processor.
It is similar to Arduino Yun but not exactly the same.
I build the sample and execute it.

The sample keeps sending the errors below
```
root@mylinkit:/usr/share/azure-iot-sdk/samples# ./simplesample_http
Info: IoT Hub SDK for C, version 1.0.0-preview.9
IoTHubClient accepted the message for delivery
Error: Time:Mon Feb  1 15:37:51 2016 File:/home/jjlee/openwrt/OpenWrt-SDK-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/azure-iot-sdks-1/azure-c-shared-utility/c/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:488 curl_easy_perform() failed: Error
Error: Time:Mon Feb  1 15:37:51 2016 File:/home/jjlee/openwrt/OpenWrt-SDK-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/azure-iot-sdks-1/azure-c-shared-utility/c/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:490 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Feb  1 15:37:51 2016 File:/home/jjlee/openwrt/OpenWrt-SDK-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/azure-iot-sdks-1/azure-c-shared-utility/c/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Mon Feb  1 15:37:51 2016 File:/home/jjlee/openwrt/OpenWrt-SDK-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/azure-iot-sdks-1/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1212 unable to HTTPAPIEX_ExecuteRequest

```
As described in openwrt-arduino-yun-c.md, should I get ca-certificates_20160104_all.ipk?
Or could I simply opkg install azure-iot-sdks_1-1_ramips_24kec.ipk under ~/openwrt/OpenWrt-SDK-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/bin/ramips/packages/base/?
This ipk file is generated by azure-iot-sdks/c/build_all/arduino/build.sh.
Or I should install the certificates by myself?
I mean, does this chip need special certificates? 
Are there instructions for certificates?

**Comment by ashokkhurana** [comment]
@jjlee3  Last time I saw similar error “unable to recover sending to a working state” from a partner (though it was on some other device), it was an issue with the certificate not installed correctly on the device. Below is the link to the instructions on how to build and deploy C SDK on Arduino Yun. 

https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/openwrt-arduino-yun-c.md

Please refer the section “Make sure the certificates are installed” to verify that the certificate is installed correctly..

**Comment by jjlee3** [comment]
I switched to a more stable wifi router remove the repeated errors away.
Anyway I still got some errors prompted as below after 50 mins, is it OK for passing Azure Certified?
```
root@mylinkit:/usr/share/azure-iot-sdk/samples# ./simplesample_http
Info: IoT Hub SDK for C, version 1.0.0-preview.9
IoTHubClient accepted the message for delivery
Message Id: 1 Received.
Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_OK
Turning fan off.
Turning fan off.
Turning fan off.
Turning fan off.
Turning fan off.
Turning fan off.
Error: Time:Fri Feb  5 08:49:52 2016 File:/home/jjlee/openwrt/OpenWrt-SDK-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/azure-iot-sdks-1/azure-c-shared-utility/c/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:488 curl_easy_perform() failed: Error
Error: Time:Fri Feb  5 08:49:52 2016 File:/home/jjlee/openwrt/OpenWrt-SDK-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/azure-iot-sdks-1/azure-c-shared-utility/c/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:490 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Turning fan off.
```

**Comment by ashokkhurana** [comment]
@jjlee3 , from the logs you shared looks like the message is received from IoT hub successfully. So it should be good to go. Please let us know if you faced any other issue or we can close this.

**Comment by jjlee9** [comment]
Yes, please close it. Thanks for help.
