### ISSUE TITLE
build.sh nukes directory in user's home dir

### ISSUE THREAD

**Issue by dciliske** [Azure/azure-iot-sdks#278]
Running the linux/build.sh nukes and uses a home directory level directory. Lines 76-78.

This is *not* ok. This is not expected. Build directories need to be contained inside the resource being built unless explicitly told otherwise.

**Comment by tameraw** [comment]
@dciliske - Thanks for reporting this issue. Agree with you. We had this issue captured in our backlog to address in an upcoming release.

**Comment by markrad** [comment]
This issue has been addressed. The cmake directory will now be created in \<repositoryroot>/c/cmake/\<buildtypeidentifier> where buildtypeidentifier will be something meaningful such as iotsdk_linux.

_Mark Radbourne MSFT_
