### ISSUE TITLE
IoT SDK for Java language on Fedora 22 - Installation of Qpid JMS not successful as test cases fail

### ISSUE THREAD

**Issue by neeraj-khanna** [Azure/azure-iot-sdks#28]
**Test case failing:**
*TransportSupportTest.testCreateSslContextIncorrectStoreType*

**Commands executed:**
```
git clone https://github.com/avranju/qpid-jms.git
cd qpid-jms
mvn install
```
**Note:** 
Although if we skip the execution of test cases, installation completes successfully and we are able to proceed and build the IoT SDK successfully.

**Command to skip test cases:**
`mvn install -DskipTests`

**Comment by avranju** [comment]
Thanks for filing this issue. I tried running this with JDK jdk1.8.0_60 and JDK jdk1.8.0_45 and the test in question passes with the latter and fails with the former. It looks like the behavior of the `KeyStore` implementation for the "jks" type has changed between JDK 1.8 revs. For the purposes of the IoT SDK skipping this test should be OK. This issue will need to be taken up with the [Apache Qpid JMS](https://issues.apache.org/jira/browse/QPIDJMS/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel) project.

**Comment by avranju** [comment]
The setup [doc](https://github.com/Azure/azure-iot-sdks/blob/develop/java/device/doc/devbox_setup.md) has been updated with instructions to run mvn install skipping tests in case it fails.
