### ISSUE TITLE
remote_monitoring.c not working correctlly with preconfigured solution

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdks#280]
If you try to use the preconfigured solution device portal to send a command to client device that was built using the remote_monitoring.c code, the portal displays the error message shown in this screenshot.
![error](https://cloud.githubusercontent.com/assets/1454644/12843672/d3da928c-cbf2-11e5-9098-cc8176d50aaa.png)

It seems likely that the model defined in the source file is incompatible with the command types expected by the portal. For reference, the simulated devices deployed by the preconfigured solution change a device temperature using a command as shown here:
![correct](https://cloud.githubusercontent.com/assets/1454644/12843767/60cd79e8-cbf3-11e5-9e4a-bab9db669e4b.png)

**Note:** I haven't tested it, but it looks as if the Node.js remote_monitoring.js sample will have the same issue.

**Comment by tameraw** [comment]
Thanks Dominic for reporting this. We'll take a look and address it.

**Comment by tameraw** [comment]
@dominicbetts - Sync'ing up with solution team to address on either side.

**Comment by tameraw** [comment]
This issue will be resolved on the remote monitoring git hub repo. Please refer to this issue for the latest status:
https://github.com/Azure/azure-iot-remote-monitoring/issues/120
