### ISSUE TITLE
Build simple_http.o failure

### ISSUE THREAD

**Issue by alexdg18** [Azure/azure-iot-sdks#284]
I was following https://azure.microsoft.com/en-us/develop/iot/get-started/.Here I have to work with the azure-iot-sdk I have manage to build the azure sdk for the cc3200.But when I try to build the simple_http it fails ,,here I index the file
[simple_http.o.txt](https://github.com/Azure/azure-iot-sdks/files/120271/simple_http.o.txt)

**Comment by tameraw** [comment]
@alexdg18 - Thanks for submitting your issue. We'll take a look and help address it.

**Comment by ashokkhurana** [comment]
@alexdg18 , From the attached logs, looks like gmake is either not installed or not set properly in PATH environment variable. Could you please make sure that all the paths in products.mak file are accessible. In my case gmake.exe is available under C:\ti\xdctools_3_31_01_33_core and this path is set under products.mak as below

XDCTOOLS_INSTALLATION_DIR ?= C:\ti11\xdctools_3_31_01_33_core

If you could share your products.mak file, it will help us to troubleshoot the issue better.

Thanks,
Ashok

**Comment by alexdg18** [comment]
Hi,I think I set them up properly.Here is from the Total commander C:\ti\xdctools_3_31_01_33_core
#
#  ======== products.mak ========
#

##################### All platforms ####################

XDCTOOLS_INSTALLATION_DIR ?= c:/ti/xdctools_3_31_01_33_core

##################### TI-RTOS ####################

TIRTOS_INSTALLATION_DIR ?= c:/ti/tirtos_simplelink_2_14_01_20
BIOS_INSTALLATION_DIR   ?= $(TIRTOS_INSTALLATION_DIR)/products/bios_6_42_02_29
UIA_INSTALLATION_DIR    ?= $(TIRTOS_INSTALLATION_DIR)/products/uia_2_00_02_39
NS_INSTALLATION_DIR     ?= c:/ti/ns_1_10_00_00_eng

##################### TI-RTOS (CC3200) ####################

CC3200SDK_VERSION = 1.1.0
CCWARE_INSTALLATION_DIR    ?= $(TIRTOS_INSTALLATION_DIR)/products/CC3200_driverlib_1.1.0
CC3200SDK_INSTALLATION_DIR ?= c:/ti/CC3200SDK_1.1.0/cc3200-sdk

# Leave assignment empty to disable this toolchain
ti.targets.arm.elf.M4  ?= c:/ti/ti-cgt-arm_5.2.5

**Comment by ashokkhurana** [comment]
@alexdg18, Could you please check if you have xdc tools folder path added to your PATH environment variable. Below is an old issue with same error and one of our developers has solved this issue by adding the xdc tools path to PATH variable.

https://github.com/Azure/azure-iot-sdks/issues/196

Please let us know how it goes.

Thanks,
Ashok

**Comment by alexdg18** [comment]
Hi Ashok:I have tried to add the xdc folder to the path enviroment variable,I think I did it succefully by adding it through : advanced system setttings ,then environment variables,the path and I added with ;C:\ti\xdctools_3_31_01_33_core\.I also added the c:\ti\ti-cgt-arm_5.2.5\ to the path environment variable,and still doesnt work 

   "C:\ti\ti-cgt-arm_5.2.5\lib\rtsv7M4_T_le_eabi.lib" for the first time, so it
   must be built.  This may take a few minutes.
>> ERROR: mklib: could not find program "sh", required for building libraries.  Modify the PATH environment variable to contain a directory containing this program.
warning: automatic RTS selection:  resolving index library "libc.a" to
   "rtsv7M4_T_le_eabi.lib", but "rtsv7M4_T_le_eabi.lib" was not found

 undefined             first referenced                                                                                 
  symbol                   in file                                                                                      
 ---------             ----------------                                                                                 
 __TI_decompress_none                                                                                                   
 __TI_decompress_rle24                                                                                                  
 __TI_zero_init                                                                                                         
 __aeabi_lmul          C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200\main\package\cfg\main_pem4.src\sysbios\sysbios.aem4<BIOS.obj>
 __aeabi_uidivmod      C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_29\packages\ti\targets\arm\rtsarm\lib\ti.targets.arm.rtsarm.aem4<System.oem4>
 __aeabi_uldivmod      C:/ti/tirtos_simplelink_2_14_01_20/packages/ti/drivers/lib/drivers_ccware.aem4<PowerCC3200.oem4> 
 _args_main            C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_29\packages\ti\targets\arm\rtsarm\lib\boot.aem4<boot.oem4>
 _nop                  C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200\main\package\cfg\main_pem4.oem4
 _register_lock        C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200\main\package\cfg\main_pem4.oem4
 _register_unlock      C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200\main\package\cfg\main_pem4.oem4
 abort                 C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_29\packages\ti\targets\arm\rtsarm\lib\ti.targets.arm.rtsarm.aem4<System.oem4>
 copy_in               C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_29\packages\ti\targets\arm\rtsarm\lib\auto_init.aem4<auto_init.oem4>
 exit                  C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_29\packages\ti\targets\arm\rtsarm\lib\ti.targets.arm.rtsarm.aem4<System.oem4>
 main_func_sp          C:\ti\tirtos_simplelink_2_14_01_20\products\bios_6_42_02_29\packages\ti\targets\arm\rtsarm\lib\boot.aem4<boot.oem4>
 memcpy                simplesample_http.o                                                                              
 memset                C:\ti\azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200\main\package\cfg\main_pem4.oem4
 strlen                netwifi.o                                                                                        

error: unresolved symbols remain
error: errors encountered during linking; "simplesample_http.out" not built

>> Compilation failure
gmake: *** [simplesample_http.out] Error 1

Thanks,
Alex

**Comment by laurawalker** [comment]
I also had a similar issue with trying to get the CC3200 examples to compile - try also adding C:\ti\xdctools_3_31_01_33_core\bin (which is the location of sh.exe) to the PATH.

**Comment by alexdg18** [comment]
Still the same error.

**Comment by ashokkhurana** [comment]
@alexdg18 , did you tried on a new command prompt after updating the PATH variable? Is it exactly the same error about missing sh.exe? If different, could you please share the error again?

**Comment by alexdg18** [comment]
Yes,it is the same.I have changed the Path Environment variable,set with and without /bin,started a new cmd.And it doesnt get it,does it matter the version of windows?im using windows 10

"c:\ti\ti-cgt-arm_5.2.5\lib\rtsv7M4_T_le_eabi.lib" for the first time, so it
   must be built.  This may take a few minutes.
>> ERROR: mklib: could not find program "gmake", required for building libraries.  Modify the PATH environment variable to contain a directory containing this program.
warning: automatic RTS selection:  resolving index library "libc.a" to
   "rtsv7M4_T_le_eabi.lib", but "rtsv7M4_T_le_eabi.lib" was not found

**Comment by ashokkhurana** [comment]
@alexdg18 , Windows version should not be an issue here as we tested on Windows 10 and it worked. The latest error is showing gmake program not found which looks like was resolved in the last log you shared which were saying "sh" not found. Could you please confirm if both the below values are set in PATH variable.
C:\ti\xdctools_3_31_01_33_core
C:\ti\xdctools_3_31_01_33_core\bin 

First one above should take care of gmake issue and the other one of sh program. Please also confirm that the command prompt instance is showing both the values by printing the environment variable using "echo $PATH".

**Comment by alexdg18** [comment]
Hi,it worked sth,but not complete now it is giving this error:
warning: automatic library build: using library
   "c:\ti\ti-cgt-arm_5.2.5\lib\rtsv7M4_T_le_eabi.lib" for the first time, so it
   must be built.  This may take a few minutes.
process_begin: CreateProcess(NULL, tools/elf2cc32 simplesample_http.out simplesample_http.bin, ...) failed.
make (e=2): The system cannot find the file specified.
gmake: *** [simplesample_http.bin] Error 2

**Comment by alexdg18** [comment]
I had to add the elf2cc32.exe to the folder <AZURE_INSTALL_DIR>\azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200\tools

**Comment by lamqhoang** [comment]
I'm having the same issue. I have added the eviromental path and elf2cc32.exe to the folder \azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200\tools
`#
#  ======== products.mak ========
#

##################### All platforms ####################

XDCTOOLS_INSTALLATION_DIR ?= E:/TI/xdctools_3_32_00_06_core

##################### TI-RTOS ####################

TIRTOS_INSTALLATION_DIR ?= E:/TI/tirtos_simplelink_2_14_03_28
BIOS_INSTALLATION_DIR   ?= $(TIRTOS_INSTALLATION_DIR)/products/bios_6_42_03_35
UIA_INSTALLATION_DIR    ?= $(TIRTOS_INSTALLATION_DIR)/products/uia_2_00_02_39
NS_INSTALLATION_DIR     ?= E:/TI/ns_1_10_00_00_eng

##################### TI-RTOS (CC3200) ####################

CC3200SDK_VERSION = 1.1.0
CCWARE_INSTALLATION_DIR    ?= $(TIRTOS_INSTALLATION_DIR)/products/CC3200_driverlib_1.1.0
CC3200SDK_INSTALLATION_DIR ?= E:/TI/CC3200SDK_1.1.0/cc3200-sdk

# Leave assignment empty to disable this toolchain
ti.targets.arm.elf.M4  ?= E:/TI/ti-cgt-arm_5.2.5`
