### ISSUE TITLE
AMQP Connection Loss

### ISSUE THREAD

**Issue by careybd** [Azure/azure-iot-sdks#285]
What is the recommended method to handle a loss of connection with the Node SDK and AMQP protocol. Is there any ack or heartbeat mechanism that can be used to detect a dead connection, because it seems as of now the standard err res callbacks in 'client.sendEvent' return nothing when the connection has been lost, rendering any depended error handling ineffective. It also seems there is a roughly 2 minute cache for IOT Hub connections, but after longer durations my messages are lost. I did notice that the new update has a 'client.on('disconnect, ..)' method, but I am not able to get this to recognize my connection loss either.

Any advice? Thanks

**Comment by pierreca** [comment]
Hi @careybd 

the connection loss event is tied to the socket closing. how do you test loss of connection?

**Comment by careybd** [comment]
We ended up putting a timeout on the acks which did not generate a null err and which stopped the queue, so that is sufficient as a workaround for now. Thanks
