### ISSUE TITLE
Cannot install NuGet package on C++ UWP app

### ISSUE THREAD

**Issue by arturl** [Azure/azure-iot-sdks#289]
Attempting to install Microsoft.Azure.DevicesClient NuGet package on a C++ UWP app gets:

> Could not install package 'Microsoft.Azure.Devices.Client 1.0.1'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I can extract Microsoft.Azure.Devices.Client.winmd from the NuGet package and add it to my project manually - that works. Therefore, this is a problem with NuGet or the way the NuGet is packaged.

**Comment by tameraw** [comment]
Thanks @arturl. I'll take a look at this.

**Comment by tameraw** [comment]
@arturl - Work in progress with VC team.

**Comment by tameraw** [comment]
@arturl - We released a new package today. This will allow you to install the NuGet package in a C++ UWP but does not automatically add the reference to your C++ project.
You have to do that one extra step of adding reference to the file <project_dir>\packages\Microsoft.Azure.Devices.Client.x.y.z\lib\native\Microsoft.Azure.Devices.Client.winmd
This should at least unblock users allowing them to install the package and we'll work on getting it linked automatically soon.

**Comment by arturl** [comment]
Good stuff, thanks for the update.

Artur
