### ISSUE TITLE
Device explorer is not filtering properly

### ISSUE THREAD

**Issue by hveiras** [Azure/azure-iot-sdks#29]
![captura de pantalla 2015-10-06 09 33 38](https://cloud.githubusercontent.com/assets/925594/10308656/b066df26-6c0d-11e5-9607-04d8794f5b49.png)

I selected device 001_487 but I'm seeing events from all XXX_487

**Comment by tameraw** [comment]
Thanks for reporting the issue. We're debugging it right now.

**Comment by tameraw** [comment]
This is issue has been fixed in the "develop" branch and a new MSI will be provided with the next release (ETA end of week)

**Comment by dcristoloveanu** [comment]
This is fixed in our latest release (1.0.0-preview.4).
