### ISSUE TITLE
simplesample_amqp execution failure on Debian Beagleboneblack

### ISSUE THREAD

**Issue by kasebe** [Azure/azure-iot-sdks#290]
Hello,

I have tried ./simplesample_amqp, but below failure occurred on Beagleboneblack Debian. The connecting ethernet cable worked fine in case of  windows' SimulatedDevice application. I brought ConnectionString from Device Explorer>Management. Should I do something of Debian configuration around network? 

---

root@arm:~/cmake/serializer/samples/simplesample_amqp# ./simplesample_amqp
Info: IoT Hub SDK for C, version 1.0.0
IoTHubClient accepted the message for delivery
Error: Time:Fri Jan 15 02:29:47 2016 File:/home/debian/azure-iot-sdks/c/azure-c-shared-utility/c/adapters/socketio_berkeley.c Func:socketio_open Line:247 Failure: connect failure -1.
Error: Time:Fri Jan 15 02:29:47 2016 File:/home/debian/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:establishConnection Line:473 Failed to open the connection with CBS.
Error: Time:Fri Jan 15 02:29:47 2016 File:/home/debian/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1129 AMQP transport failed to establish connection with service.

---

Thanks&regards,
Kasebe

**Comment by ashokkhurana** [comment]
@kasebe Could you please check with your network administrator that outbound port # 5671 is enabled. Devices with the AMQP protocol use that outbound port to communicate with IoT Hub. There is more information here: 
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-itpro-info/

**Comment by SantoshWiki** [comment]
I am having same problem with my [Internet of things](http://internetofthingswiki.com/) application, i think will need some expert advise as well.

**Comment by kasebe** [comment]
Hello ashokkhurana,

Your suggestion of 5671 port leads to next stage.
Thank you!
New error occurred.

---
root@arm:~/cmake/serializer/samples/simplesample_amqp# ./simplesample_amqp
Info: IoT Hub SDK for C, version 1.0.0
IoTHubClient accepted the message for delivery
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {default_container_id,********.azure-devices.net,4294967295,65535}
<- [OPEN]* {DeviceGateway_42294ee872884543aae66cc09877d00e,10.0.0.53,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
-> [ATTACH]* {cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,65535}
-> [ATTACH]* {cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,65535}
<- [ATTACH]* {cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,65535,NULL,NULL,NULL}
<- [FLOW]* {0,100,1,5000,0,0,100,0,NULL,false,NULL}
<- [ATTACH]* {cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65535,NULL,NULL,NULL}
-> [FLOW]* {1,4294967295,0,100,1,0,10000}
-> [TRANSFER]* {0,0,<00 00 00 00>,0,false}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
<- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}
Error: Time:Fri Jan 15 00:47:02 2016 File:/home/debian/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1145 AMQP transport authentication timed out.
---
Dose this show I have to do
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_end_to_end_tests.md
(./setiotdeviceparametersfore2etests.sh)
before this test?

Thanks,
Kasebe

**Comment by ashokkhurana** [comment]
@kasebe , https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_end_to_end_tests.md are the instructions to set environment variable which are used to execute E2E tests when building the SDK. When running sample, the connection to IoT hub is determined by the device connection string. Could you please try creating a new device using device explorer and try with new connection string. Just want to make sure that the timeout issue is happening with more than one device.

**Comment by kasebe** [comment]
I think simplesamples_amqp application needs only "device connection string" from Device Explorer.
I confirmed the string in simplesamples_amqp.c again, so it it looks like correct. Do you say simplesamples_amqp execution needs azue-iot/tools/iot_hub_e2e_tests_params/iot_device_params.txt edit?

**Comment by kasebe** [comment]
The cause was my network's firewall blocked transfer data from azure.
It worked fine by using normal network.
Thank you.

**Comment by cnvery** [comment]
Hi @kasebe,

I have same AMQP problem just like you.

I have tried 2 different networks for my Intel Edison, but it is unable to solve the problem.

Do you have any other suggestion on solving this?

Thanks!
