### ISSUE TITLE
LNK2019 when building Remote_Monitoring

### ISSUE THREAD

**Issue by boerreth** [Azure/azure-iot-sdks#291]
I try to do the IOT demo and add a new customized device. I have downloaded IOT SDK from github and try to modify and compile remote_monitoring from visual studio 2015. I got 55 LNK2019 error and also an error on the DECLARE_MODEL statement.
Anyone who can help me?

**Comment by olivierbloch** [comment]
Hi @boerreth 
The remote-monitoring sample code was updated to use the latest version of the SDK, but the NuGet Packages references were not updated.
We are working on fixing this. You should see the fix come up in our develop branch later today and in the master branch early next week. In the meantime, you can try updating the NuGet packages for the solution to the latest versions.
