### ISSUE TITLE
This blog post still references Proton & Proton_PATH

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#296]
Azure IoT device SDK for C tutorial links to this blog post by Olivier:
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-device-sdk-c-intro/

In it he talks about setting up Proton and using the PROTON_PATH environment variables.  Are those still required with the new replacement library?  Either way it appears this blog post should be updated now.

Also the first sample the blog has someone try to build is the AMQP version.  I would suggest that they start by simply build the http and verify that they can get that sample to build and connect in the DeviceExplorer while it monitors the connection first, then worry about AMQP.

**Comment by tameraw** [comment]
@jtanner-msft - PR in process from Olivier in review for updating ACOM doc.
