### ISSUE TITLE
Missing Windows solution and project files in C iothub_client samples 

### ISSUE THREAD

**Issue by timwieman** [Azure/azure-iot-sdks#299]
The Windows solution and project files are missing from the AMQP and Websockets samples for C iothub_client: 
- c/iothub_client/samples/iothub_client_sample_amqp/windows
- c/iothub_client/samples/iothub_client_sample_amqp_websockets/windows

**Comment by tameraw** [comment]
@timwieman - Thanks for filing this. We'll bring it back.

**Comment by tameraw** [comment]
@timwieman - A check in is on the way, available on develop branch later today. Thanks.

**Comment by tameraw** [comment]
Fixed. Thanks.
