### ISSUE TITLE
Building for Openwrt on IMX6

### ISSUE THREAD

**Issue by stanleyoz** [Azure/azure-iot-sdks#301]
Development machine Ubuntu 14.04 64-bit with gcc4.9  
Device is IMX6 512MB RAM with OpenWRT + Linux 3.0.35

We tried various approaches so far  .. (1) using the build_all/linux, (2) node.js and (3)modify from Arduino Yun SDK but all came to "tragic endings" so far, e.g. various missing files and broken link errors. Perhaps better to seek some experienced advise so hopefully future development time is well spent ..

Please advise what direction is prudent to build and install the Azure IOT on our device? Future use scenario requires fast configuration (prefer on device, e.g. on site) of multiple devices.

Thank you.

**Comment by stanleyoz** [comment]
Anyone with "-lssl and -lcrypto file not found" error towards end of /build_all/linux/build against an OpenWRT toolchain? The objects libssl.so and libcryto.so are in their /usr/lib but the linker does not seem to pick it up ... any remedy?

**Comment by dcristoloveanu** [comment]
Hi @stanleyoz 

Sorry for the delay.
Could you post the log with the errors encountered during cross compile (you mentioned you started at the Arduino Yun script)?

Thanks,
/Dan

**Comment by stanleyoz** [comment]
Hi Dan!

We decided to try "porting the C libraries" to our device. Please confirm the 3 files to port for cross compiling to a OpenWRT device are as following?

httpiapi_curl.c > ../src/httpapi_curl.c:14:23: fatal error: curl/curl.h: No such file or directory

lock_pthreads.c > cross compiled OK

threadapi_pthreads.c >
./src/threadapi_pthreads.o: In function `ThreadAPI_Create':
/home/amplified/workspace/G3M2M/Debug/../src/threadapi_pthreads.c:59: undefined reference to `pthread_create'
./src/threadapi_pthreads.o: In function `ThreadAPI_Join':
/home/amplified/workspace/G3M2M/Debug/../src/threadapi_pthreads.c:100: undefined reference to `pthread_join'

Kindly advise possible source of compiling errors above. Thanks mate.

Stanley

**Comment by stanleyoz** [comment]
Sorted the pthreads linker error with a -pthread flag in the linker command.

Any help of how to approach the "curl/curl.h" error for httpapi_curl.c? The header files are in my device toolchain folder but compiler does not seem to pick it up somehow.

**Comment by stanleyoz** [comment]
With much spot-on help from Dan (@Richmond), we were able to finally sort both our (1) compiling /openssl/..h header files not found and (2) linker error -lssl and -lcrypto not found errors.

For our openwrt device toolchain cross-compiled on a Ubuntu 14.04 development machine, the ..linux\build-all string is,

./build.sh --toolchain-file toolchain-cmake --skip-e2e-tests --skip-unittests-cl -D__STDC_NO_ATOMICS__ -cl --sysroot=${STAGING_TARGET}/root-imx6 -cl -I${STAGING_TARGET}/usr/include -cl –L${STAGING_TARGET}/usr/lib

I hope this helps everyone else embarking on this journey of discovery :)
