### ISSUE TITLE
redefinition of typedef 'LOGGER_LOG' while compiling c sdk

### ISSUE THREAD

**Issue by rabbitom** [Azure/azure-iot-sdks#302]
I'm cross-compiling c sdk and encounter an error of redefinition:

[ 29%] Building C object azure-uamqp-c/CMakeFiles/uamqp.dir/src/amqp_frame_codec.c.o
In file included from /home/erabbit/Develop/azure-iot-sdks/c/azure-uamqp-c/inc/frame_codec.h:8,
                 from /home/erabbit/Develop/azure-iot-sdks/c/azure-uamqp-c/inc/amqp_frame_codec.h:15,
                 from /home/erabbit/Develop/azure-iot-sdks/c/azure-uamqp-c/src/amqp_frame_codec.c:11:
/home/erabbit/Develop/azure-iot-sdks/c/azure-uamqp-c/inc/logger.h:11: error: redefinition of typedef 'LOGGER_LOG'
/home/erabbit/Develop/azure-iot-sdks/c/azure-c-shared-utility/c/inc/xlogging.h:12: error: previous declaration of 'LOGGER_LOG' was here
make[2]: *** [azure-uamqp-c/CMakeFiles/uamqp.dir/src/amqp_frame_codec.c.o] Error 1
make[1]: *** [azure-uamqp-c/CMakeFiles/uamqp.dir/all] Error 2
make: *** [all] Error 2

I've seen the two .h file and found they are pretty same. And this only happens when cross-compiling, I haven't figure out why this is not a problem  when I compile for my host system.

**Comment by dcristoloveanu** [comment]
Thanks for reporting this.
We filed this as a bug and will remove the duplication for a subsequent release.
This seems to appear in your case for cross compiling because the version of gcc for cross compiling is different than the one you use on your host. Can you check you gcc versions for the x-compile toolchain and the native gcc on your host machine?

Here is a relevant Stackoverflow discussion I found about the change that was made in gcc.
I don'tthink you have a good way to disable this though (there is a -pedantic option in gcc, but I don't see the option to disable the error).

http://stackoverflow.com/questions/15222463/compiling-source-code-on-2-different-versions-of-gcc 

If you would like to contribute a fix before we get to it, I'm more than happy to review and merge in. I guess the fix would be in azure-uamqp-c (https://github.com/Azure/azure-uamqp-c).

Thanks,
/Dan

**Comment by rabbitom** [comment]
It turned out that I was using gcc3.4.2 (what a shame!), and I later figured out that this version of gcc is not aplicable to azure-c-sdk because it doesn't supoort __COUNTER__ - which is used by serializer - I looked up and found __COUNTER__ is supported since gcc4.3(https://gcc.gnu.org/gcc-4.3/changes.html). So I made some efforts to build a new cross-compile toolchain with gcc4.9.3 by myself, and the problem is gone!

**Comment by rabbitom** [comment]
@dcristoloveanu - I think this is not only in azure-amqp-c:

erabbit@ubuntu:~/Develop/azure-iot-sdks/c$ find . -name "*.[h|c]" | xargs grep "xlogging.h"
./azure-c-shared-utility/c/inc/socketio.h:#include "xlogging.h"
./azure-c-shared-utility/c/inc/xio.h:#include "xlogging.h"
./azure-uamqp-c/azure-c-shared-utility/c/inc/socketio.h:#include "xlogging.h"
./azure-uamqp-c/azure-c-shared-utility/c/inc/xio.h:#include "xlogging.h"
./azure-umqtt-c/src/mqtt_codec.c:#include "xlogging.h"
./azure-umqtt-c/azure-c-shared-utility/c/inc/socketio.h:#include "xlogging.h"
./azure-umqtt-c/azure-c-shared-utility/c/inc/xio.h:#include "xlogging.h"
./azure-umqtt-c/inc/mqtt_client.h:#include "xlogging.h"

and my fix is quite simple with a shell command:
erabbit@ubuntu:~/Develop/azure-iot-sdks/c$ find . -name "*.[h|c]" | xargs sed -i "s/\"logger.h/\"xlogging.h/g"

Since the changes are all in submodules, and I'm not quite sure how to make pull-requests for these submodules, I haven't made a pull-request for this now.

**Comment by rabbitom** [comment]
One more thing - I found a similar redefinition error when using gcc3.4.2:

[ 79%] Building C object serializer/CMakeFiles/serializer.dir/src/agenttypesystem.c.o
In file included from /home/erabbit/Develop/azure-iot-sdks/c/serializer/src/agenttypesystem.c:10:
/home/erabbit/Develop/azure-iot-sdks/c/serializer/inc/agenttypesystem.h:643: error: redefinition of typedef 'AGENT_DATA_TYPE'
/home/erabbit/Develop/azure-iot-sdks/c/serializer/inc/agenttypesystem.h:33: error: previous declaration of 'AGENT_DATA_TYPE' was here
make[2]: *** [serializer/CMakeFiles/serializer.dir/src/agenttypesystem.c.o] Error 1
make[1]: *** [serializer/CMakeFiles/serializer.dir/all] Error 2
make: *** [all] Error 2

and the redefination is quite obvious in serializer/inc/agenttypesystem.h:
     32 struct AGENT_DATA_TYPE_TAG;
     33 typedef struct AGENT_DATA_TYPE_TAG AGENT_DATA_TYPE;
    602 typedef struct AGENT_DATA_TYPE_TAG
    643 }AGENT_DATA_TYPE;

but if I change it to this:
     32 __extern__ struct AGENT_DATA_TYPE_TAG;
     33 typedef struct AGENT_DATA_TYPE_TAG AGENT_DATA_TYPE;
    602 ~~typedef~~ struct AGENT_DATA_TYPE_TAG
    643 }~~AGENT_DATA_TYPE~~;

then error will occur when compiling c++ files:
[ 78%] Building CXX object serializer/tests/agentmacros_unittests/CMakeFiles/agentmacros_unittests_exe.dir/agentmacros_unittests.cpp.o
In file included from /home/erabbit/Develop/azure-iot-sdks/c/serializer/inc/codefirst.h:7:0,
                 from /home/erabbit/Develop/azure-iot-sdks/c/serializer/tests/agentmacros_unittests/agentmacros_unittests.cpp:13:
/home/erabbit/Develop/azure-iot-sdks/c/serializer/inc/agenttypesystem.h:32:15: error: a storage class can only be specified for objects and functions
 extern struct AGENT_DATA_TYPE_TAG;
               ^
make[2]: *** [serializer/tests/agentmacros_unittests/CMakeFiles/agentmacros_unittests_exe.dir/agentmacros_unittests.cpp.o] Error 1
make[1]: *** [serializer/tests/agentmacros_unittests/CMakeFiles/agentmacros_unittests_exe.dir/all] Error 2
make: *** [all] Error 2

Since the "redefinition" error is gone when I switched to my new cross-complie toolchain of gcc4.9.3, I decided not to modify the file. I just wanted you to know this.

**Comment by dcristoloveanu** [comment]
Thanks for letting us know.
The uAMQP change has been pulled in.
I'm not sure about the AGENT_DATA_TYPE error, would need to investigate how it breaks down, although it does not seem to be a problem with a newer gcc.

Thanks,
/Dan

**Comment by jjlee3** [comment]
[ 13%] Building C object azure-uamqp-c/CMakeFiles/uamqp.dir/src/amqp_frame_codec.c.o
In file included from /home/jjlee/azure-iot-sdks/c/azure-uamqp-c/inc/frame_codec.h:8,
                 from /home/jjlee/azure-iot-sdks/c/azure-uamqp-c/inc/amqp_frame_codec.h:15,
                 from /home/jjlee/azure-iot-sdks/c/azure-uamqp-c/src/amqp_frame_codec.c:11:
/home/jjlee/azure-iot-sdks/c/azure-uamqp-c/inc/logger.h:11: error: redefinition of typedef 'LOGGER_LOG'
/home/jjlee/azure-iot-sdks/c/azure-c-shared-utility/c/inc/xlogging.h:12: note: previous declaration of 'LOGGER_LOG' was here
make[2]: *** [azure-uamqp-c/CMakeFiles/uamqp.dir/src/amqp_frame_codec.c.o] Error 1
make[1]: *** [azure-uamqp-c/CMakeFiles/uamqp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking C static library libumqtt.a

I cannot switch to a new toolchain.
