### ISSUE TITLE
The order of events is broken when ERROR occurs in Java SDK 

### ISSUE THREAD

**Issue by GwangseokHahm** [Azure/azure-iot-sdks#303]
When I tested sending events, usually there is no problem about the order of events .
But when ERROR occurs after some exception, the order of events is broken.
I think this problem happens in the re-sending logic.
I attached my test log as below.

------------------------------------  log ---------------------------------------------------------------------------

[Send Test] sendEventAsync : Event Message #6823 -> SentTime : [2016-02-11] 04:11:38:00350 / [2016-02-11] 04:11:38:00350
[Send Test] sendEventAsync : Event Message #6824 -> SentTime : [2016-02-11] 04:11:38:00559 / [2016-02-11] 04:11:38:00559
[Send Test] sendEventAsync : Event Message #6825 -> SentTime : [2016-02-11] 04:11:38:00762 / [2016-02-11] 04:11:38:00762
[Send Test] sendEventAsync : Event Message #6826 -> SentTime : [2016-02-11] 04:11:38:00960 / [2016-02-11] 04:11:38:00960
[Send Test] sendEventAsync : Event Message #6827 -> SentTime : [2016-02-11] 04:11:39:00167 / [2016-02-11] 04:11:39:00167
[Send Test] sendEventAsync : Event Message #6828 -> SentTime : [2016-02-11] 04:11:39:00366 / [2016-02-11] 04:11:39:00366
Failed to send message because: org.apache.qpid.proton.engine.HandlerException: java.lang.Throwable: Link closed before the message was sent.
Failed to send message because: org.apache.qpid.proton.engine.HandlerException: java.lang.Throwable: Connected remotely closed due to error.
java.lang.IllegalStateException: The AMQPS IotHub Connection is currently closed. Call open() before attempting to consume a message.: The AMQPS IotHub Connection is currently closed. Call open() before attempting to consume a message.
com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.consumeMessage(AmqpsIotHubConnection.java:225)
com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.handleMessage(AmqpsTransport.java:331)
com.microsoft.azure.iothub.transport.IotHubReceiveTask.run(IotHubReceiveTask.java:25)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
Failed to send message because: The AMQPS IotHub Connection is currently closed. Call open() before attempting to schedule a message.
[Send Test] IoT Hub responded to message sent at : Event Message #6825 -> SentTime : [2016-02-11] 04:11:38:00762 with status ERROR -> ReceivedTime : [2016-02-11] 04:11:40:00665 / [2016-02-11] 04:11:40:00665
[Send Test] EventCallback execute() >>> Thread ID :  23491 / [2016-02-11] 04:11:40:00665
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

Failed to send message because: The AMQPS IotHub Connection is currently closed. Call open() before attempting to schedule a message.
[Send Test] IoT Hub responded to message sent at : Event Message #6826 -> SentTime : [2016-02-11] 04:11:38:00960 with status ERROR -> ReceivedTime : [2016-02-11] 04:11:41:00068 / [2016-02-11] 04:11:41:00068
[Send Test] EventCallback execute() >>> Thread ID :  23492 / [2016-02-11] 04:11:41:00068
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

Failed to send message because: The AMQPS IotHub Connection is currently closed. Call open() before attempting to schedule a message.
[Send Test] IoT Hub responded to message sent at : Event Message #6827 -> SentTime : [2016-02-11] 04:11:39:00167 with status ERROR -> ReceivedTime : [2016-02-11] 04:11:41:00506 / [2016-02-11] 04:11:41:00506
[Send Test] EventCallback execute() >>> Thread ID :  23493 / [2016-02-11] 04:11:41:00506
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

Failed to send message because: The AMQPS IotHub Connection is currently closed. Call open() before attempting to schedule a message.
[Send Test] IoT Hub responded to message sent at : Event Message #6828 -> SentTime : [2016-02-11] 04:11:39:00366 with status ERROR -> ReceivedTime : [2016-02-11] 04:11:41:00912 / [2016-02-11] 04:11:41:00912
[Send Test] EventCallback execute() >>> Thread ID :  23494 / [2016-02-11] 04:11:41:00912
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

[Send Test] IoT Hub responded to message sent at : Event Message #6823 -> SentTime : [2016-02-11] 04:11:38:00350 with status ERROR -> ReceivedTime : [2016-02-11] 04:11:42:00151 / [2016-02-11] 04:11:42:00151
[Send Test] EventCallback execute() >>> Thread ID :  23487 / [2016-02-11] 04:11:42:00151
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

[Send Test] IoT Hub responded to message sent at : Event Message #6824 -> SentTime : [2016-02-11] 04:11:38:00559 with status ERROR -> ReceivedTime : [2016-02-11] 04:11:42:00151 / [2016-02-11] 04:11:42:00151
[Send Test] EventCallback execute() >>> Thread ID :  23488 / [2016-02-11] 04:11:42:00151
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

[Recv Test] Received message with content: 2016-02-10 04:11:40:12610 -> My ReceivedTime : [2016-02-11] 04:11:49:00383
[Recv Test] MessageCallback execute() Ended! = 12 / [2016-02-11] 04:11:49:00383
[Recv Test] End ---------------------------------------------------- 

[Send Test] IoT Hub responded to message sent at : Event Message #6825 -> SentTime : [2016-02-11] 04:11:38:00762 with status OK_EMPTY -> ReceivedTime : [2016-02-11] 04:11:52:00400 / [2016-02-11] 04:11:52:00400
[Send Test] EventCallback execute() >>> Thread ID :  23499 / [2016-02-11] 04:11:52:00400
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

[Send Test] IoT Hub responded to message sent at : [2016-02-11] 04:11:49:00383 with status OK_EMPTY -> ReceivedTime : [2016-02-11] 04:11:52:00449 / [2016-02-11] 04:11:52:00449
[Send Test] EventCallback execute() >>> Thread ID :  23505 / [2016-02-11] 04:11:52:00449
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

[Send Test] IoT Hub responded to message sent at : Event Message #6828 -> SentTime : [2016-02-11] 04:11:39:00366 with status OK_EMPTY -> ReceivedTime : [2016-02-11] 04:11:52:00459 / [2016-02-11] 04:11:52:00459
[Send Test] EventCallback execute() >>> Thread ID :  23502 / [2016-02-11] 04:11:52:00459
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

[Send Test] IoT Hub responded to message sent at : Event Message #6823 -> SentTime : [2016-02-11] 04:11:38:00350 with status OK_EMPTY -> ReceivedTime : [2016-02-11] 04:11:52:00509 / [2016-02-11] 04:11:52:00509
[Send Test] EventCallback execute() >>> Thread ID :  23503 / [2016-02-11] 04:11:52:00509
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

[Send Test] IoT Hub responded to message sent at : Event Message #6824 -> SentTime : [2016-02-11] 04:11:38:00559 with status OK_EMPTY -> ReceivedTime : [2016-02-11] 04:11:52:00509 / [2016-02-11] 04:11:52:00509
[Send Test] EventCallback execute() >>> Thread ID :  23504 / [2016-02-11] 04:11:52:00509
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

[Send Test] IoT Hub responded to message sent at : Event Message #6827 -> SentTime : [2016-02-11] 04:11:39:00167 with status OK_EMPTY -> ReceivedTime : [2016-02-11] 04:11:52:00509 / [2016-02-11] 04:11:52:00509
[Send Test] EventCallback execute() >>> Thread ID :  23501 / [2016-02-11] 04:11:52:00509
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++ 

[Send Test] IoT Hub responded to message sent at : Event Message #6826 -> SentTime : [2016-02-11] 04:11:38:00960 with status OK_EMPTY -> ReceivedTime : [2016-02-11] 04:11:52:00559 / [2016-02-11] 04:11:52:00568
[Send Test] EventCallback execute() >>> Thread ID :  23500 / [2016-02-11] 04:11:52:00568
[Send Test] End ++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by GwangseokHahm** [comment]
I think you can reproduce this problem by unplugging network cable during sending events.

**Comment by iluican** [comment]
Hello Gwangseok,

The SDK is doing its best to preserve the order of the messages, but that is not a guarantee. I you really care about ordering, I suggest sending the messages one at a time, i.e. wait for the callback of a message to be fired before attempting to send the next message.

Please let me know if this answers your issue.

Thank you.

**Comment by GwangseokHahm** [comment]
Thanks for your response.

Actually I’m DSA in Korea Azure Team and this requirement about the order of the message is from our customer Samsung Electronics.

They have messages exceeded the size limit. So, they have no another option to split the messages.

We have a meeting with Samsung Electronics and our R&D / CAT Team of HQ tomorrow.

I think Samsung Electronics will request this requirement.

Thanks.

Gwangseok.

**Comment by iluican** [comment]
Gwangseok,

We were talking about this amongst ourselves as well. We will add this requirement to our list of things to do, with high priority. I will get back to you when we have it.

Thank you,
Ilie.

**Comment by iluican** [comment]
Hi again,

As a part of the SDK rewrite to make it Java 7 compatible I made some changes to ensure that the messages are sent by the client in order while the connection is open. However, all bets are off when the connection is lost, as the order of the ACKs coming in from the server is not guaranteed. 

As previously stated, the only way to ensure the ordering of the messages is to wait for a message callback to be fired before sending the next one. I will close this issue now, as there is nothing more we can do about it.

Thank you,
Ilie.
