### ISSUE TITLE
AMQP transport failed to establish connection with service

### ISSUE THREAD

**Issue by LingYunJiangHaiqing** [Azure/azure-iot-sdks#307]
I according to the following URL action
https://azure.microsoft.com/zh-tw/documentation/articles/iot-suite-connecting-devices-linux/

When I Execute cmake / serializer / samples / remote monitoring / remote monitoring sample application.
I get two error messages:
1.Error: Time:Tue Feb 16 16:02:13 2016 File:/home/fit/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1129 AMQP transport failed to establish connection with service.
2.Error: Time:Tue Feb 16 16:02:13 2016 File:/home/fit/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:establishConnection Line:414 Failed to obtain a TLS I/O transport layer.

How do I resolve these errors?
Thank you.

**Comment by moonape1226** [comment]
I have the same problem too.
Is there anyone can help to solve this problem?

Thanks

**Comment by LingYunJiangHaiqing** [comment]
When I run c/build_all/linux/build.sh
I get the errors:

The following tests FAILED:
         48 - iothubclient_http_e2etests (SEGFAULT)
         50 - iothubclient_mqtt_e2etests (SEGFAULT)
         52 - iothubclient_amqp_e2etests (SEGFAULT)
Errors while running CTest

**Comment by srberard** [comment]
I have a similar problem.  When I link my own application I get the above errors continuously on the console.  But I don't get this with the sample applications.  From the messages it appears that it's related to the TLS library.  Perhaps there is a mismatch in TLS libraries.  Is there a specific version of openssl required?

Thanks.

**Comment by srberard** [comment]
OK, a slight bit of headway here.  It seems that a change was made recently requiring calling platform_init() prior to any other calls.

Adding this code addresses the errors above:
```
    if (platform_init() != 0) {
        postError(500, "Could not initialize platform.\n");
        return -1;
    }
```

You may need to update you local repository (and all submodules as well) in order to get the updated library and samples.

**Comment by tameraw** [comment]
@srberard - Thanks for your help with this. This fix was in the develop branch and now is published to master as well.
Closing this issue and please feel free to reopen if still having problems.
