### ISSUE TITLE
mqtt sendEvent memory leak detected

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdks#311]
I am getting memory leak from EventEmitter after few (10-50) messages sent. Here is the error and code.
```
...
msg sent
msg sent
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increa
se limit.
Trace
    at MqttClient.addListener (events.js:252:17)
    at Mqtt.publish (E:\Projects\iot-dev\node_modules\azure-iot-mqtt-base\lib\mqtt.js:130:17)
    at Mqtt.sendEvent (E:\Projects\iot-dev\node_modules\azure-iot-device-mqtt\lib\mqtt.js:72:14)
    at Client.sendEvent (E:\Projects\iot-dev\node_modules\azure-iot-device\lib\client.js:255:19)
    at null._repeat (E:\Projects\iot-dev\device-mqtt.js:17:16)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

```
var client = clientFromConnectionString(connectionString);
client.open(() => {
    console.log('connection opened')

    var msg = new Message('mqtt: some data from my device');

    setInterval(() => {
        client.sendEvent(msg, function (err) {
            if (err) console.log(err.toString());
            console.log('msg sent');
        });
    }, 1000);
    
    client.on('message', function(msg) {
        console.log(msg.data.toString());
        client.complete(msg, (err) => {
            console.log('completed');
        });
    });
});
```

**Comment by pierreca** [comment]
Thanks for reporting. this is a known bug. I'll update the status of this issue when I get to it.

**Comment by bmrpatel** [comment]
Update: I see that the issue only happens when I have another command prompt running the device code using amqp protocol for the same device connection string.

If I change the 2nd device code to use different device connection string then I am not seeing the memory leak error. Hence this issue may be irrelevant. Since there won't be multiple processing running against same device connection string.

**Comment by pierreca** [comment]
I think we should control that behavior anyway. thanks for reporting the details!
I'm not sure having the same device connecting using different protocols is supported. I also know for a fact that one device can only have one MQTT session open at a time and that opening another will close the first.

**Comment by pierreca** [comment]
Update on that bug: it only happens when the client is disconnected, not in the "happy path" when the connection is established. we're working on a fix.

**Comment by pierreca** [comment]
Should be fixed with https://github.com/Azure/azure-iot-sdks/commit/6f6210c2da8169b478cfb727b67f86bdbe5b7048
