### ISSUE TITLE
HttpRegistryManager.AddDeviceAsync fails for non-ASCII names

### ISSUE THREAD

**Issue by arturl** [Azure/azure-iot-sdks#317]
This API throws System.ArgumentException with "Bad Request" when presented with a Chinese name or a name with spaces inside. 

If non-ASCII names are not supported, should the id be validated in Device constructor?

If it is supported, the library should properly handle it by escaping.

**Comment by rajeevmv** [comment]
As documented [here](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide/#identityregistry), deviceid only supports ASCII 7-bit alphanumeric characters.

Currently, deviceId regex validation occurs only on the service. We could consider validating deviceid on the client side as well.

**Comment by tameraw** [comment]
@arturl - Closing as documentation captures this. Please feel free to reopen if you have concerns. Thanks.
