### ISSUE TITLE
HTTPAPIEX_E xecuteRequest 

### ISSUE THREAD

**Issue by alexdg18** [Azure/azure-iot-sdks#321]
Hi im following https://azure.microsoft.com/en-us/develop/iot/get-started/ example so:
I have done the servipack update.I wasnt sure about how to flash the certificate so I did it as follows:
-Formatted the cc3200 with 1MB capacity
-Added new file then ,name :/cert/ms.der ,url: \azure-iot-sdks\c\certs\ms.der.
-the .bin to the /sys/mcuimg.bin under System Files

I have checked erase, update ,verify check boxes as specified by http://processors.wiki.ti.com/index.php/CC31xx_%26_CC32xx_UniFlash#GUI_Interface

the error:
Info: IoT Hub SDK for C, version 1.0.0-preview.9
IoTHubClient accepted the message for delivery
Error: Time:Wed Aug 23 09:48:40 2028 File:../../adapters/httpapi_tirtos.c Func:H TTPAPI_CreateConnection Line:67 HTTPCli_initSockAddr failed, ret=-106
Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_E xecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Thu May 13 16:10:32 2032 File:../../src/iothubtransporthttp.c Func:D oEvent Line:1212 unable to HTTPAPIEX_ExecuteRequest
Error: Time:Thu May 13 16:10:32 2032 File:../../adapters/httpapi_tirtos.c Func:H TTPAPI_CreateConnection Line:67 HTTPCli_initSockAddr failed, ret=-106
Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_E xecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Thu May 13 16:10:32 2032 File:../../src/iothubtransporthttp.c Func:D

**Comment by ashokkhurana** [comment]
@alexdg18 , the steps you are following to install certificate are correct. The error message though also indicates that there is some issue with certificate credentials as explaining in other issue https://github.com/Azure/azure-iot-sdks/issues/209. I am arranging a TI 3200 device for myself to test it at my end. I will let you as I find anything.

**Comment by alexdg18** [comment]
Great,let me know because I have tried it on different ways,and still can't manage to connect the launchpad to the cloud

**Comment by ashokkhurana** [comment]
@alexdg18 , I tried this today on my CC3200 device and it worked perfectly fine for me. Here is the screenshot of what I am getting.
![ti3200-results](https://cloud.githubusercontent.com/assets/13988256/13341616/1e15674e-dbef-11e5-8c74-c1f7130d0fc9.PNG)
 
Could you please confirm if you made needed changes in wificonfig.h(for SSID Key and password) and main.c(for time stamp). I am following the instructions from link here https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/ti-rtos-ti-cc3200-c.md.

Also by any chance did you tried from more than one network. May be some network issue causing the connectivity with the IoT Hub.

**Comment by alexdg18** [comment]
Hi ,its working not 100% ok,but at least it connects to the cloud,I guess the issue with the time,is that I havent set it right on my pc?cuz I didt it on the main.c.

Is this example for sending just one message to the cloud when I run the program?


Starting the simplesample_http example
CC3200 has connected to AP and acquired an IP address.
IP Address: 10.79.1.16
Info: IoT Hub SDK for C, version 1.0.0-preview.9
IoTHubClient accepted the message for delivery
Error: Time:Wed Aug 23 09:48:40 2028 File:../../src/iothubtransporthttp.c Func:D                                                                                                 oEvent Line:1226 unexpected HTTP status code (401)
Message Id: 1 Received.
Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_OK
Starting the simplesample_http e

**Comment by ashokkhurana** [comment]
@alexdg18 , Good to see that you are able to progress here. Yes the example is for just sending one message to cloud. On the version thing, maybe you downloaded before our last release. Did you recently tried downloading from here https://github.com/Azure/azure-iot-sdks?

**Comment by alexdg18** [comment]
Thanks for your help,no I haven't tried but I will,th important thing is that I manage to connect to the cloud
