### ISSUE TITLE
Is there a way to get notified for Device status?

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdks#322]
I would like to get notified when device is turned on and connection opened to iot hub as well as turned off by disconnecting from iot hub or power failure. Do we have any efficient way to get notified using some event receiver pattern? I can do the polling to the Device Registry but that can unnecessarily load the server.

Thanks

**Comment by tameraw** [comment]
@bmrpatel - Thanks for the feedback. Which language are you using? We will consider this feature add for the future.

**Comment by bmrpatel** [comment]
:+1:  Thanks that will be great. I am using C# and node.js sdks.

**Comment by olivierbloch** [comment]
@bmrpatel - This feature  you are describing for the service will be added in the near future as part of a broader set of functionality. Stay tuned. In the meantime I will go ahead an close this issue.

**Comment by MattHoneycutt** [comment]
Any change on this issue?  Is polling the registry still the best way to track which devices are connected to your hub?

**Comment by bmrpatel** [comment]
I think querying device twin is the new way! I am not sure of any implementation in-progress, to notify you. You can implement yourself using events.
