### ISSUE TITLE
Building For TI CC3200 Problem

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#323]
The documentation tells the user to install the elf2cc32 application to *\azure-iot-sdks\c\serializer\samples\simplesample_http\tirtos\cc3200\tools* but the make file is now looking for this application at *C:\ti\ns_1_10_00_00_eng\tools*. This never used to be the case.

**Comment by tameraw** [comment]
@dominicbetts - The elf2cc32 is already part of the ti tools. No need for that step anymore. Thanks.
