### ISSUE TITLE
Move Pluto-Windows getting started instructions to uber get started doc

### ISSUE THREAD

**Issue by olivierbloch** [Azure/azure-iot-sdks#324]
This file https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/doc/Winows-PlutoE220-CSharp.md should be moved to https://github.com/Azure/azure-iot-sdks/tree/master/doc/get_started folder like all the others

**Comment by dominicbetts** [comment]
Hi @olivierbloch, should be OK to close this now.
