### ISSUE TITLE
Missing Run_sample doc for C# and node service client

### ISSUE THREAD

**Issue by olivierbloch** [Azure/azure-iot-sdks#328]
We should have a simple run_sample doc for the C# and node **service ** client samples like we have for the Java one.

**Comment by dominicbetts** [comment]
Should be OK to close now.

- I reinstated the missing Java doc for the service sample.
- I added the doc for the Node service sample.
- I couldn't see a C# service sample in the repo, so no doc

**Comment by tameraw** [comment]
Thanks @dominicbetts.
