### ISSUE TITLE
Missing ReadMe.md for device explorer tool

### ISSUE THREAD

**Issue by olivierbloch** [Azure/azure-iot-sdks#329]
we need a readme.md file for the device explorer tool https://github.com/Azure/azure-iot-sdks/tree/master/tools/DeviceExplorer
I recommend moving and renaming the "how to use device explorer" doc for that and ensuring all the other docs that point to it are updated

**Comment by dominicbetts** [comment]
Hi @olivierbloch, should be OK to close this one now.
