### ISSUE TITLE
Too short token valit time

### ISSUE THREAD

**Issue by GwangseokHahm** [Azure/azure-iot-sdks#330]
When I tested Java SDK, too many these exceptions happened.
(java.lang.IllegalStateException: The AMQPS IotHub Connection is currently closed. Call open() before attempting to consume a message.: The AMQPS IotHub Connection is currently closed. Call open() before attempting to consume a message.)

In the test after adding PN_TRACE_FRM env-variable, I found it happened because of 'Token Expired'
.

In DeviceClientConfig.java, TOKEN_VALID_SECS is 600 and I thought it means 600 seconds.
But, IotHubSasToken class construct the object by 600ms as below.

    public IotHubSasToken(DeviceClientConfig config)
    {
        this(IotHubUri.getResourceUri(config.getIotHubHostname(), config.getDeviceId()),
                config.getDeviceId(),
                config.getDeviceKey(),
                System.currentTimeMillis() / 1000l + config.getTokenValidSecs() + 1l);

        if (config.targetHubType == AzureHubType.IoTHub) {
            appendSknValue = false;
        } else if (config.targetHubType == AzureHubType.EventHub) {
            appendSknValue = true;
        }
    }

I think 600ms is too short time to validate tokens and originally 'TOKEN_VALID_SECS = 600' means 600 secs.

After I changed the code into 'TOKEN_VALID_SECS = 600', the exceptions did not happpen.

**Comment by dcristoloveanu** [comment]
Thanks for reporting this.
We've created a bug for this to track it and we hope to fix it soon.
It seems like the fix is rather simple, if you would like to contribute a fix, we welcome and appreciate all contributions.

Thanks,
/Dan

**Comment by GwangseokHahm** [comment]
Thanks.

Gwangseok.

**Comment by iluican** [comment]
Gwangseok,

Thank you for reporting this. I investigated and actually your finding is incorrect. The token validity time is indeed 600 seconds currently, and not 600ms. However, you are right that we should not throw those exceptions. I will use the bug Dan filed to fix that.

Thank you,
Ilie.

**Comment by tameraw** [comment]
Fixed in develop branch. Closing issue. Thanks.
