### ISSUE TITLE
build.sh Fails for simplesample_http When Compiling For the Arduino Yun

### ISSUE THREAD

**Issue by jmwright** [Azure/azure-iot-sdks#331]
I'm trying to follow the Arduino Yun example instructions [here](https://github.com/Azure/azure-iot-sdks/blob/b0cdd9eb2d496c1dd3b7da3f740c3dd3088277d5/doc/get_started/openwrt-arduino-yun-c.md)

If I'm in the arduino directory (azure-iot-sdks/c/build_all/arduino) and run build.sh I get the errors shown below. I am trying to build this on Ubuntu 15.10 64-bit, whereas the instructions specifically call out x86. This seems more like a makefile issue than a platform issue, but I'm not sure.
```
CMake Error at CMakeLists.txt:26 (add_subdirectory):
  add_subdirectory given source "azure-c-shared-utility/c" which is not an
  existing directory.


CMake Error at CMakeLists.txt:27 (add_subdirectory):
  The source directory

    /home/jwright/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/azure-uamqp-c

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:28 (add_subdirectory):
  The source directory

    /home/jwright/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdks-1/azure-umqtt-c

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

**Comment by dcristoloveanu** [comment]
The repo uses submodules so when cloned you need to use the --recursive flag:
```c
git clone --recursive https://github.com/Azure/azure-iot-sdks.git
```

If you already cloned it without recursive, you can update the submodules after cloning by running:
```c
git submodule update --init --recursive
```

HTH,
/Dan

**Comment by jmwright** [comment]
Thanks @dcristoloveanu
