### ISSUE TITLE
Using HTTP protocol for DeviceClient

### ISSUE THREAD

**Issue by stansa** [Azure/azure-iot-sdks#332]
Greetings,

I've been testing the samples and all of them work except if I try to send a JSON serialized message over HTTPS. 

I get this back in the callback:
IoT Hub responded to message with status INTERNAL_SERVER_ERROR

Here is snippet:

              _ DeviceClient client = new DeviceClient(connStr, IotHubClientProtocol.HTTPS);
                DeviceToCloudData data = new DeviceToCloudData();
                data.humidity = 32;
                data.humidity = 70;

                String msgStr = data.serialize();

                System.out.println("Sending Data..." + msgStr);

                Message msg = new Message(msgStr);

                runClient.sendEventAsync(msg, call, null);_

Switching to non json message or setting AMQP/MQTT works just fine.

Thanks.

**Comment by stansa** [comment]
BTW I was looking for a way to specify the application/json content type via the Device client class but don't see that interface exposed.

**Comment by tameraw** [comment]
@stansa - We'll attempt a repro. Thanks.

**Comment by iluican** [comment]
Hello,

Apologies for the delayed answer. I tried to repro your issue, but I was not able to. Could you please try with the latest SDK and let us know if you're still seeing errors?

Thank you,
Ilie.

**Comment by iluican** [comment]
I will close this issue, as I was not able to repro it.

Thank you,
Ilie.
