### ISSUE TITLE
C SDK - Ubuntu 14.04 LTS build fails 3 tests

### ISSUE THREAD

**Issue by LingYunJiangHaiqing** [Azure/azure-iot-sdks#333]
I get a virtual machine in Azure. Use Ubuntu Server 14.04 LTS.
I make sure cmake version 3.2.2 and gcc version 4.9.3

When I run c/build_all/linux/build.sh
I get the errors:

=================================================
96% tests passed, 3 tests failed out of 71

Total Test time (real) =   2.46 sec

The following tests FAILED:
         48 - iothubclient_http_e2etests (SEGFAULT)
         50 - iothubclient_mqtt_e2etests (SEGFAULT)
         52 - iothubclient_amqp_e2etests (SEGFAULT)
Errors while running CTest
=================================================

How do I resolve these errors?
Thank you.

**Comment by LingYunJiangHaiqing** [comment]
I had follow this url:
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_end_to_end_tests.md

still got the same errors

**Comment by RamPrasadRP** [comment]
1) Double check the **iot_device_params** given in the **"iot_device_params.txt"**. 

2) Check whether the environment variables have been successfully exported by using the command 
> $ env | grep "IOT"

This should solve the problem :)

**Comment by LingYunJiangHaiqing** [comment]
Thank you for your answer

Environment variables had set, but according to url "Run End to End Tests".
One of the environment variables setting for IOTHUB_EVENTHUB_CONNECTION_STRING=Endpoint=[Event Hub-compatible endpoint];SharedAccessKeyName=[IOTHUB_POLICY_NAME];SharedAccessKey=[IOTHUB_POLICY_KEY]
I do not know whether the settings are correct
