### ISSUE TITLE
Node.js support for sending commands to device (C2D)

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdks#337]
Are there any plans to support C2D for node.js?

C#:
await serviceClient.SendAsync("myFirstDevice", commandMessage);

**Comment by dcristoloveanu** [comment]
@wmmihaa 
The functionality is available. In node/service/lib/client.js

/**
 * @method            module:azure-iothub.Client#send
 * @description       Sends a message to a device.
 * @param {String}    deviceId  The identifier of an existing device identity.
 * @param {}          message   The body of the message to send to the device.
 *                              If `message` is not of type
 *                              {@link module:azure-iot-common.Message|Message},
 *                              it will be converted.
 * @param {Function}  done      The function to call when the operation is
 *                              complete. `done` will be called with two
 *                              arguments: an Error object (can be null) and a
 *                              transport-specific response object useful for
 *                              logging or debugging.
 */
Client.prototype.send = function send(deviceId, message, done) {

It is used also in our tool (iothub-explorer).

If this solves it, let me know if the issue can be closed.

Thanks!
/Dan

**Comment by wmmihaa** [comment]
Great, thanks.
