### ISSUE TITLE
node.js service client : error while sending message

### ISSUE THREAD

**Issue by sachinkale** [Azure/azure-iot-sdks#342]
Error: Must connect before creating links
    at AMQPClient.createSender (/home/xxxx/node_modules/amqp10/lib/amqp_client.js:156:11)
    at Amqp.send (/home/xxxx/node_modules/azure-iot-amqp-base/lib/amqp.js:168:16)
    at Amqp.send (/home/xxxx/node_modules/azure-iothub/lib/amqp.js:71:14)
    at Client.send (/home/xxxx/node_modules/azure-iothub/lib/client.js:163:19)
    at Object.<anonymous> (/home/xxxx/tmp.js:15:8)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

--

The code is:
--

```
var iothub = require('azure-iothub');
var connectionString = 'xxxxx';

var client = new iothub.Client.fromConnectionString(connectionString);


client.send('xxxxx-device-id','hi there',function(){ console.log('done')});
```
--

Node version:
{"node":"5.4.1","npm":"3.3.12"})

Installed dependencies and version:
├─┬ azure-iothub@1.0.1
│ ├─┬ azure-iot-amqp-base@1.0.1
│ │ ├─┬ amqp10@2.2.5
│ │ │ ├─┬ bl@1.1.2
│ │ │ │ └─┬ readable-stream@2.0.5
│ │ │ │   ├── core-util-is@1.0.2
│ │ │ │   ├── inherits@2.0.1
│ │ │ │   ├── isarray@0.0.1
│ │ │ │   ├── process-nextick-args@1.0.6
│ │ │ │   ├── string_decoder@0.10.31
│ │ │ │   └── util-deprecate@1.0.2
│ │ │ ├── bluebird@3.3.1
│ │ │ ├── buffer-builder@0.2.0
│ │ │ ├── lodash@4.5.1
│ │ │ ├── node-amqp-encoder@0.0.2
│ │ │ ├── node-int64@0.4.0
│ │ │ └── stately.js@1.3.0
│ │ ├─┬ amqp10-transport-ws@0.0.2
│ │ │ └── nodejs-websocket@1.5.0
│ │ └─┬ debug@2.2.0
│ │   └── ms@0.7.1
│ ├─┬ azure-iot-common@1.0.1
│ │ └── crypto@0.0.3
│ ├── azure-iot-http-base@1.0.1
│ └── uuid@2.0.1

Let me if there is a workaround for this bug

Thanks

**Comment by pierreca** [comment]
you should call `client.open(function() {...})` before you actually call send in order to establish the connection.

**Comment by azaslonov** [comment]
it would be nice if you guys added this "client.open" example to your documentation

**Comment by pierreca** [comment]
indeed, sorry we missed that. which document were you using?

**Comment by sachinkale** [comment]
I could not find any documentation. I looked up lib/client.js
Message sending without open call worked for azure-iothub@1.0.0-preview.9

The documentation of how to send should be at https://github.com/Azure/azure-iot-sdks/tree/master/node/service

For me, 
`client.open(function(){ client.send....}) `
worked. Thanks

**Comment by pierreca** [comment]
I see. you fell into a crack created by breaking changes when we release version 1.0.0, sorry about that. We will review and update docs and samples accordingly. Closing the issue, feel free to reopen if necessary.
