### ISSUE TITLE
Error building azure-c-shared-utility for Yun/OpenWRT

### ISSUE THREAD

**Issue by netgio** [Azure/azure-iot-sdks#344]
Building on a clean vagrant ubuntu/trusty image.

I get the following errors 

> [ 21%] Building C object azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir
> /adapters/socketio_berkeley.c.o
> /home/vagrant/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdk
> s-1/azure-c-shared-utility/c/adapters/socketio_berkeley.c: In function 'socketio
> _open':
> /home/vagrant/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdk
> s-1/azure-c-shared-utility/c/adapters/socketio_berkeley.c:228:24: error: variabl
> e 'addrHint' has initializer but incomplete type
> /home/vagrant/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdk
> s-1/azure-c-shared-utility/c/adapters/socketio_berkeley.c:228:24: warning: exces
> s elements in struct initializer [enabled by default]
> /home/vagrant/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdk
> s-1/azure-c-shared-utility/c/adapters/socketio_berkeley.c:228:24: warning: (near
>  initialization for 'addrHint') [enabled by default]
> /home/vagrant/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdk
> s-1/azure-c-shared-utility/c/adapters/socketio_berkeley.c:228:33: error: storage
>  size of 'addrHint' isn't known
> /home/vagrant/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdk
> s-1/azure-c-shared-utility/c/adapters/socketio_berkeley.c:234:17: warning: impli
> cit declaration of function 'getaddrinfo' [-Wimplicit-function-declaration]
> /home/vagrant/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdk
> s-1/azure-c-shared-utility/c/adapters/socketio_berkeley.c:244:71: error: derefer
> encing pointer to incomplete type
> /home/vagrant/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdk
> s-1/azure-c-shared-utility/c/adapters/socketio_berkeley.c:244:98: error: derefer
> encing pointer to incomplete type
> /home/vagrant/openwrt/sdk/build_dir/target-mips_r2_uClibc-0.9.33.2/azure-iot-sdk
> s-1/azure-c-shared-utility/c/adapters/socketio_berkeley.c:279:21: warning: impli
> cit declaration of function 'freeaddrinfo' [-Wimplicit-function-declaration]

The line that triggers this is 
`            struct addrinfo addrHint = { 0 };`

Looking at the repo for azure-c-shared-utility it looks like there has been a whole bunch of development that has not been merged back into the master.  Is there a branch that addresses this?  Or am I doing something dumb in my build steps (just following the readme.md).

**Comment by jmwright** [comment]
The Linux desktop preparation instructions mention upgrading gcc on 14.04: https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md#set-up-a-linux-development-environment

Maybe that's your problem? I don't seem to have any problem building the examples for the Arduino on 15.10.

**Comment by rajeshgande** [comment]
updating cmake to 3.2 and gcc to 4.9 on ubuntu 14.04 worked.

**Comment by netgio** [comment]
Upgrading to Ubuntu 15.10 resolved this.

**Comment by NambiarAtNXP** [comment]
Hi All,
I have the same issue, but my host is Ubuntu 16.04 and gcc , cmake versions are 5.4.0 and 3.5.1 I doubt its due to the gcc version of Openwrt which is 4.8. Any possible inputs.

Thanks
Nambiar
