### ISSUE TITLE
Receiving messages from device - no transport

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdks#347]
Hi,
I'm trying to follow the samples as:
var device = require('azure-iot-device');
var receiver = device.Client.fromConnectionString(connectionString, device.Amqp);

but the device.Amqp is undefined. What am I doing wrong?

**Comment by wmmihaa** [comment]
From what I can see there are no transports in the package (1.0.1). The only files in the package is:

- client.js
- connection_string.js
- shared_access_signature.js


According to the samples I should be able to do this
var mqtt = require('azure-iot-device').Mqtt;

**Comment by pierreca** [comment]
Hi
you have to require('azure-iot-device-amqp') (or mqtt, or http).
See https://github.com/Azure/azure-iot-sdks/blob/master/node/device/samples/simple_sample_device.js#L6 for an example

**Comment by wmmihaa** [comment]
Thank you again.

**Comment by pierreca** [comment]
@wmmihaa  closing since it looks like this was the answer you were looking for. feel free to reopen if it wasn't the case.
