### ISSUE TITLE
Is there a good way to create devices with send privilages

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdks#348]
I have a scenario where devices needs to forward messages to other devices. So  I just added the service lib to the device to, but obviously it only has read privs. Is there a good way to provide Send privilages as well.

**Comment by rajeevmv** [comment]
Use the SharedAccessPolicy credentials named "service". You will find it in the Settings tab of your IotHub in the Azure portal.

**Comment by wmmihaa** [comment]
Thans @rajeevmv, but where do I set the policy? I've been looking at the DeviceExplorer to get an idea, and this is all I can find:

var device = new Device(deviceIDTextBox.Text);
await registryManager.AddDeviceAsync(device);
device = await registryManager.GetDeviceAsync(device.Id);
device.Authentication.SymmetricKey.PrimaryKey = primaryKey;
device.Authentication.SymmetricKey.SecondaryKey = secondaryKey;
device = await registryManager.UpdateDeviceAsync(device);

**Comment by rajeevmv** [comment]
To send messages to another device, you need to use ServiceClient:

 string connectionString = <'service' policy connection string>;
 var serviceClient = ServiceClient.CreateFromConnectionString(connectionString);
 var messageToDevice = new Message(Encoding.UTF8.GetBytes("<message to Device>"));
 await serviceClient.SendAsync(<device1 Id>, messageToDevice);

**Comment by wmmihaa** [comment]
I create and provide the connectionstring to the device based on the device symmetricKey. 
"HostName=XXX.azure-devices.net;DeviceId=device1;SharedAccessKey=[...]";

Is it correct that I cannot grant Read & Write privilages to the device, other than providing an additional Shared Access Key generated from the portal?

**Comment by rajeevmv** [comment]
A device symmetric key allows a device only to send telemetry data and receive commands.                   You cannot "forward" events to another device. You are effectively sending a command. In order to send a command to another device, you need to use ServiceClient which has IotHub-scope credentials.

**Comment by wmmihaa** [comment]
Got it, thanks!

**Comment by rajeevmv** [comment]
Closing this issue.
