### ISSUE TITLE
MQTT nuget package 1.02 doesn't export any functions in release build

### ISSUE THREAD

**Issue by mregen** [Azure/azure-iot-sdks#350]
Building a win32 solution dll in VS2015 referencing the packages on Nuget:

I'm referencing this package 
  package id="Microsoft.Azure.IoTHub.MqttTransport" version="1.0.2" targetFramework="native" 
but I'm getting this link error, only for Release (works fine in Debug builds):
1>iothub_client_python.def : error LNK2001: unresolved external symbol MQTT_Protocol

**Comment by tameraw** [comment]
@mregen  - A fix is on the way.

**Comment by tameraw** [comment]
Fixed in develop branch. Closing issue. Thanks.
