### ISSUE TITLE
AMQP nuget packages outputs a lot of debug spew, both Debug/Release builds

### ISSUE THREAD

**Issue by mregen** [Azure/azure-iot-sdks#351]
Building a win32 solution dll in VS2015 referencing the packages on Nuget:

I'm referencing this package
package id="Microsoft.Azure.IoTHub.AmqpTransport" version="1.0.2" targetFramework="native" 

running my sample it is full of debug spew from the AMQP  lib:
How to turn it off?

IoTHubClient_SendEventAsync accepted message [3] for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted message [4] for transmission to IoT Hub.
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {default_container_id,mregen-python-ne-iothub.azure-devices.net,4294967295,65535}
<- [OPEN]* {DeviceGateway_1f5ec375708b4d2491840d9b761fabc8,10.0.0.51,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
-> [ATTACH]* {cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,65535}
-> [ATTACH]* {cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,65535}
<- [ATTACH]* {cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,65535,NULL,NULL,NULL}
<- [FLOW]* {0,100,1,5000,0,0,100,0,NULL,false,NULL}
<- [ATTACH]* {cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65535,NULL,NULL,NULL}
-> [FLOW]* {1,4294967295,0,100,1,0,10000}
-> [TRANSFER]* {0,0,<00 00 00 00>,0,false}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
<- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}
-> [ATTACH]* {receiver-link,2,true,0,0,* {amqps://mregen-python-ne-iothub.azure-devices.net/devices/test/messages/devicebound},* {ingress-rx},NULL,NULL,NULL,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.1]}}
-> [ATTACH]* {sender-link,3,false,0,0,* {ingress},* {amqps://mregen-python-ne-iothub.azure-devices.net/devices/test/messages/events},NULL,NULL,0,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.1]}}
<- [ATTACH]* {receiver-link,2,false,0,0,* {amqps://mregen-python-ne-iothub.azure-devices.net/devices/test/messages/devicebound,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {ingress-rx,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.1]}}
-> [FLOW]* {2,4294967294,1,99,2,0,10000}
<- [ATTACH]* {sender-link,3,true,0,NULL,* {ingress,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://mregen-python-ne-iothub.azure-devices.net/devices/test/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.1]}}
<- [FLOW]* {1,100,2,4294967295,3,0,1000,0,NULL,false,NULL}
-> [TRANSFER]* {3,1,<00 00 00 00>,0,false}
-> [TRANSFER]* {3,2,<01 00 00 00>,0,false}
-> [TRANSFER]* {3,3,<02 00 00 00>,0,false}
-> [TRANSFER]* {3,4,<03 00 00 00>,0,false}
-> [TRANSFER]* {3,5,<04 00 00 00>,0,false}
<- [DISPOSITION]* {true,1,2,true,* {},NULL}
Confirmation[0] received for message with result = 0
Confirmation[1] received for message with result = 0
<- [DISPOSITION]* {true,3,NULL,true,* {},NULL}
Confirmation[2] received for message with result = 0
<- [DISPOSITION]* {true,4,5,true,* {},NULL}
Confirmation[3] received for message with result = 0
Confirmation[4] received for message with result = 0

**Comment by tameraw** [comment]
@mregen - This is currently not supported. We have PBI in our backlog address logging at some point and manage enabling/disabling the spew. As always, contributions are welcome.

**Comment by mregen** [comment]
this code suppresses *most* of the AMQP output
`// helper to suppress AMQP console messages, comment function to get the output to console`
`extern "C" void consolelogger_log(unsigned int options, char* format, ...) {}`
