### ISSUE TITLE
BUG: Unable to do send message with properties

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdks#352]
File: $azure-iot-sdks\node\service\lib\client.js
Function: send

My code:
```
var message = new Message({ "id": 42 })
message.properties.add('myproperty', 'myvalue');

// Just for testing
if (!(message instanceof Message)) {
    console.log("This should not happen"); // Not triggered
}
var sender = iothub.Client.fromSharedAccessSignature("...");

sender.open(function (err) {
    sender.send("device1", message, function (err) {
        console.log("done");
    });
});
```
In the client.js send function, the message is not treated as a Message, hence it creates a new message:
```
if (!(message instanceof Message)) {
    message = new Message(message); // This code is triggered...
}
```
I guess the problem is worse than the fact it's not honoring my properties...

HTH

**Comment by pierreca** [comment]
@wmmihaa quick verification, is it possible that you have npm links in your node_modules folders? 

One reason I could see `instanceof` failing to recognize that your `message` is of type `Message` is if you're running with different versions of the `azure-iot-common` module in the `service` folder (home of the `azure-iothub` package) and in your code

**Comment by pierreca** [comment]
@wmmihaa please let us know whether my previous answer helped or if you're still blocked :) If there's a bug somewhere I'd like to fix it before the next release :)

**Comment by wmmihaa** [comment]
@pierreca Sorry for late reply, but no I don't have any npm links, however I've updated the client.js (device) file in the npm package as I have the encoding issue with the fromSharedAccessSignature related to to #349. Could that have anything to do with it?

**Comment by pierreca** [comment]
I don't think it's related. what you are describing is `instanceof` failing to recognize that your message is of actually an instance of `Message`. 
the `Message` object that you are creating is of type `require('azure-iot-common').Message, right?

**Comment by pierreca** [comment]
Appart from the instanceof issue you're experiencing, I took a hard look at the implementation of custom properties on messages in our SDK for all transports and it's lacking key features. as such, I've added a bunch of work items in our backlog to catch up on this feature, which at this point should not be considered implemented (Except for sending messages from the device to the cloud in HTTP). 
Once we solve this instanceof issue I'll close this, which I'm tagging "added to backlog" while we work on the full implementation.

**Comment by wmmihaa** [comment]
Sounds good. I'll check up on the instanceof issue, and let me know if there is anything I can do to help.

**Comment by pierreca** [comment]
@wmmihaa Cool, thanks for understanding. 
I'm still a little bit concerned about that `instanceof` issues so please let me know what you find. the last question was: 
the  `Message`  object that you are creating is of type  `require('azure-iot-common').Message` , right?

**Comment by wmmihaa** [comment]
I did `var Message = require('azure-iot-device').Message;`
Should it be `require('azure-iot-common')`?

**Comment by wmmihaa** [comment]
BTW I get the same issue with `require('azure-iot-common')`

**Comment by pierreca** [comment]
@wmmihaa what version of node are you running?

**Comment by wmmihaa** [comment]
4.2.3

**Comment by pierreca** [comment]
@wmmihaa I still can't get to repro the issue. I installed the same version of node, setup the message and client exactly like you do, and instanceof work as expected. 

- Are you running on windows or Linux?
- would you mind extracting from your code the simplest possible sample that exhibits the issue, and package.json into a repo that I could just clone and npm install? 

also, what environment are you using to write this code? any debugger/code editor? how do you run the process?

**Comment by pierreca** [comment]
@wmmihaa i'm still willing to help if I can on the `instanceof` issue, although I'm still not sure what's going on and haven't been able to repro. let me know if you'd rather close the issue and figure this out on your own.

**Comment by wmmihaa** [comment]
Thank you @pierreca. I've been occupied at a different customer site, so sorry for the late reply. 
I'm on a different laptop here, and pulled the repo and tried from here, and it works as expected. Let me give it another try from home later this evening, to see if I can find out where the difference is.

Should be before noon (PDT).

**Comment by wmmihaa** [comment]
@pierreca Sorry to say but I stil get a different behavior when running the same code from the same repo (and updated all packages) at home.

Weird!

**Comment by pierreca** [comment]
Another test you can run just to verify that `instanceof` works as expected:
get this gist: https://gist.github.com/pierreca/fa57a0f87f43ab52c77e
run `node instanceof.js`
you should get this console output:
```
msg is Foo
msg is Foo inside a function
msg is Foo inside Bar
```

**Comment by pierreca** [comment]
@wmmihaa I ran into the `instanceof` bug again today, and got to the bottom of it. Again it was a dependency tree thing, and the `Message` class used to do the comparison in `client.js` in the `azure-iothub` package was different than the one used in the app code. More specifically:
`client.js` was using `<app>\node_modules\azure-iothub\node_modules\azure-iot-common\lib\message.js` whereas the app itself was using `<app>\node_modules\azure-iot-device\node_modules\azure-iot-common\lib\Message.js`. Technically it's exactly the same code, but I'm guessing `instanceof` takes the path into account and if it's not the same path for the `Message` code, it just returns false.

The solution was to add a dependency to `azure-iot-common` in the app itself, making it common for all the code.

I thought npm flattened the dependency tree completely, looks like it's not always the case (at least not all all versions. this time it was npm 2.15.0 and node 4.4.2 if my memory's correct

HTH!

**Comment by wmmihaa** [comment]
Fantastic. I bet that took a while to figure out ;)
