### ISSUE TITLE
renewal of SAS does not work with HTTP

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-iot-sdks#354]
When updateSharedAccessSignature is invoked, 'this._receiver' is not set on an instance!

Http.prototype.updateSharedAccessSignature = function (sharedAccessSignature, done) {
  /*Codes_SRS_NODE_DEVICE_HTTP_16_006: [The updateSharedAccessSignature method shall save the new shared access signature given as a parameter to its configuration.] */
  this._config.sharedAccessSignature = sharedAccessSignature;
  **this._receiver**.setSharedAccessSignature(sharedAccessSignature);
  /*Codes_SRS_NODE_DEVICE_HTTP_16_007: [The updateSharedAccessSignature method shall call the `done` callback with a null error object and a SharedAccessSignatureUpdated object as a result, indicating that the client does not need to reestablish the transport connection.] */
  done(null, new results.SharedAccessSignatureUpdated(false));
};

**Comment by ddobric** [comment]
Here is the solution:

Http.prototype.updateSharedAccessSignature = function (sharedAccessSignature, done) {

    Http.prototype.updateSharedAccessSignature = function (sharedAccessSignature, done) {
    
        this._config.sharedAccessSignature = sharedAccessSignature;

        this.getReceiver(function (err, receiver) {
            /*Codes_SRS_NODE_DEVICE_HTTP_16_006: [The updateSharedAccessSignature method shall save the new shared access signature given as a parameter to its configuration.] */
            receiver.setSharedAccessSignature(sharedAccessSignature);
            /*Codes_SRS_NODE_DEVICE_HTTP_16_007: [The updateSharedAccessSignature method shall call the `done` callback with a null error object and a SharedAccessSignatureUpdated object as a result, indicating that the client does not need to reestablish the transport connection.] */
            done(null, new results.SharedAccessSignatureUpdated(false));
        });

// O L D  C O D E... Just remove it...
    ///*Codes_SRS_NODE_DEVICE_HTTP_16_006: [The updateSharedAccessSignature method shall save the new shared access signature given as a parameter to its configuration.] */
    //this._config.sharedAccessSignature = sharedAccessSignature;
    //this._receiver.setSharedAccessSignature(sharedAccessSignature);
    ///*Codes_SRS_NODE_DEVICE_HTTP_16_007: [The updateSharedAccessSignature method shall call the `done` callback with a null error object and a SharedAccessSignatureUpdated object as a result, indicating that the client does not need to reestablish the transport connection.] */
    //done(null, new results.SharedAccessSignatureUpdated(false));
};

Sorry didn't have a time for pull-request...

**Comment by pierreca** [comment]
thanks for reporting this. bugfix is on the way to the develop branch, will make it to the next release.
