### ISSUE TITLE
Xamarin - Supported Mobile Platforms (Android / iOS )

### ISSUE THREAD

**Issue by btusca** [Azure/azure-iot-sdks#357]
The important thing of IoT is the power to get information and get it as soon as possible, and I think that cover to get the information on our mobile platforms. I'm trying to find a way to use the SDK in mobile platforms.
In Android it's possible to set the mobile phone as a '_Device_' and send Device to cloud messages (See What about iot-hub on android device #244 )
What about iOS? Is it possible to get the C-SDK working on iOS?
If not, Did anybody try to use the Azure IoT C# SDK in Xamarin?
Is Microsoft working on extend the supported mobile platforms?

Here we can vote to ask for support on mobile platforms:
https://feedback.azure.com/forums/321918-azure-iot/suggestions/11715588-android-support-for-the-device-sdk
https://feedback.azure.com/forums/321918-azure-iot/suggestions/11715597-ios-support-for-the-device-sdk

Thanks

**Comment by tameraw** [comment]
@btusca - Thanks for your feedback.
We are indeed working on extending support to several of the platforms you mentioned above. We also happily accept contributions if you're interested in contributing to any of these. Thanks.

**Comment by tameraw** [comment]
@btusca - A PCL NuGet package has been released supporting UWP, Android & iOS.
