### ISSUE TITLE
npm: azure-iot-device-http defect function

### ISSUE THREAD

**Issue by encrypted90** [Azure/azure-iot-sdks#360]
Hello

There might be a bug in the [azure-iot-device-http](https://www.npmjs.com/package/azure-iot-device-http) node package.

Executing the getting started script an error is raised: Function getReceiver is an unknown function. 
Solution: change `client.getReceiver` to `client._transport.getReceiver`

**Comment by pierreca** [comment]
Hi 
this sounds like a documentation issue. which one were you looking at?
`client.getReceiver()` has been deprecated and fields that start with `_` are considered private. 
The right fix is to subscribe directly to `client.on('message', fn(msg){})`

**Comment by pierreca** [comment]
OK looks like the problem is in the npm page itself, and applies to all transport packages. These are the readme.md files at the root of each transport package directory:
- node/device/transport/amqp
- node/device/transport/amqp-ws
- node/device/transport/http
- node/device/transport/mqtt

**Comment by encrypted90** [comment]
Yes I see. The same problem arises with node package azure-iot-device-mqtt / amqp aswel.

**Comment by pierreca** [comment]
@dominicbetts please keep me posted on the resolution of this issue, let me know if I can help in any way.

**Comment by dominicbetts** [comment]
@pierreca should be OK to close as soon as the PR is accepted.

**Comment by pierreca** [comment]
@dominicbetts indeed. thanks!
