### ISSUE TITLE
Missing DeviceToCloudMessageCount

### ISSUE THREAD

**Issue by khilscher** [Azure/azure-iot-sdks#362]
Would be nice to have DeviceToCloudMessageCount. Only have CloudToDeviceMessageCount today.

**Comment by tameraw** [comment]
@khilscher - Thanks for your feedback. This is currently not in our priority list, but we would happily accept contributions.

**Comment by tameraw** [comment]
@khilscher - Currently not in our plans to add this feature. If still interested, please feel free to contribute to the repo. Thanks.
