### ISSUE TITLE
Shared Access Signature in IoT Hub Client

### ISSUE THREAD

**Issue by asebak** [Azure/azure-iot-sdks#367]
This is the code:

DeviceClient client = new DeviceClient(connectionString, IotHubClientProtocol.HTTPS);

I am using SharedAccessSignature and not SharedAccessKey and throws an error:

throw new IllegalArgumentException("Device key cannot be null.");

I assume you guys didn't implement the java client to use sas tokens?

**Comment by tameraw** [comment]
@asebak - Correct. Today we generate the SAS token internal to the client. But it is in our backlog to accept a SAS token as input as well.

**Comment by tameraw** [comment]
@asebak - The Java Wrapper should now have this option available. It was introduced in our c-client and inherently the Java Wrapper gets this too. Let us know if you encounter any issues with this.
