### ISSUE TITLE
Cannot build Java device-manager-sample

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdks#368]
Executing `mvn clean package` in folder java\service\samples\device-manager-sample results in a dependency error.

The same occurs with the java\service\samples\service-client-sample.

Looking in the Maven Central Repository, I can only see the following is available:
```
<dependency>
    <groupId>com.microsoft.azure.iothub-java-client</groupId>
    <artifactId>iothub-java-service-client</artifactId>
    <version>1.0.0-preview.9</version>
</dependency>
```

**Comment by iluican** [comment]
Yes, it looks like our latest package never made it to maven. We will fix this asap.

**Comment by iluican** [comment]
This is no longer an issue.

Thank you,
Ilie.
