### ISSUE TITLE
 .Net Compact Framework implementation

### ISSUE THREAD

**Issue by henrikstromberg** [Azure/azure-iot-sdks#37]
Windows CE and .NET Comact framework are quite big in the industry today andy plans to implement it for Windows CE ?

**Comment by valter-minute-tx** [comment]
We (Toradex) are working on this and we already have something working on our devices. We could not release it at the moment because it needs some polishing and testing, but I hope it's not going to take too long.

**Comment by dcristoloveanu** [comment]
If you already have it running for CE, can you share a PR?
Also as a note, we have switched to cmake in our recent release, that might require some changes in your port.

**Comment by valter-minute-tx** [comment]
We have it running on CE, but I need to polish it and check that it builds on CMake before we can do a pull request.
Hope to be able to do that in the next few days.
Also running on .NET CF will require a DLL and I built a static C library ATM.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Mon, Oct 19, 2015 at 11:00 AM -0700, "Dan Cristoloveanu" <notifications@github.com<mailto:notifications@github.com>> wrote:


If you already have it running for CE, can you share a PR?
Also as a note, we have switched to cmake in our recent release, that might require some changes in your port.

-

**Comment by VMinute** [comment]
I submitted a pull-request to enable Windows CE support.
It currently builds a C library, so next step would be generate a DLL, so those functions can be p-invoked from .NET code.
The library invokes some callbacks, but those can be implemented in managed code as well.
Are you willing to collaborate in adding a managed wrapper to it? We should also understand where it would fit inside the SDK. It's managed, but it's not the standard C# client, it may need a new top-level folder.

**Comment by tameraw** [comment]
CE2013 pull request has been merged. Closing this issue. Thanks.

**Comment by VMinute** [comment]
The Compact 2013 pull-request builds a static library, you may need to link it as a DLL to be able to p-invoke its functions from the .NET Compact Framework.
