### ISSUE TITLE
npm: Receiving Messages from the IoT Hub using Node.js

### ISSUE THREAD

**Issue by m1sterc001guy** [Azure/azure-iot-sdks#373]
Hello,

I am trying to receive messages from my IoT Hub using Node.js. I used the simple_sample_device.js as a guide to try and implement this and I ran into a few problems. For some reason when calling client.open() an error would be thrown saying that "undefined is not a function". I'm using AMQP as my protocol, but it looks like a similar error happens when using HTTP or MQTT. I traced the error to azure-iot-device/lib/client.js. It seems the error goes away when commenting out the condition on line 210 ("if (this.listenerCount('message') > 0). Commenting this line out allows the client to connect to the IoT Hub and receive messages. Now, the problem is that it seems as though the callback is being invoked twice. To fix this, I commented out line 224 of azure-iot-device/lib/client.js to avoid connecting to the receiver twice. Is this a viable fix? Does the client.open() function have a bug in it or am I somehow using the API incorrectly?

Any help is appreciated.

**Comment by pierreca** [comment]
Hi @m1sterc001guy 
What version of node are you running? It looks like you're running into a bug that I ran into and fixed yesterday in the develop branch about node 0.12 compatibility (listenerCount() was implemented in later versions).
see https://github.com/Azure/azure-iot-sdks/blob/develop/node/device/core/lib/client.js#L210 for the fix that should do it.

**Comment by m1sterc001guy** [comment]
Ah yes I am running node version 0.12.6 I believe. I'll use your fix and try again. Thanks!
