### ISSUE TITLE
azure-iot-device-http on raspberry pi doesn't work when talking to azure iot hub

### ISSUE THREAD

**Issue by xiaoyongaz** [Azure/azure-iot-sdks#374]
I'm running the simple_sample_device.js and it works on my mac but on my pi device I always get below error:
getaddrinfo ENOTFOUND Tijee.azure-devices.net Tijee.azure-devices.net:443
does anyone know what might cause this or how to debug it?

thanks
Joe

**Comment by pierreca** [comment]
Hi @xiaoyongaz 
this error indicates that your raspberry pi could not resolved the DNS name of your IoT Hub to an IP address, it's likely a connectivity issue.

**Comment by pierreca** [comment]
@xiaoyongaz please let us know if you figured if this was a connectivity issue or if it's something else. we try to close issues as fast as possible. Thanks!

**Comment by pierreca** [comment]
@xiaoyongaz we're going to have to close this if we don't get more information from you :) what you see simply looks like a DNS error that is unrelated to our SDK.
