### ISSUE TITLE
Error in c/doc/SDK_cross_compile_example.md 

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdks#375]
Line 95 returns an error:
./build.sh –-toolchain-file toolchain-rpi.cmake –-skip-e2e-tests \
--skip-unittests -–no-amqp –-no-mqtt -cl -D__STDC_NO_ATOMICS__ \
-cl –-sysroot=$RPI_ROOT

Reported by @alinamstanciu 
"This command does not work. I've tried to format it to one line, run it by itself, nothing works. Always get an error when I execute this command saying the cmd is incomplete."

**Comment by srberard** [comment]
I hit this as well.  I believe there is an invalid character before the first parameter.  If you just cut-and-paste the line it will fail.  Try retyping the first parameter as "--toolchain-file"  (i.e. minus minus toolchain minus file).

**Comment by dominicbetts** [comment]
@tameraw should be OK to close now

**Comment by tameraw** [comment]
@dominicbetts - Thanks for updating.
