### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Akashdeep-Sarin** [Azure/azure-iot-sdks#377]
In the documentation for -- Setting up the development environment for SERVICE SDK
See the following URL:
**azure-iot-sdks/java/service/doc/devbox_setup.md**

![image](https://cloud.githubusercontent.com/assets/16319756/13520723/ce38d664-e208-11e5-8bb9-c132b3d75769.png)

Why does it redirect to Setting up DEVICE SDK...????

**Comment by dominicbetts** [comment]
@tameraw - submitted PR, should be OK to close.

**Comment by tameraw** [comment]
Thanks!
