### ISSUE TITLE
Code Errors During Complilation : STM32F401RE mbed

### ISSUE THREAD

**Issue by sinet666** [Azure/azure-iot-sdks#380]
THESE ARE THE ERRORS ENCOUNTERED:

mbed complier / stm32f401re

****************************************************************************************************************
****************************************************************************************************************

THESE ARE MY DETAILS:

static const char* deviceId = "tempsens";

static const char* deviceKey = "hiBZ+mPkT1anKCO8fOlt8A==";

static const char* hubName = "potentiometer";

static const char* hubSuffix = "azure-devices.net";

********************************************************************************************************************************************************************************************************************************

Error: Identifier "ETH_DMADescTypeDef" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 27, Col: 16
Error: Identifier "ETH_MAX_PACKET_SIZE" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 37, Col: 45
Error: Identifier "ETH_HandleTypeDef" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 45, Col: 2
Error: Identifier "ETH_HandleTypeDef" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 59, Col: 23
Error: Identifier "ETH" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 62, Col: 28
Error: Identifier "GPIO_AF11_ETH" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 85, Col: 38
Error: Identifier "ETH_IRQn" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 105, Col: 31
Error: Identifier "ETH_HandleTypeDef" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 113, Col: 25
Error: Identifier "ETH" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 115, Col: 28
Error: Identifier "ETH_IRQn" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 137, Col: 30
Error: Identifier "ETH_HandleTypeDef" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 147, Col: 30
Error: Identifier "ETH" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 181, Col: 22
Error: Identifier "ETH_AUTONEGOTIATION_ENABLE" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 182, Col: 34

Error: Identifier "ETH_SPEED_10M" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 183, Col: 24
Error: Identifier "ETH_RXINTERRUPT_MODE" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 197, Col: 25
Error: Identifier "ETH_CHECKSUM_BY_HARDWARE" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 198, Col: 31

Error: Identifier "ETH_MEDIA_INTERFACE_RMII" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 199, Col: 33
Error: Identifier "ETH_DMADescTypeDef" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 275, Col: 11
Error: Identifier "ETH_DMATXDESC_OWN" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 289, Col: 35
Error: Identifier "ETH_DMADescTypeDef" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 304, Col: 27
Error: Expected an expression in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 304, Col: 46
Error: Identifier "ETH_DMATXDESC_OWN" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 307, Col: 39
Error: Identifier "ETH_DMASR_TUS" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 334, Col: 34
Error: Identifier "ETH_DMADescTypeDef" is undefined in "EthernetInterface/lwip-eth/arch/TARGET_STM/stm32f4_emac.c", Line: 362, Col: 11

**Comment by anthonyvercolano** [comment]
Quick question as I investigate this further.  Have you gotten a tiny program like blinky (no azure iot code) to compile using the mbed_official Ethernet library?

**Comment by sinet666** [comment]
Hi,

I have placed on order both of ENC28j60 and Wiznet W550io but currently i dont have the hardware. I have found an example program to blink an led using ethernet on mbed developer page tested successfully on the STM32F401RE for both the ethernet modules. 

Therefore in the meanwhile i setup my azure account and finally when i ran the code these were the errors i got. 

Thank you for any help thats coming down the way. 

Regards,
K.Raghavendran

**Comment by anthonyvercolano** [comment]
Whatever changes (additional libraries or whatever) you made to make your blinky program COMPILE, you would need to apply similar changes to the sample program.

**Comment by sinet666** [comment]
Yes, the only addition would be the mbed.h header file. Still getting the same compile errors. Thank you.

**Comment by anthonyvercolano** [comment]
You probably have a project set up in your compiler build environment.  Could you publish it and then post the URL here.  What I'm looking for would be the project where you've built the blinky project and NOT gotten the compiler errors.  I'll take what you've got there and see what I can do with the sample.

**Comment by sinet666** [comment]
Hi,

Mr.Vercolano, are you talking about the blinky example running via an ethernet module ?? I have not got my ethernet modules yet, so i dont have the compiled code. 

If you are talking about the very basic blinking led without ethernet then i can provide you that.

Thank you.

**Comment by anthonyvercolano** [comment]
You can call me Tony.  (My middle initial is V.  The last name is Ercolano, so Tony is just fine)

What I'm trying to do is get past the compilation issues you're seeing.

For some reason, mbed.org does not seem to provide official compile support for the STM32F401RE using their release of the Ethernet library.  This isn't really something we can fix.  I had thought, that you had searched through the various forums and found a way to COMPILE a simple blinky program (without any azureiot at all). Not run, just compile.  So have you found a way to compile a blinky program that does use the mbed_official Ethernet library?

**Comment by sinet666** [comment]
Hi Tony,

Thank you for replying back. Below is the link for the support of ENC28j60 on an STM32F401RE board. I have compiled the code but havnt yet got the opportunity to test on hardware. Hope this helps.

Based on the **UIPEthernet LIbrary**

https://developer.mbed.org/users/hudakz/code/WebSwitch_ENC28J60/

**Comment by anthonyvercolano** [comment]
Unless there is support for a platform in the mbed_official EthernetInterface library, it is not a supported configuration for IoT Hub.
