### ISSUE TITLE
IoT Hub Sample Client for C/AMQP not working

### ISSUE THREAD

**Issue by bknabel** [Azure/azure-iot-sdks#386]
Hello,
The Sample Client for AMQP/C seems to be broken on Windows/Visual Studio. I've followed the pre-requisite and build process successfully. But when I run the application I see:

          IoT Hub SDK for C, version 1.0.1
          IoTHubClient_SetMessageCallback
          IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.

But the confirmation callback routine is never called and after 30 seconds or so I see:

          Error: Time:Tue Mar  8 16:45:29 2016 
          File:C:\Source\IoT\azure-iot-sdks\c\iothub_client\src\iothubtransportamqp.c
          Func:_IoTHubTransportAMQP_DoWork Line:1142 AMQP
          transport authentication timed out.
          -> [CLOSE]* {}

This is on a Windows desktop. I'm sure that the connection string is valid. I have run the C# and Java versions of the AMQP client sample and they work without a hitch. I can also run the C version of the HTTP client sample and it works fine. 

I've tried using the C client with both the NuGet libraries that are supplied by default and the directly built libraries after running the script in c/build_all. I get the same results with either set of libraries.

Any assistance you can provide would be greatly appreciated.

**Comment by anthonyvercolano** [comment]
Tell us a little more about your windows platform.  Is it running in a VM? (Hyper V?).  What time is it on the platform?

**Comment by bknabel** [comment]
I'm running the sample on a physical Windows 7 laptop (HP ZBook 15 if that matters). I bypass our corporate network firewall either by running at home or by using a local MiFi 4G adapter. The time on my windows machine is currently 3:18 (UTC -5:00)   I'm on the east coast.

I have tried running the same sample on an Azure VM (it fails the same way) and a coworker is having the exact same sample fail when running it on a VM on Amazon's AWS.

I'd be more concerned about the configuration/network/time if the Java and C# versions weren't working for  me as well. But given that those work and only the C version fails makes me think that there's an issue with the sample or there's something inherently different in the c code that I've failed to take into account.

Thanks for any insights you might have.

**Comment by anthonyvercolano** [comment]
I'm assuming that this is iothub_client_sample_amqp.  I note that you are using version 1.0.1.  Any chance you could try it with 1.0.2?  That got released yesterday.

**Comment by anthonyvercolano** [comment]
Let's try this.

Create a new device.  I suggest you call the device tony.  (By the way, what is the name of the device that is failing?)

Insure that this new device fails the same way.

THEN, Create a private github repo.  Invite me to access this private repo.  In the private repo, place the file iothub_client_sample_c with the connection string (for tony) in the file.  I will grab the file and try to track it down from our end.  This seems like a moderately secure (and isolated) way to share the info.  When I'm done, you can delete the device.

Thoughts?

**Comment by bknabel** [comment]
Thanks Tony for the suggestion. I've created the repository and added you as a collaborator. Please let me know if you have any problems with access.  (My previous device was called BradsDevice)

All of this is a sandbox for me - I'm not terribly concerned about security since everything will be wiped shortly. My ultimate goal is to get this working using AMQP over Websockets. So once I'm over this hurdle I'll attempt to get the Websockets sample working as well.

In the end I need to get this working through a corporate firewall - but that's a bit further down the road for me.

**Comment by anthonyvercolano** [comment]
https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/amqp-c-websockets-run-sample.md
Should provide you with some instructions about how to build/use websockets with the client.

Actually I didn't have problems.  It connected right up and got confirmations.  When you used this EXACT device connection string in your test environment it failed?

I also note that you have a GatewayHostName in your connection string.  While I'm thinking it won't hurt, it certainly shouldn't provide anything for you.

**Comment by tameraw** [comment]
@bknabel - Please reopen if still having issues.
