### ISSUE TITLE
HTTPS issue in simplesample_http

### ISSUE THREAD

**Issue by AmadeusW** [Azure/azure-iot-sdks#389]
I'm trying to run **simplesample_http** on MKR1000 but I can't send and receive messages from the IoT hub. I'm receiving error `HTTPS connection to <my iot hub>.azure-devices.net failed`

Error in the serial monitor:
```
Connected to wifi
Info: IoT Hub SDK for C, version 1.0.0-preview.7
IoTHubClient accepted the message for delivery
Info: Fetched NTP epoch time is: 1457688607
Error: Time:Fri Mar 11 09:30:27 2016 File:C:\Users\amade\Documents\Arduino\libraries\AzureIoT\src\httpapi.cpp Func:HTTPAPI_CreateConnection Line:69 HTTPS connection to hackhub.azure-devices.net failed
Error: Time:Fri Mar 11 09:30:27 2016 File:C:\Users\amade\Documents\Arduino\libraries\AzureIoT\src\sdk\httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Fri Mar 11 09:30:27 2016 File:C:\Users\amade\Documents\Arduino\libraries\AzureIoT\src\sdk\iothubtransporthttp.c Func:DoEvent Line:1206 unable to HTTPAPIEX_ExecuteRequest
```

I get the connection string [according to this guide](https://github.com/Azure/azure-iot-sdks/blob/56df7fd80f3895489afc2a24edbb6f7445eefbd8/doc/manage_iot_hub.md). I put it into `connectionString` in `simplesample_http.c`

![untitled](https://cloud.githubusercontent.com/assets/1673956/13698588/c61a6526-e729-11e5-993c-4d986336d44b.png)

Thanks!

**Comment by Janisku7** [comment]
hey have you added a cert to your wifi101? what is Wifi-shield in MKR1000?

**Comment by AmadeusW** [comment]
Thank you. The solution was to upload certs to `<my iot hub>.azure-devices.net` using [WiFi101-FirmwareUpdater tool](https://github.com/arduino-libraries/WiFi101-FirmwareUpdater)

I'm not sure about the wifi shield but I think it is related to or compatible with the one on Arudino Zero
