### ISSUE TITLE
Issue with AMQP samples on Windows

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdks#390]
Running these samples on Windows:
- https://github.com/Azure/azure-iot-sdks/tree/master/c/serializer/samples/remote_monitoring
- https://github.com/Azure/azure-iot-sdks/tree/master/c/serializer/samples/simplesample_amqp

Results in these errors (and no message is sent):

```
Error: Time:Fri Mar 11 12:02:29 2016 File:c:\repos\azure-iot-sdks\c\azure-c-shared-utility\c\adapters\socketio_win32.c Func:_socketio_open Line:229 Failure: socket create failure 10093.
Error: Time:Fri Mar 11 12:02:29 2016 File:c:\repos\azure-iot-sdks\c\iothub_client\src\iothubtransportamqp.c Func:_establishConnection Line:470 Failed to open the connection with CBS.
Error: Time:Fri Mar 11 12:02:29 2016 File:c:\repos\azure-iot-sdks\c\iothub_client\src\iothubtransportamqp.c Func:_IoTHubTransportAMQP_DoWork Line:1126 AMQP transport failed to establish connection with service.
IoTHubClient accepted the message for delivery
Sending sensor value Temperature = 50, Humidity = 50
```

HTTP samples seem to run OK.

**Comment by alinamstanciu** [comment]
This was a bug in the master branch, was fixed in developer branch, today the integration should fix it in master as well.

**Comment by taunusflieger** [comment]
Has this been fixed? I still (did a clone today) see the same error on Raspberry PI 2 und linux:

`Error: Time:Mon Mar 14 21:57:11 2016 File:/home/pi/src/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1126 AMQP transport failed to establish connection with service.
Error: Time:Mon Mar 14 21:57:11 2016 File:/home/pi/src/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:establishConnection Line:411 Failed to obtain a TLS I/O transport layer.`

**Comment by taunusflieger** [comment]
Looks like there are some lines missing in the function void simplesample_ampq_run(void)

Add the following code add the beginning of that function:
```

if (platform_init() != 0) {
        printf("Could not initialize platform.\n“);
        return -1;
    }
```
After adding that code AMQP works for me under Linux

**Comment by tameraw** [comment]
@taunusflieger - That's the correct fix as you indicated. The fix should now be available in both the develop and the master branches.
@dominicbetts - Closing issue as fixed. If you're still having problems, please reopen. Thanks.

**Comment by dominicbetts** [comment]
@alinamstanciu  Has the update been included in the NuGet packages?
