### ISSUE TITLE
Unable to communicate with IoT Hub

### ISSUE THREAD

**Issue by AmadeusW** [Azure/azure-iot-sdks#391]
I'm trying to run `simplesample_http` on Arduino MKR1000 using [this guide](https://github.com/Azure/azure-iot-sdks/blob/56df7fd80f3895489afc2a24edbb6f7445eefbd8/tools/DeviceExplorer/readme.md), but I can't get the device and *Device Explorer* to communicate. In #389 I had an issue with HTTPS which is resolved now, and the device reports no errors:

```
Connected to wifi
Info: IoT Hub SDK for C, version 1.0.0-preview.7
IoTHubClient accepted the message for delivery
Info: Fetched NTP epoch time is: 1457727786
```

In *Device Explorer* under *Monitor* I get
```
Receiving events...
Stopped Monitoring events. The operation did not complete within the allocated time 00:01:10 for object session27.
```

I sent a few messages from *Device Explorer* and Azure Portal acknowledges them, but the device doesn't output them to the serial monitor.
![img](https://i.gyazo.com/af23d3bdddbf435694438defe728f7ee.png)

How can I get the IoT Hub to work with *Device Explorer* and my device?

**Comment by Janisku7** [comment]
check if that simplesample-h have your deviceid in the code where in the sample is "firstdevice" if i remember that right but this could be your case

**Comment by tameraw** [comment]
@AmadeusW - Please follow the instructions in our guide guide at 
https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/arduinoide-arduino-wifi101-c.md
Let us know if you're still having issues and please include the output log from the device.

**Comment by AmadeusW** [comment]
Thank you both for feedback. Unfortunately something went wrong with my Arduino and I can't upload any sketches on it. I'll try a different board and I'll keep you posted.

**Comment by AmadeusW** [comment]
It did work! I needed to set `deviceId` in `simplesample_http`. Unfortunately, this sketch bricks my arduino such that I can't upload any more sketches to it unless I double-restart it (this prevents the sketch from booting). 

`iothub_client_sample_http` works without problems.

Thank you.
