### ISSUE TITLE
Intel Edison Documentation Error

### ISSUE THREAD

**Issue by jmwright** [Azure/azure-iot-sdks#395]
Under the "Downloading the Azure IoT SDK to your Intel Edison" section of the [Intel Edison documentation](https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/yocto-intel-edison-c.md#downloading-the-azure-iot-sdk-to-your-intel-edison), the following line:
```
git clone --recursive https://github.com/Azure/azure-iot-suite-sdks.git
```
Should be:
```
git clone --recursive https://github.com/Azure/azure-iot-sdks.git
```

**Comment by tameraw** [comment]
@jmwright - Thanks for reporting this. We fixed the document.
