### ISSUE TITLE
iothub_client_sample_amqp.c not working

### ISSUE THREAD

**Issue by taunusflieger** [Azure/azure-iot-sdks#399]
When running iothub_client_sample_amqp.c  on a RaspberryPI 2 (not tried any other environment) it fails with the error message shown below. Any suggestions?

`Starting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.0.2
IoTHubClient_SetMessageCallback...successful.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Press any key to exit the application. 
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {default_container_id,RaspDevice.azure-devices.net,4294967295,65535}
<- [OPEN]* {DeviceGateway_c20a71279dbe4f1f81cfceeb6f958cff,10.0.0.57,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
-> [ATTACH]* {cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,65535}
-> [ATTACH]* {cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,65535}
<- [ATTACH]* {cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,65535,NULL,NULL,NULL}
<- [FLOW]* {0,100,1,5000,0,0,100,0,NULL,false,NULL}
<- [ATTACH]* {cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65535,NULL,NULL,NULL}
-> [FLOW]* {NULL,4294967295,0,100,1,0,10000}
-> [TRANSFER]* {0,0,<00 00 00 00>,0,false}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
<- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}

-> [DETACH]* {0}
-> [DETACH]* {1}
-> [END]* {}
-> [CLOSE]* {}
Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[3] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[4] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY`

**Comment by taunusflieger** [comment]
Tameraw, any chance to look into this? To me it looks like the client is finished and had all of the messages still in the queue ... Please let me know if you need more information.

**Comment by taunusflieger** [comment]
I’ve double checked the issue on Windows 10 with the same device connection string as on the Raspberry PI2. On Windows the sample is working on the RaspPI it results in the error message shown above

**Comment by ewertons** [comment]
Hi,
this error message is shown in case the app layer (in this case the sample) calls IoTHubClient_Destroy before the IoT Hub client is done sending all the messages queued to be sent (done previous by calling IoTHubClient_SendEventAsync).

The sample has a couple lines that wait for a key to be pressed to trigger the termination (and thus call IoTHubClient_Destroy).
I see in your log that "Press any key to exit the application" was printed, so it reached that block, so would it be the case that you pressed a key before the sample had chance to send the messages?

We have a R-PI2 and will try the sample there again to verify as well.

**Comment by taunusflieger** [comment]
No I've not pressed a key - it simply runs through and resulted in that error.

**Comment by taunusflieger** [comment]
@ewertons any success with running it your Raspberry?

**Comment by ewertons** [comment]
@taunusflieger,  I was able to run the sample on raspberry Pi 2.
I used Putty to remote into it, and got the latest code from develop branch.
Note: I found a bug when building on the Pi2, for which I will check the fix in soon.
Other than that yes, the C SDK sample works as expected.

pi@raspberrypi ~/azure-iot-sdks $ ~/cmake/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp
Starting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.0.3
IoTHubClient_SetMessageCallback...successful.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Press any key to exit the application.
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {default_container_id,internalaziothub.azure-devices.net,4294967295,65535}
<- [OPEN]* {DeviceGateway_c3847035f3d2470b89a29c215e7357e8,192.0.0.350,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
-> [ATTACH]* {cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,65535}
-> [ATTACH]* {cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,65535}
<- [ATTACH]* {cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,65535,NULL,NULL,NULL}
<- [FLOW]* {0,100,1,5000,0,0,100,0,NULL,false,NULL}
<- [ATTACH]* {cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65535,NULL,NULL,NULL}
-> [FLOW]* {NULL,4294967295,0,100,1,0,10000}
-> [TRANSFER]* {0,0,<00 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
<- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}
-> [ATTACH]* {receiver-link,2,true,0,0,* {amqps://internalaziothub.azure-devices.net/devices/ewertons-device1/messages/devicebound},* {ingress-rx},NULL,NULL,NULL,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.3]}}
-> [ATTACH]* {sender-link,3,false,0,0,* {ingress},* {amqps://internalaziothub.azure-devices.net/devices/ewertons-device1/messages/events},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.3]}}
<- [ATTACH]* {receiver-link,2,false,0,0,* {amqps://internalaziothub.azure-devices.net/devices/ewertons-device1/messages/devicebound,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {ingress-rx,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.3]}}
-> [FLOW]* {NULL,4294967294,1,99,2,0,10000}
<- [ATTACH]* {sender-link,3,true,0,NULL,* {ingress,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://internalaziothub.azure-devices.net/devices/ewertons-device1/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.3]}}
<- [FLOW]* {1,100,2,4294967295,3,0,1000,0,NULL,false,NULL}
-> [TRANSFER]* {3,1,<00 00 00 00>,0,false,false}
-> [TRANSFER]* {3,2,<01 00 00 00>,0,false,false}
-> [TRANSFER]* {3,3,<02 00 00 00>,0,false,false}
-> [TRANSFER]* {3,4,<03 00 00 00>,0,false,false}
-> [TRANSFER]* {3,5,<04 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,1,NULL,true,* {},NULL}
Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,2,3,true,* {},NULL}
Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,4,5,true,* {},NULL}
Confirmation[3] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[4] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [TRANSFER]* {2,1,<A9 6F E9 A3 76 DA 7A 43 A1 BB F9 65 7C F5 74 CE>,0,NULL,false,NULL,NULL,NULL,NULL,false}
Received Message [0] with BINARY Data: <<<4/1/2016 2:26:19 PM - Hello taunusflieger>>> & Size=41
-> [DISPOSITION]* {true,1,1,true,* {}}

-> [DETACH]* {3}
-> [DETACH]* {2}
-> [DETACH]* {0}
-> [DETACH]* {1}
-> [END]* {}
-> [CLOSE]* {}
pi@raspberrypi ~/azure-iot-sdks $

**Comment by taunusflieger** [comment]
@ewertons Thanks for looking into it. I can confirm that it is working now on my system. I’ve not recompiled it, but just run the same code I’ve compiled a few days ago which was not working at that time - strange …

**Comment by ewertons** [comment]
No problem, I'm glad everything is working.
Please let us know if you have any other comments, suggestions or questions.
Thanks for using the Azure IoT Hub Client SDK.

**Comment by rhagan3** [comment]
Ran into a similar issues receiving the result 'confirmation = BECAUSE_DESTROY' in addition, the message was not getting to the hub.  
Added 'time.sleep(3)' just after 'iotHubClient.send_event_async(x,x,x)' .....and all = OK now.  Apparently, the routine was completing and closing the connection prior to the message being sent and receiving the callback confirm.

**Comment by ewertons** [comment]
Hi @rhagan3, the code you posted doesn't seem to be C.
Would you like to open a separate issue to track the problem? Please provide as many detail as possible.
