### ISSUE TITLE
Tracing Implementation - Mono Support

### ISSUE THREAD

**Issue by Injac** [Azure/azure-iot-sdks#40]
I was browsing the source today and discovered that there is no interface defined to hook into ExceptionTrace, which is making excessive use of System.Diagnostics and some native Interop-Calls. And it seems as well, that all Tracing related classes are declared as internal.

Are you planning to change this in the near future, to enable platform-specific tracing-mechanisms?

**Comment by CarlosAlayo** [comment]
Yes, we would like the .NET SDK to support Mono in the future. We will look into this issue. Thank you for the feedback.

**Comment by CarlosAlayo** [comment]
You can vote for features on our feedback forum: http://feedback.azure.com/forums/321918-azure-iot

**Comment by Injac** [comment]
Hi Carlos,
thank you for the feedback :)
