### ISSUE TITLE
Is not compatible with UAP,Version=v10.0 (win10-x64).

### ISSUE THREAD

**Issue by AdamMiltonBarker** [Azure/azure-iot-sdks#400]
Anyone know a way around this can't add any.

**Comment by tameraw** [comment]
@AdamMiltonBarker - Can you please point to which NuGet package where you attempting to install and what was your project configuration? Thanks.

**Comment by tameraw** [comment]
@AdamMiltonBarker - Please reopen if you're still having issues with this.
