### ISSUE TITLE
How to change receive_period_millis_amqps?

### ISSUE THREAD

**Issue by eissi** [Azure/azure-iot-sdks#404]
the parameter was changed into public. but, i don't know how to change the value in my code excepting direct modification of SDK.
and i saw the default value was changed to 101ms in the latest developer branch. will it be published as Master with the value?

**Comment by ewertons** [comment]
Hi,
you are talking about the Azure IoT Java Device SDK, correct?
I took a look on the code (in develop branch) and it's actually set to 10 milliseconds (public static long RECEIVE_PERIOD_MILLIS_AMQPS = 10l).
https://github.com/Azure/azure-iot-sdks/blob/master/java/device/iothub-java-client/src/main/java/com/microsoft/azure/iothub/DeviceClient.java:59
That change will be in master as soon as we finish releasing, which should be completed within the next 2 days.

As per changing the value, it can be done by calling setOption("SetMinimumPollingInterval", <value>) on the device client instance. Please see: https://github.com/Azure/azure-iot-sdks/blob/develop/java/device/iothub-java-client/src/main/java/com/microsoft/azure/iothub/DeviceClient.java:379

**Comment by ewertons** [comment]
Please re-open this issue in case you believe it has not been fully addressed or if you need any additional information or support. 

Thanks.

**Comment by eissi** [comment]
Hi, ewertons
I've already seen and tested the code before asking. setOption doesn't seem to be allowed for AMQP. I think there is no way to change the value without directly modifying SDK. Can you check for me?

**Comment by eissi** [comment]
Anyway, how can I re-open this? Do I have to create new issue?

**Comment by ewertons** [comment]
Could you share the code you are testing please?

**Comment by eissi** [comment]
Tried this one first without success. I see now that the default value was changed into 101. But, it was 50001 in the past release. So, you may try this with 50001 now.
DeviceClient client = new DeviceClient(connString, protocol);
client.RECEIVE_PERIOD_MILLIS_AMQPS = 100;

Second one is using setOption(“SetMinimumPollingInterval”, 100);
But, as the source code is implemented, it throws the exception like below.
Exception in thread "main" java.lang.IllegalArgumentException: AMQP does not have setOption
       at com.microsoft.azure.iothub.DeviceClient.setOption(DeviceClient.java:406)
       at samples.com.microsoft.azure.iothub.HandleMessages.main(HandleMessages.java:168)


감사합니다.

Best Regards,
JH Lee
이정훈 (julee@microsoft.com)<mailto:julee@microsoft.com>

**Comment by ewertons** [comment]
Hi,
I confirmed on the code, and actually the polling time is used only by the HTTP protocol.
Indeed this polling time is not used by either AMQP or MQTT.

Please use HTTP for protocol if you would like to try changing the polling time.

**Comment by eissi** [comment]
What I don’t understand is why the value should be fixed in SDK.
Is it the best recommended so that developers don’t need to change it?
Why is it changed from 50001 to 101 in the latest code?

We had a problem in the past as the value was 50001 and felt it was too long and we have to change SDK and manage our own build.
So, we wished the value could be changed outside SDK.

감사합니다.

Best Regards,
JH Lee
이정훈 (julee@microsoft.com)<mailto:julee@microsoft.com>

**Comment by ewertons** [comment]
So if you look at the code, you will see that RECEIVE_PERIOD_MILLIS* is used by an async task that behaves differently depending on the protocol.

For HTTPS, when the task go through a loop, it sends a request to the IoT Hub for new messages, receives them and bubbles them up to the upper layer (through the callback set on the client). That is done with the default frequency of RECEIVE_PERIOD_MILLIS_HTTPS, but it can be changed using setOption("SetMinimumPollingInterval").

For AMQPS, we use Proton-J at the lowest level, and it has its internal mechanism to query and queue messages from cloud to device. At our SDK level, we use RECEIVE_PERIOD_MILLIS* to throttle the frequency at which we get the messages out of Proton-J. 

The values changed recently were on RECEIVE_PERIOD_MILLIS_AMQPS and RECEIVE_PERIOD_MILLIS_MQTT, which are now **10 MILLISECONDS** (not 101). The change was an improvement after we did a fine tuning of the timeouts.
These values are fixed for the proper functionality of the SDK.

I hope this explains how the polling time works currently, and help you integrate the SDK with your solution.

Please let us know if you need any other information.

**Comment by eissi** [comment]
Got it. It was critical when the default at SDK was 5000. But, now it’s 10 milliseconds. Fine with us. We don’t have to change the value for now. Thanks.

감사합니다.

Best Regards,
JH Lee
이정훈 (julee@microsoft.com)<mailto:julee@microsoft.com>

**Comment by ewertons** [comment]
Sure, no problem.

Please let us know if you have any other comments, suggestions or questions.
Thanks for using the Azure IoT Hub Client SDK.
