### ISSUE TITLE
EventData Properties dictionary empty

### ISSUE THREAD

**Issue by pplavetzki** [Azure/azure-iot-sdks#414]
When sending a simple Message using NodeJs to an IoT Hub, the added message properties are empty.  When sending a message:

      var windSpeed = 10 + (Math.random() * 4); // range: [10, 14]
      var data = JSON.stringify({ deviceId: 'sample-node-device', windSpeed: windSpeed });
      var message = new Message(data);

      message.properties.add('messageType', 'interactive');

Data is received correctly in the EventProcessor, but the Properties are always empty.

**Comment by pierreca** [comment]
Hi, this is a known issue with the current SDK, the code to send custom properties is incomplete.. to say the least. It's in our backlog: https://github.com/Azure/azure-iot-sdks/issues/352

we do accept contributions, if you feel like taking a stab at it.

**Comment by tameraw** [comment]
This has been addressed for AMQP & HTTP protocols.
This will come later for MQTT.

**Comment by stewartadam** [comment]
I noticed this issue is closed, but being referred to in newer issues - Is support for MQTT being tracked elsewhere? I've opened https://github.com/Azure/azure-iot-sdk-node/issues/9 to address the MQTT feature gap it in the new Node SDK repo.
