### ISSUE TITLE
[Edison/C] Recompiling only modified files/part of SDK ?

### ISSUE THREAD

**Issue by shazz** [Azure/azure-iot-sdks#418]
Hi,

Compiling the SDK and examples on the Intel Edison/Galieo boards takes hours, is there a way to only recompile what has changed or for example only the samples ?
I don't know cmake and it looks that the default cmake behavior is to recompile everything.

Else is there a way to cross-compile the SDK for Edison ?

Thanks in advance

**Comment by zolvarga** [comment]
Hi shazz,

Usually to compile our SDKS takes 5-10 minutes. 
Also the cmake just generates the make file for the given compiler and the make file should build only the modified lib (and the the libs are dependent on).

For further investigation I would need more information:
- the OS are you using
- the version of the OS and compiler 
- what module you changed and recompile

Thanks,
Zoltan

**Comment by zolvarga** [comment]
Hi shazz,

Here are the instructions to cross compile our SDK for Edison:
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md

I am closing this issue, please open a new one if you hit issue with the cross compilation

Thanks,
Zoltan

**Comment by shazz** [comment]
Hi Zoltan,
Sorry for the delay, was at Build 2016 ;-)

Board : Intel Galieo Gen2 (fairly slower then Edison: (Intel Quark X1000 400 MHz/256 MB vs dual core ATOM x86 500 MHz/1GB)
OS: Yocto Linux
Version of the OS and compiler: gcc 4.2.2 i585-poky-linux-uclibc-gcc 
what module you changed and recompile: Linux C samples
