### ISSUE TITLE
Cannot connect with MQTT

### ISSUE THREAD

**Issue by AdamMiltonBarker** [Azure/azure-iot-sdks#421]
I am attempting to get MQTT working to connect to Azure IoT Hub on the MKR1000, I have successfully got connection working with HTTP requests but using the same credentials and Shared Access Signature, it is not possible to connect via MQTT. I am using PubSubClient to connect and no one seems to know the answer to this. Has anyone been successful in connecting to IoT hub using MQTT ?

When connecting it does not provide any error the serial monitor just hangs and freezes I have to force quit to close the serial monitor. As it possible to make a HTTP request both post and GET and I am certain it is not related to the SSL I am attempting to connect to an IoT hub on port 8883.

**Comment by ewertons** [comment]
Hi Adam,
yes @mikehole was able to connect to the Iot Hub using MQTT and pubsubclient (#393).
However, there is an issue that he is investigating on pubsubclient related to receiving messages from the Azure IoT hub.

**Comment by mikehole** [comment]
Hi Adam,
 
There are quite a few forks of the PubSubClient I have been using the following:
 
https://github.com/Imroy/pubsubclient
 
I did try the original client but found the one above to work better except it is supposed to be for the ESP8266. If you are using the original then you may need to up the buffer size for messages. MQTT_MAX_PACKET_SIZE 128
 
Given the size of the shard signature this packet size is a bit small.

**Comment by mikehole** [comment]
Shared signature sorry not shard

**Comment by AdamMiltonBarker** [comment]
Hii thanks guys changing the packet size has not worked will try the other library

**Comment by AdamMiltonBarker** [comment]
Thank you the packet size did solve it after trying again first time did not work but second attempt at loading worked. Thanks again

**Comment by mikehole** [comment]
Great stuff, by the way how did you get hold of a MKR1000?

**Comment by AdamMiltonBarker** [comment]
I was a phase one winner of the Microsoft/Arduino Maker Challenge.

**Comment by Quentinb** [comment]
I've been trying to connect to Azure IOT hub all day, no success. I've tried the SAS token etc and still nothing. Anybode have an example of a connection to azure please?

Example:
const char* mqtt_server = "myhub-iot.azure-devices.net";
if (client.connect("Test", "myhub-iot.azure-devices.net/Test", "SharedAccessSignature=SharedAccessSignature sr=myhub-iot.azure-devices.net%2fdevices%2fTest&sig=nnnn&se=nnnn"))

**Comment by Quentinb** [comment]
Found the solution here: http://www.radupascal.com/2016/04/03/esp8266-arduino-iot-hub
Azure is tricky with the SAS tokens, ports and TLS requirements. thanks for the Lib, great work

**Comment by AdamMiltonBarker** [comment]
@Quentinb  with the above I get 'WifiClientSecure' does not name a type I solved the issue of connecting to Azure from MKR1000 with the help above but now attempting to another broker which is accessible fine from Python Paho and Node JS. Any ideas.

**Comment by ewertons** [comment]
Hi @Quentinb , 
good job on fi ding the solution to the issue you reported, and thanks for sharing the details! This for sure will help other developers get their Arduino boards connected to Azure through MQTT.

If you have any other questions or comments, please let us know.
Thanks for using the Azure IoT Hub Client SDK.

**Comment by Quentinb** [comment]
@AdamMiltonBarker reading the other post, looks like you are sorted now?

**Comment by Quentinb** [comment]
Using Azure (West Europe) I do seem to have frequent disconnects. One or more every 10-20 seconds. I tested the same code and device using the same infrastructure on my side against http://mqtt-dashboard.com/ and had little to no disconnects.

**Comment by Dishay** [comment]
Hello has anyone been able to do the cloud to deivce communication actually i'm implementing a smart irrigation system for my final year project and using a WeMos Board i have been able to send the sensor data to azure (Via HTTPS).   I must not do this c2d comm. to be able to switch my water pump ON/OFF.

Can anyone help?

**Comment by FHFS** [comment]
You should be able to receive messages with the arduino azure iot sdk.
Are you using azure iot arduino repo with simplesamplehttp?
In the simplesamplehttp.c line 33, a model is declared with some data and actions, and below that you can see the actions defined as functions. You can easily add to that. Through Device Explorer you can send JSON messages like: `{"Name" : "SetAirResistance", "Parameters" : { "Position" : 5 }}`
