### ISSUE TITLE
Refresh Shared Access Signature 

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdks#424]
Are there any samples for how to manage renewal of sas tokens after it expires?

**Comment by zolvarga** [comment]
Hi,

Thank you for using our SDKs. Currently we have slightly different SAS token handling implementations by language.
Could you please provide more details about what language you are using and what renewal mechanism you wanted to use? 

Thanks,
Zoltan

**Comment by wmmihaa** [comment]
Sorry, I'm using node.js.

Sent from Outlook Mobile. Yes, it works with gmail.




On Tue, Mar 29, 2016 at 10:04 AM -0700, "Zoltan Varga" <notifications@github.com> wrote:





Hi,

Thank you for using our SDKs. Currently we have slightly different SAS token handling implementations by language.
Could you please provide more details about what language you are using and what renewal mechanism you wanted to use?

Thanks,
Zoltan

---

**Comment by pierreca** [comment]
There are no specific samples showing how to renew SAS tokens however, the client will do it automatically when using fromConnectionString() to create it, so you can take a look at the code of the Client itself. It happens in the `_renewSharedAccessSignature` private method:
- https://github.com/Azure/azure-iot-sdks/blob/master/node/device/core/lib/client.js#L84

This method creates a new token, then update the configuration parameters in the transport, and deals with reconnection if necessary by calling the `updateSharedAccessSignature` public method:
- https://github.com/Azure/azure-iot-sdks/blob/master/node/device/core/lib/client.js#L169

This method is the one you want to call directly when managing SAS token renewal yourself
Please let us know if this solves the issue :)

**Comment by wmmihaa** [comment]
Is there an equivalent method for the server part

**Comment by pierreca** [comment]
oh right, on the service sdk side, no we don't have that yet. it's in the backlog though but we haven't started working on it. 

We would happily review a pull request for this though if you feel like giving it a try.

**Comment by wmmihaa** [comment]
Ok thanks

**Comment by tameraw** [comment]
A backlog item is created to pass SAS token on the service client side. Should be provided in a future release.
