### ISSUE TITLE
Wait for messages by CorrelationId

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdks#425]
Right now if you need to use the request-reply pattern you need to implement something complex, the idea would be to have something similar to MessageSession of Service Bus but with Correlation Id, with that it would be easy to implement the following schema:

Send Command to Device -> Wait For Response on Correlation Id or timeout -> Receive Command Result

Another option would be to be able to add information to the Feedback message (from the Device side)

**Comment by tameraw** [comment]
Thanks for your feedback. We'll look into this feature request.

**Comment by tameraw** [comment]
@pizerg - Currently not planning to add this feature. Having said that, Correlation Id is supported, and could potentially add the logic in the application side to filter based on the expected Correlation Id.
