### ISSUE TITLE
Azure IoT Hub SDK for Windows CE 

### ISSUE THREAD

**Issue by ethanhunt4233** [Azure/azure-iot-sdks#428]
How can i use Azure IoT Hub SDK in my Windows CE applications.

**Comment by anhashia** [comment]
It is available for Windows Embedded Compact 2013  and is covered under https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md#windowsce. Example covers TORADEX_CE800 SDK. If you have different SDK, you replace the 2 environment variables with your SDK information before building the code as mentioned in the documentation.

Right now there are some build issues building **aziotsharedutil.lib **that is needed to build the sample **simplesample_http.sln**.  That is being investigated.

**Comment by anhashia** [comment]
Investigating the build error issue that is preventing building samples on WEC 2013

**Comment by ethanhunt4233** [comment]
How can i use Azure IoT in Win CE 6.0...

**Comment by anhashia** [comment]
Right now, Azure IoT SDK support is only for **WEC 2013** using WEC 2013 SDK (native code). There are some build issue around that and those are being looked at.

Currently, there is no Azure IoT SDK support for older version of Windows CE like Windows Embedded CE 6.0 or Windows Embedded Compact 7.0.

**Comment by ethanhunt4233** [comment]
Thanks for reply. Do u have any C# example for this...

**Comment by anhashia** [comment]
You would need a MQTT client library. Check following and see if it helps
https://github.com/ppatierno/m2mqtt
This is third party client library for MQTT protocol on GitHub.

**Comment by ethanhunt4233** [comment]
Thanks for your quick response. 
Yes. I am working on this library "https://github.com/eclipse/paho.mqtt.m2mqtt". I disabled firewall but still gettinng the below error from My PC.
{"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 13.76.217.46:1883"}

**Comment by anhashia** [comment]
Currently, .NET client side Azure IoT SDK side support is only for Windows and **Windows 10 IoT** core. This is covered under
https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/readme.md

**Comment by markrad** [comment]
@ethanhunt4233,

The Azure IoT Hub uses **secure** MQTT which uses well known port 8883. Failure to connect to port 1883 would be expected.

_Mark Radbourne MSFT_

**Comment by anhashia** [comment]
Build fixes to build **http sample** are in latest master branch. Go to azure-iot-sdks\c\build_all\windowsce and run **build.cmd.** This should build **iothub_client_sample_http.exe** sample under %USERPROFILE%\cmake_ce8\iothub_client\samples\iothub_client_sample_http\Debug
