### ISSUE TITLE
Java DeviceClient is not thread safe

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdks#429]
Method sendEventAsync from DeviceClient is not thread safe and produces some exceptions with the method inProgressListToMessage of the class HttpTransport when called repeatedly without waiting for the context to notify or when calling it from different threads at the same time.

**Comment by iluican** [comment]
Hello,

Could you please give us more information about this? It would be great if you could paste the exception text.

Thank you,
Ilie.

**Comment by pizerg** [comment]
Hi,

I think the issue is not related to the method sendEventAsync(...) being thread safe, I realized that I was calling client.open() all times before client.sendEventAsync(...) which shouldn't be a problem because the method just returns when the client is already open, the Exception raised is the following:

`java.lang.NullPointerException: null
com.microsoft.azure.iothub.transport.https.HttpsTransport.moveWaitingListToInProgressList(HttpsTransport.java:291)
com.microsoft.azure.iothub.transport.https.HttpsTransport.sendMessages(HttpsTransport.java:154)
com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:25)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)`

The snippet to reproduce the error is the example here: [https://azure.microsoft.com/en-us/documentation/articles/iot-hub-java-java-getstarted/](url) with a slight modification (also note that protocol used is HTTPS not AMQPS), might take some runs to provoke the exception as sometimes instead of raising it the hub just returns a "IoT Hub responded to message with status BAD_FORMAT":

```
private static class MessageSenderMS implements Runnable {
		public volatile boolean stopThread = false;

		public void run()  {
			try {
				final double avgWindSpeed = 10; // m/s
				final Random rand = new Random();
				final DeviceClient client;
				client = new DeviceClient(connString, protocol);
				client.open();

				while (!stopThread) {
					for(int i=0; i< 30; i++){
						new Thread(new Runnable() {

							@Override
							public void run() {
								double currentWindSpeed = avgWindSpeed + rand.nextDouble() * 4 - 2;
								TelemetryDataPoint telemetryDataPoint = new TelemetryDataPoint();
								telemetryDataPoint.deviceId = "myFirstDevice";
								telemetryDataPoint.windSpeed = currentWindSpeed;

								String msgStr = telemetryDataPoint.serialize();
								Message msg = new Message(msgStr);
								System.out.println(msgStr);

								Object lockobj = new Object();
								EventCallback callback = new EventCallback();
								try {
									client.open();
								} catch (IOException e1) {
									e1.printStackTrace();
								}
								client.sendEventAsync(msg, callback, lockobj);
								try{
									synchronized (lockobj) {
										lockobj.wait();
									}
									Thread.sleep(1000);
								} catch (Exception e){}
							}
						}).start();
					}
					Thread.sleep(1000);
				}
				client.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
```

**Comment by iluican** [comment]
Thank you for the additional details. I will investigate this.

**Comment by kittylyst** [comment]
I think that the snippet of code posted @pizerg may leak a connection. The client does not appear to be closed, and my experiments seem to indicate that this will lead a thread & a connection.

**Comment by tameraw** [comment]
@pizerg - A fix has been checked into the develop branch and will be released to master soon (ETA 9/23). If you face any blocking issues, please let us know. Thanks.
