### ISSUE TITLE
IoT Hub - Using the new Operations Monitoring feature

### ISSUE THREAD

**Issue by gustafsonk** [Azure/azure-iot-sdks#430]
I recently saw this and was hoping to try it out: https://azure.microsoft.com/en-us/documentation/articles/iot-hub-operations-monitoring/

I’m using the latest (2.1.3) of this library to connect to the event hub piece: https://www.nuget.org/packages/Microsoft.Azure.ServiceBus.EventProcessorHost

To start, I have code that’s able to communicate with a consumer group I make on the main event hub shown under the Messaging tab in the portal and that all works absolutely great.

Now when I try to use this Operations Monitoring tab, I check all the boxes that are available here. Then I change the event hub path in my code to the value of the Event Hub-compatible name here, and I create a new consumer group in this tab and change my code to use that one. I leave the azure storage connection string the same as well as the event hub connection string in my code since the value of the Event Hub-compatible endpoint setting is the same as the other tab.

When I try to run it, my event processor code never gets to the ‘OpenAsync’ phase, which leads me to believe I must have some of the connection information wrong. Here's what my settings look like roughly:
```
{
  "AzureStorageConnectionString": "DefaultEndpointsProtocol=https;AccountName=<omitted>;AccountKey=<omitted>",
  "EventHubConnectionString": "Endpoint=sb://<omitted>.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=<omitted>",
  "EventHubConsumerGroup": "monitorprocessor",
  "EventHubPath": "<omitted>-operationMonitoring"
}
```
Does this new feature work yet, or is there something I'm doing wrong here?

**Comment by nberdy** [comment]
What happens when you try using the IoT Hub connection string with the messages/operationsmonitoringevents endpoint?

**Comment by gustafsonk** [comment]
Figured out the problem. The 'event hub path' setting needs to be all lowercase for it to work, but I was using a capital M for Monitoring.

I would like to formally request a change to the Azure Portal to show the 'Event Hub-compatible name' box in all lowercase letters. What's the best way to communicate this out?

**Comment by tameraw** [comment]
@gustafsonk - You can start here:
https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade

**Comment by tameraw** [comment]
Closing as this is not related to the SDKs. Thanks.
