### ISSUE TITLE
PCLCrypto not included in NuGet package for UWP

### ISSUE THREAD

**Issue by arturl** [Azure/azure-iot-sdks#431]
__Repro:__
Write a UWP app that sends Azure.Devices.Client nuget package, as in samples\UWPSample. Compile and run.

__Observed behavior:__

    Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.ni.dll

    Additional information: Could not load file or assembly 'PCLCrypto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c' or one of its dependencies. The system cannot find the file specified.

The problem goes away if I manually install the PCLCrypto package.

I only tested UWP, I assume someone else tested Win32 and it works.

**Comment by tameraw** [comment]
Fixed and checked in develop
