### ISSUE TITLE
How To Cross Compile the Azure IoT Hub SDK For Intel Edison?

### ISSUE THREAD

**Issue by cnvery** [Azure/azure-iot-sdks#435]
Hi,

I would like to cross complie the Azure IoT Hub SDK in Intel Edison.

However, the tutorial in https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md only suitable for Raspberry Pi platform.

May I know the similar guide/procedure for Intel Edison?

Thank you.

**Comment by zolvarga** [comment]
Hi,

The cross compile example you mentioned suppose to work with Intel Edison too. What step did you get stuck with? Please provide more details.

Thanks,
Zoltan

**Comment by cnvery** [comment]
Hi Zoltan,

There are some errors after I typed _**rsync -rl --safe-links pi@&lt;*your Pi identifier*&gt;:/{lib,usr} . **_ , as per command below:
> cd ~/RPiTools/tools/arm-bcm2708/\
> gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf
> rsync -rl --safe-links pi@&lt;*your Pi identifier*&gt;:/{lib,usr} . 

For Intel Edison, I changed from _pi@your Pi identifier_ to _root@my Edison IP_.

The error shown as per picture in this [Image Link](http://postimg.org/image/d7kwitaxj/)

Is there any solution for this?

Thanks a lot.

**Comment by shazz** [comment]
The cross compiel example is for the RPI using RPI toolchain... to get it working with Edison I guess you need a Yocto toolchain.. Edison runs an Atom CPU not an arm.. .right ?

**Comment by cnvery** [comment]
Hi shazz,

Yup, Intel Edison runs Atom CPU instead of ARM CPU.

You can refer more here [Intel Edison Tech Spec](http://www.intel.com/buy/us/en/product/emergingtechnologies/intel-edison-compute-module-iot-463633#tech_specs)

Do you have details guidelines for cross compiling Intel Edison with Yocto toolchain?

**Comment by shazz** [comment]
At least I'm trying to setup the cross toolchain for the Intel Galileo (QUARK CPU) which should be similar in the idea, but for the moment I cannot get the CMAKE configuration file working. 
I used the toolchain shipped with the Arduino setup as explained in this tutorial: https://software.intel.com/en-us/articles/bringing-ssl-to-arduino-on-galileo-through-wolfssl

```
INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Linux)     # this one is important
SET(CMAKE_SYSTEM_VERSION 1)     # this one not so much

# this is the location of the amd64 toolchain targeting the Galileo
SET(CMAKE_C_COMPILER /home/shazz/GalileoTools/arduino-1.6.0+Intel/hardware/tools/i586/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux-uclibc/i586-poky-linux-uclibc-gcc)

# this is the file system root of the target
SET(CMAKE_FIND_ROOT_PATH $ENV{GALILEO_ROOT})

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_LDFLAGS_FLAGS -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed)
SET(CMAKE_CXX_FLAGS -O2 -pipe -g -feliminate-unused-debug-types -fpermissive)
SET(CMAKE_EXE_LINKER_FLAGS -L /home/shazz/GalileoTools/arduino-1.6.0+Intel/hardware/tools/i586/sysroots/i586-poky-linux-uclibc/lib)
```

```
./build.sh --toolchain-file toolchain-galileo.cmake --skip-e2e-tests --skip-unittests \
-cl -D__STDC_NO_ATOMICS__ -cl --sysroot=/home/shazz/GalileoTools/arduino-1.6.0+Intel/hardware/tools/i586/sysroots/i586-poky-linux-uclibc \
-cl -ldl -cl -m32 -cl -march=i586
```


but the linking fails:
```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /home/shazz/GalileoTools/arduino-1.6.0+Intel/hardware/tools/i586/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux-uclibc/i586-poky-linux-uclibc-gcc 
Build flags: 
Id flags: 

The output was:
1
/home/shazz/GalileoTools/arduino-1.6.0+Intel/hardware/tools/i586/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux-uclibc/../../libexec/i586-poky-linux-uclibc/gcc/i586-poky-linux-uclibc/4.7.2/ld: cannot find crt1.o: No such file or directory
```

as the sysroot is well set, I don't understand why ld doesn't find the libs in $sysroot/lib and $sysroot/usr/lib...

Any idea ?

**Comment by shazz** [comment]
@cnvery, did you succeed to setup the toolchain ?

**Comment by cnvery** [comment]
@shazz  Nope

Hope someone can post working tutorials for both Intel Edison and Intel Galileo

**Comment by shazz** [comment]
@cnvery : check this page: https://software.intel.com/en-us/iot/hardware/edison/downloads

at the bottom:
SDK - Cross Compile Tools
Download - Windows* 32-bit,Windows* 64-bit,OS X*,Linux* 32-bit,Linux* 64-bit

**Comment by ashokkhurana** [comment]
@cnvery, we recently did a cross compilation using the Intel Edison tool chain available at location mentioned by @shazz above: https://software.intel.com/en-us/iot/hardware/edison/downloads . Actually the  whole script to build Azure IoT C SDK using this toolchain is also available in GitHub at following location https://github.com/Azure/azure-iot-sdks/blob/develop/build/inteledison_c.sh . Script assumes that the toolchain is already setup on the box. So before running the script you would need to setup the toolchain. For setting the toolchain, in the same script their is a method name "setupIntelEdisonToolChain" which contains steps to setup the tool chain. Please run these steps manually to set up the toolchain. After running these steps you can run the script as it is or you can refer the steps in script to run it your way.

**Note: The script is currently available in develop branch only.**

Please let me know if you face any issue and I would be happy to assist you further.

**Comment by cnvery** [comment]
@ashokkhurana 

I followed your guidelines on "setupIntelEdisonToolChain"

But it appear errors on this command line as per image below:
> EnvFileName=$(DirName)/$(ls $DirName | grep environment)

The error is shown in [this image link](http://postimg.org/image/myxiytm5t/)

**Comment by ashokkhurana** [comment]
@cnvery , This error is coming because the DIRNAME variable was set in script and this method was initially written to be called from the script. But looks like the toolkit is set successfully under /opt/poky-edison/1.7.2. Could you please ignore the error and try the cross compilation using following steps:

1. Set environment variable for Intel Edison SDK path using following command
             export INTELEDISON_ROOT= /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux
2.Create a file name toolchain.cmake with **following ** content under /c/build_all/linux/
**INCLUDE(CMakeForceCompiler) 
SET(CMAKE_SYSTEM_NAME Linux) # this one is important 
SET(CMAKE_SYSTEM_VERSION 1) # this one not so much
# this is the location of the amd64 toolchain targeting the Intel Edison
SET(CMAKE_C_COMPILER ${INTELEDISON_ROOT}/../x86_64-pokysdk-linux/usr/libexec/i586-poky-linux/gcc/i586-poky-linux/4.9.1/gcc)
# this is the file system root of the target
SET(CMAKE_FIND_ROOT_PATH ${INTELEDISON_ROOT})
# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY) 
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY) **
2. Go to /c/build_all/linux  directory.
3. Run command ./build.sh --toolchain-file toolchain.cmake --skip-e2e-tests --skip-unittests --no-mqtt -cl --sysroot=$INTELEDISON_ROOT 

Please let me know if you face any issue.

**Comment by cnvery** [comment]
@ashokkhurana 

I faced problem on the first step, which cannot set environment variable for Intel Edison SDK

> export INTELEDISON_ROOT= /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux

The error is shown [this image link](http://postimg.org/image/p4dg6084z/)

**Comment by ashokkhurana** [comment]
@cnvery , there is a space in the export command after =. Could you please remove the space and try again. Pasting updated command below without space
export INTELEDISON_ROOT=/opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux

You can also use the value of this variable directly in toolchain.cmake file if you still face issue setting up the environment variable by setting CMAKE_FIND_ROOT_PATH and CMAKE_FIND_ROOT_PATH values in toolchain.cmake file like below:

# this is the location of the amd64 toolchain targeting the Intel Edison
SET(CMAKE_C_COMPILER /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux/../x86_64-pokysdk-linux/usr/libexec/i586-poky-linux/gcc/i586-poky-linux/4.9.1/gcc)

# this is the file system root of the target
SET(CMAKE_FIND_ROOT_PATH /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux)

Please let me know how it goes.

**Comment by cnvery** [comment]
@ashokkhurana 

I followed your instructions, however it shown error as per [this image link](http://postimg.org/image/579d2vdf1/)

My toolchain.cmake file is as per [this image link](http://postimg.org/image/vplec21yl/)

**Comment by ashokkhurana** [comment]
@cnvery , the image links you shared are not lading the image files. Could you please share again or paste the image or text inline?

**Comment by shazz** [comment]
It worked for me, I was able to compile the SDK for edison without errors.

Unfortunately, I cannot do the same for the Intel Galileo Gen2, it seems the cross-compilation toolchain (extracted from the Linux Arduino toolchain) is not well configured as it does not include the sysroots/lib, sysroots/usr/lib and so on in the linker library paths.

Do you have plan to support the Intel Galileo IoT board ?

**Comment by shazz** [comment]
@cnvery: are you running on a 64bits or 32bits ubuntu ? I got a similar error when the gcc symlink was pointoing to a 32bits executable.

**Comment by cnvery** [comment]
@ashokkhurana The image link is function well without any issue

@shazz I am running on 32 bits Ubuntu 15.10 version

**Comment by shazz** [comment]
@cnvery : ok so I guess this is why
if you do ls -al /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux/../x86_64-pokysdk-linux/usr/libexec/i586-poky-linux/gcc/i586-poky-linux/4.9.1/

you will see that gcc is pointing to i586-poky-linux/i586-poky-linux-gcc
and if you do "file" on this link it will tell you this is a 64bit ELF.

Can you try ?

**Comment by cnvery** [comment]
@shazz 

It shows:
> ls: cannot access /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux/../x86_64-pokysdk-linux/usr/libexec/i586-poky-linux/gcc/i586-poky-linux/4.9.1/: No such file or directory

**Comment by cnvery** [comment]
@ashokkhurana 
@shazz 

I tried again to create toolchain.cmake on 64-bit Ubuntu 15.10 version

I have successfully build the _toolchain.cmake_ using 

> INCLUDE(CMakeForceCompiler) 
> 
> SET(CMAKE_SYSTEM_NAME Linux) # this one is important 
> SET(CMAKE_SYSTEM_VERSION 1) # this one not so much 
> 
> #this is the location of the amd64 toolchain targeting the Intel Edison 
> SET(CMAKE_C_COMPILER /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux//../x86_64-pokysdk-linux/usr/libexec/i586-poky-linux/gcc/i586-poky-linux/4.9.1/gcc) 
> 
> #this is the file system root of the target 
> SET(CMAKE_FIND_ROOT_PATH /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux/) 
> 
> #search for programs in the build host directories 
> SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER) 
> 
> #for libraries and headers in the target directories 
> SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY) 
> SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

The following export command will show incomplete path after run _./build.sh_ (Hence, this method not works for me)
> export INTELEDISON_ROOT= /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux

I have successfully executed both _build.sh_ and _inteledison_c.sh_.

So, what is next step for moving these files into Intel Edison board?

**Comment by ashokkhurana** [comment]
@cnvery , with the successful build you should have got the executable **iothub_client_sample_amqp **built under ~/cmake/iothub_client/samples/iothub_client_sample_amqp/ . You can copy this anywhere on your Edison board and run the executable.

**Note: Please make sure that you did changed the device connection string in file "/c/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c before building. You can also refer the document here https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/yocto-intel-edison-c.md on how to build and run on intel Edison board. The only difference is that we are doing a cross compilation build and document is about compiling on the board itself.**

**Comment by shazz** [comment]
@cnvery good work :) 

yep now just copy the ELF to your edison thru scp and run it !

**Comment by cnvery** [comment]
@ashokkhurana @shazz 

The compiled ./iothub_client_sample_amqp runs successfully on Intel Edison.

However, the details is slightly different compared to final result in [Run a simple C sample on Intel Edison](https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/yocto-intel-edison-c.md).

It shown **IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY** instead of **IOTHUB_CLIENT_CONFIRMATION_OK**.

Is there any error from this or it is normal?

Response in Intel Edison:
> root@edison:~# ./iothub_client_sample_amqp
> Starting the IoTHub client sample AMQP...
> Info: IoT Hub SDK for C, version 1.0.5
> IoTHubClient_SetMessageCallback...successful.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> Press any key to exit the application.
> 
> -> [CLOSE]* {}
> Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT                               _CONFIRMATION_BECAUSE_DESTROY
> Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT                               _CONFIRMATION_BECAUSE_DESTROY
> Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT                               _CONFIRMATION_BECAUSE_DESTROY
> Confirmation[3] received for message tracking id = 3 with result = IOTHUB_CLIENT                               _CONFIRMATION_BECAUSE_DESTROY
> Confirmation[4] received for message tracking id = 4 with result = IOTHUB_CLIENT                               _CONFIRMATION_BECAUSE_DESTROY

One more question, is it able to compile Azure IoT C code in Eclipse IDE and then direct compiling? Instead of keep using Ubuntu OS cross compiling method and then manually transfer file via Filezilla.

Thank you.

**Comment by markrad** [comment]
Hi @cnvery,

No your output is not what I would expect. I would suspect that it is not successfully connecting to your IoT hub. A number of different problems can potentially cause this issue. 

1. You did not replace the connection string in the sample to reflect the connection string of one of your devices.
2. Your firewall is not allowing the connection to Azure You will need to allow 443 for HTTPS or 5671 for AMQP.
3. Your device is not successfully validating the server's certificate. You may be able to resolve that by explicitly passing the certificates defined in certs.c to the SDK via the TrustedCerts option. See the code that is 
ifdefed for MBED in the sample. You could try using that.

_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

Thanks for your reply.

1) My connection string is as per below:

> static const char* connectionString = "HostName=trafficIoT.azure-devices.net;CredentialScope=Device;DeviceId=WxVdxNDST9AVqtr9W1g48CR9f3MZXWITs+hZjtIr+L0=;SharedAccessKey=*Undiclosed*"; 

2) Is there a step by step tutorial for allowing Intel Edison 443 for HTTPS or 5671 for AMQP?

Thank you.

**Comment by markrad** [comment]
Hi @cnvery,

For 3) yes simply remove the #ifdef/endif from the code that looks like this:
```
#ifdef MBED_BUILD_TIMESTAMP
    // For mbed add the certificate information
    if (IoTHubClient_SetOption(iotHubClientHandle, "TrustedCerts", certificates) != IOTHUB_CLIENT_OK)
    {
        (void)printf("failure to set option \"TrustedCerts\"\r\n");
    }
#endif // MBED_BUILD_TIMESTAMP
```
You will also need to add the certificates array to your code that is in c/certs/certs.c since it will not be automatically included at this time.

_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad ,

I have tried the code and it succeed!

connectionString I have used: (It must be DeviceId and SharedAccessKey of the device such as Intel Edison)
> static const char* connectionString = "HostName=trafficIoT.azure-devices.net;CredentialScope=Device;DeviceId=Edison01;SharedAccessKey=WxVdxNDST9AVqtr9W1g48******";

The output:
> root@edison:~# ./iothub_client_sample_amqp
> Starting the IoTHub client sample AMQP...
> Info: IoT Hub SDK for C, version 1.0.5
> IoTHubClient_SetMessageCallback...successful.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
> Press any key to exit the application.
> -> Header (AMQP 0.1.0.0)
> <- Header (AMQP 0.1.0.0)
> -> [OPEN]* {default_container_id,trafficIoT.azure-devices.net,4294967295,65535}
> <- [OPEN]* {DeviceGateway_ed7b4bf7dfb44a9bb1a1c70394f5669f,10.0.0.30,65536,8191,                                                                                        240000,NULL,NULL,NULL,NULL,NULL}
> -> [BEGIN]* {NULL,0,4294967295,100,4294967295}
> <- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
> -> [ATTACH]* {cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,65535}
> -> [ATTACH]* {cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,65535}
> <- [ATTACH]* {cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N                                                                                        ULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,65535,NULL,                                                                                        NULL,NULL}
> <- [FLOW]* {0,100,1,5000,0,0,100,0,NULL,false,NULL}
> <- [ATTACH]* {cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NUL                                                                                        L,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65535,NULL,                                                                                        NULL,NULL}
> -> [FLOW]* {NULL,4294967295,0,100,1,0,10000}
> -> [TRANSFER]* {0,0,<00 00 00 00>,0,false,false}
> <- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
> <- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> -> [DISPOSITION]* {true,0,0,true,* {}}
> -> [ATTACH]* {receiver-link,2,true,0,0,* {amqps://trafficIoT.azure-devices.net/d                                                                                        evices/Edison01/messages/devicebound},* {ingress-rx},NULL,NULL,NULL,65536,NULL,N                                                                                        ULL,{[com.microsoft:client-version:iothubclient/1.0.5]}}
> Info: Event sender state changed [0->1]
> -> [ATTACH]* {sender-link,3,false,0,0,* {ingress},* {amqps://trafficIoT.azure-de                                                                                        vices.net/devices/Edison01/messages/events},NULL,NULL,0,18446744073709551615,NUL                                                                                        L,NULL,{[com.microsoft:client-version:iothubclient/1.0.5]}}
> <- [ATTACH]* {receiver-link,2,false,0,0,* {amqps://trafficIoT.azure-devices.net/                                                                                        devices/Edison01/messages/devicebound,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NU                                                                                        LL,NULL},* {ingress-rx,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65536,NULL,NUL                                                                                        L,{[com.microsoft:client-version:iothubclient/1.0.5]}}
> -> [FLOW]* {NULL,4294967294,1,99,2,0,10000}
> <- [ATTACH]* {sender-link,3,true,0,NULL,* {ingress,NULL,NULL,NULL,NULL,NULL,NULL                                                                                        ,NULL,NULL,NULL,NULL},* {amqps://trafficIoT.azure-devices.net/devices/Edison01/m                                                                                        essages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{                                                                                        [com.microsoft:client-version:iothubclient/1.0.5]}}
> Info: Event sender state changed [1->2]
> <- [FLOW]* {1,100,2,4294967292,3,0,1000,0,NULL,false,NULL}
> -> [TRANSFER]* {3,1,<00 00 00 00>,0,false,false}
> -> [TRANSFER]* {3,2,<01 00 00 00>,0,false,false}
> -> [TRANSFER]* {3,3,<02 00 00 00>,0,false,false}
> -> [TRANSFER]* {3,4,<03 00 00 00>,0,false,false}
> -> [TRANSFER]* {3,5,<04 00 00 00>,0,false,false}
> <- [DISPOSITION]* {true,1,2,true,* {},NULL}
> Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT                                                                                        _CONFIRMATION_OK
> Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT                                                                                        _CONFIRMATION_OK
> <- [DISPOSITION]* {true,3,NULL,true,* {},NULL}
> Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT                                                                                        _CONFIRMATION_OK
> <- [DISPOSITION]* {true,5,NULL,true,* {},NULL}
> Confirmation[3] received for message tracking id = 4 with result = IOTHUB_CLIENT                                                                                        _CONFIRMATION_OK
> <- [DISPOSITION]* {true,4,NULL,true,* {},NULL}
> Confirmation[4] received for message tracking id = 3 with result = IOTHUB_CLIENT                                                                                        _CONFIRMATION_OK
> 
> Info: Event sender state changed [2->3]
> -> [DETACH]* {3}
> Info: Event sender state changed [3->0]
> Info: Event sender state changed [0->0]
> -> [DETACH]* {2}
> -> [DETACH]* {0}
> -> [DETACH]* {1}
> -> [END]* {}
> -> [CLOSE]* {}

May I know is it possible to compile Azure IoT C code in Eclipse IDE and then direct compiling? Instead of keep using Ubuntu OS cross compiling method and then manually transfer file via Filezilla.

**Comment by markrad** [comment]
Hi @cnvery,

I'm not quite sure I understand your final question. I am not an Eclipse user myself. Are you asking if you can compile the code on the device itself?

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
I have closed this issue due to a lack of response. If you are still facing problems with this feel free to reopen it.

_Mark Radbourne MSFT_
