### ISSUE TITLE
can you support typings for node package

### ISSUE THREAD

**Issue by xiaoyongaz** [Azure/azure-iot-sdks#437]
I got below error trying to install typings
typings ERR! message Unable to find "azure-iothub" for "dt" in the registry. Did you want to install ambient typings with the ambient flag? If you can contribute these typings, please help us: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/dt/azure-iothub/versions/latest responded with 404, expected it to equal 200

**Comment by pierreca** [comment]
@xiaoyongaz  Thank you for your feedback, we have been thinking about it but it's low priority compared to other tasks we have in our backlog. We do accept pull-requests if you want to take a stab at it though.

**Comment by pierreca** [comment]
typings have now been added directly into both device and service SDKs packages. HTH!
