### ISSUE TITLE
IsSharedAccessSignature throws exception instead of returning false

### ISSUE THREAD

**Issue by robichaud** [Azure/azure-iot-sdks#438]
Microsoft.Azure.Devices.Common.Security.SharedAccessSignature.IsSharedAccessSignature throws an exception if it's not a SharedAccessSignature instead of returning false.

ExtractFieldValues(string sharedAccessSignature) throws the exception here:
` if (!string.Equals(lines[0].Trim(), SharedAccessSignatureConstants.SharedAccessSignature, StringComparison.Ordinal) || lines.Length != 2)
            {
                throw new FormatException("Malformed signature");
            }`

**Comment by tameraw** [comment]
@robichaud - Thanks for your feedback. We'll look into this.
Also, contributions are always welcomed.

**Comment by anhashia** [comment]
Looking into the issue

**Comment by anhashia** [comment]
Hi @robichaud 
Return type of `ExtractFieldValues(string sharedAccessSignature)` is `IDictionary<string, string>` and not BOOL so you would throw an exception so that you can catch it in **try/catch** block for any argument type error. Also, Send and Receive `DeviceClient `methods are Async tasks which would use signature validation method. So you would catch error on try/catch block on these async tasks. Look at `azure-iot-sdks\csharp\device\samples\DeviceClientHttpSample\Program.cs `sample for reference.

**Comment by robichaud** [comment]
Hi @anhashia
IsSharedAccessSignature is a bool function. If it is a SharedAccessSignature, it should return true. If it is not, it should return false. It shouldn't matter why it is not a SharedAccessSignature. So, yes, you should catch the exception from ExtractFieldValues IN the IsSharedAccessSignature method and return false. Otherwise, the method is misleading and not serving it's purpose.

I don't understand what Send and Receive methods have to do with this?

**Comment by anhashia** [comment]
Hi @robichaud 
Yeah, `IsSharedAccessSignature` is a BOOL function. It in turn uses `ExtractFieldValues` which has return type as `IDictionary<string, string>` (collection of 4 key-value pairs) and **not** BOOL. It is this function which throws exception on error and terminates the `IsSharedAccessSignature` call. Its return type is not BOOL. Now if you don't want to throw the exception but use IDictionary<string, string> to determine that signature is not correct and return some value to determine that is an invalid signature and not terminate the call then that is a design decision. If you have something to propose on those lines free to propose design change on GitHub. Again these are all **internal** calls. In the end you will have to still use try/catch to catch an exception (error)

Publically available methods for `DeviceClient` class are documented at 
https://msdn.microsoft.com/en-us/library/microsoft.azure.devices.client.deviceclient_methods.aspx

**Comment by robichaud** [comment]
Hi @anhashia 

`SharedAccessSignature.Parse` and `SharedAccessSignature.IsSharedAccessSignature` are static public, not internal. It makes sense for `ExtractFieldValues` to throw an exception if the signature is malformed.  Used in the Parse method it makes sense as it should throw an exception a la ["Try-Parse Pattern."](https://msdn.microsoft.com/en-us/library/ms229009(v=vs.110).aspx)

Where is doesn't make sense is in the IsSharedAccessSignature and I wouldn't really call it a design change. The method name itself indicates the result should be true or false. It also currently returns false when missing integral signature pieces:

```if (string.IsNullOrWhiteSpace(rawSignature))
 {
     return false;
 }```

and

```
bool isSharedAccessSignature = parsedFields.TryGetValue(SharedAccessSignatureConstants.SignatureFieldName, out signature);

return isSharedAccessSignature;
```

So when a user passes in a string into the method we can easily determine if it is indeed a SAS, without having to wrap the method call in a try/catch.

``if (SharedAccessSignature.IsSharedAccessSignature("xyz")
    {
         DoSomething();
    }
``

**Comment by anhashia** [comment]
Hi @robichaud 
We are evaluating this and looking at the code changes required to coorect this. Thanks for the feedback !

**Comment by robichaud** [comment]
@anhashia Thanks. When I first created the issue, I didn't have time to make the change and put in the pull request. It fell off my radar.

**Comment by anhashia** [comment]
Change submitted to develop branch from **IsSharedAccessSignature_438** branch.

**Comment by anhashia** [comment]
Change in develop branch. Closing the issue.
