### ISSUE TITLE
difficulty connecting to RabbitMQ

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-iot-sdks#439]
I'm using the uamqp library on the esp8266 but can't connect to a RabbitMQ server that has AMQP enabled? is there any working example of how to do this?

**Comment by ewertons** [comment]
Hi @grahamehorner , uAMQP's main target is the Azure IoT Hub, so it hasn't been tested against RabbitMQ.

In any case, do you get any error messages that could point out to the cause of the failure?

**Comment by ewertons** [comment]
We most certainly would like to understand why uAMQP is failing to connect to RabbitMQ, however the main focus for this library is to target Microsoft Azure IoT Hub, and given the extensive list of PBIs we have currently aligned for our suite we will not be able to investigate this issue at this moment. 
We apologize for that. 
If you have any progress on getting it to work, feel free to reach us if you would like any changes to be pulled into our repository.

Please let us know if you have any other comments, suggestions or questions.
Thanks for using the Azure IoT Hub Client SDK.
