### ISSUE TITLE
We do not tell the developer where to find / open the solution to setup proton libraries

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#44]
Getting Qpid Proton via NuGet
1.In Visual Studio 2015 right click on the iothub_client solution and select "Manage NuGet Package for Solutions".

The above does not tell the user where to find the solution file.  Step 0 should be 'Open the solution xxx found at the path yyy.'

**Comment by CarlosAlayo** [comment]
Thank you for the feedback. You are correct this information is missing from the docs. We will add the path information to the docs shortly. Thank you.
