### ISSUE TITLE
HTTPS Connection Issue 

### ISSUE THREAD

**Issue by ScottLiuGitHub** [Azure/azure-iot-sdks#440]
Hello, 

I am using Arduino Zero + Wifi 101 shield. 

I have followed the instruction list at 
https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/arduinoide-arduino-wifi101-c.md

I was able to update firmware and certificate using the instruction. However, when I ran the simplesample_http program, I got the following https connection error: 
--------------------------------------------------------------------------------------------------
Attempting to connect to SSID: <replaced>
Connected to wifi
Info: IoT Hub SDK for C, version 1.0.0-preview.7
IoTHubClient accepted the message for delivery
Error: Time:Sat Apr  2 15:09:38 2016 File:C:\Users\liyangz\Documents\Arduino\libraries\AzureIoT\src\httpapi.cpp Func:HTTPAPI_Init Line:27 Fetching NTP epoch time failed!
Info: Fetched NTP epoch time is: 1459609915

...\Arduino\libraries\AzureIoT\src\httpapi.cpp Func:HTTPAPI_CreateConnection Line:69 HTTPS connection to <site> failed
...\Arduino\libraries\AzureIoT\src\sdk\httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
...\Arduino\libraries\AzureIoT\src\sdk\iothubtransporthttp.c Func:DoEvent Line:1206 unable to HTTPAPIEX_ExecuteRequest

Anyone can help how to troubleshoot this? Thanks

**Comment by ewertons** [comment]
Hi @ScottLiuGitHub ,
I'll rerun the sample on our Arduino Zero to check if it works.

In the meantime, could you please try running the same sample again using the [latest release](https://github.com/Azure/azure-iot-sdks/tree/2016-03-28) I see you used 1.0.0-preview.7, which is a little old.

**Comment by ewertons** [comment]
Hi @ScottLiuGitHub, did you have chance to run the sample using the code from the latest release?

**Comment by ewertons** [comment]
I will close the issue since it hasn't been updated for a few days.
Please feel free to reopen it if you have chance to try the step above, and it still doesn't work.

Please let us know if you have any other comments, suggestions or questions.
Thanks for using the Azure IoT Hub Client SDK.
