### ISSUE TITLE
3 unit-tests fail on Linux with master branch (068aa9e65cb971db0d0982c399263e8d06e7b009)

### ISSUE THREAD

**Issue by zfields** [Azure/azure-iot-sdks#442]
**=== TOOLCHAINS ===**
GCC: gcc (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3
CMAKE: cmake version 3.2.2

**=== COMMANDS ===**
```
git clone --recursive https://zfields@github.com/azure/azure-iot-sdks.git
azure-iot-sdks/c/build_all/linux/setup.sh
azure-iot-sdks/c/build_all/linux/build.sh
```

**=== FAILED TESTS ===**
51/75 Test #52: iothubclient_http_e2etests .............***Failed    0.05 sec
 === Executing test suite iothubclient_http_e2etests ===
  Assert failed: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.
Error: Time:Sat Apr  2 21:10:45 2016 File:/home/zachary/Documents/Development/GitHub/azure-iot-sdks/c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init Line:436 Failure retrieving Connection Strings values.

54/75 Test #54: iothubclient_mqtt_e2etests .............***Failed    0.01 sec
 === Executing test suite iothubclient_mqtt_e2etests ===
  Assert failed: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.
Error: Time:Sat Apr  2 21:10:45 2016 File:/home/zachary/Documents/Development/GitHub/azure-iot-sdks/c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init Line:436 Failure retrieving Connection Strings values.

56/75 Test #56: iothubclient_amqp_e2etests .............***Failed    0.01 sec
 === Executing test suite iothubclient_amqp_e2etests ===
  Assert failed: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.
Error: Time:Sat Apr  2 21:10:45 2016 File:/home/zachary/Documents/Development/GitHub/azure-iot-sdks/c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init Line:436 Failure retrieving Connection Strings values.

**Comment by tameraw** [comment]
@zfields - Thanks for reporting the issue. You could skip running the E2E tests by running the command "build.sh --skip-e2e-tests". If you decide you want to run the E2E test, you'll need to set up  environment variables in the file:
https://github.com/Azure/azure-iot-sdks/blob/master/tools/iot_hub_e2e_tests_params/iot_device_params.txt

**Comment by zfields** [comment]
Sounds completely resonable! Can you throw that in the error message for the E2E tests, the documentation, or make a switch to enable them instead of them being enabled by default? It is difficult for a person without inside knowledge to understand what is happening.

**Comment by tameraw** [comment]
We do plan to change the default in a future release. However, we would happily accept contributions if you decide to submit a pull request for this. Thanks.

**Comment by tameraw** [comment]
@zfields - This should now be fixed with our latest release. Please try it out and let us know if you still encounter any issues. Thanks.
