### ISSUE TITLE
simplesample_http HTTPAPIEX_ExecuteRequest issue

### ISSUE THREAD

**Issue by lamqhoang** [Azure/azure-iot-sdks#444]
The example was working fine on my device for a few weeks, but today I have this issue:

`(11:37:48.930) Info: IoT Hub SDK for C, version 1.0.1
(11:37:49.030) IoTHubClient accepted the message for delivery
(11:37:49.050) Error: Time:Mon Apr  4 19:00:02 2016 File:../../adapters/httpapi_tirtos.c Func:HTTPAPI_ExecuteRequest Line:132 HTTPCli_sendRequest failed, ret=-107
(11:37:50.900) Error: Time:Mon Apr  4 19:00:02 2016 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
(11:37:50.900) Error: Time:Mon Apr  4 19:00:02 2016 File:../../src/iothubtransporthttp.c Func:DoEvent Line:1212 unable to HTTPAPIEX_ExecuteRequest
(11:37:50.900) Error: Time:Mon Apr  4 19:00:02 2016 File:../../adapters/httpapi_tirtos.c Func:HTTPAPI_CreateConnection Line:80 HTTPCli_connect failed, ret=-102
(11:37:50.970) Error: Time:Mon A[SOCK ERROR] - close socket (81) operation failed to transmit all queued packets

(11:37:50.970) pr  4 19:00:02 2016 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
(11:37:50.970) Error: Time:Mon Apr  4 19:00:02 2016 File:../../src/iothubtransporthttp.c Func:DoMessages Line:1434 unable to HTTPAPIEX_ExecuteRequest
(11:37:50.970) Error: Time:Mon Apr  4 19:00:04 2016 File:../../adapters/httpapi_tirtos.c Func:HTTPAPI_ExecuteRequest Line:132 HTTPCli_sendRequest failed, ret=-107
(11:37:52.990) Error: Time:Mon Apr  4 19:00:04 2016 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
(11:37:52.990) Error: Time:Mon Apr  4 19:00:04 2016 File:../../src/iothubtransporthttp.c Func:DoEvent Line:1212 unable to HTTPAPIEX_ExecuteRequest
(11:37:52.990) Error: Time:Mon Apr  4 19:00:04 2016 File:../../adapters/httpapi_tirtos.c Func:HTTPAPI_CreateConnection Line:80 HTTPCli_connect failed, ret=-102
(11:37:52.990) Error: Time:Mon Apr  4 19:00:04 2016 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
(11:37:52.990) [SOCK ERROR] - close socket (83) operation failed to transmit all queued packets

(11:37:52.990) Error: Time:Mon Apr  4 19:00:04 2016 File:../../src/iothubtransporthttp.c Func:DoMessages Line:1434 unable to HTTPAPIEX_ExecuteRequest
(11:37:52.990) Error: Time:Mon Apr  4 19:00:07 2016 File:../../adapters/httpapi_tirtos.c Func:HTTPAPI_ExecuteRequest Line:132 HTTPCli_sendRequest failed, ret=-107
(11:37:55.310) Error: Time:Mon Apr  4 19:00:07 2016 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
(11:37:55.310) Error: Time:Mon Apr  4 19:00:07 2016 File:../../src/iothubtransporthttp.c Func:DoEvent Line:1212 unable to HTTPAPIEX_ExecuteRequest
(11:37:55.310) Error: Time:Mon Apr  4 19:00:07 2016 File:../../adapters/httpapi_tirtos.c Func:HTTPAPI_CreateConnection Line:80 HTTPCli_connect failed, ret=-102
(11:37:55.370) Error: Time:Mon Apr  4 19:00:07 2016 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
(11:37:55.370) [SOCK ERROR] - close socket (85) operation failed to transmit all queued packets

(11:37:55.370) Error: Time:Mon Apr  4 19:00:07 2016 File:../../src/iothubtransporthttp.c Func:DoMessages Line:1434 unable to HTTPAPIEX_ExecuteRequest
(11:37:55.370) Error: Time:Mon Apr  4 19:00:09 2016 File:../../adapters/httpapi_tirtos.c Func:HTTPAPI_ExecuteRequest Line:132 HTTPCli_sendRequest failed, ret=-107
(11:37:57.460) Error: Time:Mon Apr  4 19:00:09 2016 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
(11:37:57.460) Error: Time:Mon Apr  4 19:00:09 2016 File:../../src/iothubtransporthttp.c Func:DoEvent Line:1212 unable to HTTPAPIEX_ExecuteRequest
(11:37:57.460) Error: Time:Mon Apr  4 19:00:09 2016 File:../../adapters/httpapi_tirtos.c Func:HTTPAPI_CreateConnection Line:80 HTTPCli_connect failed, ret=-102
(11:37:57.530) Error: Time:Mon Apr  4 19:00:09 2016 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:47[SOCK ERROR] - close socket (87) operation failed to transmit all queued packets

(11:37:57.530) 6 unable to recover sending to a working state
(11:37:57.530) Error: Time:Mon Apr  4 19:00:09 2016 File:../../src/iothubtransporthttp.c Func:DoMessages Line:1434 unable to HTTPAPIEX_ExecuteRequest
`
I have checked the Connection String and ms.der file and time stamp. They are all corrected. 
How do I resolve this issue?
Regards,
Hoang

**Comment by ashokkhurana** [comment]
Hi @lamqhoang ,

Could you please answer following questions to help us troubleshoot this further:

1. Do you think of anything that has changed since you started getting this error. For example moving to a new network or upgrading the firmware on your device etc
2. Did you tried building the latest SDK and re-deploying on test? 

Thanks,
Ashok

**Comment by tameraw** [comment]
@lamqhoang - Please feel free to reopen if still having issues and provide us the details as requested by @ashokkhurana. Thanks.
