### ISSUE TITLE
[Java Device Client] Additional messages counted

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdks#446]
Hi,

We've been making several tests using a raspberry pi (with both models 1 and 2) using Java Device Client (master version, 1.0.3):

```
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)
```

We have a small program that opens a connection to the IoT Hub, sends 4 messages and finishes. Our IoT Hub has a Stream Analytics Job attached with 2 outputs, one groups and count the events and the other just print each event received to a blob.

The problem we're experiencing is that the number of messages sent and the count of messages in IoT Hub dashboard (in portal.azure.com) is not the same, we are sending 4 messages on each run of our program the analytics job counts them properly (4 new events every run) but IoT Hub dashboard always counts 1 to 3 extra messages. We've done tests with all protocols (HTTPS, AMQPS, AMQPS-WS, MQTT).

We've added some additional logging to the client and we're quite sure that we're only sending 4 messages and no additional connections or retries are being made (unless they're somehow performed silently by the client).

Any idea what could be causing this issue?

**Comment by tameraw** [comment]
@pizerg - Can you please provide how large the messages that your are sending? And possibly the IoTHub name (or SKU)? What you are seeing is possibly related to sending messages larger than the IoTHub SKU which will cause you to see that count difference.

Also, please refer to our Azure pricing page:
https://azure.microsoft.com/en-us/pricing/details/iot-hub/

**Comment by olivierbloch** [comment]
Hi @pizerg , as @tameraw mentions, this might be related to the size of the messages you are sending. The number of messages you see in the portal is the number of chuncks of 4KB that are received in IoTHub. Messages can technically be as big as 255KB (including protocol overheads) but the portal will count 1 message per 4KB.

**Comment by pizerg** [comment]
@tameraw @olivierbloch Thank you for your replies, you're totally right it was about the message size. Maybe it would be a good idea to include that information here too: 

https://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/#iot-hub-limits
