### ISSUE TITLE
feedback from cloud-to-device message?

### ISSUE THREAD

**Issue by eissi** [Azure/azure-iot-sdks#447]
It worked in the past. but, now, it doesn't seem to work for both java and .net.
I used the simple sample in SDK. Service sent and Device returned with COMPLETE, but, Service didnt' get the feedback.
is it transient or is there any issue in delivering the feedback?

**Comment by eissi** [comment]
To clarify more, with .Net, the meesage should be sent with message.Ack=full to get feedback. I was wondering how we can do with Java. In Java Message class, there is no ACK member. and I was wondering how ServiceClientSample.java works. I didn't make it work.

**Comment by zolvarga** [comment]
Hi eissi,

I was able to repro the problem with Java Service SDK. You are right, it was working before but it got broken. I am investigating it and will get back to you.

Zoltan

**Comment by zolvarga** [comment]
Hi eissi,

I am checking in to develop branch a fix for Java, which will always set the message property "iothub-ack" to "full". Meanwhile there is an easy workaround to get Java Service Client working with the feedback. In the sample at line 68 add the following:
propertiesToSend.put("iothub-ack", "full");

Thanks for using our SDKs,

Zoltan
