### ISSUE TITLE
[C][Linux][CrossCompilation] Error while cross-compiling the SDK for RPI2: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by shazz** [Azure/azure-iot-sdks#449]
Hi, I followed the instructions to cross compile the SDK on rpi2 and it fails at 90%:

```
...
<command-line>:0:0: warning: "__STDC_NO_ATOMICS__" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
[ 84%] Building C object serializer/CMakeFiles/serializer.dir/src/jsonencoder.c.o
[ 85%] Building C object azure-uamqp-c/CMakeFiles/uamqp.dir/src/session.c.o
<command-line>:0:0: warning: "__STDC_NO_ATOMICS__" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
[ 86%] Building C object serializer/CMakeFiles/serializer.dir/src/multitree.c.o
Linking C static library libuamqp.a
[ 86%] Built target uamqp
Scanning dependencies of target message_sender_sample
[ 87%] [ 88%] Building C object serializer/CMakeFiles/serializer.dir/src/schema.c.o
Building C object azure-uamqp-c/samples/message_sender_sample/CMakeFiles/message_sender_sample.dir/main.c.o
<command-line>:0:0: warning: "__STDC_NO_ATOMICS__" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
Linking C executable message_sender_sample
/home/shazz/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/bin/ld: /home/shazz/RPiTools/tools/rootfs/usr/lib/arm-linux-gnueabihf/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlsym@@GLIBC_2.4'
/home/shazz/RPiTools/tools/rootfs/lib/arm-linux-gnueabihf/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [azure-uamqp-c/samples/message_sender_sample/message_sender_sample] Error 1
make[1]: *** [azure-uamqp-c/samples/message_sender_sample/CMakeFiles/message_sender_sample.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 89%] Building C object serializer/CMakeFiles/serializer.dir/src/schemalib.c.o
[ 90%] Building C object serializer/CMakeFiles/serializer.dir/src/schemaserializer.c.o
Linking C static library libserializer.a
[ 90%] Built target serializer
make: *** [all] Error 2
shazz@ubuntu:~/Source/azure-iot-sdks/c/build_all/linux$
```

Any idea ?

**Comment by shazz** [comment]
I fixed it by modifying the compile command line:

```
cd ~/Source/azure-iot-sdks/c/build_all/linux
./build.sh --toolchain-file toolchain-rpi.cmake --skip-e2e-tests \
--skip-unittests --no-amqp --no-mqtt -cl -D__STDC_NO_ATOMICS__ \
-cl --sysroot=$RPI_ROOT -cl -ldl
```

**Comment by ashokkhurana** [comment]
Hi Shazz,

Could you please provide details on the environment you are using for cross compilation? I am able to run the build successfully without adding -cl -ldl option when cross compiling on Debian 8. 

Thanks,
Ashok

**Comment by mboujonnier** [comment]
Of course:
- Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- this is a jessie sid debian based ubuntu Trusty 14.04.4 LTS

**Comment by shazz** [comment]
Of course:

Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
this is a jessie sid debian based ubuntu Trusty 14.04.4 LTS

**Comment by ashokkhurana** [comment]
Thanks @shazz . I tried cross compiling on same environment but I was still able to do it without using the new cl option. Could you please also provide the RPi device information like model and the OS version information. Just want to make sure that the rsync I did with my device is bringing same libraries to RPITools folder as in your environment.

**Comment by markrad** [comment]
Hi @shazz. Thank you for the information. I'm not sure what is different in your environment from the one I used when I created the cross compilation document. The libdl, as I understand it, is used to resolve dynamic libraries. I appreciate you telling us how you fixed it and I will update the document to reflect your findings.

_Mark Radbourne MSFT_

**Comment by shazz** [comment]
Hi @markrad,

As described previously, I just added `-cl -ldl` to the build option:

```
cd ~/Source/azure-iot-sdks/c/build_all/linux
./build.sh --toolchain-file toolchain-rpi.cmake --skip-e2e-tests \
--skip-unittests --no-amqp --no-mqtt -cl -D__STDC_NO_ATOMICS__ \
-cl --sysroot=$RPI_ROOT -cl -ldl
```

So I guess that in the document a simple: 
if the error `"error adding symbols: DSO missing from command line"` happens just add the option` -cl -ldl `to the command line. 
would be enough

**Comment by ashokkhurana** [comment]
Thanks. We'll make this edit in the document.
