### ISSUE TITLE
VS prompts to restore NuGet packages

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#45]
Between these steps:

Getting Qpid Proton via NuGet
1.In Visual Studio 2015 right click on the iothub_client solution and select "Manage NuGet Package for Solutions".

2.Click the "Include prerelease" check box.

You will see a yellow banner at the top of VS stating:
Some NuGet Packages are missing from this solution.  Click to restore from your online package sources.

If this is something our users should do, we should mention this as a possibility.

**Comment by jebrando** [comment]
Added note for this.
