### ISSUE TITLE
[C][Linux][WS] compileOption_C are not propagated to azure-c-shared-utility/ azure-uamqp-c /  azure-umqtt-c

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#451]
Hi,

I'm trying to create a dynamic lib wrapping the iothub_client static lib.
In [amqp cmake](https://github.com/Azure/azure-uamqp-c/blob/cec604402be8c3b18f643d706d2133cab8ab3e0d/CMakeLists.txt#L42-L46) libwebsocket is included before getting compiler options from compileOption_C, thus even if I add -fPIC in compileOption_C on the command line libraries won't get it.

A way is to fire a -DCMAKE_C_MAKE on the command line, but then why would I use compileOption_C  ? Additionnaly, specificaly for -fPICoptions, if the build_python option is set PIC is set faot all libs.

Could you clarify when to use -DCMAKE_C_MAKE and compileOption_C ?

**Comment by mregen** [comment]
@lmussier There is a bug in the cmake script. Currently the compileOption_C are not picked up in the subdirectories. As a workaround please modify the \c\CMakeLists.txt and move the following lines:

> add_subdirectory(azure-c-shared-utility)
add_subdirectory(azure-uamqp-c)
add_subdirectory(azure-umqtt-c)
enable_testing()

after the assignment of the compile options

>if(NOT "${compileOption_C}" STREQUAL "OFF")
    etcetc

**Comment by ewertons** [comment]
Thanks @mregen and @lmussier, I'll have the fix checked into develop soon.

**Comment by ewertons** [comment]
Alright, the fix (#41eb35d2) in develop branch now.

Please let us know if you have any other comments, suggestions or questions.
Thanks for using the Azure IoT Hub Client SDK.
