### ISSUE TITLE
[C][Linux][Cross-compiler]  How to deal with openssl issue with cross-compiler <OpenWrt-Toolchain-ar71xx-for-mips_r2-gcc-4.6-linaro_uClibc-0.9.33.2>

### ISSUE THREAD

**Issue by chaolong0129** [Azure/azure-iot-sdks#453]
Hi All,
    I am a newer and try to build azure-iot-sdks on my platform <openwrt>. I modify build.sh file to turn off some protocols and features. I just open mqtt option. But, when I build the sdks, I always meet the build error that can not find opensslconf.h  even if I included my openssl directory. I also refer the [raspberry-pi cross-compiler](https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md) and add my toolchain.cmake file.  How should I do to build the sdk ?

my environment
<pre>
OPENSSL="/Project/openwrt/build_dir/target-mips_r2_uClibc-0.9.33.2/openssl-1.0.1e"
QTOOLS="/opt/OpenWrt-Toolchain-ar71xx-for-mips_r2-gcc-4.6-linaro_uClibc-0.9.33.2/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2"
</pre>

my toolchain.cmake
<pre>
INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Linux)     # this one is important
SET(CMAKE_SYSTEM_VERSION 1)     # this one not so much

# this is the location of the amd64 toolchain targeting the Raspberry Pi
#SET(CMAKE_C_COMPILER $ENV{RPI_ROOT}/../bin/arm-linux-gnueabihf-gcc)
SET(CMAKE_C_COMPILER $ENV{QTOOLS}/bin/mips-openwrt-linux-gcc)

# this is the file system root of the target
SET(CMAKE_FIND_ROOT_PATH $ENV{QTOOLS})

SET(OPENSSL_ROOT_DIR $ENV{OPENSSL})

SET(OPENSSL_INCLUDE_DIR $ENV{OPENSSL}/include/openssl)
SET(OPENSSL_LIBARAIES $ENV{OPENSSL}/ipkg-install/usr/lib)
#SET(OPENSSL_CRYPTO_LIBRARIES $ENV{OPENSSL}/libcrypto.a)
#SET(OPENSSL_SSL_LIBRARIES $ENV{OPENSSL}/libssl.a)

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_LDFLAGS_FLAGS -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed)
SET(CMAKE_CXX_FLAGS -O2 -pipe -g -feliminate-unused-debug-types -fpermissive)
SET(CMAKE_EXE_LINKER_FLAGS -L $ENV{QTOOLS}/lib)
</pre>

build.sh <modify-parts>
<pre>
run_e2e_tests=OFF
run_longhaul_tests=OFF
build_amqp=OFF
build_http=OFF
build_mqtt=ON
skip_unittests=OFF
build_python=OFF
run_valgrind=0
</pre>

Execute build.sh script
<pre>
./build.sh --toolchain-file toolchain.cmake --skip-e2e-tests --skip-unittests --no-amqp --no-http
</pre>
Error Messages
<pre>
In file included from /usr/include/openssl/ssl.h:146:0,
                 from /Project/azure-iot-sdks/c/azure-c-shared-utility/c/src/tlsio_openssl.c:9:
/usr/include/openssl/e_os2.h:56:33: fatal error: openssl/opensslconf.h: No such file or directory
compilation terminated.
make[2]: *** [azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o] Error 1
make[1]: *** [azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
</pre>

**Comment by robert0129** [comment]
Hi,
    I refe the arduino/Makefie.iot and build it success on my openwrt platform. I will try and run it.
Thanks,

**Comment by chaolong0129** [comment]
Hi,
    My openwrt environment is like as the same Arduino. I refer the Arduino Makefile.iot and build it successfully on my project. 
Thanks,
