### ISSUE TITLE
[C][Linux][AMQP] IoTHubMessage_GetMessageId seems to always return NULL

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#454]
Hi,

I'm currently playing with the IoTHubMessage_GetMessageId, it seems the message id is never retrieve in the context of a receiveMessageCallback, I always get a null pointer.
```
static IOTHUBMESSAGE_DISPOSITION_RESULT receiveMessageCallback(IOTHUB_MESSAGE_HANDLE p_message, void* p_userContextCallback) {
  (void) p_userContextCallback;
    printf("%s", (char*) IoTHubMessage_GetMessageId(p_message);
  return IOTHUBMESSAGE_ACCEPTED;
}
```
The same function called after setting the message id (with IoTHubMessage_SetMessageId) succed. The message is send by DeviceExplorer (DE), build from develop branch. Since DE prints a massage id I thought that this message id will be retrieved on the device side, am I wrong?

**Comment by anthonyvercolano** [comment]
If you use http with your client it will work.  A bug has been filed for amqp.

**Comment by anthonyvercolano** [comment]
Sorry, closed to soon.   Will close when bug fix is released.

**Comment by dcristoloveanu** [comment]
We will look at this bug this week.

**Comment by lmussier** [comment]
Nice, thanks for the update.
I guess you'll have to go through #469 as well, right ?

**Comment by tameraw** [comment]
@lmussier - Thanks for your feedback. We'd like to keep this open until we address it.

**Comment by ewertons** [comment]
Hi @lmussier, the fix for this issue has been checked in and is in the develop branch.

Please let us know if you have any other comments, suggestions or questions.
Thanks for using the Azure IoT Hub Client SDK.
