### ISSUE TITLE
NuGet does not install Proton into AMQP project - Is this correct / expected?

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#46]
In following these steps, it installed Apache.QPID.Proton.Azurelot into the HTTP and MQTT project, but not the AMQP project.  Is that correct / expected?

Specifically the iothubclinet_sample_amqp.

Getting Qpid Proton via NuGet
1.In Visual Studio 2015 right click on the iothub_client solution and select "Manage NuGet Package for Solutions".

2.Click the "Include prerelease" check box.

3.Enter Apache.Qpid.Proton.AzureIot in the Search box (Ctrl+E) to find the Proton NuGet Package.

4.Select the Apache.Qpid.Proton.AzureIot package and on the right pane click the Install button.

5.Enter OK at the dialog and Accept the license terms to continue.

**Comment by jebrando** [comment]
That dialog is allowing you to install the Apache.QPID.Proton.AzureIot NuGet package into the HTTP and the MQTT projects, but it is not needed.  The AMQP project already ships with this dependency on the NuGet package so it is not an option to install it.
