### ISSUE TITLE
Arduino Yun Remote Monitoring Example

### ISSUE THREAD

**Issue by ScottLiuGitHub** [Azure/azure-iot-sdks#461]
I was able to follow the instruction from the following link to make Arduino Yun work with the simplesample_http example. 

https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/openwrt-arduino-yun-c.md

I have two questions: 
1. How to make it work for remote monitoring example? Do I need to make changes to any make files? 
2. Since the method does not use Arduino SDK, how should I build programs to read information sensors? 

Thanks!

**Comment by markrad** [comment]
I'll address your second question first.
I will preface this with the statement that I am not an Arduino expert however, as I understand this device, it consists of two processors. One is the same processor as runs on the Leonardo and the other is running a version of OpenWrt Linux. The Leonardo processor has access to all of the sensors etc. If you wish to move that data to the Linux side of the device you must use the bridge software that is provided. This is effectively using a serial connection between the two processors to move data between them. For examples of how this works you could start by checking out this article from Arduino: https://blog.arduino.cc/2013/09/05/hands-on-the-arduino-yuns-bridge/.

As for your first question, can you clarify what you are trying to do please? Are you trying to remotely monitor the data sent by the Arduino?

_MarkRad (MSFT)_

**Comment by ScottLiuGitHub** [comment]
For the first question: I am trying to register Arduino Yun to use the Azure IOT pre-configured solution. I was able to  follow the instruction from the following link to make Arduino Yun work with the simplesample_http example.

https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/openwrt-arduino-yun-c.md

However, when I tried to build the remote monitoring code (see below), it does not work automatically.  Do I need to make changes to any make files? 

https://github.com/Azure/azure-iot-sdks/blob/e06ad8be39e4c3bb0abe3e6ebaeed7e3bdb4edd2/c/serializer/samples/remote_monitoring/remote_monitoring.c

Thanks much for your help!

**Comment by markrad** [comment]
Hi @ScottLiuGitHub ,

I've researched this further and it appears that the remote_monitoring sample is not built if the build has been directed to not build AMQP. The make file for the Arduino Yun specifically turns off the AMQP portion of the build. You can modify this by editing the file _azure-iot-sdks-yun\c\build_all\arduino\Makefile.iot_. In there look for the section called _define Build/Configure_ and then the line in that section that starts with _cmake_. Modify the portion of that line that reads _-Duse_amqp:bool=OFF_ to _-Duse_amqp:bool=**ON**_. This should cause the remote_monitoring sample to be built for the Yun. You may also need to add a line to the section _define Package/azure-iot-sdks/install_ in the manner of the line for the simplesample_http.

Let me know if you have any further problems.

_Mark Radbourne MSFT_

**Comment by ScottLiuGitHub** [comment]
Thanks much!

**Comment by ashokkhurana** [comment]
Thanks @markrad for helping on this. Closing this issue.
