### ISSUE TITLE
Issue with mbed remote_monitoring sample

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdks#464]
If I import, compile and deploy the remote_monitoring sample program to my mbed device, it appears to freeze shortly after starting:

<img width="492" alt="mbed" src="https://cloud.githubusercontent.com/assets/1454644/14424430/e746f9cc-ffd8-11e5-8678-77c72a7a7f13.png">

If I restart the mbed board - it gets to almost the same point every time.

<img width="492" alt="mbed2" src="https://cloud.githubusercontent.com/assets/1454644/14424550/a2307d9e-ffd9-11e5-88a8-5abbae471efe.png">

**Comment by tameraw** [comment]
@dominicbetts - Thanks for filing this. We'll investigate it.

**Comment by markrad** [comment]
Hi @dominicbetts,
I built and ran the remote_monitoring sample and downloaded it to my mbed device. I am unable to reproduce your issue. It ran perfectly for me. I was able to see the messages being sent by the device and monitor them successfully with the DeviceExplorer. I was also able to send messages to the device from the DeviceExplorer. 
Looking at your output, it does not appear to have successfully connected to the IoT hub. I would start by checking that your connection string is correct.
I cloned the code from the GitHub repository on Friday 4/19. If you have an earlier version than that I suggest you try building the latest available.

_Mark Radbourne MSFT_

**Comment by dominicbetts** [comment]
Hi @markrad,
I have it working now thanks. Two things FYI:
1. Using Putty to connect to the mbed to monitor what's going on, I had to choose a baud rate of 9600. Anything higher and the console froze or displayed garbage.
2. You mentioned that you cloned the repo on 4/19. In the mbed UI the date shows as 04/08:
![mbedimport](https://cloud.githubusercontent.com/assets/1454644/14667313/8f121016-06d6-11e6-8255-495e6c1374ff.png)

Dominic

**Comment by markrad** [comment]
Hi @dominicbetts,
Actually I deleted the statement about my clone immediately after I wrote it when I realized that clone was for a different issue. Sorry for the confusion.
I checked the documentation for the mbed and found this page https://developer.mbed.org/handbook/SerialPC. It says that the device defaults to a baud rate of 9600.

_Mark Radbourne MSFT_
