### ISSUE TITLE
Is there a echo server for IoT Hub ?

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#468]
Hi,

For testing purpose and the ability to have an out of the box bi-directional working sample, could you set a echo iot hub service ? Or at least, could you provide an "how to" to create one ?

Thanks

**Comment by tameraw** [comment]
@lmussier - Currently there is no echo server for IoT Hub. One way you could achieve this is by launching a worker role that takes as input your data from your IoT Hub, then can send these back as messages to the device from which this data had originated.

Some worker-role related references:
https://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-get-started/
https://azure.microsoft.com/en-us/documentation/articles/fundamentals-application-models/#CloudServices

**Comment by tameraw** [comment]
@lmussier - Closing. Please let us know if there are other issues.
