### ISSUE TITLE
[C][Linux] Develop branch is broken

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#469]
Hello,

The devlelop branch is broken for the C sdk if we enable websockets.
The problem comes from libwebsocket compiled with -std=c99 flag
```
cmake ../azure-iot-sdks/c -Duse_amqp:BOOL=ON -Duse_http:BOOL=OFF -Duse_mqtt:BOOL=OFF -Drun_e2e_tests:BOOL=OFF -Duse_wsio:BOOL=ON -Dskip_unittests:BOOL=ON
make
```
Here is what we get 
```
[ 39%] Building C object azure-uamqp-c/libwebsockets/CMakeFiles/websockets.dir/lib/libwebsockets.c.o
cd /home/lmussier/workspace/build-sdk/azure-uamqp-c/libwebsockets && /usr/bin/cc  -DREFCOUNT_ATOMIC_DONTCARE -D__STDC_NO_ATOMICS__=1 -I/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib -I/home/lmussier/workspace/build-sdk/azure-uamqp-c/libwebsockets  -Wall -Werror -fvisibility=hidden -std=c99 -fPIC -pthread   -o CMakeFiles/websockets.dir/lib/libwebsockets.c.o   -c /home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c: In function ‘lws_get_addresses’:
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:313:18: error: storage size of ‘ai’ isn’t known
  struct addrinfo ai, *res;
                  ^
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:345:17: error: ‘AI_CANONNAME’ undeclared (first use in this function)
   ai.ai_flags = AI_CANONNAME;
                 ^
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:345:17: note: each undeclared identifier is reported only once for each function it appears in
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:347:3: error: implicit declaration of function ‘getnameinfo’ [-Werror=implicit-function-declaration]
   if (getnameinfo((struct sockaddr *)ads,
   ^
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:355:3: error: implicit declaration of function ‘getaddrinfo’ [-Werror=implicit-function-declaration]
   if (getaddrinfo(name, NULL, &ai, &result))
   ^
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:360:15: error: dereferencing pointer to incomplete type
    switch (res->ai_family) {
               ^
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:362:48: error: dereferencing pointer to incomplete type
     addr4.sin_addr = ((struct sockaddr_in *)res->ai_addr)->sin_addr;
                                                ^
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:367:13: error: dereferencing pointer to incomplete type
    res = res->ai_next;
             ^
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:369:3: error: implicit declaration of function ‘freeaddrinfo’ [-Werror=implicit-function-declaration]
   freeaddrinfo(result);
   ^
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/libwebsockets.c:313:18: error: unused variable ‘ai’ [-Werror=unused-variable]
  struct addrinfo ai, *res;
                  ^
cc1: all warnings being treated as errors
```

**Comment by lmussier** [comment]
Adding -D_POSIX_C_SOURCE=200112L to enable posix seems do the trick for this error, but another one comes right after.
```
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/context.c: In function ‘lws_create_context’:
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib/context.c:153:2: error: implicit declaration of function ‘getdtablesize’ [-Werror=implicit-function-declaration]
```

**Comment by lmussier** [comment]
Here is possible way to make things compile again.
https://github.com/Azure/azure-uamqp-c/pull/8

**Comment by ewertons** [comment]
So I deployed a brand new Ubuntu 14.04 LTS, and set it up using the script on (setup.sh)[https://github.com/Azure/azure-iot-sdks/blob/develop/c/build_all/linux/setup.sh].

Then I followed the steps on:
https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/amqp-c-websockets-run-sample.md
and
https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md 


This is the output:
===========
ewertons@esds-ubuntu01:/mnt/ewertons-dev1-repos/azure-iot-sdks$ ./build/linux_c.sh --use-websockets 

[build traces] ...

ewertons@esds-ubuntu01:/mnt/ewertons-dev1-repos/azure-iot-sdks$ ls ~/cmake/iothub_client/samples/iothub_client_sample_amqp_websockets/
CMakeFiles  cmake_install.cmake  CTestTestfile.cmake  **iothub_client_sample_amqp_websockets**  Makefile 


===========

I'm using the openssl version that comes with Ubuntu 14.04, which is the one we originally tested on.

ewertons@esds-ubuntu01:/mnt/ewertons-dev1-repos/azure-iot-sdks$ /usr/bin/openssl
OpenSSL> version
OpenSSL 1.0.1f 6 Jan 2014
OpenSSL> quit
ewertons@esds-ubuntu01:/mnt/ewertons-dev1-repos/azure-iot-sdks$

**Comment by ewertons** [comment]
So could you please try building following the steps above, and verify if it succeeds on your machine?

**Comment by lmussier** [comment]
Sure, let me try this.

2016-04-23 0:09 GMT+02:00 ewertons <notifications@github.com>:

**Comment by lmussier** [comment]
I'll write down all I've done to be sure we did not miss something...
* Run setup part
* install cmake 3.5 through https://cmake.org/files/v3.5/cmake-3.5.0-Linux-x86_64.sh
* Update the GCC to 4.9.3 through the tooolchain ppa

check 

```
* uname -a : 14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* cmake --version : cmake version 3.5.0
* gcc / g++ : Ubuntu 4.9.3-8ubuntu2~14.04
```
All seems ok up to there, the I clone develop branch
`git clone -b develop --recursive https://github.com/Azure/azure-iot-sdks.git`

Check to be sure we are were we want to be
`git submodule sync --recursive && git submodule update --recursive`

Compile with
`lmussier@lmussier-VirtualBox:~/workspace/azure-iot-sdks$ ./linux_c.sh --use-websockets`

Get an issue with file naming 

```
Scanning dependencies of target wsio_unittests_exe
[ 62%] Building CXX object azure-uamqp-c/tests/wsio_unittests/CMakeFiles/wsio_unittests_exe.dir/wsio_unittests.cpp.o
/home/lmussier/workspace/azure-iot-sdks/c/azure-uamqp-c/tests/wsio_unittests/wsio_unittests.cpp:7:40: fatal error: azure_C_shared_utility/xio.h: No such file or directory
 #include "azure_C_shared_utility/xio.h"
                                        ^
compilation terminated.
```
Correct the issue (change azure_C_shared_utility/xio.h in azure_**c**_shared_utility/xio.h)
Rerun the build script => the iot web socket sample is built.

I've switch to my own cmake command and found what I was doing wrong, passing -DcompileOption_C:STRING=-fPIC -std=c99 is not a good thing, it sends std=c99 to libwebsockets...

I've updated the pull request to correct the typo in wsio_unittests.cpp, thanks for you @ewertons.

**Comment by lmussier** [comment]
i'll reopen, juste to make sure we correct the typo
