### ISSUE TITLE
Preparing Qpid Proton libararies in Windows

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#47]
While you do state that there are two options, it might be better to clearly show them as 'Option 1' & 'Options 2'.

The AMQP samples require the Qpid Proton-C library. There are two ways to obtain the library-- via NuGet or by downloading the source from GitHub and building it yourself.

So have:
Option 1: Getting Qpid Proton via NuGet
....
Option 2: Building the Qpid Proton library

Otherwise someone following along might accidentally think that they have to follow both sets of instructions.

**Comment by jebrando** [comment]
Thank you for your comment, this has been updated and will be released.
