### ISSUE TITLE
AMQP transport authentication timed out

### ISSUE THREAD

**Issue by jamescmaki** [Azure/azure-iot-sdks#470]
AMQP transport authentication timed out on master branch at 5a6db048ef6a322ca000d3eb518ee7289c71b544. This is being run using the Python bindings, but should be same as from C. Need to know how to debug the error better.

Testing and working on x86-64, but not working on cross compile to 32 bit Arm target.

I have verified all the things asked in this issues and others (time is set correct, firewall is off, etc). In fact, I have Proton ported to Arm and it works fine to connect with IoTHub. I am working on porting SDK for long term compatibility, but it seems the SDK is still a bit flaky. 

Is latest master known working on 32 bit Arm targets? 

How can I debug transport authentication failures better?

./iothub_client_sample_amqp.py 

Python 2.7.3 (default, Aug 29 2015, 00:26:05) 
[GCC 4.8.2]

IoT Hub for Python SDK Version: 1.0.4

Starting the IoT Hub Python sample using protocol AMQP...
Info: IoT Hub SDK for C, version 1.0.4
IoTHubClient sending 5 messages
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [1] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [2] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [3] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [4] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
Send status: BUSY
Send status: BUSY
Send status: BUSY
Error: Time:Tue Apr 12 12:47:31 2016 File:<dir>/build/tmp/work/arm926ejste-mlinux-linux-gnueabi/python-iothub/1.0.4+gitAUTOINC+5a6db048ef-r0/git/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1214 AMQP transport authentication timed out.
-> [CLOSE]* {}
Send status: BUSY

**Comment by tameraw** [comment]
@jamescmaki - Thanks for reporting this issue. It's possible that it's a certificate related issue.

1) Please confirm that the certificates are up to date on your platform.
2) You can also can make use of the SetOption for "TrustedCerts" to specify the certificate as shown in the c-sample:
https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c

**Comment by jamescmaki** [comment]
Proton is capable of connecting to IoT Hub without issue. I would hope the Azure IoT Hub SDK does not need any special help to find certs as no other program does.

**Comment by jamescmaki** [comment]
TrustedCerts option looks like it was added for mbed environments. My application is running from Yocto Linux.

**Comment by mregen** [comment]
@jamescmaki, could you try the amqp c-sample mentioned in the previous post and see if it works, so we can isolate if there is an issue in the C or Python layer. 
The log output looks as if the connection string is not quite right. Could you double check?

**Comment by jamescmaki** [comment]
Adding the certificates to TrustedCerts solved the problem. Unfortunately the set_options for Python only supports integer values.

**Comment by jamescmaki** [comment]
Also note that someone just pushed changes which broke python building for me.

I have libboost_python.a and libboost_python3.a for 2.7 and 3. I do not have libboost_python-py2.7.a

**Comment by mregen** [comment]
@jamescmaki thanks for the info. I'll follow up on the cert and the build issue.

**Comment by mregen** [comment]
@jamescmaki Could you please review if  	a6c9a33 would fix your cert issue?

**Comment by mregen** [comment]
@jamescmaki certificate fix in master, build fix is going in develop
