### ISSUE TITLE
JAVA Device SDK issue: Big message is not delivered using amqps_ws

### ISSUE THREAD

**Issue by eissi** [Azure/azure-iot-sdks#472]
When a big message such as 100KB  from a device using JAVA SDK with amqps_ws, it's not delivered. It works when the protocl is amqps.

**Comment by tameraw** [comment]
@eissi - Thanks for filing this issue. We'll investigate it.

**Comment by zolvarga** [comment]
Hi eissi,

I am investigating the issue with the large message size. I have a repro of it. I will get back to you as soon as I have a fix for it.

Thanks,
Zoltan

**Comment by zolvarga** [comment]
Hi eissi,

We released a new proton-j-azure-iot package version 0.12.2. Please update your pom.xml to use it and try out with large message. Now message size is limited by the server (255K), and the amqps_ws works the same way as the amqps. 

Thanks,
Zoltan

**Comment by tameraw** [comment]
@eissi - Closing as this has been fixed. Please feel free to reopen if still facing issues with this. Thanks.
