### ISSUE TITLE
Java API does not implement any interfaces

### ISSUE THREAD

**Issue by kittylyst** [Azure/azure-iot-sdks#473]
The Java API violates the "Code to Interfaces" principle, meaning that it cannot be easily mocked. A test implementation would be very useful when debugging possibly flaky devices.

**Comment by iluican** [comment]
Hello,

While it's true that our code doesn't always follow the principle you mentioned, mocking calls to methods shouldn't be too hard using junit and jmockit (http://search.maven.org/#search%7Cga%7C1%7Cjmockit). We make extensive use of jmockit in our unit tests, and we found it rather straightforward to work with.

Thant being said, we are constantly tweaking and improving our sdks, and we will definitely consider your suggestion as a future enhancement.

Thank you,
Ilie.

**Comment by iluican** [comment]
Since I haven't heard from you in a while, I'll assume my answer was sufficient. I'll close this issue now, please feel free to reopen a new one if needed.

Thank you,
Ilie.
