### ISSUE TITLE
Java DeviceClient does not implement Closeable

### ISSUE THREAD

**Issue by kittylyst** [Azure/azure-iot-sdks#474]
The Java DeviceClient class could implement Closeable, which would make it usable in try-with-resources blocks.

**Comment by tameraw** [comment]
@kittylyst - Thanks for the feedback. We'll consider adding this in a future release. However, we happily accept [contributions](https://github.com/Azure/azure-iot-sdks/blob/master/CONTRIBUTING.md) if you decide to submit a pull request for this.

**Comment by kittylyst** [comment]
Thanks @tameraw - have submitted PR 479 for this.

**Comment by tameraw** [comment]
@kittylyst - Closing issue as PR has been merged. Thanks for your contribution.
