### ISSUE TITLE
AMQP Support in C# PCL

### ISSUE THREAD

**Issue by vslepakov** [Azure/azure-iot-sdks#477]
Great to see that there is now a PCL for C#. Are us guys plan on supporting AMQP in this PCL? As far as I know only HTTP is possible now.

**Comment by arturl** [comment]
Hi @vslepakov, this is on our backlog. We also welcome contributions, if you want to help out on this!

**Comment by vslepakov** [comment]
Hi @arturl thanks, I might do just that

**Comment by djcasey** [comment]
Any advance on this?

**Comment by arturl** [comment]
Hi @vslepakov,
We've added AMQP support for Android -- it will show up in the next release. 
Every platform in PCL has to have a different implementation, which is why it will yet be immediately available everywhere.

**Comment by djcasey** [comment]
Hi @arturl,
When is the next release expected?

**Comment by arturl** [comment]
Hi @djcasey, new releases come out every couple of weeks, so I expect this to come out very soon. I'll contact the dev team and make sure they include the updated AMQP library in the next release (that's the component that has the fix).

Also note that the PCL NuGet package is no longer needed, the "regular" Azure.Devices.Client NuGet package now supports PCL.

**Comment by djcasey** [comment]
Hi @arturl, has this feature been delayed? A new version (1.0.21) was released but doesn't appear to support AMQP on Android yet.

**Comment by arturl** [comment]
Yes, this is delayed sorry. @olivierbloch, care to comment on this?
I'll keep the issue open so it stays on the radar.

**Comment by tameraw** [comment]
@arturl - A new package for AMQP has been released in NuGet.

**Comment by tameraw** [comment]
Work is in progress to bring this support in the client SDK.

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-csharp#26
