### ISSUE TITLE
Creating Environment Variables

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#48]
When you mention create an environment variable you might want to link to a document section that describes where / how to set them for the system so they will continue to be present for each command prompt that you open.

For example here:

Building the Apache MQTT library in Windows
To build the MQTT-based samples you must install the Paho open source library.

1.Create the environment variables OpenSSLDir=c:\OpenSSL and PAHO_PATH=c:\Paho.

Since these instructions are for Windows you might want to say:
Open Control Panel, Select System.
Select the 'Advanced System Settings'
Click on the 'Advanced' tab.
Choose the Environment Variables... button

Enter any new variables as 'System' variables if you want them available for all users on the system.

Also, it doesn't mention if you need to create the directories or if they are created for you automatically.

One other question is do these variables only need to be present for a single session to build the component, or should they be set and added for all future sessions?

**Comment by jebrando** [comment]
Added Note for this, Thank you.
