### ISSUE TITLE
[Question] Stream analytics message properties

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#486]
Wasn't sure where to put this, but a Device to Cloud message, that we add properties to, how do we read or query against these properties in Azure Stream Analytics?

One of my queries is a straight `SELECT * INTO <storage> FROM <input>` and the properties aren't in the blob storage there. Was wanting to use these properties to differentiate message types.

Thanks in advance.

**Comment by burns97** [comment]
I have been trying to determine this as well.  An answer to a similar questions seems to indicate that it is not possible at this time.

https://social.msdn.microsoft.com/Forums/en-US/f40756e9-2f90-4c8a-ab3c-8665a81696ed/eventdata-properties-in-stream-analytics?forum=AzureStreamAnalytics

**Comment by damienpontifex** [comment]
Seems definitive enough. Thanks @burns97
