### ISSUE TITLE
Installing Perl on Windows

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#49]
Provided link in this line:
_2.Install Perl ver. 5.20.2 or higher (make sure it is installed in your path, type "perl -v" to verify)._
gives the end user two versions of Perl that can be installed in Windows (Strawberry/ActiveState). We should at least mention why one might pick one over the other or tell them that it makes no difference.

**Comment by jebrando** [comment]
Thank you for the comment.  We feel we should have the assumption that there may be more then 2 Perl versions and as long as they have version 5.20.2 or higher then the build will succeed.
