### ISSUE TITLE
Automate the process of creating connection String of each device

### ISSUE THREAD

**Issue by Belkheir** [Azure/azure-iot-sdks#490]
Hi .
I'm actually an engineering student  doing my internship in "Monitoring Platform and the optimization of a production line based on Azure IOT Hub".I have done an implementation with one device in the Azure  solution as well,that works pretty good, and i was wondering if there is a way to automate the process of creating connection String of many devices ,instead of creating the connection string for each device manually as well as add it inside your code.

I would be very very grateful if you can show me how can i handle this issue.

Have a nice day.

**Comment by tameraw** [comment]
@Belkheir - Currently we have code in the DeviceExplorer tool that shows how you can generate a device connection string. Check the code under the "SAS Token..." button under the "Management" tab in DeviceExplorer.

**Comment by wmmihaa** [comment]
@tameraw Would you mind if I took a shoot at this and added it to iot-hub-explorer?

**Comment by Belkheir** [comment]
Of course with all pleasure :)
Le 16 avr. 2016 12:50, "Mikael Håkansson" <notifications@github.com> a
écrit :

**Comment by wmmihaa** [comment]
@Belkheir I think @tameraw might already got started. I'll wait for his approval ;)

**Comment by Belkheir** [comment]
@tameraw I checked the SAS Token but it requires to create  each time the device ID, The solution that i'm looking for is that for example the device ID must be generated automatically using Code, not with the interface of Device Explorer :),

**Comment by tameraw** [comment]
@wmmihaa - Sure. Feel free to submit a PR for that. Thanks.

**Comment by wmmihaa** [comment]
@tameraw @pierreca What is the prefered way to work with the repo as you do development? For instance, I can't run this:
[git directory]\wmmihaa\azure-iot-sdks\tools\iothub-explorer>**node iothub-explorer.js help**

**Comment by pierreca** [comment]
that should work when running from standard command line... what's the error?

**Comment by wmmihaa** [comment]
@pierreca It's probobly me... ;)

C:\@GIT\wmmihaa\azure-iot-sdks\tools\iothub-explorer>node iothub-explorer.js help
module.js:339
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\@GIT\wmmihaa\azure-iot-sdks\tools\iothub-explorer\iothub-explorer.js:9:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

**Comment by wmmihaa** [comment]
@pierreca Perhaps I should run npm install first ;) 
#Ashamed

**Comment by wmmihaa** [comment]
@pierreca First I thought I missed doing npm install, but i had. The error I get is "Cannot find module 'debug'"

C:\@GIT\wmmihaa\azure-iot-sdks\tools\iothub-explorer>node iothub-explorer.js help
module.js:339
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\@GIT\wmmihaa\azure-iot-sdks\tools\iothub-explorer\node_modules\azure-iothub\node_modules\azure-iot-http-base\lib\http.js:7:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\@GIT\wmmihaa\azure-iot-sdks\tools\iothub-explorer\node_modules\azure-iothub\node_modules\azure-iot-http-base\index.js:13:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

**Comment by wmmihaa** [comment]
I added the debug directory from: 
C:\@GIT\wmmihaa\azure-iot-sdks\tools\iothub-explorer\node_modules\azure-iothub\node_modules\azure-iot-amqp-base\node_modules\

to:
C:\@GIT\wmmihaa\azure-iot-sdks\tools\iothub-explorer\node_modules\azure-iothub\node_modules

I realize that is probobly not the right way, but it solved my issue for now...

**Comment by pierreca** [comment]
hi @wmmihaa 
yeah it looks like there's something broken with the http-base dependencies. we're working on it. Thanks for the feedback!

**Comment by wmmihaa** [comment]
@Belkheir There is allready a function for generating connection strings for all devices (didn't know myself):
````
iothub-explorer.js list --connection-string
````

**Comment by Belkheir** [comment]
@wmmihaa  thanks for replying, but i don't wanna  list my connections. What i want do is try to create a device in the azure platform for example, and i shouldn't copy the connection string manually and add it  it in the device program code such as raspberry what i wanna do is to get connection string for each device using a WebService REST . That means put one code in any device and it will works (image you have 50 devices you should copy the connections string manually for 50 devices ...) if you have a suggestion like that i will be grateful :)

**Comment by wmmihaa** [comment]
Ok, just so I understand... - you like to use your own secret code which you have hardcoded in all devices from the start. Call  a custom REST endpoint (with the secret) to receive the connection string and continue from there?

**Comment by wmmihaa** [comment]
@Belkheir  If this is what you want, there are some obvious security issues, as anyone with access to your device will be able to receive the connectionstring and send events. Part from that you still need to configure the device with a unique name? 

Provided I understand you correctly, you might consider having a look at microServiceBus.com which is built to extend Azure IoT hub (you need to select that option when signing up or an organization) (Also it's free).

microServiceBus won't let you hardcode the secret, but you can generate the code from the portal (valid for 30 min) and use the code as a startup parameter for any number of devices.

After the device has logged in it receives the connectionstring.

There are plenty ov other features there as well. Have a look at the Get Started video here:
https://youtu.be/XjYoZ7GRWgU

Cheers

**Comment by Belkheir** [comment]
yes  that's a good idea, I was wondering if you have an example like that
or something interesting that handle this issue. :)

**Comment by Belkheir** [comment]
@wmmihaa  i think i got an idea to configure the device with unique name , for example when you create in the azure plateform  ID="Device1" , so in the configuration system of the raspberry you can call the device with the same name and in the connection string of the device you call System.getproperty()

**Comment by wmmihaa** [comment]
@Belkheir You might consider having a look at the DeviceManager to find out how to generate sas keys and connectionstrings if you'd like to build the service yourself.

Otherwise, -have a look at microServiceBus.com. It's not another platform, it just extends your Azure IoT hub with device and application management. Either way I don't think iot-explorer is the right tool in this case.

**Comment by Belkheir** [comment]
@wmmihaa  OK i'll certainly take a look to microServiceBus.com ,I want thank you so much for this interactive exchange.Hope to keep in touch with you soon.
Cheers.

**Comment by wmmihaa** [comment]
no worries. Happy to help out.

@tameraw I think you can close this issue.

**Comment by tameraw** [comment]
@wmmihaa - Thanks for your help on this. Closing.
