### ISSUE TITLE
Can you provide the Java SDK as an OSGi bundle?

### ISSUE THREAD

**Issue by bcraun** [Azure/azure-iot-sdks#491]
This would simplify OSGi developers' lives significantly. Today, it's quite fiddly to wrap the .JAR in an OSGi bundle and satisfying the bundle resolver is proving to be a big time sink.

**Comment by tameraw** [comment]
@bcraun - This is currently not in our priority list, but we would happily accept contributions. Thanks.

**Comment by tameraw** [comment]
@bcraun - Are you not able to download our libraries from Maven?

**Comment by bcraun** [comment]
To my knowledge, you don't provide any OSGi bundles; only the JAR artifacts that I spoke about previously.

**Comment by tameraw** [comment]
@bcraun -
Unfortunately, this is currently not a priority in our backlog. 
But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade).
