### ISSUE TITLE
Determining MQTT client connection state?

### ISSUE THREAD

**Issue by bcraun** [Azure/azure-iot-sdks#492]
It looks like the DeviceClient class is declared final and the connection state property is private. How does one determine the connection state of the connection from a DeviceClient instance?

**Comment by iluican** [comment]
Hello,

The connection is meant to be open at all times. Whenever a disconnection occurs (token expired or network down), we have a retry mechanism for reopening it. While the connection is down the messages are buffered to be sent the moment the connection is re-established. 

There is no way to determine the connection state currently. Could you please expand on your scenario? We could definitely add a work item to expose it in the future.

Thank you,
Ilie.

**Comment by bcraun** [comment]
As long as neither the open() or close() methods throw, I assume calling open()/close() multiple times produces no side effects. I'm thinking of (admittedly) edge cases where the DeviceClient is injected into a service which may not know the current state (open, close, faulted, etc.). Inspecting it is the defensible thing to do. So, if a, already connected client were to be injected and the service calls open(), no bad things happen. Same with close(). Just curious.

**Comment by iluican** [comment]
If open() is called on an already connected client nothing bad happens. Same goes with close(). We have checks in place for both the scenarios. I will close this issue now, please feel free to open a new one if you have further questions.

Thank you,
Ilie.
