### ISSUE TITLE
Running azure-iot-sdk sample code iothub_client_sample_http.py failed on Windows Server 2012 R2.

### ISSUE THREAD

**Issue by Laurachu** [Azure/azure-iot-sdks#493]
I am trying to run azure-iot-sdks-bak\python\device\samples\iothub_client_sample_http.py on a Windows Server 2012 R2 virtual machine. The machine is connected to our company's network which is behind a company proxy server. I received the following messages:

IoT Hub for Python SDK Version: 1.0.4

Starting the IoT Hub Python sample using protocol HTTP...
IoTHubClient sending 3 messages
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [1] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [2] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
IoTHubClient sending 3 messages
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [1] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [2] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
IoTHubClient sending 3 messages
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [1] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [2] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
IoTHubClient sending 3 messages
Error: Time:Tue Apr 19 14:25:18 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 WinHttpSendRequest: (result = HTTPAPI_SEND_REQUEST_FAILED).
Error: Time:Tue Apr 19 14:25:18 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 GetLastError: The operation timed out
.
Error: Time:Tue Apr 19 14:25:18 2016 File:C:\GitRepositories\azure-c-shared-utility\src\httpapiex.c Func:_HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Tue Apr 19 14:25:18 2016 File:C:\repos\azure-iot-sdks\c\iothub_client\src\iothubtransporthttp.c Func:_DoEvent Line:1486 unable to HTTPAPIEX_ExecuteRequest
Error: Time:Tue Apr 19 14:25:39 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 WinHttpSendRequest: (result = HTTPAPI_SEND_REQUEST_FAILED).
Error: Time:Tue Apr 19 14:25:39 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 GetLastError: The operation timed out
.
Error: Time:Tue Apr 19 14:25:39 2016 File:C:\GitRepositories\azure-c-shared-utility\src\httpapiex.c Func:_HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Tue Apr 19 14:25:39 2016 File:C:\repos\azure-iot-sdks\c\iothub_client\src\iothubtransporthttp.c Func:_DoMessages Line:1708 unable to HTTPAPIEX_ExecuteRequest
Error: Time:Tue Apr 19 14:26:00 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 WinHttpSendRequest: (result = HTTPAPI_SEND_REQUEST_FAILED).
Error: Time:Tue Apr 19 14:26:00 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 GetLastError: The operation timed out
.
Error: Time:Tue Apr 19 14:26:00 2016 File:C:\GitRepositories\azure-c-shared-utility\src\httpapiex.c Func:_HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Tue Apr 19 14:26:00 2016 File:C:\repos\azure-iot-sdks\c\iothub_client\src\iothubtransporthttp.c Func:_DoEvent Line:1486 unable to HTTPAPIEX_ExecuteRequest
Error: Time:Tue Apr 19 14:26:21 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 WinHttpSendRequest: (result = HTTPAPI_SEND_REQUEST_FAILED).
Error: Time:Tue Apr 19 14:26:21 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 GetLastError: The operation timed out

Can some one help me with this?

Thanks,
Laura

**Comment by anhashia** [comment]
Make sure you proxy settings are correct. Set system proxy settings of your Windows Server 2012 machine by going to Control Panel -> Internet Options> Connections -> LAN settings->Proxy server and re-test the sample application.

**Comment by Laurachu** [comment]
Thank you for your reply!

I checked the proxy server settings as you suggested. The settings were correct. I run the sample code, I still got the same result. 

Then I used dos command set to set the system proxy settings http_proxy and https_proxy with the proxy user name and password, re-run the sample code, the result didn't change.

Laura

**Comment by anhashia** [comment]
Please sync with latest master. Follow the documentation and try again. I tested locally with both proxy and non-proxy setting using the sample iothub_client_sample_http.py and I don't see any issue. Also, please make you sure you update iothub_client_sample_http.py file with right device connection string to make successful connection.

**Comment by Laurachu** [comment]
Thank you for replying!

I repeated the test from git pull to get the latest code from master, created iothub_client.pyd by running C:\azure-iot-sdks\python\build_all\windows\build.bat; copy&paste a device's connection string to iothub_client_sample_http.py. I got the same error code running the sample code. 

I verified that with Device Explorer tool, I couldn't send messages from my Windows Server 2012 R2 machine to IoT Hub. 

But I am able to run the C sample code to send messages to a IoT Hub on a Centos 7 machine using the same device connection string.  The Centos machine is connected to the same company network.

Laura

**Comment by anhashia** [comment]
I just tested on Azure VM running Windows Server 2012 and I tested the connection to IoT Hub device using **Device Explorer** tool. I was able to send message back and forth without any issues using Device Explorer tool.

If **Device Explorer **tool is also showing a connection issue on same network that your Centos 7 machine doesn't show, then it look like there is some firewall or connection setting on your Windows Server that is blocking the outgoing connection to Azure  IoT Hub.

**Comment by Laurachu** [comment]
I turned off the firewall off on my Windows Server 2012. Now messages are sent to IoT Hub using Device Explorer tool, but the python script still returns the same failure messages. I configured the same device connection string in iothub_client_sample_http. The same error messages were received to run it. 

For the iothub_client_sample_amqp, the following message were received:

IoT Hub for Python SDK Version: 1.0.4

Starting the IoT Hub Python sample using protocol AMQP...
Info: IoT Hub SDK for C, version 1.0.4
IoTHubClient sending 5 messages
Error: Time:Wed Apr 20 15:23:40 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\socketio_win32.c Func:_socketio_open Line:274 Failure: connect fail
ure 0.
Error: Time:Wed Apr 20 15:23:40 2016 File:C:\repos\azure-iot-sdks\c\iothub_client\src\iothubtransportamqp.c Func:_establishConnection Line:446 Failed to open th
e connection with CBS.
Error: Time:Wed Apr 20 15:23:40 2016 File:C:\repos\azure-iot-sdks\c\iothub_client\src\iothubtransportamqp.c Func:_IoTHubTransportAMQP_DoWork Line:1198 AMQP tran
sport failed to establish connection with service.
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
Error: Time:Wed Apr 20 15:24:01 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\socketio_win32.c Func:_socketio_open Line:274 Failure: connect fail
ure 0.
Error: Time:Wed Apr 20 15:24:01 2016 File:C:\repos\azure-iot-sdks\c\iothub_client\src\iothubtransportamqp.c Func:_establishConnection Line:446 Failed to open the connection with CBS.
Error: Time:Wed Apr 20 15:24:01 2016 File:C:\repos\azure-iot-sdks\c\iothub_client\src\iothubtransportamqp.c Func:_IoTHubTransportAMQP_DoWork Line:1198 AMQP tran
sport failed to establish connection with service.

**Comment by anhashia** [comment]
Your message is showing that you are using AMQP protocol (iothub_client_sample_amqp.py). Try with HTTP protocol first by running iothub_client_sample_amqp.py. For HTTP, you should see "Starting the IoT Hub Python sample using protocol HTTP..." message.

**Comment by Laurachu** [comment]
See the messages I received to run the Python sample using http:

IoT Hub for Python SDK Version: 1.0.4

Starting the IoT Hub Python sample using protocol HTTP...
Info: IoT Hub SDK for C, version 1.0.4
Info: HTTP_API first init.
IoTHubClient sending 3 messages
Info: HTTP_API has now 1 users
Error: Time:Wed Apr 20 15:37:44 2016 File:C:\GitRepositories\azure-c-shared-util
ity\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 WinHttpSend
Request: (result = HTTPAPI_SEND_REQUEST_FAILED).
Error: Time:Wed Apr 20 15:37:44 2016 File:C:\GitRepositories\azure-c-shared-util
ity\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 GetLastErro
r: The operation timed out
.
Info: HTTP_API has now 0 users
Info: Deinitializing HTTP_API
Error: Time:Wed Apr 20 15:37:44 2016 File:C:\GitRepositories\azure-c-shared-util
ity\src\httpapiex.c Func:_HTTPAPIEX_ExecuteRequest Line:476 unable to recover se
nding to a working state
Error: Time:Wed Apr 20 15:37:44 2016 File:C:\repos\azure-iot-sdks\c\iothub_clien
t\src\iothubtransporthttp.c Func:_DoMessages Line:1708 unable to HTTPAPIEX_Execu
teRequest
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [1] for transmission to IoT Hub.I
nfo: HTTP_API first init.

Info: HTTP_API has now 1 users

**Comment by anhashia** [comment]
Looks like there is still some configuration that is blocking the outgoing HTTP send request from Python sample. It is odd that you are able to send messages through Device Explorer and not through Python sample on the same machine. Check the network port used by the Python sample. See if for some reason that outgoing network port is getting blocked.

Another approach would be try with some other sample like C or node.js on same machine and see if you see the same issue with HTTPS connection.

**Comment by Laurachu** [comment]
See the messages I got to run the C code:

C:\azure-iot-sdks\c\iothub_client\samples\iothub_client_sample_http\windows\Win3
2\Debug>iothub_client_sample_http.exe
Starting the IoTHub client sample HTTP...
Info: IoT Hub SDK for C, version 1.0.4
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.

IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.

IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.

IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.

IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.

Info: HTTP_API first init.
Info: HTTP_API has now 1 users
Error: Time:Wed Apr 20 16:29:43 2016 File:C:\GitRepositories\azure-c-shared-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 WinHttpSendRequest: (result = HTTPAPI_SEND_REQUEST_FAILED).
Error: Time:Wed Apr 20 16:29:43 2016 File:C:\GitRepositories\azure-c-shared-util
ity\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:446 GetLastErro
r: The operation timed out
.
Info: HTTP_API has now 0 users
Info: Deinitializing HTTP_API
Error: Time:Wed Apr 20 16:29:43 2016 File:C:\GitRepositories\azure-c-shared-utility\src\httpapiex.c Func:_HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Wed Apr 20 16:29:43 2016 File:C:\repos\azure-iot-sdks\c\iothub_clien
t\src\iothubtransporthttp.c Func:_DoEvent Line:1486 unable to HTTPAPIEX_ExecuteRequest
Info: HTTP_API first init.
Info: HTTP_API has now 1 users

**Comment by anhashia** [comment]
Yeah, you will have to look at the network trace or log to see if the HTTPS packet sent from your client is actually leaving your Server 2012 machine. If it is not leaving the Server at all, then you need to figure out what setting on the machine is blocking the outgoing connection. Given that it works on you Centos 7 machine on same network topology, it does look like your network proxy is not blocking the connections to Azure IoT Hub..

On side note, you can also check if iothub_client_sample_amqp.py sample which uses AMPQ protocol also shows the same behavior. AMPQ will use port 5671 and HTTPS will use port 443. Also use Device Explorer tool for comparison if you are able to send packets using this tool.

**Comment by tameraw** [comment]
@Laurachu - closing this. Please let us know if you're still having issues. thanks.
