### ISSUE TITLE
node.js client does not send/recieve custom properties

### ISSUE THREAD

**Issue by ozakatAvi** [Azure/azure-iot-sdks#494]
Hi, I am using latest package "azure-iot-device-amqp" I got from npm and try to send or receive properties attached to message. My code looks like:
    var messageProto = require('azure-iot-device').Message;
    var message = new messageProto(data);
    message.messageId= 'messageId';
    message.properties.add("testProperty", "testProperty_1");
    client.sendEvent(message, exceptionlog);
On cloud side I have C# message listener what try to use message.Properties and message.Properties actually is null.
I made a small research and found out: in azure-iot-amqp-base/lib/amqp_message properties are not coped to obejct what should send over wire. The same problem with amqp_reciever - properties not copied from object send from cloud

**Comment by pierreca** [comment]
You are correct, this is a known issue (see https://github.com/Azure/azure-iot-sdks/issues/414 and https://github.com/Azure/azure-iot-sdks/issues/352). 

Closing this one to avoid duplicates. Please subscribe to notifications on https://github.com/Azure/azure-iot-sdks/issues/414 if you'd like to get a notification of when this is implemented :)
