### ISSUE TITLE
build error: Run a simple C sample on BeagleBone Black device running Debian

### ISSUE THREAD

**Issue by timov43** [Azure/azure-iot-sdks#495]
Hi,

I have Linux beaglebone 4.1.15-ti-rt-r43 running in my BeagleBone Black.

I run the instructions give in the "Run a simple C sample on BeagleBone Black device running Debian" document.

Everything is OK until I try to build the sample.

timo@beaglebone:~$ sudo ./azure-iot-sdks/c/build_all/linux/build.sh
~/cmake /home/timo
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Checking for one of the modules 'uuid'
CMake Error at /usr/share/cmake-3.4/Modules/FindPkgConfig.cmake:568 (message):
  None of the required 'uuid' found
Call Stack (most recent call first):
  azure-c-shared-utility/tests/uniqueid_unittests/CMakeLists.txt:34 (pkg_search_module)

-- Configuring incomplete, errors occurred!
See also "/root/cmake/CMakeFiles/CMakeOutput.log".

the CMakeList.txt is looking the following around line 34

if(WIN32)
    target_link_libraries(${theseTestsName}_exe rpcrt4.lib)
    target_link_libraries(${theseTestsName}_dll rpcrt4.lib)
else()
    find_package(PkgConfig REQUIRED)
    pkg_search_module(UIDLINUX REQUIRED uuid)          <== line 34

    target_link_libraries(${theseTestsName}_exe uuid)
endif()

Attached is also CMakeOutput.log file (txt)
[CMakeOutput.log.txt](https://github.com/Azure/azure-iot-sdks/files/222618/CMakeOutput.log.txt)

I'm a bit linux noob  and  not understanding reason(s) for build fail.
Any idea what is causing this?

BR
-timo-

**Comment by jebrando** [comment]
You need to install the uuid package on the device.  I will add a switch to be able to disable this feature.

**Comment by timov43** [comment]
Hi,

thanks for info.
-timo-

Sent from my stunning Lumia 640 XL
________________________________
Lähettäjä: Jelani<mailto:notifications@github.com>
Lähetetty: ‎19.‎4.‎2016 19:52
Vastaanottaja: Azure/azure-iot-sdks<mailto:azure-iot-sdks@noreply.github.com>
Kopio: timov43<mailto:timo.valimaki@outlook.com>
Aihe: Re: [Azure/azure-iot-sdks] build error: Run a simple C sample on BeagleBone Black device running Debian (#495)

You need to install the uuid package on the device.  I will add a switch to be able to disable this feature.

---

**Comment by tameraw** [comment]
@timov43 - Please feel free to reopen if still having issues.

**Comment by ratnick** [comment]
Hi,
I think I have a similar issue.
Setup: Beaglebone Black, Debian 8.4.

Commands so far (as root):
sudo apt-get update
sudo apt-get install -y curl libcurl4-openssl-dev build-essential cmake git 
git clone --recursive https://github.com/azure/azure-iot-sdks.git
edit the file 
apt-get install libssl-dev 
apt-get install uuid
./azure-iot-sdks/c/build_all/linux/build.sh


Last part of output:
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shared_Util architecture: ARM
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- Checking for one of the modules 'uuid'
**CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:574 (message):
  None of the required 'uuid' found
Call Stack (most recent call first):
  c-utility/tests/uniqueid_ut/CMakeLists.txt:34 (pkg_search_module)**
....
-- Configuring incomplete, errors occurred!
....

**Final note: the directory ./azure_iot-sdks/cmake does NOT exist (as I believe it should).**

I'm a bit stuck here, any help is appreciated.

**Comment by BertKleewein** [comment]
I believe that you need to use apt-get to install the **uuid-dev** package.  It looks like you're missing the -dev suffix
