### ISSUE TITLE
Service component for the Python SDK?

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-iot-sdks#498]
I'd like to know whether this is being contemplated. I filed a request on [User Voice](https://feedback.azure.com/forums/321918-azure-iot/suggestions/13457844-python-registry-service-sdk?tracking_code=97cd6aaaa75f0a37e690e0eeba6e5bd0) and had it closed due to what is obviously some kind of confusion.

I'd rather not roll my own REST API wrapper to provision devices, really...

**Comment by zolvarga** [comment]
Hi Rui,

We are working on the Python Service SDKs, it is actively in development and it is a high priority for us.

Best Regards,
Zoltan

**Comment by rcarmo** [comment]
Thanks for the prompt feedback!
