### ISSUE TITLE
Apache MQTT Library Issues:

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#50]
From these instructions:
Building the Apache MQTT library in Windows
To build the MQTT-based samples you must install the Paho open source library.
1.	Create the environment variables OpenSSLDir=c:\OpenSSL and PAHO_PATH=c:\Paho. C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2015\Visual Studio Tools\Windows Desktop Command Prompts
2.	Install Perl ver. 5.20.2 or higher (make sure it is installed in your path, type "perl -v" to verify).
3.	Open a Visual Studio 2015 x86 Native Tools command prompt.
4.	Run the script build_paho.cmd in the \build_all\windows directory.

For step #4, you should provide the full path of: c\build_all\windows

For step #3, on two systems we have noticed that the ‘Visual Studio 2015 x86 Native Tools’ command prompt is not listed in the start menu folder under Visual Studio 2015.  Only the x64 version appears to be listed.  If you try to use the x64 version then the build will start, but it will fail.

However, we did find that if you go to the start menu, find the x64 command prompt, right click on it and select ‘Open File Location’ then you will see a list of the various command prompts that by default can be found here:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2015\Visual Studio Tools\Windows Desktop Command Prompts

At that location users can find and launch the VS 2015 x86 Native Tools Command Prompt, which will build the Apache MQTT library.

One other thing that we might want to mention about the building of the library however is that it appears to end with 56 warnings.  Probably best to let users know that is expected (if it is) by default.

**Comment by jebrando** [comment]
Thank you for the comments

Step #4 has been updated.

For Step #3 we didn't add the path to the tools because it's dependent on the user's system, so we let the user decide where the Visual Studio 2015 x86 Native Tools prompt was on each individual system.

Since the MQTT build is a 3rd party library we're are not sure how long the build will contain these warning and shouldn't make assumptions as to the validity or the appearance of these warnings.

**Comment by jtanner-msft** [comment]
For step #3 please make a note under that instruction since it could cause users many problems as the x86 native tools prompt is not in the 'start menu' by default on x64 systems.  This impacted myself and another engineer.

For the MQTT you should mention the number of warnings since we are seeing that number today.  If that changes in the future then go back and update the docs at that time.  But as of Friday we have the 56 warnings.  Possibly say something like 'You might see up to 56 warnings when you build this, but that is okay'.
