### ISSUE TITLE
[C][Python] No message properties

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#501]
It seems getting cloud to device message properties on the device is failing for at least the C and Python clients.

I am currently adding a message type on the server as
```csharp
Microsoft.Azure.Devices.Message commandMessage;
// Initialize message here
commandMessage.Properties.Add("Type", sentFrom.ToString());
```

and then on the client retrieving them in python like:
```python
map_properties = message.properties()
msg_properties = map_properties.get_internals()
self.logger.debug("Got msg properties {}".format(msg_properties))
```

But I get an empty dictionary as `msg_properties`

See also https://github.com/Azure/azure-iot-sdks/issues/427#issuecomment-211847754 by @mregen who seems to have also reproduced the issue in C and Python clients. Also noted that it had worked in the past.

**Comment by tameraw** [comment]
@damienpontifex - Thanks for filing this issue. We'll be investigating it.

**Comment by markrad** [comment]
Hi @damienpontifex,

I am able to reproduce this issue. I will be investigating further.

_Mark Radbourne MSFT_

**Comment by damienpontifex** [comment]
Hi @markrad 
@mregen had also reproduced it and commented here https://github.com/Azure/azure-iot-sdks/issues/427#issuecomment-212947418 that it seemed to be in the amqp and mqtt transport layers as http was working. Hope this also helps.

**Comment by ewertons** [comment]
Hi @damienpontifex, the issue has been fixed for AMQP, a commit was just made in develop with the support for C2D messages.

As per MQTT, we do read then properties from C2D messages as well. Check it [here](https://github.com/Azure/azure-iot-sdks/blob/develop/c/iothub_client/src/iothubtransportmqtt.c) (line 333, function extractMqttProperties(...)).

**Comment by ewertons** [comment]
I will close the issue for now. 
If you have any other comments, please feel free to reopen it.
Thanks.

**Comment by damienpontifex** [comment]
Thanks @ewertons tested and confirmed all fixed for my scenarios. Thanks
