### ISSUE TITLE
Undefined symbol error received to build the Python iothub_client module on Centos7

### ISSUE THREAD

**Issue by Laurachu** [Azure/azure-iot-sdks#503]
I tried to build the azure-iot-sdks in Python on a Centos7 by following the instructions in website https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/python-devbox-setup.md#linux. After I manually installed the required packages included in /azure-iot-sdks/python/build_all/linux/setup.sh, I am able to run the build.sh with option --skip-unittests. But I got undefined symbol error at the end. 

Here is part of messages to run build.sh --skip-unittests
................
[ 97%] Built target simplesample_mqtt
Scanning dependencies of target iothub_client_sample_http_shared
[ 97%] Building C object iothub_client/samples/iothub_client_sample_http_shared/CMakeFiles/iothub_client_sample_http_shared.dir/iothub_client_sample_http_shared.c.o
[ 97%] Built target iothub_client_sample_http
Scanning dependencies of target iothub_client_sample_mqtt
[ 98%] Building C object iothub_client/samples/iothub_client_sample_mqtt/CMakeFiles/iothub_client_sample_mqtt.dir/iothub_client_sample_mqtt.c.o
[ 99%] Building C object iothub_client/samples/iothub_client_sample_http_shared/CMakeFiles/iothub_client_sample_http_shared.dir/linux/main.c.o
Linking C executable iothub_client_sample_http_shared
[100%] Building C object iothub_client/samples/iothub_client_sample_mqtt/CMakeFiles/iothub_client_sample_mqtt.dir/linux/main.c.o
Linking C executable iothub_client_sample_mqtt
[100%] Built target iothub_client_sample_http_shared
[100%] Built target iothub_client_sample_mqtt
Linking CXX shared library iothub_client_mock.so
[100%] Built target iothub_client_mock
Linking CXX shared library iothub_client.so
[100%] Built target iothub_client_python
Test project /home/eaton/cmake
No tests were found!!!
~/source/azure-iot-sdks
copy iothub_client library to samples folder
copy iothub_client_mock library to tests folder
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    from iothub_client_mock import *
ImportError: /home/eaton/source/azure-iot-sdks/python/device/tests/iothub_client_mock.so: undefined symbol: _ZNK5boost6python7objects21py_function_impl_base9max_arityEv

When I tried to run the sample script with the iothub_client-bak.so, I got following import errors. 
azure-iot-sdks/python/device/samples/iothub_client_sample_http.py
Traceback (most recent call last):
  File "/home/eaton/source/azure-iot-sdks/python/device/samples/iothub_client_sample_http.py", line 8, in <module>
    import iothub_client
ImportError: /home/eaton/source/azure-iot-sdks/python/device/samples/iothub_client.so: undefined symbol: _ZNK5boost6python7objects21py_function_impl_base9max_arityEv

Process finished with exit code 1

Can someone help me with this?

Thank you in advance!
Laura

**Comment by tameraw** [comment]
@Laurachu - Thanks for filing this issue. We'll investigate it.

**Comment by mregen** [comment]
@Laurachu on CentOS7 Python 2.7 is building and running ok. But tried Python 3.4 and I see the same issue now. Is this Python 3.4 version you are using?
For 3.4, it looks like the iothub_client.so cannot find a function in the libboost-python.so shared library. On Ubuntu there are seperate libboost-python libraries for each version of Python, but on CentOS 7 I can find only a single one (likely only usable with 2.7). The corresponding boost-python3 and boost-python3-devel packages don't seem available yet on CentOS7, only in Fedora 22  -> [Fedora boost-python3-devel](https://apps.fedoraproject.org/packages/boost-python3-devel). I think your only choice were to download the latest boost zip and to build boost-python3 yourself with Python 3.4 support.

**Comment by Laurachu** [comment]
Hi Mregen, thank you for reply! I am actually using Python 2.7.5 on my Centos7. 

Thanks,
Laura

**Comment by Laurachu** [comment]
For the libboost-python-dev on Ubuntu, what is a matching package for Centos? I don't see a libboost-python-dev for Centos. I have python-devel.x86_64 and boost.x86_64 installed on my Centos7 to meet the requirements setup.sh.

Thanks,
Laura

**Comment by mregen** [comment]
@Laurachu here is what I did for 2.7, I used the latest develop branch. I guess boost-python (the runtime) is missing, so it cannot load the shared lib. 
i) upgrade gcc to 4.9 and packages installed

> sudo yum install centos-release-scl-rh
sudo yum install devtoolset-3-gcc 
sudo yum install devtoolset-3-gcc-c++ 
sudo yum install python-devel
sudo yum install boost boost-devel boost-python openssl-devel curl-devel libuuid-devel

ii) only for Python 3.4 (but it wouldn't build properly)
> sudo yum install epel-release
sudo yum install python34 python34-devel

iii) edit python/device/iothub_client_python/CMakelists.txt 

> 

    # older boost-python libs didn't support versions
    if (${build_python} EQUAL "2.7")
        find_package(Boost COMPONENTS python REQUIRED)
    elseif()
        # Remove the period from python version for boost component
        string(REPLACE "." "" boost_python ${build_python})
        find_package(Boost COMPONENTS "python-py${boost_python}" REQUIRED)
    endif()

iv) now build ...

**Comment by Laurachu** [comment]
Where do I insert step iii in CMakelists.txt?

Thanks,
Lauraaa

**Comment by mregen** [comment]
Just make sure the line to find the boost package looks like this one:
`find_package(Boost COMPONENTS python REQUIRED)`

**Comment by Laurachu** [comment]
Build successfully, and sample code sent messages to IIoT Hub using HTTP.

Thanks a lot!
Laura

**Comment by mregen** [comment]
I will have to put a small tweak in our python ./build.sh for CentOS7. Please keep this issue open until change is submitted.

**Comment by mregen** [comment]
fixed in develop  47a71e9
