### ISSUE TITLE
[C][Linux][SimpleSample]Running azure-iot-sdk sample code failed

### ISSUE THREAD

**Issue by kevin0402** [Azure/azure-iot-sdks#507]
I am trying to port azure-iot-sdk on my embedded linux platform (ARM9, kernel 2.6.31), cross toolchain is arm-none-linux-elf-gnueabi. 

While running serializer/samples/simplesample_amqp, my device stop communicating with IoT Hub after TCP connection is built. 
Only following messages are printed, device can't exchange data with IoT hub.
![simplesample_amqp_error](https://cloud.githubusercontent.com/assets/8455575/14733546/5d8e76bc-0896-11e6-94d1-2dd5314a6262.jpg)

![simplesample_amqp_cap](https://cloud.githubusercontent.com/assets/8455575/14734214/7322dc5c-089b-11e6-9057-b173df0b0218.jpg)

Simplesample_mqtt can't connect to IoT hub as well and the program can't returned until I press Ctrl+C. 
![simplesample_mqtt_error](https://cloud.githubusercontent.com/assets/8455575/14733500/f16bd5ec-0895-11e6-904b-7410983ae0a9.jpg)

![arm_device](https://cloud.githubusercontent.com/assets/8455575/14730375/63e18306-0878-11e6-8129-42e9ba814f55.jpg)

The openssl version in the device is 1.0.0a. I have tried openssl 1.0.2g but it doesn't help. 

In the same environment, another Linux PC (Fedora 23) can run simplesample_mqtt and simplesample_amqp without any problem.
![linux_pc](https://cloud.githubusercontent.com/assets/8455575/14730374/63ce6f28-0878-11e6-8017-24c53861789d.jpg)

Does it relate to "Trusted certificate" which is mentioned in #470 ?
The certificate on my device is self-signed.

**Comment by jjlee3** [comment]
"In the same environment, another Linux PC (Fedora 23) can run simplesample_mqtt and simplesample_amqp without any problem."

The workable simplesample_* are not cross compiled programs. They are native compiled programs and run on Linux PC.

**Comment by markrad** [comment]
Hi @kevin0402,
In the past I've seen some of these devices fail to verify the server's certificate. One circumvention that can help with that is to pass the certificate to the SDK using the function IoTHubClient_SetOption passing the string "TrustedCerts" and the last argument is the certs array found in azure-iot-sdks/c/certs/certs.c. This functionality is only implemented for AMQP. Try that and let me know if it resolves your issue.

_Mark Radbourne MSFT_

**Comment by jjlee9** [comment]
Yes, you are right. The "TrustedCerts" solution solved this problem. Anyway the solution cannot work with OpenSSL 1.0.0a.

After I switched to OpenSSL 1.0.2g, the AMQP and MQTT worked well with "TrustedCerts" solution. I just commented out MBED_BUILD_TIMESTAMP in simplesample_amqp.c and simplesample_mqtt.c plus "TrustedCerts" solution (certs/certs.*) and linked with OpenSSL 1.0.2g library.

The two binary files (amqp and mqtt) worked well under Kevin's device!

I switched back to OpenSSL 1.0.0a with "TrustedCerts" solution and the two binary could not work correctly.

Thanks, it helps! Thanks a lot!

**Comment by markrad** [comment]
Glad to have be able to assist you. I've closed your issue.

_Mark Radbourne MSFT_

**Comment by sergiojx** [comment]
Hi.
I am trying to port azure-iot-sdk as well. My embedded linux platform (ARM9, kernel 3.6.9), cross toolchain is arm-none-linux-gnueabi-gcc. Is there some porting guide available?
Kevin, how did you get it? Could you give some guidance?
Best.

**Comment by jjlee9** [comment]
I worked with Kevin. I can share some experiences with you. I am not in Azure IoT team, so it is not an official guidance.

Follow instructions in [https://github.com/Azure/azure-iot-sdks/tree/master/c] readme.md
If you can build and run an example successfully in ~/azure-iot-sdks/c/cmake/iotsdk_linux/serializer/samples/simplesample_???? under Linux (VM?), you are ready to porting.
If your toolchain is too old, you need to modify .h and .c files.

If your openssl version in toolchain < 1.0.2g, you "might" consider to switch to version 1.0.2g.
Steps to download openssl 1.0.2g source to ~/openssl/
1. download ftp://ftp.openssl.org/source/old/1.0.2/openssl-1.0.2g.tar.gz to ~
2. cd ~
3. tar -xvzf openssl-1.0.2g.tar.gz
4. mv openssl-1.0.2g openssl

If there is no libuuid in your toolchain
Steps to download libuuid source to ~/uuid/uuid/
1. download https://sourceforge.net/projects/libuuid/ to ~/uuid/
2. cd ~/uuid/
3. tar -xvzf libuuid-1.0.3.tar.gz
4. mv libuuid-1.0.3 uuid

Copy ~/azure-iot-sdks/c/build_all/linux/ to ~/azure-iot-sdks/c/build_all/YourSystemName/
Edit a YourSystemName-arm-elf.cmake file under ~/azure-iot-sdks/c/build_all/YourSystemName/
```
INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME YourSystemName)     # this one is important
SET(CMAKE_SYSTEM_VERSION 1)     # this one not so much
SET(ARCH arm)

# this is the location of the amd64 toolchain targeting the Raspberry Pi

SET(TARGET_CROSS arm-elf-)
SET(TOOLCHAIN_DIR /<SomeWhere>/gnutools/arm-elf)
SET(CROSS ${TOOLCHAIN_DIR}/bin/${TARGET_CROSS})
SET(AR ${CROSS}ar)
SET(AS ${CROSS}as)
SET(LD ${CROSS}ld)
SET(NM ${CROSS}nm)
SET(CC ${CROSS}gcc)
SET(GCC ${CROSS}gcc)
SET(CXX ${CROSS}g++)
SET(RANLIB ${CROSS}ranlib)
SET(STRIP ${CROSS}strip)
SET(OBJCOPY ${CROSS}objcopy)
SET(OBJDUMP ${CROSS}objdump)
CMAKE_FORCE_C_COMPILER(${CC} GNU)
CMAKE_FORCE_CXX_COMPILER(${CXX} GNU)

# this is the file system root of the target
SET(CMAKE_FIND_ROOT_PATH /<SomeWhereElse>)

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
Modify ~/azure-iot-sdks/c/build_all/YourSystemName/build.sh (I only build amqp here)
    :
    :
build_amqp=ON
**build_http=OFF
build_mqtt=OFF**
use_wsio=OFF
**skip_unittests=ON**
build_python=OFF
build_javawrapper=OFF
run_valgrind=0
**build_folder=$build_root"/cmake/iotsdk_YourSystemName"**
make=true
**toolchainfile="YourSystemName-arm-elf.cmake"**
cmake_install_prefix=" "
**dont_use_uploadtoblob=ON**
    :
    :
cmake $toolchainfile $cmake_install_prefix -Drun_valgrind:BOOL=$run_valgrind -DcompileOption_C:STRING="$extracloptions" -Drun_e2e_tests:BOOL=$run_e2e_tests -Drun_longhaul_tests=$run_longhaul_tests -Duse_amqp:BOOL=$build_amqp -Duse_http:BOOL=$build_http -Duse_mqtt:BOOL=$build_mqtt -Duse_wsio:BOOL=$use_wsio -Dskip_unittests:BOOL=$skip_unittests -Dbuild_python:STRING=$build_python -Dbuild_javawrapper:BOOL=$build_javawrapper **-Ddont_use_uploadtoblob:BOOL=$dont_use_uploadtoblob** $build_root

If you got the same problem as Kevin, modify your azure-iot-sdks/c/certs.certs.c according to Mark's advice.

**Comment by sergiojx** [comment]
Thanks jjlee9. 
I have finally compiled  C SDK with openssl 1.0.2h. 
After tuning some buildroot configuration files for openssl1.0.2h compilation, It has been built  a SYSROOT directoy with all the required libraries and headers. 
Into my own cmake file I have:
SET(CMAKE_FIND_ROOT_PATH /home/embeddeddev/SPX_G25SDK/buildroot-at91/output/host/usr/arm-buildroot-linux-gnueabi/sysroot)

Now I have got into other issue: socket layer is not working =(
![sockererr](https://cloud.githubusercontent.com/assets/3307948/19934724/b61778a0-a0e5-11e6-8959-6d920e90610a.png)

**azure-iot-sdks/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:314 Failure: getaddrinfo failure -3.**

I appreciate any suggestion. 
Finally: is it curl mandatoy?
Best.

**Comment by sergiojx** [comment]
getaddrinfo failure -3 seems to be "Temporary failure in name resolution"

**Comment by sergiojx** [comment]
This problem is solved by adding some DNS servers. 
Add a resolv.conf file into /etc directory.
Its content can be(Google DNS servers):
nameserver 8.8.8.8 nameserver 8.8.4.4

**Comment by sergiojx** [comment]
HI
It almost works. I am trying iothub_client_sample_mqtt and now this is getting openssl issues.
![sslerr](https://cloud.githubusercontent.com/assets/3307948/19943709/9cd56db8-a106-11e6-9688-c87ec87382b3.png)

thanks in advance.
Best
