### ISSUE TITLE
[C][Linux][SimpleSample]Error when receiving messages from IoT Hub to device

### ISSUE THREAD

**Issue by donnerz** [Azure/azure-iot-sdks#508]
After changing the device connection string, I built the 'SimpleSample_AMQP' sample and run the code. Sending messages from the device to IoT Hub was OK that I could see the message data in Device Explorer. But when a message to device was sent in the Device Explorer, the Linux device reported the following repeated error:
- Error: Time:Fri Apr 22 11:34:46 2016 File:/home/pi/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
- Error: Time:Fri Apr 22 11:34:56 2016 File:/home/pi/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
- Error: Time:Fri Apr 22 11:35:06 2016 File:/home/pi/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed

I have tried the SimpleSample_Http and SimpleSample_Mqtt and got same errors.

**Comment by tameraw** [comment]
@donnerz - From the error you pasted, you are using the Serializer library which requires that you send a "valid" JSON formatted string to the device matching one of the commands supported in your sample.
For example: If you're using our Serializer simple sample, one of the commands you can send from DeviceExplorer would look like this:
{"Name":"TurnFanOff", "Parameters":{}}

Please update if this addresses your issue. Thanks.

**Comment by donnerz** [comment]
Yes, the message is well received and decoded at the device.

Sorry, I misunderstood that the Device Explorer might convert the to-device message into JSON format automatically.
