### ISSUE TITLE
Verify your environment section

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#51]
In the ‘Verify your environment’ section:

https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md 

It does mention that you’ll need to configure a valid IoT Hub device connection string, but it still seems to imply that you can build everything prior to doing that.  This appears to be correct that you can build everything, but since some testing happens after the build, it makes it appear that something failed since it says 4 tests have failed and stops.  This should be mentioned / noted as an expected result (if we are correct).

Another thing to mention is that you do have a note which talks about requiring a PROTON_PATH environment variable to be set to build certain things.  But if you’ve followed the ‘NuGet’ option for installing Proton then the user will probably not have defined this environment variable and the attempt to run the build will fail.  I’ve set the variable and created C:\Proton, but nothing exists in it but everything does seem to build correctly.  So this dependence for an environment variable that points to an empty directory is very confusing.

**Comment by dominicbetts** [comment]
@jtanner-msft thanks for the feedback.

I've made some changes to this document to address these issues. The changes will be checked in shortly.
