### ISSUE TITLE
no proxy support in Azure.Devices.Client

### ISSUE THREAD

**Issue by tokadu** [Azure/azure-iot-sdks#514]
Hi, we have a lot of customers with proxy authentication in their corp networks. 
It's only a slight change in the HttpClientHelper ctor to make this work:
`        public HttpClientHelper(
            Uri baseAddress,
            IAuthorizationHeaderProvider authenticationHeaderProvider,
            IDictionary<HttpStatusCode, Func<HttpResponseMessage, Task<Exception>>> defaultErrorMapping,
            TimeSpan timeout,
            Action<HttpClient> preRequestActionForAllRequests)
        {
            this.baseAddress = baseAddress;
            this.authenticationHeaderProvider = authenticationHeaderProvider;
            this.defaultErrorMapping =
                new ReadOnlyDictionary<HttpStatusCode, Func<HttpResponseMessage, Task<Exception>>>(defaultErrorMapping);

            // begin proxy authentication
            HttpClientHandler handler = null;
            string useProxy = ConfigurationManager.AppSettings["UseProxy"];
            if (!string.IsNullOrEmpty(useProxy) && useProxy.ToLower() == "true")
            {
                string proxy = ConfigurationManager.AppSettings["Proxy"];
                int proxyPort = Convert.ToInt32(ConfigurationManager.AppSettings["ProxyPort"]);
                string proxyUser = ConfigurationManager.AppSettings["ProxyUser"];
                string proxyPassword = ConfigurationManager.AppSettings["ProxyPassword"];

                handler = new HttpClientHandler { Proxy = new WebProxy(proxy, proxyPort) };
                handler.Proxy.Credentials = new NetworkCredential(proxyUser, proxyPassword);
            }

            this.httpClientObj = handler == null ? new HttpClient() : new HttpClient(handler);
            // end proxy authentication
            this.httpClientObj.BaseAddress = this.baseAddress;
            this.httpClientObj.Timeout = timeout;
            this.httpClientObj.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(CommonConstants.MediaTypeForDeviceManagementApis));
            this.httpClientObj.DefaultRequestHeaders.ExpectContinue = false; 
            if (preRequestActionForAllRequests != null)
            {
                preRequestActionForAllRequests(this.httpClientObj);
            }
        }`

**Comment by tameraw** [comment]
@tokadu - Thanks for submitting this issue. We'll consider adding this in a future release. However, we would happily accept contributions if you decide to submit a pull request for this.
Please refer to our guidelines here: https://github.com/Azure/azure-iot-sdks/blob/master/CONTRIBUTING.md

**Comment by tameraw** [comment]
Unfortunately, this is currently not a priority in our backlog. 
But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade).
Also feel free to contribute your solution via a Pull Request and we can review for a possible merge. Thanks.
