### ISSUE TITLE
[Python][Linux]build.sh script error

### ISSUE THREAD

**Issue by donnerz** [Azure/azure-iot-sdks#515]
After running the ~/azure-iot-sdks/python/build_all/linux/setup.sh and continued to run the ~/azure-iot-sdks/python/build_all/linux/build.sh script, I got the following error message and the iothub_client.so module could not be generated:
Linking C executable iothub_client_sample_mqtt
[100%] Built target iothub_client_sample_mqtt
virtual memory exhausted: Cannot allocate memory
python/test/CMakeFiles/iothub_client_mock.dir/build.make:54: recipe for target 'python/test/CMakeFiles/iothub_client_mock.dir/iothub_client_mock.cpp.o' failed
make[2]: *** [python/test/CMakeFiles/iothub_client_mock.dir/iothub_client_mock.cpp.o] Error 1
CMakeFiles/Makefile2:3288: recipe for target 'python/test/CMakeFiles/iothub_client_mock.dir/all' failed
make[1]: *** [python/test/CMakeFiles/iothub_client_mock.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library iothub_client.so
[100%] Built target iothub_client_python
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mregen** [comment]
@donnerz  is this Raspbian? We found an issue on some platforms the swap space must be increased: see #458

**Comment by mregen** [comment]
Ping @donnerz, just wondering if this is still an issue. We have reports in the meantime from other people who successfully build on Pi with the swap size increase, including myself.

**Comment by donnerz** [comment]
Yes, increasing the swap size works. Sorry for the late reply.
