### ISSUE TITLE
Rational behind Codes_SRS_WSIO_01_093 & Codes_SRS_WSIO_01_094

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#517]
Hi,

Could you explain the rational behind those two reqs ?

/* Codes_SRS_WSIO_01_093: [The members iface, token_limits, ssl_cert_filepath, ssl_private_key_filepath, ssl_private_key_password, ssl_ca_filepath, ssl_cipher_list and provided_client_ssl_ctx shall be set to NULL.] */

And  

/* Codes_SRS_WSIO_01_094: [No proxy support shall be implemented, thus setting http_proxy_address to NULL.] */

#108 have been added to backlog, so proxy issue will be addressed. Do you have a plan for openssl configuration to ?

Thanks

**Comment by tameraw** [comment]
@lmussier - Adding proxy support is added to our backlog. We'll update on a ETA soon. Thanks.
