### ISSUE TITLE
Link to the Node API Rereference is broken

### ISSUE THREAD

**Issue by pelikhan** [Azure/azure-iot-sdks#519]
On front page readme.md.

**Comment by tameraw** [comment]
@pelikhan - Thanks for submitting this issue. Can you please paste the broken link or a snapshot of which link in the readme.md file that's broken?. I tried all related "Node" links and they worked for me (under the master branch). Thanks.

**Comment by pierreca** [comment]
I'm guessing it's this page:
https://github.com/Azure/azure-iot-sdks/blob/master/node/device/readme.md

Fixed it. Thanks @pelikhan!
