### ISSUE TITLE
SDK has conflict in Web Class library project

### ISSUE THREAD

**Issue by rgrajan** [Azure/azure-iot-sdks#520]
I would like to create a wrapper around Azure IoT SDK, so i created Class Library Project using C#->Web->Class Library. When i try to use Azure SDK, i am not able compile due to some .NET platform compatibility issues. i cleaned up, created a new project and tried most of the possibilities to get rid of this error, but not able to solve. I have attached the warning message.
![azure-sdk-web-classlibrary-error](https://cloud.githubusercontent.com/assets/7380733/14848517/b0514566-0c8b-11e6-8ef4-bd9f24b708e5.PNG)

**Comment by markrad** [comment]
Hi @rgrajan,
Could you please send me a minimal buildable project that demonstrates your issue. I will research your issue. Thank you.

_Mark Radbourne MSFT_

**Comment by rgrajan** [comment]
Hi Mark,

Please find attached the sample, if you try to compile the project, you
will get an error.

Thanks,
Rajan R.G

**Comment by markrad** [comment]
@rgrajan 
Didn't seem to get the file. Can you put it somewhere public and post a link please?

**Comment by markrad** [comment]
Hi @rgrajan,

I have not been able to research this any further since I never received your sample. If you are still experiencing problems with this please reopen this issue.

Thank you.

_Mark Radbourne MSFT_
