### ISSUE TITLE
Windows 10 IoT Core and Raspberry Pi 3

### ISSUE THREAD

**Issue by ScottLiuGitHub** [Azure/azure-iot-sdks#522]
Hello, where can I find the sample code for Windows 10 IoT Core and Raspberry Pi 3 use the Azure pre-configured remote monitoring solution? Thanks!

**Comment by tameraw** [comment]
@ScottLiuGitHub - We currently don't have that. Currently in our backlog.

**Comment by ScottLiuGitHub** [comment]
Thanks!

**Comment by tameraw** [comment]
Unfortunately, this is currently not a priority in our backlog. 
But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade).
