### ISSUE TITLE
iothub_client_sample.py failed to assign new properties to message

### ISSUE THREAD

**Issue by Laurachu** [Azure/azure-iot-sdks#526]
Hi,

I need to send Python device messages with customized properties to IoT Hub. I tried to run the sample code iothub_client_sample.py and found the following code in method "iothub_client_sample_run()" failed to add the properties to the message. 
...
# optional: assign properties
                prop_map = message.properties()
                prop_text = "PropMsg_%d" % i
                prop_map.add("Property", prop_text)
...
I tried prop_map.add_or_update("Property", prop_text). It failed too.

Can someone help me with this?

Thank you in advance!
Laura

**Comment by mregen** [comment]
@Laurachu thanks for your comment, looks like you found a bug in the Python binding. The extension creates a copy of the properties which is modified but the message property itself remains unchanged. I'll let you know when there is a fix available.
Thanks,
Martin

**Comment by Laurachu** [comment]
Thank you Martin!

**Comment by mregen** [comment]
@Laurachu: Hi Laura, a fix is now in develop 57f22e2cf712b84f36ec2cb4e8b0a21e21c23301.
Please let me know if you issue is resolved.
Thanks,
Martin

**Comment by Laurachu** [comment]
I built the latest develop code and it worked. The message properties were added with add_or_update("propertyKey", "propertyValue").

Thank you very much Martin!
Laura

**Comment by mregen** [comment]
Thanks @Laurachu, please keep sending the feedback!
