### ISSUE TITLE
[Python][Linux]build.sh error

### ISSUE THREAD

**Issue by serenagrl** [Azure/azure-iot-sdks#529]
Running ./build.sh --build-python 3.5 gives the following error:

CMake Error at /usr/share/cmake-3.0/Modules/FindBoost.cmake:1198 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path: /usr/include

  Could not fine the following Boost libraries

  boost_python-py35
  
  No Boost libraries were found. You may need to set BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT to the locations of Boost.

I'm using Raspbian Jessie on Raspberry Pi 2.

Thanks.

**Comment by mregen** [comment]
@serenagrl how did you install 3.5? Is it already part of the official Raspbian distribution?
I know Python 3.4 works on Raspbian. For 3.5 it looks like the boost-python 3.5 library is still missing, There are Linux distribution which don't include latest boost-python 3.5 libraries yet.

**Comment by serenagrl** [comment]
Hi,

It did not come with the distribution. I downloaded Python 3.5.1, then I built and installed it on Raspbian manually. I have also installed libboost-python-dev as well.

Hugs,
Serena

**Comment by mregen** [comment]
Hi @serenagrl, the default boost-python-dev package doesn't have the 3.5 libs yet, or cmake had not complained, I think that's the problem..
I can only recommend to stick with 3.4 in the meantime, or, if you are up for it, 
download the latest and greatest boost source and build the missing boost-python 3.5 library yourself.

**Comment by mregen** [comment]
@serenagrl, please reopen if you have further comments or questions.

**Comment by serenagrl** [comment]
Hi,

I think I may have solved it. In azure-iot-sdks/python/device/iothub_client_python/CMakeLists.txt

Change Line 41: 
find_package(Boost COMPONENTS "python-py${boost_python}" REQUIRED)

to
find_package(Boost COMPONENTS "python" REQUIRED)

Everything should compile and build.

Hope it helps.
