### ISSUE TITLE
IoT Hub Creation - Incorrect Graphic

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#53]
The graphic shown when creating a new IoT Hub is incorrect. In the document it says *IoT Hub*. On  the web site it now says *Azure IoT Hub*

**Comment by msjaosborn** [comment]
Hi @markrad, both usages (*Azure IoT Hub* and *IoT Hub*) are correct.  Generally we use *Azure IoT Hub* on first mention then the shortened version subsequently.

**Comment by markrad** [comment]
It is not text. It is a screenshot of the web page. Apparently the webpage graphic has been modified since you took the screen shot. A minor issue granted. See the section _Create an IoT hub_ step 2. embedded screenshot. This no longer reflects the actual webpage. First picture below is how it looks now. The second is from your document.

![webpage](https://cloud.githubusercontent.com/assets/12402055/10435338/32aa1140-70d4-11e5-8237-3867007e165e.PNG)
![docshot](https://cloud.githubusercontent.com/assets/12402055/10435340/36f17f0e-70d4-11e5-8686-127880502a39.png)

**Comment by msjaosborn** [comment]
Got it.  Thanks for the clarification.

**Comment by CarlosAlayo** [comment]
Thank you for the feedback. We will be updating the docs with the new graphics shortly.

**Comment by CarlosAlayo** [comment]
We have corrected the problem. Thank you for letting us know about this issue.
