### ISSUE TITLE
[C] Issue with IoTHubMessage_GetByteArray, garbage data

### ISSUE THREAD

**Issue by mboujonnier** [Azure/azure-iot-sdks#533]
Hi,

I have an Azure Function which regurlaryl sends messages to the device.
I'm using `IoTHubMessage_GetByteArray` to consume the JSON message (see issue #532, why I'm not using `IoTHubMessage_GetString') and quite often the buffer received has some garbage characters at the end.

```
char * tmp_buffer;
size_t size;

	
    if (IoTHubMessage_GetByteArray(message, (const unsigned char**)&tmp_buffer, &size) != IOTHUB_MESSAGE_OK)
    {
        fprintf(stderr, "Unable to retrieve the message data\r\n");
		return IOTHUBMESSAGE_ACCEPTED;
    }
    else
    {
        fprintf(stdout, "Received Command <<<%s>>>, <<<%.*s>>> & Size=%d\r\n", tmp_buffer, (int)size, tmp_buffer, (int)size);
    }
```

and usually **after** the `size` nth character there are some ascii or not characters displayed.

As I understood that the SDK is modifying the char * pointer or at least copying the incoming buffer, not sure when this garbage data comes from.

Thanks

**Comment by tameraw** [comment]
@mboujonnier - Thanks for submitting this issue. We'll investigate it.

**Comment by mboujonnier** [comment]
FYI, my ugly temporary patch:

```
IoTHubMessage_GetByteArray(message, (const unsigned char**)&tmp_buffer, &size)
//ugly patch
char* substr = (char*) malloc(size*sizeof(char));
memset(substr, 	0, size*sizeof(char));
sprintf(substr, "%.*s", (int)size, tmp_buffer);
```

**Comment by anhashia** [comment]
Just follow the **sample** at \azure-iot-sdks\c\iothub_client\samples\iothub_client_sample_http\**iothub_client_sample_http.c
**
and make following change to make sure that formatting is correct in your client application
fprintf(stdout, "Received Message [%d] with Data <<<%.*s>>> & Size=%d\r\n", *counter, (int)size,tmp_buffer, (int)size);

**Comment by mboujonnier** [comment]
yes I modified your sample to show that there is garbage at the end of the buffer, else both printf would be equivalent. So let's assume you don't printf the content of the buffer but pass it to any parser, the parser will fails due to the garbage.

That's why I needed to clean the buffer first using the ugly patch.

**Comment by anhashia** [comment]
IoTHubMessage_GetByteArray doesn't return NULL terminated string. You will have to use return parameter size to determine size of the buffer. Trying to read beyond size of the buffer will result in garbage.

**Comment by mboujonnier** [comment]
Hi. Ok that's fine but should be clearly stated in the doc and API, else that's a quite dangerous piece of code. 

So, how to use IoTHubMessage_GetString to avoid this risk ?

**Comment by anhashia** [comment]
It is covered under http://azure.github.io/azure-iot-sdks/c/api_reference/iothub__message_8h.html.  Below is the documentation on this
Fetches a **pointer** and size for the data associated with the IoT hub message handle
**Parameters**
iotHubMessageHandle: Handle to the message.
buffer: Pointer to the memory location where the pointer to the buffer will be written.
**size** : The size of the buffer will be written to this address. 

For `IoTHubMessage_GetString  `use sample located at \azure-iot-sdks\c\iothub_client\samples\iothub_client_sample_amqp\iothub_client_sample_amqp.c for your reference.
Your  message type has to be  IOTHUBMESSAGE_STRING  to use this function

**Comment by mboujonnier** [comment]
Yeah yeah but as you wrote "Trying to read beyond size of the buffer will result in garbage. " can be helpful :) That was not obvious.

As those Strign emssage are sent from the cloud and not a device, how do you create a  IOTHUBMESSAGE_STRING using the node.js Service SDK ? (https://github.com/Azure/azure-iot-sdks/blob/master/node/common/core/lib/message.js)

**Comment by mboujonnier** [comment]
Ah ok just read issue #532, that's in the backlog.
