### ISSUE TITLE
Device explorer enhancement request

### ISSUE THREAD

**Issue by srini1978** [Azure/azure-iot-sdks#534]
On the message to device tab, can we make a tweak to the ui so as to provide the messages as parameterized values rather than allowing a free form text?

For example 👍 
Message :

 Parameter 1 name :  value 👍 
Parameter 2 name :  value :

And then the tool can create a json out of these values and submit them to iot hub.

**Comment by tameraw** [comment]
@srini1978 - Thanks for submitting this issue. We'll evaluate your request.

**Comment by tameraw** [comment]
@srini1978 -
Unfortunately, this is currently not a priority in our backlog. 
But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade).
