### ISSUE TITLE
[Java Device Client] AMQPS executes callback several times when resending messages

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdks#538]
If a message fails to be sent by the method sendMessages() in AmqpsTransport.java the message is added again to the waiting list and the callback is executed anyway, when it's sent again (with or without success) the callback executes again.

It would be useful to be able to configure if the message should be added to the waiting list after a failed attempt, as executing the callback on each attempt could have unwanted consequences.

Also it could be considered that after a failure / exception sendMessages() method, all messages in waiting list execute their callback with "ERROR" result and the waiting list is cleared.

**Comment by iluican** [comment]
Hello,

We are about to release (by EOD today) a new version of the Java SDK which fixes the problem you encountered. The callback will only be executed when a response is received from the server.

I will close this issue. Please feel free to open a new one if you have further problems.

Thank you,
Ilie.
