### ISSUE TITLE
[Java Device Client] Add a method to send messages synchronously or with timeout

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdks#539]
In some applications and environments it could be useful to be able to send messages synchronously

**Comment by tameraw** [comment]
@pizerg - Thanks for submitting this request. We'll evaluate adding this request to our backlog.

**Comment by tameraw** [comment]
@pizerg - We're currently working on enhancing the retry logic and connection error reporting. Through that effort, you should be able to achieve the scenario you asked for.
A link to the GitHub project is here:
https://github.com/Azure/azure-iot-sdks/projects/2
