### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#54]
In Create an IoT Hub the link (in italics) in this line is broken:
◦In the Resource group box, create a new resource group, or select and existing one. For more information, see *Using resource groups to manage your Azure resources*.

**Comment by andrew-buckley** [comment]
Hi, @markrad. Thank you for opening this issue. We are looking into that now.

**Comment by andrew-buckley** [comment]
@markrad, the updated doc is now in the master branch.
