### ISSUE TITLE
[Java Device Client] AMQPS, quite long delay before detecting network disconnection

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdks#540]
We have an app that sends messages using AMQPS protocol through IoTHub following this steps:

1) Send message with callback + context
2) Wait() on context item
3) Recover result from the context

Our callback basically sets IotHubStatusCode status in a parameter of the context and calls context.notify() to enable our app to go from 2) to 3) and be able to process new messages or deal with the ones that return status = ERROR.

The problem appears when the connection drops, if the system lose internet connection and sends a message, instead of geting a quick callback execution with status = ERROR the app blocks on the following line (AmqpsTransport.java:212):

`Boolean result = futureStatus.get();`

So even being disconnected is able to get a "deliveryHash" (see AmqpsIotHubConnection.java scheduleSend(...) and send(...) methods) and waits to get the acknowledge from IoTHub. After a very long time (> 5 minutes) futureStatus.get() finally returns and the status of AMQPS transport changes to CRASH, this also happens some seconds after internet connection is restablished.

It would useful to have a configurable timeout for this or if the system actually prevents this situation to happen when we try to send a message and the internet connection is down

**Comment by zolvarga** [comment]
Hi pizerg,

We already updated the Java device client code in develop branch. We are planning to release it today to master, so you are going to able to get it from the master branch after the release is done.
Please try your code with the new release. That should fix the issue. 

Thanks,
Zoltan

**Comment by tameraw** [comment]
@pizerg - As we're having a release today, I'll go ahead and close this issue. And please feel free to reopen if still having problems after testing out the code from our new release.
