### ISSUE TITLE
[Question][Java] Service SDK, how to listen to incoming devices messages ?

### ISSUE THREAD

**Issue by shazz** [Azure/azure-iot-sdks#541]
Hi,

I read the APIs multiple times, check the Java Service SDK examples, but I did not find how to listen to devices messages from the Service SDK (I only found the feedback receiver). Is it on purpose ? And the Event hub interface of the IoT Hub should be used ?

Thanks

**Comment by iluican** [comment]
Hello,

This is currently not supported. We have a task to implement it in the near future.
Thank you,
Ilie.

**Comment by tameraw** [comment]
Unfortunately, this is currently not a priority in our backlog. 
But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade).
