### ISSUE TITLE
No get feedback from IOT hub in particular time

### ISSUE THREAD

**Issue by vishalk00** [Azure/azure-iot-sdks#555]
Hello,

I have use **IOT hub** to send message to my device, it is basically display device which show general text message. What is doing now when I send message to hub and call feedback methods of **SDK** for getting feedback of my message but unfortunately it takes long time then excepted. Due to this thread expired which call feedback method  and not got any feedback from hub. The reason behind the thread expired is the feedback method read all the messages from queue unneeded Like  if queue had 50 unread feedback and my message feedback comes in 51, so it read one by one. So as per condition my question is there is any methods in SDK which read only my message feedback for hub?.

Thanks,

**Comment by rajeevmv** [comment]
IoT Hub tries to batch feedback responses by waiting for 15 seconds or 64 feedbacks. Meeting either condition will cause it to send the feedback response back to the Service Client.

There are no APIs to receive feedback specific to individual messages.

**Comment by vishalk00** [comment]
Azure service API have any method which give feedback of message according to date filter?

**Comment by vishalk00** [comment]
Is there any way through API  to get feedback of message(sent on HUB) less then 15 second?

**Comment by rajeevmv** [comment]
There are no feedback APIs that accept a date filter.

Currently, the only way to receive feedback under 15 seconds is to receive 64 feedbacks in quick succession.

**Comment by rajeevmv** [comment]
I am closing this issue. Please reopen in case you have more questions.

**Comment by krishnabatham** [comment]
I am facing same issue with feedback receiver. It will not return feedback on as mention(15 seconds is to receive 64 feedbacks )
For test it I have created a console simulator application.That app send/receiver message to hub.
This app continuously send message to hub and concurrently receive messages from hub.To increase load on hub I am running 4 instance of that application. 
Feedback receiver also work continuously for getting feedback on message.But I am not getting feedback in 15 sec or 64 feedback message. Some time it take 30 sec ,some time it take 40-100 sec. So it seems that it not receive feedback in any specific time period or specific amount of message.

**Comment by frode** [comment]
I have experienced the same, it will not always give a feedback within the 15 seconds. Isn't this still a valid issue?
