### ISSUE TITLE
Sample C Code For Intel Edison Receiving Azure Messages

### ISSUE THREAD

**Issue by cnvery** [Azure/azure-iot-sdks#558]
Hi,

I have successfully run _iothub_client_sample_amqp_ sample on sending messages from Intel Edison to Azure Cloud.

Now, I wish to receive Azure Cloud message on Intel Edison.

May I know is there any sample code for receiving Azure Cloud messages on Intel Edison?

Thanks in advance!

**Comment by chrit-msft** [comment]
The client sample already has the callback code in it for receiving messages.  Here is the code snippet from the sample that sets up the callback.
```C
/* Setting Message call back, so we can receive Commands. */ 
    if (IoTHubClient_SetMessageCallback(iotHubClientHandle, ReceiveMessageCallback, &receiveContext) != IOTHUB_CLIENT_OK) 
    { 
        (void)printf("ERROR: IoTHubClient_SetMessageCallback..........FAILED!\r\n"); 
    } 
```

**Comment by chrit-msft** [comment]
Closing this issue. If still having problems, please let us know.
