### ISSUE TITLE
Build_paho.sh execution is failing on Debian desktop with C libraries

### ISSUE THREAD

**Issue by v-pravek** [Azure/azure-iot-sdks#56]
Followed following document on Debian8.1 desktop. 
https://github.com/Azure/azure-iot-sdks/blob/master/doc/iotcertification/iot_certification_linux_c/iot_certification_linux_c.md

After successful build_proton.sh execution ./azure-iot-sdks/c/build_all/linux/build_paho.sh is failing as shown in screenshot.

![build_paho-failure](https://cloud.githubusercontent.com/assets/13991281/10426314/939384be-70fc-11e5-8c6a-a6c6e3aeec6c.png)

**Comment by aribeironovaes** [comment]
Thanks for letting us know, I will take a look into that. 
From your logs it seems that you don't have open ssl installed on the machine. 
We will work to have this added to the script. 
Meanwhile can you install openssl on your linux Machine? and try the build_paho.sh script again?

Thanks, 

Angelo Ribeiro.

**Comment by v-pravek** [comment]
root@debian:~# openssl version
OpenSSL 1.0.1k 8 Jan 2015
root@debian:~#

I checked OpeSSL is installed. Please let me know if some other version need to be installed.

**Comment by xtrsys** [comment]
Same issue on Raspiban.

**Comment by aribeironovaes** [comment]
I'm taking a look (Setting up the Debian Environment, I had Ubuntu). 

Meanwhile what you can do 2 things to unblock yourselves:
1-Search if with your installation of OpenSSL you have the Include folder and where is it. Basically Paho needs to know the location of OpenSSL Include files to build; You can check details of installation with Paho;
2-Try to download and install OpenSSL from cloning OpenSSL Github and following their instruction on the installation. This will most likely include the OpenSSL Include folder in a way that Paho can see it. 

Again, I'm setting up here on my environment as well so I can help you more directly. 
Please, post here if you could find a solution of the problem. 

Thanks for reporting it, 

Angelo Ribeiro.

**Comment by aribeironovaes** [comment]
So, I could repro your issue with a Docker Image of Debian. 

Can you please, run: sudo apt-get install libssl-dev  and run build_paho.sh and let me know if this fixes your problem?

Thanks, 

Angelo Ribeiro.

**Comment by aribeironovaes** [comment]
Hi @v-pravek and @xtrsys, 

Just want to check with you if it got solved with the steps above so we can close this issue. 

Thanks, 

Angelo Ribiero.

**Comment by v-pravek** [comment]
build_paho.sh execution was successful after running "sudo apt-get install libssl-dev ". Thanks for your help. Closing this issue now.
