### ISSUE TITLE
Will there be a Python package for the Azure IOT Python SDK?

### ISSUE THREAD

**Issue by najibninaba** [Azure/azure-iot-sdks#560]
Hi,

There is already a Python package for the Azure SDK. Wondering if there is going to be one for the Azure IoT Python SDK in the roadmap? Thank you!

Best Regards,
-najib

**Comment by zerox1212** [comment]
I'm basically looking for the same thing.

It's a major pain to have to build the .PYD myself. I had to download the entire Visual Studio suite to run build.cmd, which took about 10 seconds.

Is there at least a way to reuse the PYD on another PC? The way I understand it is that the only way to get the python bindings to work is run build.cmd on that specific machine.

I tried to move PYD to another PC with the same version of Python (because this PC is on a domain and I can't install Visual Studio) and it doesn't work.

**Comment by tameraw** [comment]
@najibninaba & @zerox1212 - Very reasonable ask.
We have captured this in our backlog to provide a package for the Python SDK and will update you once available. Thanks.

**Comment by zerox1212** [comment]
In the mean time. Can you tell me if it's possible to move the .PYD to another computer and use it?

**Comment by mregen** [comment]
@zerox1212 the pyd *should* work on another PC, if you use exactly the same Python version with the same architecture. e.g. build for Python 2.7.11, 64bit on one machine, then you can also use it on another one with exactly the same Python version. 

A .pyd for Python 2.7 does not work with Python 3.4 and vice versa. 
Neither does a 32bit .pyd work with a 64 bit Python and vice versa. Makes sense?

If the .pyd still doesn't work on another box a VC runtime component might be missing, boost-python is linked as static lib. I need to check if there is a dependency and get back to you.

**Comment by zerox1212** [comment]
>If the .pyd still doesn't work on another box a VC runtime component might be missing, boost-python is linked as static lib. I need to check if there is a dependency and get back to you.

In other words, the other PC also needs the 2015 redistributables? When I moved the PYD it didn't work even though it's the same Python version (32bit). However the PC probably didn't have the same libs.

**Comment by zerox1212** [comment]
A possible easy work around would be to just include the PYD files for the major python releases and make a note that the redistributables are required.

**Comment by mregen** [comment]
@zerox1212 , thanks for testing! 
Its now on the backlog and yes indeed the better solution is to provide a known working.pyd somehow, if we limit to windows, 2.7, 3.4, each 32bit and 64 bit, it might still be manageable. Your feedback has been valuable, we'll be looking for a good solution. Thanks!

**Comment by najibninaba** [comment]
@tameraw & @mregen,

With regards to the Python package, I'm looking for a ready to use package for Linux, particularly Ubuntu without having to rebuild the SDK each time. Would the scope be simpler and focused if we could have a .DEB package instead? This would be similar to how Visual Studio Code supports the different OSes, as they have a Windows installer, .DEB package for Ubuntu and .RPM package for RHEL/CentOS. Thanks!

-najib

**Comment by tameraw** [comment]
@najibninaba - We'll look at providing such package. We'd also happily accept contributions.

**Comment by xscript** [comment]
I noticed that current Azure-IoT-SDK only has device SDK for Python. Do you guys have plans to provide  service SDK for Python? If so, any timeline on this?

**Comment by dcristoloveanu** [comment]
@xscript Hi, we have already implemented the C portion for the service SDK so what is left is the Python binding for it. This is not currently slotted for August, so if you would like to take a stab at adding the bindings via a PR we would be more than happy to help you review and merge that in.

/Dan

**Comment by jtanner-msft** [comment]
We're looking again into adding the prebuilt .PYD and .SO as installable packages for Windows and Linux platforms.  Once I have a further update on where we stand I will let you know.

**Comment by mregen** [comment]
Hello early adopters. For windows there is a Python wheel available for testing. All Python windows flavors should work.  Please report all issues you may find.

> pip install -i https://testpypi.python.org/pypi iothub-client --upgrade

**Comment by zerox1212** [comment]
Thanks for the update. I will test this and report back if I find any issues.

**Comment by mregen** [comment]
The first official windows wheels based on the 1.0.16 libs have been released on pypi:

> pip install iothub-client --upgrade

Please report any issues

**Comment by zerox1212** [comment]
I just installed via pip for testing.

FYI you should update https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/python-devbox-setup.md with the pip option at the top.

**Comment by zerox1212** [comment]
Looks good. I tested it on Windows 7 with Python 3.4.4 and it worked without issue. Now that docs are updated I think this issue can be closed.

Thanks.

**Comment by tameraw** [comment]
@zerox1212 - Thanks for the update!

**Comment by catan85** [comment]
When will it be available for linux?
