### ISSUE TITLE
Connection issue in Wince 2013

### ISSUE THREAD

**Issue by kavyadc8** [Azure/azure-iot-sdks#563]
Hi,

I am trying to run simplesample_http application on WEC2013 by following below link,
https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/wince2013-toradex-module-c.md .

When I run application on Wince 2013 i get "connection failed" error. 
What could be the reason for this issue and how I can solve this issue?

Thanks in advance.

**Comment by anhashia** [comment]
Hi @kavyadc8 
Latest code for WEC 2013 has some build issues. Those are being investigated. If you are able to build and run the sample then the area where you may be probably failing is around SSL handshake as that would be first step for making connection to Azure IoT Hub over HTTPS.

Azure IoT Hub would use **HTTPS** connection (Port 443). Make sure SSL handshake is succeeding by looking at the network trace. WEC 2013 client authentication of Server certificate should succeed to move forward in the connection process.

**Comment by anhashia** [comment]
Closing this. If still having issues, please let us know
