### ISSUE TITLE
Archive files do not include submodules

### ISSUE THREAD

**Issue by augiekim** [Azure/azure-iot-sdks#564]
Archive files such as https://github.com/Azure/azure-iot-sdks/archive/2016-05-06.tar.gz do not include submodules. Is there anyway to build the c project without submodules? I want to build it without git dependency.

**Comment by tameraw** [comment]
@augiekim - Currently, if you want to avoid git, you would have to either use the corresponding packages (ex: NuGet, apt-get,...etc.), or you can download the zip for each of the submodules and place it in the proper directory in your local repo.

**Comment by augiekim** [comment]
Thanks!!
