### ISSUE TITLE
An error or a warning or just ignore it =>git: 'submodule' is not a git command. See 'git --help'

### ISSUE THREAD

**Issue by Maximus1129** [Azure/azure-iot-sdks#565]
when I was trying to run "git clone --recursive https://github.com/Azure/azure-iot-sdks.git" form the tutorial of "https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/yocto-intel-edison-c.md". It came with following as you could see below. I do not know if it is a warning or it is an error? Anyone have idea how to deal with it? Or just ignore it?
Thank in advance.
git: 'submodule' is not a git command. See 'git --help'.

**Comment by markrad** [comment]
Hi @Maximus1129,

Apparently the version of git available to the Edison from its opkg repositories is a version known as "git light". This version omits some of the less commonly used commands and, unfortunately, submodule is one of those. I am looking for a viable circumvention.

_Mark Radbourne MSFT_

**Comment by Maximus1129** [comment]
@markrad I found that this link may be helpful, and I am trying to solve the problelm by following this link to update my nodejs which is 0.12... version. And I will let you know if it works. https://github.com/creationix/nvm

**Comment by anhashia** [comment]
Linking to GitHub issue [(https://github.com/Azure/azure-iot-sdks/issues/562)]

**Comment by anhashia** [comment]
Hi @Maximus1129 
If you still have issue please re-open it.
