### ISSUE TITLE
the destination include path from sudo make install is wrong

### ISSUE THREAD

**Issue by augiekim** [Azure/azure-iot-sdks#567]
I used "sudo make install" from ~/cmake directory to install library files and headers into /usr/lib and /usr/include of my Linux machine. But this sudo make install copies every header into /usr/include/azureiot. 

Since, the paths in the header files are like this,
#include "azure_c_shared_utility/platform.h"

these files should be copied under /usr/lib/azure_c_shared_utility and other directories.

Could you let me know what is the right way to install library files and headers on the Linux system?

**Comment by jebrando** [comment]
I changed the location to be /usr/include/azureiot/azure_c_shared_utility/*
