### ISSUE TITLE
About certification on Android system (with Java Device SDK)

### ISSUE THREAD

**Issue by yphuangms** [Azure/azure-iot-sdks#569]
There exists certification example and guidelines for Linux, but none for Android. 

Since Android uses it's own Java virtual machine (not standard JRE), we created an Android app and imported the Java device SDK (.jar) and in this Android app we integrated the sample code SentEvent and Handle-Messages. The result confirmed that both device to cloud (SentEvent) and cloud to device (Handle-Message) worked well on our target IoT device running Android 6.0.
The log could be collected by using logcat from adb shell console. 

We would like to know if it's possible to use logcat output messages as the log file for Azure IoT device (Java) for Android certification.
Is there any guideline or procedure for IoT certification for Android system?

Thanks!
YP

**Comment by ashokkhurana** [comment]
@yphuangms , yes we currently don't have a certification instructions for Android platform using Java. We are working on same and will be releasing it very soon. The instructions will have full details of what we would need to have a device as Azure IoT certified. To become an Azure IoT certified partner, we would also required you to create a certification request at https://iotcert.cloudapp.net . This way we can track you in our certification system and will send you the certification instructions, program benefits and other useful information about certification program.

**Comment by yphuangms** [comment]
Thanks for the information.
We'll issue a certification request first, and wait for the release of Android certification instructions.
