### ISSUE TITLE
Errors using iothub-explorer on Ubuntu 1504

### ISSUE THREAD

**Issue by kingliantop** [Azure/azure-iot-sdks#571]
Hi guys,

I installed iothub-explorer on Ubunu1404 as following:

$ sudo npm install -g iothub-explorer

While when I use it to create a device, it showed errors like following:

/usr/bin/env: node: No such file or directory
No command 'create' found, did you mean:
 Command 'pcreate' from package 'pbuilder-scripts' (universe)
 Command 'pcreate' from package 'python-pyramid' (universe)
create: command not found

Any comments?

**Comment by pierreca** [comment]
can you provide a console log of what is happening? also, what version of node do you have running? (to find out, just type node --version in the console)

**Comment by pierreca** [comment]
closing due to lack of response... feel free to reopen if needed.
