### ISSUE TITLE
Declare `DEFINE_ENUM_STRINGS` in `iothub_client_ll.c`

### ISSUE THREAD

**Issue by avranju** [Azure/azure-iot-sdks#573]
Right now, if someone attempts to generate a string version of an instance of the enum `IOTHUB_CLIENT_CONFIRMATION_RESULT` using `ENUM_TO_STRING` then we get linker errors because the functions that implement the string conversion don't exist. Currently this can be worked around by writing the following in a C file (as in fact the samples do):

```c
DEFINE_ENUM_STRINGS(IOTHUB_CLIENT_CONFIRMATION_RESULT, IOTHUB_CLIENT_CONFIRMATION_RESULT_VALUES);
```

It might be a good idea to have this declaration in `iothub_client_ll.c` instead just the way many of the other enumerations are declared.

**Comment by jtanner-msft** [comment]
Thanks for the suggestion.  I'll see if we can get this updated.

**Comment by jtanner-msft** [comment]
Changes have been merged into Develop branch. Closing request.
