### ISSUE TITLE
Problem with device registration and dmpreview

### ISSUE THREAD

**Issue by ncamino** [Azure/azure-iot-sdks#575]
I created an Ubuntu VM on Azure. I pulled dmpreview down and built the C simple example.
I created a Windows VM and installed the device manager
I created an IOTHub and set the Device Management option
I got the device key from the Device Manager
When I run the device I get all the way down where the device starts to run. It reports that it is waiting for the registration. No errors are displayed. However, Device Manager gets a device registration request. IoTHub is not showing any messages coming in.

**Comment by damonbarry** [comment]
By "Device Manager" I assume you are referring to the DeviceExplorer.exe tool?  DeviceExplorer has not been updated to support the Device Management capabilities of IoT Hub (yet).  Have you tried running the [C#](https://github.com/Azure/azure-iot-sdks/tree/dmpreview/csharp/service) or [Node.js](https://github.com/Azure/azure-iot-sdks/tree/dmpreview/node/service) samples?

**Comment by ncamino** [comment]
I went in and built the C# sample device. It does seem to register with IoT Hub. I see that IoT Hub create observer requests which the device responds to. I then built Device Explorer but was not seeing any updates. I had concluded that Device Explorer was not wired to OMA DM but rather to just IoT messages. That seems to be the case from your comment. I'm not sure why the C simple device on Ubuntu is not registering though.

**Comment by ncamino** [comment]
What's the timeline for updating Device Explorer. It would also be desirable to know how to get to the OMA DM information in IoT Hub so we can create our own clients.

**Comment by damonbarry** [comment]
We do plan to update Device Explorer although it's a little farther down the list, especially because we have DM support in [iothub-explorer](https://github.com/Azure/azure-iot-sdks/tree/dmpreview/tools/iothub-explorer), which is a cross-platform CLI.

**Comment by ncamino** [comment]
Is there documentation on the DM implementation in IoT Hub? When a device registers using the OMA calls, what does IoT Hub do with that information? The iohub-explorer monitors events through the event hub. Are the OMA messages translated into events? I'm trying to get a handle on what the overall architecture/plan is for device management.

**Comment by damonbarry** [comment]
There's more information [here](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-device-management-overview/), but after the device connects to the IoT Hub and registers, the service sends an observe request for each of the resources that were reported (we call this "auto-sync"). Once that's done, the device will notify the service if there any resource values change. Notifies happen on a schedule, e.g. not any more frequently than once in 5 minutes, and not any less frequently than once in 5 hours (I think those are the values we currently use by default--we'll give the customer more control over the schedule in the future). So once the device is registered it has two jobs: (1) end out resource notifications on a schedule, and (2) respond to any job requests that come in (e.g., deep read, firmware update, etc.). The user interacts with the service in two ways: (1) Inspecting the device twin from the Registry to see the values of properties, and (2) scheduling jobs like deep read or firmware update.

Currently DM stuff happens on its own channel and does not use event hub or anything else from the messaging (telemetry) side of things. But expect tighter integration in the future.
