### ISSUE TITLE
Microsoft.Azure.Devices.Client version 1.0.8 references DotNetty 3.0.0, but nuspec defines only 0.2.3

### ISSUE THREAD

**Issue by ktos** [Azure/azure-iot-sdks#578]
The available from yesterday version 1.0.8 of C# Microsoft.Azure.Devices.Client from NuGet references (for .NET 4.5) DotNetty.Codecs.Mqtt version 3.0.0 in assembly itself, but in nuspec file there is 0.2.3 version being defined as dependency, which causes System.IO.FileLoadException:

> Could not load file or assembly 'DotNetty.Codecs.Mqtt, Version=0.3.0.0, Culture=neutral, 
> PublicKeyToken=e7a0210a354f294a' or one of its dependencies. The located assembly's manifest 
> definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

The [nuspec](https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/NuGet/Microsoft.Azure.Devices.Client.nuspec) says:
`<dependency id="DotNetty.Codecs.Mqtt-signed" version="0.2.3" />`

While both [packages.config](https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/Microsoft.Azure.Devices.Client/packages.config#L4) and [csproj](https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/Microsoft.Azure.Devices.Client/Microsoft.Azure.Devices.Client.csproj#L69) say about 0.3.0.

This caused a huge headache today in my live demo, as I was presenting the usage of Azure + IoT :-)

**Comment by rajeevmv** [comment]
Please accept our apologies for releasing an unusable version of the Microsoft.Azure.Devices.Client NuGet package. 

We have pulled the offending version (1.0.8) and released a newer version 1.0.9 with the appropriate NuGet spec dependencies.

**Comment by rajeevmv** [comment]
Closing this issue since it has been resolved.
