### ISSUE TITLE
Getting deviceId with python

### ISSUE THREAD

**Issue by lmouhib** [Azure/azure-iot-sdks#579]
How can use the python client for get the device id ?? Thanks

**Comment by mregen** [comment]
@lmouhib could you explain what you would like to do?
The Python client gets the device id as part of the connection string which you get from  [iothub-explorer](https://github.com/Azure/azure-iot-sdks/blob/develop/doc/manage_iot_hub.md) utility.

**Comment by lmouhib** [comment]
I wan to get the device id, without going through parsing the connection string. In the NodeJs library there is a function that allows to get the device id, I was wondering if there is such function in python. The function in nodejs just parse the supplied the connection string, but it comes as part of the library.

**Comment by mregen** [comment]
@lmouhib Sorry, but the Python SDK is a straight binding to the C SDK, so reading back the deviceid is not supported.

**Comment by lmouhib** [comment]
Okay, thanks for your help!
