### ISSUE TITLE
DeviceExplorer - Where is it after install?

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#58]
The documentation offers a pre-built version of DeviceExplorer which I have downloaded and installed.  Everything seemed to go fine by following this instruction:
Download a pre-built version of the Device Explorer application

A pre-built version of the Device Explorer application for Windows can be downloaded by clicking on this link DeviceExplorer.msi.

However, now that it's downloaded I do not have any idea of where (if anyplace) in the start menu the utility is located.  Also I did not see any shortcut created on my desktop either.  Even if neither of these happen, we should at least provide the default path to where the .exe can be found.

**Comment by jtanner-msft** [comment]
Default path appears to be this location: C:\Program Files (x86)\Microsoft\DeviceExplorer

**Comment by CarlosAlayo** [comment]
You are correct. This information is missing from the documentation. We have corrected the problem. Thank you for the feedback.
