### ISSUE TITLE
AMQP transport authentication timed out. -> [CLOSE]* {} - Release 2016-05-20 branch - C library

### ISSUE THREAD

**Issue by rajvael** [Azure/azure-iot-sdks#580]
Hi, 
 I am facing below error while sending message to iot using AMQP. After very long time I planned to migrate the libraries to support new uamqp implemented recently. Before that i have used proton-c library it was working fine. I am not sure why i am getting this error. I tried the sample in  different network also checked the amqp port 5671 and also checked the date. All are look like correct but i am getting this error.  

**Environment** : Lnux localhost 3.14.39ltsi-WR7.0.0.9_standard #1 SMP PREEMPT Fri Oct 30 23:10:41 IST 2015 armv7l armv7l armv7l GNU/Linux

**Programming Language**: C 

**Iot hub git branch** : 2016-05-20 
**Sample** = https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c

**Open ssl verison** : OpenSSL 1.0.1j 15 Oct 2014

Actually I need to check SaS token support, if I use SaS token in the connection string i get this error more frequently. Then I tried SharedAccessKey, this is also not working same error. 

**Error**: Time:Thu May 26 09:19:42 2016 File:/home/avenger/GIT/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}

**Comment by ewertons** [comment]
Hi @rajvael ,
could you share the complete output of the sample please?
and did you run the same sample from a Linux Desktop with the same credentials? could you please try if possible?

And, could you run this on your arm environment and let us know if the connection succeeds (please omit the certificate info when replying)?

ewertons@esds-ubuntu01:~/openssl$ openssl
OpenSSL> s_client -host <your iot hub server name>.azure-devices.net -port 5671


Example of mine:

CONNECTED(00000003)
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT SSL SHA2
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=*.azure-devices.net
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
subject=/CN=*.azure-devices.net
issuer=/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
---
No client certificate CA names sent
---
SSL handshake has read 3677 bytes and written 521 bytes
---
New, TLSv1/SSLv3, Cipher is <OBFUSCATED>
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : <OBFUSCATED>
    Session-ID: <OBFUSCATED>
    Session-ID-ctx:
    Master-Key: <OBFUSCATED>
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1464304988
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---

**Comment by rajvael** [comment]
**Complete output**: 

# ./IotHub_client_amqp_latest 
Starting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.0.7
IoTHubClient_SetMessageCallback...successful.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Press any key to exit the application. 
Error: Time:Fri May 27 07:51:15 2016 File:/home/GIT/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Fri May 27 07:51:45 2016 File:/home/GIT/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Fri May 27 07:52:15 2016 File:/home/GIT/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}

**Comment by rajvael** [comment]
As per your advice i executed the below command


OpenSSL>  s_client -host myownrajkumar.azure-devices.net -port 5671
CONNECTED(00000003)
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT SSL SHA2
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=*.azure-devices.net
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGcjCCBFqgAwIBAgITWgABtrNbz7vBeV0QWwABAAG2szANBgkqhkiG9w0BAQsF
ADCBizELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEVMBMGA1UE
CxMMTWljcm9zb2Z0IElUMR4wHAYDVQQDExVNaWNyb3NvZnQgSVQgU1NMIFNIQTIw
HhcNMTUwODI3MDMxODA0WhcNMTcwODI2MDMxODA0WjAeMRwwGgYDVQQDDBMqLmF6
dXJlLWRldmljZXMubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
nXC/qBUdlnfIm5K3HYu0o/Mb5tNNcsr0xy4Do0Puwq2W1tz0ZHvIIS9VOANhkNCb
VyOncnP6dvmM/rYYKth/NQ8RUiZOYlROZ0SYC8cvxq9WOln4GXtEU8vNVqJbYrJj
rPMHfxqLzTE/0ZnQffnDT3iMUE9kFLHow0YgaSRU0KZsc9KAROmzBzu+QIB1WGKX
D7CN361tG1UuN68Bz7MSnbgk98Z+DjDxfusoDhiiy/Y9MLOJMt4WIy5BqL3lfLnn
r+JLqmpiFuyVUDacFQDprYJ1/AFgcsKYu/ydmASARPzqJhOGaC2sZP0U5oBOoBzI
bz4tfn8Bi0kJKmS53mQt+wIDAQABo4ICOTCCAjUwCwYDVR0PBAQDAgSwMB0GA1Ud
JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQUKpYehBSNA53Oxivn
aLCz3+eFUJ0wXQYDVR0RBFYwVIITKi5henVyZS1kZXZpY2VzLm5ldIIaKi5hbXFw
d3MuYXp1cmUtZGV2aWNlcy5uZXSCISouc3UubWFuYWdlbWVudC1henVyZS1kZXZp
Y2VzLm5ldDAfBgNVHSMEGDAWgBRRryQmnPRoIleAJis7RmIVex7MpTB9BgNVHR8E
djB0MHKgcKBuhjZodHRwOi8vbXNjcmwubWljcm9zb2Z0LmNvbS9wa2kvbXNjb3Jw
L2NybC9tc2l0d3d3Mi5jcmyGNGh0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kv
bXNjb3JwL2NybC9tc2l0d3d3Mi5jcmwwcAYIKwYBBQUHAQEEZDBiMDwGCCsGAQUF
BzAChjBodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL21zY29ycC9tc2l0d3d3
Mi5jcnQwIgYIKwYBBQUHMAGGFmh0dHA6Ly9vY3NwLm1zb2NzcC5jb20wTgYDVR0g
BEcwRTBDBgkrBgEEAYI3KgEwNjA0BggrBgEFBQcCARYoaHR0cDovL3d3dy5taWNy
b3NvZnQuY29tL3BraS9tc2NvcnAvY3BzADAnBgkrBgEEAYI3FQoEGjAYMAoGCCsG
AQUFBwMBMAoGCCsGAQUFBwMCMA0GCSqGSIb3DQEBCwUAA4ICAQCrjzOSW+X6v+UC
u+JkYyuypXN14pPLcGFbknJWj6DAyFWXKC8ihIYdtf/szWIO7VooplSTZ05u/JYu
ZYh7fAw27qih9CLhhfncXi5yzjgLMlD0mlbORvMJR/nMl7Yh1ki9GyLnpOqMmO+E
yTpOiE07Uyt2uWelLHjMY8kwy2bSRXIp7/+A8qHRaIIdXNtAKIK5jo068BJpo77h
4PljCb9JFdEt6sAKKuaP86Y+8oRZ7YzU4TLDCiK8P8n/gQXH0vvhOE/O0n7gWPqB
n8KxsnRicop6tB6GZy32Stn8w0qktmQNXOGU+hp8OL6irULWZw/781po6d78nmwk
1IFl2TB4+jgyblvJdTM0rx8vPf3F2O2kgsRNs9M5qCI7m+he43Bhue0Fj/h3oIIo
Qx7X/uqc8j3VTNE9hf2A4wksSRgRydjAYoo+bduNagC5s7Eucb4mBG0MMk7HAQU9
m/gyaxqth6ygDLK58wojSV0i4RiU01qZkHzqIWv5FhhMjbFwyKEc6U35Ps7kP/1O
fdGm13ONaYqDl44RyFsLFFiiDYxZFDSsKM0WDxbl9ULAlVc3WR85kEBK6I+pSQj+
7/Z5z2zTz9qOFWgB15SegTbjSR7uk9mEVnj9KDlGtG8W1or0EGrrEDP2CMsp0oEj
VTJbZAxEaZ3cVCKva5sQUxFMjwG32g==
-----END CERTIFICATE-----
subject=/CN=*.azure-devices.net
issuer=/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
---
No client certificate CA names sent
---
SSL handshake has read 3677 bytes and written 523 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
    Session-ID: 84460000F992361DDC1A33FD640BFBAB64D7301DA288D8DB3576F6A3B6050E21
    Session-ID-ctx: 
    Master-Key: B5E7EE34C4C6152F1B0CF27E2F3031DEEF106F60A0C20BB5AF18472A02297927EA304F6E49E70CD42A26909372177EDE
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1464335325
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---

**Comment by markrad** [comment]
Hi @rajvael,

You might try passing the chain of certificates to the SDK via the TrustedCerts option. Take a look at the AMQP samples and you will see this option is used for MBED platforms. In all other platforms it is omitted via a undefined #define variable. You can find the array of certificates in certs.c. Simply copy that into your code and use it in the set options function call. If this successfully connects then it would be indicative of OpenSSL being unable to find the root certificate to validate the certificate from the server.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @rajeevmv,

Following up on this: Can you try running the following command:
```
openssl s_client -CApath /etc/ssl/certs -state -nbio -connect <yourhub>.azure-devices.net:443
```
On my Arduino Yun running OpenWrt this fixed the certificate failure. However, when I tried setting SSL_CERT_DIR to the same location it failed. I'm not really sure what is going on at this time but I'm still looking into it.

Did you try the TrustedCerts option that I suggested above?

_Mark Radbourne MSFT_

**Comment by rajvael** [comment]
i will try it and let you know.

**Comment by ewertons** [comment]
Hello @rajvael, we just had a series of updates done to the C AMQP transport.

Could you please re-run the sample, setting the certificate and let us know if you still have the issue?

Thanks.

**Comment by vrvlive** [comment]
hello @ewertons I was facing the same issue on intel edison board. Tried all the all the options above and following is the result after enabling TrustedCerts option in the code. But still the device is in Pending state at the website. Device names and hostnames are changed in the log. Could you please check the log to see where it is going wrong? 
I was able to successfully run the sample using a raspberry pi 3. 

Starting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.0.9
IoTHubClient_SetMessageCallback...successful.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {default_container_id,<hostxxxx>.azure-devices.net,4294967295,65535}
<- [OPEN]* {DeviceGateway_83fc4617585f4f8192557f531a1685f9,10.0.0.32,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
-> [ATTACH]* {cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,65535}
-> [ATTACH]* {cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,65535}
<- [ATTACH]* {cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,65535,NULL,NULL,NULL}
<- [FLOW]* {0,100,1,5000,0,0,100,0,NULL,false,NULL}
<- [ATTACH]* {cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65535,NULL,NULL,NULL}
-> [FLOW]* {NULL,4294967295,0,100,1,0,10000}
-> [TRANSFER]* {0,0,<00 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
<- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}
-> [ATTACH]* {receiver-link,2,true,0,0,* {amqps://<hostxxxx>.azure-devices.net/devices/IntelEdison@<xxxxxxx>/messages/devicebound},* {ingress-rx},NULL,NULL,NULL,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.9]}}
Info: Event sender state changed [0->1]
-> [ATTACH]* {sender-link,3,false,0,0,* {ingress},* {amqps://<hostxxxx>.azure-devices.net/devices/IntelEdison@<xxxxxxx>/messages/events},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.9]}}
<- [ATTACH]* {receiver-link,2,false,0,0,* {amqps://<hostxxxx>.azure-devices.net/devices/IntelEdison@<xxxxxxx>/messages/devicebound,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {ingress-rx,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.9]}}
-> [FLOW]* {NULL,4294967294,1,99,2,0,10000}
<- [ATTACH]* {sender-link,3,true,0,NULL,* {ingress,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://<hostxxxx>.azure-devices.net/devices/IntelEdison@<xxxxxxx>/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.9]}}
Info: Event sender state changed [1->2]
<- [FLOW]* {1,100,2,4294967295,3,0,1000,0,NULL,false,NULL}
-> [TRANSFER]* {3,1,<00 00 00 00>,0,false,false}
-> [TRANSFER]* {3,2,<01 00 00 00>,0,false,false}
-> [TRANSFER]* {3,3,<02 00 00 00>,0,false,false}
-> [TRANSFER]* {3,4,<03 00 00 00>,0,false,false}
-> [TRANSFER]* {3,5,<04 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,1,NULL,true,* {},NULL}
Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,2,3,true,* {},NULL}
Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,4,NULL,true,* {},NULL}
Confirmation[3] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,5,NULL,true,* {},NULL}
Confirmation[4] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Info: Event sender state changed [2->3]
-> [DETACH]* {3}
Info: Event sender state changed [3->0]
Info: Event sender state changed [0->0]
-> [DETACH]* {2}
-> [DETACH]* {0}
-> [DETACH]* {1}
-> [END]* {}
-> [CLOSE]* {}

**Comment by markrad** [comment]
Hi @rajvael,
Can you rerun your test and provide me with the UTC time that you ran it. I'll check the IoT Hub logs for any issues.
Thanks.
_Mark Radbourne MSFT_

**Comment by rajvael** [comment]
hi @markrad 

UTC time: 11:06 AM i start executing the program 

My Current timezone: IST 

Sample file attached: 
[iothub_client_sample_amqp.txt](https://github.com/Azure/azure-iot-sdks/files/368867/iothub_client_sample_amqp.txt)


Here is the output I got:


$$ ./iothub_client_sample_amqp 
Starting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.0.7
IoTHubClient_SetMessageCallback...successful.
Error: Time:Mon Jul 18 16:36:57 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Press any key to exit the application. 
Error: Time:Mon Jul 18 16:36:58 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:36:58 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:36:58 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:36:59 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:36:59 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:08 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:09 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:09 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:09 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:10 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:10 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:10 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:11 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:11 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:11 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:11 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:12 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Mon Jul 18 16:37:12 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1465 AMQP transport authentication timed out.

Error: Time:Mon Jul 18 16:43:05 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/azure-c-shared-utility/adapters/socketio_berkeley.c Func:socketio_open Line:320 Failure: select failure.
Error: Time:Mon Jul 18 16:43:05 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:establishConnection Line:749 Failed to open the connection with CBS.
Error: Time:Mon Jul 18 16:43:05 2016 File:/home/avenger/azure_iot_sdk_2016-05-20/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1449 AMQP transport failed to establish connection with service.
Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[3] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[4] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY

**Comment by markrad** [comment]
I'm still looking at a number of similar issues on devices such as the Edison and those running OpenWRT. I have a couple of theories but nothing that I am ready share at this time.

**Comment by markrad** [comment]
Hi @rajvael,

On the Intel Edison board I am able to get this sample to work if I remove the #ifdef and #endif from this code:

```c
#ifdef MBED_BUILD_TIMESTAMP
            // For mbed add the certificate information
            if (IoTHubClient_SetOption(iotHubClientHandle, "TrustedCerts", certificates) != IOTHUB_CLIENT_OK)
            {
                printf("failure to set option \"TrustedCerts\"\r\n");
            }
#endif // MBED_BUILD_TIMESTAMP
```

You will also need to copy the certificate strings into your code from c/certs.c. The variable is called certificates. Copy the entire array into your code for use by the lines above.

I don't know why the Edison's OpenSSL will not recognize the certificates in the certificate store. I checked all of the symbolic links including the hashed certificate link and they all appeared to be in order. I am going to try a later build of OpenSSL to see if it resolves the issue.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @rajvael,

Further update: I retested this on my Arduino Yun and I was able to successfully send messages to the IoT Hub without adding the TrustedCerts option. Possibly this issue has been inadvertently addressed by updates to the SDK. Much work has gone on in the last month or to improve reliability on smaller devices. Perhaps you would like to test this again?

_Mark Radbourne MSFT_

**Comment by jtanner-msft** [comment]
Closing as I have not seen any update from @rajvael.  If you still see the problem after testing with the updated SDK, please feel free to re-open the issue.

**Comment by brwhaley** [comment]
I've rebuilt the SDK (10/3/2016) but still encounter the issue above on the Edison.  The TrustedCerts workaround does mitigate the issue, but doesn't seem like a good long-term solution.  I've seen speculation that updating OpenSSL might fix the problem -- has anyone actually seen that work?  Thank you.

**Comment by brwhaley** [comment]
Update -- I was able to get the AMQP sample to work on my Edison without the TrustedCerts workaround by setting the following environment variable:

 export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
