### ISSUE TITLE
MQTT example crashed if network connection is lost unexpectedly

### ISSUE THREAD

**Issue by kevin0402** [Azure/azure-iot-sdks#581]
While running C example iothub_client_sample_mqtt under Linux, after the client connected to IoT hub, if the network connection is broken (e.g: client can't ping to IoT hub), the example program will crash after about 20 minutes.

In the example program, I send 300 bytes data to IoT hub every 1 minute. When network connection is down, the data is queued in TCP buffer and I got "Confirmation[6] received for message tracking id = 7 with result = IOTHUB_CLIENT_CONFIRMATION_ERROR". 

In this case, I think TCP socket and MQTT connection should be closed, then upper layer example program can exit normally.

**Comment by jebrando** [comment]
Can you please send me a code snippet to repro the issues.  I've been running for 60 min and haven't experienced a crash.  I do receive a socket failure which is expected due to the client connection failure.  I’m running on Ubuntu 16.04 on the develop branch.

**Comment by kevin0402** [comment]
Test environment :
   My EV board --- switch 1 --- switch 2 --- IoT hub (Internet)

Linux kernel : 2.6.31
SDK version : 2016-05-06

Procedure :
1. EV board connect to IoT hub (CONNECT and SUBSCRIBE successfully) 
2. EV board PUBLISH an event and receive the PUBACK
3. Unplug the Ethernet cable between switch 2 and IoT hub
4. EV board continue PUBLISH the event every 1 minute but can't receive PUBACK.
    I can see TCP stack try to re-transmit these packets.
5. After about 20 minutes, when next event is sending, the example program enter socketio_berkeley.c : socketio_send() -> send() and "never return", then the program terminate unexpectedly. 

Note: 
1. MQTT keep alive and TCP keep alive are not triggered by default. 
    It does not help even I enable above two keep alive mechanism. 
    Socket level and MQTT level does not know the network connection is broken.
2. In iothub_client_sample_mqtt.c, is there a way to know underlying connection is broken ?

**Comment by kevin0402** [comment]
@tameraw 

Can you reproduce this issue ?
Do you need any additional info ?

**Comment by jebrando** [comment]
Can you let me know what distro you are using?  Running this on Ubuntu is working correctly.  I think I need to run this on a different distro to see the error.

**Comment by kevin0402** [comment]
It's Fedora 12 with kernel 2.6.31.

**Comment by jebrando** [comment]
We only support Fedora version 20 and higher:
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-tested-configurations/

The gcc version for this is 4.4 and the SDK 4.9
