### ISSUE TITLE
C library - How to pass trust store path or certificates to validate ****.azure-devices.net server certificate using amqp or websocket 

### ISSUE THREAD

**Issue by rajvael** [Azure/azure-iot-sdks#584]
Please let me know  
How to pass trust store path or certificates to validate ****.azure-devices.net server certificate using amqp or websocket protocol. 

I saw the below method in

>  iothubtransportamqp_websockets.c

 but I am not sure how to pass this certificate string. 

```
XIO_HANDLE getWebSocketsIOTransport(const char* fqdn, int port, const char* certificates)
{
	WSIO_CONFIG ws_io_config = { fqdn, port, DEFAULT_WS_PROTOCOL_NAME, DEFAULT_WS_RELATIVE_PATH, true, certificates };

	return xio_create(wsio_get_interface_description(), &ws_io_config, NULL);
}
```

**Comment by tameraw** [comment]
@rajvael - Currently our C client SDK provides the option to pass the certificate via the API SetOption. For an example on how this is used, please refer to the following sample:

https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_amqp_websockets/iothub_client_sample_amqp_websockets.c

**Comment by rajvael** [comment]
Thanks.
Let me try to compile with -DMBED_BUILD_TIMESTAMP option and let you know.

**Comment by rajvael** [comment]
I have once more question, 
How can I pass revocation certificate list to verify certificate presented by server is revoked already? 
Does Iot Hub libraries checking OCSP in certificate to verify the server certificate is valid?

**Comment by tameraw** [comment]
@rajvael - Currently we do not provide an option to pass revocation certificate list. It is in our backlog to address in the near future.

**Comment by tameraw** [comment]
Closing issue. Feel free to reactivate or file another one if encountering any issues. Thanks.
