### ISSUE TITLE
[C#][UWP] AMQP Transport not working

### ISSUE THREAD

**Issue by yuri1312** [Azure/azure-iot-sdks#585]
Hi,

I've noticed that since version 1.0.9+ of the SDK I've been unable to create instances of DeviceClient using a transport type of Amqp (always falls back to Http) in UWP clients. (seems like it was caused by the changes in 23a89dac6b8dbe634eff40227b162f4f38c4ad1a)

Is this expected behaviour?

Thanks

**Comment by arturl** [comment]
@yuri1312: no, this is not expected, we'll take a look. Thanks for the report!

**Comment by anthonyvercolano** [comment]
Could you try using Amqp_Tcp_Only?  Please post results.

Also, what specifically is telling you that you are falling back to http?

Thank you.

**Comment by anthonyvercolano** [comment]
We have a good track on this issue.  No need for you to post any results.  Thank you for reporting this.

**Comment by mtuchkov** [comment]
Thank you for the report @yuri1312. This was a regression. Fixed.

**Comment by yuri1312** [comment]
Hi,

I was trying to receive messages with a timeout (which is supported in Amqp transport but not in HTTP), and I was getting an exception that HTTP didn't support that (which only started in 1.0.9).

**Comment by mtuchkov** [comment]
Fixed. 	[Fixes AMQP on UWP](https://github.com/Azure/azure-iot-sdks/commit/feec94a58eddd04416bc73d0b0d6f024532f3dd2)
