### ISSUE TITLE
AzureIoTHubTrigger function

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdks#586]
I know this question is not directly related to the SDK, but does anyone know if there are any plans on offering an AzureIoTHubTrigger function?

**Comment by christopheranderson** [comment]
Created an issue to track this in the Azure Functions repo - https://github.com/Azure/azure-webjobs-sdk-script/issues/413
We plan on getting started planning the IoT stuff in June, so should start seeing some progress quite soon.

**Comment by tameraw** [comment]
@wmmihaa - Closing this issue as you mentioned not related to the SDK and being tracked in the Azure Functions repo. Thanks.
