### ISSUE TITLE
Guidance/docs for new C project with cmake

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#587]
We have prototyped in Python, but I am looking at eventually creating our client application using c. I have been able to run the samples etc, but was looking for some guidance on including the iothub_client c library as a cmake dependency in my project. 

*My apologies for my limited CMake abilities*

Thinking along the lines of:

1. Add azure-iot-sdks as submodule into lib folder for my project `git submodule add https://github.com/Azure/azure-iot-sdks.git lib`
2. Configure CMakeLists.txt of my project to utilise the c iothub_client adapted from amqp samples directory (*currently not working CMake file*)
```cmake
cmake_minimum_required(VERSION 2.8.11)
add_subdirectory(lib/c/iothub_client)

add_executable(
    iot_sample
    ./main.c
)

target_link_libraries(iot_sample
    iothub_client
    iothub_client_amqp_transport
    aziotsharedutil
    uamqp
    pthread
    curl
    ssl
    crypto
)
```
3. `mkdir build && cd build && cmake ..`
4. `make`

Any guidance/documentation on this type of workflow would be greatly appreciated. Or if I am completely on the wrong path, guidance on including the iothub_client as a dependency to a standalone project.

Thank you in advance

**Comment by anhashia** [comment]
Looking into this.

**Comment by anhashia** [comment]
Hi @damienpontifex 

Once you build the Azure IoT SDK C libraries, there are 2 approaches here to build your own application using these libraries.

1.) Use existing build structure which uses CMake tool. Basically, add your files in CMakeLists.txt. It will generate **makefile** under **home/cmake**/iothub_client/samples/iothub_client_sample_amqp once it goes through the build process. On this CMake generated makefile which you can run make command.

2.) Another approach is to create your own custom **makefile** and the simply run make command on it. Below is the example of makefile that you create. This makefile will build **main.c** where you would have your own code calling Azure IoT SDK API's. Below is an example which uses AMQP. Here repository has been cloned under works sub-directory under home directory.
make command on this makefile will result in **myTestApp** executable file.

**Example**
```
CC = gcc

INCDIRS = \
    -I $$HOME/works/azure-iot-sdks/c/azure-c-shared-utility/inc/azure_c_shared_utility \
    -I $$HOME/works/azure-iot-sdks/c/iothub_client/samples/iothub_client_sample_amqp \
    -I $$HOME/works/azure-iot-sdks/c/azure-c-shared-utility/inc \
    -I $$HOME/works/azure-iot-sdks/c/azure-c-shared-utility/c/inc \
    -I $$HOME/works/azure-iot-sdks/c/iothub_client/inc

BINS = main.o

LIBDIRS = \
    -L $$HOME/cmake/iothub_client \
    -L $$HOME/cmake/azure-c-shared-utility/c/ \
    -L $$HOME/cmake/azure-c-shared-utility \
    -L $$HOME/cmake/azure-uamqp-c \

LIBS = \
    -liothub_client_amqp_transport \
    -luamqp \
    -liothub_client \
    -laziotsharedutil \
    -lssl \
    -lcrypto \
    -lpthread

TARGETS = myTestApp

###############################################################################
	
.PHONY: all
all: $(TARGETS)

.PHONY: clean
clean:
	rm -f $(TARGETS)
	rm -f $(BINS)

###############################################################################

myTestApp: $(BINS)
	$(CC) -o myTestApp $(LIBDIRS) $(BINS) $(LIBS)

###############################################################################

main.o: main.c
	$(CC) -c $(CFLAGS) $(INCDIRS) main.c

```
`

**Comment by damienpontifex** [comment]
Thanks @anhashia I didn't want a Makefile if using CMake to generate it. With this repo as a submodule located at 'lib/azure-iot-sdks', my CMakeLists.txt I ended up with that worked was:

```cmake
cmake_minimum_required(VERSION 2.8.11)
project(iot_sample)

include_directories(.)

set(iot_sample_c_files
	main.c
)

set(iot_sample_h_files
)

add_executable(
	${CMAKE_PROJECT_NAME}
	${iot_sample_c_files}
	${iot_sample_h_files}
)

add_subdirectory(lib/azure-iot-sdks/c)
include_directories(lib/azure-iot-sdks/c/iothub_client/inc)
include_directories(lib/azure-iot-sdks/c/azure-c-shared-utility/inc)

target_link_libraries(${CMAKE_PROJECT_NAME}
	iothub_client
	iothub_client_amqp_transport
	aziotsharedutil
	uamqp
	pthread
	curl
	ssl
	crypto
)

linkSharedUtil(${CMAKE_PROJECT_NAME})
linkUAMQP(${CMAKE_PROJECT_NAME})
```

Any feedback would be always appreciated, but now with a working minimum sample, feeling better that I can integrate in this way successfully.

**Comment by anhashia** [comment]
Hi @damienpontifex 
Good to hear that you got it working using `CMakeLists.txt.` For comparison, you can always reference \azure-iot-sdks\c\iothub_client\samples\iothub_client_sample_amqp\linux`\CMakeLists.txt ` **sample**
