### ISSUE TITLE
SSL_write error when running iothub_client_sample_amqp

### ISSUE THREAD

**Issue by wangxhere** [Azure/azure-iot-sdks#588]
Hi,

I'm running Azure IoT SDK on a MT7688 running OpenWRT (Kernel version 3.18.29, MIPSel). IoT Hub SDK for C version 1.0.7.

When I run iothub_client_sample_amqp:

Error: Time:Sun May 29 06:14:32 2016 File:/home/wangxhere/openwrt/wrtnode/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/azure-iot-sdks-1/azure-c-shared-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:674 SSL_write error.

SSL_ERROR_SYSCALL is returned by a SSL_get_error call right after SSL_write. ERR_get_error returns 0, meaning an EOF is observed. In Wireshark I see client sending FIN, ACK following "Change Cipher Spec" message. Also the certs' trust chain is verified with openssl on client machine to be OK. I could not find the issue here.

At the same time, MQTT sample runs with a similar error -- SSL_write error. HTTP sample runs without issue after installing CA certificates.

Below is output of my OpenSSL:

root@OpenWrt:~# openssl s_client -host [my iothub name].n
et -port 5671
CONNECTED(00000004)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT SSL SHA2
verify return:1
depth=0 CN = *.azure-devices.net
verify return:1
2002281544:error:0606C06E:lib(6):func(108):reason(110):NA:0:
2002281544:error:1408D07B:lib(20):func(141):reason(123):NA:0:
---
Certificate chain
 0 s:/CN=*.azure-devices.net
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGcjCCBFqgAwIBAgITWgABtrNbz7vBeV0QWwABAAG2szANBgkqhkiG9w0BAQsF
ADCBizELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEVMBMGA1UE
CxMMTWljcm9zb2Z0IElUMR4wHAYDVQQDExVNaWNyb3NvZnQgSVQgU1NMIFNIQTIw
HhcNMTUwODI3MDMxODA0WhcNMTcwODI2MDMxODA0WjAeMRwwGgYDVQQDDBMqLmF6
dXJlLWRldmljZXMubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
nXC/qBUdlnfIm5K3HYu0o/Mb5tNNcsr0xy4Do0Puwq2W1tz0ZHvIIS9VOANhkNCb
VyOncnP6dvmM/rYYKth/NQ8RUiZOYlROZ0SYC8cvxq9WOln4GXtEU8vNVqJbYrJj
rPMHfxqLzTE/0ZnQffnDT3iMUE9kFLHow0YgaSRU0KZsc9KAROmzBzu+QIB1WGKX
D7CN361tG1UuN68Bz7MSnbgk98Z+DjDxfusoDhiiy/Y9MLOJMt4WIy5BqL3lfLnn
r+JLqmpiFuyVUDacFQDprYJ1/AFgcsKYu/ydmASARPzqJhOGaC2sZP0U5oBOoBzI
bz4tfn8Bi0kJKmS53mQt+wIDAQABo4ICOTCCAjUwCwYDVR0PBAQDAgSwMB0GA1Ud
JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQUKpYehBSNA53Oxivn
aLCz3+eFUJ0wXQYDVR0RBFYwVIITKi5henVyZS1kZXZpY2VzLm5ldIIaKi5hbXFw
d3MuYXp1cmUtZGV2aWNlcy5uZXSCISouc3UubWFuYWdlbWVudC1henVyZS1kZXZp
Y2VzLm5ldDAfBgNVHSMEGDAWgBRRryQmnPRoIleAJis7RmIVex7MpTB9BgNVHR8E
djB0MHKgcKBuhjZodHRwOi8vbXNjcmwubWljcm9zb2Z0LmNvbS9wa2kvbXNjb3Jw
L2NybC9tc2l0d3d3Mi5jcmyGNGh0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kv
bXNjb3JwL2NybC9tc2l0d3d3Mi5jcmwwcAYIKwYBBQUHAQEEZDBiMDwGCCsGAQUF
BzAChjBodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL21zY29ycC9tc2l0d3d3
Mi5jcnQwIgYIKwYBBQUHMAGGFmh0dHA6Ly9vY3NwLm1zb2NzcC5jb20wTgYDVR0g
BEcwRTBDBgkrBgEEAYI3KgEwNjA0BggrBgEFBQcCARYoaHR0cDovL3d3dy5taWNy
b3NvZnQuY29tL3BraS9tc2NvcnAvY3BzADAnBgkrBgEEAYI3FQoEGjAYMAoGCCsG
AQUFBwMBMAoGCCsGAQUFBwMCMA0GCSqGSIb3DQEBCwUAA4ICAQCrjzOSW+X6v+UC
u+JkYyuypXN14pPLcGFbknJWj6DAyFWXKC8ihIYdtf/szWIO7VooplSTZ05u/JYu
ZYh7fAw27qih9CLhhfncXi5yzjgLMlD0mlbORvMJR/nMl7Yh1ki9GyLnpOqMmO+E
yTpOiE07Uyt2uWelLHjMY8kwy2bSRXIp7/+A8qHRaIIdXNtAKIK5jo068BJpo77h
4PljCb9JFdEt6sAKKuaP86Y+8oRZ7YzU4TLDCiK8P8n/gQXH0vvhOE/O0n7gWPqB
n8KxsnRicop6tB6GZy32Stn8w0qktmQNXOGU+hp8OL6irULWZw/781po6d78nmwk
1IFl2TB4+jgyblvJdTM0rx8vPf3F2O2kgsRNs9M5qCI7m+he43Bhue0Fj/h3oIIo
Qx7X/uqc8j3VTNE9hf2A4wksSRgRydjAYoo+bduNagC5s7Eucb4mBG0MMk7HAQU9
m/gyaxqth6ygDLK58wojSV0i4RiU01qZkHzqIWv5FhhMjbFwyKEc6U35Ps7kP/1O
fdGm13ONaYqDl44RyFsLFFiiDYxZFDSsKM0WDxbl9ULAlVc3WR85kEBK6I+pSQj+
7/Z5z2zTz9qOFWgB15SegTbjSR7uk9mEVnj9KDlGtG8W1or0EGrrEDP2CMsp0oEj
VTJbZAxEaZ3cVCKva5sQUxFMjwG32g==
-----END CERTIFICATE-----
subject=/CN=*.azure-devices.net
issuer=/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
---
No client certificate CA names sent
Peer signing digest: SHA1
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 3570 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: A20B000011F0F5512DE57FE3F2F937ED51A40AC2576D4D9693E50B5BF93E786C
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1464540147
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

Thanks.

**Comment by wangxhere** [comment]
It seems a SSL cert error as I rerouted the packets through VM and monitor the data flow. However is that cert already provided in source code in ./c/certs/certs.c?

**Comment by tameraw** [comment]
@wangxhere - Can you please confirm if your sample runs ok if you use the SetOption() to specify the TrustedCert? You can see that in our samples (when running on MBED) but if you haven't done already, you can potentially try the same on your device and share the results. Thanks.

**Comment by wangxhere** [comment]
@tameraw Thank you for the advice. However as I tried to specify TrustedCert and even put the certificate char array into the same C file, all the behaviors are still the same. I've attached the Wireshark capture file for you to analyze. My client's IP is 10.0.0.225 in the capture file.

[openwrt.zip](https://github.com/Azure/azure-iot-sdks/files/293611/openwrt.zip)

**Comment by tameraw** [comment]
@wangxhere - Thanks for the data. We'll investigate the issue.

**Comment by markrad** [comment]
Hi @wangxhere,
I took a look at the network trace that you sent to us. At the moment I'm not really sure what's going on. The SSL handshake appears to complete successfully but then the client immediately closes the connection, sending an ACK FIN. 
I do have a (very different) device here that appears to reproduce the issue in that the network trace is very similar but I can't be sure that it is the same root cause. However, I'm going to debug that issue to see if it gives me any additional insight.

_Mark Radbourne MSFT_

**Comment by wangxhere** [comment]
Hi @markrad ,

Yes, that is what I captured, the client closes connection immediately after what seems to be a successful SSL handshake. However there is ** a slight difference in timing ** between the normal case (running on a Ubuntu 14.04 VM) and this failure case, with the same code, but that difference is not significant. I do not have other devices at my hand other than this OpenWRT device, that can be used to compare.

I have updated to latest commit just now (51d24aa8cc180e21627be807ee42b19aba91add2), and the problem persists. To be more accurate, I'm currently running the following OpenWRT revision:
OpenWrt Chaos Calmer 15.05.1 r49363 / LuCI for-15.05 branch (git-16.146.70274-cfd3bb1)

The hardware platform is a WRTnode2P (http://wrtnode.com/w/?p=727), its firmware source is hosted at:
https://github.com/WRTnode/openwrt.

Thanks.

**Comment by markrad** [comment]
Hi @wangxhere,
I debugged the other device to which I referred above. Unfortunately I doubt the root cause in that instance has any relation to your issue. The code on that device was failing because it also expected the server's certificate to be in its certificate store rather than just the parents of that certificate. I suspect that is an implementation error.
I am continuing to research your issue.
_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @wangxhere,

Since I don't have a device to reproduce this, resolving it will be difficult. For testing purposes only I would like you to turn off certificate validation. In the file azure-iot-sdks\c\azure-c-shared-utility\src\tlsio_openssl.c find the call to SSL_CTX_set_verify and change SSL_VERIFY_PEER to read SSL_VERIFY_NONE. Test this, let me know if it works and send me a network trace regardless.

Thank you.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Did you try my suggestion? I will assume that this issue is resolved if you don't respond.

**Comment by wangxhere** [comment]
Hi @markrad ,

Sorry I was tied to another issue the past 2 weeks. Just tried your suggestion with latest commit on master branch, but got no luck. The scenario is completely same. May I ask whether there is any other dependencies of Azure IoT SDK code, especially on other OS components?

Thanks,
Wang Xian

**Comment by markrad** [comment]
Hi @wangxhere,
This is not making any sense. The OpenSSL s_client appeared to work but you can't connect even when you shut off certificate validation. Perhaps you could try the HTTPS sample to see if that works. 

_ Mark Radbourne MSFT_

**Comment by wangxhere** [comment]
Hi @markrad 

I previously tried all three protocols and only HTTPS works. Also I believe that you are right by saying OpenSSL s_client seems to be working, as from the Wireshark capture (in previous replies) it shows that SSL connection was established when a RST packet was sent by Client, which was even not anticipated by OpenSSL (as it complains about write error). I'm not sure about where the RST comes from, but the time delay from the previous packet is so short that I don't think it has anything to do with the other network traffics that I did not capture.

I am using HTTPS now to continue with implementing functionalities but the delay is obviously longer than AMQP, not to mention network traffic sizes. Hope if you can point out further way for me to debug at my side, and supply you with more information you need to pinpoint the issue.

Thanks,
Wang Xian

**Comment by markrad** [comment]
Hi @wangxhere,

Using the latest version of the SDK in the develop branch I was able to get my Arduino Yun to successfully connect to the IoT Hub using AMQP. Though I am unable to identify a specific fix that addressed this it may have been inadvertently fixed. This was failing on my Yun previously and now it appears to work with both AMQP and HTTP.

Perhaps you could try this again? I know you are using OpenWrt but I'm not sure what device you are using...

_Mark Radbourne MSFT_

**Comment by wangxhere** [comment]
Hi @markrad 

With the latest master branch of Azure IoT library, this issue is gone. I'm closing this issue. Thanks so much.

Best Regards,
Wang Xian
