### ISSUE TITLE
[python][Linux]can't build python iot hub library on Linux

### ISSUE THREAD

**Issue by kingliantop** [Azure/azure-iot-sdks#589]
Hi guys,

When I followed instructions to build python iot hub client, I encountered the following issue, I build C part successfully, what kinds of parameters I should use?

pi@raspberrypi:~/azure-iot-sdks $ more /etc/issue
Raspbian GNU/Linux 8 \n \l

pi@raspberrypi:~/azure-iot-sdks $ python/build_all/linux/build.sh --build-python 3.4
build.sh [options]
options
 -cl, --compileoption <value>  specify a compile option to be passed to gcc
   Example: -cl -O1 -cl ...
 --skip-e2e-tests              skip the running of end-to-end tests (e2e tests are run by default)
 --skip-unittests              skip the running of unit tests (unit tests are run by default)
 --run-longhaul-tests          run long haul tests (long haul tests are not run by default)

 --no-amqp                     do no build AMQP transport and samples
 --no-http                     do no build HTTP transport and samples
 --no-mqtt                     do no build MQTT transport and samples

**Comment by mregen** [comment]
@kingliantop Your command line looks ok. I verified I can build the latest master on Raspbian for 2.7 and 3.4. The error you experience happens if a command line parameter is not quite right. Could you check without parameter (

> python/build_all/linux/build.sh

)? Also make sure the swap space is increased. (see --> #458)

**Comment by kingliantop** [comment]
I upgrade my gcc and cmake to latest version, it seems gone. Thanks!
