### ISSUE TITLE
Argument Exception in DeviceExplorer

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#59]
In the section:
_Configure an IoT Hub connection
• In the Configuration tab, add the connection string for your IoT Hub. For information about how to find this connection string, see the document Setup your IoT Hub. Then click Update._

If one fails to click Update before going to the management tab, the program throws an argument exception if you click list

**Comment by andrew-buckley** [comment]
@markrad, thanks for reporting this. We are looking into it now.

**Comment by andrew-buckley** [comment]
@markrad, this fix will be included in the next release but you can see it in the develop branch now or see the above commit. Thanks.
