### ISSUE TITLE
[C][Linux] Compilation with --no-http

### ISSUE THREAD

**Issue by sogeti-ht-grenoble** [Azure/azure-iot-sdks#591]
Hi I try to compile the head of develop like this 
`./build.sh --no-http`

I get this error :
```
lmussier@ubuntu:~/workspace/official/azure-iot-sdks/c/build_all/linux$ ./build.sh --no-http
~/cmake ~/workspace/official/azure-iot-sdks/c/build_all/linux
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'uuid'
CMake Error at iothub_client/tests/iothubclient_ll_uploadtoblob_unittests/CMakeLists.txt:8 (message):
  iothub_client_ll_uploadtoblob being generated without HTTP support


-- Configuring incomplete, errors occurred!
See also "/home/lmussier/cmake/CMakeFiles/CMakeOutput.log".
```

I've try to correct azure-iot-sdks/c/iothub_client/tests/CMakeLists.txt, adding the test to the tests run only when ${use_http} is defined but I ran into another error. It seems, from the reading of azure-iot-sdks/c/iothub_client/CMakeLists.txt, that blob upload function are always to be compiled. And this code need stuff from the http side.

Q1 : Is the http option is to be removed ?
Q2 : For now I'm using only uamqp over websockets, do I need the blob functionality ? And if yes, will it be available over websockets ?

Regards.

**Comment by tameraw** [comment]
@sogeti-ht-grenoble - No plans to remove the HTTP options from our SDKs.
Recently we have added a new feature allowing you to upload files to the cloud. This feature "requires" HTTP to be enabled in your build.

We have recently added the ability to not use HTTP if you decide to NOT use the FileUpload feature as well. Please checkout our latest code and let us know if you have any issues.
Thanks.
