### ISSUE TITLE
[C][Linux]bugs in the amqp SDK, fixed in my demo, please fix it in SDK

### ISSUE THREAD

**Issue by kingliantop** [Azure/azure-iot-sdks#592]
Hi guys,
When I try to run the remote_monitoring demo on my Ubuntu Linux, I encountered the following errors:

steven@CN-STLIAN-SP4:~/iotdemo/azure-iot-sdks/c/build_all/linux$ ~/cmake/serializer/samples/remote_monitoring/remote_monitoring
Error: Time:Tue May 31 18:50:34 2016 File:/home/steven/iotdemo/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_Create Line:1210 Invalid configuration (Both deviceKey and deviceSasToken are defined)
Error: Time:Tue May 31 18:50:34 2016 File:/home/steven/iotdemo/azure-iot-sdks/c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_Create Line:324 underlying transport failed
Failed on IoTHubClient_CreateFromConnectionString

My environment as below:

Ubuntu 1404 LTS, gcc 4.9.3, cmake 3.2.2

After debugging and tracing, I found the error comes from the improper initialization for the IOTHUB_CLIENT_CONFIG in the AMQP SDK:

line 1210:

 else if (config->upperConfig->deviceKey != NULL && config->upperConfig->deviceSasToken != NULL)
    {
        LogError("Invalid configuration (Both deviceKey and deviceSasToken are defined)");
    }

My solution is that I explicitly set the deviceSasToken as NULL in the remote_monitoring.c:

config.deviceSasToken = NULL;

It works fine for me now, but my concern is that you should check the other parameters in the AMQP SDK, and they all should have a default value in case of such errors.

My email is stlian@microsoft.com if you want to know more details. Thanks!

**Comment by tameraw** [comment]
@kingliantop - Thanks for reporting this issue. It has been noticed and fixed already in our develop branch:
https://github.com/Azure/azure-iot-sdks/blob/develop/c/serializer/samples/remote_monitoring/remote_monitoring.c

We'll be updating the master branch as well. Approximate ETA --> end of day Monday 5/6.
Will close this issue, and if you still encounter any problems after that release, please report back. Thanks.
