### ISSUE TITLE
warning - unable to load bountycastle provider

### ISSUE THREAD

**Issue by prafullj** [Azure/azure-iot-sdks#594]
In the last step in "Get started with Azure IoT Hub for Java", - "Run the applications" mvn exec:java -Dexec.mainClass="com.mycompany.app.App", I get a warning - 'unable to load bountycastle provider' and three other warnings associated with sslbountycastle! The application does run after that normally, sending simulated data (windSpeed) to Azore cloud. But why are the warnings coming there and how to get rid of them?

**Comment by andrew-buckley** [comment]
Hi @prafullj,

Thanks for reporting this. This is actually  known issue in Proton-J (https://issues.apache.org/jira/browse/PROTON-612). I don't think it has been resolved yet, and I'm not quite sure what their plans are. But yes, as you mentioned, the application should run normally even though these warnings appear.

Thanks!

**Comment by prafullj** [comment]
thanks andrew. As long as it not harmful and is under resolution, I am fine with it.
Hopefully it will get resolved in future versions of PROTON.

Thanks again.
regards
prafull

--------------------------------------------
On Wed, 6/1/16, Andrew Buckley <notifications@github.com> wrote:

 Subject: Re: [Azure/azure-iot-sdks] warning - unable to load bountycastle provider (#594)
 To: "Azure/azure-iot-sdks" <azure-iot-sdks@noreply.github.com>
 Cc: "prafullj" <prafull_j@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Wednesday, June 1, 2016, 2:07 AM
 
 Hi @prafullj,
 
 Thanks for reporting this. This is actually  known issue
 in Proton-J (https://issues.apache.org/jira/browse/PROTON-612).
 I don't think it has been resolved yet, and I'm not
 quite sure what their plans are. But yes, as you mentioned,
 the application should run normally even though these
 warnings appear.
 
 Thanks!
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
