### ISSUE TITLE
Intermittent IotHubException thrown when running Device simulator which is trying to provision ~1000 devices

### ISSUE THREAD

**Issue by faister** [Azure/azure-iot-sdks#595]
I have modified the Azure IoT Suite's remote monitoring solution to have the DeviceSimulator-WebJob provision ~1000 devices. I get intermittent exceptions thrown for quite a number of devices while trying to add to the device registry. Why am I getting this exception? I am using an IoT Hub S1 unit. I couldn't have exceeded the IoT Hub quota for identity registry operations (100/min/unit, up to 5000/min) because I was stepping through my code in Visual Studio, trying to figure out why some devices failed with the exception thrown, but most devices provisioned properly. Let me know if you need more details. Thanks

Exception details below: .

Microsoft.Azure.Devices.Client.Exceptions.IotHubException: An internal server error has occurred. Timestamp:5/31/2016 11:06:13 PM.
Tracking Id:ec8524321e764300a2c0616020cc0d6a-G:3-TimeStamp:05/31/2016 23:06:13
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.<OnOpenAsync
>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<TryOpenPrioritizedTransportsA
sync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.DeviceClient.<TryOpenPrioritizedTransportsA
sync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<EnsureOpenedAsync>d__34.MoveN
ext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<EnsureOpenedAsync>d__34.MoveN
ext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<<ReceiveAsync>b__24_0>d.MoveN
ext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Devices.Applications.RemoteMonitoring.Simulator.WebJob.Sim
ulatorCore.Transport.IoTHubTransport.<<ReceiveAsync>b__13_0>d.MoveNext() in C:\U
sers\hoongfai\Source\Repos\test\azure-iot-remote-monitoring\Simulator\Simulator.
WebJob\SimulatorCore\Transport\IoTHubTransport.cs:line 144

**Comment by aguilaaj** [comment]
Hi @faister - for future, feel free to file remote monitoring related issues to https://github.com/Azure/azure-iot-remote-monitoring. Please retry provisioning. You can also add in some retry logic to sleep and retry, what's happening is you're hitting sporadic DNS errors when establishing a connection with the IoT Hub for each device. 
Closing out for now. Please reopen an issue in the remote monitoring repository if need be.
