### ISSUE TITLE
[C] build.sh fails for missing python-pkgconfig package with Ubuntu

### ISSUE THREAD

**Issue by veekoo** [Azure/azure-iot-sdks#599]
Add two packages to the deps variable in c/build_all/linux/setup.sh:
python python-pkgconfig

And it works like a charm. This is a dep from submodule, at least common c tools. Sorry didn't have time to make a req out of this..

**Comment by mregen** [comment]
@veekoo Sorry for the confusion. Is this fix for the Python or the C build? Python dependencies would be setup by python/build_all/linux/setup.sh. Or is there a dependency to Python in the c build?
Thanks for your feedback!

**Comment by veekoo** [comment]
It's in the c code setup. The dependency comes up when you work on a minimal setup without python-dev packages. Adding the package mentioned is sufficient to avoid somewhat complicated looking linker error(s).

**Comment by jtanner-msft** [comment]
Hi Veekoo,

  I’ve tried to look into what you had suggested, but am a little confused about the scenario you are trying to protect against.  I’m running Ubuntu 16.04 and didn’t see any issues with the latest dev branch of the Azure-Iot-SDK installed.

  You are correct that the ./setup.sh in the C build does not set the deps for ‘python or python-pkgconfig’.  But if you plan to build for python the instructions are to do the following:

1.	Go thru the setup for the C build (which would include calling c/build_all/linux/setup.sh and c/build_all/linux/build.sh 
2.	Next, you would go and run python/build_all/linux/setup.sh (which I believe should install the packages in question) and then python/build_all/linux/build.sh

  When I tried the above in my own Ubuntu environment I didn’t see any errors with missing package dependencies.  My concern with adding the Python dependencies into the ./setup.sh file for the C build is that it would force people to install Python in their Linux environment when it might not be needed and space could be limited.  I understand that the C/build_all/linux/build.sh can take a parameter to build the Python C wrapper, but most often I would expect that to be called indirectly from the Python build.sh.  Does that make sense?

**Comment by jtanner-msft** [comment]
Closing as I haven't seen any feedback.  If you believe this is still needed please clarify.
