### ISSUE TITLE
Getting System.StackOverflowException on _deviceClient.SendEventAsync

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-iot-sdks#602]
I'm using the Azure Device client SDK on Windows 10 IoT running on a Raspberry Pi 2. Once in a while, my application locks up and exits. I've done some extensive debugging sessions and found that, for reasons I do not understand, the call to

await _deviceClient.SendEventAsync(message);

sometimes ends in a StackOverflowException in mscorlib without any further details:

System.StackOverflowException was unhandled
  HResult=-2147023895
  InnerException: 

A similar thing sometimes happens on the receiving end. This happens at random it seems. Sometimes it's quick (couple of minutes), sometimes it runs for days without interruption. I'm lost in how I should debug this further. I previously thought it was my Chinese made WiFi dongle, but have replaced that with an original (supported) raspberry dongle which makes absolutely no difference at all. This project is C# and the SDK version is v1.0.11 (latest at time of writing).

**Comment by chrit-msft** [comment]
@jsiegmund I have picked up this issue and will be working with you on it.  Could you please let me know which protocol you are using?  Would it be possible to get a copy of your application to attempt a local repro?

**Comment by jsiegmund** [comment]
@chrit-msft I didn't set any specific protocol, so I guess the default? I'm working on getting everything pushed to my github repo but need to clean out some senstive keys and stuff before I can do so. There's not much to it though, it's basically equal to the IoT Suite remote monitoring solution.

**Comment by chrit-msft** [comment]
@jsiegmund were you able to scrub you code so I can try to reproduce this issue?  I would prefer to use your code instead of our sample since it is the code that reproduced the behavior.  Please let me know if you still need assistance.

**Comment by jsiegmund** [comment]
Right, sorry about that I kinda forgot. The sources are up on github.com/jsiegmund/submerged and you'll need the Gateway directory for the part that's running on the Pi. The exact class is this one (from which you'll need to take the code probably, you cannot run this project without the back-end): https://github.com/jsiegmund/submerged/blob/master/src/Gateway/Repsaj.Submerged.GatewayApp/Device/AzureConnection.cs

**Comment by chrit-msft** [comment]
@jsiegmund I am unable to hit this error, you don't have a callstack from one of your failures do you?

**Comment by jsiegmund** [comment]
Nope but I can put some effort into getting one for you. Although last thing I remembered is that the stacktrace didn't give thay much info.

**Comment by chrit-msft** [comment]
@jsiegmund I just wanted to touch base to see if you were able to capture that stack trace.  While it might not give much info I can always review it internally with the code owners.

**Comment by chrit-msft** [comment]
@jsiegmund I still haven't been able to reproduce this issue and I haven't heard back from you about the stack trace.  If you are still seeing this behavior please re-open this GitHub issue.
