### ISSUE TITLE
Node.js - AMQP - Does not reconnect after a network break.

### ISSUE THREAD

**Issue by edyrli** [Azure/azure-iot-sdks#604]
When running the SimulatedDevice.js on a linux machine. azure iot will not reconnect after i remove the network connection and reconnets it. It reconnets ok if i use HTTP (azure-iot-device-http) protocol.
It still reconnects when the SDK renews the token.

From visual studio code i get the following errors:
Fri, 03 Jun 2016 07:13:34 GMT amqp10:connection Error from socket: Error: read ECONNRESET
Fri, 03 Jun 2016 07:13:34 GMT amqp10:client connection error:  { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Fri, 03 Jun 2016 07:13:34 GMT amqp-common Error received from node-amqp10: read ECONNRESET
Fri, 03 Jun 2016 07:13:34 GMT amqp10:client disconnected
Fri, 03 Jun 2016 07:13:34 GMT amqp10:link Force-detach for /devices/000000001f2d1e93/messages/devicebound_1ceb6d05-160f-40f0-aabe-c08659e95242. Current state: attached
Fri, 03 Jun 2016 07:13:34 GMT amqp10:link /devices/000000001f2d1e93/messages/devicebound_1ceb6d05-160f-40f0-aabe-c08659e95242:0: Transitioning from ATTACHED to DETACHED due to forceDetach
Fri, 03 Jun 2016 07:13:34 GMT amqp10:connection Transitioning from OPENED to DISCONNECTED due to error

More details in the attached log file.
[DebugLog.txt](https://github.com/Azure/azure-iot-sdks/files/297147/DebugLog.txt)

Any suggestions what to do? Any other ways to manually initiate a re-connect?
I am going to use this code as a base for further development and needs to get this sorted.

**Comment by pierreca** [comment]
Hi

From the shared log file it looks like the client reconnected fine, and even received a message, once the token was renewed, so I'm not sure what the "Nothing done" means at the end of the file?

Also if you want the client to reconnect earlier, you can subscribe to the `disconnect` event on the client and then try and call Client.open() again once the network connection has been reestablished.

**Comment by edyrli** [comment]
Yes, the renew token will make a re-connect and receive the waiting messages.
But i did expect the SDK would try to reconnect earlier. If i use
var Protocol = require('azure-iot-device-http').Http;
It will re-connect automatically after a few seconds.
I have tried to subscribe to disconnect.
client.on('disconnect', function () {
This is never triggered.
But as far as i can see there is no emitter in client.js that will ever emit 'disconnect'

(Note: I am not a very experienced node programmer so there could be something i have overlooked)

**Comment by pierreca** [comment]
Oh wow, you're right, that's an oversight on our part. the transport layer (AMQP or MQTT) does emit a `disconnect` event but the Client doesn't forward it. 

In the case of HTTP it's normal since the connection is opened/closed at each request.

**Comment by pierreca** [comment]
This is now resolved in the develop branch and will make it into our next release which will happen end of this week or beginning of next week.

**Comment by PanzerHabba** [comment]
This is still some kind of buggy. I ran the same code on both linux (ubuntu & Rpi3) and windows10 and only on windows10 the `client.on('disconnect', function() {})` seems to be "fired".
node version: 4.4.5
azure-iot-device@1.0.11
azure-iot-device-amqp@1.0.12

After I unplug the ethernet-cable the debug-output is as follow:
` amqp10:framing sending frame:  +85ms { type: 0, channel: 0 } : 0000000802000000`
repeated over and over with approx 1 min interval.

**Comment by pierreca** [comment]
Reopening to investigate issue reported by @PanzerHabba 

As far as I understand the event doesn't fire on Linux, right?

**Comment by PanzerHabba** [comment]
@pierreca That is correct.

**Comment by jtjk** [comment]
Yes, I have also problems with getting the events. Often If I connect and get disconnected, I might be getting the first disconnect event. But after reconnecting, I am not getting these events again. I tried to debug it but it looked very complex way to handle when to add new event listeners and when not. I guess somebody should refactor it little bit.

**Comment by tameraw** [comment]
@edyrli & @jtjk - We're investigating this issue. Thanks.

**Comment by jtanner-msft** [comment]
Hi @jtjk , @edyrli,

  I wanted to let you know that I’ve begun to investigate the behavior that you reported.  Given that it’s been a while, can you please confirm if you are still seeing this behavior on the latest develop branch?

Thanks,

**Comment by jtanner-msft** [comment]
As an update I've been able to repro that the disconnect event does not appear to be exposed on Linux.  I'm in the process of trying to determine at what level it is or is not getting passed along.

**Comment by frode** [comment]
@jtanner-msft any progress on spotting the failing area for Linux?

**Comment by markrad** [comment]
@frode - still researching this

**Comment by markrad** [comment]
Hi @frode, 

After much debugging it would appear that the emit doesn't occur on Linux because the socket doesn't not respond with an error. Even if one pulls the network cable the socket does not return an error on send. Windows is apparently much more sensitive which is why it works on that platform. At the moment I do not have a resolution for this. Tribal knowledge suggests that the only way to circumvent this issue is to do it at an application level such as if you don't get the OK reflected in the message sent callback then tear down the connection and start over.

I will have further discussion with the product group regarding this issue. Currently there is an effort to improve the recovery in response to a network failure. Hopefully it will assist in this too.

_Mark Radbourne MSFT_

**Comment by mgiuncato** [comment]
Hi @markrad,

I have this problem too, platform is Yocto 3.5 on Intel Edison with node 4.4.3.
I remain tuned on this issue for news.
feel free to ask for test o info 

Marco

**Comment by tameraw** [comment]
Closing this as reconnection logic enhancements are being tracked under this project:
https://github.com/Azure/azure-iot-sdks/projects/2

**Comment by AlessandroH** [comment]
Hi,
I'm working with mgiuncato and this issue is blocking our project with big customer disappointment ; It's possible to know when this issue will be solved? Thanks in advance
