### ISSUE TITLE
[C][Linux][DM] Compilation is not c99

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#605]
Hi,

I'l starting to work on the dmprewiev banch. Despite what is written in the [readme.md](https://github.com/Azure/azure-iot-sdks/tree/dmpreview/c/readme.md) in the i[otdm_client CMakeListst.txt](https://github.com/Azure/azure-iot-sdks/blob/dmpreview/c/iotdm_client/CMakeLists.txt#L117)
We found 
`set (CMAKE_C_FLAGS "--std=c11 ${CMAKE_C_FLAGS}")`

Edit : I Change this line to 
`set (CMAKE_C_FLAGS "--std=c99 ${CMAKE_C_FLAGS}")`

It seems to be ok when i compile whith 
`cmake ../c -Duse_amqp:BOOL=ON -Duse_http:BOOL=ON -Duse_mqtt:BOOL=OFF -Drun_e2e_tests:BOOL=OFF -Duse_wsio:BOOL=ON -Dskip_unittests:BOOL=ON -DcompileOption_C:STRING=-fPIC`

I think this line is not required (at least with my options) since you are using compileAsC99() function at the beginning of the cmake file.

**Comment by damonbarry** [comment]
Thanks for getting this on our radar.  We'll get the cmake file cleaned up soon.

**Comment by damonbarry** [comment]
I just checked in 979a607 to the dmpreview branch, so this should be fixed. Thanks!
