### ISSUE TITLE
Error while sending msg through iothub-explorer

### ISSUE THREAD

**Issue by RamPrasadRP** [Azure/azure-iot-sdks#606]
The following error occurs while sending msg through iothub-explorer to device, in which "iothub_client_sample_http" application is running. I could receive the message in the device without any issue.

$ iothub-explorer send "testDevice" "test message 1" --ack=full

Message sent (id: 9745d0fe-aa03-41b1-8895-1e1d3716ea20)
Unhandled rejection TypeError: undefined is not a function
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iothub/lib/amqp.js:38:7
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iothub/node_modules/azure-iot-amqp-base/lib/amqp.js:147:17
    at tryCatcher (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/usr/local/lib/node_modules/iothub-explorer/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)

**Comment by pierreca** [comment]
This looks like a bug that was fixed in the latest version, but should've been only transient in the develop branch last week. Which version of iothub-explorer are you running?

**Comment by pierreca** [comment]
I just pushed the new version of iothub-explorer (1.0.7) and it should fix this problem (I checked but I'd like to have confirmation from you too). Thanks!

**Comment by RamPrasadRP** [comment]
Yes, the above mentioned problem is solved in the latest version of iothub-explorer, but I'm facing other issues with iothub-explorer and iot-hub-sdk (tested from Ubuntu 14.04 PC)

1. I don't receive any msg in iothub-explorer monitor-event when I ran sample apps, but I can receive in Device Explorer (not running at the same time with iothub-explorer). iothub-explorer starts listening to the 16 partitions of my iothub and waiting, but got no msg.

2. Sometimes, I'm not able to send msg to iothub-sdk sample amqp & mqtt applications, but http application. I'm receiving the following error:
**Error** Could not open the connection to the service: AMQP Transport: Could not connect
 But after "logout" and "login" into iothub-explorer can send the msg.

Can you help me with these issues?

**Comment by pierreca** [comment]
can you edit/add a new comment with the commands you're running and their output?

**Comment by RamPrasadRP** [comment]
@pierreca In my dev PC, I logged in the iothub-explorer and executed the following command with my **SharedAccessKey** :
`ram@ram:~$ iothub-explorer 'HostName=remotecamerahub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<key>' monitor-events "Ankaa_Ubuntu"

Monitoring events from device Ankaa_Ubuntu
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/0 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/1 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/2 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/3 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/4 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/5 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/6 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/7 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/8 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/9 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/10 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/11 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/12 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/13 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/14 start time: 1465801673498
Listening on endpoint remotecamerahub/ConsumerGroups/$Default/Partitions/15 start time: 1465801673498
`
Then I ran the following application in my device:
./iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http

There is no response receiving the msg from my application, which send some sample data to the iot-hub. After sometime, I closed the iothub-explorer and started Device Explorer in a Windows PC which receives msg from the sample application running in the device.

**Comment by RamPrasadRP** [comment]
@pierreca This time I left the iothub-explorer running and then I received the messages after some 10 minutes. It is way too long, but I noticed that after the initial delay iothub-explorer could recieve msgs in quick time. 
Can you please check the initial time delay while receiving the messages?

**Comment by pierreca** [comment]
Huh, interesting. There is no initial delay that is set anywhere to receive the messages. We do specify a "start time" to receive the message that is at the time the iothub-explorer command is ran and that is based on your dev machine time. could it be that there's a difference between the PC and the device clock?

**Comment by RamPrasadRP** [comment]
@pierreca There is no time difference between them.

**Comment by pierreca** [comment]
Thanks for checking. I believe this 10 minutes delay is actually due to an early design hack in `iothub-explorer` that is that it receives all messages in the partitions (including very old ones), and filter them on the client-side, which can take a lot of time before it actually reaches more recent messages.

The [Azure Event-Hubs SDK](http://github.com/azure/azure-event-hubs/) has a feature to do this filtering on the event hubs side. 
I'll try to integrate this in iothub-explorer tomorrow so that the new version can be released at the end of the week or beginning of next week.

In the meantime, may I suggest that you use the simple event hubs client sample here:
https://github.com/Azure/azure-event-hubs/blob/master/node/samples/simple_eventhubs_client.js

Using your iothub connection string and setting `eventHubPath` to undefined should just work and act as a listener for all the messages sent by your devices.

**Comment by RamPrasadRP** [comment]
@pierreca I have updated to the latest iothub-explorer(iothub-explorer@1.0.8) and couldn't even run it. 

` ram@ram:~$ iothub-explorer help

util.js:555
  ctor.prototype = Object.create(superCtor.prototype, {
                          ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.exports.inherits (util.js:555:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/receiver.js:59:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:9:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)`

**Comment by pierreca** [comment]
Glad to hear that. This version of the iothub-explorer, because it's released of the `master` branch, doesn't have the device management features of the `dmpreview` branch, so you wont be able to schedule jobs, etc. This being said, the mainline branches (`master`/`develop`) are regularly merged back into `dmpreview` so the fixes will make it there soon and you'll have a fully-functional, device-management enabled iothub-explorer again.
