### ISSUE TITLE
UWP sample out of date: wrong lib reference and missing NuGet

### ISSUE THREAD

**Issue by olivierbloch** [Azure/azure-iot-sdks#612]
The UWP sample (https://github.com/Azure/azure-iot-sdks/tree/master/csharp/device/samples/UWPSample) is referencing Microsoft.Azure.Devices.Client.WinRT (should be Microsoft.Azure.Devices.Client) and the NuGet package Microsoft.Azure.Devices.Client is not referenced in the project.

**Comment by tameraw** [comment]
@olivierbloch - Please reopen if still an issue.
