### ISSUE TITLE
Receiving Messages from IoT Hub using C Language SDK

### ISSUE THREAD

**Issue by dhillii** [Azure/azure-iot-sdks#614]
Hello Everyone,

I have been working with the C part of the SDK to write a program that consumes data that has already been sent to the cloud. Is there any way for me to receive message data from an existing IoT Hub using the C Language? I have been successful doing this in C#. However, my project is in C and I cant think of a way to include a C# program into a C project seamlessly.

Thank you in advance for your help. @kittylyst @ahmetalpbalkan @cwrenniks @cringthis @tomconte

**Comment by zerox1212** [comment]
I think the IoT Hub Client was written natively in C....

https://github.com/Azure/azure-iot-sdks/tree/master/c

**Comment by tomconte** [comment]
Hi, to my knowledge we only have Service SDKs for .NET, Node.JS and Java.

**Comment by dhillii** [comment]
Ok, thanks.

**Comment by zolvarga** [comment]
We are working on the C Service SDK implementation and planning to release it soon. It will have Registry Manager and Feedback Receiver client. 

Event Hub Client will be implemented later. Until that you could use C#, Java or Node Event Hub client from the azure event hub sdk repo. (https://github.com/Azure/azure-event-hubs)

Alternatively you can implement C Event Hub client using uamqp (https://github.com/Azure/azure-uamqp-c/tree/5c4aaddd93b9f3f4c334fbce26dda6decdb3cbb6) or proton-c amqp library.

**Comment by tameraw** [comment]
@dhillii - Unfortunately, this is currently not a priority in our backlog. 
But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade).

Having said that, you can peek at our C E2E tests which will show how we receive messages from IoTHub. https://github.com/Azure/azure-iot-sdks/tree/master/c/iothub_client/tests/iothubclient_amqp_e2e
