### ISSUE TITLE
Info: HTTP Response:{"Message":"The specified SAS token has an invalid signature. It does not match either the primary or secondary key."}

### ISSUE THREAD

**Issue by FrancisVenturini** [Azure/azure-iot-sdks#615]
Hello, I'm working with device sdk for c and it's giving me this error:

azure-iot-sdks/c/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:530 Failure in HTTP communication: server reply code is 401
Info: HTTP Response:{"Message":"The specified SAS token has an invalid signature. It does not match either the primary or secondary key."}
azure-iot-sdks/c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1588 unexpected HTTP status code (401)

Any ideas?

**Comment by tameraw** [comment]
@FrancisVenturini - Please double check the connection string you're passing to the client. Ensure no extra characters were copy/pasted inadvertently.

**Comment by tameraw** [comment]
@FrancisVenturini - Closing. If still having issues, please let us know.
