### ISSUE TITLE
CancelJobAsync throws Object not set to an instance of an object

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-iot-sdks#617]
The job exists because first I get it, and it is running, but Cancel throws exception.

`
private async void btnCancel_Click(object sender, EventArgs e)
{
    try
    {
		JobClient client = 
			JobClient.CreateFromConnectionString(cs);

		//Find a job
		var job = await client.GetJobAsync(txtJobId.Text);

		//exists and is it running?
		if (job.Status == JobStatus.Running)
			await client.CancelJobAsync(job.JobId); //bomb here

		await OutputRunningJobs(cs);
    }
    catch (Exception ex)
    {
		txtJobs.Text += ex.ToString();
    }
}
`

**Comment by anhashia** [comment]
Looking into this issue.

**Comment by anhashia** [comment]
Device Management feature still in **Preview** mode. CancelJobAsync method has not been implemented yet. It is work in progress.
