### ISSUE TITLE
[DM] Integration into device explorer

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#620]
Hi,

A simple question, do you plan to integrate device management into the device explorer tool ?
This tool is great in prototype phase, adding LWM2M to it would be great. Simply query (read/deep read), on demand, all default object resources should be enough for a start.

**Comment by damonbarry** [comment]
We do plan to update Device Explorer although it's a little farther down the list, especially because we have DM support in [iothub-explorer](https://github.com/Azure/azure-iot-sdks/tree/dmpreview/tools/iothub-explorer), which is a cross-platform CLI.

**Comment by lmussier** [comment]
if the node tool do the trick is far enough for me, thanks !
