### ISSUE TITLE
I cannot use iot sdk to connect to my Iot Hub,should I open MQTT port first on Azure?

### ISSUE THREAD

**Issue by karenjian0822** [Azure/azure-iot-sdks#627]
Hi,
I cannot use iot sdk to connect to my Iot Hub
I try the sample code \simulated-device\src\main\java\com\mycompany\app\App.java,but get the exception as:
java.io.IOException: Error initializing MQTT connection:無法連接到伺服器
	at com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:141)
	at com.microsoft.azure.iothub.transport.mqtt.MqttTransport.open(MqttTransport.java:83)
	at com.microsoft.azure.iothub.DeviceClient.open(DeviceClient.java:163)
	at com.mycompany.app.App$MessageSender.run(App.java:66)
	at java.lang.Thread.run(Thread.java:745)

Also.. I try to telnet my iot hub hostname with port 1883 or 8883... but failed to connect,
Should I open MQTT port on Azure ,How to ?

**Comment by anhashia** [comment]
Looking into the issue

**Comment by anhashia** [comment]
Hi @karenjian0822
Look at following sample code for reference 
azure-iot-sdks\java\device\samples\send-receive-sample\src\main\java\samples\com\microsoft\azure\iothub\SendReceive.java
Check if you are able to run the sample and able to connect to Azure IoT Hub with your device connection string.
MQTT over TLS/SSL is port **8883**

In this sample when you specify `mqtt ` in the command line parameter, it sets the connection using **MQTT** protocol

Underlying call is
```
protocol = IotHubClientProtocol.MQTT
DeviceClient client = new DeviceClient(connString, protocol);

```
**Azure IoT Java SDK reference**
```
https://azure.github.io/azure-iot-sdks/java/device/api_reference/com/microsoft/azure/iothub/DeviceClient.html
https://azure.github.io/azure-iot-sdks/java/device/api_reference/com/microsoft/azure/iothub/IotHubClientProtocol.html


```

**Comment by anhashia** [comment]
Closing. Please reactivate if still having issues.
