### ISSUE TITLE
java sdk for device: reconnect backoff bug....

### ISSUE THREAD

**Issue by eissi** [Azure/azure-iot-sdks#628]
In AmqpsIotHubConnection.java, the code used Thread.sleep with exponential backoff intervals.
Thread.sleep(TransportUtils.generateSleepInterval(currentReconnectionAttempt));
But, the return value of TransportUtils.generateSleepInterval(currentReconnectionAttempt) is second thoughThread.sleep accepts the value by milliseconds. So, currently, there is no exponential backoff here.

**Comment by tameraw** [comment]
@eissi - Thanks for filing this issue. We're looking into it.

**Comment by iluican** [comment]
The fix for this is in develop. Thanks again for reporting it to us.
