### ISSUE TITLE
Messages marked as Rejected when using Http1 Transport

### ISSUE THREAD

**Issue by robwestwood** [Azure/azure-iot-sdks#63]
When using the HTTP transport then a message received by the client is always marked as Rejected by the IoT Hub, regardless of whether `CompleteAsync()` or `RejectAsync()` is called. 

If neither call is made then nothing is sent to the feedback endpoint, as expected.

Test setup (for the `CompleteAsync()` case):

- DeviceExplorer (built from this repository) to send messages and monitor the feedback endpoint.
- DeviceClientHttpSample (from this repository) as a test client.

Output from DeviceExplorer:

```
Started monitoring feedback for device rjwsimulator.
Sent to Device ID: [rjwsimulator], Message:"{"msg":"helloD"}", message Id: c1465e6b-4500-4f9d-962a-d38c5183734f
Message Feedback status: "Rejected", Description: "Message rejected", Original Message Id: c1465e6b-4500-4f9d-962a-d38c5183734f
```

**Comment by tameraw** [comment]
We're providing a fix for that. Will update the issue once it's checked in.

**Comment by tameraw** [comment]
A fix was provided in the following nuget release
https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/1.0.0-preview-005
Closing this issue and please let us know if have any other issues.
