### ISSUE TITLE
[IoT SDK][Java] Random MqttException during connection attempt 

### ISSUE THREAD

**Issue by bcraun** [Azure/azure-iot-sdks#630]
I've recently been experiencing random MQTT connection failures with the Java SDK. It appears that there is something on the IoT Hub side holding on to a dead connection for some interval at which point the problems disappear. I'm using an earlier build of the SDK and since I had to convert it to an OSGi bundle, it's very tedious to upgrade. I've looked at the SDK source files referenced in the stack trace and see that the last changes were made 2 months ago so I'm pretty sure there wasn't an explicit fix for this issue. In fact, I'm not sure it's even a client issue. 

Is this expected behavior where the IoT Hub sweeps dead connections on a interval-based policy while refusing new connections?

From the top of stack trace I've listed the relevant lines:

```
java.io.IOException: xxxxx
at MqttIotHubConnection.open(MqttIotHubConnection.java:144)
at MqttTransport.open(MqttTransport:87)
at DeviceClient.open(DeviceClient:162)
at <code that calls DeviceClient.open()>
...
...
```

Please advise ASAP as we've burned many cycles trying to determine the root cause. If there's anything else I can provide please let me know.

**Comment by tameraw** [comment]
@bcraun - Thanks for filing this issue. In order to help, we need more info.


1) You said "recently experiencing" random MQTT Connection Failures. Do you have a timeframe as to when this started happening?

2) "It appears that there is something on the IoT Hub side holding on to a dead connection for some interval at which point the problems disappear." --> Are you saying that if a device is disconnected, it is unable to reconnect for a fixed amount of time, and that after that fixed amount of time elapses, it is able to connect again? Generally our policy is that a new incoming connection for a device should supersede / "kick out" the old connection. 

3) Can you provide the name of your IoT Hub, the device ID, and a narrowed down timeframe during which this occurred?

4) Is the repro consistent?

**Comment by markrad** [comment]
Hi @bcraun,

Please respond to the questions @tameraw listed above. Once I have that information I will be able to assist you futher.

_Mark Radbourne MSFT_

**Comment by bcraun** [comment]
@tameraw,

Thanks for the prompt response. Answers to questions follow:

1. By recent I mean that I typically have a long cycle (hours) between device reboots which auto-starts the the gateway software. I suppose I would not have seen this issue before now that I'm performing startup/shutdown cycles within a couple of minutes. Today is the first time I've noticed that it's non-deterministic in behavior and I cannot seem to correlate a specific interval of time before it works again.

2. The behavior I see is that at some point, I'm able to connect successfully, but following a restart of the gateway software it throws the exception provided in my initial issue description. It was my understanding that a new connection attempt would preempt a previously established one so hence my lack of understanding of what could be the root cause. Even rebooting the device gateway does not resolve the issue so I had concluded it might be on the IoT Hub side.

3. Hub name: **sym-iothub.azure-devices.net**, Device ID: **b827eba52e7d**

4. As far as I can tell, it has failed more than it has worked today. I think you could look at a time window of 08:00EST-16:00EST today for occurrences.

Thanks

**Comment by bcraun** [comment]
I'm going to close the issue as it appears that the root cause is a race condition with the physical network interface on the gateway device being unavailable when Linux is restarted. The application uses LSB init scripts to automate service control and even though there's an explicit dependency on all other Linux services, the network interface is frequently not fully functional when the MQTT client connection is attempted. Adding an explicit delay appears to have resolved the issue.
