### ISSUE TITLE
Problem with How to certify IoT devices running Windows with Azure IoT SDK guide

### ISSUE THREAD

**Issue by Karsten85** [Azure/azure-iot-sdks#632]
I've downloaded the Azure IoT SDK from https://github.com/Azure/azure-iot-sdks

I'm trying to follow the guide for the certification for windows
https://github.com/Azure/azure-iot-sdks/blob/master/doc/iotcertification/iot_certification_windows_c/iot_certification_windows_c.md
But there is something i don't understand

The guide says "Start a new instance of Visual Studio 2015. Open the azure_iot_sdks.sln solution in the cmake folder in your home directory."
But in the downloaded foldere there are no cmake folder or azure_iot_sdks.sln

What am i doing wrong?

**Comment by ashokkhurana** [comment]
Hi @Karsten85 , 

cmake directory is created after running **build_client.cmd** available in the **azure-iot-sdks\c\build_all\windows** directory. In the certification guide, Under **Introduction->Prepare**, there are instructions on how to prepare your development environment which takes you to the link https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md . After following the steps in this link for Windows, you should be able to see the **cmake** or **cmake_win32** folder created under c:/users/[yourusername]/cmake_win32/ which should contain azure_iot_sdks.sln folder.

I will make some edits in the document to have it less confusing.

Please let us know if you still face any issue.

**Comment by tameraw** [comment]
@Karsten85 - Closing this one. Let us know if you're still having any issues. Thanks.
