### ISSUE TITLE
Node SDK - Set message.subject of amqp message

### ISSUE THREAD

**Issue by PanzerHabba** [Azure/azure-iot-sdks#633]
Hi,

When I tried to set properties of amqp-message I would only receive message.messageId property:.

```
var Message = require('azure-iot-device').Message;
var message = new Message(data);
message.userId = 'mcDonalds';
message.messageId = 'hello1';
message.subject = "livemessage";
```

the subject- and userId-property would not be received by iot hub

This can be fixed by adding:

```
if (message.subject) {
    amqpMessage.properties.subject = message.subject;
  }

if (message.userId) {
    amqpMessage.properties.userId = message.userId;
  }

```

to:  azure-iot-device-amqp\node_modules\azure-iot-amqp-base\lib\amqp_message.js

**Comment by anthonyvercolano** [comment]
Application properties for node amqp are currently not supported.  It is in our backlog for a future release.

**Comment by tameraw** [comment]
@PanzerHabba - Please check against the latest in develop (soon to be release to master).
We know look for customer properties on the message.properties property which should hopefully serve your scenario.
If still blocked, please feel free to file new issue. Thanks.
