### ISSUE TITLE
SDK downloaded as zip doesn't have the contents of git submodules

### ISSUE THREAD

**Issue by RamPrasadRP** [Azure/azure-iot-sdks#634]
I downloaded the azure-iot-sdk in zip format from the **Clone or Download** option from the master branch. After extracting, I checked for 'C' and found that the 'c' folder doesn't have the sub-module contents in it.

Can you please check it and upload the whole repository as zip file.

**Comment by markrad** [comment]
Hi @RamPrasadRP,

Sorry I cannot assist you with this. The failure to download the submodules is a limitation of the GitHub website. It has nothing to do with the way we have set up our repository. 

I **strongly** recommend that you use git to acquire the source code with the following command:

```
git clone --recursive https://GitHub.com/Azure/azure-iot-sdks.git
```

This will obviously require you to install git on your chosen platform. 

If, for some reason, you absolutely have to acquire the source via the zip download then you will have to download the three submodules manually from their respective GitHub repositories and insert them into the appropriate locations in the IoT SDK tree.

Sorry I couldn't be of further assistance.

_Mark Radbourne MSFT_
