### ISSUE TITLE
[C][Linux] AMQP_Protocol_over_WebSocketsTls does not have the right signature

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#638]
Hi, 

On develop, AMQP_Protocol_over_WebSocketsTls function does not have the new transport provider signature.

```	
extern const void* AMQP_Protocol_over_WebSocketsTls(void);
```

Given the new signature in iothub_client_ll.h we have for transport providers it should be 
```	
extern const TRANSPORT_PROVIDER* AMQP_Protocol_over_WebSocketsTls(void);
```

**Comment by lmussier** [comment]
Additionally the transport provider for websockets seems to be badly constructed.
If I mirror with AMQP provider fields are messed up.
And (possibly the last thing), getWebSocketsIOTransport, in iothubtransportamqp_websockets.c, does not match the signature required by AMQP_TRANSPORT_INSTANCE structure.
```
 // Pointer to the function that creates the TLS I/O (internal use only).
    TLS_IO_TRANSPORT_PROVIDER tls_io_transport_provider;
```
Where TLS_IO_TRANSPORT_PROVIDER id defined as 
```
typedef XIO_HANDLE(*TLS_IO_TRANSPORT_PROVIDER)(const char* fqdn, int port);
```
But the function passed set as  tls_io_transport_provider for websockets is defined as 
```
XIO_HANDLE getWebSocketsIOTransport(const char* fqdn, int port, const char* certificates)
```
Obviously it does not match.

**Comment by ewertons** [comment]
Hi @lmussier, thanks for bringing this to our attention.

This is indeed an issue and it will be addressed right away.

**Comment by ewertons** [comment]
Hi @lmussier, the AMQP transport over WS has been fixed. The changes are currently on the develop branch, and will be in main on the next release.

Thanks for reporting the issue, and please feel free to re-open the issue if needed.

**Comment by lmussier** [comment]
works for me thanks !
