### ISSUE TITLE
No error message when IoTHub reaches the maximum number of messages / day

### ISSUE THREAD

**Issue by oriolpinol** [Azure/azure-iot-sdks#645]
Is there any feedback / error when messages are not accepted anymore by the Hub because the daily limit has been reached? When that happened to me I could not observe that.

Furthermore, when using MQTT, since messages were not received anymore the sending thread would get stuck in a sleep loop waiting for the number of in-flight messages to decrease but it never did causing a lock in that loop and other threads trying to send trying to grab the lock. Using the built-in IMqttAsyncClient.getPendingDeliveryTokens() seems to prevent the lock (#644) but it would still be nice to see from the client side that the messages are not accepted anymore. 

Thank you very much for your good work!

**Comment by chrit-msft** [comment]
@oriolpinol thank you for raising this issue in order to start investigating this I will need some more information.  Can you tell me which SDK you were using?  Which device\platform you were testing this on?  Is there any additional data you think I would need in order to reproduce this issue?

**Comment by oriolpinol** [comment]
@chrit-msft Hi there! I am using the java sdk and it is running under linux. The only thing is that the hub needs to have reached the limit of messages. Thanks!

**Comment by chrit-msft** [comment]
@oriolpinol were you using the amqps protocol when you reproduced this?

**Comment by oriolpinol** [comment]
No, it was using the MQTT protocol

**Comment by chrit-msft** [comment]
@oriolpinol Sorry I missed that above in your opening statement.  In my repro MQTT closes the connection and starts throwing out the following messages:
The MQTT connection is currently closed. Call open() before attemptingto receive a message.
com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.receiveMessage(MqttIotHubConnection.java:248)
com.microsoft.azure.iothub.transport.mqtt.MqttTransport.handleMessage(MqttTransport.java:255)
com.microsoft.azure.iothub.transport.IotHubReceiveTask.run(IotHubReceiveTask.java:25)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

Is this what you are seeing?

**Comment by oriolpinol** [comment]
@chrit-msft Sorry for the late reply. No, I did not get the error you show. My thread is stuck here:

"pool-2-thread-2" #79 prio=5 os_prio=31 tid=0x00007feed880a800 nid=0xd003 sleeping[0x0000700005698000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.sendEvent(MqttIotHubConnection.java:215)
	- locked <0x000000076e86dfb0> (a java.lang.Object)
	at com.microsoft.azure.iothub.transport.mqtt.MqttTransport.sendMessages(MqttTransport.java:174)
	- locked <0x000000076e86df40> (a java.lang.Object)
	at com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x000000076e86ee70> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by oriolpinol** [comment]
@chrit-msft Maybe this should be 2 separate issues. One, that I don't get an error when the hub has reached its limit looks like, the second one is the thread getting stuck as I mention in my previous commit and probably can be fixed with #644. From what I see in your comment your hub gets into a closed state but mine doesn't seem to.

**Comment by chrit-msft** [comment]
@oriolpinol I have run the java send_event sample against both MQTT and AMQP.  There is a clear difference in behavior.  For MQTT I ran 8100 messages to get over the limit, reset the command and ran an additional 100 events.  The behavior I saw is that it just stopped sending the events after about the 10th event with no message nor warning, it just stopped sending events.  I tested AMQP to determine if it is the service (cloud side) or the SDK sample.  With AMQP it just keeps sending messages.  I managed to get up to 12,000 events before I stopped it.  I have reported both behaviors to the code owners.

**Comment by chrit-msft** [comment]
@oriolpinol I have discussed this behavior with the code owners and they have changed this request to an enhancement.  They will ensure that the SDK bubbles up an intuitive error message when exceeding the hubs daily limit.

**Comment by tameraw** [comment]
We're currently working on enhancing the retry logic and connection error reporting. This should provide you with error indicating a maximum quota has been reached.
A link to the GitHub project is here:
https://github.com/Azure/azure-iot-sdks/projects/2
