### ISSUE TITLE
C# DeviceClient Check if device is able to establish a connection

### ISSUE THREAD

**Issue by reginbald** [Azure/azure-iot-sdks#649]
I'm trying to check if a device is able to connect to the IoT Hub. 
When the device is on a closed network with limited internet connection, It tries to send events, doesn't report that anything is wrong but when I check there are no messages received by IoT Hub.

I noticed that there is a callback class in java that is missing in C#

[https://azure.microsoft.com/en-us/develop/iot/get-started/](link to java example)

    protected static class EventCallback implements IotHubEventCallback {
        public void execute(IotHubStatusCode status, Object context) {
            System.out.println("IoT Hub responded to message with status " + status.name());
        }
    }

Does anyone know how to check for a response from IoTHub? Or check if the connection was established?

**Comment by anhashia** [comment]
Looking into the issue

**Comment by reginbald** [comment]
Is this the only option?
`
    try {
        client = DeviceClient.CreateFromConnectionString("***", TransportType.Amqp);
        var task = client.OpenAsync();
        task.Wait(30000); // wait for 30 sec 
        if (task.IsCompleted) {
            Console.WriteLine("Connected");
        }
        else {
            throw new Exception("Time out");
        }
    }
    catch (Exception e) {
        Console.WriteLine("Error");
    }`

**Comment by anhashia** [comment]
Have a look at https://msdn.microsoft.com/en-us/library/mt674882.aspx for **async/ await**  pattern

**Comment by anhashia** [comment]
Typical send message call would be `await deviceClient.SendEventAsync(message)` in a try/catch block.
If there is any exception while executing the awaitable, you would capture it in a catch block.
Use `azure-iot-sdks\csharp\device\samples\DeviceClientHttpSample\Program.cs` for your reference.

**Comment by anhashia** [comment]
Closing this. Please let us know if you're still having issues. Thanks.
