### ISSUE TITLE
Undocumented dependency when using the HTTP transport

### ISSUE THREAD

**Issue by robwestwood** [Azure/azure-iot-sdks#65]
When trying to send or receive messages using the client library and the HTTP transport, then the assembly `System.Net.Http.Formatting, Version 5.2.3.0` is required. Failure to have this library available results in a `Microsoft.Azure.DevicesMicrosoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException` exception being thrown.

The assembly can be provided bu installing the `Microsoft.AspNet.WebApi.Client` package from NuGet, version 5.2.3.

**Comment by CarlosAlayo** [comment]
Thank you for reporting this issue. We are investigating the problem.

**Comment by dominicbetts** [comment]
@robwestwood @CarlosAlayo. Can you provide more context please? I just tried the following:
1. Create a new C# console project in Visual Studio.
2. Copied the HTTPS sample code from the file csharp\\samples\\DeviceClientHttpSample\\Program.cs in the repository and added my device connection-string.
3. Used the NuGet Package Manager to add the **Microsoft.Azure.Devices.Client** package.
4. Run the application.

I didn't get any errors and I successfully sent device-to-cloud messages and received cloud-to-device messages.

Thanks!

**Comment by robwestwood** [comment]
Hi @dominicbetts did you copy the references across? The sample project has a reference on Microsoft.Azure.Devices.Client project, which has a reference to "Microsoft.AspNet.WebApi.Client in it's packages.config, so the NuGet package is downloaded on package restore.

If you try and install the library via NuGet (ie as you would in normal workflow), then this dependency is not declared, nor can I see it documented anywhere that it is required (other than looking in the source code).

This was with version 1.0.0-preview-003-1; I note that a new version (1.0.0-preview-004) has been dropped onto NuGet; I'm happy to try with this version to see whether it is now fixed in the next couple of days.

**Comment by dominicbetts** [comment]
Hi @robwestwood. My mistake as I didn't notice that you were using HTTP rather than AMQP. I am seeing an exception now.

**Comment by robwestwood** [comment]
More me to apologise, @dominicbetts  - it was a very poor example of a bug report.

**Comment by dominicbetts** [comment]
Hi @robwestwood, I just submitted a PR to make a change to the docs that describes this issue. Thanks for letting us know about it.

**Comment by robwestwood** [comment]
Thanks @dominicbetts.

**Comment by tameraw** [comment]
Issue resolved. Please advise/reopen if you're still having issues. Thanks.
