### ISSUE TITLE
Error compiling azure-iot-sdks on the Intel Edison

### ISSUE THREAD

**Issue by aviiandevil** [Azure/azure-iot-sdks#650]
Hi all, 
  I am trying to connect the Intel Edison to the azure iot hub. I have managed to set-up the hub , and add the Edison device to the hub (using iothub-explorer), and git clone the azure-iot-sdks onto the Edison. 
For building the sample c application I am following: (https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/yocto-intel-edison-c.md)
however, when I build the sdks i get the following error:

--------------------------------------------------------------------------------------------------------------------------
[ 73%] 	Linking CXX executable iothubtransportamqp_unittests_exe 
[ 73%] 	Built target iothubtransportamqp_unittests_exe 
		Scanning dependencies of target iothub_rm_unittests_exe 
[ 73%] 	Building C object service/iothub_service_client/tests/iothub_rm_unittests/CMakeFiles/iothub_rm_unittests_exe.dir/iothub_rm_unittests.c.o 
		cc: internal compiler error: Killed (program cc1) 
		Please submit a full bug report, 
		with preprocessed source if appropriate. 
		See <http://gcc.gnu.org/bugs.html> for instructions. 
service/iothub_service_client/tests/iothub_messaging_ll_unittests/CMakeFiles/iothub_messaging_ll_unittests_exe.dir/build.make:62: recipe for target **'service/iothub_service_client/tests/iothub_messaging_ll_unittests/CMakeFiles/iothub_messaging_ll_unittests_exe.dir/iothub_messaging_ll_unittests.c.o' failed** 
**make[2]: *** [service/iothub_service_client/tests/iothub_messaging_ll_unittests/CMakeFiles/iothub_messaging_ll_unittests_exe.dir/iothub_messaging_ll_unittests.c.o] Error 4** 
CMakeFiles/Makefile2:7000: recipe for target 'service/iothub_service_client/tests/iothub_messaging_ll_unittests/CMakeFiles/iothub_messaging_ll_unittests_exe.dir/all' failed 
make[1]: *** [service/iothub_service_client/tests/iothub_messaging_ll_unittests/CMakeFiles/iothub_messaging_ll_unittests_exe.dir/all] **Error 2** 
make[1]: *** Waiting for unfinished jobs....
 
[ 73%] 	Building C object service/iothub_service_client/tests/iothub_rm_unittests/CMakeFiles/iothub_rm_unittests_exe.dir/__/__/src/iothub_registrymanager.c.o 

[ 73%] 	Building C object service/iothub_service_client/tests/iothub_rm_unittests/CMakeFiles/iothub_rm_unittests_exe.dir/main.c.o 

------------------------------------------------------------------------------------------------------------------------

**Note**: my cmake version is 3.4.0,
Can anyone please help me out?
Thanks,

**Comment by markrad** [comment]
Hi @aviiandevil,

I have not encountered this particular error. I will run the build for myself to see if I see it too. In the meantime, I would like to suggest that you try cross compiling the SDK for your Edison. If you have a Debian based Linux machine available (for example Ubuntu) you can use the script provided in the GitHub repository for this purpose. You can find the script [here](https://github.com/Azure/azure-iot-sdks/tree/master/build) called inteledison_c.sh. This will download the environment required for the cross compile and build the SDK.

If you would prefer to have more control over this process then I suggest you read this [document](https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md).

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Brief update:
Working on an unrelated issue I see the same error _cc: internal compiler error: Killed (program cc1)_ when I was building the SDK on a Raspberry Pi but not on the same file. I will continue my research.

**Comment by aviiandevil** [comment]
@markrad Thank you very much for the help. I will try cross compiling and see how I get on with it. 
The python version is working flawlessly on Edison, so I'm guessing there is some C specific problem
P.S. the GCC is 4.9.1 version

**Comment by markrad** [comment]
Hi @aviiandevil,
I tried building on the Edision and I experienced the same failure as yourself. However, when I switched to the c\cmake\/iotsdk_linux and entered the command make then build continued from where it left off and was apparently successful. You might try that if you prefer to compile on the device rather than cross compile. Cross compiling is typically significantly quicker.

**Comment by aviiandevil** [comment]
Hi @markrad okay thanks. I was able to cross compile and then run the program from Edison. This way seems quicker, but I will try the make command too.
Thanks

**Comment by markrad** [comment]
Following up on this issue, yes I too found that one could get the build to continue where it left off if one runs the make from the cmake/iotsdk_linux directory. I've done some research into this issue and I suspect that it is a problem with the limited RAM available on the Intel Edison. One can reproduce a similar error on the Raspberry Pi so it does not appear to be an architecture issue.

I have managed to find two circumventions though.

1. Pass --skip-unittests to the build.sh script. The failure occurs in the portion that builds the unit tests. There are some particularly large files in that part of the code tree. This will prevent them from being built.

1. Modify the build.sh script and remove from --jobs=$CORES from the make command. This will cause the make system to only use one process thus leading to lower memory usage. This will build successfully albeit very slowly. 

Note: I have not tried circumvention 2 on the Intel Edison only the Raspberry Pi. I don't have an Edison readily available at the moment. I'll test it later. To find out how many cores the Edison reports use the command:
```
grep -c ^processor /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu
```
If its any more than one then try circumvention 2.

Cross compiling will be much quicker though.

**Comment by aviiandevil** [comment]
Hi @markrad  thanks for the detailed info.

The command grep -c ^processor /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu reveals '2' cores.

Since I have an Edison here for now, I tried the Cirumvention 2.
Observations: 
1. By removing only the make --jobs=$CORES, there are errors, the build is unable to find multiple unit-test files.
2. By setting CORES=1 and keeping the make --jobs=$CORES it is building successfully (takes ages though), **and fortunately the program is running successfully, and I am receiving the messages on the azure iot hub. :)**

Just got a warning during the build process: Clock skew detected. Your build may be incomplete. 
However, the program is building and running fine on Edison. But could this warning be a future problem?

Thanks,
Avijit

**Comment by markrad** [comment]
Hi @aviiandevil,

We will be making a change to the build script to also take into account the amount of RAM on the device when deciding how many make jobs to run. Simply put, if the device has less than a Gigabyte of RAM it will only use one job. I tried to run two jobs on a Raspberry Pi but it still failed though later in the build.

As for your clock skew error, I suspect that you are probably editing the files on the Edison via some sort of remote link such as ssh. This will occur when the make system sees a file with a timestamp that is later than the current time on the device. This can occur if you edit files remotely and the Edison and your remote machine's clocks are not fairly closely synchronized.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @aviiandevil,

The build script has been modified to address the build error that you are seeing. This is currently only available in the develop branch. It will be merged into master in the next week or so. 

I have closed your issue. I you are still having problems feel free to reopen it.

_Mark Radbourne MSFT_
