### ISSUE TITLE
Firmware update supplied sample (use ota update) does not work on edison (Image size too big)

### ISSUE THREAD

**Issue by mgiuncato** [Azure/azure-iot-sdks#651]
the "IOTdm_Edison_sample" agent is not able to "firmware update" an edison Yocto image built following instructions : https://github.com/Azure/azure-iot-sdks/blob/dmpreview/c/iotdm_client/samples/iotdm_edison_sample/how_to_create_an_image_for_Intel_Edison.md

I verify that the .ext4 rootfs (about 1.1 GB ) file generated in toFlash dir, is greater than the /update (about 768 mb) partition itself , that is where the "IOTdm_Edison_sample"  c sample use.

nobody knows how reduce rootfs image size in bitbake "edison-image.bb" to fit inside 600-650mb ?

Marco

**Comment by damonbarry** [comment]
I followed these steps recently (1-2 weeks ago), and my `~/src/edison/edison-src/build/toFlash/edison-image-edison.ext4` file was 536870912 bytes, or 512 MB.  Note that I commented the `paho-*` and `iotkit-*` packages out of the `edison-image.bb` file, as described in the instructions you referenced.  Did you do that?  I don't know whether that would make such a dramatic difference...

**Comment by mgiuncato** [comment]
wow !!! 
tks a lot Damon 
I'm running to verify and eventually test it, mm mumble, IOT REMOVING iotkit-* ?? 
let me try and notify.
really surprised..

Marco

**Comment by BertKleewein** [comment]
Are you using Intel's v2.5 source from edison-src-ww25.5-15.tgz?  I'm asking because there is a size issue with the v3.0 source and we're waiting for feedback from Intel on how to reduce the size of 3.0 images.

**Comment by mgiuncato** [comment]
no, we are not using 2.5. jump on 3.0 some weeks ago, after  http://iotdk.intel.com/src/3.0/edison/iot-devkit-yp-poky-edison-20160315.zip was finally published.
I put also a

**Comment by mgiuncato** [comment]
I put also :  
POST su Intel
https://communities.intel.com/thread/102736

**Comment by BertKleewein** [comment]
OK, that explains it.  I will re-engage with Intel on this issue and see if they have suggestions for shrinking the image. 

Note: I also worked with Dominic Betts ( @dominicbetts ) on the issue in the Intel thread you referenced.  His issue was actually a hardware-specific problem that was not related to image size.  We suspect there is something wrong with file system partitioning on his system, but we are still investigating.

**Comment by mgiuncato** [comment]
that's good .
file system partitioning on edison is quite particular, built (correctly I think) with smartphone structure in mind.
I try to resize or to change partition size by myself, but after several different approach, at the end found bitbake oganization with meta/layer/target/image too large to control starting from scratch with it.
the only way to reach fast production prototype based on edison/IOT/IOTDM , passes through a working example.
it worked with 2.5 BUT... not with 3.0
that's all
very kind for support 
Marco

**Comment by mgiuncato** [comment]
Damon,

can you clear  what is the version of INTEL® IOT DEVELOPER KIT ( e.g. 
https://software.intel.com/en-us/blogs/2016/06/06/intel-iot-dev-kit-35-release-announcement or https://software.intel.com/en-us/blogs/2016/03/30/intel-iot-developer-kit-30-release-notes or 
https://software.intel.com/en-us/blogs/2015/10/13/announcing-intel-iot-developer-kit-v20 or https://software.intel.com/en-us/blogs/2014/09/08/announcing-intel-iot-developer-kit or  ) 
that  Azure-iot-SDK refer to use;

tks
Marco
