### ISSUE TITLE
[Java Device Client]Full reconnect during refresh SAS-token

### ISSUE THREAD

**Issue by BlueBasher** [Azure/azure-iot-sdks#654]
The Java Device Client refreshes the SAS-token by doing a full reconnect.
This is different than the .NET Client, which refreshes without reconnecting.

The Java client should also be able to refresh without a full reconnect.
Furthermore, the interval for refreshing (currently 70 minutes) should at least be configurable.

**Comment by tameraw** [comment]
@BlueBasher - Currently it's in our backlog to align this behavior. Thanks for filing this issue.

**Comment by jtanner-msft** [comment]
Which transport protocol are you trying to use to connect with?

**Comment by BlueBasher** [comment]
We saw this when using the AMQPS protocol.

**Comment by BlueBasher** [comment]
I've just tested the latest development branch and can confirm that the new functionality of SetSASTokenExpiryTime is working correctly.
The DeviceClient still does a full reconnect but with this new functionality we can influence the number of times it does so (and thus the overall bandwidth)

**Comment by prmathur-microsoft** [comment]
Yes that is correct. With SetSASTokenExpiryTime you can set the time you want. However it still goes through full reconnect cycle.

**Comment by tameraw** [comment]
@BlueBasher - Closing this since a SetSASTokenExpiryTime option has been added. If it's blocking you in any way, please feel free to open.
