### ISSUE TITLE
[Java Device Client]No hooks into clients behavior

### ISSUE THREAD

**Issue by BlueBasher** [Azure/azure-iot-sdks#656]
The overall interface of the Device Client Java SDK is limited. So it’s effectively a black box.
Some events like OnConnecting, OnConnected, OnDisconnected, OnReconnecting etc would allow for better monitoring / healing.

**Comment by tameraw** [comment]
@BlueBasher - Thanks for the feedback. We'll consider adding this in a future release. However, we happily accept contributions if you decide to submit a pull request for this.
https://github.com/Azure/azure-iot-sdks/blob/master/CONTRIBUTING.md

**Comment by tameraw** [comment]
We're currently working on enhancing the retry logic and connection status reporting. Through that effort, you might be able to achieve the scenarios you're looking for.
A link to the GitHub project is here:
https://github.com/Azure/azure-iot-sdks/projects/2
