### ISSUE TITLE
[JAVA] Issues while running simulator app

### ISSUE THREAD

**Issue by gnandev** [Azure/azure-iot-sdks#657]
Hi,

Have followed all steps mentioned at
https://azure.microsoft.com/en-in/documentation/articles/iot-hub-java-java-getstarted/

And while running simulator app, am getting below mentioned errors.
Request you to let me know if I am missing anything here.

C:\Azure_IOT\working\iot-java-get-started\simulated-device>mvn exec:java -Dexec.
mainClass="com.mycompany.app.App"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building simulated-device 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ simulated-device ---
Press ENTER to exit.
Jun 23, 2016 9:12:26 PM org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFa
ctory getClass
WARNING: unable to load org.bouncycastle.openssl.PEMReader
Jun 23, 2016 9:12:27 PM org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFa
ctory getClass
WARNING: unable to load org.bouncycastle.openssl.PasswordFinder
Jun 23, 2016 9:12:27 PM org.apache.qpid.proton.engine.impl.ssl.SslEngineFacadeFa
ctory <clinit>
WARNING: unable to load bouncycastle provider
Error: Error{condition=amqp:connection:framing-error, description='org.apache.qp
id.proton.engine.TransportException: connection aborted', info=null}
Error: org.apache.qpid.proton.engine.TransportException: connection aborted
java.io.IOException: java.util.concurrent.ExecutionException: java.lang.Throwabl
e: Connection unable to be opened in time.
        at com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.open(AmqpsT
ransport.java:91)
        at com.microsoft.azure.iothub.DeviceClient.open(DeviceClient.java:162)
        at com.mycompany.app.App$MessageSender.run(App.java:58)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.Throwable: Connect
ion unable to be opened in time.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.ja
va:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:189
5)
        at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.reac
torReady(AmqpsIotHubConnection.java:465)
        at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.open
(AmqpsIotHubConnection.java:177)
        at com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.open(AmqpsT
ransport.java:89)
        ... 3 more
Caused by: java.lang.Throwable: Connection unable to be opened in time.
        at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionBaseH
andler.lambda$onConnectionLocalOpen$3(AmqpsIotHubConnectionBaseHandler.java:298)

        ... 1 more

**Comment by dominicbetts** [comment]
Hi gnandev,

You can safely ignore the warning messages regarding the bouncycastle provider, these messages come from one of the libraries used by the SDK.

With regard to the AMQP errors:
1. Can you confirm that there is no firewall blocking your outgoing AMQP traffic - specifically port 5671 (https://azure.microsoft.com/documentation/articles/iot-hub-itpro-info/).
2. Can you check the device connection string you are using - it should be in the form "HostName={YOURHUBNAME}.azure-devices.net;DeviceId={YOURDEVICENAME};SharedAccessKey={YOURDEVICEKEY}.
3. We are about to update the article, and one of the changes is to update the version of the iothub-java-device-client to 1.0.8. Please try using this latest version of the Maven package  with your code.

Regards,
Dominic

**Comment by tameraw** [comment]
Closing. Let us know if still having issues.
