### ISSUE TITLE
updateSharedAccessSignature failure on nodejs using http transport

### ISSUE THREAD

**Issue by sashomasho** [Azure/azure-iot-sdks#658]
When I leave the application for several hours I always get this error:

        "TypeError: this._receiver.updateSharedAccessSignature is not a function",
        "    at Http.updateSharedAccessSignature (/app/node_modules/azure-iot-device-http/lib/http.js:294:20)",
        "    at Client.updateSharedAccessSignature (/app/node_modules/azure-iot-device/lib/client.js:182:19)",
        "    at Client._renewSharedAccessSignature (/app/node_modules/azure-iot-device/lib/client.js:91:8)",
        "    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)",
        "    at tryOnTimeout (timers.js:224:11)",
        "    at Timer.listOnTimeout (timers.js:198:5)"

Browsing through the code I can't seem to find an updateSharedAccessSignature in HttpReceiver class.

The library versions I use are:
    "azure-iot-common": "^1.0.8",
    "azure-iot-device": "^1.0.8",
    "azure-iot-device-http": "^1.0.9",
    "azure-iothub": "^1.0.10",

**Comment by anhashia** [comment]
Looking into this issue

**Comment by anhashia** [comment]
HI @sashomasho 
I tried `simple_sample_device_with_sas.js `located at `azure-iot-sdks\node\device\samples `which uses SharedAccessSignature (SAS) and **AMQP** by default but I didn't see any SAS issue as such. What is your use case and what exactly are your reproduction steps ?

**Comment by sashomasho** [comment]
Hi @anhashia 

The problem occur only when we are using the HTTP transport. AMPQ is working fine, but we use HTTP for environments where AMPQ is blocked by a firewall.

The code is pretty straight-forward:
```
        var transport = getTransport(); //either HTTP or AMPQ
        client = Client.fromConnectionString(connectionString, transport);
        client.open(iotConnectCallback);
```

And now every 20-30 seconds we send a status message to the IoT hub. Nothing fancy. But when the HTTP is used, after a couple of hours I get the error from the original message. We don't explicitly deal with any SAS methods or transport options. As you see from the traceback: no application code is involved in this error, and there is no easy way to handle this exception.

Looking into the sdk sources, I see that HttpReceiver class doesn't have updateSharedAccessSignature method in it:

This is from http.js:
 

```
  Http.prototype.updateSharedAccessSignature = function (sharedAccessSignature, done) {
    this._config.sharedAccessSignature = sharedAccessSignature;
    this._receiver.setSharedAccessSignature(sharedAccessSignature);
    done(null, new results.SharedAccessSignatureUpdated(false));
  };
```

_receiver is HttpReceiver instance, but  http_receiver.js doesn't have the method.

The Client tries to call it no matter which transport is being used (every 45 minutes as I see).

**Comment by sashomasho** [comment]
Hi @anhashia

The problem occur only when we are using the HTTP transport. AMPQ is working fine, but we use HTTP for environments where AMPQ is blocked by a firewall.

The code is pretty straight-forward:

        var transport = getTransport(); //either HTTP or AMPQ
        client = Client.fromConnectionString(connectionString, transport);
        client.open(iotConnectCallback);
And now every 20-30 seconds we send a status message to the IoT hub. Nothing fancy. But when the HTTP is used, after a couple of hours I get the error from the original message. We don't explicitly deal with any SAS methods or transport options. As you see from the traceback: no application code is involved in this error, and there is no easy way to handle this exception.

Looking into the sdk sources, I see that HttpReceiver class doesn't have updateSharedAccessSignature method in it:

This is from http.js:

```
Http.prototype.updateSharedAccessSignature = function (sharedAccessSignature, done) {
  this._config.sharedAccessSignature = sharedAccessSignature;
  if (this._receiver) {
    this._receiver.updateSharedAccessSignature(sharedAccessSignature);
  }
  done(null, new results.SharedAccessSignatureUpdated(false));
};

```
_receiver is HttpReceiver instance, but http_receiver.js doesn't have the method, it has **setSharedAccessSignature**

The Client tries to call it no matter which transport is being used (every 45 minutes as I see).

**Comment by pierreca** [comment]
This is absolutely a bug. I'll provide a fix shortly.

**Comment by pierreca** [comment]
The fix is in  the `develop` branch and will be published in the npm packages with our next release cycle, approximately 10 days from now.
