### ISSUE TITLE
DeviceConnectionString - Do you keep the brackets?

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#66]
So I was following the instructions to build the 'serializaer' solution for Windows:
Build and run the sample

1.Start a new instance of Visual Studio 2015. Open the serializer.sln solution in the c\serializer\build\windows folder in your local copy of the repository.

2.In Visual Studio, in Solution Explorer, navigate to the samples folder. In the simplesample_amqp project, open the simplesample_amqp.c file.

3.Locate the following code in the file:
static const char* connectionString = "[device connection string]";

4.Replace "[device connection string]" with the device connection string you noted earlier. Save the changes.

All of the above makes sense, but as no example was provided of the device connection string, I'm not sure if it should be:
static const char* connectionString = "[my device connection string]";

or

static const char* connectionString = "my device connection string with no brackets";

**Comment by robwestwood** [comment]
It's without the brackets.

**Comment by dominicbetts** [comment]
@jtanner-msft @robwestwood. Thanks for pointing this out. I've made some changes to the document in question to clarify this. It will be checked in shortly.
