### ISSUE TITLE
[Java SDK for Decice] Build error in tests

### ISSUE THREAD

**Issue by eissi** [Azure/azure-iot-sdks#661]
When 'mvn install' is executed, it fails most times (very rarely it passes the test without any modification).

-------------------------------------------------------------------------------
Test set: tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest
-------------------------------------------------------------------------------
Tests run: 34, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.349 sec <<< FAILURE! - in tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest
openTriggersProtonReactor(tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest)  Time elapsed: 0.071 sec  <<< ERROR!
mockit.internal.MissingInvocation:
Missing 1 invocation to:
com.microsoft.azure.iothub.transport.amqps.IotHubReactor#run()
   on mock instance: com.microsoft.azure.iothub.transport.amqps.IotHubReactor@36bc55de
        at tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest.openTriggersProtonReactor(AmqpsIotHubConnectionTest.java:423)
Caused by: mockit.internal.expectations.invocation.ExpectationError
        at tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest.openTriggersProtonReactor(AmqpsIotHubConnectionTest.java:423)

**Comment by eissi** [comment]
When I comment out below, it passes without any issues.

In the file, AmqpsIotHubConnectionTest.java,
from the line 423,
        new Verifications()
        {
            {
                new IotHubSasToken(anyString, anyString, anyLong);
                times = 1;
                new IotHubReactor((Reactor)any);
                times = 1;
                mockIotHubReactor.run();
                times = 1;
            }
        };

**Comment by chrit-msft** [comment]
@eissi thank you for reporting this issue, this is a known issue which we are investigating.  I will update this thread as we have additional information.

**Comment by chrit-msft** [comment]
@eissi my java development environment is toast but my colleague has tested this and confirmed that the unit tests pass both in windows and Linux environments.  If you are still seeing the failure please update your environment.

**Comment by chrit-msft** [comment]
@eissi As this issue is now resolved and I haven't heard from you I will be closing this issue.  If you run into this behavior again please reach out.
