### ISSUE TITLE
[C][Linux][AMQP] IoTHubMessage_CreateFromByteArray with null payload

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#665]
Hi, 

I trying to send (amqp) messages with no payload, I set  only properties.

```
iotMsg = IoTHubMessage_CreateFromByteArray(NULL, 0);
[...]
Map_Add(properties, MESSAGE_COMMAND_KEY, paramStr)
[...]
IoTHubClient_SendEventAsync(g_iotHubClientHandle, iotMsg, sendConfirmationTrashCbk, iotMsg) ;
```
This code lead to print the following line, quite a few time

`Error: Time:Tue Jun 28 15:42:15 2016 File:/home/lmussier/workspace/Agents/iothub/agent/external/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1498 AMQP transport failed sending events.`

Given lines around  Codes_SRS_IOTHUBMESSAGE_06_001, I understand that a null payload should be valid.
Am I wrong ?

PS: I'm on develop

**Comment by chrit-msft** [comment]
@lmussier thank you for reporting this issue, I am looking into it and will update you after researching this.

**Comment by chrit-msft** [comment]
@lmussier I have reproduced the failure you experienced and I will be following up with the code owner.  I will update you once I have heard back from the code owner.

**Comment by QiMata** [comment]
Can confirm still in build

**Comment by tameraw** [comment]
@lmussier & @QiMata  - Working on a fix to release soon. Thanks for your patience.

**Comment by chrit-msft** [comment]
@lmussier & @QiMata There was a fix checked into the develop branch for this issue.
