### ISSUE TITLE
[DM][C#] Port IoT Hub DM client to C#

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/azure-iot-sdks#669]
From this looks of things, Azure IoT Hub Device Management client (for devices) is only available in C?

**Comment by damonbarry** [comment]
That's correct.  We're currently working on Node.js, and Java will follow later.

**Comment by tedvanderveen** [comment]
Thanks @damonbarry . And how about UWP / .Net?

**Comment by damonbarry** [comment]
Ah, sorry I left that out...  .Net is also in development. It will either be PCL or they'll have a UWP project for it.
