### ISSUE TITLE
Sending data to Serializer sample from DeviceExplorer results in errors

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#67]
While the documentation does not state explicitly that you can send data to the 'Serializer' sample it does mention that you can monitor the device.  This does work.  However, the DeviceExplorer page leads you to try sending data as a next step after monitoring data.

When sending a single word like 'hello' to the device you get the following errors:

Info: IoT Hub SDK for C, version 1.0.0-preview.3
IoTHubClient accepted the message for delivery
Message Id: 0 Received.
Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_OK
Error: Time:Tue Oct 13 13:14:30 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
Error: Time:Tue Oct 13 13:14:31 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
Error: Time:Tue Oct 13 13:14:31 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
Error: Time:Tue Oct 13 13:14:32 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
Error: Time:Tue Oct 13 13:14:32 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
Error: Time:Tue Oct 13 13:14:32 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
Error: Time:Tue Oct 13 13:14:32 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
Error: Time:Tue Oct 13 13:14:32 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
Error: Time:Tue Oct 13 13:14:33 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
Error: Time:Tue Oct 13 13:14:33 2015 File:..\..\src\commanddecoder.c Func:_CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed

**Comment by CarlosAlayo** [comment]
Thank you for the feedback. We will update our docs with a JSON sample for a command. Something like the following:
{"Name":"SetAirResistance","Parameters":{"Position":55}}
{"Name":"TurnFanOn","Parameters":{}}

**Comment by dominicbetts** [comment]
@jtanner-msft @CarlosAlayo I've added some additional information to the DeviceExplorer doc. Changes will be checked in shortly.
