### ISSUE TITLE
Node sample doesn't work

### ISSUE THREAD

**Issue by robotdad** [Azure/azure-iot-sdks#671]
Sample in the node readme doesn't work, needs to use client.open I think.
https://github.com/Azure/azure-iot-sdks/blob/master/node/device/core/readme.md 

Note this sample is also used on the npm page so should be updated there as well.
https://www.npmjs.com/package/azure-iot-device

**Comment by tameraw** [comment]
@robotdad - Thanks for filing this issue. @dominicbetts - Thanks for updating the doc.
