### ISSUE TITLE
Provide an ImportDevicesAsync taking in an IEnumerable<Device>

### ISSUE THREAD

**Issue by Praburaj** [Azure/azure-iot-sdks#673]
Device provisioning API - `ImportDevicesAsync` takes in a blob file. It will be more convenient if there is an overload of this method which takes in an `IEnumerable<Device>` or a local file path.

**Comment by tameraw** [comment]
Thanks for the feedback. We'll consider adding this in a future release. However, we happily accept contributions if you decide to submit a pull request for this.
https://github.com/Azure/azure-iot-sdks/blob/master/CONTRIBUTING.md

**Comment by rajeevmv** [comment]
The `RegistryManager` provides an `AddDevicesAsync` API which takes `IEnumerable<Device>` as input. The number of devices is limited to 100 per invocation.

**Comment by tameraw** [comment]
@Praburaj - Let us know if you have any other issues.
Regards.
