### ISSUE TITLE
[DM] Support for deep synchronization of custom device twin properties.

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/azure-iot-sdks#676]
At the moment a fixed set of Device twin Properties are kept in sync between the device and it's cloud twin, properties like UtcOffset and firmware details. 
Will it be possible to extend this list of properties with custom items? Or do we have to use 'standard' messaging methods to enable these scenarios?

**Comment by CarlosAlayo** [comment]
Hi Ted,
Yes, we plan to enable the ability to add custom properties to a device twin. Thank you.
Best regards,
Carlos.

**Comment by tedvanderveen** [comment]
@CarlosAlayo thanks for your feedback! For what timeframe is support synchonized custom properties for device twins expected? Any milestone/release attached to this maybe?
