### ISSUE TITLE
[C][Linux][AMQP] IIoTHubMessage_SetMessageId does not set AMQP value

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#677]
Hi,

While setting a message id using this code
```
 if ( IoTHubMessage_SetMessageId(iotMsg, p_message->id.id) == IOTHUB_MESSAGE_OK) {
IOTHUBAGENT_LOG_INFO(logger_agent, "####[%s]...", IoTHubMessage_GetMessageId(iotMsg));
 }
```
All seems to work properly, but the message id is not set in the AMQP message.
The id is not present while in the message on the iot hub side (checked with custom code and device explorer)

**Comment by ewertons** [comment]
Hi @lmussier, thanks for reporting this issue.

Indeed I verified that this is a bug in our current code. A fix will be provided shortly.

**Comment by zerox1212** [comment]
Is this fixed yet? The same issue occurs on Python and Windows.

This python code is from the sample (message_id changed to a GUID)

```python
message = IoTHubMessage(msg_txt_formatted)
 # optional: assign ids
message.message_id = str(uuid.uuid1())
message.correlation_id = "correlation_%d" % i
```

This shows up in the IoT Hub stream.
```json
"EventProcessedUtcTime": "2016-07-20T20:44:46.6262895Z",
"PartitionId": 1,
"EventEnqueuedUtcTime": "2016-07-20T20:43:34.3240000Z",
"IoTHub": {
	"MessageId": null,
	"CorrelationId": null,
	"ConnectionDeviceId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"ConnectionDeviceGenerationId": "636046339888502271",
	"EnqueuedTime": "0001-01-01T00:00:00.0000000",
	"StreamId": null
```

I would really like to use the IoT Hub header for message ID and Correlation ID.

**Comment by ewertons** [comment]
Hi @lmussier , the fix is on the way. 
There were a couple other tasks that had to be prioritized this past week.

Regarding the repro on Python, it uses the same C library underneath, so the issue should be expected to be fixed with the same fix for the C client.

**Comment by zerox1212** [comment]
Thanks @ewertons . I'm actively working on a project that needs this so I'm looking forward to the fix.

**Comment by zerox1212** [comment]
Can you give details why this is a partial fix? Sorry I don't know C.

**Comment by ewertons** [comment]
hi @zerox1212 , this was a commit with part of the fix, which is being completed by another engineer.
The fix is on its way. I'll update this issue once it's in.

**Comment by tameraw** [comment]
@lmussier - fixed in the latest release.
