### ISSUE TITLE
[PEN Testing] DllImport search path not set

### ISSUE THREAD

**Issue by vishal-gandhi** [Azure/azure-iot-sdks#679]
/csharp/device/Microsoft.Azure.Devices.Client/Common/Interop/UnsafeNativeMethods.cs

Without explicit search paths set on utilizing DllImport for loading native dlls, the search order on Windows systems will search the current working directory first. An attacker is then able to introduce a malicious dll. SetDllDirectory can be explicitly set on each DllImport call

**Comment by anhashia** [comment]
Looking into this

**Comment by anhashia** [comment]
Investigating the issue

**Comment by anhashia** [comment]
Closing. Please re-activate if you still are having issues. Thanks !
