### ISSUE TITLE
Instructions have you update device agent string in wrong location

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#68]
Following this set of instructions for C# on Windows:

Build and run the sample

1.Start a new instance of Visual Studio 2015. Open the iothub_csharp_client.sln solution in the csharp folder in your local copy of the repository.

2.In Visual Studio, in Solution Explorer, navigate to the samples folder. In the DeviceClientAmqpSample project, open the ConnectionStrings.cs file.

3.Locate the following code in the file:
public const string DeviceConnectionString = "<replace>";

4.Replace  <replace>  with the connection string for your device. The section "Get device connection string or data" in the document How to use Device Explorer explains how to retrieve the connection string for your device. Save the changes.

It rather clearly asks you to open the file: ConnectionStrings.cs and replace the connection string that is defined there.  However, this does not work and if you try to debug the sample at this point you will get an exception thrown.

The reason for this is because the 'DeviceConnectionString is not used from the ConnectionString.cs file, it is instead defined again at the top of the file Program.cs.  If you do not update the 'DeviceConnectionString' in that file the sample will not work or run correctly.  This should be fixed to reference the correct file(s).

**Comment by dominicbetts** [comment]
@jtanner-msft  thanks for pointing this out. The document has been updated and will be checked in shortly.

@andrew-buckley it looks like the ConnectionString.cs file could be deleted from this project?

**Comment by dominicbetts** [comment]
Hi @andrew-buckley, can you remove the documentation label from this issue now? Thanks!

**Comment by tameraw** [comment]
@dominicbetts & @andrew-buckley 
The ConnectionString.cs file has been deleted. Please update the doc to no longer mention this file and to update the connectionstring variable directly in the sample (as is the case with all the samples for all the other clients)

**Comment by dominicbetts** [comment]
@tameraw the doc is already updated, you can close this issue now.

**Comment by tameraw** [comment]
Thanks @dominicbetts
