### ISSUE TITLE
No UWP support for Azure IoT service SDK libraries

### ISSUE THREAD

**Issue by atuzovic** [Azure/azure-iot-sdks#683]
https://www.nuget.org/packages/Microsoft.Azure.Devices currently cannot be added to UWP applications.

Received error message is:
**Package Microsoft.Azure.Devices 1.0.11 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot**

Is there a way around this?
Do you have any ETA when and if this will be supported?

Thank you!

**Comment by arturl** [comment]
@atuzovic: this is already implemented and will be supported in the next release (1.0.12)
