### ISSUE TITLE
Intel Edison - Sending and Receiving Messages in JSON Format Using C

### ISSUE THREAD

**Issue by cnvery** [Azure/azure-iot-sdks#685]
Hi,

I have managed to follow four tutorials from Microsoft as per below:
[Receive device-to-cloud messages](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-csharp-csharp-getstarted/#receive-device-to-cloud-messages)
[Create a simulated device app](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-csharp-csharp-getstarted/#create-a-simulated-device-app)
[Receiving messages on the simulated device](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-csharp-csharp-c2d/#receiving-messages-on-the-simulated-device)
[Send a cloud-to-device message from the app back end](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-csharp-csharp-c2d/#send-a-cloud-to-device-message-from-the-app-back-end)

Simulated device is able to send and receive messages from Microsoft Visual Studio 2015. All coding above are written in C# programming with JSON Format. I have no issue with these, since all are working properly.

However, I faced problem on configuring Intel Edison for sending messages (Which will replace simulated device). I wish to send and receive messages in C programming with JSON format, since all peripheral configuration all are written in C programming. 

My final aim is to send and receive messages between Intel Edison and Microsoft Visual Studio 2015 software.

Two Questons:
1) How to send messages from Intel Edison to the software since the sample code (_sprintf_s()_ and _IoTHubMessage_CreateFromByteArray()_) sending in string format instead of JSON format? I cant access **windSpeed** variable since it is string format.
2) How to receive messages from the software to Intel Edison since the sample code (_IoTHubMessage_GetByteArray()_) receiving in string format instead of JSON format? I cant access **windSpeed** variable since it is string format.

Without access to **windSpeed** variable, I cant do further processing in my Intel Edison.

C Programming for Intel Edison Sending Messages (Based on sample codes from [iothub_client_sample_amqp.c](https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c):
> sprintf_s(msgText, sizeof(msgText), "{\"deviceId\":\"Edison01\",\"windSpeed\":%.2f}", avgWindSpeed + (rand() % 4 + 2));
>                     if ((messages[i].messageHandle = IoTHubMessage_CreateFromByteArray((const unsigned char*)msgText, strlen(msgText))) == NULL)
>                     {
>                         (void)printf("ERROR: iotHubMessageHandle is NULL!\r\n");
>                     }

C# Programming for Simulated Device Sending Messages: 
> private static async void SendDeviceToCloudMessagesAsync()
>         {
>             Random rand = new Random();
> 
>             while (true)
>             {
>                 int variable1 = rand.Next(1, 50);
>                 int variable2 = rand.Next(1, 50);
>                 int variable3 = rand.Next(1, 50);
> 
>                 var telemetryDataPoint = new
>                 {
>                     deviceId = "Lenovo01",
>                     nt1 = variable1,
>                     et1 = variable2,
>                     st1 = variable3,
>                 };
> 
>                 var messageString = JsonConvert.SerializeObject(telemetryDataPoint);
>                 var message = new Message(Encoding.ASCII.GetBytes(messageString));
> 
>                 await deviceClient.SendEventAsync(message);
>                 Console.WriteLine("{0} > Sending message: {1}", DateTime.Now, messageString);
> 
>             }
>         }

C Programming for Intel Edison Receiving Messages (Based on sample codes from [iothub_client_sample_amqp.c](https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c):
> outcome = IoTHubMessage_GetByteArray(messages[i].messageHandle, &buffer, &size);
> 						(void)printf("Received ByteArray Data: %d\r\n", buffer[i]);

C# Programming for Simulated Device Receiving Messages: 

> private async Task ReceiveMessagesFromDeviceAsync(string partition)
>         {
>             var eventHubReceiver = eventHubClient.GetDefaultConsumerGroup().CreateReceiver(partition, DateTime.UtcNow);
> 
>             while (true)
>             {
>                 EventData eventData = await eventHubReceiver.ReceiveAsync();
>                 if (eventData == null) continue;
> 
>                 string data = Encoding.UTF8.GetString(eventData.GetBytes());
>                 dynamic test = JsonConvert.DeserializeObject(data);
> 
>                 Junction Junction1;            // Declare structures
> 
>                 // Junction 1 Variables Initialization
>                 Junction1.north_traffic = test.nt1;
>                 Junction1.east_traffic = test.et1;
>                 Junction1.south_traffic = test.st1;
> 
>                 Main();
>             }
>         }

Hope someone could solve my doubts.

Thanks!

**Comment by markrad** [comment]
Hi @cnvery,

As I understand it, you are trying to process JSON data on an Intel Edison for both sending messages and receiving messages. The call to _IoTHubMessage_GetByteArray_ doesn't really care what the data is. If it is a string containing JSON then that is what it will send. Building such a string is likely not difficult but decoding JSON coming from the Cloud is going to be more challenging. Obviously manually parsing it will be error prone and not very maintainable and, since the IoT SDK does **not** provide this facility, you will need to look for an alternative library to assist you with this. 
I did some research into JSON libraries that are currently available. I picked Jansson which seemed to be well thought of and downloaded it to my Edison. I was able to successfully build this library and the built in test suite passed. From this it would seem to be a reasonable candidate to assist you with your JSON handling. You can find further information here: https://jansson.readthedocs.io/en/2.7/index.html.
Please let me know if you have any further questions.
_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

You are right.

I tried to send JSON data from Visual Studio 2015 to Intel Edison, and it pop up error on _decoding JSON to a multi tree failed_.

Is the IoT SDK does not provide facility for C only? Or it does not supports for Node.js too?

Since Node.js commonly is used with JSON.

In my opinion, it is quite weird that IoT SDK does not support JSON facility. This is due to IoT devices used JSON frequently for data transmission via Wi-Fi.

Details on Intel Edison running **simplesample_amqp,c**:
> root@edison01:~# ./simplesample_amqp
> Info: IoT Hub SDK for C, version 1.0.5
> IoTHubClient accepted the message for delivery
> Serialize Success!!
> -> Header (AMQP 0.1.0.0)
> <- Header (AMQP 0.1.0.0)
> -> [OPEN]* {default_container_id,trafficIoT.azure-devices.net,4294967295,65535}
> <- [OPEN]* {DeviceGateway_741400d2bfe846e49f5d005521275a40,10.0.0.29,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
> -> [BEGIN]* {NULL,0,4294967295,100,4294967295}
> <- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
> -> [ATTACH]* {cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,65535}
> -> [ATTACH]* {cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,65535}
> <- [ATTACH]* {cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,65535,NULL,NULL,NULL}
> <- [FLOW]* {0,100,1,5000,0,0,100,0,NULL,false,NULL}
> <- [ATTACH]* {cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65535,NULL,NULL,NULL}
> -> [FLOW]* {NULL,4294967295,0,100,1,0,10000}
> -> [TRANSFER]* {0,0,<00 00 00 00>,0,false,false}
> <- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
> <- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> -> [DISPOSITION]* {true,0,0,true,* {}}
> -> [ATTACH]* {receiver-link,2,true,0,0,* {amqps://trafficIoT.azure-devices.net/devices/Edison01/messages/devicebound},* {ingress-rx},NULL,NULL,NULL,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.5]}}
> Info: Event sender state changed [0->1]
> -> [ATTACH]* {sender-link,3,false,0,0,* {ingress},* {amqps://trafficIoT.azure-devices.net/devices/Edison01/messages/events},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.5]}}
> <- [ATTACH]* {receiver-link,2,false,0,0,* {amqps://trafficIoT.azure-devices.net/devices/Edison01/messages/devicebound,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {ingress-rx,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.5]}}
> -> [FLOW]* {NULL,4294967294,1,99,2,0,10000}
> <- [ATTACH]* {sender-link,3,true,0,NULL,* {ingress,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://trafficIoT.azure-devices.net/devices/Edison01/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.0.5]}}
> Info: Event sender state changed [1->2]
> <- [FLOW]* {1,100,2,4294967292,3,0,1000,0,NULL,false,NULL}
> -> [TRANSFER]* {3,1,<00 00 00 00>,0,false,false}
> <- [DISPOSITION]* {true,1,NULL,true,* {},NULL}
> Message Id: 0 Received.
> Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_OK
> <- [TRANSFER]* {2,1,<97 F3 9F 47 F8 BF 2D 4D 89 32 A2 C9 2D 0F 11 CE>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:21 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,1,1,true,* {}}
> <- [TRANSFER]* {2,2,<A5 A6 6A 7A EA 41 19 49 A1 F7 C2 F7 C2 E4 E8 6A>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:21 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,2,2,true,* {}}
> <- [TRANSFER]* {2,3,<9E 83 D1 C5 96 54 BD 4A 85 5C 96 65 6B 6B F2 05>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:21 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,3,3,true,* {}}
> <- [TRANSFER]* {2,4,<AE F4 C8 35 B6 4F 4D 43 93 E4 DB BE 2B E1 E1 F9>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:21 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,4,4,true,* {}}
> <- [TRANSFER]* {2,5,<E5 37 C1 5E 3F C6 73 40 85 D3 C0 AF 96 89 CA 24>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:21 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,5,5,true,* {}}
> <- [TRANSFER]* {2,6,<D1 C9 9A 53 B6 91 5E 4A 91 33 D8 7E D8 24 F9 ED>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:21 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,6,6,true,* {}}
> <- [TRANSFER]* {2,7,<6B 2C C6 C2 CE C9 AA 42 B8 63 EE 99 E3 EA 41 44>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:21 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,7,7,true,* {}}
> <- [TRANSFER]* {2,8,<74 CE 6F B3 52 8F 22 4B AC 14 D2 0D 91 A8 3E 4A>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:21 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,8,8,true,* {}}
> <- [TRANSFER]* {2,9,<99 44 58 16 46 A4 6C 4A 92 6E 46 7B 40 FE 0A 59>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,9,9,true,* {}}
> <- [TRANSFER]* {2,10,<C2 7F 27 54 70 43 EB 48 95 38 79 B5 F8 56 87 42>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,10,10,true,* {}}
> <- [TRANSFER]* {2,11,<1A 7C 65 19 10 27 77 46 89 F2 8F E5 E3 35 DF 17>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,11,11,true,* {}}
> <- [TRANSFER]* {2,12,<AF 9C 6B 94 F7 54 56 4E B0 38 38 73 85 46 4D 70>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,12,12,true,* {}}
> <- [TRANSFER]* {2,13,<2B CE BF ED D9 C2 5D 45 B1 BC 40 C7 3D 75 01 B2>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,13,13,true,* {}}
> <- [TRANSFER]* {2,14,<A4 53 4C 35 48 CE D1 4C B1 BD 13 6E D5 FE 69 BB>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,14,14,true,* {}}
> <- [TRANSFER]* {2,15,<D6 9D 4C F2 BE 17 CC 43 A3 A2 7C CE 61 F6 AC 02>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,15,15,true,* {}}
> <- [TRANSFER]* {2,16,<67 DF 92 30 CA 0B 17 4A AC 58 14 CA 33 A7 EA 64>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,16,16,true,* {}}
> <- [TRANSFER]* {2,17,<FA 28 53 24 8A C5 89 4D AF 80 E3 AF 1D 02 9A F2>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,17,17,true,* {}}
> <- [TRANSFER]* {2,18,<4A EE 6A EF 74 3E 50 49 AA C3 10 97 A4 6A 65 B8>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,18,18,true,* {}}
> <- [TRANSFER]* {2,19,<CC 79 3E 86 33 25 85 45 93 8E F1 40 F1 1D 26 97>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,19,19,true,* {}}
> <- [TRANSFER]* {2,20,<E5 72 46 91 0B 95 79 4A AE FD 0D C8 6B 87 97 E4>,0,NULL,false,NULL,NULL,NULL,NULL,false}
> Error: Time:Thu Jul  7 08:54:22 2016 File:/home/osboxes/Source/azure-iot-sdks/c/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteCommand Line:464 Decoding JSON to a multi tree failed
> Received Messages Success!!
> -> [DISPOSITION]* {true,20,20,true,* {}}

**Comment by markrad** [comment]
Hi @cnvery,

Without seeing your code I can't theorize where your error may lie. You might try dumping the received JSON to the console in order to assess its validity prior to attempting to decode it.

The serializer sample at azure-iot-sdks-build\c\serializer\samples\simplesample_amqp\simplesample_amqp.c attempts to abstract away some of the data format management but I'm not sure if it will solve your issue.

To address you questions. 

Yes there is a node.js npm package for communicating with the Azure IoT Hub. You can find further information here: https://azure.microsoft.com/en-us/documentation/articles/iot-hub-node-node-getstarted/

To support JSON directly in the C SDK would require either implementing a JSON parser or embedding an already existing parser. Either way this would increase the memory footprint of the library potentially making it unusable on smaller devices. Since there are many open source offerings already available, it would seem more prudent to have the developer include one of those libraries if required. This minimizes the dependencies of our code and reduces maintenance complexities.

Let me know if I can be of further assistance.

_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

I tried decoding JSON using [JSMN](http://zserge.com/jsmn.html), which is much simpler compared to Jansson. It consist only two files: **jsmn.c** and **jsmn.h**.

I copy these files into _azure-iot-sdks\c\serializer\samples\simplesample_amqp\windows_ folder and complied using Microsoft Visual Studio 2015. It is successfully complied and able to receive JSON messages correctly.

I do the same things by copying into same directory just now and [cross compie Azure IoT SDK in Ubuntu OS](https://github.com/Azure/azure-iot-sdks/issues/435). However, it failed as per [this image link](https://s32.postimg.org/wofe462px/Capture.jpg)

May I know why it failed to compile the files? Since Microsoft Visual Studio 2015 is able to compile the same files without any issues.

Thanks!

**Comment by markrad** [comment]
Hi @cnvery,

The problem you are seeing is that fact that the make files generated by the build.sh script know nothing about your additional files so they were not compiled thus were not available as .a files to resolve the link externs you are seeing.

I would recommend that you try the following: 
* Cross compile the SDK without any changes in the tree. 
* In a separate directory place your source code and the two files from JSMN
* Create a makefile to build your source code and the two JSMN files

Just to give you a bit of a head start, below I have included a makefile that will cross compile a single source file called main.c against the Raspberry Pi cross compile environment. You will need to modify it to use the Edison cross compile environment and you will need to add a build rule for jsmn.c and add it to the BINS variable as jsmn.o.
```makefile
# This is the location of your cross compiler (in this case for Raspberry Pi)
CC = /home/markrad/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/../bin/arm-linux-gnueabihf-gcc

INCDIRS = \
    -I $$HOME/Source/azure-iot-sdks-xcomp/c/azure-c-shared-utility/inc/azure_c_shared_utility \
    -I $$HOME/Source/azure-iot-sdks-xcomp/c/azure-c-shared-utility/inc \
    -I $$HOME/Source/azure-iot-sdks-xcomp/c/azure-c-shared-utility/c/inc \
    -I $$HOME/Source/azure-iot-sdks-xcomp/c/iothub_client/inc

# --sysroot identifies the alternative root for locating include files and libraries
CFLAGS = --sysroot=/home/markrad/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf -D__STDC_NO_ATOMICS__ -std=gnu99

C_DEFINES = -DARCHITECTURE_ARM=1

BINS = main.o

# This should identify the libraries built when you cross compiled the SDK
LIBDIRS = \
    -L $$HOME/Source/azure-iot-sdks-xcomp/c/cmake/iotsdk_linux/iothub_client \
    -L $$HOME/Source/azure-iot-sdks-xcomp/c/cmake/iotsdk_linux/azure-c-shared-utility/c/ \
    -L $$HOME/Source/azure-iot-sdks-xcomp/c/cmake/iotsdk_linux/azure-uamqp-c \
    -L $$HOME/Source/azure-iot-sdks-xcomp/c/cmake/iotsdk_linux/azure-umqtt-c \
    -L $$HOME/Source/azure-iot-sdks-xcomp/c/cmake/iotsdk_linux/azure-c-shared-utility \
    -L $$HOME/Source/azure-iot-sdks-xcomp/c/cmake/iotsdk_linux/azure-uamqp-c/libwebsockets/lib 

LIBS = \
    -liothub_client_amqp_transport \
    -liothub_client_http_transport \
    -luamqp \
    -lumqtt \
    -liothub_client \
    -laziotsharedutil \
    -lcurl \
    -lssl \
    -lcrypto \
    -lpthread

TARGETS = testapp

###############################################################################
	
.PHONY: all
all: $(TARGETS)

.PHONY: clean
clean:
	rm -f $(TARGETS)
	rm -f $(BINS)

###############################################################################

testapp: $(BINS)
	$(CC) -o testapp $(CFLAGS) $(LIBDIRS) $(BINS) $(LIBS) 

###############################################################################

main.o: main.c
	$(CC) -c $(C_DEFINES) $(CFLAGS) $(INCDIRS) main.c
```
I hope this helps.

_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

I am confused about where the files should be put at.

Is this what you mean, where all files are put on same folder as per below?

**Project1 Folder**, there are following files:
_jsmn.c
jsmn.h
Project1.c
makefile_

Thanks!

**Comment by markrad** [comment]
Hi @cnvery,

Yes that is exactly what you need to do. Your BINS line would look like this:
```
BINS = main.o \
       jsmn.o
```
You will also need to add:
```
jsmn.o: jsmn.c
    $(CC) -c $(C_DEFINES) $(CFLAGS) $(INCDIRS) jsmn.c
```

You would also modify all instances of testapp to be whatever you want your final executable to be called.

_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

I tried your method but it does not works.

**cmake** will only build default sample directories such as _simplesample_amqp_ and _simplesample_http_, ignoring new folder I created despite having these four files.

Instead, I tried on create **CMakeLists.txt** under same folder and it build successfully!!!

CMakeLists.txt Code:
> #Copyright (c) Microsoft. All rights reserved.
> #Licensed under the MIT license. See LICENSE file in the project root for full license information.
> 
> #this is CMakeLists.txt for simplesample_amqp sample
> 
> compileAsC99()
> 
> if(NOT ${use_amqp})
> 	message(FATAL_ERROR "Project1 being generated without amqp support")
> endif()
> 
> set(Project1_c_files
> jsmn.c
> )
> 
> 	set(Project1_c_files ${Project1_c_files} ./main.c)
> 
> set(Project1_h_files
> jsmn.h
> )
> 
> include_directories(. ${SHARED_UTIL_INC_FOLDER} ${IOTHUB_CLIENT_INC_FOLDER})
> link_directories(${whatIsBuilding}_dll ${SHARED_UTIL_LIB_DIR})
> 
> add_executable(Project1 ${Project1_c_files} ${Project1_h_files})
> 
> target_link_libraries(Project1 serializer iothub_client iothub_client_amqp_transport)
> 
> linkSharedUtil(Project1)
> linkUAMQP(Project1)

I have one last question for this issue.

If I wish to add another c code and header files, I just simple add _sample123.c_ under _set(Project1_c_files sample123.c)_ and _sample123.h_ under _set(Project1_h_files sample123.h)_?

Since I dont actually understand 100% how these code works.

**Comment by markrad** [comment]
Hi @cnvery,
I am curious to know why it didn't work for you. I build samples in that manner all the time. Was there some sort of typo in my instructions or was I too vague? Yes, I think what you suggest will work. The reason that I recommend that you pull your code out of the Azure IoT SDKs tree is that you do not 'pollute' the SDKs GitHub clone. 
Can you let me know what issues you had? I would appreciate it.
_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

When I build using makefile for my project, it poped up this error:
`The source directory ..... does not contain a CMakeLists.txt file`

Configuration of makefile for my project:
> # This is the location of your cross compiler (in this case for Intel Edison)
> CC = /opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux//../x86_64-pokysdk-linux/usr/libexec/i586-poky-linux/gcc/i586-poky-linux/4.9.1/gcc
> 
> INCDIRS = \
>     -I $$HOME/Source/azure-iot-sdks/c/azure-c-shared-utility/inc/azure_c_shared_utility \
>     -I $$HOME/Source/azure-iot-sdks/c/azure-c-shared-utility/inc \
>     -I $$HOME/Source/azure-iot-sdks/c/azure-uamqp-c/inc/azure_uamqp_c \
>     -I $$HOME/Source/azure-iot-sdks/c/azure-uamqp-c/inc \
>     -I $$HOME/Source/azure-iot-sdks/c/azure-umqtt-c/inc/azure_umqtt_c \
>     -I $$HOME/Source/azure-iot-sdks/c/azure-umqtt-c/inc \
>     -I $$HOME/Source/azure-iot-sdks/c/iothub_client/inc \
>     -I $$HOME/Source/azure-iot-sdks/c/serializer/inc
> 
> # --sysroot identifies the alternative root for locating include files and libraries
> CFLAGS = --sysroot=/opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux -D__STDC_NO_ATOMICS__ -std=gnu99
> 
> # C_DEFINES = -DARCHITECTURE_ARM=1
> 
> BINS = main.o \
>        jsmn.o
> 
> # This should identify the libraries built when you cross compiled the SDK
> LIBDIRS = \
>     -L $$HOME/Source/azure-iot-sdks/c/iothub_client \
>     -L $$HOME/Source/azure-iot-sdks/c/serializer \
>     -L $$HOME/Source/azure-iot-sdks/c/azure-uamqp-c \
>     -L $$HOME/Source/azure-iot-sdks/c/azure-umqtt-c \
>     -L $$HOME/Source/azure-iot-sdks/c/azure-c-shared-utility \
>     -L $$HOME/Source/azure-iot-sdks/c/azure-uamqp-c/libwebsockets/lib 
> 
> LIBS = \
>     -liothub_client_amqp_transport \
>     -liothub_client_http_transport \
>     -luamqp \
>     -lumqtt \
>     -liothub_client \
>     -laziotsharedutil \
>     -lcurl \
>     -lssl \
>     -lcrypto \
>     -lpthread
> 
> TARGETS = testapp
> 
> ###############################################################################
> 
> .PHONY: all
> all: $(TARGETS)
> 
> .PHONY: clean
> clean:
>     rm -f $(TARGETS)
>     rm -f $(BINS)
> 
> ###############################################################################
> 
> testapp: $(BINS)
>     $(CC) -o testapp $(CFLAGS) $(LIBDIRS) $(BINS) $(LIBS) 
> 
> ###############################################################################
> 
> main.o: main.c
>     $(CC) -c $(C_DEFINES) $(CFLAGS) $(INCDIRS) main.c
> 
> jsmn.o: jsmn.c
>     $(CC) -c $(C_DEFINES) $(CFLAGS) $(INCDIRS) jsmn.c

Anyway, the issue for compiling sending and receive JSON messages is solved.

Thus, I closed this issue.

Thanks for your great help!

**Comment by markrad** [comment]
Hi @cnvery,

This is my fault. I should have specified that when you create a makefile in the format I provided you use the command _make_ not cmake. The make command will look for a makefile in the current directory and use it to build your code.

Regards,

_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

I found another new issue on receiving messages for Intel Edison.

You may refer to [this new issue link](https://github.com/Azure/azure-iot-sdks/issues/757).

Thanks!
