### ISSUE TITLE
DM Preview: Build.sh does not have flag parity with CMake

### ISSUE THREAD

**Issue by zafields** [Azure/azure-iot-sdks#688]
It is not possible to run the script with the `--no-amqp --no-http --no-mqtt` flags because there is no flag for disabling blob storage in `Build.sh`. This requires the inclusion of the parson submodule when trying to run the `iotdm_simple_sample` (found in `iotdm_edison_sample`).

**Comment by tameraw** [comment]
@zafields  - As we released a new public preview for Azure IoT Hub Device Management, we moved the related code and samples that were in this branch to a different repository. You can now find all Device Twins, Device Methods, and Device Management related code in this new repository: https://github.com/azure/azure-iot-sdks-preview. The current dmpreview branch should be considered  obsolete.
Closing this, and please feel free to let us know of any issues related to DM in that new repo. Thanks.
