### ISSUE TITLE
Add to tools the possibility to send messages with properties

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#689]
Hi,
using the device explorer (and for what I know the iothub explorer) it is impossible to send messages with properties.
Could you add this possibility to one of the tool ?

**Comment by tameraw** [comment]
@lmussier - Thanks for filing this.
We'll consider adding this in a future release. However, we would happily accept contributions if you decide to submit a pull request for this.
https://github.com/Azure/azure-iot-sdks/blob/master/CONTRIBUTING.md

**Comment by lmussier** [comment]
We'll do that, thanks.

**Comment by lmussier** [comment]
Our pull request was merged in develop, thanks.
