### ISSUE TITLE
Setting up IoT Devices

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#69]
It's unclear from the docs here if users should download the RTM version of Windows 10 IoT Core, or instead try an insider preview build:
Setting Up You Device

First of all, you need to set up your device.
•If you’re using Raspberry Pi, set up your device according to instructions here.
•If you’re using MinnowBoard Max set up your device according to instructions here.
•If you’re using Dragonboard setup instructions should come soon here.

Depending upon what you have tested with you might want to clarify that fact.

**Comment by dominicbetts** [comment]
@jtanner-msft thanks for pointing this out. I've added a recommendation in the docs to use the RTM version. The change will be checked in shortly.
