### ISSUE TITLE
[C#]Any plans for .NET Core?

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-iot-sdks#691]
Are there any plans for C# device sdk to work on .NET Core?

**Comment by tameraw** [comment]
@yfakariya - We currently have a PCL library. Only supports HTTP protocol for now, but plan to enable other protocols as well.

**Comment by yfakariya** [comment]
@tameraw Thank you. I'm looking forward to releasing AMQP/MQTT in PCL.
