### ISSUE TITLE
import error on python 2.7.9 shell on raspbian 

### ISSUE THREAD

**Issue by SKVasanth** [Azure/azure-iot-sdks#692]
Hi Team,

I am getting import error while running iohub_client_sample.py. **Import error: No module named iothub_client**, Refer attached image please. 

At that time of building I got errors (refer attached images). I ignored n tried with sample than landed into import error. I have used python 3.4 for setup.sh/build.sh (ex: **./build.sh --build-python 3.4**), These build errors are making issue now? I understand **iothub_client** module is not build properly.  Please help me to resolve this issue. 

Thanks in advance.

![import err](https://cloud.githubusercontent.com/assets/13313162/16654371/19b9f592-4473-11e6-878a-ba57e41b1f00.jpg)

![build err](https://cloud.githubusercontent.com/assets/13313162/16654601/2dcea7b6-4474-11e6-9955-f704c3a9de22.jpg)
![build err1](https://cloud.githubusercontent.com/assets/13313162/16654600/2dc94da2-4474-11e6-91d7-daf184570add.jpg)

**Comment by SKVasanth** [comment]
Hi Guys,
Its working now for me, I have missed sub modules and I executed below command n steps,
git clone -b develop --recursive https://github.com/Azure/azure-iot-sdks.git azure-iot-develop
Step1: navigated to **c/build_all/linux** and ran ./setup.sh n ./build.sh (igonored build errors)
Step2: navigated to **python/build_all/linux** and ran ./setup.sh n ./build.sh
           verified iothub_client.so presence in **python/device/samples folder**
And executed **iothub_client_sample.py** script and ensured received msgs using device explorer.

Thanks.

**Comment by lgarreta** [comment]
Hello,
I fixed that by changing the names of the deb repositories in the dir /etc/apt/sources.list.d
from  deb http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu trusty main (WRONG)
deb http://ppa.launchpad.net/aziotsdklinux/ppa-azure-iot-sdk-c/ubuntu trusty main (RIGHT)

At the end, it creates the iothub_client.so
