### ISSUE TITLE
[C][Linux][MQTT]Signal interrupts socketio_open causing socket failure

### ISSUE THREAD

**Issue by ebeistle** [Azure/azure-iot-sdks#694]
After adding a simple timer function to my application using SIGALRM, socketio_open() in azure-c-shared-utility\adapters\socketio_berkely.c began having failures to open the socket.

The select() function can be interrupted by a signal, causing it to return prematurely with EINTR.  This is not being handled in the socketio_open() function.

The solution is simply a matter of wrapping the select() call in a do-while loop.

The solution suggested below is based on the following post:
http://stackoverflow.com/a/6962247

Change the following:
````C
if (select(socket_io_instance->socket + 1, NULL, &fdset, NULL, &tv) != 1)
{
    LogError("Failure: select failure.");
    close(socket_io_instance->socket);
    socket_io_instance->socket = INVALID_SOCKET;
    result = __LINE__;
}
else
...
````
to:
````C
int retval = -1;
int select_errno = 0;

do
{
    retval = select(socket_io_instance->socket + 1, NULL, &fdset, NULL, &tv);

    if (retval < 0)
    {
        /* Cache the value of errno in case a system call is later
         * added prior to the loop guard (i.e., the while expression). */
        select_errno = errno;
    }

    /* Other system calls might be added here.  These could change the
     * value of errno, losing track of the error during the select(),
     * again this is the reason we cached the value.  (E.g, you might call
     * a log method which calls gettimeofday().) */

    /* Automatically restart the system call if it was interrupted by
     * a signal -- with a while loop. */
} while ((retval < 0) && (select_errno == EINTR));

if (retval != 1)
{
    LogError("Failure: select failure.");
    close(socket_io_instance->socket);
    socket_io_instance->socket = INVALID_SOCKET;
    result = __LINE__;
}
else
...
````

**Comment by markrad** [comment]
Hi @ebeistle,

Not being primarily a Linux developer, I had to research this a little more. If I understand this correctly, if you have a signal handler then you can override the default action with custom processing. A SIGHUP, for example, appears to be generally used to reload one's configuration files. Given that, am I correct in assuming that after you handle the signal, control will return to the select which will, in turn, return an error with errno set to EINTR? If that is the case then I can see why you would like the modifications you have suggested. 

_Mark Radbourne MSFT_

**Comment by ebeistle** [comment]
Yes I believe your understanding is correct.

**Comment by markrad** [comment]
HI @ebeistle,

I have checked in your suggested change. You will find it in the develop branch at time of writing.

_Mark Radbourne MSFT_
