### ISSUE TITLE
Intel Edison - Issue On Compiling Azure IoT SDK In Eclipse IDE

### ISSUE THREAD

**Issue by cnvery** [Azure/azure-iot-sdks#698]
Hi,
 
I managed to compile my Azure IoT SDK C programming project files (Without I/O and I2C Configuration) within Intel Edison itself using cmake via [cross-compiling](https://github.com/Azure/azure-iot-sdks/issues/435).

Now, I wish to compile the Azure IoT SDK C programming project files in the [Eclipse IDE](https://eclipse.org/).
 
Reason for choosing Eclipse IDE is my I/O and I2C C project files are compiled and runs sucessfully on Eclipse IDE. (I/O and I2C configuration requires **MRAA** library, thus Eclipse IDE is chosen due to its support of C programming languages)
 
Now, I have encountered compiling errors when trying to compile whole project files (Combined codes of Azure IoT SDK, I/O and I2C).
 
The errors are as per below:
**It cannot reference to some functions of Azure library (I have copied all required C header files from Azure folder and inserted into Eclipse)**
[Image 1](https://s32.postimg.org/a8j3z8fn9/image.jpg)
[Image 2](https://s31.postimg.org/72bo52ba3/image.jpg)

Below are the full list of header files I have included in Eclipse IDE:
_Current Directory - Precedent of Other Folders: azure_c_shared_utility, azure_uamqp_c and azure_umqtt_c_
> agenttypesystem.c
> agenttypesystem.h
> codefirst.c
> codefirst.h
> commanddecoder.c
> commanddecoder.h
> datamarshaller.c
> datamarshaller.h
> datapublisher.c
> datapublisher.h
> dataserializer.c
> dataserializer.h
> iotdevice.c
> iotdevice.h
> iothub_client.c
> iothub_client.h
> iothub_client_II.c
> iothub_client_II.h
> iothub_client_private.h
> iothub_client_version.h
> iothub_message.c
> iothub_message.h
> iothub_transport_II.h
> iothubtransport.c
> iothubtransport.h
> iothubtransportamqp.c
> iothubtransportamqp.h
> iothubtransportamqp_websockets.c
> iothubtransportamqp_websockets.h
> iothubtransporthttp.c
> iothubtransporthttp.h
> iothubtransportmqtt.c
> iothubtransportmqtt.h
> jsondecoder.c
> jsondecoder.h
> jsonencoder.c
> jsonencoder.h
> multitree.c
> multitree.h
> schema.c
> schema.h
> schemalib.c
> schemalib.h
> schemaserializer.c
> schemaserializer.h
> serializer.h
> version.c

_azure_c_shared_utility Folder_
> agenttime.h
> base64.c
> base64.h
> buffer.c
> buffer_.h
> condition.h
> constbuffer.c
> constbuffer.h
> constmap.c
> constmap.h
> crt_abstractions.c
> crt_abstractions.h
> doublylinkedlist.c
> doublylinkedlist.h
> gb_stdio.c
> gb_stdio.h
> gb_time.c
> gb_time.h
> gballoc.c
> gballoc.h
> hmac.c
> hmac.h
> hmacsha256.c
> hmacsha256.h
> httpapi.h
> httpapiex.c
> httpapiex.h
> httpapiexsas.c
> httpapiexsas.h
> httpheaders.c
> httpheaders.h
> iot_logging.h
> list.c
> list.h
> lock.h
> macro_utils.h
> map.c
> map.h
> platform.h
> refcount.h
> sastoken.c
> sastoken.h
> sha.h
> sha1.c
> sha224.c
> sha384-512.c
> sha-private.h
> socketio.h
> stdint_ce6.h
> string_tokenizer.c
> string_tokenizer.h
> strings.c
> strings.h
> threadapi.h
> tickcounter.h
> tlsio.h
> tlsio_openssl.c
> tlsio_openssl.h
> tlsio_schannel.c
> tlsio_schannel.h
> tlsio_wolfssl.c
> tlsio_wolfssl.h
> umock_c_prod.h
> uniqueid.h
> urlencode.c
> urlencode.h
> usha.c
> vector.c
> vector.h
> xio.c
> xio.h
> xlogging.h

_azure_uamqp_c Folder_
> amqp_definitions.c
> amqp_definitions.h
> amqp_frame_codec.c
> amqp_frame_codec.h
> amqp_management.c
> amqp_management.h
> amqp_types.h
> amqpalloc.c
> amqpalloc.h
> amqpvalue.c
> amqpvalue.h
> amqpvalue_to_string.c
> amqpvalue_to_string.h
> cbs.c
> cbs.h
> connection.c
> connection.h
> consolelogger.c
> consolelogger.h
> frame_codec.c
> frame_codec.h
> header_detect_io.c
> header_detect_io.h
> link.c
> link.h
> logger.h
> message.c
> message.h
> message_receiver.c
> message_receiver.h
> message_sender.c
> message_sender.h
> messaging.c
> messaging.h
> sasl_anonymous.c
> sasl_anonymous.h
> sasl_frame_codec.c
> sasl_frame_codec.h
> sasl_mechanism.c
> sasl_mechanism.h
> sasl_mssbcbs.c
> sasl_mssbcbs.h
> sasl_plain.c
> sasl_plain.h
> saslclientio.c
> saslclientio.h
> session.c
> session.h
> socket_listener.h
> socket_listener_win32.c
> wsio.c
> wsio.h

_azure_umqtt_c Folder_
> mqtt_client.c
> mqtt_client.h
> mqtt_codec.c
> mqtt_codec.h
> mqtt_message.c
> mqtt_message.h
> mqttconst.h

May I know is there any solution for this? 

Did I miss out any important header files?

Hope someone will solve my doubt.

Thanks!

**Comment by markrad** [comment]
Hi @cnvery,

I'm not particularly familiar with Eclipse but, speaking in general of development IDEs, you have three tasks in order to build against a third party code base such as the Azure-IoT-SDKs. 

1. Build the SDK as per the instructions
2. In your IDE tell it the location of any required header files
3. In you IDE tell it the location of any required libraries

It is not a good idea to extract portions of the SDK code and put them in your project. It will make it very difficult for you to pull new updates from GitHub.

Looking at your output, I suspect that the link step failed rather than the compile step. This is because it is trying to resolve the external functions that are being called from the code.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @cnvery,
Do you need further assistance with this issue?

_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

I knew that I cannot extract portions of the SDK code and put them in my project.

There are number of different header/include files in _azure-iot-sdks_ folder.

These files are located under different folders such as _azure-c-shared-utility_, _azure-uamqp-c_, _azure-umqtt-c_, _iothub_client_ and _serializer_.

I tried to include directory for _azure-iot-sdks_ folder, but it does not works. (Same problem)

Should I copy all these header/include files into one new folder and just include that directory?

Thanks!

**Comment by cnvery** [comment]
Hi @markrad,

I tell Eclipse IDE again by specifing location of all required header files and libraries.

The includes in Eclipse IDE is shown in [this image](https://s32.postimg.org/6n0aoy1yd/5345.jpg).

However, it is unable to reference for some variables despite all header/library are included, which is shown in [this image](https://s32.postimg.org/a8j3z8fn9/image.jpg).

May I know which part is going wrong?

Thank in advance.

**Comment by markrad** [comment]
Hi @cnvery,

Can you attach your Eclipse project to this thread? I'll try using it to build the project and update you on my findings.

_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

Here is my Eclipse project files.
[Azure_Edison.zip](https://github.com/Azure/azure-iot-sdks/files/402055/Azure_Edison.zip)

If Eclipse IDE can successfully build Azure sample project _simplesample_amqp.c_ without any errors, then this issue topic can be closed.

Thanks!

**Comment by markrad** [comment]
Hi @cnvery,

Just to be clear, are you running Eclipse on your Edison (can you even do that?) or are you trying to set up a cross compile environment in Eclipse to build your Edison binaries?

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @cnvery,

Since you have not responded in almost two weeks I am closing this issue. Please feel free to reopen it if you need.

_Mark Radbourne MSFT_

**Comment by cnvery** [comment]
Hi @markrad,

The problem still remain, and I dont have privilege to re-open this issue.

Just to be clear, are you running Eclipse on your Edison (can you even do that?) 
**Ans: My Eclipse project without Azure C SDK is able to compile succesfully in Eclispe software** 

or are you trying to set up a cross compile environment in Eclipse to build your Edison binaries?
**Ans: I wish to compile my Eclipse project together with Azure C SDK in Eclipse software, but currently still  have problem**

Thanks!

**Comment by markrad** [comment]
On what platform is Eclipse running?

**Comment by cnvery** [comment]
Hi @markrad,

The Eclipse Platform is:
Version: Luna SR2 (4.4.2)
Build id: M20150204-1700

**Comment by markrad** [comment]
Hi @cnvery,

Is Eclipse running **on the Edison** or on a desktop machine?

**Comment by jtanner-msft** [comment]
Hi @cnvery,

  As we haven't seen a response to Mark's question in a few weeks now I'm going to close this issue.  If you do still require assistance please feel free to re-open the issue and provide the answer on if Eclipse was running on the Edison device, or a desktop system.  If it was a desktop, what OS were you running on?
Thanks,
