### ISSUE TITLE
[C][Linux][AMQP] A message send with no payload (from the device explorer) never reach the device

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#699]
Hi,

I'm experiencing a strange behavior with Device Explorer and a C client.
If a send a message with no payload (Message edit box left black) the device explorer sends the message to the hub 
`Sent to Device ID: [ludo], Message:"", message Id: 15544f45-135e-45b3-a6b4-c32c5e3c0233`
But the C SDK never gets it, the message is still stored in the hub, as shown by the message count column on management tab.

If  I send the message with a payload (Message edit box contains something) the message finds its way through the device.

Do we have to set payloads to every massage we send or this behavior is not intended ?

**Comment by tameraw** [comment]
@lmussier - Thanks for filing this. Looking at this issue.

**Comment by tameraw** [comment]
Reproduced it and working on a fix.

**Comment by chrit-msft** [comment]
@lmussier A fix for this has been checked in to the develop branch.  I will be closing this GitHub thread.  If you see this behavior return please reach out immediately.
