### ISSUE TITLE
Cross-compiling for Raspberry Pi 3 from Ubuntu 14.04 seems to be out of date

### ISSUE THREAD

**Issue by zfields** [Azure/azure-iot-sdks#700]
Either the Azure IoT Hub SDK has advanced beyond the basic library files on the Raspberry Pi toolchain targeted in your instructions, or the toolchain has been reorganized since the directions were created.

Either way, the directions provided for cross-compiling for a Raspberry Pi are not working.

**Comment by zfields** [comment]
Warnings: 

```
CMake Warning: 
  Manually-specified variables were not used by the project: 
 
    run_valgrind 
    use_wsio 

============= 

<command-line>:0:0: warning: "__STDC_NO_ATOMICS__" redefined [enabled by default] 
```
Errors: 
```
/home/zafields/azure-iot-sdks/c/azure-c-shared-utility/adapters/uniqueid_linux.c:7:23: fatal error: uuid/uuid.h: No such file or directory 
 #include <uuid/uuid.h> 
                       ^ 
compilation terminated. 
make[2]: *** [azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/uniqueid_linux.c.o] Error 1 
make[1]: *** [azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/all] Error 2 
[ 60%] make[1]: *** Waiting for unfinished jobs.... 

============ 

/home/zafields/azure-iot-sdks/c/wakaama/platforms/Linux/platform.c: In function ‘lwm2m_strdup’: 
/home/zafields/azure-iot-sdks/c/wakaama/platforms/Linux/platform.c:38:12: warning: incompatible implicit declaration of built-in function ‘strdup’ [enabled by default] 
     return strdup(str); 
            ^ 
Linking C static library libiotdm_client.a 
[ 75%] Built target iotdm_client 
make: *** [all] Error 2 

============ 

/home/zafields/azure-iot-sdks/c/azure-c-shared-utility/src/tlsio_openssl.c:9:25: fatal error: openssl/ssl.h: No such file or directory 
 #include "openssl/ssl.h" 
                         ^ 
compilation terminated. 
make[2]: *** [azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o] Error 1 
make[2]: *** Waiting for unfinished jobs.... 

============ 

/home/zafields/azure-iot-sdks/c/azure-c-shared-utility/adapters/httpapi_curl.c:14:23: fatal error: curl/curl.h: No such file or directory 
 #include "curl/curl.h" 
                       ^ 
compilation terminated. 
make[2]: *** [azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/httpapi_curl.c.o] Error 1 
make[1]: *** [azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/all] Error 2 
make: *** [all] Error 2
```

**Comment by lmussier** [comment]
@zfields Do you have curl and libuuid installed ?
It seems these libs are missing, do you follow the steps [here](https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md)

Since you compile on the raspberry, you have to see it as a "devbox".

**Comment by zfields** [comment]
@lmussier Thank you for responding! To clarify, I am not building on my Raspberry Pi directly, but cross-compiling from Ubuntu 14.04.  On my Ubuntu machine, I already have the most recent `curl` and `openssl` available. I checked `libuuid` as you suggested, but `apt-get` was "unable to locate package".

As a note, the link you provided it does not specify installing `libuuid` or `curl` as a dependency, perhaps the documentation could be upgraded.

**Comment by markrad** [comment]
Hi @zafields,

To be clear, you are following this document: https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md?

The toolchain effectively mimics the file system on the Raspberry Pi 2 so a reorganization is unlikely. I ran a Raspberry Pi 2 cross compile in the last week or two so I know that it works as described. I have not ever tried to use these instructions to cross compile for a Raspberry Pi 3. According to ARM's website software built for the A7 will run on the A53 in 32 bit compatibility mode. I have not seen a Raspberry Pi 3 cross compile tool chain.

One other point, when @lmussier asked if you had curl and libuuid installed that was referring to being installed on the Raspberry Pi. You are copying all those files from your Pi to your desktop. If they weren't installed on your Pi then they won't be in your cross compile environment. For example, on my Pi I see uuid.h in /usr/include/uuid which would have been copied to your desktop by the rsync command if it existed on your Pi.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
@zfields are you still having problems with your cross compile?

**Comment by zfields** [comment]
@markrad Thanks for checking back. I haven't had an opportunity to revisit this. I do have `curl` and `openssl` installed on the pi, so I left this for the moment.

I've noticed the toolchain has a separate folder for the raspberry pi 3, so I thought I would need to attempt to extrapolate the instructions you've provided in your documentation for the tools in the raspberry pi 3 section.

I'll respond here when I have time to attempt this.

Thanks,
Zak

**Comment by markrad** [comment]
Hi @zfields,

I have closed this issue for the time being. Please reopen it when you have time to address this again.

Regards,

_Mark Radbourne MSFT_
