### ISSUE TITLE
[C][Yocto-Linux][AMQP]Help for "AMQP transport authentication timed out" error

### ISSUE THREAD

**Issue by RamPrasadRP** [Azure/azure-iot-sdks#701]
Running the serializer samples - "remote_monitoring" & "simplesample_amqp" in my ARM device throws the following error:

./remote_monitoring
IoTHubClient accepted the message for delivery
Sending sensor value Temperature = 50, Humidity = 50
IoTHubClient accepted the message for delivery
Sending sensor value Temperature = 50, Humidity = 50
IoTHubClient accepted the message for delivery
Sending sensor value Temperature = 50, Humidity = 50
IoTHubClient accepted the message for delivery
Sending sensor value Temperature = 50, Humidity = 50
IoTHubClient accepted the message for delivery
Sending sensor value Temperature = 50, Humidity = 50
IoTHubClient accepted the message for delivery
**Error: Time:Tue Jul 12 14:45:21 2016 File:/home/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1469 AMQP transport authentication timed out.**

I don't find such error while running a sample http application. How to solve this? Thanks

**Comment by chrit-msft** [comment]
@RamPrasadRP Thank for your raising this issue.  I have an ARM device that I will try to get a local repro on and let you know the results.

**Comment by chrit-msft** [comment]
@RamPrasadRP This is probably an issue with your certificate validation, can you try using the this call from the remote_monitoring sample (remove the ifdef)?
```c
#ifdef MBED_BUILD_TIMESTAMP
                // For mbed add the certificate information
                if (IoTHubClient_SetOption(iotHubClientHandle, "TrustedCerts", certificates) != IOTHUB_CLIENT_OK)
                {
                    printf("failure to set option \"TrustedCerts\"\r\n");
                }
#endif // MBED_BUILD_TIMESTAMP
```
the only issue is you need to copy the array of certs from certs.c into your file (code).

**Comment by chrit-msft** [comment]
@RamPrasadRP I am closing this issue.  If after following the steps in my last post you still see this behavior please reopen this issue and reach out immediately.
