### ISSUE TITLE
[C][MQTT]Packet ID mismatch in iothubtransportmqtt.c causes all retries to fail

### ISSUE THREAD

**Issue by ebeistle** [Azure/azure-iot-sdks#702]
publishMqttMessage() creates an MQTT message with transportState->packetId as the packet ID and increments transportState->packetId.

MqttOpCompleteCallback() compares incoming ACK packet IDs to mqttMsgEntry->msgPacketId.

IoTHubTransportMqtt_DoWork() saves the packed ID in mqttMsgEntry->msgPacketId prior to calling publishMqttMessage() when it sends the first time, but does not update the packet ID when it retries the message.

If the packet succeeds the first time it works, but all retries will fail because MqttOpCompleteCallback() will be unable to match the packet ID.

The best solution is to change publishMqttMessage() to use mqttMsgEntry->msgPacketId and change IoTHubTransportMqtt_DoWork() to increment transportState->packetId when making the assignment to mqttMsgEntry->msgPacketId.  This fixes the packet ID mismatch on retries and provides the ability to detect duplicate messages via the packet ID which is currently not possible since every attempt to send has a different packet ID due to the increment in publishMqttMessage().
 
In publishMqttMessage():
```
change:
    MQTT_MESSAGE_HANDLE mqttMsg = mqttmessage_create(transportState->packetId++, STRING_c_str(msgTopic), DELIVER_AT_LEAST_ONCE, payload, len);
to:
    MQTT_MESSAGE_HANDLE mqttMsg = mqttmessage_create(mqttMsgEntry->msgPacketId, STRING_c_str(msgTopic), DELIVER_AT_LEAST_ONCE, payload, len);
```

In IoTHubTransportMqtt_DoWork():
```
change:
    mqttMsgEntry->msgPacketId = transportState->packetId;
to:
    mqttMsgEntry->msgPacketId = transportState->packetId++;
```

**Comment by tameraw** [comment]
@ebeistle - Thanks for filing this. We're evaluating your proposal and will update you.

**Comment by ebeistle** [comment]
I believe this was corrected in part of an earlier change that moved the assignment of packetId to the get_next_packet_id() function.
