### ISSUE TITLE
[C] Is there a connexion status exposed somewhere ?

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#704]
Hi,

Is there a way to know if the library is actually connected the iothub ?
I'm using iothub_client API, and I can't figure out how we can have a feed back on the connection status, I only see status related to messages sending.

I am missing something or there is no connection status available ?

**Comment by tameraw** [comment]
@lmussier - Yes there is a connection status. If you're simply looking at finding out what the status of a particular device is, you can use DeviceExplorer and look at your device under the management tab.
If you're looking at programatically getting the status, you can use our "Service" clients to do that.

**As example for c#:**
https://msdn.microsoft.com/en-us/library/microsoft.azure.devices.registrymanager.aspx

**If need this in C, check out our registry manager module:**
https://github.com/Azure/azure-iot-sdks/blob/master/c/service/iothub_service_client/src/iothub_registrymanager.c

**Comment by lmussier** [comment]
@tameraw If I understand well, I can't get connection status from the device side (the iothub_client library) I have to use the service SDK to ask, from my device if I'm connected or not, that's it?
There is not simple way to know if the device is connected or not ?

For me IoTHubClient_CreateFromConnectionString does not expose a way to know if the connection is effective or not.

**Comment by tameraw** [comment]
@lmussier - Back to this. We're working on providing a mechanism in the SDKs by which you can find out recoverable/un-recoverable errors with the connection/sending/receiving.

**Comment by tameraw** [comment]
A link to the GitHub project is here:
https://github.com/Azure/azure-iot-sdks/projects/2
