### ISSUE TITLE
[Java SDK] Handling exceptions thrown while receiving messages from IoT hub

### ISSUE THREAD

**Issue by merjadok** [Azure/azure-iot-sdks#705]
Hello everyone,

is there a way to "catch" exception thrown during the receiving of the message from IoT hub (for example, IllegalArgumentException for invalid property values)? By looking at the IotHubReceiveTask ([line 29)](https://github.com/Azure/azure-iot-sdks/blob/master/java/device/iothub-java-client/src/main/java/com/microsoft/azure/iothub/transport/IotHubReceiveTask.java#L29) it looks like exceptions are printed to console and not in any way propagated out of this class.

It is true that we probably couldn't do too much about these exceptions, but it would still be nice to have a handler or something similar for this so that we can log it or handle it in custom way.

Thanks and best regards,
Filip

**Comment by Vingutt** [comment]
@merjadok Thank you for submitting this question. We'll research it and get back to you.

**Comment by Vingutt** [comment]
@merjadok Thank you for submitting this question. We'll research it and get back to you.

**Comment by Rohit-MSFT** [comment]
@merjadok Thankyou for submitting your question. We'll research it and get back to you.

**Comment by Rohit-MSFT** [comment]
@merjadok at this time there does not seem to be a mechanism by which these exceptions can be handled outside the thread. Registering a global exception handler for the thread will catch only the unhandled exceptions. The code you pointed out unfortunately catches all the exception in transport, and we currently do not have a plan to change it.
