### ISSUE TITLE
[C][Yocto Linux][AMQP] transport authentication timed out (Help needed)

### ISSUE THREAD

**Issue by davidv9345** [Azure/azure-iot-sdks#707]
Hi Guys,

I cannot seem to get the AMQP version of the simple sample running on my Intel Edison. At the moment HTTP works, however as mentioned, I am having trouble getting the AMQP to work.

This is my error message 
---------------------------------------------------
Starting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.0.9
IoTHubClient_SetMessageCallback...successful.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Error: Time:Wed Jul 13 21:54:41 2016 File:/home/cpt/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1469 AMQP transport authentication timed out.
-> [CLOSE]* {}
Error: Time:Wed Jul 13 21:55:11 2016 File:/home/cpt/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1469 AMQP transport authentication timed out.
-> [CLOSE]* {}
---------------------------------------------------

Having looked at other posts with the similar issues, I tried passing down the certificates to iot_client_sample_amqp.c but the issue still remains.

Let me know if you have any suggestions!

Much appreciated.

**Comment by markrad** [comment]
Hi @davidv9345,

I'll take a look at this and see if I can help out.

_Mark Radbourne MSFT_

**Comment by davidv9345** [comment]
Thanks markrad!

**Comment by markrad** [comment]
This seems to be an issue on Yocto. Others have reported this. I am researching it.

**Comment by isamllr** [comment]
+1

**Comment by Ivannnm** [comment]
Hello

I have the same problem with Intel Edison an IOTSDK for C (amqp):

~/azure-iot-sdks/c/cmake/iotsdk_linux/serializer/samples/simplesample_amqp# ./simplesample_amqp
Info: IoT Hub SDK for C, version 1.0.11
IoTHubClient accepted the message for delivery
Error: Time:Thu Jul 21 17:35:38 2016 File:/home/root/azure-iot-sdks/c/azure-c-shared-utility/src/consolelogger.c Func:consolelogger_log Line:31 AMQP transport authentication timed out.
-> [CLOSE]* {}
^C

**Comment by davidv9345** [comment]
Having tried ubilinux(Debian) on the board, all of the samples have successfully ran on all protocols. 

From reading previous issues, I saw one person with the same problem, the solution was to pass down the certificates into the program and to update the openssl version from 1.0.1m to a higher version of 1.0.2g.

---> https://github.com/Azure/azure-iot-sdks/issues/507

I believe the problem is the version of openssl > 1.0.1m when running on Yocto Linux. At the minute I am looking into updating this version. 

However the problem is that Yocto repository does not have a newer version of openssl. I will try and manually update the openssl on Yocto and report back with the findings.

If anybody has done the manual update of the openssl before I would appreciate your input!!

Thanks

**Comment by chrit-msft** [comment]
@davidv9345 You mentioned a previous issue, were you talking about #701?  If so have you tried the solution provided?
try using the this call from the simple sample (remove the ifdef)?
```c
#ifdef MBED_BUILD_TIMESTAMP
                // For mbed add the certificate information
                if (IoTHubClient_SetOption(iotHubClientHandle, "TrustedCerts", certificates) != IOTHUB_CLIENT_OK)
                {
                    printf("failure to set option \"TrustedCerts\"\r\n");
                }
#endif // MBED_BUILD_TIMESTAMP
```
the only issue is you need to copy the array of certs from certs.c into your file (code).
Were you able to manually updated openssl?

**Comment by davidv9345** [comment]
Hi chrit-msft,

Yes, this is the issue I was referring to previously. I have tried the solution and the problem still persists on the Yocto.

**Comment by davidv9345** [comment]
I did not manage to update the openssl as the repo for the Yocto does not have an up to date openssl version. I had posted the issue of updating the version on Intel Edison forums, still no solution to updating it https://communities.intel.com/thread/104438

**Comment by Gep-Kistler** [comment]
I had the same problem. But after passing certificates (as described here https://github.com/Azure/azure-iot-sdks/issues/701) the problem has gone.

**Comment by davidv9345** [comment]
I will just double check and try again later on today, maybe I missed something. 

Will update soon.

**Comment by markrad** [comment]
Hi @davidv9345,

Did you ever retry this? I am unable to reproduce your issue once I use the TrustedCerts option.

_Mark Radbourne MSFT_

**Comment by jtanner-msft** [comment]
Hi @davidv9345,  It's been over a month now and we haven't seen any response yet.  If you still see the issue with the latest SDK please feel free to re-open the issue.
