### ISSUE TITLE
[Node] Parsing 409 error when creating a device that already exists

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdks#711]
While using the IoT hub explorer, if one tries to create the same device twice, the error on the console is parsed incorrectly, and looks like (note the truncated text):

> Error onflic

The service returns a status code 409, which is not mapped in [azure-iot-sdks/node/service/lib/registry_http_errors.js](https://github.com/Azure/azure-iot-sdks/blob/master/node/service/lib/registry_http_errors.js) (the code actually expects a 412 for DeviceAlredyExists). I think the generic `Error` class is unable to parse the error message and thus shows the truncated "onflic" word.

For reference, the response from the service looks like:

> `{"Message":"ErrorCode:DeviceAlreadyExists;Conflict","ExceptionMessage":"Tracking ID:e4cb4b6c18f4462fbe2c1a2d02d7dbe4-G:11-TimeStamp:07/16/2016 00:12:41"}`

How to reproduce:

```
* node iothub-explorer.js create foo
* node iothub-explorer.js create foo 
```

**Comment by pierreca** [comment]
Thanks for reporting the issue. it was fixed in https://github.com/Azure/azure-iot-sdks/commit/b1d58c4e0a7684ebcb1f8e4a11f80920dac58267 and updated packages should be released within the next couple of days.
