### ISSUE TITLE
[C][MQTT]Message Tracking broken in simplesample_mqtt.c

### ISSUE THREAD

**Issue by ebeistle** [Azure/azure-iot-sdks#713]
A change was made in the "Fix for Azure IoT SDK broken C samples" that should be reverted.  The original code worked, the new code does not.

The original code uses the callback context pointer to pass an actual value.  Instead of using the pointer to point to an object, it uses a trick of type casting to repurpose it to pass a value directly.  Perhaps it deserved some comments explaining the trick, but it worked.

The new code instead uses the callback context pointer to pass the address of the static variable messageTrackingId which is simply incremented on each send.  There are two problems with this: 1) If a single message is sent and the message is sent with a value of 27 in sendMessage(), the value displayed in sendCallback() will be 28 because the static variable pointed to by the context pointer was incremented after the message was sent; 2) if multiple messages are sent faster than they are completed, each message will display exactly the same messageTrackingId value, which will be one more than the value for the most recently sent message.

To verify, simply add displaying the value of messageTrackingId to the print statements in sendMessage() (it really should be displayed here anyway to demonstrate the message tracking) and compare the value displayed when the message is sent with the value displayed when the message completes.

An alternative would be to malloc() a new value every time a message is sent and free() that value every time the message completes, but this seems like a lot of extra messing around just to have a very simple message tracker.

Change that should be reverted:
```
In sendCallback()
-    int messageTrackingId = (intptr_t)userContextCallback;
+	unsigned int* messageTrackingId = (unsigned int*)userContextCallback;

In sendMessage()
-        if (IoTHubClient_LL_SendEventAsync(iotHubClientHandle, messageHandle, sendCallback, (void*)(uintptr_t)messageTrackingId) != IOTHUB_CLIENT_OK)
+        if (IoTHubClient_LL_SendEventAsync(iotHubClientHandle, messageHandle, sendCallback, (void*)&messageTrackingId) != IOTHUB_CLIENT_OK)
```

**Comment by jebrando** [comment]
This will be fixed in the current release and will hit development on Tuesday.
