### ISSUE TITLE
Node.js IoT SDK Documentation Issues

### ISSUE THREAD

**Issue by Injac** [Azure/azure-iot-sdks#714]
The documentation for node.js , is missing important information's, like the fact, that devices have to be registered first and that the connection string has to be taken from a device to actually make this sample work:

[azure-iot-device](https://github.com/Azure/azure-iot-sdks/blob/master/node/device/core/readme.md)

This leads to misunderstandings and misinterpretations of the current state of the node.js SDK. Also there is no overall coverage of an end to end example for node.js, starting from device registration to sending and receiving messages using the SDK for node.js. 

Apart from that,  great job on the SDK for node :)

**Comment by joshuazsprague** [comment]
+1
Have now invested several days trying to guess and check to get this setup with node/javascript.

**Comment by tameraw** [comment]
@Injac - @joshuazsprague - Thanks for highlighting this. We'll revise our documents.

**Comment by olivierbloch** [comment]
I have addressed this in this [commit](https://github.com/Azure/azure-iot-sdks/commit/10b787ba764571e616519a1948afb58ed4c46c6a)
