### ISSUE TITLE
azure iot hub with arduino 

### ISSUE THREAD

**Issue by codehArt** [Azure/azure-iot-sdks#715]
Hello i am a newbie to azure IoT,
is there any way to integrate azure IoT with Arduino directly???
please help me I couldn't find out sample, document or anything regarding Arduino integration on this repo as well as on azure IoT hub official page.

**Comment by jonbgallant** [comment]
https://azure.microsoft.com/en-us/documentation/samples/iot-hub-c-thingdev-getstartedkit/

https://github.com/arduino-libraries/AzureIoTHub

**Comment by mamokarz** [comment]
Hi codehArt, depend of each Arduino are you talking about. You can find tutorial for Feather M0 and for Adafruit Huzzah on https://azure.microsoft.com/en-us/develop/iot/starter-kits/.

**Comment by codehArt** [comment]
thanks @jonbgallant and @mamokarz  for your guidence.
