### ISSUE TITLE
platform_init() linux implementation always yields the same result

### ISSUE THREAD

**Issue by AlexandreMarechalSE** [Azure/azure-iot-sdks#716]
platform_init() linux implementation always yields the same result:

File: azure-iot-sdks/c/azure-c-shared-utility/adapters/platform_linux.c
Function: platform_init() (line 8)

Implementation suggestion:

int platform_init(void)
{
return error_conversion_function(tlsio_openssl_init());

}

**Comment by Rohit-MSFT** [comment]
@merjadok Thankyou for submitting your question. We'll research the issue and get back to you.

**Comment by Rohit-MSFT** [comment]
@ Just to update you - we have made the necessary changes to platform_init() and under process of checking it in.
