### ISSUE TITLE
[PYTHON] Exceeding IoT Hub Daily Limit Doesn't Throw Exception

### ISSUE THREAD

**Issue by zerox1212** [Azure/azure-iot-sdks#717]
I'm currently using the Free tier of IoT Hub for testing. I turned up the message send frequency of IoT Hub client SDK to consume all the daily messages to see what happens. I am using AMQP.

After the daily limit is exceeded, the client continues to send messages and get's a call back that it succeeded. It seems that IoT Hub responds, but doesn't actually host the message.

The worst part about this is that if you leave the client running, one day later when the message limit resets IoT hub continues to ignore the client. You have to stop the client and start it again.

Is there an exception when daily message limit is exceeded? When the message limit resets, does the client have to reconnect for it to work again?

PS. Seems this same issue also occurs with the Java SDK.

**Comment by chrit-msft** [comment]
@zerox1212 Thank you for opening this issue.  I have been investigating the Java issue already and will add this to my investigation.  As soon as I have more information I will share it with you.

**Comment by tameraw** [comment]
@zerox1212 - We have plans to address this in a future release. No ETA as of yet. If it's a blocking issue on your end, we'd happily accept contributions to our repo.
[https://github.com/Azure/azure-iot-sdks/blob/master/CONTRIBUTING.md](url)

**Comment by zerox1212** [comment]
Thanks for the update. Unfortunately I don't know C so I can' contribute. At this time I just upgraded my IoT hub to avoid running out of messages.

**Comment by tameraw** [comment]
@zerox1212 - We're currently working on enhancing the retry logic and connection error reporting. Once completed, you should be able to get notified via an error indicating when you have reached the maximum quote for sending messages to the IoTHub.
A link to the GitHub project is here:
https://github.com/Azure/azure-iot-sdks/projects/2
