### ISSUE TITLE
[c][x86][AMQP SEC_E_UNTRUSTED_ROOT error

### ISSUE THREAD

**Issue by AcoemDlu** [Azure/azure-iot-sdks#719]
Iothub_client_sample_amqp project compiled with VS2015.
Without Sdk compiled: OK
With Sdk compiled:
**Error:**  SEC_E_WRONG_PRINCIPAL for InitializeSecurityContext()

![image](https://cloud.githubusercontent.com/assets/20553490/16979443/74cfb2bc-4e61-11e6-9b26-fa8c135d4522.png)

Can you help me.
Thanks.

**Comment by anhashia** [comment]
Looking into the issue

**Comment by AcoemDlu** [comment]
It's ok with the last sources
