### ISSUE TITLE
Docs do not mention accepting license agreement

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#72]
As part of this process the user has to agree to add it to their solution, and accept a license agreement:
The NuGet Package Manager will open. Find the package named "Microsoft.Azure.Devices.Client" and click Install: 

Installing Microsoft.Azure.Devices.Client package

The package will be downloaded and added to your project.

Both of those things must happen before it completes the download and adding to the project.

**Comment by dominicbetts** [comment]
@jtanner-msft thanks for pointing this out. I've updated the doc to address this. The new version will be checked in shortly.
