### ISSUE TITLE
[Java SDK] Memory optimization while using org.apache.qpid.proton 

### ISSUE THREAD

**Issue by kevinledinh** [Azure/azure-iot-sdks#720]
Hi Azure team,

I am currently working to integrate the Azure IoT Hub into an Android board (4.4.2). I am having some difficulty with the memory management while using org.apache.qpid.proton .

Generally, after running the app over night, there are a lot of duplicated instances of Strings, byte arrays, etc being retained on the heap. 

A quick summary: after 16 hours of run-time, the heap grew from 10MB to almost 29MB. 

Below is the link of the heap capture in .hprof when the app first started and after 16 hours:
https://drive.google.com/file/d/0Bxtcm6BT3IfpVmZiQVE2SlFhRXM/view?usp=sharing 

https://drive.google.com/file/d/0Bxtcm6BT3IfpWWEydFdsMDljeFk/view?usp=sharing

Is there a way to better manage the memory or has this been any update on this?

Any help appreciated.

**Comment by kevinledinh** [comment]
Some additional info, AMQP is currently used to push data from the Android app to an IoT Hub.

Some updates, following an advice on this post ​http://stackoverflow.com/questions/38119446/why-would-i-want-to-find-duplicate-strings-with-hprof-viewer-and-analyzer, I've used a StringBuilder in org/apache/qpid/proton/amqp/transport/ErrorCondition.java for _description. It improves the memory usage a lot. 

Also, there is a lot of "sendto broken PIPE" exception not being caught. A quick search came up with something related to the java sdk package libcore.io.ErronoException. Would it be related to this problem somehow?

However, after running the Android app for 21.5 hours, the Heap grows from ~3MB to ~8MB and the kernel CPU usage from ~3% to ~35% (in addition to 40% User CPU usage). The heap seems to contain a lot of byte[] coming from the AMQP transport layer (please correct me if I'm wrong). We would like to run the app for months if not years, so this problem needs to be fixed.

Please find attached the new hprof after running the app for 21.5 hours, it can be viewed using Android studio - https://drive.google.com/file/d/0Bxtcm6BT3IfpMjVxcnNtYXYwNEk/view?usp=sharing

Any help appreciated.

**Comment by kevinledinh** [comment]
Additional info, the package used in conjunction with the IoT Hub is proton-j-azure-iot-0.12.2

**Comment by markrad** [comment]
Hi @kevinledinh,

I'm having difficulty opening your .hprof files. I'm using jhat version 2.0 (java version 1.8.0_91) and receiving error _Version string not recognized at byte 17_. Do you know what version your .hprof files are at?

_Mark Radbourne MSFT_

**Comment by kevinledinh** [comment]
Hi @markrad,

Please find the converted hrof file here: https://drive.google.com/file/d/0Bxtcm6BT3IfpM05QTkRGSUZkVTQ/view?usp=sharing

I check that it can viewed in Memory Analyzer Tool.  The leak report says that there are many Thread being retained. This problem has been persisting and I'm not sure how to get around it.

Any suggestion is very welcomed.

Best wishes,

**Comment by kevinledinh** [comment]
Hi @markrad ,

So today i've found out where the memory leak problem is. I'm using IoT Hub v1.0.11.

In IotHubReactor.java, just checking whether the current Thread is interrupted is not sufficient because most of the time, the thread does not detect this interrupt signal. 

In addition, although the reactorFuture is cancelled, the current Thread has to also manually checked for .isCancelled signal. 

All of this is done on Android so I'm not sure how different the Thread framework is on a PC. So this is my two cents for the memory leak problem. I'm glad to solve it after two months of reading Heap dumps.

I'm interested if this is going to be in the next release. Please let me know so I can test it on my set up.

Thanks for assisting. Best wishes.

**Comment by markrad** [comment]
Hi @kevinledinh,

Thank you for the update. I'll inform the product group of your findings and let them take it from there.

_Mark Radbourne MSFT_

**Comment by kevinledinh** [comment]
Hi @markrad ,

A pull request has been successfully done, see #790.

Best wishes,
