### ISSUE TITLE
Windowc c sample exception

### ISSUE THREAD

**Issue by basimolimajeed** [Azure/azure-iot-sdks#723]
When I am running the iothub_client_sample_amqp sample, I get the following error. Any ideas?
Thanks

Unhandled exception thrown: read access violation.

handleData was 0xFFFFFFFFFFFFFFEF.

**Comment by anhashia** [comment]
Looking into the issue

**Comment by basimolimajeed** [comment]
This is what I get on debug


![x509](https://cloud.githubusercontent.com/assets/16608331/17055093/97b74194-5002-11e6-9f5f-9b0902359fa8.png)

**Comment by anhashia** [comment]
Hi @basimolimajeed 
I wasn't able to reproduce the issue using existing iothub_client_sample_amqp sample where I used SharedAccessKey in connection string.
Exception that you are hitting is related to using **X.509 certificate** option covered under https://azure.microsoft.com/en-us/documentation/articles/iot-hub-sas-tokens/  Are you using X.509 certificate to authenticate a device with IoT Hub ?

**Comment by basimolimajeed** [comment]
I did not change anything apart from the connection string. However I was running on a Surface device when I was getting the error. I moved to my development PC and it seems to work fine. Not sure why though

**Comment by basimolimajeed** [comment]
It seems that the latest master branch resolved the problem.
