### ISSUE TITLE
[C][Linux] CMAKE_BUILD_TYPE seems to be not used

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#725]
Hi,

Using cmake one should be able to set CMAKE_BUILD_TYPE to different values to build in, at least debug and release mode. I don't see any difference in the compile options when the SDk is build with CMAKE_BUILD_TYPE=Debug Vs. CMAKE_BUILD_TYPE=Release

I think (and don't try) if I use compileOption_C I might be able to pass flags like -Os -s to the compilation but I don't think this is the intent.

**Comment by anhashia** [comment]
Hi @lmussier 
Different configuration types are supported as shown below
Let us take example of W32 samples for Windows 10
azure-iot-sdks\c\cmake\iotsdk_win32\CMakeCache.txt has
`CMAKE_CONFIGURATION_TYPES:STRING=Debug;Release;MinSizeRel;RelWithDebInfo`
Now open 
azure-iot-sdks\c\cmake\iotsdk_win32\azure-c-shared-utility\ aziotsharedutil.vcxproj in VS 2015
You will see all **4 options** to build in the configuration section. 
By default there is Debug. You can also choose Release.

Using command  you can run azure-iot-sdks\c\build_all\windows\build.cmd
`build --config Release `for Release configuration

**Comment by lmussier** [comment]
@anhashia I can't find azure-iot-sdks\c\cmake\ folder (searched here https://github.com/Azure/azure-iot-sdks/tree/develop/c)

I'll rename the issue since I search this for linux build. It may be clearer.

**Comment by anhashia** [comment]
Hi @lmussier 
Following cmake sub-directories will be created after your run corresponding build scripts
azure-iot-sdks\c\cmake\iotsdk_win32 (for Windows)
azure-iot-sdks/c/cmake/iotsdk_linux (for Linux)

For Linux, go to open **CMakeCache.txt** located at
azure-iot-sdks/c/cmake/iotsdk_linux/
This file is generated by **CMake** tool

Edit it to build type you want
`CMAKE_BUILD_TYPE:STRING=Debug `(example for debug)
Now run **make** tool on the makefile from the location you want debug build. For example for creating **debug** version of libaziotsharedutil.a you would run make tool from /azure-iot-sdks/c/cmake/iotsdk_linux/azure-c-shared-utility

**Comment by lmussier** [comment]
@anhashia Could you provide me the settings for debug and release build ?
The problem is not that we can't set release types, it is more I can't find the flags used in release and debug (and I think there is no difference between build types).

For instance, debug build should set cflags=-g -O0 and min size release to -Os, and I can't find a place where CMAKE_CXX_FLAGS_DEBUG and friends are set.

**Comment by anhashia** [comment]
Hi @lmussier 
I wasn't able to find the settings in \build_all\linux\build.sh script that you can use directly to set debug or release build (if that is what you are exactly looking for). To workaround this you can edit CMakeCache.txt **after** you run cmake which gets invoked when you run build.sh.

For Linux, go to open **CMakeCache.txt** located at
 azure-iot-sdks/c/cmake/iotsdk_linux/
 This file is generated by CMake tool

Edit below string it to build type you want. Below is example for setting debug build
` CMAKE_BUILD_TYPE:STRING=Debug`
 Now run **make** tool directly on the makefile from the location you want debug build

**Comment by lmussier** [comment]
@anhashia The need is to have different compiler settings for Debug and Release mode, not to trigger CMake with one or the other build type.

**Comment by anhashia** [comment]
Hi @lmussier 
Try azure-iot-sdks/c/build_all/linux$ ./**build.sh -cl -g** option. This should produce debug build with debugging information

**Comment by anhashia** [comment]
Closing. Please re-activate if you still are having issues. Thanks !
