### ISSUE TITLE
Websocket IO interface description not initalized correctly at declaraton

### ISSUE THREAD

**Issue by AlexandreMarechalSE** [Azure/azure-iot-sdks#731]
commit 1ffa71c59c3b05a8e3a0e7b91bd0e90214878727

In file wsio.c, declaration and initialization of ws_io_interface_description:

```
static_ const IO_INTERFACE_DESCRIPTION ws_io_interface_description =
{
	wsio_create,
	wsio_destroy,
	wsio_open,
	wsio_close,
	wsio_send,
	wsio_dowork,
    wsio_setoption
};
```

but structure IO_INTERFACE_DESCRIPTION is defined in xio.h as below:

```
typedef struct IO_INTERFACE_DESCRIPTION_TAG
{
    IO_RETRIEVEOPTIONS concrete_io_retrieveoptions;
    IO_CREATE concrete_io_create;
    IO_DESTROY concrete_io_destroy;
    IO_OPEN concrete_io_open;
    IO_CLOSE concrete_io_close;
    IO_SEND concrete_io_send;
    IO_DOWORK concrete_io_dowork;
    IO_SETOPTION concrete_io_setoption;
} IO_INTERFACE_DESCRIPTION;
```

As a consequence, all the structure is shifted and concrete_io_setoption field is set to NULL.

This lead to xio_create() function to fail.

**Comment by AlexandreMarechalSE** [comment]
wsio_retrieveoptions function is missing (and does not exist)

**Comment by anporumb** [comment]
Working on it...

**Comment by anporumb** [comment]
There's code checked in branch develop that fixes the reported issue. Let me know how it works for you.

Best Regards,
Andrei Porumb

**Comment by AlexandreMarechalSE** [comment]
Hi, thanks for the modification. but build is currenlty unstable #737
Alexandre

**Comment by AlexandreMarechalSE** [comment]
It works for me anporumb. Thanks
