### ISSUE TITLE
Where is the Device API for NODE documentation

### ISSUE THREAD

**Issue by Agilart** [Azure/azure-iot-sdks#733]
Hi,
the link in the readme file does not work - returns 404: http://azure.github.io/azure-iot-sdks/node/api_reference/azure-iot-device/1.0.9/index.html

Where I can find the latest documentation?

Thanks in advance,
Ivan Dragoev

**Comment by pierreca** [comment]
Hi @Agilart, sorry for the inconvenience. It looks like there was an error pushing the node documentation for the last release. we will look into it and try to publish it asap. 

In the meantime you can find the content of the documentation directly in the code and if you clone the repository you should be able to generate the pages and use them locally by running the `gen_jsdocs` script in the `build/docs` folder. I'll update the issue with a new link when the docs are published, and figure out why it didn't work during the release process.

**Comment by pierreca** [comment]
The new docs have been published:

Device SDK: http://azure.github.io/azure-iot-sdks/node/api_reference/azure-iot-device/1.0.10/index.html
Service SDK: http://azure.github.io/azure-iot-sdks/node/api_reference/azure-iothub/1.0.12/index.html
