### ISSUE TITLE
[C][MQTT] Unittest - iothubtransportmqtt_unittests - failed at test "IoTHubTransportMqtt_MqttOpCompleteCallback_PUBLISH_ACK_succeed"

### ISSUE THREAD

**Issue by yphuangms** [Azure/azure-iot-sdks#736]
The latest sdk mqtt C code (iothubtransportmqtt.c) has modify to get next available packet Id for a new message for publishing. This makes the newly assigned packetId to be "2" instead of "1". 

static int publishMqttMessage(...)
{   ...
    mqttMsgEntry->msgPacketId = get_next_packet_id(transportState);
    ...
}

In "get_next_packet_id()", it return "1" if the number reached the maximum count, but if the transport data handle is newly created, it will return "2", for the initial packet id value is "1". This might not be a big issue, but it makes the packet id number ranging from 1 to max or 2 to max, not consistent, and might cause potential issue in the future.

In unit-test case, the expected packet id for the very first published message is still set to "1", this will cause the test case failure.
The following is the code snippet from unit-test code to highlight the root cause:  
In "iothubtransportmqtt_unittests.cpp"
TEST_FUNCTION(IoTHubTransportMqtt_MqttOpCompleteCallback_PUBLISH_ACK_succeed)
{
   ...
  puback.packetId = 1; .// this should be set to '2' to be compatible with latest mqtt code changes.
  ...
}

**Comment by jtanner-msft** [comment]
Thank you for reporting this.  I'll look into updating the test code.

**Comment by jtanner-msft** [comment]
I've just tested with the latest master branch and all of the tests (including IoTHubTransportMqtt_MqttOpCompleteCallback_PUBLISH_ACK_succeed) appear to pass.
Also the value you indicated has been changed from 1 to 2.
Closing this incident.  Thanks again for your suggestion.  If you do see any other problems in the future please mention them.
