### ISSUE TITLE
Deployment suggestions for IoT Core

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#74]
You might want to mention that you can instead use an IP address instead of the hostname, but to make sure authentication is set to None.
Using that method you can avoid going to the project properties entirely if desired.

Or you might review / contrast the 'Hello World' docs to see how they've described it:

http://ms-iot.github.io/content/en-US/win10/samples/HelloWorld.htm
This is in reference to the following section on getting CSharp up on an Windows IoT Core device such as Rpi2:

If you're using a Raspberry Pi device, select ARM. For other supported devices, consult windowsondevices.com.

You will need to deploy your app to an IoT device so that you can run and debug it remotely. Right-click on the solution in the Solution Explorer, select Properties and navigate to the Debug tab:

Type in the name of your device. Make sure the "Use authentication" box is unchecked.

Now, you're ready to build and deploy the app. Choose "Build" and then "Deploy" from the top menu.

**Comment by dominicbetts** [comment]
@jtanner-msft thanks for the pointer. I've made some changes to the doc so that it references these resources. Changes will be checked in shortly.
