### ISSUE TITLE
[C][DM] Will you instantiate all LWM2M objects ?

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#741]
Hi,

Currently on [DM branch](https://github.com/Azure/azure-iot-sdks/tree/dmpreview/c/iotdm_client/lwm2m_objects) branch I can see device, firmwareupdate, config  and server objects.

Do you plan to support all of 7 LWM2M objetcs (or provide a mean to do so if necessary) ?
My current concern is to provide /4/0/0, the network bearer of my device.

**Comment by damonbarry** [comment]
@lmussier, you’re right we don’t currently support the connectivity monitoring object (object ID #4). It’s difficult to say at this point how things will look in the future. We’re currently incorporating feedback from our DM public preview to decide how best to expose the device management features and patterns people expect. Stay tuned…

**Comment by lmussier** [comment]
Hi there, I just wonder if you have a date to communicate for "official" DM availability.
We've made a work around to support missing objects, and we look forward to integrate the DM support from the SDK.

**Comment by damonbarry** [comment]
@lmussier Not yet, but stay tuned. We'll have more information in the coming weeks

**Comment by mgiuncato** [comment]
Hi Damon,

we are working hard to go in production with our products based on Azure IOTHUB.
but  in the last days, we start having problem with DM both with client and ( https://github.com/Azure/azure-iot-sdks/issues/854 ) your words sounds like a charm :-D 
could you supply us some "rumors" ;-)  about DM official release date ?
or "spoiling" some other new... 
appreciate this so much !!!
Marco
('cause we are stuck now)

**Comment by tameraw** [comment]
@lmussier - As we released a new public preview for Azure IoT Hub Device Management, we moved the related code and samples that were in this branch to a different repository. You can now find all Device Twins, Device Methods, and Device Management related code in this new repository: https://github.com/azure/azure-iot-sdks-preview. The current dmpreview branch should be considered  obsolete.
Closing this, and please feel free to let us know of any issues related to DM in that new repo. Thanks.
