### ISSUE TITLE
azure-iot-device, iothub-explorer, et al npm packages are vulnerable to https://nodesecurity.io/advisories/130

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-iot-sdks#742]
Several of the Node SDK packages depend on an older version of request, which uses a vulnerable version of tough-cookie described here: https://nodesecurity.io/advisories/130.  As such, you'll see security warnings when installing the iothub-explorer and device SDK.

Updating the SDKs to use the latest version of requestjs should fix the issue, as it depends on tough-cookie 2.3 which fixes the vulnerability.

**Comment by pierreca** [comment]
Thanks for opening this issue. Looks like the package we depend on that brings this dependency is the azure-storage package. I'll work with the maintainers to get it updated ASAP and provide tracking updates here.

**Comment by pierreca** [comment]
Just pushed a fix to our `develop` branch, will be published during our next release cycle.
