### ISSUE TITLE
IotHub setDisconnectHandler

### ISSUE THREAD

**Issue by kasparsklavins** [Azure/azure-iot-sdks#746]
How does one access the `setDisconnectHandler` method from `azure-iot-amqp-base.Amqp`, if I have connected connected from `azure-iothub.Client`?

> iotHub = require('azure-iothub').Client.fromSharedAccessSignature(sas);
> iotHub._transport._amqp.setDisconnectHandler(error => console.log(error));

This does not get triggered upon disconnect.
It sends messages just fine, so it was connected at some point.

**Comment by pierreca** [comment]
If the `disconnect` event is not fired at the client level, then it's a bug. Can you share how you ran into this issue? version of the SDK, command line dump, maybe the code that reproes the problem and how often it does?

As a general principle, I would advise against trying to access anything in the amqp-base package, although we follow semantic versioning those are really internal APIs more than anything (as described in the readme). The base package is just a way for us to share code between the Service and Device SDKs and those are the public APIs.

Thanks!

**Comment by kasparsklavins** [comment]
I understand that it is not recommended to use private api's, but it is not exactly documented how I can access the disconnect handler or event listener without it.

**Comment by pierreca** [comment]
The `disconnect` event should be fired by the `Client` object. 

```js
var Client = require('azure-iot-device').Client;
var Amqp = require('azure-iot-device-amqp').Amqp;

var client = Client.fromConnectionString("<CONNECTION_STRING>", Amqp);
client.on('disconnect', function() {
  // code to execute when the connection is disconnected
});
```

If that is not firing, then it's definitely a bug. What protocol are you using to communicate with IoT Hub?

**Comment by kasparsklavins** [comment]
I'm using **azure-iothub** and not **azure-iot-device** for service-to-device messages with amqp protocol. 
Can't confirm it at the moment, but I think there was no `on()` methos for iothub service client.

**Comment by pierreca** [comment]
ha got it. I assumed you were working on the device SDK. The Service SDK is incomplete in that regard, we haven't gotten to implementing this yet. Let me see if I can squeeze this in the next release. we do accept pull requests if you want to take a stab at it.

**Comment by kasparsklavins** [comment]
Any timeline of when the next release might happen?

**Comment by pierreca** [comment]
We release every other week, so that'd be end of next week. still working on squeezing this within this sprint.

**Comment by pierreca** [comment]
The feature was finally implemented here: https://github.com/Azure/azure-iot-sdks/commit/7861a0cc243bfc95b634668093078b0e450a88e6

Will be released with the next release cycle, one week from now.

**Comment by kasparsklavins** [comment]
@pierreca 
In what scenarios the disconnect event is emitted?

At the moment the event is not emitted if internet connectivity disappears.

**Comment by pierreca** [comment]
@kasparsklavins it gets called when the socket gets disconnected, so we depend on the OS TCP/IP stack. What OS and SDK version are you running?

**Comment by kasparsklavins** [comment]
I'm on `1.0.14`
I'm on Ubuntu 14.04 virtual machine, through windows 10 host machine.

Although, it did get called when the machine went in sleep mode. Not the best way to test it.
