### ISSUE TITLE
AddDeviceAsync fails on UWP project but works on Console

### ISSUE THREAD

**Issue by Jiihaa** [Azure/azure-iot-sdks#749]
When you try to run the code from https://azure.microsoft.com/en-us/documentation/articles/iot-hub-csharp-csharp-getstarted/ to create Device Identity, it works perfectly on console app, but when run on UWP app, it fails on device = await registryManager.AddDeviceAsync(new Device(deviceId));
with the FileNotFoundException, message is: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

It seems that the Nuget package doesn't add the correct references on UWP (it adds 6.0.4) and on console project it does with Visual Studio 2015 Update 3 installed.

**Comment by arturl** [comment]
thanks @Jiihaa, I'm looking into it now. The problem should go away if you explicitly add 'Newtonsoft.Json, Version=8.0.0.0 to your project -- use that as a work-around for now.

**Comment by arturl** [comment]
Should be fixed in the latest release.
