### ISSUE TITLE
AMQP C samples on RaspberryPI not working

### ISSUE THREAD

**Issue by xtrsys** [Azure/azure-iot-sdks#75]
I've followed https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_sample_on_raspberrypi2_raspbian.md and added correct connectionString from DeviceExplorer. 

**iothub_client_sample_amqp** 
```
pi@myraspb ~ $ ./azure-iot-sdks/c/iothub_client/samples/iothub_client_sample_amqp/linux/iothub_client_sample_amqp
Starting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.0.0-preview.3
IoTHubClient_SetMessageCallback...successful.
Error: Time:Wed Oct 14 11:44:00 2015 File:../../src/iothubtransportamqp.c Func:protonMessengerInit Line:762 unable to create a subscription to the cbs address
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Press any key to exit the application.
Error: Time:Wed Oct 14 11:44:00 2015 File:../../src/iothubtransportamqp.c Func:protonMessengerInit Line:762 unable to create a subscription to the cbs address
Error: Time:Wed Oct 14 11:44:00 2015 File:../../src/iothubtransportamqp.c Func:protonMessengerInit Line:762 unable to create a subscription to the cbs address
```

**simplesample_amqp**
```
pi@myraspb ~ $ ./azure-iot-sdks/c/serializer/samples/simplesample_amqp/linux/simplesample_amqp
Info: IoT Hub SDK for C, version 1.0.0-preview.3
Error: Time:Wed Oct 14 16:17:38 2015 File:../../src/iothubtransportamqp.c Func:protonMessengerInit Line:762 unable to create a subscription to the cbs address
IoTHubClient accepted the message for delivery
Error: Time:Wed Oct 14 16:17:38 2015 File:../../src/iothubtransportamqp.c Func:protonMessengerInit Line:762 unable to create a subscription to the cbs address
```

**remote_monitoring**
```
pi@myraspb ~ $ ./azure-iot-sdks/c/serializer/samples/remote_monitoring/linux/remote_monitoring
Error: Time:Wed Oct 14 16:19:43 2015 File:../../src/iothubtransportamqp.c Func:protonMessengerInit Line:762 unable to create a subscription to the cbs address
IoTHubClient accepted the message for delivery
Sending sensor value Temperature = 50.000000, Humidity = 50.000000
IoTHubClient accepted the message for delivery
Error: Time:Wed Oct 14 16:19:43 2015 File:../../src/iothubtransportamqp.c Func:protonMessengerInit Line:762 unable to create a subscription to the cbs address
Error: Time:Wed Oct 14 16:19:43 2015 File:../../src/iothubtransportamqp.c Func:protonMessengerInit Line:762 unable to create a subscription to the cbs address
```
On the other hand the one with HTTP can send messages successfully to IoTHub.

Might this be related to ssl issue I'm having also? https://github.com/Azure/azure-iot-sdks/issues/56

**Comment by CarlosAlayo** [comment]
Check with your network administrator that outbound port # 5671 is enabled. Devices with the AMQP protocol use that outbound port to communicate with IoT Hub. There is more information here: 
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-itpro-info/

**Comment by DayronIG** [comment]
I have the same error does not want me working

**Comment by anporumb** [comment]
Instructions for RP2 have been updated.

**Comment by Ivannnm** [comment]
Hello, I have the same problem running "simplesample_amqp" on Debian.

Info: IoT Hub SDK for C, version 1.0.0-preview.8
Error: Time:Thu Jan  7 17:29:29 2016 File:/root/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:protonMessengerInit Line:879 unable to create a subscription to the cbs address
IoTHubClient accepted the message for delivery
Error: Time:Thu Jan  7 17:29:29 2016 File:/root/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:protonMessengerInit Line:879 unable to create a subscription to the cbs address

......


......

Error: Time:Thu Jan  7 17:29:35 2016 File:/root/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:protonMessengerInit Line:879 unable to create a subscription to the cbs address
Message Id: 0 Received.
Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY

....................................

nmap -p 5671 RastreoZendos.azure-devices.net

Starting Nmap 6.47 ( http://nmap.org ) at 2016-01-07 16:50 CET
Nmap scan report for RastreoZendos.azure-devices.net (40.127.132.17)
Host is up (0.053s latency).
PORT     STATE SERVICE
5671/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 2.00 seconds

Help,please..
