### ISSUE TITLE
[C] Add CMake install commands

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#752]
Would it be amenable to add CMake [install](https://cmake.org/cmake/help/v3.0/command/install.html) commands to the c iothub_client and related libraries?

e.g. in azure-iot-sdks/c/iothub_client/CMakeLists.txt
```cmake
install(TARGETS iothub_client DESTINATION bin)
install(FILES ${iothub_client_h_files} DESTINATION include)
```
Thus the target could be built and installed into common global locations and then linked against. This may then also have to be added to other dependent libraries such as amqp etc.

I'd be happy to have a go at adding the required functionality if happy?

**Comment by markrad** [comment]
Hi @damienpontifex,

Can you be more specific please? The .a files are already installed into lib and the headers are installed into include/azureiot. Are them some additional files you want installed?

_Mark Radbourne MSFT_

**Comment by Jokymon** [comment]
@markrad it looks as if on Windows this is not the case.

from azure-iot-sdks/c/iothub_client/CMakeLists.txt at the bottom
```cmake
if(WIN32)
else()
    install (TARGETS 
		${iothub_client_libs} 
		DESTINATION lib)
    install (FILES 
		${iothub_client_h_install_files} 
		DESTINATION include/azureiot)
endif (WIN32)
```
Are these libraries and headers not needed for Windows?

**Comment by markrad** [comment]
Hi @damienpontifex, @Jokymon,

Indeed you are correct, there is no install step for Windows. If you prepare a pull request to address this I will be happy to review it.

_Mark Radbourne MSFT_

**Comment by damienpontifex** [comment]
Sorry @markrad if I am mistaken. I was looking through the CMake files to analyse how I might use this library and didn't come across those install steps.

Happy to close unless you want to track the windows install step here also.

**Comment by Jokymon** [comment]
@markrad I can do that. However it looks like this will need several PRs because it also affects the submodules azure-uamqp-c, azure-umqtt-c, azure-c-shared-utility and libwebsockets. Do you want the PRs with updated submodule references or do you want to update them yourself?

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Looking into the issue.

**Comment by markrad** [comment]
Hi @Jokymon,

The task to make the SDK properly installable on all platforms is currently being implemented by the product group. It's quite a large work item so it will be a while before it is ready. However, since it is being addressed I am closing this issue.

Thank you.

_Mark Radbourne MSFT_
