### ISSUE TITLE
Issue with asp.net 5

### ISSUE THREAD

**Issue by mburumaxwell** [Azure/azure-iot-sdks#76]
First am not sure if I am posting this in the right repository but I could not find one that is closest to being right other than this one. Please redirect the issue to the right repository if I made a mistake.

I added the nuget package ``` Microsoft.Azure.Devices ``` version ```1.0.0-preview-004``` to an Asp.Net 5 project but I got an error about the framework assembly ```System.Net.Http.Formatting``` not being found. I did some research and realized that it should be added by the package ```Microsoft.AspNet.WebApi.Client``` version ```5.2.3``` which is added to the nuget spec as a dependency. I presume that due to the way Asp.Net 5 works, ```System.Net.Http.Formatting``` cannot be added as framework assembly..
I edited the ```.nuspec``` file in the package cache to remove this line below.
```xml
<frameworkAssembly assemblyName="System.Net.Http.Formatting" targetFramework=".NETFramework4.5.1" />
```
The error then disappeared. and the project runs very well.

I went on a created another package with ```Microsoft.Azure.Amqp``` version ```1.0.0-preview-003``` as the only dependency and omitting the said framework assembly. After listing it on nuget temporarily, and installing it in the project, everything went fine.

I think dependency on ```Microsoft.AspNet.WebApi.Client``` and ```Microsoft.AspNet.WebApi.Core``` is should not be necessary.

I am not also sure if using the ```Microsoft.AspNet.Mvc``` package in the project resolved the said frameworkAssembly

**Comment by CarlosAlayo** [comment]
Thank you for reporting this issue. We are investigating the problem.

**Comment by rajeevmv** [comment]
Thanks for identifying this issue. We will incorporate these dependency changes in the next version of the  Microsoft.Azure.Devices  SDK.

**Comment by mburumaxwell** [comment]
Any updates on this?
