### ISSUE TITLE
[C][Edison] - Unit test `crt_abstractions_unittests` fails on Intel Edison

### ISSUE THREAD

**Issue by avranju** [Azure/azure-iot-sdks#760]
The unit tests  in the suite **crt_abstractions_unittests** fails on the Intel Edison. Here're the failing test cases:

```
Executing test strtold_s_min_negative_value_success ...
  Assert failed: Expression should be true: expectedResult == result. 
!!! FAILED !!!
Executing test strtold_s_max_positive_exponential_number_success ...
Suceeded.
Executing test strtold_s_min_positive_value_success ...
  Assert failed: Expression should be true: expectedResult == result. 
!!! FAILED !!!
```

**Comment by jtanner-msft** [comment]
I've repro'd the failure on my Edison and have been trying to determine why those long values appear to get treated differently.  Once I have more of an update I will let you know.

**Comment by jtanner-msft** [comment]
We have developed an update that resolves this which is being checked in.  It should be in develop branch later today or tomorrow.  Closing issue.
