### ISSUE TITLE
Can't recieve message in UWP from Iot hub

### ISSUE THREAD

**Issue by programmersommer** [Azure/azure-iot-sdks#762]
I am trying create application like it's written in article [Connect your Windows app to Azure IoT Hub with Visual Studio](https://blogs.windows.com/buildingapps/2016/03/03/connect-your-windows-app-to-azure-iot-hub-with-visual-studio/) but can't read message from hub. I have tried different transport types without any result. receivedMessage inside ReceiveCloudToDeviceMessageAsync() is always null. I has event post topic on forum [Azure IoT hub reading messages issue](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/1cac75c6-bea4-468f-8961-b87001ce5350/azure-iot-hub-reading-messages-issue?forum=azureiothub)
[Here you can find UWP application](https://github.com/programmersommer/UWPAzureIotHub) that can send message but can't read
And here you can download [2 console applications](https://1drv.ms/u/s!AjtugYahwCUTqGbVVdVJeIaRmb9N) One could simulate device and another could read messages from iot hub

**Comment by arturl** [comment]
Hi @programmersommer,

Sorry it took me a while to get back to you.

I've looked at your UWPAzureIotHub project. When used with 1.0.11 Azure.Devices.Client library, `ReceiveAsync` can return null with AMQP protocol, so you need a while loop to handle that. When using a more recent version of the the library (1.0.19), null message is fixed, so the while loop is no longer necessary. 

In either case, the app receives the messages correctly. 

I did change your app to work with my IoT Hub, but that was the only change (BTW, it's best not to leave the credentials in the code).

I'll close this issue now, but feel free to reopen or ping me directly (which can be faster)
