### ISSUE TITLE
Python API Documentation

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [Azure/azure-iot-sdks#763]
I didn't find complete documentation of the python API's, can you please provide me the same?

**Comment by sanket-kulkarni-vmware** [comment]
Hello I got stuck because of incomplete documentation, Can please provide link for the same.

Thanks

**Comment by tameraw** [comment]
@sanket-kulkarni-vmware - Currently we provide a document on how to start running the sample in Python. [https://github.com/Azure/azure-iot-sdks/blob/master/python/device/readme.md](url)
We'll work on generating API docs for the Python libraries.

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-python#8
