### ISSUE TITLE
[Java]Java device client can't connect to IOT hub in Azure China with MQTT protocol 

### ISSUE THREAD

**Issue by kingliantop** [Azure/azure-iot-sdks#766]
Hi guys,
Using the latest SDK and Java sample code from below, I can use https or AMQPS to communicate with Azure China IOT hub successfully, but failed for the mqtt protocol.

The sample code URL as below:
https://github.com/Azure/azure-iot-sdks/tree/master/java/device/samples/send-receive-sample

The detailed error information:

Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol MQTT.
Successfully created an IoT Hub client.
Successfully set message callback.
Exception in thread "main" java.io.IOException: Error initializing MQTT connection:MqttException
	at com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:139)
	at com.microsoft.azure.iothub.transport.mqtt.MqttTransport.open(MqttTransport.java:83)
	at com.microsoft.azure.iothub.DeviceClient.open(DeviceClient.java:168)

Any clues or suggestions for the issues? I use the latest SDK. thanks!

**Comment by prmathur-microsoft** [comment]
Hi, I have ran MQTT send-receive sample on my end and could not see this issue. Could you please sync to latest and see if the issue is still reproducible ? If so can you provide more details about how you are running this scenario ?

**Comment by kingliantop** [comment]
Finally found it is the SSL certificate issue. Resolved, thanks!
