### ISSUE TITLE
MQTT QoS 0 Message (Azure IoT SDK Python)

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [Azure/azure-iot-sdks#770]
I am facing a problem of sending QoS 0 message in **python azure client**. Can you tell me which method should I use to set QoS level of the MQTT message?

**Comment by tameraw** [comment]
The SDK does not currently provide an option to modify the QoS. Currently in the backlog.

**Comment by tameraw** [comment]
Unfortunately, this is currently not a priority in our backlog. 
But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade).
