### ISSUE TITLE
Multiple models in serialization namespace can't have same properties names

### ISSUE THREAD

**Issue by ritave** [Azure/azure-iot-sdks#773]
On develop branch @ commit 8f2d430, using C sdk.

After declaring the model:
```c
BEGIN_NAMESPACE(HealthPortalEvents);

DECLARE_MODEL(GatewayCreated,
	WITH_DATA(ascii_char_ptr, DeviceId),
	WITH_DATA(ascii_char_ptr, What)
);

DECLARE_MODEL(ModuleListChanged,
	WITH_DATA(ascii_char_ptr, DeviceId),
	WITH_DATA(ascii_char_ptr, ActiveModuleNames)
);

END_NAMESPACE(HealthPortalEvents);
```

the code fails to compile because:

```
error C2084: function 'int Create_AGENT_DATA_TYPE_From_Ptr_DeviceId(void *,AGENT_DATA_TYPE *)' already has a body
```

**Comment by ritave** [comment]
I serialized my data manually with Parson library and it worked better. Maybe it's better to deprecate serializer module and direct people to Parson?

**Comment by tameraw** [comment]
"I serialized my data manually with Parson library and it worked better. Maybe it's better to deprecate serializer module and direct people to Parson?"

@ritave - Thanks for your feedback. We'll look into this in the future. Meanwhile, please let us know if you're blocked.

**Comment by ritave** [comment]
Nope

**Comment by tameraw** [comment]
This is currently not a priority in our backlog. 
But if it becomes a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade).
Thanks.
