### ISSUE TITLE
Link to Pine64 Win10 IoT FFU is broken...

### ISSUE THREAD

**Issue by crpietschmann** [Azure/azure-iot-sdks#774]
The "azure-iot-sdks/doc/get_started/windows10-iot-core-pine64-csharp.md" article shows that you can install Windows 10 IoT Core on a Pine64 board. However, the link to download the FFU to flash on the SD Card for the Pine64 board is a broken link.

Is the Pine64 officially supported by Windows 10 IoT Core? It's not listed on Microsoft's Windows IoT Core site...

**Comment by ashokkhurana** [comment]
The document was provided by our partner who recently certified their device with us. I have sent an email to them for sending us the updated link. I will update the document as soon as I hear back from them. The board is listed as a certified Azure IoT device here https://azure.microsoft.com/en-us/documentation/articles/iot-hub-tested-configurations/

**Comment by crpietschmann** [comment]
Cool, thanks!

**Comment by ashokkhurana** [comment]
I got the updated link from partner as http://files.pine64.org/os/win10-iot/Pine64_Win10IoTCore10586_beta0.1.ffu

Thanks,
Ashok
