### ISSUE TITLE
I need build for architecture x86_64 or arm64, What should I do?

### ISSUE THREAD

**Issue by jiangzhibin** [Azure/azure-iot-sdks#775]
I need build a static library for architecture x86_64 or arm64,so that can runs on iPhone  or mac os x. I built master branch on Linux,it succeeded but not for architecture x86_64, What should I do,add some parameters in cmake file?
It's appreciative for your reply.

**Comment by anhashia** [comment]
Investigating.

**Comment by anhashia** [comment]
Hi @jiangzhibin 
Thanks for patience ! I don’t see any issue with building **x86_64** on x86 64 bit Ubuntu machine on latest master. The processor architecture will be automatically determined as CMake tool is run which would use CMakeLists.txt.  For azure-c-shared-utility you should see `azure-shared- -- Shared_Util architecture: x86_64` messages in your terminal output window if you are building on x86_64 architecture. 

Now if you are trying to build for Mac OS X using existing script then you are basically building for **cross-platform** scenario. Executable for building for Ubuntu (Linux) will have  ELF 64-bit LSB executable, x86-64 format whereas Mac OS X executable will have  Mach-O 64-bit x86_64 executable. There are 2 different formats. You have to build with compiler that builds for Mac OS X. There is work going to make the C client SDK build on Mac OS X.  Check https://github.com/Azure/azure-c-shared-utility/commit/cae5fd8b21b87eff073763f6ee60491b1c8f97f5#diff-75713e004674c106e192d7c1a123f6df for reference.

For running on iPhone,  currently there is a Xamarin option (cross-platform development software) also  which uses C#.  Check for  azure-iot-master\csharp\device\samples\DeviceClientSampleiOS sample. It uses C# programming language.

**Comment by anhashia** [comment]
Hi @jiangzhibin 
Just wanted to add that you also have an option of using **node.js** on Mac OS X. Install the node.js on Mac OS X. And then follow documentation at https://github.com/Azure/azure-iot-sdks/blob/master/node/device/core/readme.md to install the required **azure-iot-sdk** packages and run the sample after replacing connection string with you device connection string. Programming language here would be JavaScript.

**Comment by jiangzhibin** [comment]
@anhashia  Thanks for your patience! Please let me introduce our project requirements about IoT for you!

We need send orders to iOS device by azure IoT, so we must integrate the azure-iot-sdks into our app(iOS). As far as I know Xamarin which you suggested just only uses C# programming language, but we need code other project requirements using Objective-C, it may doesn't suit us.

In addition, There are three different formats on iPhone: armv7、armv7s and arm64,we have to support these architecture for running on iPhone.  

In a few words,we need build azure-iot-sdks for iPhone on mac OSX.Any suggestions would be appreciated!

**Comment by anhashia** [comment]
Hi @jiangzhibin 
For Mac OS X, work is currently going on. Please check 
https://github.com/Azure/azure-c-shared-utility/commit/cae5fd8b21b87eff073763f6ee60491b1c8f97f5

**Comment by anhashia** [comment]
Closing. Please re-activate if you have any further questions on this. Thanks !
