### ISSUE TITLE
[Java] Support IoTHub file upload API for Java device client

### ISSUE THREAD

**Issue by tkysmz** [Azure/azure-iot-sdks#776]
Hi.
I'm using Java device client, but it not supports IoTHub file upload API.
I need this API. It is scheduled to support for Java?

thanks.

**Comment by olivierbloch** [comment]
hi @tkysmz 
For now the file upload feature is supported in our JavaWrapper SDK, not in the native Java one. We are putting more focus and efforts on the JavaWrapper version as i allows us to bring new features faster to Java developers. I suggest you try it out and let us know what you think.
Thanks

**Comment by tkysmz** [comment]
hi @olivierbloch

In our case, We want to avoid cross building. (We have no envirinment for cross building now) And, JavaWrapper is little more complexity then using native JavaSDK. So, I want to use native JavaSDK, if it's supported.

Thanks.

**Comment by tameraw** [comment]
@tkysmz - We totally understand your concern. We're looking at options to bring in the latest SDK features into a Java SDK that is platform-independent.
Thanks.

**Comment by tkysmz** [comment]
Hi @tameraw

Wow, I'm waiting for being merged the feature.
Thank you so much.

**Comment by tameraw** [comment]
@tkysmz - FYI - This is currently a work-in-progress.
Regards.

**Comment by tkysmz** [comment]
Hi @tameraw 
Thank you for working. I'm really waiting for this.
Regards.

**Comment by tameraw** [comment]
Work has started. We'll try to share an ETA soon. Thanks.

**Comment by tkysmz** [comment]
Hi @tameraw Thank you for working.
How is this status ? I wander to know progress.

Regards.

**Comment by tameraw** [comment]
@tkysmz 
We'll be tracking progress of the Java missing features under the following project:
https://github.com/Azure/azure-iot-sdk-java/projects/1
FileUpload is on the list as one of the top features to bring in.
Also for java specific issues, we'll be monitoring those under the corresponding repo for java:
https://github.com/Azure/azure-iot-sdk-java/issues.
