### ISSUE TITLE
How to generate the x509 and private key for Azure IoT Hub?

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [Azure/azure-iot-sdks#782]
I am following [this](https://github.com/Azure/azure-iot-sdks/blob/master/python/device/samples/iothub_client_sample_x509.py#L45) example.

Thanks.

**Comment by rajeevmv** [comment]
You can use either [OpenSSL](https://www.openssl.org/) or [Windows SelfSignedCertificate](https://technet.microsoft.com/library/hh848633).

**Comment by tameraw** [comment]
@sanket-kulkarni-vmware - Please let us know if you have any other questions or issues. Thanks.
