### ISSUE TITLE
[node-red] Package.json missing Keywords

### ISSUE THREAD

**Issue by olivierbloch** [Azure/azure-iot-sdks#785]
In order for the node-red package to appear in the node-red flows/nodes library, the package.json file should contain at least the following keyword:
"Keywords":["node-red"]
I recommend also adding "azure" and "iot" keywords so that search results in npm and node-red libraries work better.
Guidances on node-red packaging are [here](http://nodered.org/docs/creating-nodes/packaging.html)

**Comment by pierreca** [comment]
Solved in https://github.com/Azure/azure-iot-sdks/commit/d8a12837b28c593a8781cde1aa5c99c53c780eae
