### ISSUE TITLE
Method to give the current status of Azure IoT connection in python SDK. 

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [Azure/azure-iot-sdks#787]
Hi,

I am using **official python SDK** to connect IoT Hub, I didn't find any method to check the status of connection with Azure IoT Hub. I am using MQTT protocol.

Thanks

**Comment by mregen** [comment]
@sanket-kulkarni-vmware The Python SDk is a wrapper for the C library. The only way to check is using get_send_status and track the message callback results.

**Comment by sanket-kulkarni-vmware** [comment]
@mregen thanks.
