### ISSUE TITLE
Python SDK method to close the connection with Azure IoT HUB.

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [Azure/azure-iot-sdks#788]
I am using python SDK for connecting the Azure Hub, I am using MQTT protocol. I didn't find any method to close the connection with Azure IoT Hub in Official python SDK.

**Comment by mregen** [comment]
@sanket-kulkarni-vmware the connection is implicitly closed when the Python IoTHubClient object is destroyed.

**Comment by sanket-kulkarni-vmware** [comment]
Thanks, it means official SDK does not support explicit method to close the existing connection with Azure IoT Hub?

**Comment by mregen** [comment]
@sanket-kulkarni-vmware yes there is no explicit method. when the object is destroyed the connection is closed.

the message set_message_callback() function receives only the c2d messages: https://msdn.microsoft.com/en-us/library/mt590786.aspx

**Comment by tameraw** [comment]
@sanket-kulkarni-vmware - Let us know if facing any issues. Thanks.
