### ISSUE TITLE
IoTHubClient accepted the message for delivery, but not showing up in Azure IoT Suite

### ISSUE THREAD

**Issue by ravenzachary** [Azure/azure-iot-sdks#795]
Hello. I purchased the Microsoft IoT Pack for Raspberry Pi 3 from Adafruit and followed the instructions here:

https://azure.microsoft.com/en-us/documentation/samples/iot-hub-c-raspberrypi-getstartedkit/

I was able to make it all the way through Step 1.6 (Build the Modified Sample), but when I got to Step 1.7, (View the Sensor Data from the IoT Suite Portal) the device I created remains in a Pending state, even though I am getting data off the device with the following log entries:

raw H = 0x00008000
Humidity = 62.5% Temperature = 23.3*C 
Sending sensor value Temperature = 23.3*C, Humidity = 62.5%
IoTHubClient accepted the message for delivery
(repeating over and over)

When I login to the Azure IoT Suite, there is no Telemetry History and I cannot select my device from the Device to View pull-down list. Under devices, I see my device remains in a Pending state.

It seems someone else had the same problem here (although with a different device type):

https://social.msdn.microsoft.com/Forums/en-US/897e474e-d270-429c-a2ce-c5dab93b61b9/iot-hub-client-accepted-the-message-for-delivery-but-doesnt-show-up-in-my-azure-iot-portal?forum=servbus

My device is connected to the Internet, as I am able to SSH to it, and out from it to the public Internet using a curl command. I have no firewall or port blocking on this network.

Any missing steps from that walkthrough tutorial that would explain my predicament? Thank you.

**Comment by DiogenesB** [comment]
I'm having the same issue here.

**Comment by ravenzachary** [comment]
This may be unrelated, but Rick Rainey's walkthrough of the Adafruit Feather Kit worked perfectly! That's a different kit that the one I referenced above, and setup steps are quite unique, but at least I was able to get one kit talking to the Azure IoT Hub!

http://rickrainey.com/2016/06/22/add-custom-device-azure-iot-suite-remote-monitoring-solution/

**Comment by ravenzachary** [comment]
Two of the devices I was running into this problem with have mysteriously shown up in my Azure IoT Suite dashboard. It looks like, in my case, there was some outage with the Azure IoT Suite that delayed the appearance of new devices by several days.

**Comment by sergaz-msft** [comment]
Hi @ravenzachary . Can you still reproduce the same issue you describe above? On the same or a different Azure IoT Suite project? Also please send me your subscription ID and the Azure IoT Suite name so that I can have a look at it on the date that the issue occurred (1st of September I suppose?). Thanks!

**Comment by sergaz-msft** [comment]
Hi again @ravenzachary I am setting this issue as solved since you can now see the devices on your Azure IoT Suite dashboard. Please feel free to let us know if you are still encountering any problems. Thanks!
