### ISSUE TITLE
ConnectionString with X509 (nodejs, c, python)

### ISSUE THREAD

**Issue by ChristianBeier** [Azure/azure-iot-sdks#798]
The connection string from Device Explorer contains "X509" whilst connection_string.js checks for "x509" as well as the c SDK and python. C#/.Net expects X509.
Please fix this inconsistency.

**Comment by tameraw** [comment]
@ChristianBeier - Thanks for filing this issue. We'll make the proposed fix soon.

**Comment by tameraw** [comment]
Fix provided in "develop" branch and ETA to release to master is end of this week.

**Comment by ChristianBeier** [comment]
Please ensure that the device explorer generated the right connection
string. Currently it generates capital X
