### ISSUE TITLE
Make async calls configurable with ConfigureAwait(continueOnCapturedContext)

### ISSUE THREAD

**Issue by mtuchkov** [Azure/azure-iot-sdks#799]
This is the best practice for libraries that allows to do a 'sync over async' in the user code and do not cause deadlocks.

See [Stephen Toub's blog post](https://blogs.msdn.microsoft.com/pfxteam/2012/04/13/should-i-expose-synchronous-wrappers-for-asynchronous-methods/) 

Also, see issue #764

**Comment by tameraw** [comment]
@mtuchkov - Closing this issue.
Feel free to file under the csharp repo if still necessary.
https://github.com/Azure/azure-iot-sdk-csharp
