### ISSUE TITLE
How to handle Microsoft.Azure.Devices.Client exception at UWP app, when TransportType set Amqp ? 

### ISSUE THREAD

**Issue by rainmakerho** [Azure/azure-iot-sdks#800]
Hi Sirs, 
May I ask a question? I use Microsoft.Azure.Devices.Client to receive message from IoThub in my UWP App. Because My IotHub Quota Exceeded. I can handle the QuotaExceeded, if TransportType set Http1.
If TransportType set Amqp, I can't handle exception. It will cause System.NullReferenceException, I can't handle error at UnhandledException Event.
May I handle exception when TransportType set Amqp ? 
The UWP app will crash because I can't handle Amqp exceptions  
Thanks.

Amqp's exceptions
System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in mscorlib.ni.dll
Additional information: Object reference not set to an instance of an object.

Exception thrown: 'System.NullReferenceException' in Microsoft.Azure.Amqp.Uwp.dll

An unhandled exception of type 'Microsoft.Azure.Devices.Client.Exceptions.IotHubSuspendedException' occurred in mscorlib.dll

Additional information: Iothub 

Tracking Id:ca047b5368ca4bad8009e3e589ca9e26-G:9-TimeStamp:09/06/2016 11:04:29 is suspended

Http1's exceptions 
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.QuotaExceededException' in Microsoft.Azure.Devices.Client.PCL.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.QuotaExceededException' in mscorlib.ni.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.QuotaExceededException' in mscorlib.ni.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.QuotaExceededException' in mscorlib.ni.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.QuotaExceededException' in Microsoft.Azure.Devices.Client.PCL.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.QuotaExceededException' in mscorlib.ni.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.QuotaExceededException' in mscorlib.ni.dll

my codes 
try
{
	ReceiveC2dAsync().ConfigureAwait(false);
}
catch (Exception ex)
{
	System.Diagnostics.Debug.WriteLine(ex.ToString());
}

private static async Task ReceiveC2dAsync()
{
	DeviceClient deviceClient = DeviceClient.CreateFromConnectionString(
				"HostName=gsstddhub.azure-devices.net;DeviceId=0521;SharedAccessKey=keys"
				, TransportType.Amqp
				);

	while (true)
	{
		Message receivedMessage = null;
		try
		{
			receivedMessage = await deviceClient.ReceiveAsync();
		}
		catch (Exception ex)
		{
			System.Diagnostics.Debug.WriteLine(ex.ToString());
		}
		if (receivedMessage == null) continue;
		await deviceClient.CompleteAsync(receivedMessage);
	}
}

**Comment by arturl** [comment]
Hi @rainmakerho,

Looks like there is a few things going on.

1. Microsoft.Azure.Devices.Client.PCL.dll does not support AMQP, Instead, you should use Microsoft.Azure.Devices.Client.winmd for UWP. If you just install the Microsoft.Azure.Devices.Client NuGet package, it will do the right thing for you. UWP supports both AMQP and HTTP.

2. The NullReferenceException is a bug, but it only happens during the error handling of your original "QuotaExceeded" error. I tried to simulated it with the binaries I built from source and could not -- there is a good chance that it's already fixed, and you will see the fix in the upcoming release.

If you have a stable repro (possibly with another server error), I can take another look.

**Comment by rainmakerho** [comment]
Hi @arturl ,
    I use Microsoft.Azure.Devices.Client.PCL.dll for debug purpose, because i can handle the NullReferenceException from Microsoft.Azure.Devices.Client NuGet package dll.

I'll look forward the new version.

Thank for your help.
