### ISSUE TITLE
[JAVA] Potential infinite loop while closing Device Client obj

### ISSUE THREAD

**Issue by kevinledinh** [Azure/azure-iot-sdks#803]
Hi Azure IoT Hub Team,

In normal operation the IoT Hub SDK automatically detects a loss and reconnects to the server. However, after running for > 4 hours, this automation mechanism seems to stop working, and I have to force a reconnection if no acknowledgement is heard from the Server. 

During the manual re-connection, I noticed that if the device is closed (using device.close() ) and re-opened (using device.open() ), another transport thread is created without stopping the the old threads. This will create another memory leak issue if manual re-connection is done frequently. For now, it is a penalty I'm willing to accept (hopefully, this will be addressed in future releases from the community). 

I've been looking into the close() method of the Device Client and just noticed that there is a while() loop which potentially locking up the code, see DeviceClient.java - line 221.

This while loop check if the transport object is empty. However, for some reason, when the DeviceClient.close() is called manually from my application, while while loop never returns. In the meantime, I'll add more debug trace in order to find out exactly what is blocking this while statement.

Has anyone encountered problem using close() ?

Any help is much appreciated.

**Comment by oriolpinol** [comment]
I encountered this problem as well and reported it: #684

**Comment by kevinledinh** [comment]
Thanks @oriolpinol . My workaround is to break out of the loop after a certain timeout. I'll keep an eye for the fix.

**Comment by kevinledinh** [comment]
A bit more information:

While checking if the transport is empty, the inProgress message queue is never emptied, and it never will be if a reconnection is not established. Therefore, the while loop never returns.

**Comment by tameraw** [comment]
@kevinledinh - Thanks for filing this issue. We're investigating.

**Comment by prmathur-microsoft** [comment]
Hi Kevin,

As per our email conversation, Can you try against latest develop which has changes related to memory leak fix in java and notify me back if you still see a leak.

Also as requested earlier, can you please provide me more details about the connection break in  > 4 hours.

Thanks
Priyanka

**Comment by tameraw** [comment]
@kevinledinh - Closing issue. Please feel free to let us know if you're still encountering problems. Thanks.
