### ISSUE TITLE
[C][Linux] Connection retry frequency

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#804]
Hi,
I encounter an issue with the connection retry mechanism on a small target.
If I try to connect to the iot hub without a network link it obviously fails, but the static int ScheduleWork_Thread(void* threadArgument) function runs every 1ms.
And on my target, it take almost all the CPU. What I plan is to patch the SDK to slow the loop a bit, but what I don’t see is impacts of doing that, will I only slow things down or doing this will raise problems like race condition and other weird synchro bugs ?

**Comment by lmussier** [comment]
Made some tests, and we ran into an authentication time out at some point (go from 1ms to 1s in schedule work). The next question is how to slow things...

**Comment by tameraw** [comment]
@lmussier - Slowing things down in the SDK should work. Let us know if you encounter any issues.
FYI - We are currently working on providing knobs to the users of the SDKs to select a "Retry Policy" and bound the retry to a specified timeout.

**Comment by IngoMaindorfer** [comment]
@tameraw - Nice info about the "Retry policy". Can you estimate roughly when that feature will be available?

**Comment by tameraw** [comment]
@IngoMaindorfer - Work has started on this. Expect to start seeing some of these feature updates rolling into the SDK in the releases next month.
A link to the GitHub project is here:
https://github.com/Azure/azure-iot-sdks/projects/2
