### ISSUE TITLE
There is no method available in C library to read message-id property like in Proton C

### ISSUE THREAD

**Issue by rajvael** [Azure/azure-iot-sdks#81]
There is no method available in C library to read message-id property like in Proton C. Message id is important to match request and response sending and receiving from C2D. Please add methods in iothub_message.h to get message-id property. But in .Net/Java API Message class has MessageId property to get messageId.

**Comment by dcristoloveanu** [comment]
This sounds like a bug, we are investigating it.

**Comment by jebrando** [comment]
This will be address in the next release.

**Comment by jebrando** [comment]
There is now a function of IoTHubMessage_GetMessageId which returns the message ID of the message.  See iothub_message.h for more information.  This will be available on the next release date.

**Comment by rajvael** [comment]
Is it possible to add SetMessageId , GetCorrelationId and SetCoorelationId methods too?

**Comment by tameraw** [comment]
SetMessageId already exists (under the develop branch). We filed a bug to also add GetCorrelationId & SetCorrelationId and will update this thread once checked in.
