### ISSUE TITLE
EROFS Error on DefaultCertificate

### ISSUE THREAD

**Issue by jackoneill23** [Azure/azure-iot-sdks#814]
I'm not able to estabilish connection to my iot-hub because i gain the error in the object.
I'm running it on android M version 6.0.1.
The version of the lib is 1.0.13, but i have this error also with the oldest version.

this is the error:

java.io.IOError: java.io.IOException: open failed: EROFS (Read-only file system)
at com.microsoft.azure.iothub.DefaultCertificate.getDefaultCertificate(DefaultCertificate.java:52)
at com.microsoft.azure.iothub.DeviceClientConfig.<init>(DeviceClientConfig.java:83)
at com.microsoft.azure.iothub.DeviceClient.initIotHubClient(DeviceClient.java:340)
at com.microsoft.azure.iothub.DeviceClient.<init>(DeviceClient.java:155)

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Hi @jackoneill23 
I will try to see if I can locally reproduce the issue. I am assuming that you are using following steps https://github.com/Azure/azure-iot-sdks/blob/master/doc/iotcertification/iot_certification_android_java/iot_certification_android_java.md to build and test the **sample**. Is that correct  ?

**Comment by jackoneill23** [comment]
Hi @anhashia thanks for your reply.
I was already working on my own project with 1.0.7 version of the library and everything was ok when I was compiling on **debug**.

When I run the application on **release** mode I found that the app crashes with this error: "java.lang.ExceptionInInitializerError" so I started to investigate about this and I updated the version of the library to the latest one and now I have the issue that I explained on my previous post.

Anyway now I will run again the sample to check if I have the same issue.

**Comment by anhashia** [comment]
Hi @jackoneill23 
I tried with debug mode (which is by default) and it worked fine. My next step will be to try in **release** mode and check if I see the same error that you are seeing.

**Comment by anhashia** [comment]
Hi @jackoneill23 
I didn't see the issue in **release** mode with default 1.0.7 that sample uses . But I do see the issue locally that you reported on latest **1.0.13** iothub-java-device-client library . It needs some further investigation. In the meantime, you can use 1.0.9 if you want to upgrade from 1.0.7 to later versions. 1.0.9 doesn't have this issue.

**Comment by jackoneill23** [comment]
Hi @anhashia, 
using 1.0.9 version and AMQPS protocol it works fine.
if I try to use MQTT protocol instead I have  "java.lang.ExceptionInInitializerError" exception.

Thanks a lot for your support.

**Comment by anhashia** [comment]
I was able to send and receive using **MQTT** protocol. I set `IotHubClientProtocol protocol = IotHubClientProtocol.MQTT` in the sample.

Library I used was  `iothub-java-device-client:1.0.9`.  I tested it both on actual Android **device** and Android Emulator.

**Comment by anhashia** [comment]
Closing this. Please re-activate if you have any further questions on this. Thanks !

**Comment by pcarbajals** [comment]
Hi @anhashia,

Any updates about fixing this issue? 

Just as you mention above, I am having the error EROFS with iothub-java-device-client:1.0.13 but everything works well when switching to iothub-java-device-client:1.0.9. I am initializing my DeviceClient object using MQTT.

Thanks.

**Comment by anhashia** [comment]
Hi @pcarbajals 
Please test with latest available com.microsoft.azure.iothub-java-client:iothub-java-device-client:**1.0.14** . It has the fix.

**Comment by pcarbajals** [comment]
@anhashia, great! I'm not having the EROFS error anymore. Thank you.
