### ISSUE TITLE
Azure IOT C# device client  SDK: X509 certificate based authentication throws "Unauthorized exception"

### ISSUE THREAD

**Issue by Kunjan123** [Azure/azure-iot-sdks#815]
Hi,

Microsoft. Azure.devices version : 1.0.15
Microsoft.Azure.devices.client : 1.0.19

I wrote a sample application modifying C# sample for AMQP. Modification is regarding AMQP over web sockets using X509 certificate based authentication.

I have registered the certificate thumbprint in IOT hub. But when I try to send message to cloud, I always encounter an "Unauthorized" exception in the IOT client

My sample application is attached. I have tried the transport type as http1 and it works fine with the same device and certificate. 

Any help will be very much appreciated

**Comment by rajeevmv** [comment]
I don't see the sample application attached. Also, can you provide your IotHub name and time window of failure?

**Comment by Kunjan123** [comment]
Hi Rajeev,
Please find the required details.

IOT Hub name : CSA-IoTSP-Secure-Hub
Time windows of failure - 13th September between 2-4 PM Central European time
                                          14th September 10 - 10.15 AM Central European time

[sample.docx](https://github.com/Azure/azure-iot-sdks/files/471556/sample.docx)
Somehow am not able to upload .zip files. So I have copied the sample program to a word file and uploaded the same.

**Comment by rajeevmv** [comment]
Hi Kunjan123,

I will take a look at your sample. In the meantime, please remove the private credentials from your document.

**Comment by Kunjan123** [comment]
Thanks. Attached the cleaned up sample

**Comment by rajeevmv** [comment]
Please remove the IotHub connection string entirely.

**Comment by Kunjan123** [comment]
Ok.

**Comment by rajeevmv** [comment]
I ran the attached X509 sample against your IotHub using a self-signed cert and it worked fine. Can you give it a try after plugging in your IotHub details and your X509 cert?

[X509Sample.zip](https://github.com/Azure/azure-iot-sdks/files/472656/X509Sample.zip)

**Comment by Kunjan123** [comment]
Hi Rajeev,

Thanks for your reply. If this is the sample from 
https://github.com/Azure/azure-iot-sdks/issues/759

I have already tried it. I do get the same error "Unauthorized exception" with this as well. I am not sure what is going wrong. Can it be a configuration issue?

The strange thing is that it just works fine, when I change the transport type to http1

**Comment by Kunjan123** [comment]
I tried the sample you sent just now as well, just replacing the certificate and IOT hub details there. It gives me unauthorized exception again. can it  be something to do with the certificate which I use?

**Comment by rajeevmv** [comment]
Can you retry the sample while also reusing its certificate from #759 ? 

From the logs on the service, it appears that the DeviceClient is not presenting the certificate to the service. I would verify using a debugger that the X509Certificate2 object is properly initialized with the correct certificate details.

**Comment by sbuster** [comment]
I also get an UnauthorizedException using the X509Sample provided above.  I'm able to successfully register the device but when I try to send data it throws an exception.

Couple of items that are not clear to me:
1) I'm assuming I use my public certificate when registering the device?
2) Is there a specific format of the key I should
3) Why can I create a device with the key (and see it in DeviceExplorer) but not post data in the same program?

Thanks

**Comment by Kunjan123** [comment]
Hi Rajeev,

I tried also the certificate files in the #759 . But still I get the same error.
I checked the X509Certificate2 using the debugger and it seems to be properly initialized.
Not sure what exactly is going wrong.

Thanks

**Comment by Kunjan123** [comment]
By the way, I verified the wireshark logs and I can see that the client certificate is not sent as part of TLS handhsake

**Comment by rajeevmv** [comment]
Which version of the DeviceClient NuGet package are you using?

**Comment by Kunjan123** [comment]
Hi Rajeev,
sorry for the delay. I was travelling.

I am using 
Microsoft.Azure,.devices  version 1.0.14
Microsoft.Azure.devices.client version 1.0.17

I see that devices.client version 1.0.19 has been released. Will upgrading to 1.0.19 solve the issue?

Thanks

**Comment by rajeevmv** [comment]
I was using Microsoft.Azure.Devices.Client version 1.0.13 when I successfully ran the X.509 sample above. I am not aware of any issues with using version 1.0.17 or even the latest (1.0.19). 

One other option might be to clone the solution for azure-iot-sdks and build you own version of the Microsoft.Azure.Devices.Client.dll. You could set a breakpoint in [IotHubConnection.cs](https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/Microsoft.Azure.Devices.Client/IotHubConnection.cs) line 236 where the client cert is set on the client websocket and see if it is somehow null when it gets to that point.

**Comment by Kunjan123** [comment]
Hi Rajeev,

Am not sure what is happening. But can you also try with the same versions in which I have tried?
I have not done any modification to the X509Sample you have provided apart from the IOT hub details.

I have debugged into the IotHubconnection.cs and also the web socket layer, but I could not identify where the problem is?

Thanks

**Comment by sbuster** [comment]
I have successfully used the the sample above with a self signed certificate.  Are you properly generated your certificate?  I get similar error when I try with invalid certificate.

**Comment by navilwayne** [comment]
Hi Rajeev/Folks
- I tried the sample given on azure documentation 'Register an X.509 client certificate for a device', I am also facing the issue while sending the data to IOT HUB. 
https://azure.microsoft.com/en-in/documentation/articles/iot-hub-sas-tokens/#register-an-x509-client-certificate-for-a-device

- Azure sdk version > 1.0.20 (stable)

- One thing I saw when you register a device using thumbprint, we can't see the thumbprint print key on IOT HUB platform side?
Please give suggestions, what I am missing ?

Thanks.

**Comment by rajeevmv** [comment]
@navilwayne,

Are you using the C# SDK ? How are you creating the DeviceClient? 
You can retrieve the configured thumbprint of a device from the IotHub using the RegistryManager:
   _await registryManager.GetDeviceAsync(device.Id);_

**Comment by navilwayne** [comment]
- Yes , I am using the C# SDK- Version - 1.0.20 (downloaded from Nuget) 
- I am using the Device client as -   
 **deviceClient = DeviceClient.Create(iotHubUri, new DeviceAuthenticationWithX509Certificate("deviceID",x509Certificate));**

An exception of type 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' occurred in mscorlib.dll but was not handled in user code
Inner EXCEPTION
{"\r\nTracking Id:b8b1ae2200214d098547579a3d94466f-G:3-TimeStamp:09/29/2016 06:27:22"}

**Comment by rajeevmv** [comment]
@navilwayne,

For the above tracking id ( b8b1ae2200214d098547579a3d94466f-G:3), the error I see in the service indicates that a device with an Id of "device_X.509" tried to connect. However, no device with such an Id is registered with the IotHub "demoIOTHubDevicemanager". 

FYI - you can also use [operational monitoring](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-operations-monitoring/) to look for logs to help diagnose these types of issues. You should look for these under the "Connections" category.

**Comment by navilwayne** [comment]
Thanks Rajeev

**Comment by tameraw** [comment]
@navilwayne - Currently the C# SDK does not support file upload with X509. It is high in our backlog to provide that.

**Comment by tameraw** [comment]
In regards to the initial issue for which this was filed, appears that one of the problems was that the Device ID was not created. 
As for the support of FileUpload with X509 cert, that will be a feature enabled in the SDK soon.
Closing, and please let us know if still having any problems.
