### ISSUE TITLE
Java SDK NoSuchElementException AMQPS transport

### ISSUE THREAD

**Issue by oriolpinol** [Azure/azure-iot-sdks#818]
Hi,
My application just got stuck in an infinite loop throwing NoSuchElementException:

`java.util.NoSuchElementException: null
java.util.LinkedList.removeFirst(LinkedList.java:270)
java.util.LinkedList.remove(LinkedList.java:685)
com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.invokeCallbacks(AmqpsTransport.java:240)
com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:27)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
java.util.NoSuchElementException: null
java.util.LinkedList.removeFirst(LinkedList.java:270)
java.util.LinkedList.remove(LinkedList.java:685)
com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.invokeCallbacks(AmqpsTransport.java:240)
com.microsoft.azure.iothub.transport.IotHubSendTask.run(IotHubSendTask.java:27)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)`

I reported this behaviour previously https://github.com/Azure/azure-iot-sdks/issues/684#issuecomment-232334812 and we hoped it would be fixed with some socket improvements that were done but it looks like the problem still remains.

I am using the library version 1.0.12. Java SDK. AMQPS transport.

Thank you very much! All the help is really appreciated!

**Comment by zolvarga** [comment]
Hi oriopinol,

I am working on the fix and will let you know...

Zoltan

**Comment by oriolpinol** [comment]
@zolvarga Great! Thanks!

**Comment by zolvarga** [comment]
Hi oriopinol,

The fix checked in to develop branch. Please let me know if it worked for you.

Thanks,
Zoltan

**Comment by tameraw** [comment]
@oriolpinol - Closing. Please feel free to open a new issue if still having any problems. Thanks.
