### ISSUE TITLE
CloseAsync() Does Not Close IoT Hub Connection 

### ISSUE THREAD

**Issue by robichaud** [Azure/azure-iot-sdks#821]
There is a bug in the `GateKeeperDelegatingHandler` class's `CloseAsync()` method: Calling this method does not close the IoT Hub connection as it should.

[GateKeeperDelegatingHandler Line 116](https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/Microsoft.Azure.Devices.Client/Transport/GateKeeperDelegatingHandler.cs#L116)

_Simple fix:_ `if (!this.TryCloseGate())` _should be_ `if (this.TryCloseGate())`

A pull request will follow

**Comment by tameraw** [comment]
@robichaud - Thanks for reporting this. We're looking at it.

**Comment by tameraw** [comment]
Closing as PR has been addressed.
