### ISSUE TITLE
setup.bat leads to ErrorCode:InvalidProtocolVersion;BadRequest

### ISSUE THREAD

**Issue by yaweiw** [Azure/azure-iot-sdks#828]
Provisioning devices...
Deserializing sampledevices.json
{"Message":"ErrorCode:InvalidProtocolVersion;BadRequest","ExceptionMessage":"Tracking ID:a33335f891bd4d3a9d6d5656c32bece0-G:4-TimeStamp:09/18/2016 03:48:41"}

Looks somethings to do with nugget package version referenced.

**Comment by pierreca** [comment]
Hi @yaweiw 

a little more context would help. Are you trying to run the Device Management Samples? in what language? Have you enabled device management preview on your hub?

**Comment by markbdev** [comment]
Seeing the same error code using nuget package Microsoft.Azure.Devices v1.0.15 and v1.1.0-preview-003, when registering a device from within a service fabric service.

**Comment by markbdev** [comment]
We have now resolved this. The problem occurred due to mixed versions of the package across different projects and solutions.

**Comment by tameraw** [comment]
@yaweiw - @markbdev 
Please let us know if still having any issues. Regards.

**Comment by yaweiw** [comment]
@tameraw was stuck in the middle of something. will verify and let you know.
