### ISSUE TITLE
C SDK MQTT - Intermittent Network Connection

### ISSUE THREAD

**Issue by twgcriot** [Azure/azure-iot-sdks#830]
I am using C SDK and MQTT transport. My device has intermittent connection to internet. When the network connection drops, the C SDK does not raise any error. Also when the network connection resumes the messages sent during the network failure or even after it don't reach IoT Hub.

How long (or how many messages) does the C SDK buffer in the event of network disruption?

Is there a way to check status of underlying connection before sending messages?

**Comment by tameraw** [comment]
@twgcriot - Thanks for reporting this:
“When the network connection drops, the C SDK does not raise any error.”
This is true. We’re in the midst of refining the APIs to allow detecting such an event.

“Also when the network connection resumes the messages sent during the network failure or even after it don't reach IoT Hub.”
We have retry logic implemented which should re-connect once the network connection is up again.
If this does not happen it is a bug. Can you give us repro steps and platform details?

"How long (or how many messages) does the C SDK buffer in the event of network disruption?"
The C SDK will buffer messages until runs out of memory.

**Comment by twgcriot** [comment]
Thanks Tamer.

Can you explain how does the retry logic work? For instance, how long does the SDK take to detect that network has been restored?

For MQTT,
https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/src/iothubtransportmqtt.c

#define DEFAULT_MQTT_KEEPALIVE      4*60 // 4 min
#define RESEND_TIMEOUT_VALUE_MIN    1*60
#define DEFAULT_CONNECTION_INTERVAL 30

What would be implications of tweaking the above parameters?

**Comment by tameraw** [comment]
@twgcriot 
"Can you explain how does the retry logic work? For instance, how long does the SDK take to detect that network has been restored?"
Once the message timeout expires, the SDK will resend and will keep doing this forever, unless a connection loss is detected. A connection loss can be detected by the SDK when the ACK to the Keep Alive pings that the SDK send is not received.

Responding to tweaking the parameters below:
#define DEFAULT_MQTT_KEEPALIVE 4*60 // 4 min
--> This is required to maintain the connection between the device and the server. Should not exceed 4 minutes.

#define RESEND_TIMEOUT_VALUE_MIN 1*60
--> How often to retry sending in minutes. It's OK to play with that one.

#define DEFAULT_CONNECTION_INTERVAL 30
--> How often to retry the connection in seconds. It's OK to play with that one.

**Comment by tameraw** [comment]
@twgcriot - Closing this one. Please let us know if still having any issues or questions.
