### ISSUE TITLE
C SDK contains multiple latin-1 sources which causes compilation error

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-iot-sdks#832]
I noticed that following files are saved as Latin-1 encoding, so it causes compilation error because of "treating warning as error" when the developer uses non Latin-1 code page console in Windows. 
It is just messy when I build sources, but it is better and easy to save as UTF-8. Thanks!
- c/azure-uamqp-c/src/connection.c
- c/azure-uamqp-c/src/frame_codec.c
- c/azure-uamqp-c/src/saslclientio.c
- c/azure-uamqp-c/src/sasl_frame_codec.c
- c/azure-uamqp-c/tests/connection_ut/connection_ut.cpp
- c/azure-uamqp-c/tests/frame_codec_ut/frame_codec_ut.cpp
- c/azure-uamqp-c/tests/sasl_frame_codec_ut/sasl_frame_codec_ut.cpp
- c/azure-uamqp-c/tests/saslclientio_ut/saslclientio_ut.cpp
- c/iothub_client/src/iothubtransportmqtt.c
- c/iothub_client/tests/iothubtransportmqtt_ut/iothubtransportmqtt_ut.cpp

**Comment by tameraw** [comment]
@yfakariya - Just wanted to let you know that this is still on our plate to address. We'll provide you an update soon.

**Comment by yfakariya** [comment]
@tameraw Thank you!

**Comment by jtanner-msft** [comment]
Hi @yfakariya,
  I just wanted to let you know that I'll be looking into making these changes for you soon.  I'll let you know once I have an additional update.

**Comment by yfakariya** [comment]
I see. Thank you again.

**Comment by jtanner-msft** [comment]
Hi @yfakariya,

  All of the files in the list above should now be encoded at UTF-8 in the C repository (and below) within the develop branch.
https://github.com/Azure/azure-iot-sdk-c/ 

  If you find any in the above list that are still not UTF-8 please feel free to re-activate this issue (or file a new one).  As any FYI I'm also working on fixing the file xlogging.h, but that is not fully resolved yet but should be soon.
