### ISSUE TITLE
General SSL problem using Java device client with SSL

### ISSUE THREAD

**Issue by sbuster** [Azure/azure-iot-sdks#833]
I'm trying to run the samples.com.microsoft.azure.iothub.SendEvent example with a certificate and keep getting the error below.  
Some general questions I have are what requirements are there for generating a cert?  key strength, algorithms...?

I used the example code in https://github.com/Azure/azure-iot-sdks/issues/815 to test everything works fine from C# and it does.  The issues seems to be when I use the Java client.

iothub-java-client 1.0.12
Java 8
Windows 7

I also turned on -Djavax.net.debug=all and got additional details.

I'm unclear if the path refers to the path of my certificate or if there is a missing ca,certs.... in the java keystore?

***
pool-1-thread-1, fatal error: 46: General SSLEngine problem
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
%% Invalidated:  [Session-1, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256]
pool-1-thread-1, SEND TLSv1.2 ALERT:  fatal, description = certificate_unknown
pool-1-thread-1, WRITE: TLSv1.2 Alert, length = 2
pool-1-thread-1, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLHandshakeException: General SSLEngine problem
Sep 20, 2016 9:26:48 AM org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper process
WARNING: General SSLEngine problem
[Raw write]: length = 7
0000: 15 03 03 00 02 02 2E                               .......
Exception in thread "main" java.io.IOException: java.io.IOException: Error opening Amqp connection:

**Comment by tameraw** [comment]
@sbuster - Thanks for reporting this. We'll investigate the issue.

**Comment by anhashia** [comment]
Hi @sbuster 
The command line option in **send-event** Java sample is for validating Root CA sent by the Server as part of TLS handshake. It is for **1-way** SSL authentication . It is not for specifying **client side certificate** (2-way SSL authentication). 

You need to specify this option in case you don't have server side Root CA in your certificate store and you want to point to a certificate file. That file is located at c\certs\ms.der

**Comment by anhashia** [comment]
Closing. Please re-activate if you still are having issues. Thanks !
