### ISSUE TITLE
don't receive c2d message feedback 

### ISSUE THREAD

**Issue by guybartal** [Azure/azure-iot-sdks#838]
hi,

i've followed this article:
[https://azure.microsoft.com/en-us/documentation/articles/iot-hub-node-node-c2d/](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-node-node-c2d/)

and i don't receive c2d message feedback.

here's my code:

```
'use strict';

var Client = require('azure-iothub').Client;
var Message = require('azure-iot-common').Message;

var client = Client.fromConnectionString(connectionString);

client.open(function (err) {
    if (err) {
        console.error('Could not connect: ' + err.message);
    } else {
        console.log('Client connected');
        client.getFeedbackReceiver(receiveFeedback);

        var data = JSON.stringify({ text: 'foo' });
        var message = new Message(data);
        message.ack = 'full';
        message.messageId = 'TurnOnLightsInRoom';
        console.log('Sending message: ' + message.getData());
        client.send(targetDevice, message, printResultFor('send'));
    }
});

// Helper function to print results in the console
function printResultFor(op) {
    return function printResult(err, res) {
        if (err) {
            console.log(op + ' error: ' + err.toString());
        } else {
            console.log(op + ' status: ' + res.constructor.name);
        }
    };
}

function receiveFeedback(err, receiver) {
    receiver.on('message', function (msg) {
        console.log('Feedback message:');
        var feedbackData = msg.getData();
        console.log(feedbackData.toString('utf-8'));
    });
}
```

**Comment by pierreca** [comment]
Hi @guybartal 

at first glance the code looks correct. Do you see the message coming in on the simulated device? is there any error when calling complete() and passing it the message?
Can you paste the command line log on both the device and the service application side?

**Comment by pierreca** [comment]
@guybartal 
We got a repro by using an older version of NPM and nested dependency trees. I've pushed a fix and it will make it to the next release (in the next couple of days).

You can temporarily circumvent this problem by updating to npm v3 and cleaning your node_modules folder, then run npm install again.

Thanks for filing this issue!

**Comment by pierreca** [comment]
Closing assuming it's resolved. Feel free to reopen if that wasn't the case.

**Comment by guybartal** [comment]
it's working now, thanks! 

I have another issue regarding the feedback message.. I don't receive the message properties back from the original message. 

[https://github.com/smart-home-bot/bot/blob/master/app.js](https://github.com/smart-home-bot/bot/blob/master/app.js) line number 68

I want to store information in the c2d which I need to have it back in the feedback message. what is the proper way to code it?
