### ISSUE TITLE
CorrelationId is not set in FeedbackRecord (Java Service SDK)

### ISSUE THREAD

**Issue by lruchandani** [Azure/azure-iot-sdks#840]
CorrelationId is not set in the FeedbackRecord , refer FeedbackBatchMessage class. Probably , it should be set to originalMessageId as its done in C# SDK
[https://github.com/Azure/azure-iot-sdks/blob/e06ad8be39e4c3bb0abe3e6ebaeed7e3bdb4edd2/java/service/iothub-service-sdk/src/main/java/com/microsoft/azure/iot/service/sdk/FeedbackBatchMessage.java](url)

**Comment by tameraw** [comment]
@lruchandani - You're correct. We'll look at this one.

**Comment by tameraw** [comment]
PR #768 should address this issue.

**Comment by tameraw** [comment]
@lruchandani - A PR related to this issue has been merged. Please let us know if still having any issues.
Thanks.
