### ISSUE TITLE
Node.js client connect errors - "Not authorized"

### ISSUE THREAD

**Issue by dick** [Azure/azure-iot-sdks#844]
I am dealing with an unreliable network connection and seem to be getting frequent "Not authorized" errors thrown from MQTT on client.open().

No issues with my connection strings, as everything goes through normally if the connection is OK on bootup (e.g. I restart Raspberry Pi with modem already booted up). 

Issues:

- Sporadic "not authorized" errors on connection. I can't totally predict when they will happen, but they are more consistent when network connection is not immediately available.
- My connectCallback is firing even when the errorCallback fires, which seems likely to be a bug on my side, but I don't see it.

Any ideas on how to connect more reliably?

Here is my openClient function: 
var openClient = function (connectCallback, errorCallback) {

    var device = new Iothub.Device(null);
    device.deviceId = config.myDeviceId;
    
    var client = Client.fromConnectionString(config.deviceConnectionString, Protocol);

    client.open(function (err) {
        if (err) {
            console.log("Error opening IotHubClient!", err);
            errorCallback("iot hub client open error: ", err);
        } else {
            console.log("IotHubClient is open.");
            // Bind client to "this" for the callback function
            connectCallback.bind(client)();
        }
    });
};

Here is my connectCallback:
var connectCallback = function () {
    logConsole('Client connected');
        
    client = this;
    IotHubClient = client;

    logConsole("Setting IoT Hub interval");
    intervalIotHub = setInterval(function () { sendADC(client); }, config.reportPeriod);

    setLED(iotLED);

    client.on('message', function (msg) {
        var jsonData;

        try {
            jsonData = JSON.parse(msg.getData());
        } catch (e) {
            logConsole("JSON parse failed: ", msg.getData());
            var echo = { "Received from cloud:": msg };
            client.sendEvent(echo, printResultFor('send'));
        }

        if (jsonData.reportPeriod) {
            logConsole("updating config: ", jsonData);

            config.reportPeriod = jsonData.reportPeriod;
            
            if (intervalIotHub) {
                logConsole("Clearing iothub interval because a new report period was sent to config.");
                clearInterval(intervalIotHub);
            }

            intervalIotHub = setInterval(function () { sendADC(client); }, config.reportPeriod);
        }

        if (jsonData.ain1) {
            config.ain1.name = jsonData.ain1.name;
            config.ain1.config = jsonData.ain1.analog;
            logConsole("updated config: ", config);
        }

        client.complete(msg, function () {
            logConsole('c2d message completed');
        });
    });

    client.on('error', function (err) {
        logConsole("IOT Client Error:", err.message);
    });

    client.on('disconnect', function () {
        logConsole("IOT Hub Disconnected");
        setLED(iotErrorLED);
        if (intervalIotHub) { clearInterval(intervalIotHub); }
        client.removeAllListeners();
        IotHubClient = null;
    });

    openingClient = false;
};

Here is my errorCallback: 
function errorCallback (msg, err) {
    logConsole(msg.toString(), err.toString());
    if (intervalIotHub) { clearInterval(intervalIotHub); }
    intervalIotHub = null;
    if (IotHubClient) {
        IotHubClient = null;
    }
    openingClient = false;
}

**Comment by dick** [comment]
Example error log:

Error opening IotHubClient! Error: Connection refused: Not authorized
   at MqttClient.prototype._handleConnack (C:\Data\Users\DefaultAccount\AppData\Local\Packages\petropi5_k2qva3ds8n4c6\LocalState\node_modules\mqtt\lib\client.js:720:5)
   at MqttClient.prototype._handlePacket (C:\Data\Users\DefaultAccount\AppData\Local\Packages\petropi5_k2qva3ds8n4c6\LocalState\node_modules\mqtt\lib\client.js:292:7)
   at process (C:\Data\Users\DefaultAccount\AppData\Local\Packages\petropi5_k2qva3ds8n4c6\LocalState\node_modules\mqtt\lib\client.js:234:7)
   at writable._write (C:\Data\Users\DefaultAccount\AppData\Local\Packages\petropi5_k2qva3ds8n4c6\LocalState\node_modules\mqtt\lib\client.js:244:5)
   at doWrite (C:\Data\Users\DefaultAccount\AppData\Local\Packages\petropi5_k2qva3ds8n4c6\LocalState\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:237:3)
   at writeOrBuffer (C:\Data\Users\DefaultAccount\AppData\Local\Packages\petropi5_k2qva3ds8n4c6\LocalState\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:227:5)
   at Writable.prototype.write (C:\Data\Users\DefaultAccount\AppData\Local\Packages\petropi5_k2qva3ds8n4c6\LocalState\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:194:5)
   at ondata (_stream_readable.js:555:5)
   at emitOne (events.js:96:5)
   at emit (events.js:188:7)
   at readableAddChunk (_stream_readable.js:172:11)
   at Readable.prototype.push (_stream_readable.js:130:3)
   at onread (net.js:535:5)

**Comment by jtanner-msft** [comment]
Hi @dick,

  What OS are you running on the Raspberry Pi?  Based upon the error log I would guess Windows 10 IoT Core, but wanted to double check.  If that is the case, what build are you using?
  Also, is it only MQTT that you see the problem with, or do you observe the same behavior if you use HTTPS or AMQP instead?

Thanks,
~Jonathan

**Comment by dick** [comment]
Hi @jtanner-msft,

I'm running Windows 10 IoT Core 10.0.14915.1000. I'm having trouble with all of the protocols. I tried AMQP and HTTPS yesterday with no luck. AMQP throws a similar "unauthorized" error, and HTTPS doesn't get messages through to the hub, but I don't know what specific error it's throwing. 

Thanks!
Dick

**Comment by dick** [comment]
* I'm running Windows 10 IoT Core 10.0.14915.1000 on a Raspberry Pi 2.

**Comment by jtanner-msft** [comment]
Hi @dick,

Thank you for providing that information.  It sounds like you’re using the most recent insider preview release of IoT Core.  As a test have you tried running with a C# client on the device?  Does it also have the same errors, or are they specific to Node.js?

Thanks,
~Jonathan

**Comment by dick** [comment]
@jtanner-msft I have almost no experience with C#. Is there a good example you can point me to? I can get a console app running locally to connect to the IoT Hub just fine, but I haven't found an example of a UWP app that also connects to IoT Hub...

**Comment by dick** [comment]
I tried this app with no luck. Messages were written to debug console but never showed up when monitoring in Device Explorer. I didn't see any errors thrown either, though.

`using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.ApplicationModel;
using Windows.ApplicationModel.Activation;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Azure.Devices.Client;
using System.Diagnostics;
using Newtonsoft.Json;

namespace App2
{
    /// <summary>
    /// Provides application-specific behavior to supplement the default Application class.
    /// </summary>
    sealed partial class App : Application
    {
        static DeviceClient deviceClient;
        static string iotHubUri = "<>";
        static string deviceKey = "<>";

        private static async void SendDeviceToCloudMessagesAsync()
        {
            double avgWindSpeed = 10; // m/s
            Random rand = new Random();

            while (true)
            {
                double currentWindSpeed = avgWindSpeed + rand.NextDouble() * 4 - 2;

                var telemetryDataPoint = new
                {
                    deviceId = "myRPi2",
                    windSpeed = currentWindSpeed
                };
                var messageString = JsonConvert.SerializeObject(telemetryDataPoint);
                var message = new Message(Encoding.ASCII.GetBytes(messageString));

                await deviceClient.SendEventAsync(message);
                Debug.WriteLine("{0} > Sending message: {1}", DateTime.Now, messageString);

                Task.Delay(1000).Wait();
            }
        }

        /// <summary>
        /// Initializes the singleton application object.  This is the first line of authored code
        /// executed, and as such is the logical equivalent of main() or WinMain().
        /// </summary>
        public App()
        {
            Debug.WriteLine("Simulated device\n");
            //deviceClient = DeviceClient.Create(iotHubUri, new DeviceAuthenticationWithRegistrySymmetricKey("myRPi2", deviceKey));
            deviceClient = DeviceClient.CreateFromConnectionString("<>");
            SendDeviceToCloudMessagesAsync();
            //Console.ReadLine();
            //this.InitializeComponent();
            //this.Suspending += OnSuspending;
        }

        /// <summary>
        /// Invoked when the application is launched normally by the end user.  Other entry points
        /// will be used such as when the application is launched to open a specific file.
        /// </summary>
        /// <param name="e">Details about the launch request and process.</param>
        protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
#if DEBUG
            if (System.Diagnostics.Debugger.IsAttached)
            {
                this.DebugSettings.EnableFrameRateCounter = true;
            }
#endif
            Frame rootFrame = Window.Current.Content as Frame;

            // Do not repeat app initialization when the Window already has content,
            // just ensure that the window is active
            if (rootFrame == null)
            {
                // Create a Frame to act as the navigation context and navigate to the first page
                rootFrame = new Frame();

                rootFrame.NavigationFailed += OnNavigationFailed;

                if (e.PreviousExecutionState == ApplicationExecutionState.Terminated)
                {
                    //TODO: Load state from previously suspended application
                }

                // Place the frame in the current Window
                Window.Current.Content = rootFrame;
            }

            if (e.PrelaunchActivated == false)
            {
                if (rootFrame.Content == null)
                {
                    // When the navigation stack isn't restored navigate to the first page,
                    // configuring the new page by passing required information as a navigation
                    // parameter
                    rootFrame.Navigate(typeof(MainPage), e.Arguments);
                }
                // Ensure the current window is active
                Window.Current.Activate();
            }
        }

        /// <summary>
        /// Invoked when Navigation to a certain page fails
        /// </summary>
        /// <param name="sender">The Frame which failed navigation</param>
        /// <param name="e">Details about the navigation failure</param>
        void OnNavigationFailed(object sender, NavigationFailedEventArgs e)
        {
            throw new Exception("Failed to load Page " + e.SourcePageType.FullName);
        }

        /// <summary>
        /// Invoked when application execution is being suspended.  Application state is saved
        /// without knowing whether the application will be terminated or resumed with the contents
        /// of memory still intact.
        /// </summary>
        /// <param name="sender">The source of the suspend request.</param>
        /// <param name="e">Details about the suspend request.</param>
        private void OnSuspending(object sender, SuspendingEventArgs e)
        {
            var deferral = e.SuspendingOperation.GetDeferral();
            //TODO: Save application state and stop any background activity
            deferral.Complete();
        }
    }
}
`

**Comment by jtanner-msft** [comment]
Hi @dick,

  There is a UWP C# sample that you can use for testing.  It's located here:
https://github.com/Azure/azure-iot-sdks/tree/master/csharp/device/samples/UWPSample 

  The other thing I'll mention is that I've occasionally copied a different connection string than I expected from Device Explorer.  Please make certain that the device name you want for the string is selected before right clicking to get the connection string.  Similarly, please double check the device name you are monitoring as well.  Most often if things seem to be working without any errors, but I'm not seeing anything it means I've selected the wrong device to monitor (which could also be true if the connection string isn't 100% correct).

**Comment by dick** [comment]
Hi @jtanner-msft, 

I've been doing a lot more testing today. I was able to connect several times successfully using MQTT and my Node.js scripts that I originally posted, but I am getting intermittent "not authorized errors." I don't think that my device connection string is incorrect because it is working some of the time. I also tried using a Shared Access Signature generated by Device Explorer with a long TTL, but that did not work. 

Does the IoT Hub ever refuse connections from a device because it still thinks that it is connected or some other reason? Are there any sort of timing issues that can be created with the authorization signatures?

**Comment by jtanner-msft** [comment]
Hi @dick,

  I generally create a unique device name for each protocol I'm testing.  So Rpi2MQTT, Rpi2AMQP, etc. for example.  That way only that specific device / protocol should be getting used with a specific sample.  Some of the protocols have longer session timeouts, so it is possible you could confuse the hub if you have two different samples using the same connection string in too short of a time period.

**Comment by dick** [comment]
Hi @jtanner-msft,

After further testing, it seems that I am triggering some sort of IoT Hub-wide lockout for my device (possibly based on IP address??). I added registry code to generate a unique Device Id each time I run the code and immediately got an "Unauthorized" error just trying to call registry.create(). I spun up a new IoT Hub and the same code worked fine -- it generated a unique time-stamped deviceId and started transmitting to the Hub via MQTT with no problems. 

Any other ideas about what I could be doing to anger IoT Hub? I am nowhere close to the published rate limits. I worry that IoT Hub is suspicious of my 4G modem, which may be changing settings each time it restarts, but it's impossible to do comprehensive testing without frequently restarting the device.

**Comment by rajeevmv** [comment]
Have you considered using [operational monitoring](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-operations-monitoring/) to figure out what is going on?

**Comment by dick** [comment]
@rajeevmv I have, but unfortunately operational monitoring is not any more helpful in terms of an error message. Once IoT Hub has decided it doesn't like my device, operational monitoring streams 401 "Unauthorized" events even in verbose mode. My example output is below:

I20160927-20:25:37.804(-5)? Event received: 
I20160927-20:25:37.806(-5)? { time: '2016-09-28T01:25:31.9980577Z',
I20160927-20:25:37.806(-5)?   operationName: 'create',
I20160927-20:25:37.806(-5)?   category: 'DeviceIdentityOperations',
I20160927-20:25:37.807(-5)?   level: 'Error',
I20160927-20:25:37.807(-5)?   statusCode: 401,
I20160927-20:25:37.807(-5)?   statusDescription: 'Unauthorized',
I20160927-20:25:37.808(-5)?   deviceId: 'petropi-1475014820675' }
I20160927-20:25:38.213(-5)? Event received: 
I20160927-20:25:38.215(-5)? { time: '2016-09-28T01:25:32.584616Z',
I20160927-20:25:38.216(-5)?   operationName: 'get',
I20160927-20:25:38.216(-5)?   category: 'DeviceIdentityOperations',
I20160927-20:25:38.216(-5)?   level: 'Error',
I20160927-20:25:38.217(-5)?   statusCode: 401,
I20160927-20:25:38.218(-5)?   statusDescription: 'Unauthorized',
I20160927-20:25:38.218(-5)?   deviceId: 'petropi-1475014820675' }

**Comment by rajeevmv** [comment]
Do you see anything under the "Connections" category?

**Comment by dick** [comment]
I don't, but my code is now set up to register a device name first, then try to initiate a connection. It's failing at the registration step and never trying to connect now. If I recall correctly, I followed the ops monitoring log for the same issue last week and received an HTTP 500 "Internal Server Error" on a failed connection, and there was no helpful additional info. I'll see if I can induce that again.

**Comment by rajeevmv** [comment]
Can you give us the name of your hub?

**Comment by jtanner-msft** [comment]
@dick,
  One other thought was that depending upon how your 4G modem operates, maybe it's switching you from using IPv4 to IPv6 addresses?
  Can you capture a small netmon or wireshark capture of your devices when they are trying to connect and getting rejected to see if IPv4 or 6 is being used?

**Comment by jtanner-msft** [comment]
Hi @dick,
  As it's been a week now and I haven't seen any update from you I'll close the issue at this time.  If you still do need assistance please capture the traces we suggested and re-open this issue.
