### ISSUE TITLE
nodejs - correlationId not set

### ISSUE THREAD

**Issue by KunalSaini** [Azure/azure-iot-sdks#845]
Hi,
I am not receiving any correlationId or messageId on feedback message in my cloud to device scenario.
following is the message cloud app is sending to Azure IOT. ( App is setting the message Id as well as correlationId.
```Javascript
{
  data: 
   {
     path: '/a/thermostat',
     setpoint: '65' 
   },
  properties: { propertyList: [] },
  messageId: 1475012324560,
  to: '',
  expiryTimeUtc: null,
  lockToken: '',
  correlationId: 1475012324560,
  userId: '',
  ack: 'full'
 }
```
following is the message recieved on cloud app on feedback event handler (device has completed the action successfully)
```javascript
{
properties: { propertyList: [] },
messageId: '',
to: '',
expiryTimeUtc: null,
lockToken: '',
correlationId: '',
userId: '',
transportObj: { 
  messageAnnotations: { 'iothub-enqueuedtime': 2016-09-27T21:38:47.940Z },
  properties: {
   messageId: null,
   userId: <Buffer >,
   to: null,
   subject: null,
   replyTo: null,
   correlationId: null,
   contentType: 'application/vnd.microsoft.iothub.feedback.json',
   contentEncoding: null,
   absoluteExpiryTime: null,
   creationTime: null,
   groupId: null,
   groupSequence: null,
   replyToGroupId: null,
   },
 }
}
```

I am using the following version of packages
├── azure-event-hubs@0.0.3
├── azure-iot-common@1.0.15
├── azure-iot-device@1.0.15
├── azure-iot-device-amqp@1.0.15
├── azure-iothub@1.0.17

**Comment by pierreca** [comment]
Hi @KunalSaini 
can you  paste how you create the message on the device side? We've had issues with the way we package the message before we send it in some cases, I wonder if it might be related. 
What happens is that the SDK is trying to be too smart, and if the object passed to send() is not an instance of `Message`, it bundles it into a `Message`. so you end up with your own object the payload of a `Message`. and the messageId ends up in the payload instead of the properties.

One way to tell would be to try this: create the message first:
```js
var msg = new Message();
```
then set the properties of `msg` (`messageId`, etc) and send it.
Please do let us know if that helps!

**Comment by KunalSaini** [comment]
following is the relevant piece of code on device
```Javascript
cloudclient.on('message', messageFromCloud);
.......
.......
function messageFromCloud(msg) {
  console.log(`msg from cloud for : ${util.inspect(msg.data)}`);
  .....
   if(somecondition) { 
    cloudclient.complete(msg, printResultFor('completed')))
   } else {
    cloudclient.reject(msg, printResultFor('rejectMsg'));
  }
}
```
following is how I am creating message on cloud side and listening for feedback
```Javascript
function receiveFeedback(err, receiver) {
  receiver.on('message', (msg) => {
    console.log('Feedback message:');
    console.log(util.inspect(msg));
  });
}


serviceClient.open((err) => {
  if (err) {
    console.error(`Could not connect: ${err.message}`);
  } else {
    console.log('Service client connected');
    serviceClient.getFeedbackReceiver(receiveFeedback);
    .........
    .........
    .........
    const message = new Message(messageBody);
    message.ack = 'full';
    message.messageId = new Date().getTime();
    message.correlationId = new Date().getTime();
    console.log(`Sending message: ${util.inspect(message)}`);
    serviceClient.send(targetDevice, message, printResultFor('send'));
  }
```

I also tried 
```Javascript
    const message = new Message();
    message.data = messageBody;
    message.ack = 'full';
    message.messageId = new Date().getTime();
    message.correlationId = new Date().getTime();
```
however still no message id or correlation id on feedback

**Comment by pierreca** [comment]
Hi @KunalSaini 

The message object returned by the feedback receiver is a little bit confusing. What you're looking for (the `originalMessageId` field) is actually directly in the body of the message. You can access it like so:

```js
    client.getFeedbackReceiver(function(err, recv) {
      recv.on('message', function(msg) {
        var feedback = JSON.parse(msg.getData())[0];
        console.log('id: ' + feedback.originalMessageId + ': ' + feedback.description);
      });
    });
```

**Comment by KunalSaini** [comment]
@pierreca thanks, I can get the originalMessageId now, however just wanted to clarify , is the ```correlationId``` also supported in API or just ```originalMessageId```

**Comment by pierreca** [comment]
In the case of message feedback, it's `originalMessageId`, not `correlationId`. Message Feedback is discussed here: 
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-messaging/#cloud-to-device-messages 

Closing the issue, since it seems solved on your end. feel free to reopen if not!
