### ISSUE TITLE
[Java] Does SDK reconnect when disconnected ?

### ISSUE THREAD

**Issue by tkysmz** [Azure/azure-iot-sdks#847]
Hi.

I have a question about Java IoT SDK.
Does it "reconnection" in SDK, when disconnected from IoTHub ?

i.e. Should we implement reconnection application code ?

Thanks.

**Comment by tameraw** [comment]
@tkysmz - Yes. The Java SDK has existing logic to reconnect to the IoTHub.

**Comment by tkysmz** [comment]
@tameraw Thank you for Answer quickly. 
Could you tell the place of reconnection logic on code? I want to know details. 

Thanks.

**Comment by BlueBasher** [comment]
@tkysmz I believe it depends on what protocol you are using. But if you're using AMQP you can find it here: https://github.com/Azure/azure-iot-sdks/blob/master/java/device/iothub-java-client/src/main/java/com/microsoft/azure/iothub/transport/amqps/AmqpsIotHubConnection.java#L600

**Comment by tameraw** [comment]
@BlueBasher - Thanks for providing the info.
@tkysmz - Please let us know if you still have any other questions or issues.
