### ISSUE TITLE
nodejs connection resiliency

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdks#848]
I am writing a device code using **Node v1.0.15**, which needs to be connected all the time and if disconnected, needs to be reconnected.

Here are some of the questions regarding this issue:
- [readme](https://github.com/Azure/azure-iot-sdks/tree/master/node/device/transport/amqp) doc is using `clientFromConnectionString` whereas in this [devdoc](https://github.com/Azure/azure-iot-sdks/blob/master/node/device/transport/amqp/devdoc/device_amqp_requirements.md) is using `Amqp(config)`.  Which is the preferred/latest way of using the library?
- Do you have any recommendations for how to handle disconnect events and what needs to be done on disconnect? I reviewed the code and see that it does try to reconnect itself, is that correct? If it does try to reconnect itself, is there any other events I should be handling?
- I followed the [devdoc](https://github.com/Azure/azure-iot-sdks/blob/master/node/device/transport/amqp/devdoc/device_amqp_requirements.md) and it does not work. I get an error _AMQP Transport: Could not connect_

Thanks

**Comment by pierreca** [comment]
The documents in `devdoc` are requirements documents that describe the internal APIs, it's useful for us and our CI builds, not as much for tutorials. 

The preferred way of using the `Client` object is described in the following file:
https://github.com/Azure/azure-iot-sdks/blob/master/node/device/samples/simple_sample_device.js

**Comment by bmrpatel** [comment]
Thanks for pointing to the sample. I modified the app to use `Client`

However, I get the following error, while program is running perfectly fine. Here is the sequence, `disconnect` event is called then I try to reconnect by using the following code.

```
            this.client.close(() => {
                logger.debug(`client connection closed [${reason}]`);
                this.connect(config, reason); //other function in my class that makes connection
            });
```
Above code tries to reconnect and gets the error 
`AMQP Transport: Could not connect`
