### ISSUE TITLE
universal windows app unhandled exception of type 'System.ExecutionEngineException'

### ISSUE THREAD

**Issue by levalencia** [Azure/azure-iot-sdks#849]
I have the following code which reads a temperature from a sensor on a raspberry pi.

The code is asynchronous, and if I remove ONLY the last line of the code, the one that sends the message, I never get the exception. I meant this line:

    await deviceClient.SendEventAsync(message);
    
    
    
    
     private async void InitializeSensors()
            {
                string calibrationData;
                //_periodicTimer.Dispose();
                // Inicializar el sensor bmp180
                try
                {
                    _bmp180 = new Bmp180Sensor();
                    await _bmp180.InitializeAsync();
                    calibrationData = _bmp180.CalibrationData.ToString();   //Retorna una cadena que representa al objeto actual.
                    if (_periodicTimer == null)
                    {
                        _periodicTimer = new Timer(this.TimerCallback, null, 0, readingInterval);
                    }
                }
                catch (Exception ex)
                {
                    calibrationData = "Error de dispositivo! " + ex.Message;
                }
    
                var task = this.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
                {
                    //calibrationDataTextBlock.Text = "";
                });
            }
    
            public async void TimerCallback(object state)
            {
                string temperatureText;
                // Leer  datos del sensor
                try
                {
                    var sensorData = await _bmp180.GetSensorDataAsync(Bmp180AccuracyMode.UltraHighResolution);
                    temperatureText = sensorData.Temperature.ToString("");
                    //pressureText = sensorData.Pressure.ToString("F2");
                    temperatureText += "°C";
                    //pressureText += "hPa - " + BitConverter.ToString(sensorData.UncompestatedPressure);
                    var temperatureDataPoint = new
                    {
                        deviceKey = deviceKey,
                        deviceName = deviceName,
                        temperatura = sensorData.Temperature,
                        fecha = DateTime.Now
                    };
                    var messageString = JsonConvert.SerializeObject(temperatureDataPoint);
                    var message = new Microsoft.Azure.Devices.Client.Message(Encoding.ASCII.GetBytes(messageString));
                    message.Properties["Ambiente"] = ambiente;
    
                    ////temperatura.Text = temperatureText;
                    await deviceClient.SendEventAsync(message);
                }
                catch (Exception ex)
                {
                    temperatureText = "Sensor Error: " + ex.Message;
                    //pressureText = "Sensor Error: " + ex.Message;
                }
    
                //// actualizaciones de la interfaz de usuario... deben ser invocados en el subproceso de interfaz de usuario
                var task = this.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
                {
                    temperatura.Text = temperatureText;
                });
    
            }

Stack trace

at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__14`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.<SendEventAsync>d__11.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at ActiveSense.Tempsense.Sensor1.MainPage.<TimerCallback>d__13.MoveNext()"

**Comment by levalencia** [comment]
The thing is that this code worked for several days, and suddenlty stopped working

**Comment by anhashia** [comment]
Investigating !

**Comment by levalencia** [comment]
I appreciate the effort, we are almost in the go live phase 👍

**Comment by anhashia** [comment]
Hi @levalencia 
I just tried `csharp\device\samples\UWPSample` on **Raspberry Pi2**  Windows IoT Core **10.0.14393** and I **don't** see any issue in sending and receiving messages. 

Try this **sample** on your device and see if you see any issues with running of this sample. This sample also uses `deviceClient.SendEventAsync `to send messages to Azure IoT Hub. Check \csharp\device\samples\UWPSample\IoTClient.cs for reference.

If you are using older version of Azure IoT SDK, try to update to newer available version and test the scenario again.

**Comment by levalencia** [comment]
fixed, it was a typo on the connection string our fault!

**Comment by anhashia** [comment]
okay ! Thanks for the update.

**Comment by anhashia** [comment]
Closing this. Please re-activate if you have any further questions on this. Thanks !
