### ISSUE TITLE
Support for net45 framework

### ISSUE THREAD

**Issue by danstoian** [Azure/azure-iot-sdks#853]
Hei,

Can you please compile the Microsoft.Azure.Devices package for net45? 
Our project targets net45 (and we cannot change it).

Microsoft.Azure.Amqp requires net451 and I've submitted a pull-request to change the target framework from net451 to net45
(https://github.com/Azure/azure-amqp/issues/39)

Thanks,
Dan

**Comment by tameraw** [comment]
@danstoian - Thanks for filing this. We'll look into adding support for .net 4.5 as well.

**Comment by markrad** [comment]
Hi @danstoian,

I reviewed your pull request but you unfortunately made it against the master branch. I can't merge anything into that branch. The develop branch has undergone a significant reorganization so I was having difficulty getting a clean merge of your changes into that branch.

To try and circumvent this, I loaded the develop branch version of iothub_csharp_deviceclient.sln into Visual Studio and modified the project properties of the device project to target .Net 4.5. Unfortunately this caused catastrophic build errors when I attempted a rebuild. I'm still looking into the cause.

_Mark Radbourne MSFT_

**Comment by danstoian** [comment]
Hi @markrad,

I've created a new pull request for the azure-amqp project this time in the develop branch: https://github.com/Azure/azure-amqp/pull/43

I've created a new package for Microsoft.Azure.Amqp locally and then included the new one in iothub_csharp_deviceclient.sln. 

The solution didn't build correctly the first time because there is a new method _void SetMonitor(ITransportMonitor usageMeter)_ in  Microsoft.Azure.Amqp.Transport that need to be implemented in ClientWebSocketTransport and LegacyClientWebSocketTransport otherwise the solution won't compile.

Since I'm not quite sure what it does I've created an override in both classes that will throw a NotImplementedException.

The bottom line is that the solution compiles locally. I can make a pull-request for _Azure-iot-sdks_ if you wish. You can check my commit at: https://github.com/Azure/azure-iot-sdks/compare/develop...danstoian:develop?expand=1

**Comment by tameraw** [comment]
@danstoian - This is currently WIP. Will update the issue as soon as we have news.

**Comment by markrad** [comment]
Hi @danstoian,

Currently I am pestering the product group to publish your changes to Microsoft.Azure.Amqp. The Nuget package is still targeting .Net 4.5.1. Once they have updated that I will go ahead and make the rest of the changes to target this to .Net 4.5.

_Mark Radbourne MSFT_

**Comment by danstoian** [comment]
Hi @markrad,

Thx for the update. 
I'm looking forward to it.

Br,
Dan

**Comment by tameraw** [comment]
@markrad - A new Nuget package has been released for Microsoft.Azure.Amqp.

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-csharp#29
