### ISSUE TITLE
[C][DM] IOTdm_edison_sample connection failure (always since some days)

### ISSUE THREAD

**Issue by mgiuncato** [Azure/azure-iot-sdks#854]
on branch DMPREVIEW.
since some hours(?) / days (?) the client sample iotdm_edison_sample connection to iothub fails with following message : 

> Oct 03 09:26:04 edison iotdm_edison_sample[641]: Error: Time:Mon Oct  3 09:26:04                                                                         2016 File:/home/mgiuncato/edison_new_img_v3.0-2/iot-devkit-yp-poky-edison-20160                                                                        315/build_edison/tmp/work/core2-32-poky-linux/iotdm-edison-sample/1.0-r0/home/mg                                                                        iuncato/azure-sdk-dmpreview/azure-iot-sdks/c/azure-c-shared-utility/adapters/soc                                                                        ketio_berkeley.c Func:socketio_open Line:321 Failure: select failure.

I notice that the connection on netstat remain in "SYNC" for 3 minutes and after disappear.
the program /service remain loaded and does not close.

any news ? does the preview ends ?

any suggestion is appreciate.

Marco

**Comment by olivierbloch** [comment]
Hi @mgiuncato 
We just released a new preview for device management and changes are consequent enough that we moved the SDKs code to their own [preview repo](https://github.com/Azure/azure-iot-sdks-preview)

You can find documentation on the new public preview here:
[Understand Device Twins](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-device-twins/)
[How to use the device twin](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-node-node-twin-getstarted/)
[How to use twin properties](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-device-twins/)
[Invoke a direct method on a device](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-direct-methods/)
[Get started with Device Management](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-device-management-get-started/)
[Schedule jobs on multiple devices](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-jobs/)

**Comment by tameraw** [comment]
@mgiuncato - Please let us know if you still have any further questions.
