### ISSUE TITLE
ITransportSettings.DefaultReceiveTimeout not present in documentation

### ISSUE THREAD

**Issue by murdockcrc** [Azure/azure-iot-sdks#855]
Hi,

I see that the interface `ITransportSettings` defines the property `DefaultReceiveTimeout `: 

```
public interface ITransportSettings
    {
        TransportType GetTransportType();

        TimeSpan DefaultReceiveTimeout { get; }
    }
```

However, in the [MSDN documentation](https://msdn.microsoft.com/en-us/library/microsoft.azure.devices.client.itransportsettings.aspx), this property does not exist in the interface's definition.

Just wanted to file this inconsistency and check if I got the versioning wrong in the documentation, or if you can provide a pointer where this property is documented.

Thanks.

**Comment by mtuchkov** [comment]
@murdockcrc Thank you for reporting this inconsistency. We will update the MSDN spec as soon as possible.

**Comment by dominicbetts** [comment]
@tameraw - the MSDN content is now updated.

**Comment by tameraw** [comment]
@dominicbetts - Thanks!
@murdockcrc - Closing this. Please let us know if you have any issues or questions.
