### ISSUE TITLE
azure-iot-sdks\node\build\dev-setup.cmd gives openssl_conf environment variable must be defined error

### ISSUE THREAD

**Issue by prbarl** [Azure/azure-iot-sdks#858]
Hi,

As part of dev setup for running nodejs sample I am getting the above mentioned error . ANy idea?

Regards,
Praveen

**Comment by pierreca** [comment]
You need to set the OPENSSL_CONF environment variable (to anything really, it doesn't matter unless you run the build scripts, which you shouldn't need to do).

Context: Our build runs integration and end-to-end tests that require creating a device that authenticate using x509 certificates. We rely on OpenSSL to generate that certificate. The test for this variable belongs in the build.cmd script but instead was added to the dev-setup.cmd script. I'll move it away.

**Comment by pierreca** [comment]
This was fixed in 911fd1851aab58fbf7e9ec9b8cf99535b44a58c3
