### ISSUE TITLE
Public class for .net45 and internal for uap10 ?

### ISSUE THREAD

**Issue by NicolasHumann** [Azure/azure-iot-sdks#86]
Hi,

Why many classes like DeviceAuthenticationWithRegistrySymmetricKey / IOTHubException are public for .net451 and internal for uap10 ?
I try to use the simulator sample from remote monitoring to develop my rpi2 gateway but so may classes are inaccessible...

Why ?

Thansk

**Comment by dcristoloveanu** [comment]
We are investigating it.

**Comment by pierreca** [comment]
DeviceAuthentication* classes have been made public in develop, master and packages will be updated as a part of our regular release cycle. WinRT prevent components from defining custom exceptions though, so exceptions will stay internal until we figure out the right pattern. Feel free to reopen the issue if you have suggestions :)
