### ISSUE TITLE
SDK fails if no Internet connection is available at startup

### ISSUE THREAD

**Issue by IngoMaindorfer** [Azure/azure-iot-sdks#860]
Hi there,
we use SDK from 2016-09-09 on Linux with MQTT as transport and observed, that the SDK have some issues with Internet availability on start up. 
If there is no Internet, SDK try to connect, which is ok. 
If Internet come up, SDK still try to connect even after 15 minutes after Internet connection is stable.

It seems that there are two different behaviours: one is like you have no Internet et all, the other is you have a valid connection and can resolve the Azure IoT-Hub DNS name but your companies firewall blocks port 8883.

My current work around for that connection on startup issue is:
-init SDK 
-send dummy packet
-check cyclic for a given time that packet has been sent (like a timeout but I'm use the _LL_ functions here)
-If packet has been sent successful, al right, do the normal work
-If packet didn't made it in a given time,  de-init SDK and jump to first step

Best,
Ingo

**Comment by sergaz-msft** [comment]
Hi @IngoMaindorfer thanks for sharing this issue. I will start working on it. For a better understanding can you share more details?
- What is the sample you are using to repro this? This one? https://github.com/Azure/azure-iot-sdks/tree/master/c/iothub_client/samples/iothub_client_sample_mqtt
- Did you changed the samplec? If so please share it with me by email.

My email is sergaz@microsoft.com . If you can also have some time to share your screen and show me how you repro this would help me understand it better.

Thanks!

**Comment by prmathur-microsoft** [comment]
We discovered a bug for the scenario you were talking about. Fix is coming in soon.

**Comment by prmathur-microsoft** [comment]
The fix for this is pushed in. Please let us know if you see any other issues.
