### ISSUE TITLE
Iothub Sending and Receiving Messages C2D and D2C 

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#861]
Hi i have two applications running From Application 1 i will send data and that has to be received by Application 2 and  in turn   it will return some message back to Application 1  which is different message .Can u send  any readily Available documentation(links) for this scenario as it is IotHub Bi Directional in nature.This is very urgent requirement

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
It is not clear what runs where in your scenario (device vs. cloud).
Overall, a good starting point to learn more about Azure IoT Hub and what can be done with it is here: https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide/

And here you can find the info about sending and receiving messages:
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-messaging/

**Comment by tameraw** [comment]
@mupparajuvamsi - Please let us know if you have any further questions or issues. Regards.
