### ISSUE TITLE
nodejs x509 sample amqp:unauthorized-access

### ISSUE THREAD

**Issue by ChristianBeier** [Azure/azure-iot-sdks#866]
One month ago I successfully used x509 authentication with a NodeJS and MQTT sample as well as MQTT command line client but since last week I get with AMQP
_amqp:unauthorized-access_
and any connection attempt with MQTT fails.
I am using the same self-signed certificate what worked beginning of September.
Seems similar to the C# SDK issues mentioned in https://github.com/Azure/azure-iot-sdks/issues/815

Any changes in the x.509 behavior of IoT Hub?

**Comment by pierreca** [comment]
Hi @ChristianBeier 
There have been no breaking changes. 

Could it be that the certificate expired? 
Also, can you check in your device registry that the thumbprint for this certificate is still there?

**Comment by ChristianBeier** [comment]
I created new certificate & key pair and was able to connect and authenticate. Don't know what went wrong with my other setup. Maybe wrong key thumbprint combination.

**Comment by FabianKLS** [comment]
Hi @ChristianBeier,

Is your source code for the node.js and x.509 available on girhub? I'm looking for a node.js IoT solution with x.509.

**Comment by ChristianBeier** [comment]
You can use the sample code for node provided in github.

Best regards
Christian

**Comment by FabianKLS** [comment]
thanks. I missed that sample in my initial search. It's working!
