### ISSUE TITLE
[Java Device Client] Number of active threads is constantly increasing in the case of the reconnect

### ISSUE THREAD

**Issue by merjadok** [Azure/azure-iot-sdks#872]
Hello,

we have identified one potential problem with the reconnect functionality: it creates a large number of active threads (fast, it even looks like it is exponential growth) which try to connect to Azure IoT hub. This is output from the JConsole (after just few minutes):

![threads](https://cloud.githubusercontent.com/assets/58171/19380225/8ef36142-91f6-11e6-8a91-714b9d8d168a.png)

This was noticed because of the strange output we got in the console:

> Lost connection to the server. Reconnection attempt 1...
> Lost connection to the server. Reconnection attempt 1...
> Lost connection to the server. Reconnection attempt 1...
> Lost connection to the server. Reconnection attempt 1...
> Lost connection to the server. Reconnection attempt 1...
> Lost connection to the server. Reconnection attempt 1...
> Lost connection to the server. Reconnection attempt 1...
> Lost connection to the server. Reconnection attempt 1...
> Lost connection to the server. Reconnection attempt 1...

On the first glance, it looks like the problem is that there is a while loop in https://github.com/Azure/azure-iot-sdks/blob/master/java/device/iothub-java-client/src/main/java/com/microsoft/azure/iothub/transport/amqps/AmqpsIotHubConnection.java#L610, while at the same time this.open() creates a new thread each time it is called and enters the reconnect() afterwards (I didn't dig into the details, just took a short look).

How to reproduce?
Run https://github.com/Azure/azure-iot-sdks/blob/master/java/device/samples/send-event/src/main/java/samples/com/microsoft/azure/iothub/SendEvent.java with the connection string for **valid IoT hub instance** but with a **DeviceId value which is not registered at the hub**.

**Comment by zolvarga** [comment]
Hello merjadok,

Thanks for using IoTHub and reporting this issue.
The issue is known and we are currently working on a fix.
We will update this thread if the fix is released.

Best Regards,
Zoltan

**Comment by merjadok** [comment]
Thank you!

**Comment by tameraw** [comment]
This has now been fixed and available in the master branch. Let us know if still having issue.

**Comment by merjadok** [comment]
Can confirm that this was fixed, thanks a lot!
