### ISSUE TITLE
IotHub Reading messages sent by the device

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#873]
Hi Can you exactly say what it will do PartitionReceiver  receiver.setReceiveHandler(new PartitionReceiveHandler(100)   what does that number indicate because when we are receving messages it is iterating those many times .If only one message is sent is it necessary to run those many times.and how the callback functions  is executed each time when we receive message or it will execute after all messages are send .

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
It seems you are looking into "reading" data from IoT Hub. The way this is done is by getting the data from the Event Hub compatible endpoint using an Event Hub client. There are several solutions for doing so. In y our case it seems you are using the EventHubReceiver class. I invite you to go through the documentation and samples for this [here](https://msdn.microsoft.com/en-us/library/azure/microsoft.servicebus.messaging.eventhubreceiver.aspx).
There is also [this great thread on StackOverflow](http://stackoverflow.com/questions/27789320/azure-event-hubs-and-multiple-consumer-groups) that goes through the solutions to deal with reading from Event Hub

Hope this helps.

**Comment by mupparajuvamsi** [comment]
Hi @olivierbloch  
The issue is solved

**Comment by olivierbloch** [comment]
Thx
