### ISSUE TITLE
process-d2c-messages  process-interactive-messages Reading IotHub messages from devicetocloud 

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#875]
Hi i followed the same documentation (https://github.com/Azure/azure-content/blob/master/articles/iot-hub/iot-hub-java-java-process-d2c.md )and i am able to send but while receiving i am getting this exception Failure while registering: com.microsoft.azure.eventprocessorhost.EPHConfigurati
onException: Encountered error while fetching the list of EventHub PartitionIds:
 Server returned HTTP response code: 401 for URL: https://ihsuprodhkres002dednam
espace.servicebus.windows.net/iothub-ehub-demoiothub-71552-2480f0e0fe/consumergr
oups/$Default/partitions
java.util.concurrent.ExecutionException: com.microsoft.azure.eventprocessorhost.
EPHConfigurationException: Encountered error while fetching the list of EventHub
 PartitionIds: Server returned HTTP response code: 401 for URL: https://ihsuprod
hkres002dednamespace.servicebus.windows.net/iothub-ehub-demoiothub-71552-2480f0e
0fe/consumergroups/$Default/partitions

Can u please give a quick reply i am struck with these from three weeks .I have to sort out this quickly

If you want screenshots i can provide

**Comment by olivierbloch** [comment]
Hello @mupparajuvamsi 
Please do NOT put secrets such as SAS keys in discussion threads like this one.
The 401 response is an authentication error. Can you validate the credentials you are using trying to get the messages using the Device Explorer tool or the node iothub-explorer one (you can learn how to use these tools [here](https://github.com/Azure/azure-iot-sdks/blob/master/doc/manage_iot_hub.md)?

**Comment by mupparajuvamsi** [comment]
Hi @olivierbloch  
Thanks for the reply . I am able to send and receive messages through EventHubClient .I will check the credentials once again for sending through EventProcessorHost.
Is there any possibility of sending million-events(heartbeat message) from multiple devices to-azure-Iothub-every-5-seconds(or any time period)  .Here documentation says the concept is there (https://azure.microsoft.com/en-in/documentation/articles/iot-hub-devguide-identity-registry/#device-provisioning) Device heartbeat .But how to implement it in java can u send code(links) if available

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
I responded to this one here: https://github.com/Azure/azure-iot-sdks/issues/880
Closing this one
