### ISSUE TITLE
IotHub Consumer Group 

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#876]
Hi How may consumer groups can i create for IotHub and how much should be the size of message and if it exceeds the size  shall we loose the messages .

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
The size of the message is independent of the consumer groups notion. Message sizes limitations are described in our [throttle and quotas document](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-quotas-throttling/).
IoTHub puts device messages into the Event Hub partitions (partitioning is done based on device ID, meaning all messages from a specific device will all go in the same partition). You can create up to 32 partitions to optimize throughput when reading messages from the event hub endpoint, parallelizing and having as many readers as you have partitions. If you want more than one reader per partition, you will need to create new consumer groups as event hubs manages offsets on a per consumer group basis for each partition. Please read [Event Hubs documentation](https://azure.microsoft.com/en-us/documentation/articles/event-hubs-programming-guide/#event-consumers) for more details.

**Comment by tameraw** [comment]
Closing. Please let us know if you still have any questions.
