### ISSUE TITLE
IotHub Reading messages sent by the device

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#877]
How Consumer Groups works in IotHub DeviceToCloud messages Receiving .Is it related to multiple devices sending data at a time ?

Please provide Documentation links how to create and use them in Receiving messages and is there any relationship between Partiiton count and Consumer Group

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
Please check out our documentation on Device to Cloud messages [here](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-messaging/#device-to-cloud-messages), it explains how messages are partitioned and how to consume events from the Event Hub endpoint.

**Comment by tameraw** [comment]
Closing. Please let us know if you still have any questions or face any issues. Regards.
