### ISSUE TITLE
don't receive the message properties on feedback function back from the original c2d message.

### ISSUE THREAD

**Issue by guybartal** [Azure/azure-iot-sdks#879]
I don't receive the message properties back from the original message.

https://github.com/smart-home-bot/bot/blob/master/app.js line number 68:

```
            var data = JSON.stringify({Name: 'TurnOnLightsInRoom', Parameters: { Room: 'all', TurnOn: true } });
            var message = new iotMessage(data);
            message.properties.add("Address", JSON.stringify(session.message.address));
            message.ack = 'full';
            message.messageId = 'TurnOnLightsInRoom';
            console.log('Sending message: ' + message.getData());
            iotClient.send(iotTargetDevice, message, printResultFor('send'));

```

I want to store information in the c2d which I need to have it back in the feedback message. what is the proper way to code it?

here's my feedback function:

```
function receiveFeedback(err, receiver) {
    receiver.on('message', function (msg) {
        console.log('Feedback message:');
        var feedbackData = msg.getData();
        var msgObj = JSON.parse(feedbackData.toString('utf-8'))[0];
        console.log(feedbackData.toString('utf-8'));
        var msg = new botBuilder.Message()
            .address(msgObj.Address)
            .text(msgObj.Name);
        bot.send(msg);
    });

    receiver.on('error', function (msg) {
        console.log('Feedback error:' + msg);
    });
```

**Comment by pierreca** [comment]
hi @guybartal 
the feedback message is not supposed to contain the properties of the original message, just the `originalMessageId` if you set a `messageId` on the message you sent (therefore I would advise to make it unique per message).

You could either reply to your c2d message with a d2c message that contains the same properties (although you'd have to open all messages to find which one is the one you're looking for), or use a feature currently in preview called device methods:
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-direct-methods/

HTH
Pierre
