### ISSUE TITLE
Freescale FRDM-K64F Setup - Doc change suggestion

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#88]
I feel this part is slightly misleading:

_Connect to the device using an **SSH client application**, such as PuTTY. You can determine which serial port your device uses by checking the Windows Device Manager:_

While I am perfectly aware that PuTTY can be used as a serial terminal that is not necessarily true for all SSH client applications. In my opinion this should call out for a serial terminal application.

**Comment by dominicbetts** [comment]
Hi @markrad. I've submited a PR to address this in this doc and in a couple of others to make them all consistent. Thanks!

**Comment by tameraw** [comment]
Issue resolved. Please advise/reopen if you're still having issues. Thanks.
