### ISSUE TITLE
IotHub Device HeartBeat 

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#880]
Hi 
From below documentation(https://azure.microsoft.com/en-in/documentation/articles/iot-hub-devguide-identity-registry/#device-provisioning) i found there is a concept of Device heartbeat. But how can i Send million events/heartbeat messages (from multiple devices ) to Azure IotHub every 5 seconds(or some particular time duration)
using this concept in Java
 And how to authenticate device  before sending messages to IotHub ?
Q.How many maximum no of devices can i create for my Requirement 

1. 100 customers each with 100 (devices)
  2. 1000 customers each with 50,000 (devices)
On following scenarios,
 - normal load (50% devices send data concurrently to IotHub) 
 - peak load (90% devices sends data concurrently to IotHub)

I am building Java Application for all these requirements anything related to this Documentation you can send the links

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
The heartbeat is taken care of by our SDKs for AMQP and MQTT protocols and these heartbeat messages are not counted for billing, so these don't impact the throttle and quotas.
in addition, you can find details about throttle and quotas [here](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-quotas-throttling/).

**Comment by mupparajuvamsi** [comment]
Hi @olivierbloch
Thanks for the reply Can you send me the documentation code(exact link) for sending heartbeat messages How can i achieve through Java/ or any other language for me to confirm .better if you send java code link

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
As mentioned previously, heartbeat (aka Keep Alive) messages are taken care of by the SDKs, you don't need to send them.
If you want to implement your own "Heartbeat" mechanism on top of that, then you just need to send messages as shown in all our samples.
Regarding "differentiating" messages for different devices, this is indeed supported out of the box. Please see our samples for reading D2C messages from IoT Hub. I pointed you to these docs in other thread.
Also, please go to StackOverflow for this kind of conversation.
Thank you

**Comment by mupparajuvamsi** [comment]
Hi @olivierbloch 
heartbeat (aka Keep Alive) messages can be supported along with http/https other than amqp//mqtt .
How can i send heartbeat message using http or https if i am inside a corporate network when i can have access for  port 443 .which doesnt support any other ports

**Comment by olivierbloch** [comment]
Messaging can happen over Websockets using AMQP or MQTT
