### ISSUE TITLE
[PCL Device Client] Support MQTT protocol

### ISSUE THREAD

**Issue by stephannielsen** [Azure/azure-iot-sdks#881]
Hi,

is MQTT support planned for the PCL version of the client SDK? If yes, when? If no, why? Technical issues?

**Comment by olivierbloch** [comment]
Hi @stephannielsen , @kierepka 
We are making progress regarding this one. Work is in progress to make the DotNetty library (that's the one we are using for MQTT support) support UWP and PCL, which means we will be able to pick this one up and hopefully publish a Nuget package for the SDK that will support PCL and UWP. Stay tuned.
PS: if you are curious to track the work in progress on DotNetty, it's happening here: https://github.com/nayato/DotNetty/tree/coreclr

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-csharp#30
