### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by ondrejtomcik** [Azure/azure-iot-sdks#887]
Hello,
we're using .net core and I am missing support for Microsoft.Azure.Devices . When it will be added please?
Service fabric already supports .net core but this main IoT SDK, which should be first in my opinion, is still missing.

Thanks

**Comment by olivierbloch** [comment]
Hi @ondrejtomcik 
We do have this in our backlog but haven't prioritized over other features yet and we cannot commit to an ETA just yet either.
We understand the importance of supporting .Net Core, and if you want to give it a shot before we can get to it, we'd be more than happy to accept your contribution and can even try and point  you in the right direction to make this happen.
We'll update the thread as soon as we have a clearer idea of when the work will be done.
Thanks

**Comment by ondrejtomcik** [comment]
Okay, thanks for the info. I will try to find some time for contribution. Can we discuss more deeply what should be done to have at least the idea where to begin?

**Comment by arturl** [comment]
Hi @ondrejtomcik,

I suggest looking at the work we did to add support for UWP. Create a new project of type "Class Library (.NET Core)", start moving the source files from the Microsoft.Azure.Devices.csproj there, and see what breaks. You will discover a few APIs not supported for .NET Core, which will be a similar set to UWP -- look at how WINDOWS_UWP was used in the code.

If you succeed in pulling it off, I recommend creating a shared project to minimize duplication in multiple csproj files, as we did [here](https://github.com/Azure/azure-iot-sdks/tree/master/csharp/device/Microsoft.Azure.Devices.Client.Shared).

Good luck, and thanks so much for your help!

**Comment by ondrejtomcik** [comment]
@arturl thank you. I'll try to find a time to make it happen.

**Comment by ondrejtomcik** [comment]
Hello again @arturl @olivierbloch,
I would like to ask you if you know when https://github.com/Azure/azure-amqp will be released? Repo updated to work with .net core but released nuget is old.

Could you please help me with another library, Microsoft.Azure.ServiceBus.EventProcessorHost ? ServiceFabric is already able to use with .net core but this key library is still not. Do you have any info regarding this please?

thanks a lot

**Comment by olivierbloch** [comment]
Hi @ondrejtomcik 
I'll work on getting the Nuget Package updated for the azure-amqp library.
For the EventProcessorHost one, it's a different team owning it, I'll try and see what their plans are. If we could get the C2D messaging and the registry manager working already that'd be great.

**Comment by ondrejtomcik** [comment]
@olivierbloch great :)

Let me know if you have some info regarding EventProcessorHost please.
Thanks

**Comment by olivierbloch** [comment]
@ondrejtomcik 
We expect to have the preview repo merged back into the mainstream one next month.

**Comment by olivierbloch** [comment]
@ondrejtomcik 
Regarding EventProcessorHost support for .Net Core, it seems there is work in progress, but not ETA yet.
In the meantime we could consider using https://github.com/Azure/amqpnetlite

**Comment by ondrejtomcik** [comment]
@olivierbloch 
How it looks with the azure amqp nuget release ?

**Comment by tameraw** [comment]
@ondrejtomcik - ETA before end of this month.

**Comment by radu-matei** [comment]
Any updates on the .NET Core support for the IoT Hub SDK?

Is there any way I can get to help?

Thanks!

**Comment by ondrejtomcik** [comment]
Hi Radu,
I was waiting for amqp release, but in a meantime we switched to different IoT platform. IoT Hub does not meet our criteria after deep evaluation.

**Comment by Kordonme** [comment]
+1 Bummer to see that Microsoft.Azure.Devices is not .NET Core compatible. Updated ETA, or should we get our hands dirty?

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-csharp#31
