### ISSUE TITLE
DeviceExplorer doesn't get the data from IoTHub.

### ISSUE THREAD

**Issue by jaeeunchoi** [Azure/azure-iot-sdks#889]
I'm not sure which version this problem is from.
But now, when I launched the DeviceExplorer and configured it properly,
I can see the device list in the 'Management' tab
And send message to device in the 'Messages To Device' tab.
But can't see no telemetry message in the 'Data' tab.

I doubt whether it's from the recent IoTHub update ( 2nd Device management preview is applied.)

Is there anyone who has the same problem or knows any clue?

**Comment by olivierbloch** [comment]
Hi @jaeeunchoi 
Can you confirm you are using the DeviceExplorer app from our preview repository (https://github.com/Azure/azure-iot-sdks/preview). If not, you can clone this repo and run it directly from Visual Studio using the solution in this folder: https://github.com/Azure/azure-iot-sdks/tree/master/tools/DeviceExplorer
Another that can happen is if you have other services (such as Stream Analytics or Functions or other reading from IoT Hub), then you might hit the readers limitation for the $Default consumer group.
You can try the following:
- Go to the IoT Hub blade in the Azure portal
- Click on Messaging to bring the Messaging blade
- Look for the Consumer Groups section and add a new consumer group (name of your choice)
- then in Device Explorer, in the Data tab, check the Consumer Group Enable Check box, then type in your new consumer group (without the "$").
- Hit Monitor and let us know if that works

**Comment by jaeeunchoi** [comment]
The readers limit for the $Default consumer group was the reason as you commented.
I assigned another consumer group and now it works fine.
Thanks.

**Comment by olivierbloch** [comment]
Thanks for the heads up.
