### ISSUE TITLE
Registering Devices( Multitenant ) 

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#894]
Hi How can i register multitenant devices through programtically and what is the maximum no of devices i can register per tenant .Can we customize the no of devices per tenant programatically?

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
The Azure IoT Hub service doesn't support multitenancy yet.
Now, if you are asking how you can programmatically register devices to Azure IoT Hub, you can find documentation [here](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-csharp-csharp-getstarted/).
Thanks
