### ISSUE TITLE
Iothub Sending messages fromDevice

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#895]
In Documentation it is mentioned that AMQPS_WS will use 443 port to send messages but when i am using this i am getting below exception Caused by: java.lang.InterruptedException: Waited too long for the connection to open.
    at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.connectionReady(AmqpsIotHubConnection.java:543)
    at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:176)
    ... 3 more
Lost connection to the server. Reconnection attempt 1...
Lost connection to the server. Reconnection attempt 1...
Lost connection to the server. Reconnection attempt 1...
Lost connection to the server. Reconnection attempt 1...

Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...
Lost connection to the server. Reconnection attempt 6...

It keeps on coming will it support 443 port or not

But with https port i am able to send messages

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
Can you check your router settings to ensure you are not blocking the port?

**Comment by olivierbloch** [comment]
Closing because thread is stale. Feel free to reopen if still valid
