### ISSUE TITLE
Tutorial azure

### ISSUE THREAD

**Issue by Geget** [Azure/azure-iot-sdks#896]
Hi, 
Im trying to run an azure tutorial => https://azure.microsoft.com/fr-fr/documentation/articles/iot-hub-device-management-get-started/
But i can not find the setup.bat and simulate.bat files in github.
Can you help and tell me the braunch where in can find these files ?

Thansk in advance

**Comment by olivierbloch** [comment]
Hello @Geget 
The device management is still in preview, and  you need to work out of our preview repository: https://GitHub.com/azure/azure-iot-sdks-preview

**Comment by olivierbloch** [comment]
Closing as older than a week
