### ISSUE TITLE
Registering Devices using RegistryManger Through C Code

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#899]
Hi 

How to register a device with Registry Manger using C code and how to send messages from device using 
HTTPS using c code Can u send me any useful links to finish the same with Java i already used both funcionalities

**Comment by olivierbloch** [comment]
You can find samples for this here: https://github.com/Azure/azure-iot-sdks/tree/master/c/iothub_service_client/samples/
