### ISSUE TITLE
Java device client connection failed with mooncake

### ISSUE THREAD

**Issue by allenhula** [Azure/azure-iot-sdks#900]
I am following this [sample](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-java-java-c2d/) to send cloud-to-device message from mooncake. But in device side, it always failed to open connection with below exception:

Oct 27, 2016 4:26:12 PM org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper process
WARNING: General SSLEngine problem
Exception in thread "main" java.io.IOException: java.io.IOException: Error opening Amqp connection: 
    at com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.open(AmqpsTransport.java:104)
    at com.microsoft.azure.iothub.DeviceClient.open(DeviceClient.java:175)
    at com.mycompany.app.App.main(App.java:29)
Caused by: java.io.IOException: Error opening Amqp connection: 
    at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:204)
    at com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.open(AmqpsTransport.java:100)
    ... 2 more
Caused by: java.lang.InterruptedException: Waited too long for the connection to open.
    at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.connectionReady(AmqpsIotHubConnection.java:581)
    at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:197)
    ... 3 more

I am using latest version SDK [1.0.14](https://mvnrepository.com/artifact/com.microsoft.azure.iothub-java-client/iothub-java-device-client/1.0.14).
It works fine for global azure.
I know mooncake is using different root certificate (Wosign), but even I added this certificate into Java key store, still failed with same error.

Please help.

**Comment by allenhula** [comment]
I have done more testing, found the issue started to happen from version 1.0.10. Not sure what changes made in that version.

Besides, when successful connection, the output is starting with below messages:
Oct 27, 2016 5:01:04 PM org.apache.qpid.proton.engine.impl.ssl.**SslEngineFacadeFactory** getClass
WARNING: unable to load org.bouncycastle.openssl.PEMReader
Oct 27, 2016 5:01:04 PM org.apache.qpid.proton.engine.impl.ssl.**SslEngineFacadeFactory** getClass
WARNING: unable to load org.bouncycastle.openssl.PasswordFinder
Oct 27, 2016 5:01:04 PM org.apache.qpid.proton.engine.impl.ssl.**SslEngineFacadeFactory** <clinit>
WARNING: unable to load bouncycastle provider

But, for current failed connection, the output is starting with different messages:
Oct 27, 2016 4:26:12 PM org.apache.qpid.proton.engine.impl.ssl.**SimpleSslTransportWrapper** process
WARNING: General SSLEngine problem

Looks like the main change was happened on SSL layer

**Comment by allenhula** [comment]
#833

**Comment by allenhula** [comment]
From code, the default certificate is Baltimore. However, mooncake is using Wosign as root certificate.
Based on the comments on issue #833, I should use **client side certificate** (2-way SSL authentication). But how to use this option?

**Comment by allenhula** [comment]
I found a workaround. Explicitly set certificate path to my Wosign certificate.
client = new DeviceClient(connString, protocol);
client.setOption("SetCertificatePath", "D:\\CIE\\Certs\\WS_CA1_NEW.cer");

But still how to use the client side certificate option?

**Comment by tameraw** [comment]
@allenhula - Thanks for filing this issue. At this moment we do not support x509 cert on the client side for the java sdk. This support is currently available in C, Node, Javascript and C#. However this in currently in our backlog and we'll update the forum once released.

**Comment by allenhula** [comment]
Thanks. Look forward to it.

**Comment by tameraw** [comment]
@allenhula - Closing this issue and tracking the feature addition under the following project:
https://github.com/Azure/azure-iot-sdk-java/projects/1
Currently this is bubbling up to the priority in our backlog and should see these features added soon.
