### ISSUE TITLE
Iothub SASToken generation using c code

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#901]
Hi 
i generated iothub sastoken using java but i didnt find any code using c language.Can u please send a readily available code which genearates sas token for iothub using c

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
The SASToken generation in C is taken care of in the azure-c-shared-utility library https://github.com/Azure/azure-c-shared-utility/blob/master/src/sastoken.c
