### ISSUE TITLE
openssl 1.1 compile issue

### ISSUE THREAD

**Issue by enjoydiy** [Azure/azure-iot-sdks#903]
[ 47%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o
/home/wzj/openwrt/sdk_x1000/src/c-utility/src/tlsio_openssl.c: In function 'create_openssl_instance':
/home/wzj/openwrt/sdk_x1000/src/c-utility/src/tlsio_openssl.c:783:2: error: 'TLSv1_method' is deprecated (declared at /home/wzj/openwrt/sdk_x1000/toolchain/mips-linux-gnu/libc/usr/include/openssl/ssl.h:1596) [-Werror=deprecated-declarations]
/home/wzj/openwrt/sdk_x1000/src/c-utility/src/tlsio_openssl.c:787:3: error: 'TLSv1_2_method' is deprecated (declared at /home/wzj/openwrt/sdk_x1000/toolchain/mips-linux-gnu/libc/usr/include/openssl/ssl.h:1608) [-Werror=deprecated-declarations]
/home/wzj/openwrt/sdk_x1000/src/c-utility/src/tlsio_openssl.c:791:3: error: 'TLSv1_1_method' is deprecated (declared at /home/wzj/openwrt/sdk_x1000/toolchain/mips-linux-gnu/libc/usr/include/openssl/ssl.h:1602) [-Werror=deprecated-declarations]
/home/wzj/openwrt/sdk_x1000/src/c-utility/src/tlsio_openssl.c: In function 'tlsio_openssl_deinit':
/home/wzj/openwrt/sdk_x1000/src/c-utility/src/tlsio_openssl.c:936:2: error: 'ERR_remove_state' is deprecated (declared at /home/wzj/openwrt/sdk_x1000/toolchain/mips-linux-gnu/libc/usr/include/openssl/err.h:247) [-Werror=deprecated-declarations]
cc1: all warnings being treated as errors
make[2]: **\* [c-utility/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o] Error 1
make[2]: **\* Waiting for unfinished jobs....

**Comment by jtanner-msft** [comment]
Hi @enjoydiy,  is it only on openwrt that you are seeing this issue?  Was it version 15.04 or an older version?  Also from the strings included it sounds like you were maybe building for a MIPS CPU.  is that correct?
  If you just install openssl outside of the Azure IoT SDK can you get it to build without problems?

**Comment by jtanner-msft** [comment]
Hi @enjoydiy ,
  Since it's been a few weeks now and I haven't seen a response to my questions I'm going to close this incident.  If you do still have a problem please feel free to re-open and just include replies to my questions when you do.
Thanks,.
