### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by enjoydiy** [Azure/azure-iot-sdks#904]
/home/wzj/openwrt/sdk_x1000/src/iothub_client/src/iothubtransport_mqtt_common.c: In function 'mqtt_operation_complete_callback':
/home/wzj/openwrt/sdk_x1000/src/iothub_client/src/iothubtransport_mqtt_common.c:526:13: error: duplicate case value
/home/wzj/openwrt/sdk_x1000/src/iothub_client/src/iothubtransport_mqtt_common.c:441:13: error: previously used here
/home/wzj/openwrt/sdk_x1000/src/iothub_client/src/iothubtransport_mqtt_common.c:528:18: error: 'MQTT_CLIENT_ON_ERROR' undeclared (first use in this function)
/home/wzj/openwrt/sdk_x1000/src/iothub_client/src/iothubtransport_mqtt_common.c:528:18: note: each undeclared identifier is reported only once for each function it appears in
/home/wzj/openwrt/sdk_x1000/src/iothub_client/src/iothubtransport_mqtt_common.c: In function 'InitializeTransportHandleData':
/home/wzj/openwrt/sdk_x1000/src/iothub_client/src/iothubtransport_mqtt_common.c:887:13: error: too few arguments to function 'mqtt_client_init'
In file included from /home/wzj/openwrt/sdk_x1000/src/iothub_client/src/iothubtransport_mqtt_common.c:18:0:
/home/wzj/openwrt/sdk_x1000/src/umqtt/inc/azure_umqtt_c/mqtt_client.h:48:1: note: declared here
make[2]: **\* [iothub_client/CMakeFiles/iothub_client_mqtt_ws_transport.dir/src/iothubtransport_mqtt_common.c.o] Error 1
make[1]: **\* [iothub_client/CMakeFiles/iothub_client_mqtt_ws_transport.dir/all] Error 2

**Comment by olivierbloch** [comment]
Hi @enjoydiy 
can you please add more details? Which steps did you go through? We need more details to help you out here

**Comment by tameraw** [comment]
@enjoydiy - Closing this issue. Please let us know is still having problems. Thanks.
