### ISSUE TITLE
Help building project on VS 2015 using Visual C++ for Linux

### ISSUE THREAD

**Issue by emtopping** [Azure/azure-iot-sdks#905]
Hi, I'm trying to build a simple project that access the SDK for Raspberry Pi 3 on Windows 7. I've managed to get it to compile by adding in the various headers in the SDK but it is not linking:

Note I have NOT installed the "Visual C++ for IoT Development" extension as I don't think that's required.

I have set up the additional libraries within VS Project properties as:

/home/pi/azure-iot-sdks/c/cmake/iotsdk_linux/iothub_service_client;//home/pi/azure-iot-sdks/c/cmake/iotsdk_linux/uamqp;/home/pi/azure-iot-sdks/c/cmake/iotsdk_linux/umqtt;/home/pi/azure-iot-sdks/c/cmake/iotsdk_linux/serializer;/home/pi/azure-iot-sdks/c/cmake/iotsdk_linux/c-utility;/home/pi/azure-iot-sdks/c/cmake/iotsdk_linux/iothub_client

(Note the actual test project is not within /home/pi/azure-iot-sdks but /home/pi/projects)

I have specified additional Library Dependencies as:

wiringPi;iothub_service_client;uamqp;umqtt;serializer;aziotsharedutil;iothub_client_mqtt_transport;iothub_client;iothub_client_amqp_transport;iothub_client_http_transport;

The various libNNNN.a libraries exist in the above directories.
I have set "Yes (-Wl,--verbose)" but I get nothing more than this:

This is the linker output:
  Compiling sources:
1>  Linking objects
1>g++: error : error : No such file or directory
1>g++: error: D : error : No such file or directory

... etc - about 20 more times! ...

1>g++: error : error : No such file or directory
1>g++: error : error : No such file or directory
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

On the Pi itself I can build one of the SDK samples no problem.

Can you help?

Thanks

**Comment by olivierbloch** [comment]
Hi @emtopping 
Have you gone through our document describing how to cross compile for a Linux target on Windows?
The document is here: https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md

**Comment by emtopping** [comment]
Hi, Oliver just to be clear I am not cross-compiling. Visual C++ for Linux copies everything over to the Pi and builds it natively. Can you advise on the libraries?

**Comment by emtopping** [comment]
This is the extension: 
https://visualstudiogallery.msdn.microsoft.com/725025cf-7067-45c2-8d01-1e0fd359ae6e

**Comment by olivierbloch** [comment]
Got it. We've not tested our build process using the VS extension yet.
Note that we are using cmake for now. We'll need some time to try and repro and put together instructions on how to leverage the extension.

**Comment by emtopping** [comment]
Thanks, Oliver. Larry from the team that developed the extension is currently progressing this via email with me. Hang fire until I can feedback with his response... (I think it's copying over some Windows libraries during the build).

**Comment by tameraw** [comment]
@emtopping - Can you please let us know on this thread where you're standing with this issue? Thanks.

**Comment by tameraw** [comment]
Please let us know is still having any issues. Thanks.
