### ISSUE TITLE
Azure IoT C SDK porting guide

### ISSUE THREAD

**Issue by sergiojx** [Azure/azure-iot-sdks#906]
Hi.
I am trying to port azure-iot-sdk as well. My embedded linux platform (ARM9, kernel 3.6.9), cross toolchain is arm-none-linux-gnueabi-gcc.No apt-get command. Is there some porting guide available?
Best.

**Comment by tameraw** [comment]
@sergiojx - Please see the link to our [Porting Guide](https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/porting_guide.md)

**Comment by sergiojx** [comment]
Thank you.

**Comment by sergiojx** [comment]
Hi tameraw.
I have read [Proting Guide](https://github.com/Azure/azure-c-shared-utility/blob/master/doc/porting_guide.md) and [Cross Compiling the Azure IoT Hub SDK](https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/SDK_cross_compile_example.md) 
now I´ve got two more ??
what is the actual ouput of the azure-c-shared-utility compilation? is it a .so shared library?
in order to cross complie the whole C Azure IoT SDK
How can I instruct cmake to find headers and libraries in different paths??

thanks in advance

**Comment by sergiojx** [comment]
Hi tameraw.
I have finally compiled C SDK with openssl 1.0.2h. 
After tuning some buildroot configuration files for openssl1.0.2h compilation, It has been built a SYSROOT directoy with all the required libraries and headers. 
Into my own cmake file I have:
SET(CMAKE_FIND_ROOT_PATH /home/embeddeddev/SPX_G25SDK/buildroot-at91/output/host/usr/arm-buildroot-linux-gnueabi/sysroot)

Now I have got into other issue: socket layer is not working =(
![sockererr](https://cloud.githubusercontent.com/assets/3307948/19935537/62ee0218-a0e8-11e6-91f7-083e370b3cca.png)
azure-iot-sdks/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:314 Failure: getaddrinfo failure -3.

I appreciate any suggestion. 
Finally: is it curl mandatoy?
Best

**Comment by sergiojx** [comment]
getaddrinfo failure -3 seems to be "Temporary failure in name resolution"

**Comment by sergiojx** [comment]
This problem is solved by adding some DNS servers. 
Add a resolv.conf file into /etc directory.
Its content can be(Google DNS servers):
nameserver 8.8.8.8 nameserver 8.8.4.4

**Comment by sergiojx** [comment]
HI
It almost works. I am trying iothub_client_sample_mqtt and now this is getting openssl issues.
![sslerr](https://cloud.githubusercontent.com/assets/3307948/19943831/1e500eb6-a107-11e6-994e-b3bbdd7678fb.png)


thanks in advance.
Best

**Comment by markrad** [comment]
Hi @sergiojx,

I'm not convinced that this is an SSL issue. the first error message from iothubtransport_mqtt_common.c specifying _Not Authorized_ is typically generated when the connection string passed is invalid thus the connection is rejected.

Can you ensure your connection string is correct? Perhaps try it from another platform with a different language. Node JS is pretty quick to set up and test with a simulated device. See this link: https://azure.microsoft.com/en-us/documentation/articles/iot-hub-node-node-getstarted/. You only need to refer to the section ***Create a simulated device app***.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @sergiojx,

Did you perform the test I suggested above? Is this problem resolved so that I can close the GitHub issue?

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @sergiojx,

I have closed this issue due to a lack of response from you. Please reopen it if you need to.

Ref: 116110714904097

**Comment by sergiojx** [comment]
Sorry mark. Issue was finally solved by a correct platform date and time zone setup.
Best.
