### ISSUE TITLE
stdatomic.h not found

### ISSUE THREAD

**Issue by ravikasyap1717** [Azure/azure-iot-sdks#910]
Hi, 
I am using cmake to compile the code.I have to add two more dynamic library with Azure IOT.
So, I want to compile the code in outside the azure folder means in current source directory.
So, I am using cmake to build the code instead of script.When i am running make, i found this error.

![screenshot from 2016-11-01 01 14 36](https://cloud.githubusercontent.com/assets/14104387/19870576/26e75dd0-9fd7-11e6-811c-978184f9efb6.png)
this is my cmake file .

[CMakeLists.txt](https://github.com/Azure/azure-iot-sdks/files/563443/CMakeLists.txt)

 I  am using Gcc 4.8.4 . when i am using script i am able to compile the code with ./build.sh --use-websockets --skip-unittests.
So, Please let me know how can i solve this issue.

**Comment by markrad** [comment]
Hi @ravikasyap1717,

You don't mention what platform you are using to build the SDK however some platforms do not include the stdatomic functions and hence do not have stdatomic.h.

You can circumvent this by adding _-cl -D__STDC_NO_ATOMICS___ to the parameter list passed to build.sh. This will cause refcount.h to use standard GNU C atomics instead. In your example this would now look like 
```
./build.sh --use-websockets --skip-unittests -cl -D__STDC_NO_ATOMICS__
```

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @ravikasyap1717,

Have you been able to resolve this issue?

_Mark Radbourne MSFT_

**Comment by ravikasyap1717** [comment]
Hi,
Yes, In Cmake file i force to off all test.It was working fine.

Thanks
Ravi Kumar

**Comment by markrad** [comment]
Thanks for the update. Closing as resolved.

_Mark Radbourne MSFT_
