### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by xingzhougmu** [Azure/azure-iot-sdks#913]
Run the following to clone this project:
`git clone --recursive https://github.com/Azure/azure-iot-sdks.git`

always failed with the error below:
**Failed to recurse into submodule path 'c/c-utility'**

**Comment by tameraw** [comment]
@xingzhougmu - I could not reproduce on my side. It worked for me. Can you please try again? Please make sure you start in a clean folder and let us know if you're still seeing this issue.

**Comment by tameraw** [comment]
@xingzhougmu - Closing. Please let us know if you're still having issues with more details. Thanks.
