### ISSUE TITLE
C iothub_client_sample_mqtt =( Connection Not Accepted: 0x05: Not Authorized

### ISSUE THREAD

**Issue by sergiojx** [Azure/azure-iot-sdks#915]
Hi.
I am trying to port azure-iot-sdk C. It almost works.  My embedded linux platform (ARM9, kernel 3.6.9), cross toolchain is arm-none-linux-gnueabi-gcc. gcc version 4.6.1

I have compiled C SDK with openssl 1.0.2h support. 
After tuning some [buildroot](https://buildroot.org/) configuration files for openssl1.0.2h compilation, It has been built a SYSROOT directoy with all the required libraries and headers. 
Into my own cmake file I have:
SET(CMAKE_FIND_ROOT_PATH /home/embeddeddev/SPX_G25SDK/buildroot-at91/output/host/usr/arm-buildroot-linux-gnueabi/sysroot)

So far so good=)

I am trying iothub_client_sample_mqtt and now this is getting openssl issues.
**Connection Not Accepted: 0x05: Not Authorized**
![sslerr](https://cloud.githubusercontent.com/assets/3307948/19954801/9ddca5ee-a149-11e6-8f67-8a9d44765ad9.png)
**...tlsio_openssl.c Func:decode_ssl_received_bytes Line:654 SSL channel closed in decode_ssl_received_bytes.**

**...tlsio_openssl.c Func:on_underlying_io_bytes_received Line:709 Error in decode_ssl_received_bytes.**

Same code works fine on Ubuntu so I am afraid, I have misunderstood certificate scheme, must this be stored into /etc/ssl/certs folder?, how can I get it? or this must be copied from .../c/certs/certs.c into iothub_client_sample_mqtt.c?
thank you in advance for your help.
Best

**Comment by sergiojx** [comment]
I have returned to original buildroot 1.0.1c openssl version, And I get same error.
![noconect](https://cloud.githubusercontent.com/assets/3307948/20023797/5d8f2dfa-a2b0-11e6-9628-77ef72c53048.png)

First IoTHubClient_LL_SendEventAsync transmissions seem to go fine, but MQTT CONNECT does not work.

I have used c/certs/certs.c certificates to build a ca-certificates.crt. This is stored into /etc/ssl/certs, and I have tested certificate. It has been got this output:
![crttest](https://cloud.githubusercontent.com/assets/3307948/20023963/4c71f7cc-a2b1-11e6-9fdc-c7af062f23e8.png)

**Comment by sergiojx** [comment]
I have solved cerificate issue, It was a matter of time, this  article [Troubleshooting Azure IOT Hub connections on embedded Linux ](https://blogs.msdn.microsoft.com/holgerkenn/2016/08/10/troubleshooting-azure-iot-hub-connections-on-embedded-linux/) holds key information about certificate verification and proper embedded linux platform time/time zone set up.
Thank you Holger

**Comment by tameraw** [comment]
@sergiojx - Closing. Please let us know if you're still having any issues. Thanks.
