### ISSUE TITLE
Readme pointing to dead link

### ISSUE THREAD

**Issue by radu-matei** [Azure/azure-iot-sdks#916]
https://github.com/Azure/azure-iot-sdks/tree/master/c/serializer/samples/simplesample_amqp/linux

The readme on this page is pointing to dead link - https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_sample_on_desktop_linux.md

I think it should be this link - https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/linux-desktop-c.md - but I am not sure.

**Comment by olivierbloch** [comment]
Fixed. Thanks
