### ISSUE TITLE
nodejs MQTT sendEvent throws client disconnecting error

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdks#917]
I am getting `client disconnecting` error when trying to send event using `sendEvent`. It also stops receiving any commands from cloud. Once I reboot it starts working fine. I am using version 1.0.16

Thanks

**Comment by pierreca** [comment]
@bmrpatel That's very little to go on. how often are you sending messages? after how long does this happen? can you paste some code and/or console logs? can you activate the verbose debug output (set the DEBUG environment variable to '*')? What version of node/npm are you using?

**Comment by bmrpatel** [comment]
@pierreca It happens when process is idle for about 3-4 hours. I am using Node v7. It has not happened for last 2 days. I will set the DEBUG mode and send you the output if it happens again. I will investigate the sdk code to see where it will return `client disconnecting` error upon `sendEvent` and let you know if I find something.  Thanks

**Comment by pierreca** [comment]
I'm guessing what might have happened is that the message was sent while the client was disconnecting and reconnecting to renew the SAS token. I've introduced a state machine mechanism in the new version of the SDK (will be released in the next few days) that should resolve this issue.

**Comment by pierreca** [comment]
I've just released a new version of the SDK (both the mainline and the preview packages). Please give it a try and let us know if that help!

**Comment by bmrpatel** [comment]
Thanks @pierreca,  I will test this and let you know.

**Comment by pierreca** [comment]
closing until we get more feedback

**Comment by bmrpatel** [comment]
I am not getting this error anymore. So must be good now. 
Thanks
