### ISSUE TITLE
SDK samples in java for the azure iot hub trouble

### ISSUE THREAD

**Issue by enchiladaRoja** [Azure/azure-iot-sdks#919]
Hi, the java samples in the sdk work fine in a machine with windows 10, but when i try to make it work in a raspberry pi 3 model B it doesnt connect, no matter what protocol i use, can someone help me, i provide all data neccesary.

The next images show the information I got when I try to run it. It seems like the client doesnt open.
If it helps, the same raspberry pi 3 model B is sending data to the azure iot hub to be used in the stream analytics and then shown in power bi. That data is been sending in to a different hub, but i dont know if that is causing trouble with the hub im trying to use. That data ys using languague phyton.

Im using this tutorial, https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/java-run-sample.md  and, again, in a machine with windows 10 works fine.

![error_https](https://cloud.githubusercontent.com/assets/23262644/20010149/a9a9c2ac-a26c-11e6-90b1-70fc0b287b78.PNG)
![error_https_log](https://cloud.githubusercontent.com/assets/23262644/20010148/a9a8d270-a26c-11e6-9888-4067847cd019.PNG)
![error_mqtt](https://cloud.githubusercontent.com/assets/23262644/20010147/a9a67674-a26c-11e6-8e17-999684c75956.PNG)
![error_amqps](https://cloud.githubusercontent.com/assets/23262644/20010150/a9b1ce5c-a26c-11e6-85d5-398031a3179c.PNG)

**Comment by markrad** [comment]
Hi @enchiladaRoja,

I took a look at your issue and I was able to reproduce it on my Raspberry Pi too. I've done a little further research and it would appear that something in open jdk 8 has created an incompatibility though only on the Raspberry Pi. I was able to use open jdk 8 on an Ubuntu desktop but not on the Pi.

To temporarily circumvent this issue please try using jdk 8 from Oracle instead. You may have this installed already. To find out try this:
```
pi@mr_rpi1 ~ $ sudo update-alternatives --config java
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                                   Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-openjdk-armhf/jre/bin/java          1063      auto mode
  1            /usr/lib/jvm/java-7-openjdk-armhf/jre/bin/java          1063      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-armhf/jre/bin/java          1063      manual mode
  3            /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/bin/java   318       manual mode

Press enter to keep the current choice[*], or type selection number: 3
update-alternatives: using /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/bin/java to provide /usr/bin/java (java) in manual mode
```

At the prompt I entered the number (three in my case) corresponding to the Oracle version of Java. If you don't have it installed you can install it via apt-get.

Thank you for reporting this issue. I will send my findings to the product group.

_Mark Radbourne MSFT_

**Comment by enchiladaRoja** [comment]
Thanks for the help, your solution work with the amqps protocol, but the mqtt still show the same error,I will try to find solution for that, but at least i can work now with amqps. Thank you very much!

**Comment by markrad** [comment]
Hi @enchiladaRoja,

This is not my experience. Here are the results of my testing:
```
|      | open jdk 7 | open jdk 8       | Oracle jdk 8 |
|------|------------|------------------|--------------|
| mqtt | works      | throws exception | works        |
| amqp | works      | fails            | works        |
```

Currently either Open jdk 7 or Oracle jdk 8 work as expected. The product team are looking into the issue with Open jdk 8.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @enchiladaRoja,

It seems that the product group are going to recommend using Oracle and consider that their supported JVM. Thank you for notifying us of this issue.

_Mark Radbourne MSFT_
