### ISSUE TITLE
Receive CloudToDevice Messages using c code

### ISSUE THREAD

**Issue by sivakesavareddy** [Azure/azure-iot-sdks#922]
Hi can u please send code link for receiving IotHub cloudtodevice messages using c code

**Comment by olivierbloch** [comment]
You can find samples for this in the following samples: 
  - using [MQTT](https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c)
  - using [AMQP](https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c)
  - using [HTTP](https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c)

**Comment by tameraw** [comment]
Let us know if you have any other issues. Regards.
