### ISSUE TITLE
iothub_service_client_auth.h #include reference change.

### ISSUE THREAD

**Issue by cnsegura** [Azure/azure-iot-sdks#925]
Hi,
In this file https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_service_client/inc/iothub_service_client_auth.h

The include statement on line 28 is currently coded as:
#include "macro_utils.h"

To work with the gateway SDK I needed to make it this:
#include "azure_c_shared_utility/macro_utils.h"

Can we get this changed?

**Comment by tameraw** [comment]
@cnsegura - Thanks for bringing this up. As I understand you're working with Jelani on this offline.

**Comment by jebrando** [comment]
I put this in a CR and it will be in this week.

Thanks,
Chris.
