### ISSUE TITLE
Get the messages published by other Devices IoTHub with MQTT protocol

### ISSUE THREAD

**Issue by adiabvs** [Azure/azure-iot-sdks#926]
Hi,

Is it possible from one device to get the messages published by other device from cloud storage?

**Comment by olivierbloch** [comment]
Hi @adiabvs 
An application running on a device can access data sent to IoT Hub, but it cannot do it with its device credentials and the device SDK. You would have to create an access policy in the IoT Hub for this, and use our Service SDK provisioned with these new credentials to access the data sent to IoT Hub by other devices.
Now, if what you want to implement is a device to device communication, then what I would recommend would be to instantiate a service such as Azure Functions or your own Cloud App that would monitor events coming into IoT Hub and would send the message back to the desired device when relevant. This allows you to have full control over who talks to who and ensure integrity of the data and security in your solution.
You can see such mechanism implemented in this sample: http://aka.ms/azureiotping
