### ISSUE TITLE
Iothub Register an X.509 certificate for a device with c code and Java

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#929]
Hi can u please send the documentation for Register an X.509 certificate for a device with c and java code
How to generate PrimaryThumbprint  for the device using c  and Java

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
To generate a cert and thumbrpint, you can use either [OpenSSL](https://www.openssl.org/) or [Windows SelfSignedCertificate](https://technet.microsoft.com/library/hh848633).
Regarding the registration of a device in the IoT Hub device registry using a cert and thumbprint, only the C# and Node service SDKs support it for now. If you want to do this in Java or C, you will need to implement this using the REST API.
Please read more about using X-509 to authenticate devices [here](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-security/#supported-x509-certificates).

**Comment by mupparajuvamsi** [comment]
Hi @olivierbloch .Thanks for quick reply Regarding rest api 
https://msdn.microsoft.com/en-us/library/azure/mt548493.aspx  here in put Request where can i pass cert and thumbprint

**Comment by olivierbloch** [comment]
Documentation needs to (and will soon) be updated.
To configure a device to use X.509 device client certs using a REST API:
PUT	https://{IoTHubName}.azure-devices.net/devices/{deviceId}?api-version={api-version}

{
  deviceId: "{deviceId}",
  authentication: {
   x509Thumbprint: {
     primaryThumbprint  : "{primaryThumbprint}"
  }
 } 
}
