### ISSUE TITLE
GetUser() role in the IoTHubConnectionString class

### ISSUE THREAD

**Issue by ppatierno** [Azure/azure-iot-sdks#93]
Deeping into the code I see the GetUser() method inside IoTHubConnectionString never referenced in the code.
The related GetPassword() is used only in the HTTP client to get the "authorization" header for the HTTP request.
So ... what's the role of GetUser() method ?

**Comment by rajeevmv** [comment]
It was used in earlier versions of DeviceClient that supported the Amqp SASL-Plain authentication mechanism. It is no longer used and can be removed.

**Comment by rajeevmv** [comment]
This method has been removed from the 'develop' branch.
