### ISSUE TITLE
Unable to get device Information in the DeviceToCloud Receive Program

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#933]
Hi I am sending messages from c program and i am receiving messages from Java Program Ia m not able to receive deviceId from Java receiver Program

  System.out.println(String.format("| Device ID: %s", receivedEvent.getProperties().get("iothub-connection-device-id")));
	               
	                System.out.println(String.format("| Message Payload: %s", new String(receivedEvent.getBody(),
	                  Charset.defaultCharset())));

If i am using only Java to Send and Receive i am able to do so

**Comment by sergaz-msft** [comment]
Hi @mupparajuvamsi can you please detail better the code you are using for this? Are you following a sample from Azure-IoT-SDK? And which version are you using? Thanks

**Comment by tameraw** [comment]
@mupparajuvamsi - Please let us know if still having issues and provide us more details. Thanks.

**Comment by sergaz-msft** [comment]
Hi @mupparajuvamsi in order to receive the device Id in Java you should do it like this:

```java
System.out.println(String.format("| Device ID: %s", receivedEvent.getSystemProperties().get("iothub-connection-device-id")));
```

**Comment by olivierbloch** [comment]
Closing. Please reopen if needed
