### ISSUE TITLE
[NODE]AMQP message format - transportObj

### ISSUE THREAD

**Issue by PanzerHabba** [Azure/azure-iot-sdks#936]
I have an iot-hub device client running on Linux/Node.js.
When I receive messages from cloud and output it to console:
`client.on('message', function(msg) {
            console.log(JSON.stringify(msg)) }`

I get the following output:

`{"data":{"type":"Buffer","data":[message.body represented binary]},"properties":{"propertyList":[{"key":"iothub-ack","value":"full"}]},"messageId":"MY_MESSAGE_ID","to":"/devices/MY_DEVICE/messages/deviceBound","expiryTimeUtc":null,"lockToken":"","correlationId":"","userId":"","transportObj":{"messageAnnotations":{"x-opt-sequence-number":290,"iothub-enqueuedtime":"2016-11-09T09:31:02.873Z","iothub-deliverycount":0},"properties":{"messageId":"MY-MESSAGE-ID","userId":null,"to":"/devices/MY_DEVICE/messages/deviceBound","subject":null,"replyTo":null,"correlationId":null,"contentType":null,"contentEncoding":null,"absoluteExpiryTime":null,"creationTime":null,"groupId":null,"groupSequence":null,"replyToGroupId":null},"applicationProperties":{"iothub-ack":"full"},"body":{"type":"Buffer","data":[message.body represented binary]}}}`

Why is it so that it seems like message.body and message.properties, set by application is duplicated ?
I get the following JSON-structure:
`{"data" : "", "properties" : "", "transportObj" : {"messageAnnotations" : "", "properties" : "", "body" :   ""}}`

npm list --depth=0
azure-iot-device@1.0.16
azure-iot-device-amqp@1.0.16

Is this expected behavior ?

**Comment by pierreca** [comment]
it's by design. the transportObj property is a reference to the object that is provided by the AMQP layer, in case you need to access some AMQP specific data that are not provided in the top-level properties.
