### ISSUE TITLE
Iothub DeviceToCloud and ClouToDevice message parameters

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#939]
Hi 
I want to know how can we identify the message has been already read or not.Now what is happening is If i give a particular time Instant in Java i Am getting all the messages If i run that Program More than once i I will get same data twice which we already read .How to Identify the data while reading whether this has been already consumed or not.If so what is the parameter we should set to mark that as read in Java

**Comment by tameraw** [comment]
@mupparajuvamsi - I'm not totally clear on what you are trying to do, but I believe you want to keep track of what you have read on the Service side. For that, I refer you to some of the [EvenHub documentation](https://blogs.msdn.microsoft.com/servicebus/2015/01/16/event-processor-host-best-practices-part-1/) on how to track what you have read and completed via the concept of "CheckPoints". The EventHub Java repo provides a sample showing how that is used. The sample an be found [here](https://github.com/Azure/azure-event-hubs-java/blob/e6413d059471d75224a62df89251c5dfd331f5e2/azure-eventhubs-samples/src/main/java/com/microsoft/azure/eventhubs/samples/EventProcessorSample.java).
