### ISSUE TITLE
Android sample not sending via AMQPS

### ISSUE THREAD

**Issue by sarahyiwang** [Azure/azure-iot-sdks#940]
Hi all,

I am attempting to test whether the Android sample can send messages via AMQPS. I confirmed with `iothubexplorer` that messages can be send over HTTPS, but I am not getting any feedback when I change to AMQPS. The messages don't seem to be showing up in Azure portal either.

I am using version 1.0.14 of `iot-hub-java-device-client`, for which I did a clean rebuild of the project when I changed it.

Besides these modifications, I have not changed the code. Any thoughts?

**Comment by tameraw** [comment]
Currently the Java SDK provides support for HTTP & MQTT on Android. Please try MQTT instead.
Having AMQP support with the Java SDK on Android is in our backlog and we'll be getting to it at some point.

**Comment by tameraw** [comment]
Currently there is limitation in porting the AMQP library for Android. We will be revisiting this at some point in the backlog, but I have to let you know it's not at the top of the priority list. Hopefully using MQTT can meet your scenario requirements.
