### ISSUE TITLE
Twins Querying is not working for node.js

### ISSUE THREAD

**Issue by ondrejtomcik** [Azure/azure-iot-sdks#941]
I am writing service for querying device twins of IoT Hub for node.js.
Basic query from provided sample is not working, same as my own implementation.
I am always receiving BadRequest.

For C# querying is working correctly.

`responseBody: '{"Message":"ErrorCode:ArgumentNull;BadRequest","ExceptionMessage":"Tracking ID:0145380c335046479275c10be0eb278f-G:0-TimeStamp:11/10/2016 08:37:23"}' }                
GET /api/v1/devicemanagement/query/test 400 357.758 ms - 147                                                                                                                        
{ [ArgumentError: BadRequest]                                                                                                                                                          
  message: 'BadRequest',                                                                                                                                                               
  stack: 'Error\n    at new ArgumentError (C:\\Projects\\pilot\\pilot-device-management\\node_modules\\azure-iothub\\node_modules\\azure-iot-common\\lib\\errors.js:14:17)\n   
 at Function.RestApiClient.translateError (C:\\Projects\\pilot\\pilot-device-management\\node_modules\\azure-iothub\\lib\\rest_api_client.js:148:15)\n    at C:\\Projects\\pilot\\pilot-device-management\\node_modules\\azure-iothub\\lib\\rest_api_client.js:101:28\n    at IncomingMessage.onResponseEnd (C:\\Projects\\pilot\\pilot-device-managem
ent\\node_modules\\azure-iothub\\node_modules\\azure-iot-http-base\\lib\\http.js:73:7)\n    at emitNone (events.js:72:20)\n    at IncomingMessage.emit (events.js:166:7)\n    at endRea
dableNT (_stream_readable.js:921:12)\n    at nextTickCallbackWith2Args (node.js:442:9)\n    at process._tickCallback (node.js:356:17)', `

**Comment by pierreca** [comment]
Hi
A breaking change was deployed in the device management preview regarding queries. We've adjusted the node SDK in the source tree but haven't released the new packages yet (it'll happen in the next couple of days). Here's the commit hash you can pull to get you back in working order: 63d0895dc1bb3b007b195db88f93d9b7c8e2d66d

**Comment by ondrejtomcik** [comment]
@pierreca provided commit does not fix the issue. I am still getting same ErrorCode ArgumentNull;BadRequest.

**Comment by pierreca** [comment]
And the packages have been released, so if you npm install azure-iothub@dtpreview you should get the latest version that contain the fix.
