### ISSUE TITLE
[DeviceExplorer] Timestamp corrupts the JSON payload

### ISSUE THREAD

**Issue by DanaEpp** [Azure/azure-iot-sdks#947]
If you select the "Add Time Stamp" to the "Message To Device" tab, when firing to the device it will blow up in ble_c2d.c on line 241. A sample error is:

Error: Time:Thu Nov 10 14:23:52 2016 File:/home/pi/code/azure-iot-gateway-sdk/modules/ble/src/ble_c2d.c Func:BLE_C2D_Receive Line:241 JSON Object expected, not received.

**Comment by tameraw** [comment]
@DanaEpp - Thanks for filing this issue. 
As this pertains to the azure-iot-gateway-sdk, please file the issue under that repo:
https://github.com/Azure/azure-iot-gateway-sdk/issues

**Comment by olivierbloch** [comment]
@tameraw 
This actually pertains to the DeviceExplorer tool, not the the gateway SDK.
Reopening

**Comment by sergaz-msft** [comment]
Hello @DanaEpp  I will have a look at this. Just let me know the branch you are using and if when you use the compiled version (.msi) can you send the message to the device with the TimeStamp?

**Comment by DanaEpp** [comment]
I was having this problem with both the shipping MSI as well as the custom build we had for the IoT Hackathon during MVP Summit.

The message I was sending was simply:

{"type": "write_once","characteristic_uuid": "F000AA65-0451-4000-B000-000000000000","data": "AQ=="}

But it would fail on any message I would send. If I checked the timestamp checkbox in the UI, it would inject it in the beginning of the message and screw up the JSON.

**Comment by sergaz-msft** [comment]
Hi @DanaEpp, thanks for the details. That is a normal behavior from Device Explorer if you are using it as is. Have a look at Device Explorer Code and you can see the following in [MainForm.cs](https://github.com/Azure/azure-iot-sdks/blob/master/tools/DeviceExplorer/DeviceExplorer/MainForm.cs#L545)
```cs
private async void sendMessageToDeviceButton_Click(object sender, EventArgs e)
        {
            try
            {
                if (checkBox1.Checked)
                {
                    if (string.IsNullOrEmpty(textBoxMessage.Text))
                    {
                        cloudToDeviceMessage = DateTime.Now.ToLocalTime().ToString();
                    }
                    else
                    {
                        cloudToDeviceMessage = DateTime.Now.ToLocalTime() + " - " + textBoxMessage.Text;
                    }
                }
                else
                {
                    cloudToDeviceMessage = textBoxMessage.Text;
                }
...
```


Meaning that we are not sending the message in a JSON Format. 

```cs
var serviceMessage = new Microsoft.Azure.Devices.Message(Encoding.ASCII.GetBytes(cloudToDeviceMessage));
```
You can customize Device Explorer very easily and encode the message to a JSON format.
Let me know if that helps?

**Comment by DanaEpp** [comment]
Have you actually tried it? If you select the timestamp button and look at the message firing across the wire, its blowing up on the line of code I showed. If you look at the JSON received in the SDK, it is indeed not in a format it can understand.

**Comment by olivierbloch** [comment]
I agree with you @DanaEpp 
@sergaz-msft , I've added a bug for resolving this in our backlog.

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-csharp#32
