### ISSUE TITLE
Extra 1000 has been multiplied when calculating sleep time in connectionLost method

### ISSUE THREAD

**Issue by allenhula** [Azure/azure-iot-sdks#949]
Extra 1000 has been multiplied when calculating sleep time in connectionLost method of MqttIotHubConnection class:
`Thread.sleep(TransportUtils.generateSleepInterval(currentReconnectionAttempt) * 1000);`
Because the value returned from `TransportUtils.generateSleepInterval(currentReconnectionAttempt)` has updated to multiply 1000 in this [commit](https://github.com/Azure/azure-iot-sdks/commit/dcdf605d07d088afabce3e7a3ff917077b5ad4a0).

**Comment by zolvarga** [comment]
Hi allenhula,

Thank you for using our SDK and reporting this issue. We are fixing it.

Zoltan

**Comment by anhashia** [comment]
**Fixed** in https://github.com/Azure/azure-iot-sdks/commit/79261d6bd51bc3872fc199b5818ea9e168d8ba40

https://github.com/Azure/azure-iot-sdks/blob/master/java/device/iothub-java-client/src/main/java/com/microsoft/azure/iothub/transport/mqtt/MqttIotHubConnection.java

Closing the issue
