### ISSUE TITLE
Do we have a recommendation on which Java version should be used on Windows?

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#95]
We link to the page of the downloads, but unfortunately they provide two versions on that link:
jdk1.7.0_79 as is mentioned in one of the examples, and then
jdk1.7.0_80 also appears to be present.
I've downloaded in the _80 update but if that is the better option we might want to explicitly state that, or if the _79 is preferred call that out as well.

Also we have a note about making sure that a Java\bin directory is part of the PATH environment variables.  After installing the JDK 1.7.0_80 as mentioned above I checked my path to see if it had been added for me.  The first entry in the path was:
C:\ProgramData\Oracle\Java\javapath

This folder in turn had three .symlink files (java, javaw and javaws) that all pointed to files in:
JRE 1.8.0_51\bin

So even if I added the bin path you suggested, it's unclear which version might get used.  And from your notes it sounds like I must use the 1.7.0 version.

Prepended the path suggested onto my system and then ran the java -version check in a new cmd prompt.  This was the result:

C:\windows\system32>java -version
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

**Comment by tameraw** [comment]
We need to revise the doc to allow customers to download version x or higher.

**Comment by dominicbetts** [comment]
@tameraw can you confirm the required versions for different platforms before I update the docs? My understanding is:
- Windows: Java SE 7 or higher
- Linux: Java SE 8 or higher

**Comment by andrew-buckley** [comment]
@dominicbetts, @jtanner-msft please update the docs to state that the required java version is now Java SE 8.

**Comment by andrew-buckley** [comment]
@dominicbetts, @jtanner-msft thanks for catching this.

**Comment by dominicbetts** [comment]
Submitted PR to specify Java SE 8/OpenJDK8 as the prerequisites.
@tameraw this issue can be closed now.

**Comment by tameraw** [comment]
Thanks @dominicbetts
