### ISSUE TITLE
[SDK C MQTT over WS] got segmentation fault

### ISSUE THREAD

**Issue by IngoMaindorfer** [Azure/azure-iot-sdks#950]
Hello @all,

at the moment we discover the new MQTT over WS feature, but unfortunately my stress tests failed. 

After some cycles of initialize the SDK, send some data via the the IoTHubClient_LL_* functions and some clean up via  IoTHubClient_LL_Destroy() and platform_deinit() I got a Segmentation fault:

Program terminated with signal 11, Segmentation fault.
#0  0x000e6458 in remove_wsi_socket_from_fds (wsi=wsi@entry=0x5fb6e0)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/c-utility/deps/libwebsockets/lib/pollfd.c:91
91		if (context->protocols[0].callback(wsi, LWS_CALLBACK_LOCK_POLL,

Here the stack trace:
(gdb) backtrace
#0  0x000e6458 in remove_wsi_socket_from_fds (wsi=wsi@entry=0x5fb6e0)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/c-utility/deps/libwebsockets/lib/pollfd.c:91
#1  0x000e54d0 in lws_close_free_wsi (wsi=wsi@entry=0x5fb6e0, reason=reason@entry=LWS_CLOSE_STATUS_NOSTATUS)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/c-utility/deps/libwebsockets/lib/libwebsockets.c:220
#2  0x000e5d78 in lws_service_timeout_check (wsi=0x5fb6e0, sec=1478802329)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/c-utility/deps/libwebsockets/lib/service.c:301
#3  0x000e5e84 in lws_service_fd (context=0x31bc68, pollfd=0x30b7f0)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/c-utility/deps/libwebsockets/lib/service.c:397
#4  0x000ec7e0 in lws_plat_service (context=0x31bc68, timeout_ms=<optimized out>)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/c-utility/deps/libwebsockets/lib/lws-plat-unix.c:179
#5  0x000d6c08 in xio_dowork (xio=<optimized out>)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/c-utility/src/xio.c:166
#6  0x000bb278 in mqtt_client_dowork (handle=0x6164d8)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1083
#7  0x000b823c in IoTHubTransport_MQTT_Common_DoWork (handle=0x301b50, iotHubClientHandle=<optimized out>)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2098
#8  0x000a87d0 in IoTHubClient_LL_DoWork (iotHubClientHandle=0x2fda90)
    at /home/mm/wago/ptxproj-2.4.22/platform-wago-pfcXXX/build-target/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:934
#9  0x000748e0 in TransmitterIoTHubLL::WaitForSdkToBecomeReady (this=0xbecc5788, a_connectionTimeout=110) at Connection/TransmitterIoTHubLL.cpp:342
#10 0x00073950 in TransmitterIoTHubLL::Run (this=0xbecc5788) at Connection/TransmitterIoTHubLL.cpp:200
#11 0x0007c73c in std::_Mem_fn<void (TransmitterIoTHubLL::*)()>::operator() (this=0x2640e8, __object=0xbecc5788)
    at /opt/OSELAS.Toolchain-2012.12.1/arm-cortexa8-linux-gnueabihf/gcc-4.7.3-glibc-2.16.0-binutils-2.22-kernel-3.6-sanitized/bin/../lib/gcc/arm-cortexa8-linux-gnueabihf/4.7.3/../../../../arm-cortexa8-linux-gnueabihf/include/c++/4.7.3/functional:554
#12 0x0007c618 in std::_Bind_simple<std::_Mem_fn<void (TransmitterIoTHubLL::*)()> (TransmitterIoTHubLL*)>::_M_invoke<0u>(std::_Index_tuple<0u>) (this=0x2640e4)
    at /opt/OSELAS.Toolchain-2012.12.1/arm-cortexa8-linux-gnueabihf/gcc-4.7.3-glibc-2.16.0-binutils-2.22-kernel-3.6-sanitized/bin/../lib/gcc/arm-cortexa8-linux-gnueabihf/4.7.3/../../../../arm-cortexa8-linux-gnueabihf/include/c++/4.7.3/functional:1598
#13 0x0007c464 in std::_Bind_simple<std::_Mem_fn<void (TransmitterIoTHubLL::*)()> (TransmitterIoTHubLL*)>::operator()() (this=0x2640e4)
    at /opt/OSELAS.Toolchain-2012.12.1/arm-cortexa8-linux-gnueabihf/gcc-4.7.3-glibc-2.16.0-binutils-2.22-kernel-3.6-sanitized/bin/../lib/gcc/arm-cortexa8-linux-gnueabihf/4.7.3/../../../../arm-cortexa8-linux-gnueabihf/include/c++/4.7.3/functional:1586
#14 0x0007c27c in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (TransmitterIoTHubLL::*)()> (TransmitterIoTHubLL*)> >::_M_run() (this=0x2640d8)
    at /opt/OSELAS.Toolchain-2012.12.1/arm-cortexa8-linux-gnueabihf/gcc-4.7.3-glibc-2.16.0-binutils-2.22-kernel-3.6-sanitized/bin/../lib/gcc/arm-cortexa8-linux-gnueabihf/4.7.3/../../../../arm-cortexa8-linux-gnueabihf/include/c++/4.7.3/thread:115

My system is an embedded Linux on ARM, SDK is from yesterday.

Best Regards,

Ingo

**Comment by chrit-msft** [comment]
@IngoMaindorfer Thanks for raising this issue, we are investigating this now.

**Comment by chrit-msft** [comment]
@IngoMaindorfer I have been trying to reproduce this issue but so far haven't hit the segfault you show above.  Are you still able to reproduce this issue?

**Comment by IngoMaindorfer** [comment]
Hi Chris,
please close this bug, can't reproduce that with code base from 2016-11-17.

Thanks,

Ingo

**Comment by tameraw** [comment]
@IngoMaindorfer - Thanks for the update.
