### ISSUE TITLE
[Java][MQTT] When connection is lost, IotHubReceiveTask prints Exception every 10ms to Stdout

### ISSUE THREAD

**Issue by zzeekk** [Azure/azure-iot-sdks#951]
Hello,

With MQTT Java client, if the connection is lost, IotHubReceiveTask.run prints an IllegalStateException to Stdout every 10ms, which fills up logs pretty fast...

Suggestions:
- throttle IotHubReceiveTask.run similar as MqttIotHubConnection.connectionLost
- make RECEIVE_PERIOD_MILLIS_MQTT configurable

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Looking into the issue.

**Comment by anhashia** [comment]
Hi @zzeekk 
Yeah, this scenario (use case) needs an **improvement**. Product Backlog Item (PBI) has been created to track this.

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-java#12
