### ISSUE TITLE
IotHub C deviceSdk HTTP Protocol issue

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#952]
Hi Please find the below Screenshot 

if ((iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, HTTP_Protocol)) == NULL)
![iothubcode](https://cloud.githubusercontent.com/assets/13390260/20255784/60410c3c-aa65-11e6-9b3a-854fa350c57c.png)
![iothubc](https://cloud.githubusercontent.com/assets/13390260/20255788/6b969f34-aa65-11e6-8f67-af9ed5378173.png)

In the First screenshot u can find code and i am getting exception inside the Corporate network
eventhough iam using http protocol

**Comment by enuysa-msft** [comment]
Hi @mupparajuvamsi 

If you are having issue with HTTP protocol in only your Corporate Network. I belive it is not related with the code you shared. But you can also test  REST Api to be sure if it is with HTTP protocol(https://msdn.microsoft.com/en-us/library/azure/mt590784.aspx) then if you have the same error as seen your screenshot( HTTP status code 403) then it is probably some firewalls are blocking to access IoT Hub.

**Comment by enuysa-msft** [comment]
Closing. Please re-activate if you still are having issues. Thanks !

@tameraw Could you please close this?

**Comment by enuysa-msft** [comment]
Hi @mupparajuvamsi 

Did you check that if some firewalls are blocking to access IoT Hub?

**Comment by tameraw** [comment]
Let us know if still having issues.
