### ISSUE TITLE
azure-iot-support-for-x-509-certificates using c code 

### ISSUE THREAD

**Issue by rajeshlipu** [Azure/azure-iot-sdks#953]
Hi Can you send a way to generate x509 certificate using c code and how to sign that with Azure Iothub x509 certifcate authentication .To be straight forward  How IoT device can now store a private key locally, and an associated device X.509 certificate generated to identify the device to Azure IoT Hub before the information is transmitted using c code both creating private key and x509 certificate using c code

**Comment by tameraw** [comment]
@rajeshlipu - Thanks for filing this.
Please checkout the documentation provided [here](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-security/#supported-x509-certificates) in regards to how to use an existing cert, self generated one or use a CA-signed cert.

**Comment by tameraw** [comment]
Let us know if you have any further questions.
