### ISSUE TITLE
[c][iothub_client] reconnection policy function group

### ISSUE THREAD

**Issue by IngoMaindorfer** [Azure/azure-iot-sdks#954]
Hi there,

I have some issues with the newest master according iothub_client functions:

IoTHubClient_SetRetryPolicy(), IoTHubClient_GetRetryPolicy() and IoTHubClient_GetRetryPolicy() are affected by:
a) docu issue: all functions have the same docu with is clearly false
b) functions take IOTHUB_CLIENT_LL_HANDLE as argument but it should be IOTHUB_CLIENT_HANDLE
c) all three functions have an empty body in the .c file, just a few casts of the arguments to make the compiler happy and they do exactly nothing else...

Best Regards,

Ingo

**Comment by prmathur-microsoft** [comment]
Thanks for reporting this issue. We were in the middle of development when you happened to see this. Reconnection policy is implemented for mqtt and it is currently in develop (which will come into master in couple of days). Please give it a try and let us know if you still see this issue.

**Comment by lmussier** [comment]
Hi

@prmathur-microsoft when you say

> We were in the middle of development when you happened to see this. Reconnection policy is implemented for mqtt and it is currently in develop

Does it mean that reconnection policy is exclusivly availbale for MQTT transport ? (it seems to be the case since AMQP/WS is still "non implemented")

The question is, does AMQP is a kind of deprecated transport ? Or the plan is to leverage all transport to the same feature set ?

**Comment by prmathur-microsoft** [comment]
We are in the process of implementing the retry logic for AMQP and AMQP-WS as well. We want to have same feature set across all transports.

**Comment by tameraw** [comment]
Please visit this project to see the progress of the retry logic. We sill be adding the same support in AMQP and AMQP_overwebsockets. Regards.
