### ISSUE TITLE
Monitor_the_subscription_requests

### ISSUE THREAD

**Issue by ramya12345** [Azure/azure-iot-sdks#955]
Hi,
I would like to know if there is  any way to find  a subscription request is done by a device  using JAVA.In short  I need to know whether a device is connected for subscription or not.Can you please help me.Thanks in Advance.

**Comment by tameraw** [comment]
@ramya12345 - You can query the "ConnectionState" on the service side to find out if the device is connected or not. For more details, please see the following:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry

**Comment by tameraw** [comment]
@ramya12345 - Closing issue. Please let us know if still having any other questions.
