### ISSUE TITLE
[Linux C SDK] Memory leak in init() - do_work() - deinit() cylce

### ISSUE THREAD

**Issue by IngoMaindorfer** [Azure/azure-iot-sdks#957]
Hi there,

I've got a memory leak while trying to send a message , cleaning up SDK and reinitializing it (because of faulty network).

Please find attached example and change the connection string at line 218 and let it run and disable your network, e.g. by calling ifconfig. 
The leak is worse with AMPQ than with MQTT, you can change that in line 215.

This is really a show stopper for us because we need a stable reconnect scenario and current SDK didn't provide it yet.

Best Regards,

Ingo

[azure_test.zip](https://github.com/Azure/azure-iot-sdks/files/591267/azure_test.zip)

PS: some valgrind messages:

==8973== 32,736 bytes in 1 blocks are possibly lost in loss record 813 of 902
==8973==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5FC1248: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19)
==8973==    by 0x5FC1E0A: std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19)
==8973==    by 0x5FC1EA3: std::string::reserve(unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19)
==8973==    by 0x5FC20EE: std::string::append(char const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19)
==8973==    by 0x468A67: main::{lambda()#1}::operator()() const (test.cpp:127)
==8973==    by 0x46ACB1: void std::_Bind_simple<main::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) (functional:1732)
==8973==    by 0x46AC08: std::_Bind_simple<main::{lambda()#1} ()>::operator()() (functional:1720)
==8973==    by 0x46ABA1: std::thread::_Impl<std::_Bind_simple<main::{lambda()#1} ()> >::_M_run() (thread:115)
==8973==    by 0x5FB8A5F: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19)
==8973==    by 0x5CF1183: start_thread (pthread_create.c:312)
==8973==    by 0x682137C: clone (clone.S:111)
==8973== 
==8973== 34,827 bytes in 57 blocks are possibly lost in loss record 814 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5558DB2: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x5603153: asn1_enc_save (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x5602889: ASN1_item_ex_d2i (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x5602C3F: ??? (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x5602E8B: ??? (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x56025E4: ASN1_item_ex_d2i (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x56029C3: ASN1_item_d2i (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x56114DD: PEM_ASN1_read_bio (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x41A5BB: add_certificate_to_store (tlsio_openssl.c:752)
==8973==    by 0x41A6C6: create_openssl_instance (tlsio_openssl.c:800)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973== 
==8973== 46,080 bytes in 45 blocks are possibly lost in loss record 816 of 902
==8973==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5558E68: CRYPTO_realloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x55DEFE9: sk_insert (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x52D8D32: ??? (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x52D1963: SSL_CTX_new (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x41A67F: create_openssl_instance (tlsio_openssl.c:794)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973==    by 0x41BA7C: xio_open (xio.c:90)
==8973==    by 0x42E397: mqtt_client_connect (mqtt_client.c:865)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973== 
==8973== 51,964 (352 direct, 51,612 indirect) bytes in 11 blocks are definitely lost in loss record 818 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5558DB2: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x55DEECC: sk_new (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x561A67D: X509_STORE_new (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x52D1930: SSL_CTX_new (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x41A67F: create_openssl_instance (tlsio_openssl.c:794)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973==    by 0x41BA7C: xio_open (xio.c:90)
==8973==    by 0x42E397: mqtt_client_connect (mqtt_client.c:865)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973== 
==8973== 53,248 bytes in 52 blocks are possibly lost in loss record 819 of 902
==8973==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5558E68: CRYPTO_realloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x55DF1D9: sk_dup (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x52D8D4D: ??? (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x52D1963: SSL_CTX_new (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x41A67F: create_openssl_instance (tlsio_openssl.c:794)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973==    by 0x41BA7C: xio_open (xio.c:90)
==8973==    by 0x42E397: mqtt_client_connect (mqtt_client.c:865)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973== 
==8973== 62,400 bytes in 52 blocks are possibly lost in loss record 822 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5558DB2: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x52B7579: ??? (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x52C0CC8: ??? (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x52D3E6F: SSL_new (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x41AAA8: create_openssl_instance (tlsio_openssl.c:884)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973==    by 0x41BA7C: xio_open (xio.c:90)
==8973==    by 0x42E397: mqtt_client_connect (mqtt_client.c:865)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973== 
==8973== 406,264 (2,752 direct, 403,512 indirect) bytes in 86 blocks are definitely lost in loss record 865 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5558DB2: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x561A479: X509_LOOKUP_new (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x561A826: X509_STORE_add_lookup (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x5613E8F: X509_STORE_set_default_paths (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x41AA52: create_openssl_instance (tlsio_openssl.c:878)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973==    by 0x41BA7C: xio_open (xio.c:90)
==8973==    by 0x42E397: mqtt_client_connect (mqtt_client.c:865)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973== 
==8973== 549,142 bytes in 5,038 blocks are definitely lost in loss record 870 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x411065: mallocAndStrcpy_s (crt_abstractions.c:689)
==8973==    by 0x42CEA6: cloneMqttOptions (mqtt_client.c:426)
==8973==    by 0x42E312: mqtt_client_connect (mqtt_client.c:859)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973==    by 0x42BC50: IoTHubTransportMqtt_DoWork (iothubtransportmqtt.c:89)
==8973==    by 0x4276B9: IoTHubClient_LL_DoWork (iothub_client_ll.c:934)
==8973==    by 0x4697CB: WaitForSdkToBecomeReady(double) (test.cpp:310)
==8973==    by 0x468C16: main (test.cpp:153)
==8973== 
==8973== 610,089 (80,720 direct, 529,369 indirect) bytes in 5,045 blocks are definitely lost in loss record 872 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x41B976: xio_create (xio.c:39)
==8973==    by 0x41A937: create_openssl_instance (tlsio_openssl.c:861)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973==    by 0x41BA7C: xio_open (xio.c:90)
==8973==    by 0x42E397: mqtt_client_connect (mqtt_client.c:865)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973==    by 0x42BC50: IoTHubTransportMqtt_DoWork (iothubtransportmqtt.c:89)
==8973==    by 0x4276B9: IoTHubClient_LL_DoWork (iothub_client_ll.c:934)
==8973==    by 0x4697CB: WaitForSdkToBecomeReady(double) (test.cpp:310)
==8973== 
==8973== 728,892 bytes in 5,038 blocks are definitely lost in loss record 878 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x411065: mallocAndStrcpy_s (crt_abstractions.c:689)
==8973==    by 0x42CF20: cloneMqttOptions (mqtt_client.c:434)
==8973==    by 0x42E312: mqtt_client_connect (mqtt_client.c:859)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973==    by 0x42BC50: IoTHubTransportMqtt_DoWork (iothubtransportmqtt.c:89)
==8973==    by 0x4276B9: IoTHubClient_LL_DoWork (iothub_client_ll.c:934)
==8973==    by 0x4697CB: WaitForSdkToBecomeReady(double) (test.cpp:310)
==8973==    by 0x468C16: main (test.cpp:153)
==8973== 
==8973== 2,490,882 (16,928 direct, 2,473,954 indirect) bytes in 529 blocks are definitely lost in loss record 894 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5558DB2: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x55DEEAE: sk_new (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x561A67D: X509_STORE_new (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x52D1930: SSL_CTX_new (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x41A67F: create_openssl_instance (tlsio_openssl.c:794)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973==    by 0x41BA7C: xio_open (xio.c:90)
==8973==    by 0x42E397: mqtt_client_connect (mqtt_client.c:865)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973== 
==8973== 4,939,558 (33,504 direct, 4,906,054 indirect) bytes in 1,047 blocks are definitely lost in loss record 897 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5558DB2: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x561A479: X509_LOOKUP_new (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x561A826: X509_STORE_add_lookup (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x5613E63: X509_STORE_set_default_paths (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x41AA52: create_openssl_instance (tlsio_openssl.c:878)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973==    by 0x41BA7C: xio_open (xio.c:90)
==8973==    by 0x42E397: mqtt_client_connect (mqtt_client.c:865)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973== 
==8973== 58,018,484 (4,877,088 direct, 53,141,396 indirect) bytes in 6,036 blocks are definitely lost in loss record 902 of 902
==8973==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8973==    by 0x5558DB2: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==8973==    by 0x52D3C1F: SSL_new (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==8973==    by 0x41AAA8: create_openssl_instance (tlsio_openssl.c:884)
==8973==    by 0x41B03B: tlsio_openssl_open (tlsio_openssl.c:1051)
==8973==    by 0x41BA7C: xio_open (xio.c:90)
==8973==    by 0x42E397: mqtt_client_connect (mqtt_client.c:865)
==8973==    by 0x4628EC: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1231)
==8973==    by 0x462AA4: InitializeConnection (iothubtransport_mqtt_common.c:1291)
==8973==    by 0x46444F: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:1982)
==8973==    by 0x42BC50: IoTHubTransportMqtt_DoWork (iothubtransportmqtt.c:89)
==8973==    by 0x4276B9: IoTHubClient_LL_DoWork (iothub_client_ll.c:934)
==8973== 
==8973== LEAK SUMMARY:
==8973==    definitely lost: 6,319,648 bytes in 27,875 blocks
==8973==    indirectly lost: 61,505,897 bytes in 829,699 blocks
==8973==      possibly lost: 513,853 bytes in 6,447 blocks
==8973==    still reachable: 21,508,183 bytes in 7,932 blocks
==8973==         suppressed: 0 bytes in 0 blocks
==8973== Reachable blocks (those to which a pointer was found) are not shown.
==8973== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==8973== 
==8973== For counts of detected and suppressed errors, rerun with: -v
==8973== ERROR SUMMARY: 113 errors from 113 contexts (suppressed: 0 from 0)

**Comment by markrad** [comment]
Hi @IngoMaindorfer,

Can you tell me the Linux distro, version and architecture (32/64 bit) please? I'll run your code and see if I can reproduce this with the latest master version of the SDK on GitHub.

_Mark Radbourne MSFT_

**Comment by IngoMaindorfer** [comment]
Hi Mark,

my given code didn't show the leak against newest release from 2016-11-17, tested on Mint 17.4 (which is based on Ubuntu 14.04 LTS, 64 bit).
Something magically happens in between ;-)
I'm missing the unimplemented reconnect policies. What's the schedule for them?

Best,

Ingo

**Comment by markrad** [comment]
Hi @IngoMaindorfer,

There have been some significant changes in the SDK recently. Most of this was aimed at detecting and recovering from a network failure. Your issue was probably fixed by that code.

This work is still continuing and should include the missing policies. I have not been provided with a firm completion date.

_Mark Radbourne MSFT_
