### ISSUE TITLE
Error when creating device using iothub-explorer

### ISSUE THREAD

**Issue by sankettandulwadkar** [Azure/azure-iot-sdks#959]
Hi, 

I am trying to create a device identity for a box using iothub-explorer, I am getting this error -
[root@localhost ~]# iothub-explorer create sanketsdevice

Error: InternalServerError: InternalServerError

I am logged in using the "login" command.

[root@localhost ~]# npm list
/root
└─┬ azure-iothub@1.0.18
  ├─┬ azure-iot-amqp-base@1.0.17
  │ ├─┬ amqp10@3.3.2
  │ │ ├─┬ bl@1.1.2
  │ │ │ └─┬ readable-stream@2.0.6
  │ │ │   ├── core-util-is@1.0.2
  │ │ │   ├── inherits@2.0.3
  │ │ │   ├── isarray@1.0.0
  │ │ │   ├── process-nextick-args@1.0.7
  │ │ │   ├── string_decoder@0.10.31
  │ │ │   └── util-deprecate@1.0.2
  │ │ ├── bluebird@3.4.6
  │ │ ├── buffer-builder@0.2.0
  │ │ ├── lodash@4.17.2
  │ │ ├── node-amqp-encoder@0.0.2
  │ │ ├── node-int64@0.4.0
  │ │ └── stately.js@1.3.0
  │ ├─┬ amqp10-transport-ws@0.0.5
  │ │ └── nodejs-websocket@1.7.1
  │ ├─┬ debug@2.3.2
  │ │ └── ms@0.7.2
  │ ├─┬ sinon@1.17.6
  │ │ ├── formatio@1.1.1
  │ │ ├── lolex@1.3.2
  │ │ ├── samsam@1.1.2
  │ │ └─┬ util@0.10.3
  │ │   └── inherits@2.0.1
  │ └─┬ sinon-as-promised@4.0.2
  │   ├─┬ create-thenable@1.0.2
  │   │ ├─┬ object.omit@2.0.1
  │   │ │ ├─┬ for-own@0.1.4
  │   │ │ │ └── for-in@0.1.6
  │   │ │ └── is-extendable@0.1.1
  │   │ └── unique-concat@0.2.2
  │   └── native-promise-only@0.8.1
  ├─┬ azure-iot-common@1.0.16
  │ └── crypto@0.0.3
  ├─┬ azure-iot-http-base@1.0.16
  │ └── azure-iot-common@1.0.15
  └── uuid@2.0.3

**Comment by pierreca** [comment]
@sankettandulwadkar 
- are you still running into this issue?
- what version of iothub-explorer are you using (`iothub-explorer --version` should tell you)

The 500 error makes me think it's a service issue more than an SDK or iothub-explorer issue it might have been transient? If it keeps reproducing, can you write down the exact time at which you made the request and give us the hub name?

**Comment by sankettandulwadkar** [comment]
@pierreca -

**Comment by tameraw** [comment]
@sankettandulwadkar - Please let us know if still encountering any issues.
Regards.
