### ISSUE TITLE
iothub.Device is not a constructor     at Object.<anonymous> (/Users/luis.valencia/Projects/IoTSamples/NodeJSIoTHelloWorld /CreateDeviceIdentity.js:7:14)

### ISSUE THREAD

**Issue by levalencia** [Azure/azure-iot-sdks#962]
With NodeJS I am using the basic sample documentation from here:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-getstarted

However I get this error:
iothub.Device is not a constructor
    at Object.<anonymous> (/Users/luis.valencia/Projects/IoTSamples/NodeJSIoTHelloWorld
/CreateDeviceIdentity.js:7:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

My code is as follows:

```javascript
 'use strict';
var iothub = require('azure-iothub');
var connectionString = 'HostName=xxx.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=xxx=';
var registry = iothub.Registry.fromConnectionString(connectionString);
var deviceId = "helloworlddevice";

var device = new iothub.Device(null);
device.deviceId = deviceId;
 
registry.create(device, function(err, deviceInfo, res) {
  if (err)
    registry.get(device.deviceId, printDeviceInfo); 
 
  if (deviceInfo)
    printDeviceInfo(err, deviceInfo, res) 
});
 
function printDeviceInfo(err, deviceInfo, res) {
  if (deviceInfo)
    console.log('Generated device key: ' + deviceInfo.authentication.SymmetricKey.primaryKey);
}
```

**Comment by sharathbaddam** [comment]
looks like azure-iothub is not exporting device.js file from lib

**Comment by levalencia** [comment]
So this happened to you as well, I wonder if this was ever tested

**Comment by tameraw** [comment]
Please try latest package released last night and let us know if still having issues.

**Comment by levalencia** [comment]
I reinstalled the package and the error is gone, however I get a new error

TypeError: Cannot read property 'primaryKey' of undefined
    at printDeviceInfo (/Users/luis.valencia/Projects/IoTSamples/NodeJSIoTHelloWorld/Cr
eateDeviceIdentity.js:20:82)
    at /Users/luis.valencia/Projects/IoTSamples/NodeJSIoTHelloWorld/CreateDeviceIdentit
y.js:15:5
    at /Users/luis.valencia/Projects/IoTSamples/NodeJSIoTHelloWorld/node_modules/azure-
iothub/lib/registry.js:139:7
    at /Users/luis.valencia/Projects/IoTSamples/NodeJSIoTHelloWorld/node_modules/azure-
iothub/lib/rest_api_client.js:109:7
    at IncomingMessage.onResponseEnd (/Users/luis.valencia/Projects/IoTSamples/NodeJSIo
THelloWorld/node_modules/azure-iothub/node_modules/azure-iot-http-base/lib/http.js:73:7
)

**Comment by levalencia** [comment]
OK, I found the bug when debugging, its a documentation issue,

It should be symmetricKey not SymmetricKey, please correct in the documentation.

**Comment by dominicbetts** [comment]
@levalencia @tameraw The [doc ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-getstarted) will be updated later today.

@tameraw Please close.

**Comment by alianal89** [comment]
Hi, 

Today while tryibg to run this tutorial, I got the following issue. Could you please let me know what is wrong actually, tried it a couple of times but always the same error is there.

Following the tutorial when I try to run CreateDeviceIdentity.js, it gives the following message on command prompt

C:\createdeviceidentity>node CreateDeviceIdentity.js

C:\createdeviceidentity\node_modules\azure-iot-common\lib\connection_string.js:2
1
    if (!(key in dict)) throw new ArgumentError(err + key);
                        ^
Error
    at new ArgumentError (C:\createdeviceidentity\node_modules\azure-iot-common\
lib\errors.js:14:17)
    at C:\createdeviceidentity\node_modules\azure-iot-common\lib\connection_stri
ng.js:21:31
    at Array.forEach (native)
    at Function.parse (C:\createdeviceidentity\node_modules\azure-iot-common\lib
\connection_string.js:20:18)
    at Object.parse (C:\createdeviceidentity\node_modules\azure-iothub\lib\conne
ction_string.js:12:17)
    at Function.fromConnectionString (C:\createdeviceidentity\node_modules\azure
-iothub\lib\registry.js:61:29)
    at Object.<anonymous> (C:\createdeviceidentity\CreateDeviceIdentity.js:6:33)

    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

C:\createdeviceidentity>

**Comment by alianal89** [comment]
My code is following in CreateDeviceIdentity.js file

 'use strict';

 var iothub = require('azure-iothub');
 var connectionString = '{HostName=SimulatedNODElatestTest.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=PjcYmCqKbOz0ws92Y4CxjEXDWIu0qTXr0uJ1mYfSWd0=}';

 var registry = iothub.Registry.fromConnectionString(connectionString);
var device = new iothub.Device(null);
 device.deviceId = 'myFirstNodeDevice';
 registry.create(device, function(err, deviceInfo, res) {
   if (err) {
     registry.get(device.deviceId, printDeviceInfo);
   }
   if (deviceInfo) {
     printDeviceInfo(err, deviceInfo, res)
   }
 });

 function printDeviceInfo(err, deviceInfo, res) {
   if (deviceInfo) {
     console.log('Device id: ' + deviceInfo.deviceId);
     console.log('Device key: ' + deviceInfo.authentication.symmetricKey.primaryKey);
   }
 }

**Comment by pierreca** [comment]
@alianal89 The problem is with your connection string, it should not have the curly braces on each end of the string. 

Also:
- Please don't post your connection string in the issue. I suggest your rotate you generate new keys for the iothubowner policy.
- Please open a new issue when the error you're seeing is different from the original issue.
