### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by mm-ark** [Azure/azure-iot-sdks#965]
Hi folks,

We are using "Azure IoT device SDK for C" and try to implement the connectivity between our Linux-based programmable field devices and Azure Cloud via MQTT protocol.
Our management planned a potential solution to collect data from our devices within Azure Cloud all the time (24/7).

We observed that SDK behaves bad in case the network connection is not available after device power-on or when it gets interrupted over and over again.
It means that SDK does not reconnect or needs hours to do so.

So far we have implemented a workaround: we are using LL API, so its is possible to detect interrupted network connection and then "restart SDK".
Now we observe that "restart SDK" produces memory leaks. This is crucial for the whole intended solution.

We can easily reproduce memory leaks by following pseudo code.

```
int main(int argc, char *argv[])
{
    xlogging_set_log_function(nullptr); // Silence out the SDK
    for(;;)
    {
        platform_init();
        std::cout << "Starting ...";
        auto iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(
                    "HostName=mytest.azure-devices.net;DeviceId=MyDevice;SharedAccessKey=rcBjPRNm9ko6pkdw4SxLHeHrnYkNXYABCRB04gu1FfU=",
                    MQTT_Protocol);

        IoTHubClient_LL_DoWork(iotHubClientHandle);
        ThreadAPI_Sleep(10);
        IoTHubClient_LL_Destroy(iotHubClientHandle);
        std::cout << "... end" << std::endl;
        platform_deinit();
    }
}
```

Thank you in advance & best regards :-)
ark

**Comment by markrad** [comment]
Hi @mm-ark,

I'm working on reproducing this. With a small number of iterations valgrind did not report any memory leaks using the latest clone of the master branch. I'm going to leave it running for longer to see if the results are different.

Can you provide me details about how you are detecting a failed network connection? It might be that it only leaks when this occurs. I have not implemented anything to simulate that condition.

_Mark Radbourne MSFT_

**Comment by mm-ark** [comment]
Hey Mark,

The reported issue is reproducable in release tagged as "2016-09-09"
According to our first checks on the release tagged as "2016-11-17" this issue is as well not reproducable anymore. Thank you very much for checking! :-)

If you are still interested how we detect failed netwrok connection then my colleaque has discribed it within the issue #957

**Comment by markrad** [comment]
Hi @mm-ark,

Thank you for the update. I worked with your colleague on that issue too. Since you are no longer able to reproduce the defect I this closed issue.

Thank for taking the time to report this.

_Mark Radbourne MSFT_
