### ISSUE TITLE
Twin is not defined in typings file 

### ISSUE THREAD

**Issue by sharathbaddam** [Azure/azure-iot-sdks#969]
C:/Users/sbaddam/Documents/gitHub/node_modules/azure-iot-device/lib/client.d.ts(23,36): error TS2304: Cannot find name 'Twin'.

https://github.com/Azure/azure-iot-sdks/blob/master/node/device/core/lib/client.d.ts#L23

**Comment by sharathbaddam** [comment]
Please comment line 23 in client.d.ts file ( getTwin(done: (err: Error, twin: Twin) => void): void; ) to avoid any further errors when using 'azure-iot-device' package!

**Comment by pierreca** [comment]
An omission on our part. I'm adding the class and this will be fixed in the next release.

**Comment by pierreca** [comment]
fix is here: https://github.com/Azure/azure-iot-sdk-node/commit/fe291cdcde8c95d338c95b6c1416e892987ff706

we'll be releasing end of next week. Feel free to clone the `develop` branch of our new repo for the node SDK if you want to benefit from it right now: https://github.com/Azure/azure-iot-sdk-node/

**Comment by sharathbaddam** [comment]
Thank you!
