### ISSUE TITLE
cannot build azure-iot-sdks for c on Ubuntu machine

### ISSUE THREAD

**Issue by xingzhougmu** [Azure/azure-iot-sdks#970]
I follow [this link](https://github.com/Azure/azure-iot-sdks/blob/master/doc/iotcertification/iot_certification_linux_c/iot_certification_linux_c.md) to compile iot-hub SDK for c on ubuntu.
I downloaded the sdk file in zip format and unzip in my ubuntu machine.

I tried to run the following code to build:
```
sudo ./azure-iot-sdks/c/build_all/linux/build.sh --run-e2e-tests | tee LogFile.txt
```
However, get the following error. It complains that some directories does not contain **CMakeLists.txt**. I looked inside those folders. They are indeed empty. Am I missing anything here?
```
CMake Error at dependencies.cmake:22 (add_subdirectory):
  The source directory

    /home/xing/azure-iot-sdks/c/c-utility

  **does not contain a CMakeLists.txt file.**
Call Stack (most recent call first):
  CMakeLists.txt:111 (include)


CMake Error at dependencies.cmake:23 (add_subdirectory):
  The source directory

    /home/xing/azure-iot-sdks/c/uamqp

  **does not contain a CMakeLists.txt file.**
Call Stack (most recent call first):
  CMakeLists.txt:111 (include)


CMake Error at dependencies.cmake:24 (add_subdirectory):
  The source directory

    /home/xing/azure-iot-sdks/c/umqtt

  **does not contain a CMakeLists.txt file.**
Call Stack (most recent call first):
  CMakeLists.txt:111 (include)


-- Looking for __x86_64__
-- Looking for __x86_64__ - found
-- iothub architecture: x86_64
CMake Error at iothub_service_client/tests/connectionstringparser_ut/CMakeLists.txt:22 (build_test_artifacts):
  Unknown CMake command "build_test_artifacts".
```

**Comment by enuysa-msft** [comment]
Hi @xingzhougmu,

Could you please try get the sdk with using git command instead of downloading zip directly?

`git clone --recursive https://github.com/Azure/azure-iot-sdks.git`

Then you can try to run the following code to build:
`sudo ./azure-iot-sdks/c/build_all/linux/build.sh --run-e2e-tests | tee LogFile.txt`

**Comment by xingzhougmu** [comment]
Hi @enuysa-msft 

Thanks for your response. I tried git clone before. But the issue is it will take hours, and will finally failed with errors. 

I am trying again now, and will let you know the result. (BTW, I am testing from an UbuntU VM in China Azure)

```
xing@ML-Learning:~/Downloads$ git clone --recursive https://github.com/Azure/azure-iot-sdks.git
Cloning into 'azure-iot-sdks'...
remote: Counting objects: 59961, done.
remote: Compressing objects: 100% (1585/1585), done.
Receiving objects:   1% (1098/59961), 212.00 KiB | 4.00 KiB/s
```

**Comment by xingzhougmu** [comment]
Hi @enuysa-msft

Git clone finished successfully, and the build can move forward.

**One observation:**
The downloaded zip file is only around **18MB**, while the direct git clone size will be **~200MB**. Do you think there is any issue with the zip file. Will we fix it?

Cheers,
Xing

**Comment by enuysa-msft** [comment]
Hi @xingzhougmu,

The downloaded zip file does not include submodules thats why it is very small size.

For example **c-utility** folder under azure-iot-sdks/c/  directory  is a submodule and  if you downloaded SDK as a zip file then you need to download this submodule again from  https://github.com/Azure/azure-c-shared-utility/tree/master.

But if you use **git clone** with **--recursive**, it initialize all submodules then you dont need to download all submodules.

Is that clear?

Thanks 
Enes

**Comment by xingzhougmu** [comment]
Hi @enuysa-msft ,

Thanks for your help on this. 

And similar question can be found here. #634
