### ISSUE TITLE
How to run AzureIOT-sdk in arduino mega2560 with Ethernet shield??

### ISSUE THREAD

**Issue by Monish-Thatraju** [Azure/azure-iot-sdks#972]
Hello everyone,

I am using an Ethernet shield with ARduino Mega2560.
My requirement is to install AzureIOT sdk in Mega, and to send and receive Sensor data.
So is it possible to do this through Arduino Mega with Ethernet shield or do we have any other alternate things.
The links which i am following are
[https://github.com/Azure/azure-iot-arduino](https://github.com/Azure/azure-iot-arduino)
[https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/openwrt-arduino-yun-c.md#Step-2-PrepareDevice](https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/openwrt-arduino-yun-c.md#Step-2-PrepareDevice)

**Comment by mamokarz** [comment]
Hi Monish-Thatraju,

Arduino Mega2560 has 256K of Flash and 8K of SRAN, which is not enough to fits all you need for the Azure IoT.

Nowadays, Microsoft provides two Samples with Arduino ESP8266 and one with Arduino Cortex-M0+, you can find more information about it in the [Microsoft Azure IoT Starter Kits](https://azure.microsoft.com/en-us/develop/iot/starter-kits/).

These samples have a kit and a tutorial that will show you how to use the Azure IoT Hub to transfer data and the Azure IoT Suite to process this data to generate events. This is a good way to start.

**Comment by tameraw** [comment]
@Monish-Thatraju  - Closing issue. Please let us know if you have any further inquiries.

**Comment by Monish-Thatraju** [comment]
as of now, no queries..!! Please close the issue. Thank you
