### ISSUE TITLE
issues noticed while build this sdk

### ISSUE THREAD

**Issue by xingzhougmu** [Azure/azure-iot-sdks#975]
I followed [this link](https://github.com/Azure/azure-iot-sdks/blob/master/doc/iotcertification/iot_certification_linux_c/iot_certification_linux_c.md) to build the sdk for c on Ubuntu Virtual Machine.

I found two issues during the build process.

1. unknown type name 'time_t'
>In file included from /home/xing/azure-iot-sdks/c/iothub_client/tests/common_dev                                                                                                                                                             >ice_method_e2e/iothubclient_common_device_method_e2e.c:17:0:
>/home/xing/azure-iot-sdks/c/testtools/iothub_test/inc/iothubtest.h:30:168: error : unknown type name >‘time_t’
 >extern IOTHUB_TEST_CLIENT_RESULT IoTHubTest_ListenForEvent(IOTHUB_TEST_HANDLE d >evhubHandle, pfIoTHubMessageCallback msgCallback, size_t partitionCount, void* context, time_t >receiveTimeRangeStart, double maxDrainTimeInSeconds);

In order to resolve this issue, I add the "**include <time.h>**" to **azure-iot-sdks/c/testtools/iothub_test/inc/iothubtest.h**
```c
#ifndef IOTHUBTEST_H
#define IOTHUBTEST_H

#ifdef __cplusplus
#include <cstddef>
extern "C"
{
#else
#include <stddef.h>
#include <time.h>
#endif
```

2. the required virtual memory to complete the build process is huge. Based on my observation, it is around 28GB. Why it required this much virtual memory?
Initially, I tried with an Azure Ubuntu VM hasing 14GB RAM, but failed with the error below.
>[ 77%] Building C object >iothub_client/tests/iothubtransportamqp_ut/CMakeFiles/iothubtransportamqp_ut_exe.dir/iothubtransp>ortamqp_ut.c.o
>virtual memory exhausted: Cannot allocate memory
>make[2]: *** [iothub_client/tests/uamqp_messaging_ut/CMakeFiles/uamqp_messaging_ut_exe.dir/uamqp_messaging_>ut.c.o] Error 1
>make[1]: *** [iothub_client/tests/uamqp_messaging_ut/CMakeFiles/uamqp_messaging_ut_exe.dir/all] >Error 2
make[1]: *** Waiting for unfinished jobs....

Finally, I complete the build process with 20GB SWAP file.
>xing@ML-Learning:~ swapon -s
>Filename                                Type            Size    Used    Priority
>/swapfile                               file            20971516        24580   -1
>xing@ML-Learning:~ free -m
>             total       used       free     shared    buffers     cached
>Mem:         14023        431      13592          0          9        271
>-/+ buffers/cache:        149      13873
>Swap:        20479         23      20456

3. Build result: Three of the test cases are failed. Is this normal?
 >The following tests FAILED:
         83 - iothubclient_http_e2e (Failed)
           86 - iothubclient_mqtt_e2e (Failed)
           87 - iothubclient_mqtt_dt_e2e (Failed)
Errors while running CTest
         88 - iothubclient_mqtt_device_method_e2e (Failed)
         92 - iothubclient_amqp_e2e (Failed)
        115 - serializer_e2e (Failed)

If you required any other information, I am happy to provide.

**Comment by xingzhougmu** [comment]
Hi @markrad,

**My environment settings:**
Ubuntu 14.04 LTS (64 bit)
gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
cmake version 2.8.12.2

Regarding the virtual memory issue, can we update the document to explicitly stating customer can add --skip-unittests parameter to avoid this issue? (We do receive support tickets for this issue from our azure customers).

Cheers,
Xing

**Comment by markrad** [comment]
Hi @xingzhougmu,

Having discussed this with the product group, we plan to modify the default to **not** build the unit tests. One will have to explicitly ask for them to be built via a command line argument to build.sh. This will be completed reasonably soon.

I ran a build on my Ubuntu 14.04 machine and could not reproduce your build issue. My gcc is at 4.8.4-2ubuntu1~14.04.3 4.8.4. cmake is the same as yours. I did use the latest repro for the C code. Currently that is in a different GitHub repository though since the product group are reorganizing the repros into languages. You can find it at https://github.com/Azure/Azure-iot-sdk-c. Perhaps you could try that one and see if you still have the issue with time_t.

_Mark Radbourne MSFT_

**Comment by xingzhougmu** [comment]
Hi @markrad,

Sure. I will try the new one, and report back if I could still encounter that issue.

Cheers,
Xing

**Comment by xingzhougmu** [comment]
Hi @markrad,

Yes. The time.h issue does not occur in the latest git repository. I will close this issue. Thanks for your help!
