### ISSUE TITLE
Does this SDK run on the Adafruit Feather Huzzah with MQTT?

### ISSUE THREAD

**Issue by henrik-d** [Azure/azure-iot-sdks#977]
Hey,

the arduino port of this SDK doesn't support MQTT at the moment. Can I run this SDK on a Adafruit Feather Huzzah to **receive messages with MQTT**? The getting started guide doesn't mention receiving messages https://azure.microsoft.com/en-us/resources/samples/iot-hub-c-thingdev-getstartedkit/

**Comment by olivierbloch** [comment]
Hi @henrik-d 
We are working on the MQTT support and expect it to be available in the next few weeks. This is where the Arduino library is developed: https://github.com/azure/azure-iot-arduino

**Comment by henrik-d** [comment]
Hey @olivierbloch,
yes thanks I know ;-) But I would still be interested in the answer to my question

**Comment by olivierbloch** [comment]
The answer to the question "can you receive messages with MQTT" is no, not yet.
Now if you meant "receive messages with HTTP" then the answer is yes. And this is demonstrated in the samples in the https://github.com/azure/azure-iot-arduino repository.

**Comment by henrik-d** [comment]
Ok, but my actual question was if the **C SDK** works on Adafruit Feather Huzzah, or will just the Arduino SDK work? Sorry for the confusion.

**Comment by mamokarz** [comment]
Hi henrik-d,

Yes, we have a port of the **C SDK** for **Adafruit Huzzah**, and now it works with HTTP and MQTT. Please take a look at this [sample](https://azure.microsoft.com/en-us/resources/samples/iot-hub-c-huzzah-getstartedkit/). It provides 2 examples on how to do that, both using MQTT protocol.
