### ISSUE TITLE
[node] device method timeout param is ignored

### ISSUE THREAD

**Issue by ChristianBeier** [Azure/azure-iot-sdks#979]
Regardless of what value I set in the timeoutInSeconds method parameter I always receive a timeout after 30 seconds.
Btw: device_method_params.d.ts mentions 0 seconds as default while 30 is documented.

I tested with the example code and commented the response.send part in the simulated device.

**Comment by tameraw** [comment]
Investigating.

**Comment by anhashia** [comment]
Looking into the issue.

**Comment by anhashia** [comment]
Hi @ChristianBeier 
I was able to reproduce the issue locally.
Looks like there is new parameter name to specify timeout for method. It is called `responseTimeoutInSeconds`

As an **example**, in sample service\samples\device_method.js replace timeoutInSeconds with **responseTimeoutInSeconds**

```
var methodParams = {
  methodName: 'myMethod', 
  payload: 'myPayload',
  responseTimeoutInSeconds: 10
};
```
If myMethod is not implementation, you should see following message after 10 seconds
`Failed to invoke method 'myMethod': Timed out waiting for the response from device.`

**Comment by ChristianBeier** [comment]
Great, thank you for confirming. Seems that documentation needs an update.

**Comment by anhashia** [comment]
Hi @ChristianBeier 
Yeah, documentation will be updated to reflect the change.

**Comment by anhashia** [comment]
https://github.com/Azure/azure-iot-sdk-node/commit/c8d5bb7bf9b82caab5c48cced89be2b31e5f8766

**Comment by pierreca** [comment]
@anhashia thanks for the fix!
