### ISSUE TITLE
Minor suggestion for required strings on command line

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#98]
I appreciate this note on the Java samples page:
Note that the double quotes around each argument are required.

But I would suggest it be expanded to state:
Note that the double quotes around each argument are required, but the '{' and '}' characters should be removed.

**Comment by andrew-buckley** [comment]
Thank you @jtanner-msft, we will have a look.

**Comment by dominicbetts** [comment]
@jtanner-msft and @andrew-buckley. I've made a change to the two Java documents based on this suggestion. PR will be submitted shortly.

**Comment by tameraw** [comment]
Issue resolved. Please advise/reopen if you're still having issues. Thanks.
