### ISSUE TITLE
Device (node, mqtt) disconnects after couple of days

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdks#980]
**Platform: Linux, Nodejs 7.1, SDK v 1.1 MQTT**

Device getting disconnected is a very serious issue and can't deploy it to prod unless resolved. Only way to resolve this is to restart the device.

_**Scenario:**_ Device is connected and not getting any commands or methods from cloud for a day or two.
 It gets disconnected after 2nd day almost. `disconnect` event is not fired as well. 
**Question** Do I have to some some sort of heartbeat to let server know that device is up and running?

**Comment by bmrpatel** [comment]
may be related to #981

**Comment by bmrpatel** [comment]
I had two test devices connected for 3 days and today both of them are disconnected with the following debug log: Please note that both devices got disconnected at the same time. Hope this will help investigate this issue.

**device1**
```
Tue, 29 Nov 2016 17:44:52 GMT mqtt-common topic publish: devices/000019/messages/events/
Tue, 29 Nov 2016 17:44:52 GMT mqtt-common topic subscribe: devices/000019/messages/devicebound/#
Tue, 29 Nov 2016 17:44:52 GMT mqtt-common username: myhubendpoint.azure-devices.net/000019/DeviceClientType=azure-iot-device%2F1.1.0&api-version=2016-11-14
Tue, 29 Nov 2016 17:44:52 GMT mqtt-common uri:      mqtts://myhubendpoint.azure-devices.net
Tue, 29 Nov 2016 17:44:52 GMT mqtt-common Device is connected
Tue, 29 Nov 2016 17:44:52 GMT mqtt-common CONNACK: {"cmd":"connack","retain":false,"qos":0,"dup":false,"length":2,"topic":null,"payload":null,"sessionPresent":true,"returnCode":0}
Tue, 29 Nov 2016 18:06:44 GMT mqtt-common Device connection to the server has been closed

```

**device 2**
```
Tue, 29 Nov 2016 16:13:54 GMT mqtt-common uri:      mqtts://myhubendpoint.azure-devices.net
Tue, 29 Nov 2016 16:13:55 GMT mqtt-common Device is connected
Tue, 29 Nov 2016 16:13:55 GMT mqtt-common CONNACK: {"cmd":"connack","retain":false,"qos":0,"dup":false,"length":2,"topic":null,"payload":null,"sessionPresent":true,"returnCode":0}
Tue, 29 Nov 2016 16:58:55 GMT mqtt-common topic publish: devices/001262/messages/events/
Tue, 29 Nov 2016 16:58:55 GMT mqtt-common topic subscribe: devices/001262/messages/devicebound/#
Tue, 29 Nov 2016 16:58:55 GMT mqtt-common username: myhubendpoint.azure-devices.net/001262/DeviceClientType=azure-iot-device%2F1.1.0&api-version=2016-11-14
Tue, 29 Nov 2016 16:58:55 GMT mqtt-common uri:      mqtts://myhubendpoint.azure-devices.net
Tue, 29 Nov 2016 16:58:55 GMT mqtt-common Device is connected
Tue, 29 Nov 2016 16:58:55 GMT mqtt-common CONNACK: {"cmd":"connack","retain":false,"qos":0,"dup":false,"length":2,"topic":null,"payload":null,"sessionPresent":true,"returnCode":0}
Tue, 29 Nov 2016 17:43:56 GMT mqtt-common topic publish: devices/001262/messages/events/
Tue, 29 Nov 2016 17:43:56 GMT mqtt-common topic subscribe: devices/001262/messages/devicebound/#
Tue, 29 Nov 2016 17:43:56 GMT mqtt-common username: myhubendpoint.azure-devices.net/001262/DeviceClientType=azure-iot-device%2F1.1.0&api-version=2016-11-14
Tue, 29 Nov 2016 17:43:56 GMT mqtt-common uri:      mqtts://myhubendpoint.azure-devices.net
Tue, 29 Nov 2016 17:43:56 GMT mqtt-common Device is connected
Tue, 29 Nov 2016 17:43:56 GMT mqtt-common CONNACK: {"cmd":"connack","retain":false,"qos":0,"dup":false,"length":2,"topic":null,"payload":null,"sessionPresent":true,"returnCode":0}
Tue, 29 Nov 2016 18:06:47 GMT mqtt-common Device connection to the server has been closed
```

**Comment by sergaz-msft** [comment]
Hi @bmrpatel , thank you for letting us know about this. I will try to reproduce the same on my Environment. Can you please clarify the following?

"Scenario: Device is connected and not getting any commands or methods from cloud for a day or two.
It gets disconnected after 2nd day almost. disconnect event is not fired as well."

This means that device is not receiving Cloud-to-device messages and not sending device-to-Cloud messages during 2 days correct?

Thanks

**Comment by bmrpatel** [comment]
As far as I can find out, it has been disconnecting with the debug message: 
`mqtt-common Device connection to the server has been closed`

This happens when device is busy processing some other long task. So my comments about 2 days may be irrelevant. It may happened to be after 2 days at that time, but it can happen right away if I start he lengthy task.


**Off topic question:** I have also notices (very rarely) that **device explorer** tool is not showing all of my devices on the Management tab. I also can't connect to cloud from device at that time. It seems as if IOT Hub service might be down at that time. Is it possible?

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-node#12
