### ISSUE TITLE
Device (node, mqtt) disconnects during direct method execution

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdks#981]
**Platform: Linux, Nodejs 7.1, SDK v 1.1 MQTT**

_**Scenario:**_ Device is connected and method gets invoked. Direct Method is executed. I am using the sample code with the following changes to test async execution. Using DeviceExplorer to invoke method. As soon as `onWriteLine` is called, it gets disconnected and get the error on the DeviceExplorer side. 

```
client.onDeviceMethod('writeLine', (req, res) => {
            console.log('writeLine method req received!');
            setTimeout(() => {
                onWriteLine(req, res)
            }, 1000)
        });
``` 
![image](https://cloud.githubusercontent.com/assets/5115789/20524367/418c6542-b088-11e6-9e2c-29ddab206462.png)

may be related to #980

**Comment by bmrpatel** [comment]
**DEBUG Output**
![image](https://cloud.githubusercontent.com/assets/5115789/20525227/7a89142c-b08c-11e6-9905-40ea49eaa0fd.png)

**Comment by bmrpatel** [comment]
I noticed the pattern and I see that it disconnects when it happens. I am making a web request call to get some data which is completely unrelated to the iot client. When this request is taking long time to receive a response, it disconnects and following debug output is produced. I am guessing mqtt is doing some health check in background. This background check may be timing out and hence disconnecting since other task is taking long time. Please let me know if you need help reproducing this issue.

` mqtt-common Device connection to the server has been closed`

**Comment by bmrpatel** [comment]
I get the following error:
![image](https://cloud.githubusercontent.com/assets/5115789/20607654/2ba8ab34-b248-11e6-9889-2022fab57e85.png)

**Comment by tameraw** [comment]
Investigating.

**Comment by bmrpatel** [comment]
**UPDATE:** I get the same error when I set a break point to debug after it connects to the hub. I try to evaluate for few seconds to minute and see the same error in console. 

It is weird that it is not calling/emitting disconnect event on the client. If I get that then at least I can handle that and try to connect again. What is the policy to handle this kind of close events?

I am wondering if this is deployed to production by anyone, are they not seeing this issue? Or it is being handled and I am unaware of the way to do that! 

Thanks a lot..

**Comment by bmrpatel** [comment]
@pierreca, @tameraw  I ran another test. I modified one of the device to use AMQP (2 line change). Otherwise both devices are running the same program. MQTT device disconnected the same day after couple of hours and AMQP device is still connected after 3 days and responding from cloud.

**Comment by sergaz-msft** [comment]
Hi @bmrpatel thanks for the details. I will try to reproduce the same on my Environment. I am also working on #980 so we will check if both issues are related or not.

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-node#11
