### ISSUE TITLE
[Java SDK Client] Error when build for Android

### ISSUE THREAD

**Issue by kevin-ledinh** [Azure/azure-iot-sdks#983]
Hi all,

I've been using IoT Hub for a while but wanting to update my current version (1.0.11) so I created a brand new project with the intention of using the maven build process in the instruction page.

I've clone the Github project and was able to build .jar file using maven install. I used the package with all the dependencies in my Android studio project. 

The project build return the following error:

> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$2) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is *not* an inner class.
> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$1) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is *not* an inner class.
> Error:Error converting bytecode to dex:
> Cause: com.android.dex.DexException: Multiple dex files define Lorg/apache/commons/codec/Decoder;
> :app:transformClassesWithDexForDebug FAILED
> Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_11\bin\java.exe'' finished with non-zero exit value 2

Has anyone encounter this error? Any help is appreciated.

Thanks,

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Looking into the issue.

**Comment by anhashia** [comment]
Hi @kevin-ledinh 
You can try with Android sample for reference. The sample is located at  java\device\samples\android-sample 
https://github.com/Azure/azure-iot-sdk-java/tree/master/device/samples/android-sample

**Update** 
java\device\samples\android-sample\app\build.gradle (**build.gradle** file)  to point to the latest version of available client SDK.

**Example**
````
dependencies {
    // Remote binary dependency
    compile 'com.microsoft.azure.iothub-java-client:iothub-java-device-client:1.0.16'
 }
````

**Comment by kevin-ledinh** [comment]
Hi @anhashia,

I am able to use remote repo ok, no problem. 

The problem only arises when I try to manually compile the IoT Hub SDK.

Best wishes,

**Comment by anhashia** [comment]
Hi @kevin-ledinh 
https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/java-devbox-setup.md covers how to build client SDK `iothub-java-client`

Run `java\device>mvn install`
This should build client SDK under device\iothub-java-client\target

**Comment by anhashia** [comment]
Closing this. Please re-activate if you have any further questions on this. Thanks !
