### ISSUE TITLE
Android Java SDK  - IotHubEventCallback not called after sendEventAsync

### ISSUE THREAD

**Issue by kevin-ledinh** [Azure/azure-iot-sdks#986]
Hi Azure team,

Please advise the following problem when I run the IoT Hub Java SDK to send msg iva AMQP on an Android dev board.

In my first set up, I've been using IoT Hub SDK 1.0.11 and proton-j-azure-iot-0.12.2 (downloaded from Maven repo: https://mvnrepository.com/artifact/com.microsoft.azure.iot/proton-j-azure-iot/0.12.2). With this set up, I am able to send messages to the Could (via sendEventAsync) and receive acknowledgement (via IotHubEventCallback).

In the second set up, a compiled version of the IoT Hub SDK 1.0.15 is used. It is pulled from Maven Repo. I've also checked that the connection string is valid. However, the behaviour is quite different as follows:

- It takes three minutes for the DeviceClient.open() to return. Looking in AmqpIotHubConnection.java, openLock.waitLock(maxWaitTimeForOpeningClosingConnection) is where the wait is. Is this necessary?

- Acknowledgement are not received on the device any more. The implementation of IotHubEventCallback is not called. I used both break points and printing out messages to ADB to confirm this and neither happen. Could you advise on how to investigate and fix this?

Any help appreciated. Best wishes,

Kevin

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Looking into the issue.

**Comment by anhashia** [comment]
Hi @kevin-ledinh 
I was able to locally **reproduce** the issue using ``iothub-java-device-client:1.0.16``  in Android emulator using **AMQPS** protocol.

This issue looks specific to Android and seems to be coming when accessing certificate and needs further investigation. The issue doesn't happen on Windows 10 PC using the same the client library version.

Also, issue seems to be **regression** and doesn't happen if using older version of ``iothub-java-device-client:1.0.9`` with AMQPS protocol in Android application. The issue also doesn't happen with MQTT protocol in Android application using latest ``iothub-java-device-client:1.0.16``

**Comment by anhashia** [comment]
@814

**Comment by kevin-ledinh** [comment]
Hi @anhashia,

Would you be able to update me on this issue?

Best wishes,
Kevin

**Comment by anhashia** [comment]
Hi @kevin-ledinh 
This is coming from way certificate is being handled. Product Backlog Item (PBI) has been created  to investigate this further. More details on the root cause is in my **previous** comment above provided 8 days ago .

**Comment by anhashia** [comment]
Hi @kevin-ledinh 

Just wanted to add that one possible **workaround** would be to use **MQTT** protocol.  Client library doesn't have this issue with MQTT protocol.  Android sample https://github.com/Azure/azure-iot-sdk-java/tree/master/device/samples/android-sample  uses that as default on both send and receive side.

Android sample has been updated to use  latest available `iothub-java-device-client:1.0.16`  client library.
https://github.com/Azure/azure-iot-sdk-java/blob/develop/device/samples/android-sample/app/build.gradle

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-java#21
