### ISSUE TITLE
[Java] C2D Feedback receiver doesn't time out

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdks#989]
A request for feedback doesn't timeout, even if a timeout setting is passed to `receive()`/`receiveAsync()` methods.

Example code:
1. Sync: https://gist.github.com/dluc/7e02947720a1b86d03ab42c5801bd208
2. Async: https://gist.github.com/dluc/a4b7f27c586b2ccadffd422c8dfd0d70

**Comment by zolvarga** [comment]
Hi Devis,

Thanks for reporting this.
We are going to take a look at it.

Thanks,
Zoltan

**Comment by tameraw** [comment]
Possibly related to #968 . We'll be investigating.

**Comment by anhashia** [comment]
Being tracked with Product Backlog Item (PBI)

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-java#18
