### ISSUE TITLE
This link leads to a 404 not found error from the Java samples page:

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#99]
To learn how to create a Java application that communicates with an IoT hub from scratch, see How to write an Azure IoT client application from scratch with Java on Windows.

**Comment by dominicbetts** [comment]
@jtanner-msft thanks for pointing this out. PR will be submitted shortly to fix this issue.

**Comment by tameraw** [comment]
Issue resolved. Please advise/reopen if you're still having issues. Thanks.
