### ISSUE TITLE
[Java] No error when sending more than 50 messages (to the same device)

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdks#997]
The [documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging#cloud-to-device-messages) mentions a limit on the number of messages per device that can be enqueued:

> Each device queue holds at most 50 cloud-to-device messages. Trying to send more messages to the same device results in an error

When an application sends more than 50 C2D messages though, no error occurs. The code below for instance, sends **1000 messages** to the same device, without throwing any exception.

1. Are the messages discarded without exceptions after the 50th, or are they actually enqueued (in which case the documentation doesn't reflect the service behavior) ? 
2. If "50" is a soft limit, what is the actual hard limit and what exception should one expect ?

Thanks
Devis

Code:

```java
/* 
    Dependencies:
    iothub-java-service-client  1.0.10
    iothub-java-device-client   1.0.15
*/

import com.microsoft.azure.iot.service.sdk.DeliveryAcknowledgement;
import com.microsoft.azure.iot.service.sdk.IotHubServiceClientProtocol;
import com.microsoft.azure.iot.service.sdk.Message;
import com.microsoft.azure.iot.service.sdk.ServiceClient;

import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.UUID;

public class Test
{
    static String hub = System.getenv("SDK_HUB_NAME");
    static String serviceKey = System.getenv("SDK_SERVICE_KEY");
    static String device = System.getenv("SDK_DEVICE_ID");

    static ServiceClient client;

    public static void main(String[] args) throws Exception
    {
        log("Creating service client");
        String cs = "HostName=" + hub + ".azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=" + serviceKey;
        client = ServiceClient.createFromConnectionString(cs, IotHubServiceClientProtocol.AMQPS);

        log("Open service client connection");
        client.open();

        for (int i = 0; i < 1000; i++) send(i);

        log("Close service client connection");
        client.close();

        log("Done");
    }

    static void send(Integer i) throws Exception
    {
        Message msg = new Message("test".getBytes(StandardCharsets.UTF_8));
        msg.setTo(device);
        msg.setDeliveryAcknowledgement(DeliveryAcknowledgement.Full);
        msg.setExpiryTimeUtc(Date.from(Instant.now().plusSeconds(3600)));
        msg.setMessageId(UUID.randomUUID().toString());

        log("Sending msg #" + i + ", To: '" + device + "', ID: " + msg.getMessageId() + ", Expire: " + msg.getExpiryTimeUtc());
        client.send(device, msg);
    }

    static void log(String text)
    {
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss.SSS");
        System.out.println("[" + dateFormat.format(new Date()) + "] " + text);
    }
}
```

**Comment by dluc** [comment]
Log from the example above: https://gist.github.com/dluc/e934374b397457ee870373261af52fac

**Comment by jtanner-msft** [comment]
Hi @dluc ,

  Thank you for raising this question.  I'll check into it and let you know if the 50 limit is just a suggested limit, or it's  hard limit that we're not respecting properly.
  Thanks,

**Comment by jtanner-msft** [comment]
Hi @dluc,

  I’ve discussed this with the product team and they have confirmed that there is a 50 message queue limit for Cloud 2 Device messages.  Unfortunately there is a problem with the Java SDK where it just continues to say that the message has been accepted even if the queue is already full.  My understanding is that this is a known problem that they are looking to address in the near future.  Please talk to Elio of you have more questions or need internal specifics.

  I’ll close this now as the work item is with the product team.

Thanks,

**Comment by dluc** [comment]
Could we keep this open until fixed?

**Comment by tameraw** [comment]
Reopening this issue as it is an issue with the Java Service SDK

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-java#23
