### ISSUE TITLE
Cannot read property 'primaryKey' of undefined

### ISSUE THREAD

**Issue by robert4os** [Azure/azure-iot-sdks#998]
Hi,

I was following this tutorial: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-device-management-get-started

When calling 
iothub-explorer create myDeviceId --connection-string
... I get the error message below.

Thank you for your help,

Robert

Error:

AppData\Roaming\npm\node_modules\iothub-explorer\common.js:22
  if (deviceInfo.authentication.SymmetricKey.primaryKey) {
                                            ^
TypeError: Cannot read property 'primaryKey' of undefined
    at createDeviceConnectionString (C:\Users\user\AppData\Roaming\npm\node_modules\iothub-explorer\common.js:22:45)
    at printDevice (C:\Users\user\AppData\Roaming\npm\node_modules\iothub-explorer\common.js:135:31)
    at C:\Users\user\AppData\Roaming\npm\node_modules\iothub-explorer\iothub-explorer-create.js:101:7
    at C:\Users\user\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\azure-iothub\lib\registry.js:139:7
    at C:\Users\user\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\azure-iothub\lib\rest_api_client.:109:7
    at IncomingMessage.onResponseEnd (C:\Users\user\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\azure-iothub\node_modules\azure-iot-http-base\lib\http.js:73:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

I used the following installation/version:
	

$ npm install -g iothub-explorer@latest
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
iothub-explorer@1.1.0
├── uuid@2.0.3
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── colors-tmpl@1.0.0 (colors@1.0.3)
├── pem@1.9.2 (os-tmpdir@1.0.2, which@1.2.12)
├── azure-iot-device-http@1.1.0 (node-crontab@0.0.8, azure-iot-http-base@1.1.0)
├── bluebird@3.4.6
├── azure-iot-common@1.1.0 (crypto@0.0.3)
├── prettyjson@1.2.0 (colors@1.1.2, minimist@1.2.0)
├── azure-iot-device-mqtt@1.1.0 (debug@2.3.3, es5-shim@4.5.9, mqtt@1.14.1)
├── azure-iot-device@1.1.0 (azure-iot-http-base@1.1.0, debug@2.3.3, traverse@0.6.6, es5-shim@4.5.9, machina@2.0.0, lodash@4.17.2)
├── azure-iothub@1.1.0 (azure-iot-http-base@1.1.0, azure-iot-amqp-base@1.1.0, lodash@4.17.2)
├── azure-event-hubs@0.0.3 (amqp10@3.2.2)
├── azure-iot-device-amqp@1.1.0 (azure-iot-amqp-base@1.1.0)
└── azure-storage@1.3.2 (extend@1.2.1, xmlbuilder@0.4.3, browserify-mime@1.2.9, node-uuid@1.4.7, validator@3.22.2, underscore@1.4.4, json-edm-parser@0.1.2, readable-stream@2.0.6, xml2js@0.2.7, request@2.74.0)

$ npm install -g azure-iot-device@latest
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
azure-iot-device@1.1.0
├── azure-iot-http-base@1.1.0
├── traverse@0.6.6
├── debug@2.3.3 (ms@0.7.2)
├── es5-shim@4.5.9
├── azure-iot-common@1.1.0 (crypto@0.0.3)
├── machina@2.0.0 (lodash@3.10.1)
├── azure-storage@1.3.2 (extend@1.2.1, xmlbuilder@0.4.3, browserify-mime@1.2.9, node-uuid@1.4.7, validator@3.22.2, underscore@1.4.4, json-edm-parser@0.1.2, readable-stream@2.0.6, xml2js@0.2.7, request@2.74.0)
└── lodash@4.17.2

**Comment by sebastian-azeti** [comment]
I got exactly the same. Mac OSX Sierra and node 6.9.1

**Comment by BertKleewein** [comment]
We have a fix in progress and should be releasing it to NPM within the next few days.

**Comment by pierreca** [comment]
Packages have been released and the issue should be fixed. (packages version: 1.1.1)
